upup/pkg/fi/cloudup/apply_cluster.go

We break the hard-link with the ApplyClusterCmd, the code is
over-coupled and ApplyClusterCmd is too big.

Refactor nodeUpConfigBuilder to be standalone

---

tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml
tests/integration/update_cluster/launch_templates/cloudformation.json.extracted.yaml
tests/integration/update_cluster/launch_templates/data/aws_launch_configuration_master-us-test-1a.masters.launchtemplates.example.com_user_data
tests/integration/update_cluster/launch_templates/data/aws_launch_configuration_master-us-test-1b.masters.launchtemplates.example.com_user_data
tests/integration/update_cluster/launch_templates/data/aws_launch_configuration_master-us-test-1c.masters.launchtemplates.example.com_user_data
tests/integration/update_cluster/launch_templates/data/aws_launch_configuration_nodes.launchtemplates.example.com_user_data
tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
tests/integration/update_cluster/mixed_instances/data/aws_launch_template_master-us-test-1a.masters.mixedinstances.example.com_user_data
tests/integration/update_cluster/mixed_instances/data/aws_launch_template_master-us-test-1b.masters.mixedinstances.example.com_user_data
tests/integration/update_cluster/mixed_instances/data/aws_launch_template_master-us-test-1c.masters.mixedinstances.example.com_user_data
tests/integration/update_cluster/mixed_instances/data/aws_launch_template_nodes.mixedinstances.example.com_user_data
tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
tests/integration/update_cluster/mixed_instances_spot/data/aws_launch_template_master-us-test-1a.masters.mixedinstances.example.com_user_data
tests/integration/update_cluster/mixed_instances_spot/data/aws_launch_template_master-us-test-1b.masters.mixedinstances.example.com_user_data
tests/integration/update_cluster/mixed_instances_spot/data/aws_launch_template_master-us-test-1c.masters.mixedinstances.example.com_user_data
tests/integration/update_cluster/mixed_instances_spot/data/aws_launch_template_nodes.mixedinstances.example.com_user_data
tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
tests/integration/update_cluster/privatecalico/data/aws_launch_template_master-us-test-1a.masters.privatecalico.example.com_user_data
tests/integration/update_cluster/privatecalico/data/aws_launch_template_nodes.privatecalico.example.com_user_data
upup/pkg/fi/cloudup/networking.go
upup/pkg/fi/cloudup/networking_test.go

https://github.com/containernetworking/plugins/releases/tag/v0.8.7
xRef: https://github.com/kubernetes/kubernetes/pull/94367

Update CNI plugins to v0.8.7

---

pkg/model/gcemodel/autoscalinggroup.go

Clearer, and for future cluster-api support.

Refactor GCE InstanceTemplate

---

Makefile
docs/release-process.md
pkg/model/components/kubeapiserver/model.go
pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
upup/models/bindata.go
upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
upup/pkg/fi/cloudup/urls_test.go
version.go

Release 1.19.0-beta.3

---

tests/e2e/kubetest2-kops/deployer/common.go

To run directly, I need to specify AWS_PROFILE.

kubetest2: Pass through some AWS env vars

---

OWNERS

Cherry pick of #10466 #10542 on release-1.19.
#10466: Remove gjtempleton as reviewer
#10542: Promote Ole Markus to approvers list

Automated cherry pick of #10466: Remove gjtempleton as reviewer #10542: Promote Ole Markus to approvers list

---

WORKSPACE

Update Go to v1.15.6 for 1.19

---

upup/models/bindata.go
upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml

https://github.com/weaveworks/weave/releases/tag/v2.8.0

Update Weave to v2.8.0

---

tests/e2e/scenarios/upgrade/run-test

fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-misc-upgrade/1352280388818440192#1:build-log.txt%3A74442

Ensure SpecOverrideFlag is set in upgrade test

---

tests/e2e/scenarios/upgrade/run-test

fixes https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-misc-upgrade/1352341291798630400

Fix unbound variable in upgrade scenario script

---

cloudmock/aws/mockec2/launch_templates.go
cloudmock/aws/mockec2/volumes.go
pkg/model/awsmodel/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go

Backport gp3 volumes fixes

---

docs/iam_roles.md

Added kops version information for external policies support.

Add minimum version info for External Policies

---

docs/cluster_spec.md

Fix cluster_spec.md indentation

---

channels/alpha
channels/stable
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

Bump Ubuntu images for AWS and GCE

---

docs/releases/1.19-NOTES.md

Including a note about containerd + kubenet/kopeio/gce/external
networking.

Release notes for 1.19.0

---

upup/pkg/fi/files.go

Cherry pick of #10581 on release-1.19.
#10581: Allow nodeup (and others) to replace in-use files

Automated cherry pick of #10581: Allow nodeup (and others) to replace in-use files

---

pkg/model/master_volumes.go

Fix bug preventing tasks using gp2

---

upup/models/bindata.go
upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml

Cherry pick of #10604 #10698 on release-1.19.
#10604: Update Weave to v2.8.0
#10698: Update Weave to v2.8.1
Ref: https://github.com/kubernetes/kops/issues/10693

Automated cherry pick of #10604: Update Weave to v2.8.0 #10698: Update Weave to v2.8.1

---

upup/models/bindata.go
upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml

https://github.com/weaveworks/weave/releases/tag/v2.8.1
Fixes: https://github.com/kubernetes/kops/issues/10693

Update Weave to v2.8.1

---

tests/e2e/scenarios/upgrade/run-test

Testing for https://github.com/kubernetes/kops/issues/10704

Update upgrade test to use 1.18->1.19

---

channels/alpha

To pick up the sudo fixes, also addresses some problems with docker
preinstallation.
Issue #10122

alpha channel: Update older images

---

Makefile
pkg/model/components/kubeapiserver/model.go
pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
upup/models/bindata.go
upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
upup/pkg/fi/cloudup/urls_test.go
version.go

Release 1.20.0-alpha.2

---

pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
upup/pkg/fi/fitasks/managedfile.go

A prereq to uploading JWKS to public store.

Add support for creating world-readable managedFiles

---

upup/models/bindata.go
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

https://docs.projectcalico.org/archive/v3.17/release-notes/

Update Calico to v3.17.2

---

upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go

Quick hack until @liranp can fix it properly.
Ref: https://github.com/kubernetes/kops/pull/10679#issuecomment-769701745
/cc @rifelpet @liranp

Fix LaunchSpec TF output

---

tests/e2e/pkg/tester/tester.go

This argument was required for the tests to pass prior to 1.18, so we
should still pass it if we want these tests to pass.
We can infer it from kubeconfig (that is the fix that was introduced in 1.18)

kubetest2: Add --host argument

---

upup/models/bindata.go
upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

This PR upgrades the Ocean Controller to 1.0.72.

Spotinst: Bump the Ocean Controller to 1.0.72

---

cmd/kops/delete_instance.go

Just a small copy/paste error that needs fixing.

Fix kdi 'must specify' error

---

Makefile
pkg/model/components/kubeapiserver/model.go
pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
upup/models/bindata.go
upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
upup/pkg/fi/cloudup/urls_test.go
version.go

Release 1.21.0-alpha.1

---

.github/workflows/main.yml
WORKSPACE

https://github.com/golang/go/issues?q=milestone%3AGo1.15.8+label%3ACherryPickApproved

Update Go to v1.15.8

---

upup/models/bindata.go
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

#10633 didn't work as expected, this is another attempt to work around https://github.com/projectcalico/calico/issues/3751.

Add liveness probe for calico-kube-controllers

---

docs/releases/1.19-NOTES.md

Add note about remote identities

---

pkg/apis/kops/validation/aws.go
pkg/testutils/integrationtestharness.go
tests/integration/update_cluster/complex/instancegroup.nodes.overrides.txt
upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go

Improving things a bit over #10747.

Improve machine type and image validation

---

upup/pkg/fi/cloudup/azuretasks/vmscaleset.go

I missed one of the null pointers but I fixed it in this pr. 
*e.LoadBalancer.Name is null pointer but i've moved it inside a check for nil.

fix loadBalancerID null pointer

---

Makefile
pkg/model/components/kubeapiserver/model.go
pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
upup/models/bindata.go
upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
upup/pkg/fi/cloudup/urls_test.go
version.go

Release 1.20.0-beta.1

---

docs/release-process.md
docs/releases/1.20-NOTES.md

Release notes for 1.20.0-beta.1

---

pkg/model/iam.go
upup/pkg/fi/cloudup/awstasks/iamrolepolicy.go

Sort external policies when checking for changes

---

pkg/model/iam.go
upup/pkg/fi/cloudup/awstasks/iamrolepolicy.go

Cherry pick of #10940 on release-1.20.
#10940: Sort external policies when checking for changes

Automated cherry pick of #10940: Sort external policies when checking for changes

---

upup/models/bindata.go
upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template

gce doesn't suffix the IG names with ClusterName

---

upup/models/bindata.go
upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

This PR upgrades the Ocean Controller to 1.0.73.

Spotinst: Bump the Ocean Controller to 1.0.73

---

upup/models/bindata.go
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template

Fixes #10936
xRef https://github.com/cilium/cilium/pull/13369
/milestone v1.19

Add explicit RBAC permissions for finalizers subresources

---

k8s/crds/kops.k8s.io_instancegroups.yaml
pkg/apis/kops/instancegroup.go
pkg/apis/kops/v1alpha2/instancegroup.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/validation/aws.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/awsmodel/autoscalinggroup.go
tests/integration/update_cluster/complex/cloudformation.json
tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
tests/integration/update_cluster/complex/in-v1alpha2.yaml
tests/integration/update_cluster/complex/instancegroup.nodes.overrides.txt
tests/integration/update_cluster/complex/kubernetes.tf
upup/pkg/fi/cloudup/awstasks/launchtemplate.go
upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go
upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go

Add support for CPU Credits on AWS t2 and t3 instance families

---

tests/integration/update_cluster/existing_iam/kubernetes.tf
tests/integration/update_cluster/ha/kubernetes.tf
tests/integration/update_cluster/launch_templates/kubernetes.tf
tests/integration/update_cluster/mixed_instances/kubernetes.tf
tests/integration/update_cluster/mixed_instances_spot/kubernetes.tf
upup/pkg/fi/cloudup/terraform/target_hcl2.go
upup/pkg/fi/cloudup/terraform/target_hcl2_test.go
upup/pkg/fi/cloudup/terraform/target_json.go

Signed-off-by: mmerrill3 <michael.merrill@vonage.com>
- fix for #10786 removing duplicated values in local and output variables for terraform

Removing duplicate local and output values in terraform(#10786)

---

pkg/model/spotinstmodel/instance_group.go

Cherry pick of #10630 on release-1.19.
#10630: fix(spot/ocean): avoid unnecessary duplication of tasks

Automated cherry pick of #10630: fix(spot/ocean): avoid unnecessary duplication of tasks

---

docs/releases/1.21-NOTES.md

Add to 1.21 release notes

---

dns-controller/pkg/dns/dnscontroller.go

Cherry pick of #10996 on release-1.20.
#10996: Use exponential backoff for DNS updates

Automated cherry pick of #10996: Use exponential backoff for DNS updates

---

upup/models/bindata.go
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

https://docs.projectcalico.org/archive/v3.18/release-notes/
/cc @rifelpet

Update Calico to v3.18.1

---

nodeup/pkg/model/docker_test.go
pkg/apis/kops/dockerconfig.go
pkg/apis/kops/v1alpha2/dockerconfig.go

Fixes: https://github.com/kubernetes/kops/issues/11024

Fix rendering of multiple Docker insecure registries

---

.github/workflows/main.yml
WORKSPACE

/cc @rifelpet @olemarkus @bmelbourne

Update Go to v1.16.2

---

hack/verify-terraform.sh

Update Terraform Docker image to **v0.14.8**.
N/A
None

Update Terraform to v0.14.8

---

pkg/apis/kops/validation/aws.go
pkg/apis/kops/validation/aws_test.go
upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go

Cherry pick of #11043 on release-1.20.
#11043: Create an environment file for kops-configuration systemd

Automated cherry pick of #11043: Improve instance type validation error message

---

docs/releases/1.18-NOTES.md
docs/releases/1.19-NOTES.md

correct a word for readme

---

Makefile

Leftover from #11041 
/cc @rifelpet

Install bazelisk before pushing images

---

tests/e2e/kubetest2-kops/deployer/deployer.go

fixes this failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-gce-kubetest2/1372953020580499456

Kubetest2 - initialize boskos heartbeat channel

---

tests/e2e/kubetest2-kops/deployer/up.go

Some of the "beforeSuite" tests are failing because the e2e.test binary isn't resolving the API DNS.
This extends the validation time and also adds a sleep to wait for any negative TTLs to expire.
example failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-scenario-terraform/1370951323993772032

Kubetest2 - add more validation time for --target terraform

---

upup/models/bindata.go
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.7.10

Upgrade AWS CNI to version 1.7.10

---

pkg/model/iam/subject.go

I left off the publicDataStore (must pass --overwrite on create, I
believe), and the error message was a type-cast failure.

Improve error messages around PublicJWKS

---

cmd/kops/integration_test.go
pkg/apis/kops/validation/BUILD.bazel
pkg/apis/kops/validation/legacy.go
pkg/model/iam/subject.go
tests/integration/update_cluster/public-jwks/data/aws_iam_role_dns-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/public-jwks/data/aws_iam_role_policy_masters.minimal.example.com_policy
tests/integration/update_cluster/public-jwks/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/public-jwks/in-v1alpha2.yaml
tests/integration/update_cluster/public-jwks/kubernetes.tf
upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/cluster.yaml
upup/pkg/fi/fitasks/managedfile.go

We removed them from #10756, but they can be re-added.

Re-add integration tests for jwks

---

dns-controller/README.md
dns-controller/pkg/watchers/BUILD.bazel
dns-controller/pkg/watchers/node.go
dns-controller/pkg/watchers/pod_test.go
dns-controller/pkg/watchers/testhelpers.go

My original intention was to try to correctly document how dns-controller worked. I had to test some code to check the actual behaviour, so may as well commit those too.
Ref #11055

Dns controller fixes

---

docs/values.md
mkdocs.yml

As discussed in #10672, we are maintaining the BLM statement on a page
dedicated to our values.
Additional values mirror the kubernetes project values.  We can
document additional values by agreement in office hours.

Add values page

---

pkg/apis/kops/validation/validation.go
pkg/apis/kops/validation/validation_test.go

Cherry pick of #11127 on release-1.20.
#11127: Validate that kube-apiserver has the necessary authz modes

Automated cherry pick of #11127: Validate that kube-apiserver has the necessary authz modes

---

pkg/model/domodel/droplets.go

Cherry pick of #11102 on release-1.20.
#11102: Fix DO Tag issue

Automated cherry pick of #11102: Fix DO Tag issue

---

protokube/cmd/protokube/main.go

internalIP will be nil as it has just been declared just above. We can remove the nil checks.

minor protokube code clean up

---

docs/addons.md

fixs  the wrong lint in addons.md

fix the mistake link in addons.md

---

Makefile
cloudbuild.yaml

Aiming to create a "chain of trust"; from code to promotion PR.
Ideally we would get the promotion PRs output here, but we can start
by outputing the hashes needed.

cloudbuild: capture some hashes

---

upup/pkg/fi/cloudup/apply_cluster.go

Sideload images when we also do this for the other roles.

Side load images also on apiserver

---

upup/models/bindata.go
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder.go

Fixes: https://github.com/kubernetes/kops/issues/10974

Remove Calico bgppeer KeepOriginalNextHop default

---

docs/tutorial/working-with-instancegroups.md

Update IG tutorial for per-AZ node groups

---

tests/e2e/kubetest2-kops/aws/zones.go

xRef: https://github.com/kubernetes/k8s.io/issues/1921
xRef: https://github.com/kubernetes/test-infra/issues/21817
/cc @rifelpet

Run tests only in zones with increased limits

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/v1alpha2/networking.go

Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

Fix golint issue caused by typo

---

pkg/apis/kops/v1alpha2/instancegroup.go

Remove unused constants

---

channels/alpha
channels/stable
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

/cc @MoShitrit @olemarkus @rifelpet

Update kOps recommended versions and images

---

tests/e2e/kubetest2-kops/aws/zones.go

Run tests in all regions with increased limits

---

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template

Fixes https://github.com/kubernetes/kops/issues/11269

Fix cilium template scoping typo

---

upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go

This PR resolves issue #10908 by adding missing nil checks.

Spotinst: Prevent nil pointer dereference

---

upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go

Cherry pick of #11289 on release-1.20.
#11289: fix(spot/elastigroup): prevent nil pointer dereference

Automated cherry pick of #11289: fix(spot/elastigroup): prevent nil pointer dereference

---

upup/pkg/fi/cloudup/awstasks/warmpool.go

Make warm pool no ASG found error retryable

---

upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
upup/pkg/fi/dryrun_target.go

Cherry pick of #11255 on release-1.19.
#11255: Make it possible to detect field changes when

Automated cherry pick of #11255: Make it possible to detect field changes when

---

docs/addons.md
docs/releases/1.21-NOTES.md

fixes https://github.com/kubernetes/kops/issues/11299

Document the newly required SQS permissions for NTH

---

upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template

Updates the NTH addon to the latest release version

bump NTH to 1.13.0

---

protokube/pkg/gossip/openstack/seeds.go

Cherry pick of #11305 on release-1.19.
#11305: Update seeds.go

Automated cherry pick of #11305: Update seeds.go

---

protokube/pkg/gossip/openstack/seeds.go

Filter servers using cluster name in tags

---

channels/alpha
channels/stable
pkg/apis/kops/channel.go
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

.. and bump the recommended image version.

Promote channel alpha to stable

---

upup/models/bindata.go
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder.go

https://docs.projectcalico.org/archive/v3.17/release-notes/#v3174

Update Calico to v3.17.4 for kOps 1.19

---

util/pkg/distributions/distributions.go
util/pkg/distributions/identify.go
util/pkg/distributions/identify_test.go
util/pkg/distributions/tests/ubuntu2104/etc/os-release

Add **unofficial** support for Ubuntu 21.04.
https://ubuntu.com/blog/ubuntu-21-04-is-here

Recognize Ubuntu 21.04

---

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template

This completes #11333. I missed these updating these other template
files when I submitted #11333.

Add `enable-host-reachable-services` to 1.8 and generic cilium.

---

upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

https://docs.projectcalico.org/archive/v3.18/release-notes/#v3182

Update Calico to v3.18.2

---

tests/e2e/scenarios/upgrade/run-test

followup to https://github.com/kubernetes/kops/pull/11338
fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-misc-upgrade/1387358718366060544

Fix upgrade scenario kubetest2 install

---

upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

https://docs.projectcalico.org/archive/v3.19/release-notes/

Update Calico to v3.19.0

---

upup/pkg/fi/fitasks/keypair.go
upup/pkg/fi/vfs_castore.go

Fix upgrade of service-account key

---

upup/models/bindata.go
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml

Don't try to mount hubble TLS on the agent if we don't use hubble

---

tests/e2e/scenarios/kops-upgrade/run-test.sh

fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-misc-kops-upgrade/1389933886250684416#1:build-log.txt%3A477

Kubetest2 - fix wget flag in kops download

---

cmd/kops/integration_test.go
pkg/model/components/BUILD.bazel
pkg/model/components/discovery.go
tests/integration/update_cluster/public-jwks-apiserver/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/public-jwks-apiserver/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/public-jwks-apiserver/in-v1alpha2.yaml

Whittling down the use of the PublicJWKS feature flag.

Recognize the ServiceAccountIssuerDiscovery featue gate

---

tests/e2e/scenarios/k8s-upgrade/run-test.sh
tests/e2e/scenarios/kops-upgrade/run-test.sh

This way we can confirm that no changes are reported after update cluster --yes

Add another update cluster dryrun to upgrade tests

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

The intent is that we'll be able to perform arbitrary
upgrades/downgrades; creating a new scenario to avoid breaking
existing tests.

Create upgrade_ab e2e scenario for complex upgrades

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

A few errors I missed and probably should have caught in testing!

e2e upgrade-ab: fix a few errors

---

Makefile
docs/contributing/release.md
docs/release-process.md
hack/set-version
hack/verify-versions.sh

Simplifies the release process and solves the "how do I review a release PR?" problem.

Verify all versions are set correctly

---

docs/releases/1.21-NOTES.md

Fix references to v1.20 in v1.21 release notes

---

nodeup/pkg/model/kubelet_test.go
nodeup/pkg/model/secrets.go
pkg/model/pki.go
upup/pkg/fi/fitasks/keypair.go
upup/pkg/fi/vfs_castore.go

Backport rename of service-account key to 1.19

---

hack/verify-terraform.sh

ref: https://github.com/kubernetes/kops/pull/11433

release-1.20: Update verify-terraform to use 0.14.11

---

docs/release-process.md

ref: https://github.com/kubernetes/test-infra/pull/22165

Add instructions for updating the k8s versions periodic jobs

---

tests/e2e/scenarios/aws-ebs-csi/run-test.sh

/cc @rifelpet 
This seems to mimic what kubetest2's ginkgo runner is doing

Use ginkgo to run the tests so we can run things in parallel

---

tests/e2e/kubetest2-kops/deployer/up.go

See https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-do-calico/1392825464610885632

Kubetest2 - Increase validation time for DO jobs

---

channels/alpha

Add kOps and k8s 1.21 to alpha channel

---

README.md

All affected versions are now EOL.
/cc @rifelpet

Remove etcd-manager certificate expiration advisory

---

upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template

Cherry pick of #11493 on release-1.21.
#11493: Update cert-manager

Automated cherry pick of #11493: Update cert-manager

---

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml

Cherry pick of #11459 on release-1.21.
#11459: fix(coredns/rbac): add permission to list and watch

Automated cherry pick of #11459: fix(coredns/rbac): add permission to list and watch

---

tests/e2e/scenarios/aws-lb-controller/run-test.sh

Aws lb scenario fix flags

---

tests/e2e/scenarios/aws-lb-controller/run-test.sh

AWS LB controller requires multiple subnets to work

---

tests/e2e/scenarios/k8s-upgrade/run-test.sh
tests/e2e/scenarios/kops-upgrade/run-test.sh
tests/e2e/scenarios/upgrade-ab/run-test.sh

This makes them a bit more consistent.

Cleanup some of the scenario scripts

---

docs/release-process.md

ref: https://github.com/kubernetes/test-infra/pull/22214

Include new pipeline job in the release branch process

---

tests/e2e/scenarios/aws-ebs-csi/run-test.sh

I believe this will take care of the remaining failures.

Skip feature tests for ebs csi e2e

---

tests/e2e/scenarios/aws-ebs-csi/run-test.sh

Run the tests requiring snapshotcontroller again

---

pkg/model/components/cilium.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml

Bump default cilium to 1.9.7

---

pkg/model/awsmodel/BUILD.bazel
pkg/model/awsmodel/iam.go
pkg/resources/aws/aws.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/awstasks/iamrole.go
upup/pkg/fi/cloudup/loader.go
upup/pkg/fi/task.go

Cherry pick of #11497 on release-1.21.
#11497: Delete IAM roles no longer in the model

Automated cherry pick of #11497, #11558: Delete IAM roles no longer in the model

---

pkg/apis/kops/validation/aws.go

Cherry pick of #11560 on release-1.21.
#11560: Allow Spotinst to use comma separated instance types

Automated cherry pick of #11560: Allow Spotinst to use comma separated instance types

---

tests/e2e/scenarios/aws-ebs-csi/run-test.sh

Enable cert-manager in the ebs csi e2e test

---

pkg/model/iam/iam_builder.go

Only allow deletion of snapshots owned by the cluster

---

pkg/model/iam/iam_builder.go

Cherry pick of #11571 on release-1.21.
#11571: Only allow deletion of snapshots owned by the cluster

Automated cherry pick of #11571: Only allow deletion of snapshots owned by the cluster

---

pkg/kubeconfig/kubecfg_builder.go

Cherry pick of #11584 on release-1.20.
#11584: Only update kubeconfig user when we have user info

Automated cherry pick of #11584: Only update kubeconfig user when we have user info

---

tests/e2e/scenarios/aws-lb-controller/run-test.sh

Use the downloaded kops version for awslbc test

---

upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

https://docs.projectcalico.org/archive/v3.19/release-notes/

Update Calico to v3.19.1

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template

Add init image field for Amazon VPC CNI

---

tests/e2e/scenarios/kops-upgrade/run-test.sh

Remove debug code and copy kops to PATH

---

cloudmock/aws/mockautoscaling/warmpool.go
pkg/model/awsmodel/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/warmpool.go

Set lifecycle on WarmPool task

---

docs/operations/service_account_token_volumes.md

Update the service account issuer discovery documentation

---

docs/addons.md

The kOps addon has become one of the kOps big strenght. However, the static addons have been unmaintained for years and few of them actually work anymore.

Remove docs on static addons

---

pkg/model/iam/subject.go
pkg/model/issuerdiscovery.go
tests/integration/update_cluster/aws-lb-controller/data/aws_iam_role_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/aws-lb-controller/data/aws_iam_role_dns-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/aws-lb-controller/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/aws-lb-controller/kubernetes.tf
tests/integration/update_cluster/irsa/data/aws_iam_role_myotherserviceaccount.myapp.sa.minimal.example.com_policy
tests/integration/update_cluster/irsa/data/aws_iam_role_myserviceaccount.default.sa.minimal.example.com_policy
tests/integration/update_cluster/irsa/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/irsa/kubernetes.tf
tests/integration/update_cluster/public-jwks-apiserver/data/aws_iam_role_dns-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/public-jwks-apiserver/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/public-jwks-apiserver/kubernetes.tf
tests/integration/update_cluster/vfs-said/data/aws_iam_role_dns-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/vfs-said/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/vfs-said/kubernetes.tf
util/pkg/vfs/s3fs.go

Cherry pick of #11649 on release-1.21.
#11649: Fix issuer and jwks object path for IRSA

Automated cherry pick of #11649: Fix issuer and jwks object path for IRSA

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

Largely the same changes that made the upgrade scenario work.
/cc @rifelpet @hakman

Use version marker for kops ab scenario

---

tests/e2e/scenarios/aws-ebs-csi/run-test.sh
tests/e2e/scenarios/k8s-upgrade/run-test.sh

followup to https://github.com/kubernetes/kops/pull/11668
fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-aws-ebs-csi-driver/1400240774150361088#1:build-log.txt%3A486

Fix kubetest2 upgrade scripts

---

tests/e2e/scenarios/lib/common.sh
tests/e2e/scenarios/upgrade-ab/run-test.sh

Use release markers instead of releases

---

pkg/model/issuerdiscovery.go

This is where the trailing slash came from.
/kind bug
/cc @rifelpet

Drop trailing slash from oidc issuer

---

.github/workflows/main.yml
WORKSPACE

https://groups.google.com/g/golang-announce/c/RgCMkAEQjSI/m/r_EP-NlKBgAJ

Update Go to v1.16.5

---

pkg/model/components/awsebscsidriver.go
tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-a-ha-gce-example-com_metadata_startup-script
tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-b-ha-gce-example-com_metadata_startup-script
tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-c-ha-gce-example-com_metadata_startup-script
tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_nodes-ha-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce_private/data/google_compute_instance_template_master-us-test1-a-minimal-gce-private-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce_private/data/google_compute_instance_template_nodes-minimal-gce-private-example-com_metadata_startup-script

Generate AWSEBSCSIDriver model only when using AWS

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

Add support for setting latest k8s in ab scenario

---

tests/e2e/scenarios/addon-resource-tracking/run-test.sh
tests/e2e/scenarios/lib/common.sh

There is nothing that will make this test pass at the moment, but this script aims to show the intent of what we want to achieve with e.g #11712

Add test scenario for if channels is able to delete dangling resources

---

cmd/kops-controller/pkg/server/node_config.go
pkg/apis/nodeup/bootstrap.go

Remove unused field

---

pkg/apis/kops/cluster.go
pkg/model/components/apiserver.go
pkg/model/iam/subject.go

Set BindAddress appropriately when in IPv6-only mode

---

docs/cluster_spec.md

`inlinePolicy` isa `[]*iam.Statement`

Fix typo in IRSA docs

---

Makefile
pkg/model/components/kubeapiserver/model.go
pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
upup/models/bindata.go
upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
upup/pkg/fi/cloudup/urls_test.go
version.go

Bump versions for release 1.20.2

Release 1.20.2

---

docs/cluster_spec.md
k8s/crds/kops.k8s.io_clusters.yaml
k8s/crds/kops.k8s.io_instancegroups.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/validation/validation.go
pkg/apis/kops/validation/validation_test.go

Fixes: https://github.com/kubernetes/kops/issues/11576

Add support for logging-format option (text/json)

---

docs/addons.md

Fix kOps version for managed flag on cert-manager

---

docs/advanced/experimental.md
pkg/apis/kops/validation/validation.go
pkg/featureflag/featureflag.go

Fixes: https://github.com/kubernetes/kops/issues/11826
Refs: https://github.com/kubernetes/kops/pull/11825#issuecomment-865199882
/cc @johngmyers @olemarkus

Completely remove EnableExternalCloudController feature flag

---

tests/e2e/pkg/tester/skip_regex.go

Only set default --skip-regex if it hasn't been set

---

go.mod
go.sum
vendor/github.com/aws/aws-sdk-go/aws/client/client.go
vendor/github.com/aws/aws-sdk-go/aws/client/logger.go
vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
vendor/github.com/aws/aws-sdk-go/aws/session/credentials.go
vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go
vendor/github.com/aws/aws-sdk-go/aws/version.go
vendor/github.com/aws/aws-sdk-go/service/autoscaling/api.go
vendor/github.com/aws/aws-sdk-go/service/cloudformation/api.go
vendor/github.com/aws/aws-sdk-go/service/ec2/doc.go
vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface/interface.go
vendor/github.com/aws/aws-sdk-go/service/elbv2/api.go
vendor/github.com/aws/aws-sdk-go/service/iam/api.go
vendor/github.com/aws/aws-sdk-go/service/iam/errors.go
vendor/github.com/aws/aws-sdk-go/service/iam/iamiface/interface.go
vendor/github.com/aws/aws-sdk-go/service/route53/api.go
vendor/github.com/aws/aws-sdk-go/service/route53/errors.go
vendor/github.com/aws/aws-sdk-go/service/s3/api.go
vendor/github.com/aws/aws-sdk-go/service/s3/endpoint.go
vendor/github.com/aws/aws-sdk-go/service/s3/endpoint_builder.go
vendor/github.com/aws/aws-sdk-go/service/s3/errors.go
vendor/github.com/aws/aws-sdk-go/service/s3/service.go
vendor/modules.txt

This will allow it to recognize `ap-northeast-3`.

Update aws-sdk-go to v1.37.33 for kOps 1.20

---

upup/pkg/fi/cloudup/networking.go
upup/pkg/fi/cloudup/networking_test.go

Ref: https://github.com/kubernetes/kubernetes/pull/102328

Update CNI plugins to v0.9.1

---

channels/stable
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

It's been a week since alpha was updated.
[Original PR to alpha](https://github.com/kubernetes/kops/pull/11803)

Push alpha channel to stable

---

addons/README.md

Link to the documentation was broken.

fix: broken link

---

pkg/model/awsmodel/iam.go

If we are using a shared IAM profile, kops shouldn't try to do anything with policies and profile role.

Don't reconcile roles and policies if a profile is provided

---

pkg/client/simple/api/clientset.go
pkg/client/simple/clientset.go
pkg/client/simple/vfsclientset/clientset.go
pkg/client/simple/vfsclientset/cluster.go
pkg/client/simple/vfsclientset/instancegroup.go
pkg/model/BUILD.bazel
pkg/model/config.go
upup/pkg/fi/cloudup/BUILD.bazel
upup/pkg/fi/cloudup/apply_cluster.go

Write config as ManagedFile

---

cmd/kops/distrust_keypair.go
docs/cli/kops_distrust_keypair.md

Improve "kops distrust keypair" command

---

.shipbot.yaml
Makefile
cmd/kops/BUILD.bazel

Fixes: https://github.com/kubernetes/kops/issues/11875

Add support for darwin/arm64 on the client-side

---

cmd/kops/create_keypair.go

Allow rotation of etcd-clients-ca-cilium

---

tests/e2e/kubetest2-kops/deployer/up.go

Minor change to increase droplet size for e2e tests.
FYI - @timoreimann

[DigitalOcean] Increase droplet size for e2e tests

---

upup/pkg/fi/http.go

This will be closer to what we had before #11884 and is more than enough.

Set download timeout to 3 minutes

---

upup/pkg/fi/fitasks/keypair.go

Fix nil-pointer dereference on dryrun

---

tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
upup/pkg/fi/cloudup/terraform/target_hcl2.go

This has been included in the JSON output but was missing from HCL2

Include GCP Project in terraform HCL2 output

---

dns-controller/pkg/dns/record.go
dns-controller/pkg/watchers/BUILD.bazel
dns-controller/pkg/watchers/ingress.go
dns-controller/pkg/watchers/node.go
dns-controller/pkg/watchers/pod.go
dns-controller/pkg/watchers/pod_test.go
dns-controller/pkg/watchers/service.go
upup/pkg/fi/utils/BUILD.bazel
upup/pkg/fi/utils/net.go

Add support for IPv6 addresses to dns-controller

---

Makefile
pkg/model/components/kubeapiserver/model.go
pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/service-account-iam/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/service-account-iam/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/service-account-iam/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
upup/pkg/fi/cloudup/urls_test.go
version.go

Bump versions for release 1.21.0

Release 1.21.0

---

pkg/dump/dumper.go

Capture logs from the containerd service

---

pkg/model/awsmodel/bastion.go

Do not set both CIDR and IPv6CIDR on sg rules

---

nodeup/pkg/model/logrotate.go
pkg/dump/dumper.go

Add log rotation for etcd-cilium.log

---

pkg/resources/digitalocean/resources.go

Based on our e2e tests, when the e2e tests are complete, we delete the cluster. As part of the delete workflow, we first detach the droplets from the volume, and then go about deleting the volume.
We found a sporadic error when volume is already detached to the droplet - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-do-calico/1412394584972988416. Looks like some kind of a race condition..
Error details below for quick reference.
```
droplet:253698717
volume:8d266b3f-de59-11eb-81b7-0a58ac144312
volume:8d266b3f-de59-11eb-81b7-0a58ac144312	error deleting resources, will retry: failed to detach volume: 8d266b3f-de59-11eb-81b7-0a58ac144312, err: POST https://api.digitalocean.com/v2/volumes/8d266b3f-de59-11eb-81b7-0a58ac144312/actions: 404 (request …
```

[Digital Ocean] Fix sporadic volume detach error when volume is already detached

---

cmd/kops/export_kubeconfig.go

I missed some necessary changes to the argument parsing.

Fix "kops export kubeconfig"

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.9_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.9_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.9.yaml.template

Should avoid a call to the metadata API

Add region to aws lbc

---

addons/kubernetes-dashboard/v1.6.0.yaml
addons/kubernetes-dashboard/v1.6.1.yaml
addons/kubernetes-dashboard/v1.6.3.yaml

Clean up extra spaces, although these errors are not important, they affect the code specification.

Clean up extra spaces

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

Accommodate older destination kops versions in upgrade-ab scenario

---

tests/e2e/scenarios/keypair-rotation/run-test.sh

should fix https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-keypair-rotation#1:1416473162182299648/build-log.txt%3A919

Fix kops binary references in keypair rotation scenario

---

docs/networking.md

Promote AWS VPC CNI to stable

---

pkg/testutils/integrationtestharness.go
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.9_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.9_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.9.yaml.template
upup/pkg/fi/cloudup/BUILD.bazel
upup/pkg/fi/cloudup/template_functions.go

Without this, it will try to access data from IMDS

Set vpc-id on aws lbc

---

images/mkdocs/requirements.txt
mkdocs.yml

Also adding 1.22 release notes to nav and updating the release docs to mention doing so.

Update mkdocs dependencies to latest versions

---

channels/alpha
channels/stable
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

... and promote channel alpha to stable.
Fixes: #12069

Update Ubuntu images to v20210720

---

tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template

https://github.com/projectcalico/calico/releases/tag/v3.20.0

Update Calico to v3.20.0

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.9_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.9_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.9.yaml.template
upup/pkg/fi/cloudup/BUILD.bazel
upup/pkg/fi/cloudup/template_functions.go

Revert most of #12023 and keep awslbc on CP nodes

---

upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/cluster.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/metrics-server.addons.k8s.io-k8s-1.11.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/cluster.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/cluster.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/metrics-server.addons.k8s.io-k8s-1.11.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/cluster.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml

Also add tests for each variation to make sure this sticks
Fixes #12113

Make metrics-server insecure if insecure is true

---

upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template

Update Calico to v3.19.2

---

upup/pkg/fi/fitasks/managedfile.go
util/pkg/vfs/s3fs.go

This should take care of the `<nil> -> true` on the OIDC files.

Reconcile if managedFile is public or not

---

upup/pkg/fi/fitasks/managedfile.go
util/pkg/vfs/s3fs.go

Cherry pick of #12148 on release-1.21.
#12148: Reconcile if managedFile is public or not

Automated cherry pick of #12148: Reconcile if managedFile is public or not

---

upup/pkg/fi/http.go

Cherry pick of #12150 on release-1.21.
#12150: leverage proxy env variables

Automated cherry pick of #12150: leverage proxy env variables

---

.github/workflows/main.yml
WORKSPACE

https://golang.org/doc/devel/release#go1.16.minor

Update Go to v1.16.7

---

pkg/apis/kops/validation/validation.go

Add API validation for subcomponents using API versions removed in k8s 1.22

---

tests/e2e/scenarios/metrics-server/run-test.sh

ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-metrics-server/1427581668251668480#1:build-log.txt%3A810

Fix scaling of metrics-server deployment in e2e scenario

---

docs/addons.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/components/clusterautoscaler.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template

PR for feature request https://github.com/kubernetes/kops/issues/12100

Add option in Cluster Autoscaler AddOn for AWS EC2 Static instance list

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Bump cert-manager to 1.5.2

---

Makefile
pkg/model/components/kubeapiserver/model.go
pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/service-account-iam/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/service-account-iam/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/service-account-iam/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
upup/pkg/fi/cloudup/urls_test.go
version.go

Bump versions for release 1.21.1

Release 1.21.1

---

upup/pkg/fi/cloudup/openstack/cloud.go

fix parse semver

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Let's see if it sticks this time.

Bump cert-manager to 1.5.3

---

cmd/kops/integration_test.go
pkg/model/awsmodel/nodeterminationhandler.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/nth_sqs_resources/cloudformation.json
tests/integration/update_cluster/nth_sqs_resources/data/aws_cloudwatch_event_rule_nthsqsresources.example.com-InstanceStateChange_event_pattern
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_nthsqsresources.example.com-addons-bootstrap_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_nthsqsresources.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/nth_sqs_resources/kubernetes.tf
upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template

Also enable some extra features.
cc @haugenj

Bump node termination handler to 1.13.3

---

cmd/kops/integration_test.go
pkg/model/awsmodel/nodeterminationhandler.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/nth_sqs_resources/cloudformation.json
tests/integration/update_cluster/nth_sqs_resources/data/aws_cloudwatch_event_rule_nthsqsresources.example.com-InstanceStateChange_event_pattern
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_nthsqsresources.example.com-addons-bootstrap_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_nthsqsresources.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/nth_sqs_resources/kubernetes.tf
upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template

Cherry pick of #12237 on release-1.22.
#12237: Add instance state change notification to nth

Automated cherry pick of #12237: Add instance state change notification to nth

---

upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template

update openstack CSI

---

upup/pkg/fi/nodeup/nodetasks/bootstrap_client.go

Fix bootstrap when at least one IP is available

---

nodeup/pkg/model/sysctls.go

Fix kernel parameter for IPv6 forwarding

---

pkg/dump/dumper.go

This helps troubleshooting when the apiserver starts and the dns pods are created but the API DNS record never resolves.
Both external-dns and dns-controller run on control plane hosts only, so kubectl should be available in those cases.
https://github.com/kubernetes/kops/blob/43906b993da21bb1ed5a0122d2446d6a1e0348f3/upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/k8s-1.12.yaml.template#L26-L28
https://github.com/kubernetes/kops/blob/43906b993da21bb1ed5a0122d2446d6a1e0348f3/upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template#L29-L30

Dump external-dns and dns-controller pod logs

---

k8s/crds/kops.k8s.io_clusters.yaml
k8s/crds/kops.k8s.io_instancegroups.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

Fixes: https://github.com/kubernetes/kops/issues/12257

Add support --kernel-memcg-notification Kubelet flag

---

.github/workflows/main.yml
WORKSPACE

https://groups.google.com/g/golang-announce/c/dx9d7IOseHw

Update Go to v1.16.8

---

docs/getting_started/aws.md

include new required permissions in documentation

---

go.mod
go.sum
tests/e2e/go.sum
upup/pkg/fi/cloudup/terraform/hcl2.go
upup/pkg/fi/cloudup/terraform/hcl2_test.go
upup/pkg/fi/cloudup/terraformWriter/literal.go
vendor/github.com/hashicorp/hcl/v2/CHANGELOG.md
vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go
vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression_template.go
vendor/github.com/hashicorp/hcl/v2/hclsyntax/parser.go
vendor/github.com/hashicorp/hcl/v2/hclsyntax/spec.md
vendor/github.com/hashicorp/hcl/v2/ops.go
vendor/modules.txt

Cherry pick of #12316 on release-1.22.
#12316: Upgrade hcl to 2.10.1
```release-note
```

Automated cherry pick of #12316: Upgrade hcl to 2.10.1

---

upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

This PR removes an inconsistent comment.

fix: remove inconsistent comment

---

docs/cluster_spec.md

This PR fixes etcd backup docs (yearly instead of daily)

fix: etcd backup docs

---

upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template

Fix EC2 IPv6 endpoint for EBS CSI Driver controller

---

hack/dev-build-aws.sh

Somewhat opinionated, but should be an easy and quick way to build for
dev in most cases.

Script for iterating development on AWS

---

tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template

https://docs.projectcalico.org/archive/v3.20/release-notes/#v3201

Update Calico to v3.20.1

---

tests/e2e/pkg/tester/skip_regex.go

followup to https://github.com/kubernetes/kops/pull/12348

Fix version check in cilium SCTP test skipping

---

upup/pkg/fi/cloudup/new_cluster.go

These aren't used on other clouds.

Only configure IMDSv2 on AWS

---

pkg/model/awsmodel/context.go
pkg/model/names.go

We want to move all these eventually, and this is preparing for better
GCE subnet support.

AWS: Move some subnet functions into AWS model

---

pkg/util/subnet/BUILD.bazel
pkg/util/subnet/cidrmap.go
upup/pkg/fi/cloudup/gce/BUILD.bazel
upup/pkg/fi/cloudup/gce/network.go

This will enable reuse outside of gce.
We also enable it for IPv6 for use with AWS.

Move cidrmap to subnet package

---

pkg/model/gcemodel/firewall.go
tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
upup/pkg/fi/cloudup/gcetasks/firewallrule.go

If we don't specify some SourceRanges, it defaults to 0.0.0.0/0, which
is IPv4 and confusing.

GCE: Always have IPv6 rules in "ipv6 mode"

---

channels/alpha
channels/stable
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.23/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

[channels] Bump AWS/GCP/Azure Ubuntu AMIs to latest

---

cmd/kops/integration_test.go
pkg/model/awsmodel/BUILD.bazel
pkg/model/awsmodel/iam.go
pkg/model/awsmodel/iam_test.go
pkg/model/iam/types.go
tests/integration/update_cluster/irsa/data/aws_iam_role_myserviceaccount.test-wildcard.sa.minimal.example.com_policy
tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/irsa/in-v1alpha2.yaml
tests/integration/update_cluster/irsa/kubernetes.tf

This PR adds support for wildcard in roles generated for IRSA.
Added unit and integration tests.

feat: add support for wildcard in roles generated for IRSA

---

cmd/kops/create_cluster.go
docs/cli/kops_create_cluster.md

followup from https://github.com/kubernetes/kops/pull/12366

Fix list of supported cloud providers in CLI docs

---

hack/verify-terraform.sh

Seeing if this helps with the job failures

Upgrade terraform to 1.0.7

---

hack/verify-cloudformation.sh

hoping to fix https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/12398/pull-kops-verify-cloudformation/1441342494347366400
with an equivalent fix as https://github.com/kubernetes/kops/pull/12403/files

Run verify-cloudformation in host network

---

hack/verify-cloudformation.sh

Upgrade cnf-lint to 0.54.2

---

docs/bastion.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/bastion.go
pkg/apis/kops/v1alpha2/bastion.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/model/awsmodel/bastion.go
tests/integration/update_cluster/privatekopeio/kubernetes.tf
tests/integration/update_cluster/unmanaged/kubernetes.tf
upup/pkg/fi/cloudup/new_cluster.go

Attempt to address https://github.com/kubernetes/kops/issues/12147

Add option to create an internal load balancer for the bastion

---

tests/e2e/kubetest2-kops/deployer/template.go
tests/e2e/pkg/tester/tester.go
tests/e2e/templates/apiserver.yaml.tmpl

depends on https://github.com/kubernetes/test-infra/pull/23755

Add kubetest2-kops template for testing dedicated APIServer nodes

---

cmd/kops/integration_test.go
pkg/model/awsmodel/BUILD.bazel
pkg/model/awsmodel/iam.go
pkg/model/awsmodel/iam_test.go
pkg/model/iam/types.go
tests/integration/update_cluster/irsa/data/aws_iam_role_myserviceaccount.test-wildcard.sa.minimal.example.com_policy
tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/irsa/in-v1alpha2.yaml
tests/integration/update_cluster/irsa/kubernetes.tf

Cherry pick of #12342 on release-1.22.
#12342: feat: add support for wildcard in roles generated for IRSA
```release-note
```

Automated cherry pick of #12342: feat: add support for wildcard in roles generated for IRSA

---

pkg/apis/kops/validation/validation.go
upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml

Also upgrading to [v0.5.3](https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.5.3).
/hold for feedback on https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/397

Fix AWS IAM Authenticator support for k8s 1.22

---

cmd/kops/get_instances.go

Add support for YAML/JSON output to 'kops get instances'

---

channels/stable

It's been two weeks since these were added to alpha, should safe to push to stable
https://github.com/kubernetes/kops/pull/12337

Update stable k8s versions

---

cmd/kops/get_instances.go

Cherry pick of #12442 on release-1.22.
#12442: Add support for YAML/JSON output to 'kops get instances'
```release-note
```

Automated cherry pick of #12442: Add support for YAML/JSON output to 'kops get instances'

---

cmd/kops/toolbox_template.go

Don't ignore channel value in toolbox template

---

hack/verify-terraform.sh

This should catch issues like #12633 earlier. Note that this will fail until the bug in question has been fixed.
Our integration tests use an `aws-test` partition in any ARNs, so there should never be an `arn:aws:` occurrence in the outputs.

Check for hardcoded partitions in integration tests

---

nodeup/pkg/model/sysctls.go

Ref: https://github.com/kubernetes/kops/pull/12642#discussion_r739765757

Enable Router Advertisements for Debian 11 on  ens* interfaces

---

pkg/model/components/awscloudcontrollermanager.go
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
upup/pkg/fi/cloudup/new_cluster.go

Start IPv6 CIDR numbering from 0

---

pkg/model/iam/iam_builder.go
tests/integration/update_cluster/minimal-warmpool/data/aws_iam_role_policy_nodes.minimal-warmpool.example.com_policy
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-warmpool/in-v1alpha2.yaml
tests/integration/update_cluster/minimal-warmpool/kubernetes.tf

Fix cluster name used in IAM policies

---

nodeup/pkg/model/ntp.go

Seems `systemd-timesyncd` is replaced by `chrony` in Ubuntu 21.10 (Impish):
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/12681/pull-kops-e2e-k8s-ubuntu2110/1456135670358609920/artifacts/ip-172-20-33-101.ec2.internal/kops-configuration.log
Switching to `chrony` fixes things with Ubuntu 21.10 (Impish):
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/12681/pull-kops-e2e-k8s-ubuntu2110/1456147090349494272/artifacts/ip-172-20-33-128.us-east-2.compute.internal/kops-configuration.log
Also, `chrony` works with older Ubuntu versions like 20.04 (Focal).
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/12681/pull-kops-e2e-kubernetes-aws/1456147651497037824/artifacts/ip-172-20-36-186.eu-west-3.compute.internal/kops-configuration.log

Use chrony for synchronizing time in Ubuntu

---

channels/alpha

* https://github.com/kubernetes/kubernetes/releases/tag/v1.22.3
* https://github.com/kubernetes/kubernetes/releases/tag/v1.21.6
* https://github.com/kubernetes/kubernetes/releases/tag/v1.20.12
* https://github.com/kubernetes/kubernetes/releases/tag/v1.19.16

Update k8s versions with latest releases. Also bump AWS Ubuntu AMI version

---

upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template

This PR updates `spotinst/ocean-controller` to v1.0.79.

Spotinst: Update `spotinst/ocean-controller` to v1.0.79

---

pkg/nodeidentity/gce/identify.go

It does seem that filtering is not yet implemented on this call.
Don't over-warn.
Also introduce pagination, because without a filter we might paginate.

gce: don't over-warn on ManagedInstanceGroups filtering

---

pkg/apis/kops/validation/validation.go

Don't fail validation if Nvidia and containerRuntime defaults

---

pkg/commands/set_cluster_test.go
pkg/commands/unset_cluster_test.go
util/pkg/reflectutils/access.go

Support setting empty maps and structs

---

nodeup/pkg/model/networking/cilium.go

Do not return error when there is no error checking for cgroupfs

---

.github/workflows/main.yml
WORKSPACE

https://groups.google.com/g/golang-announce/c/0fM21h43arc/m/a2Hu_dWRAAAJ

Update Go to v1.17.3

---

k8s/crds/kops.k8s.io_clusters.yaml
nodeup/pkg/model/cloudconfig.go
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

https://github.com/kubernetes/cloud-provider-openstack/pull/1689
/hold
lets wait that cloud-provider-openstack is merged first

Add ingress hostname suffix configurable to kOps

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Partial backport of #12564 
Keep CNP status updates enabled to avoid BC break.

Partial backport of #12564

---

pkg/model/BUILD.bazel
pkg/model/master_volumes.go
pkg/model/master_volumes_test.go

Cherry pick of #12791 on release-1.21.
#12791: Add test for ratio bug
```release-note
```

Automated cherry pick of #12791: Add test for ratio bug

---

pkg/model/components/containerd.go
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
upup/pkg/fi/cloudup/containerd.go

Update containerd to v1.6.0-beta.3

---

tests/integration/update_cluster/privateflannel/data/aws_s3_bucket_object_privateflannel.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateflannel/data/aws_s3_bucket_object_privateflannel.example.com-addons-networking.flannel-k8s-1.12_content
upup/models/cloudup/resources/addons/networking.flannel/k8s-1.12.yaml.template

https://github.com/flannel-io/flannel/releases/tag/v0.15.1

Update Flannel CNI to v0.15.1

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.16_content
tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template

https://docs.projectcalico.org/archive/v3.21/release-notes/

Update Calico to v3.21.1

---

tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-networking.projectcalico.org.canal-k8s-1.22_content
upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.22.yaml.template

Ref: https://docs.projectcalico.org/archive/v3.21/release-notes/

Update Canal to v3.21.1

---

channels/stable

This way we don't forget about it.
/cc @johngmyers @rifelpet

Promote alpha channel to stable

---

tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-networking.projectcalico.org.canal-k8s-1.22_content
upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.22.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template

Ref: https://docs.projectcalico.org/archive/v3.20/release-notes/#v3203

Update Calico and Canal to v3.20.3 for kOps 1.22

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

Fix upgrade tests with dest kOps version < 1.22

---

tests/e2e/scenarios/aws-lb-controller/run-test.sh
tests/e2e/scenarios/lib/common.sh

Pin the aws-lb-controller scenario to k8s 1.21

---

tests/e2e/scenarios/lib/common.sh

Fix e2e scenario tests

---

docs/contributing/testing.md
tests/e2e/kubetest2-kops/deployer/up.go

Open nodeport to IPv6 in e2e tests

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

Fix upgrade tests to kops version < 1.22

---

docs/releases/1.23-NOTES.md
nodeup/pkg/model/docker_test.go
nodeup/pkg/model/packages.go
nodeup/pkg/model/sysctls.go
util/pkg/distributions/distributions.go
util/pkg/distributions/identify.go
util/pkg/distributions/identify_test.go

As agreed during the 03.12.2021 office hours.
/cc @johngmyers @rifelpet

Remove support for old distros

---

pkg/apis/kops/validation/validation.go
upup/pkg/fi/cloudup/bootstrapchannelbuilder/cilium.go

Currently at rc2 and it doesn't look like any changes are needed to the manifests.

Allow setting cilium 1.11

---

.github/workflows/main.yml
WORKSPACE

Ref: https://groups.google.com/g/golang-announce/c/Xcefh1Tfj-U/m/vVWkIVTVBwAJ

Update Go to v1.17.4

---

.github/workflows/main.yml
WORKSPACE

Ref: https://groups.google.com/g/golang-announce/c/Xcefh1Tfj-U/m/vVWkIVTVBwAJ

Update Go to v1.16.11

---

tests/integration/update_cluster/external_dns/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/external_dns/data/aws_s3_bucket_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/external_dns_irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/external_dns_irsa/data/aws_s3_bucket_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.19_content
upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/k8s-1.19.yaml.template

Fix external-dns service name

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.9_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.9_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.9_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.9_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.9.yaml.template

Ref: https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.3.1
/cc @olemarkus

Update aws-load-balancer-controller to v2.3.1

---

nodeup/pkg/model/kube_apiserver.go
nodeup/pkg/model/kube_apiserver_test.go
nodeup/pkg/model/tests/golden/minimal/tasks-kube-apiserver.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/validation/validation.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/flagbuilder/buildflags_test.go
pkg/model/components/apiserver.go
tests/integration/update_cluster/privatecilium2/cloudformation.json.extracted.yaml
tests/integration/update_cluster/privatecilium2/data/aws_launch_template_master-us-test-1a.masters.privatecilium.example.com_user_data
tests/integration/update_cluster/privatecilium2/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/public-jwks-apiserver/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/public-jwks-apiserver/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/public-jwks-apiserver/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content

Ref:
* https://github.com/kubernetes/kubernetes/pull/106859

Do not set insecure-port as of k8s 1.20

---

nodeup/pkg/model/cloudconfig_test.go

I encountered a test failure that was hard to track down; this
additional logging on failure helped me figure it out.

tests: Improve logging on test failure

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.16_content
tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-networking.projectcalico.org.canal-k8s-1.22_content
upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.22.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template

xRef: https://projectcalico.docs.tigera.io/archive/v3.21/release-notes/#v3212

Update Calico and Canal to v3.21.2

---

.github/workflows/main.yml
WORKSPACE

xRef: https://groups.google.com/g/golang-announce/c/hcmEScgc00k/m/ZWnOjeY4CQAJ

Update Go to v1.17.5

---

.github/workflows/main.yml
WORKSPACE

xRef: https://groups.google.com/g/golang-announce/c/hcmEScgc00k/m/ZWnOjeY4CQAJ

Update Go to v1.16.12

---

pkg/model/components/containerd.go
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

xRef: https://github.com/containerd/containerd/releases/tag/v1.6.0-beta.4
Ref: https://github.com/kubernetes/kops/issues/12969

Update containerd to v1.6.0-beta.4

---

docs/getting_started/aws.md

Add missing permissions

---

tests/e2e/pkg/tester/skip_regex.go

xRef: https://github.com/kubernetes/kubernetes/pull/81537

Do not skip HPA tests

---

pkg/model/gcemodel/BUILD.bazel
pkg/model/gcemodel/autoscalinggroup.go
pkg/model/gcemodel/context.go
pkg/model/gcemodel/service_accounts.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/gcetasks/instance.go
upup/pkg/fi/cloudup/gcetasks/instancetemplate.go

The next step towards supporting custom ServiceAccounts per IG

gce: Use ServiceAccount task when building model

---

pkg/pki/BUILD.bazel
pkg/pki/publickey.go

These are useful when verifying and creating PKI signatures.

Create helper functions for parsing public keys

---

tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
upup/pkg/fi/cloudup/gcetasks/instance.go
upup/pkg/fi/cloudup/gcetasks/instancetemplate.go

followup to https://github.com/kubernetes/kops/pull/12988

Use terraform literals in GCP service account references

---

cmd/kops-controller/main.go
cmd/kops-controller/pkg/server/server.go

This gives us access to a managed client, and it lets us hook into the
lifecycle.

kops-controller: use controller-runtime manager

---

pkg/resources/gce/gce.go

We try to avoid cleaning up by name, and prefer checking references to
(e.g. targeting) a known resource, like an instancegroup.

gce: clean up networking objects by reference

---

docs/releases/1.24-NOTES.md
pkg/apis/kops/validation/validation.go

Ref:
* https://github.com/kubernetes/kubernetes/issues/106893
* https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/2221-remove-dockershim/README.md

Do not allow docker on k8s 1.24+

---

nodeup/pkg/model/containerd.go
nodeup/pkg/model/kubelet.go

Fixes #11607
It's only partial though due to https://github.com/kubernetes/kubernetes/issues/101189
If this looks good, I'll add some release notes as well

Create cgroups for kube and runtime if configured

---

upup/models/cloudup/resources/addons/storage-aws.addons.k8s.io/v1.15.0.yaml.template

Do not install ClusterRole and binding used by in-tree volume provider if CSI is used

---

tests/integration/update_cluster/karpenter/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_bucket_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template
upup/pkg/fi/cloudup/template_functions.go

/bug
This should fix the karpenter e2e. It may be that 10m validation is a bit short though.

Fix various typos related to karpenter

---

pkg/model/components/BUILD.bazel
pkg/model/components/gcpcloudcontrollermanager.go
upup/models/BUILD.bazel
upup/models/cloudup/resources/addons/gcp-cloud-controller.addons.k8s.io/k8s-1.23.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/populate_cluster_spec.go

This PR adds `ExternalCloudControllerManager` support for gcp.

external CCM for GCE

---

nodeup/pkg/model/convenience.go
nodeup/pkg/model/kube_apiserver.go
nodeup/pkg/model/kube_controller_manager.go
nodeup/pkg/model/kube_proxy.go
nodeup/pkg/model/kube_scheduler.go
pkg/kubemanifest/volumes.go
pkg/model/components/etcdmanager/model.go

This allows for the helper to be used in more places.

Enhance AddHostPathMapping to support a fluent style

---

cmd/kops/get_instances.go

Don't try to add node name to instances without node object

---

docs/releases/1.23-NOTES.md

We should hilight the state of ipv6 in the relnotes.

Add ipv6 to relnotes

---

nodeup/pkg/model/kubelet.go
nodeup/pkg/model/tests/kubelet/featuregates/cluster.yaml
nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
nodeup/pkg/model/tests/kubelet/warmpool/cluster.yaml
nodeup/pkg/model/tests/kubelet/warmpool/tasks.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/validation/legacy.go
pkg/apis/kops/validation/validation.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/components/kubelet.go
pkg/model/components/networking.go
upup/pkg/fi/cloudup/populate_cluster_spec_test.go

Clean up kubelet networking flags for dockershim

---

pkg/model/openstackmodel/firewall.go

Cherry pick of #13131 on release-1.23.
#13131: expose external ccm metrics for OpenStack

Automated cherry pick of #13131: expose external ccm metrics for OpenStack

---

upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template

minor update to keep up to date with the latest DO CCM version.
Tested locally and works as expected.

[DigitalOcean] update ccm version to 0.1.36

---

pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

Ref: https://github.com/kubernetes/kops/issues/12969

Update containerd to v1.6.0-rc.2

---

docs/contributing/test_versions.md
mkdocs.yml
tests/e2e/kubetest2-kops/deployer/build.go

Add documentation for how to test master/branch/PRs without local build env.

Document download of test versions

---

pkg/model/components/apiserver.go
pkg/model/components/kubecontrollermanager.go
pkg/model/components/kubescheduler.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_master-us-test-1a.masters.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/privatecanal/data/aws_launch_template_master-us-test-1a.masters.privatecanal.example.com_user_data
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content

Cherry pick of #13203 on release-1.22.
#13203: Fix CSI migration feature gates
```release-note
```

Automated cherry pick of #13203: Fix CSI migration feature gates

---

pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

xRef: https://github.com/containerd/containerd/releases/tag/v1.6.0-rc.3
This should be the final release candidate! 😄

Update containerd to v1.6.0-rc.3

---

nodeup/pkg/model/containerd.go
nodeup/pkg/model/containerd_test.go
nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml
pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

Cherry pick of #13248 on release-1.23.
#13248: Install contained from the release package

Automated cherry pick of #13248: Install contained from the release package

---

pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go
upup/pkg/fi/cloudup/runc.go

Ref: https://github.com/containerd/containerd/releases/tag/v1.6.0
Fixes: #12969 
/cc @olemarkus @rifelpet @johngmyers @justinsb

Update containerd to v1.6.0

---

cmd/kops/integration_test.go
pkg/apis/kops/validation/validation.go
tests/e2e/scenarios/aws-lb-controller/run-test.sh
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/kubernetes.tf
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/kubernetes.tf
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_iam_role_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/kubernetes.tf
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/kubernetes.tf
upup/models/BUILD.bazel
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

Cherry pick of #13267 on release-1.23.
#13267: Update LBC to 2.4.0

Automated cherry pick of #13267: Update LBC to 2.4.0

---

nodeup/pkg/model/kube_apiserver.go

Cherry pick of #13264 on release-1.22.
#13264: Disable some flags in kube-apiserver when logging-format is

Automated cherry pick of #13264: Disable some flags in kube-apiserver when logging-format is

---

nodeup/pkg/model/kubelet.go
pkg/apis/nodeup/config.go
upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #13268 to release-1.23 branch.

Cherry-pick of #13268: Enable RBN with AWS CCM 1.22.0-alpha.1

---

tests/e2e/scenarios/upgrade-ha-leader-migration/run-test.sh
tests/e2e/scenarios/upgrade-ha-leader-migration/test-leader-migration.sh

This PR tries to reduce assumptions to the supporting scripts and testing environment, in hope of getting out of the "it works on my machine" situation.

kops: Leader Migration testing: run with pure kubetest2

---

pkg/model/components/addonmanifests/awsloadbalancercontroller/iam.go
pkg/model/iam/iam_builder.go
tests/integration/update_cluster/aws-lb-controller/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm/data/aws_iam_role_policy_masters.minimal.example.com_policy
tests/integration/update_cluster/many-addons/data/aws_iam_role_policy_masters.minimal.example.com_policy

Cherry pick of #13280 on release-1.23.
#13280: Add missing permissions to aws lbc for irsa
```release-note
```

Automated cherry pick of #13280: Add missing permissions to aws lbc for irsa

---

pkg/model/components/etcdmanager/model.go
pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
pkg/model/components/etcdmanager/tests/pollinterval/tasks.yaml
pkg/model/components/etcdmanager/tests/proxy/tasks.yaml

Cherry pick of #13196 onto release-1.21

---

docs/operations/updates_and_upgrades.md

Added commands to run to update the cluster after kOps update so new features/bug-fixes are applied to the cluster

Cluster config update after kOps update

---

pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

https://github.com/containerd/containerd/releases/tag/v1.6.1

Update containerd to v1.6.1

---

cloudmock/gce/mockiam/serviceaccounts.go
pkg/model/gcemodel/service_accounts.go
tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
upup/pkg/fi/cloudup/gcetasks/serviceaccount.go

fixes #13309
looks like the payload should NOT contain email when creating new service account.

Fix GCE service account creation

---

tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template

Cherry pick of #13328 on release-1.23.
#13328: Use proper image and add health check
```release-note
```

Automated cherry pick of #13328: Use proper image and add health check

---

pkg/apis/kops/validation/instancegroup.go
pkg/apis/kops/validation/instancegroup_test.go

Allow duplicate taint keys

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml.template
upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template

Cherry pick of #13383 on release-1.23.
#13383: Add protocol explicitly to services
```release-note
```

Automated cherry pick of #13383: Add protocol explicitly to services

---

Makefile

This target may have done something at some point in time. But not anymore

Remove pr target

---

images/mkdocs/Dockerfile
images/mkdocs/requirements.txt

/cc @rifelpet @olemarkus @MoShitrit

Update netflify deps

---

channels/stable

The previous PR (#13411 ) got into a weird state because of a rebase attempt.
Re-trying this with a fresh PR
/cc @hakman

Promote alpha to stable

---

upup/pkg/fi/cloudup/openstack/BUILD.bazel
upup/pkg/fi/cloudup/openstack/instance.go
upup/pkg/fi/cloudup/openstack/loadbalancer.go

fix member update when draining

---

docs/security.md

Security docs are very dates. I at least updated/removed the incorrect stuff now, but we should look into extending this.

Update the security docs

---

tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_minimal-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
upup/models/cloudup/resources/addons/gcp-pd-csi-driver.addons.k8s.io/k8s-1.23.yaml.template

fixes #13425
I tested creating new pvcs, resizing them and deleting. Everything works smoothly now.

Run CSI controller in masters

---

.github/dependabot.yml

- Included githubactions in the dependabot config
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.
Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot
GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
**Special notes …

Included githubactions in dependabot config

---

hack/install-gsutil.sh

Install gcloud instead of gsutil

---

dnsprovider/pkg/dnsprovider/providers/do/dns.go

More details can be found in the issue #13441

fix dns controller crashing for DO

---

pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

Update containerd to v1.6.2

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_nthsqsresources.longclustername.example.com-addons-bootstrap_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_nthsqsresources.longclustername.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml.template
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

And a topology spread constraint to NTH.

Add PDBs to addons where this was missing

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.10.3

Bump AWS CNI to version 1.10.3

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.16_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_privatecanal.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_privatecanal.example.com-addons-networking.projectcalico.org.canal-k8s-1.22_content
upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.22.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template

Ref: https://projectcalico.docs.tigera.io/archive/v3.21/release-notes/#v3215

Update Calico and Canal to v3.21.5

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template

adds pod annotations to cluster autoscaler.

add cluster autoscaler pod annotations

---

.github/workflows/main.yml
Makefile
cloudbuild.yaml

Ref: https://groups.google.com/g/golang-announce/c/oecdBNLOml8

Update Go to v1.18.1

---

docs/operations/images.md
docs/releases/1.23-NOTES.md
util/pkg/distributions/distributions.go
util/pkg/distributions/identify.go
util/pkg/distributions/identify_test.go

Add back support for Ubuntu 18.04

---

pkg/assets/builder.go

Image digest doesn't work with side-loaded images.
/cc @olemarkus @justinsb

Don't digest side-loaded images

---

pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

Ref: https://github.com/containerd/containerd/releases/tag/v1.6.3

Update containerd to v1.6.3

---

docs/releases/1.24-NOTES.md
pkg/apis/kops/containerdconfig.go
tests/integration/update_cluster/nvidia/cloudformation.json.extracted.yaml
tests/integration/update_cluster/nvidia/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/nvidia/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/nvidia/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/nvidia/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/nvidia/data/aws_s3_object_minimal.example.com-addons-nvidia.addons.k8s.io-k8s-1.16_content
tests/integration/update_cluster/nvidia/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/nvidia/data/aws_s3_object_nodeupconfig-nodes_content
upup/models/cloudup/resources/addons/nvidia.addons.k8s.io/k8s-1.16.yaml

This will also make it possible to use gpu + arm. That combination requires jammy AMIs.

Bump nvidia device plugin to 0.11 and nvidia driver to 510

---

pkg/model/awsmodel/spotinst.go
upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go

This PR adds support for EBS root volume encryption.

Spotinst: Add support for EBS root volume encryption

---

pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

https://github.com/containerd/containerd/issues/6876
will revisit once 1.6.4 is out

Revert containerd v1.6.3 upgrade

---

upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template

add priorities to CSI openstack

---

pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

Ref: https://github.com/containerd/containerd/releases/tag/v1.6.4

Update containerd to v1.6.4

---

docs/instance_groups.md
docs/releases/1.24-NOTES.md
hack/mkdocs_macros/feature_stability_table.py

Add docs for the packages option

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.16_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_privatecanal.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_privatecanal.example.com-addons-networking.projectcalico.org.canal-k8s-1.22_content
upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.22.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template

Ref: https://github.com/projectcalico/calico/releases/tag/v3.23.0

Update Calico and Canal to v3.23.0

---

pkg/model/components/addonmanifests/karpenter/iam.go
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template

this job timed out, seeing if an upgrade will help: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-misc-karpenter/1517300168158875648
Fixes a few bugs in the manifest and updates it to more closely match the rendered helm chart

Upgrade Karpenter to 0.10.0

---

cloudbuild.yaml

Increase timeout for pushing binaries to staging

---

pkg/model/components/kubeapiserver/model_test.go
pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml

Ignore digest for kube-apiserver-healthcheck model test

---

tests/e2e/scenarios/digital-ocean/run-test
tests/e2e/scenarios/kops-upgrade/run-test.sh
tests/e2e/scenarios/upgrade-ab/run-test.sh

Ref: https://github.com/kubernetes/kops/pull/13577

Skip nfs tests in all scenarios

---

tests/e2e/scenarios/aws-lb-controller/run-test.sh

https://testgrid.k8s.io/kops-misc#kops-aws-aws-load-balancer-controller
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-aws-load-balancer-controller/1525228677749542912
/cc @olemarkus

Use -ginkgo.junit-report instead of -ginkgo.reportFile

---

channels/alpha
channels/stable
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.23/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

Already been running for some time in e2e

Promote May AMIs in channels

---

pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-ipv6-cilium/kubernetes.tf
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-warmpool/kubernetes.tf
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/kubernetes.tf
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/kubernetes.tf
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.11.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/cilium.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Since this introduced some backwards breaking RBAC changes, the manifest got forked

Bump Cilium to 1.11.5

---

docs/getting_started/aws.md

Add missing backslash to aws.md

---

protokube/cmd/protokube/main.go

Fix Protokube gossip flag

---

.github/dependabot.yml

Use dependabot for Go deps

---

Makefile
vendor/github.com/weaveworks/mesh/peer_name_hash.go
vendor/github.com/weaveworks/mesh/peer_name_mac.go

Alternative to #13703 
/cc @rifelpet @olemarkus @justinsb

Use build tags for Protokube

---

docs/terraform.md

Fixes: https://github.com/kubernetes/kops/issues/13688

Clarify difference between terraform and kOps state stores

---

channels/stable

Versions have been running in alpha for 7 days

promote alpha to stable (k8s releases)

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.11.2

Bump aws cni to 1.11.2

---

channels/pkg/channels/apply.go

This is one of the solutions to #13712
I think we should get this one in to verify this solves the issue. Leaving the issue open so we can discuss if this is the right solution or not.

Use kubectl replace instead of apply when updating addons

---

pkg/model/components/awscloudcontrollermanager.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/aws-cloud-controller.addons.k8s.io-k8s-1.18.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml

Update AWS CCM images for k8s 1.20-1.22

---

channels/alpha
channels/stable

Recommend the latest kOps version in alpha & stable channels and add 1.24 to alpha

---

docs/index.md

Align website and readme file

---

upup/pkg/fi/cloudup/openstack/loadbalancer.go

we are currently seeing that current backoff is not enough always. This will double the Steps

increase backoff time when updating loadbalancer pool member

---

docs/contributing/test_versions.md
tests/e2e/kubetest2-kops/deployer/build.go

And update the docs accordingly so the script actually works.

Set Makefile GITSHA to the git sha instead of human 'readable' name

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.23_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.23_content
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.23.yaml.template

Ref: https://projectcalico.docs.tigera.io/release-notes/#v3232

Update Calico to v3.23.2

---

channels/pkg/channels/addon.go
channels/pkg/channels/apply.go

Cherry pick of #13897 on release-1.24.
#13897: Apply PKI even if addon fails
```release-note
```

Automated cherry pick of #13897: Apply PKI even if addon fails

---

pkg/model/gcemodel/context.go
upup/pkg/fi/cloudup/gce/gce_cloud.go

Limit GCE names to 63 chars for various resources

---

pkg/model/awsmodel/autoscalinggroup.go
tests/integration/update_cluster/mixed_instances/cloudformation.json
tests/integration/update_cluster/mixed_instances/kubernetes.tf
upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go

Fixes https://github.com/kubernetes/kops/issues/13849

Fix unsetting ASG max price

---

upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml

This reverts commit 6d0cc427f65ba1bf3e08592aabc679bae45bbbcb.

Revert "Add back the metrics-server 443 port with a new name"

---

docs/cli/kops_create_cluster.md
docs/cli/kops_edit_cluster.md
docs/cli/kops_edit_instancegroup.md
pkg/featureflag/featureflag.go

Set SpecOverrideFlag to true by default

---

channels/alpha
channels/stable

/cc @olemarkus @rifelpet @MoShitrit

Add release 1.24.0 to channels

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go

Skip deregistering the instance during rolling update for Spotinst

---

tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-authentication.aws-k8s-1.12_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/manifest.yaml

Upgrade aws-iam-authenticator to v0.5.9

---

docs/cluster_spec.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/cluster.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/cluster.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/components/etcdmanager/model.go
pkg/model/components/etcdmanager/model_test.go
pkg/model/components/etcdmanager/tests/interval/cluster.yaml
pkg/model/components/etcdmanager/tests/interval/tasks.yaml

Add option to set etcd-manager backup interval

---

k8s/crds/kops.k8s.io_instancegroups.yaml
pkg/apis/kops/instancegroup.go
pkg/apis/kops/v1alpha2/instancegroup.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/instancegroup.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/validation/gce.go
pkg/apis/kops/validation/instancegroup.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/gcemodel/autoscalinggroup.go
tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
upup/pkg/fi/cloudup/gcetasks/instancetemplate.go

Resolves https://github.com/kubernetes/kops/issues/13945

Adding GCE SPOT support

---

channels/pkg/channels/apply.go

We also aim to be a little stricter about invalid input
(e.g. namespace specified for cluster-scoped objects).

Applier should be more tolerant of errors

---

pkg/model/hetznermodel/servers.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/hetzner/cloud.go
upup/pkg/fi/cloudup/hetznertasks/server.go
upup/pkg/fi/cloudup/hetznertasks/servergroup_fitask.go

Add server group management for Hetzner

---

channels/stable

promote alpha k8s versions to stable

---

pkg/model/hetznermodel/servers.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/hetzner/cloud.go
upup/pkg/fi/cloudup/hetznertasks/server.go
upup/pkg/fi/cloudup/hetznertasks/servergroup_fitask.go

Cherry pick of #14018 on release-1.24.
#14018: Add server group management for Hetzner
```release-note
```

Automated cherry pick of #14018: Add server group management for Hetzner

---

upup/pkg/fi/cloudup/containerd.go

Ref: https://github.com/containerd/containerd/releases/tag/v1.6.7
/cc @olemarkus

Add hashes for containerd v1.6.7

---

tests/e2e/pkg/tester/skip_regex.go

Fix more e2e skips

---

pkg/model/gcemodel/context.go
pkg/resources/gce/gce.go
tests/e2e/pkg/tester/skip_regex.go
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
upup/pkg/fi/cloudup/gce/utils.go

I think this is a more complete version of #14132.

Limit GCE network names to 63 chars

---

nodeup/pkg/model/sysctls.go
pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Also fixes an issue with rp_filters on some clouds/distros combinations. See https://github.com/cilium/cilium/issues/10645

Bump cilium to 1.11.8

---

pkg/resources/aws/aws.go

Because we iterate over _all_ IAM roles and profiles in the account, there may be cases, especially in e2e, where an item has been deleted after being listed. Those should be safe to ignore.
Examples:
* https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-distro-debian11/1561015949732089856/build-log.txt
* https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-misc-arm64-conformance/1561028281317199872/build-log.txt

Ignore entities not found when deleting IAM roles and profiles

---

docs/operations/etcd_administration.md
docs/operations/etcd_backup_restore_encryption.md
docs/operations/troubleshoot.md

Update and clean up etcdcli and etcd backup documentation

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

Don't set unused test package flags to empty string

---

tests/e2e/go.mod
tests/e2e/go.sum

Update cloud.google.com/go/storage to v1.25.0

---

tests/integration/update_cluster/karpenter/data/aws_launch_template_karpenter-nodes-default.minimal.example.com_user_data
tests/integration/update_cluster/karpenter/data/aws_launch_template_karpenter-nodes-single-machinetype.minimal.example.com_user_data
tests/integration/update_cluster/karpenter/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/karpenter/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/karpenter/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_nodeupconfig-karpenter-nodes-default_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_nodeupconfig-karpenter-nodes-single-machinetype_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_nodeupconfig-nodes_content

This test is failing master. Probably some merge concurrency error.

Fix karpenter update test

---

pkg/model/components/etcdmanager/model.go
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_manifests-etcdmanager-events-master-fsn1_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_manifests-etcdmanager-main-master-fsn1_content

```sh
$ hcloud volume list -o columns=name,server -s name 
NAME                                       SERVER
etcd-1.etcd-events.test1.k8s.local         master-fsn1-1-572f678e19233740
etcd-1.etcd-main.test1.k8s.local           master-fsn1-1-572f678e19233740
etcd-2.etcd-events.test1.k8s.local         master-fsn1-2-35d166ac6dc945b1
etcd-2.etcd-main.test1.k8s.local           master-fsn1-2-35d166ac6dc945b1
etcd-3.etcd-events.test1.k8s.local         master-fsn1-3-7af95061338a68fd
etcd-3.etcd-main.test1.k8s.local           master-fsn1-3-7af95061338a68fd
```
/cc @justinsb @olemarkus

Run etcd-manager with instance group name as volume name tag for Hetzner

---

pkg/apis/kops/validation/aws.go

Refs: https://github.com/kubernetes/kops/issues/14133

Show the reason for which an AWS image is invalid

---

pkg/model/components/awscloudcontrollermanager.go
tests/integration/update_cluster/karpenter/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-1.25/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.25/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-1.25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content

Currently using staging image. 
/hold for stable

Bumping AWS CCM to 1.25

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Bump cert-manager to 1.8.2

---

upup/pkg/fi/cloudup/hetzner/cloud.go

Remove warning for FindClusterStatus not implemented for Hetzner

---

pkg/applylib/applyset/health.go

Add a few objects that are well-known as not having status, so that we
avoid/reduce logspam.

applylib: Better health checking

---

pkg/model/openstackmodel/servergroup.go
pkg/model/openstackmodel/servergroup_test.go
pkg/model/openstackmodel/tests/servergroup/truncate-cluster-names-to-42-characters.yaml
upup/pkg/fi/cloudup/openstacktasks/instance.go
upup/pkg/fi/cloudup/openstacktasks/instance_test.go

Cherry pick of #13853 on release-1.25.
#13853: Fix openstack tag limitation
```release-note
```

Automated cherry pick of #13853: Fix openstack tag limitation

---

pkg/instancegroups/instancegroups.go
pkg/instancegroups/instancegroups_test.go

Warm pool-enabled ASGs scaled to zero will no longer panic

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.11.4

Bump aws-cni to v1.11.4

---

upup/pkg/fi/cloudup/hetznertasks/servergroup.go

Delete the oldest servers when over the desired count for Hetzner

---

cmd/kops/edit_instancegroup.go
cmd/kops/edit_instancegroup_test.go
cmd/kops/test/edit_instance_group.yaml
pkg/model/awsmodel/autoscalinggroup_test.go
pkg/testutils/cluster.go
upup/pkg/fi/cloudup/awsup/aws_utils_test.go
upup/pkg/fi/cloudup/deepvalidate_test.go
upup/pkg/fi/cloudup/populate_cluster_spec_test.go
upup/pkg/fi/cloudup/populate_instancegroup_spec_test.go
upup/pkg/fi/cloudup/validation_test.go

Prevent kops edit cluster from writing the populated IG spec to state store

---

channels/alpha
channels/stable

Add release 1.25.0 to channels

---

docs/releases/1.25-NOTES.md

Release notes for 1.25.0

---

pkg/model/bootstrapscript.go
tests/integration/update_cluster/private-shared-ip/cloudformation.json
tests/integration/update_cluster/private-shared-ip/cloudformation.json.extracted.yaml
tests/integration/update_cluster/privatecilium/cloudformation.json
tests/integration/update_cluster/privatecilium/cloudformation.json.extracted.yaml
tests/integration/update_cluster/privatecilium2/cloudformation.json
tests/integration/update_cluster/privatecilium2/cloudformation.json.extracted.yaml
tests/integration/update_cluster/privateciliumadvanced/cloudformation.json
tests/integration/update_cluster/privateciliumadvanced/cloudformation.json.extracted.yaml

Avoid spurious changes with bastion hosts due to user data

---

upup/pkg/fi/cloudup/new_cluster.go

Validate `--zones` flag earlier

---

hack/verify-terraform.sh

Bump Terraform tag to v1.3.0

---

channels/alpha
channels/stable
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.23/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.24/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.25/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

Update channels with the latest Ubuntu images

---

go.sum
pkg/apis/kops/v1alpha2/cluster.go
protokube/cmd/protokube/main.go
protokube/pkg/gossip/scaleway/seeds.go
protokube/pkg/protokube/scaleway_volumes.go
upup/pkg/fi/cloudup/scaleway/cloud.go
vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/image_utils.go
vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_metadata_sdk.go
vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_sdk.go
vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_utils.go
vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/security_group_utils.go
vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/server_utils.go
vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/snapshot_utils.go
vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/volume_utils.go
vendor/github.com/scaleway/scaleway-sdk-go/api/marketplace/v1/marketplace_sdk.go
vendor/github.com/scaleway/scaleway-sdk-go/api/marketplace/v1/marketplace_utils.go
vendor/github.com/scaleway/scaleway-sdk-go/internal/async/wait.go
vendor/github.com/scaleway/scaleway-sdk-go/internal/marshaler/duration.go
vendor/github.com/scaleway/scaleway-sdk-go/internal/parameter/query.go
vendor/github.com/scaleway/scaleway-sdk-go/namegenerator/name_generator.go
vendor/modules.txt

The goal of this PR is to add support for Scaleway in protokube. This step will complete the bootstrapping of new nodes. For the time being, only gossip DNS is supported but a custom DNS will soon come in a next PR.

Scaleway support in protokube

---

cmd/kops/create_cluster.go
cmd/kops/create_cluster_integration_test.go
tests/integration/create_cluster/minimal-1.26-arm64/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-arm64/options.yaml
tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/private_gce/options.yaml
upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
upup/pkg/fi/cloudup/new_cluster.go

Add node/master size from create cluster into IG spec

---

nodeup/pkg/model/etc_hosts.go
upup/pkg/fi/nodeup/command.go
upup/pkg/fi/nodeup/nodetasks/service.go
upup/pkg/fi/nodeup/nodetasks/update_etc_hosts_task.go

Refactor NodeUp GossipBuilder to EtcHostsBuilder

---

pkg/model/components/nodeproblemdetector.go

Cherry pick of #14382 on release-1.25.
#14382: update NPD to version 0.8.12
```release-note
```

Automated cherry pick of #14382: update NPD to version 0.8.12

---

pkg/model/awsmodel/spotinst.go

Currently cluster creation is failing if `SpotInstanceGroupLabelOceanDefaultLaunchSpec` label is set for an instance group.
This should fix it.

Fix default launch spec detection for spotinst

---

pkg/model/bootstrapscript.go
pkg/model/resources/nodeup.go

More self-documenting and flexible than accepting a string.

nodeup script: accept strongly typed nodeup.Config

---

upup/pkg/fi/cloudup/gce/utils.go
upup/pkg/fi/cloudup/hetzner/cloud.go

Fixing Warning that should have been a Warningf

Fix typo in format string

---

pkg/model/awsmodel/spotinst.go

Cherry pick of #14389 on release-1.24.
#14389: Fix default launch spec detection
```release-note
```

Automated cherry pick of #14389: Fix default launch spec detection

---

upup/pkg/fi/cloudup/template_functions.go

there was one bug in 1.25.1 release so that is why we need to update this once more

update k8s openstack

---

cmd/kops/create_cluster.go
docs/cli/kops_create_cluster.md
docs/cluster_spec.md
docs/releases/1.26-NOTES.md
tests/integration/create_cluster/different-amis/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/new_cluster.go

Deprecate AWS Classic Load Balancer support for API

---

upup/pkg/fi/cloudup/template_functions.go

contains fix for https://github.com/kubernetes/kubernetes/issues/112793
cc @olemarkus @hakman

bump Openstack ccm version

---

pkg/instancegroups/instancegroups.go

Ensure kOps doesn't surge on karpenter IGs

---

pkg/instancegroups/rollingupdate.go

Rather than just returning the error from the first failing IG

Log and aggregate errors from rolling update

---

nodeup/pkg/model/etc_hosts.go
nodeup/pkg/model/kube_proxy.go
nodeup/pkg/model/protokube.go
pkg/apis/kops/cluster.go
pkg/apis/kops/validation/validation.go
pkg/dns/gossip.go
pkg/kubeconfig/create_kubecfg.go
pkg/model/awsmodel/api_loadbalancer.go
pkg/model/awsmodel/dns.go
pkg/model/awsmodel/iam.go
pkg/model/azuremodel/api_loadbalancer.go
pkg/model/components/etcdmanager/model.go
pkg/model/components/kopscontroller/template_functions.go
pkg/model/context.go
pkg/model/domodel/api_loadbalancer.go
pkg/model/gcemodel/firewall.go
pkg/model/openstackmodel/firewall.go
pkg/model/openstackmodel/servergroup.go
pkg/validation/validate_cluster.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/dns.go
upup/pkg/fi/cloudup/new_cluster.go
upup/pkg/fi/cloudup/populate_cluster_spec.go
upup/pkg/fi/cloudup/template_functions.go

Move Gossip check to cluster struct

---

tests/e2e/templates/many-addons.yaml.tmpl
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template

Also removing namespace from non-namespaced resource

Fix pdb for identity webhook

---

docs/releases/1.25-NOTES.md
docs/releases/1.26-NOTES.md
permalinks/upgrade_k8s.md

Update Kubernetes support removal documentation

---

addons/prometheus-operator/v0.19.0.yaml
addons/prometheus-operator/v0.26.0.yaml
addons/prometheus-operator/v0.29.0.yaml
addons/prometheus-operator/v0.42.1.yaml
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-metadata-proxy.addons.k8s.io-v0.1.12_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-metadata-proxy.addons.k8s.io-v0.1.12_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-metadata-proxy.addons.k8s.io-v0.1.12_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-metadata-proxy.addons.k8s.io-v0.1.12_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-metadata-proxy.addons.k8s.io-v0.1.12_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-metadata-proxy.addons.k8s.io-v0.1.12_content
upup/models/cloudup/resources/addons/metadata-proxy.addons.k8s.io/v0.1.12.yaml

See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.

Stop applying the beta.kubernetes.io/os

---

nodeup/pkg/model/etc_hosts.go
pkg/model/hetznermodel/loadbalancer.go
tests/integration/update_cluster/minimal_hetzner/kubernetes.tf
upup/pkg/fi/cloudup/hetznertasks/loadbalancer.go

A few more nits...
/cc @olemarkus

hetzner: Add listener for kops-controller when using it for node bootstrap

---

pkg/dump/dumper.go
pkg/resources/aws/aws.go

I don't have IPv6 connectivity to my test environment, so I could only test this so far.

Also dump logs from IPv6 nodes

---

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/coredns/coredns.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/coredns/manifest.yaml

Set customizable affinity and tolerations for coredns-autoscaler to match main coredns deployment

---

upup/pkg/fi/cloudup/do/cloud.go

do: Return ingress addresses even when public name is not set

---

pkg/model/iam/iam_builder_test.go
pkg/model/iam/tests/iam_builder_node_strict.json
pkg/model/iam/tests/iam_builder_node_strict_ecr.json

aws: Fix TestPolicyGeneration output

---

nodeup/pkg/model/etc_hosts.go

Use local API server on control plane nodes for clusters without DNS

---

pkg/apis/kops/validation/aws.go
upup/pkg/fi/cloudup/awsup/aws_cloud.go
upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
upup/pkg/fi/cloudup/new_cluster.go

Clearer error messages around instance types not found

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

https://go.dev/doc/devel/release#go1.19.minor

Update Go to v1.19.3

---

cmd/kops/toolbox_instance-selector.go
upup/pkg/fi/cloudup/awsup/aws_cloud.go
upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go

Fixes: #14571
Fixes: #14247
/cc @olemarkus @bwagner5

aws: Fix SIGSEGV when using instance selector

---

hack/install-ko.sh

Update ko to v0.12.0

---

cmd/kops/create_cluster.go
cmd/kops/create_cluster_integration_test.go
docs/cli/kops_create_cluster.md
tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal_feature-gates/options.yaml
upup/pkg/fi/cloudup/new_cluster.go

/cc @olemarkus @rifelpet @jsafrane

Add option for setting Kubernetes feature gates

---

pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/validation/validation.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/components/clusterautoscaler.go

This should simplify templating in #14519

Don't use ptr for CAS expander field

---

tests/integration/update_cluster/private-shared-ip/kubernetes.tf
tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
tests/integration/update_cluster/privatedns2/kubernetes.tf
tests/integration/update_cluster/shared_subnet/kubernetes.tf
tests/integration/update_cluster/shared_vpc/kubernetes.tf
tests/integration/update_cluster/unmanaged/kubernetes.tf
upup/pkg/fi/cloudup/awstasks/vpc.go
upup/pkg/fi/cloudup/terraform/hcl2_test.go
upup/pkg/fi/cloudup/terraform/target_hcl2.go
upup/pkg/fi/cloudup/terraformWriter/literal.go
upup/pkg/fi/cloudup/terraformWriter/writer.go

Will need this for IPv6 `/64#N` support.

Write Terraform vpc_cidr_block output for shared VPCs

---

tests/integration/create_cluster/ha_hetzner/options.yaml
tests/integration/create_cluster/minimal_hetzner/options.yaml
upup/pkg/fi/cloudup/new_cluster.go
upup/pkg/fi/cloudup/new_cluster_test.go
upup/pkg/fi/cloudup/populate_instancegroup_spec.go
upup/pkg/fi/cloudup/tests/channels/channel.yaml

hetzner: Set default image to `ubuntu-20.04`

---

pkg/model/gcemodel/firewall.go
pkg/wellknownports/wellknownports.go

gce: Allow Cilium to connect to its etcd cluster

---

docs/networking/calico.md
pkg/apis/kops/validation/validation.go

Update Calico documentation and validation

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha3/networking.go
pkg/apis/kops/validation/validation.go
pkg/apis/kops/validation/validation_test.go
pkg/model/iam/iam_builder.go
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_iam_role_policy_masters.minimal-ipv6.example.com_policy
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_iam_role_policy_nodes.minimal-ipv6.example.com_policy
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.25_content
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.25.yaml.template

Don't disable AWS src/dst checks in Calico IPv6

---

upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.22.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.25.yaml.template

This reverts commit 9105368a411d47b4a519d25ca7c369a7db2976e8.

Revert "Calico: Work around host port/conntrack problem"

---

upup/pkg/fi/cloudup/terraform/hcl2.go
upup/pkg/fi/cloudup/terraform/hcl2_test.go
upup/pkg/fi/cloudup/terraform/target_hcl2.go
upup/pkg/fi/cloudup/terraformWriter/literal.go

It's early days.
I'll probably need to define an interface implemented by `Literal` and other things that get printed with indentation and a leading key.

Refactor writing of terraform block

---

OWNERS
pkg/model/openstackmodel/OWNERS
pkg/resources/openstack/OWNERS
pkg/resources/spotinst/OWNERS
upup/pkg/fi/cloudup/openstack/OWNERS
upup/pkg/fi/cloudup/openstacktasks/OWNERS
upup/pkg/fi/cloudup/spotinsttasks/OWNERS

/cc @justinsb @johngmyers @olemarkus @rifelpet @zetaab 

Update OWNERS files

---

pkg/model/gcemodel/autoscalinggroup.go
tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/many-addons-gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/in-v1alpha2.yaml
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf

Ref: https://github.com/kubernetes/autoscaler/issues/718

gce: Set AUTOSCALER_ENV_VARS in instance template metadata

---

pkg/model/gcemodel/firewall.go
pkg/wellknownports/wellknownports.go
tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/many-addons-gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf

Closes https://github.com/kubernetes/kops/issues/14708

gce: Allow metrics-server to access kubelet API

---

docs/networking.md
docs/networking/cilium.md
pkg/apis/kops/validation/validation.go

Update documentation and validation for Cilium

---

cmd/kops/create_cluster.go
pkg/clouds/supported.go
pkg/zones/wellknown.go
upup/pkg/fi/cloudup/new_cluster.go

Slightly related to discussions around https://github.com/kubernetes/kops/pull/14682 and https://github.com/kubernetes/kops/pull/14683.
/cc @johngmyers @justinsb

Guess cloud provider from state store path

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.25_content
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.25.yaml.template

Calico: Don't try to upgrade IPAM in IPv6 clusters

---

pkg/kubeconfig/create_kubecfg.go
pkg/kubeconfig/create_kubecfg_test.go

kOps only pre-creates DNS records when there is no API load balancer. They are created later, by `dns-controller` or `external-dns`. In the mean time, the DNS name is cached as failed and operators will not be able to access the API.
Using the load balancer address instead of a DNS record should be a better approach from availability point of view, as DNS changes may be available late and take a long time to be visible for operators.
https://github.com/kubernetes/kops/blob/a9c6c4e5fa26d64d04fbf9f58aee9154090e7943/upup/pkg/fi/cloudup/dns.go#L252-L266
/cc @justinsb @johngmyers @rifelpet @olemarkus 
Closes https://github.com/kubernetes/kops/issues/14726

Always use load balancer address in kubeconfig

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/validation/validation.go

NTH: add API validation against unsupported option configurations

---

docs/cluster_spec.md
tests/e2e/scenarios/aws-ebs-csi/run-test.sh
tests/e2e/scenarios/aws-lb-controller/run-test.sh

Update AWS test scenarios

---

pkg/acls/gce/storage.go
util/pkg/vfs/context.go
util/pkg/vfs/gsfs.go

By initializing on demand, we avoid the need for some context.Context
during "build" time and better reflect the notion of (passive)
builders vs (active) requests.

vfs: avoid early initialization of GCS client

---

channels/pkg/api/channel.go
channels/pkg/channels/addon.go
channels/pkg/channels/addons_test.go
cmd/kops/integration_test.go
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-nodelocaldns.addons.k8s.io-k8s-1.12_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/many-addons-ccm-irsa26/in-v1alpha2.yaml
tests/integration/update_cluster/many-addons-ccm-irsa26/kubernetes.tf
upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/bootstrapchannelbuilder/cilium.go

Use OnDelete update strategy for node local dns cache

---

util/pkg/vfs/s3context.go
util/pkg/vfs/s3fs.go

We don't have the early initialization problem, but we do want to pass
the context through to the requests e.g. for tracing.

vfs: add context to s3 functions

---

tests/e2e/scenarios/addon-resource-tracking/run-test.sh

Not sure if this test is still useful, but updating it to not fail.

Update resource tracking test scenario

---

tests/e2e/kubetest2-kops/deployer/common.go

Fix logging of the generated e2e cluster name

---

tests/e2e/scenarios/addon-resource-tracking/run-test.sh

https://testgrid.k8s.io/kops-misc#kops-aws-addon-resource-tracking
/cc @olemarkus

Update resource tracking test scenario, again

---

util/pkg/vfs/context.go
util/pkg/vfs/swiftfs.go

Setting up context usage internally ready for the context to be
exposed.
Also avoid initializing the client until the first usage, making
building VFS path more of a builder function (deterministic, not
expected to fail for good inputs).

VFS: Add context to internals of Openstack Swift client

---

pkg/model/openstackmodel/context.go
protokube/pkg/protokube/openstack_volume.go
upup/pkg/fi/cloudup/new_cluster.go
upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstack/cloud_test.go
upup/pkg/fi/cloudup/utils.go

Ref: https://github.com/kubernetes/kops/pull/14846#issuecomment-1362430399
/cc @johngmyers @olemarkus

openstack: Refactor DNS client initialization

---

pkg/apis/kops/validation/instancegroup.go
pkg/apis/kops/validation/instancegroup_test.go

Not everybody reads https://kops.sigs.k8s.io/single-to-multi-master.

Validate control-plane IG size

---

util/pkg/vfs/sshfs.go

Generally cleaning up the SSH/SFTP code, only real change is to use posix rename.

vfs: cleanup of SSH code

---

util/pkg/vfs/sshfs.go

It doesn't follow quite the same patterns, but we still need to lay
the groundwork here.

vfs: wire context into SSHPath

---

cloudmock/aws/mockec2/images.go
go.mod
go.sum
tests/e2e/go.mod
tests/e2e/go.sum
upup/pkg/fi/cloudup/awsup/aws_cloud.go
vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
vendor/github.com/aws/aws-sdk-go/aws/version.go
vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface/interface.go
vendor/github.com/aws/aws-sdk-go/service/ssm/api.go
vendor/github.com/aws/aws-sdk-go/service/ssm/doc.go
vendor/modules.txt

AWS: Use pagination for DescribeImages call

---

cmd/kops/create_secret_ciliumpassword.go
cmd/kops/create_secret_dockerconfig.go
cmd/kops/create_secret_encryptionconfig.go
cmd/kops/create_secret_weavepassword.go
pkg/configserver/secretstore.go
upup/pkg/fi/fitasks/secret.go
upup/pkg/fi/secrets.go
upup/pkg/fi/secrets/clientset_secretstore.go
upup/pkg/fi/secrets/vfs_secretstore.go

Continuing the wiring as needed.

Add context to GetOrCreateSecret

---

upup/pkg/fi/cloudup/openstack/cloud.go

All openstack API loadbalancers does not have public name, so the logic does not work currently for those at all. with old code:
```
% ./kops export kubeconfig -v=2
Using cluster from kubectl context: jessetesti.k8s.local
I1227 15:52:57.573921   81441 factory.go:83] state store s3://xx-kaas-e2e-test
I1227 15:52:57.588060   81441 s3context.go:92] Found S3_ENDPOINT="https://s3.eu-north-1.amazonaws.com", using as non-AWS S3 backend
I1227 15:52:57.763358   81441 cloud.go:359] authenticating to keystone
I1227 15:52:58.104259   81441 cloud.go:490] Openstack using Octavia lbaasv2 api
W1227 15:52:58.104560   81441 create_kubecfg.go:70] Did not find API endpoint; may not be able to reach cluster
kOps has set your kubectl context to jessetesti.k8s.local
% kubectl get nodes
Unable to connect to the …
```

Fix ingress status for loadbalancers that does not have publicname

---

upup/pkg/fi/cloudup/openstack/cloud.go

Cherry pick of #14888 on release-1.26.
#14888: Fix ingress status for loadbalancers that does not have
```release-note
```

Automated cherry pick of #14888: Fix ingress status for loadbalancers that does not have

---

pkg/apis/kops/install/install.go
tests/codecs/componentconfig_test.go
tests/integration/conversion/integration_test.go

Don't expose v1alpha3 API

---

util/pkg/vfs/s3fs.go

We cache it in the S3Context anyway, and this potentially avoids some
race conditions (albeit likely harmless race conditions).

vfs: don't cache bucketDetails in S3Path

---

tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/lifecycle_phases/network-kubernetes.tf
tests/integration/update_cluster/many-addons-gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
tests/integration/update_cluster/minimal_hetzner/kubernetes.tf
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go
upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
upup/pkg/fi/cloudup/awstasks/render_test.go
upup/pkg/fi/cloudup/terraform/target.go
upup/pkg/fi/cloudup/terraform/target_hcl2.go
upup/pkg/fi/cloudup/terraformWriter/provider.go
upup/pkg/fi/cloudup/terraformWriter/writer.go
util/pkg/vfs/gsfs.go
util/pkg/vfs/memfs.go
util/pkg/vfs/s3fs.go
util/pkg/vfs/tests/gsfs_test.go
util/pkg/vfs/tests/s3fs_test.go
util/pkg/vfs/vfs.go

By adding them on-demand, it is arguably a little simpler as well.

Support multiple terraform file providers

---

nodeup/pkg/model/context.go
nodeup/pkg/model/kubelet.go
pkg/model/awsmodel/api_loadbalancer.go
pkg/model/awsmodel/autoscalinggroup.go
pkg/model/awsmodel/dns.go
pkg/model/awsmodel/network.go
pkg/model/awsmodel/spotinst.go
pkg/model/components/etcdmanager/model.go
upup/pkg/fi/nodeup/nodetasks/issue_cert.go
upup/pkg/fi/task.go

This means that we automatically check the error code.  A linter could
detect errors here (maybe), but in practice we can't recover from
errors here anyway.

EnsureTask should panic

---

upup/pkg/fi/cloudup/terraform/target_hcl2.go

As suggested in review of #14926, this approach might be more concise and clearer.
Builds on #14926

Refactor terraform provider version logic

---

docs/releases/1.26-NOTES.md

Add release note for https://github.com/kubernetes/kops/pull/14519

Add release note about CAS expander config

---

pkg/model/components/etcdmanager/model.go
pkg/model/master_volumes.go
pkg/model/scalewaymodel/instances.go
upup/pkg/fi/cloudup/scaleway/cloud.go
upup/pkg/fi/cloudup/scalewaytasks/instance.go

According to review comments in #14933, I did a bit of refactoring :
- replaced `TagRoleMaster` by `TagRoleControlPlane`
- added a check for 404 errors in the delete functions (no need to return an error in that case)
- added the field `Role` in the Instance task (will be useful for the LoadBalancer task)

scaleway: refactoring: instance and tags

---

tests/e2e/scenarios/lib/common.sh

Fixes #15028
/test pull-kops-e2e-aws-load-balancer-controller

Fix LBC e2e after dropping override feature flag

---

nodeup/pkg/model/containerd.go

If the non-masquerade CIDR is not set, take that as an indication that
we don't want masquerade, rather than failing nodeup.
Not setting a non-masquerade CIDR means that we likely won't preserve
pod IPs for pod-to-pod traffic, but likely just means that more
NATting is done than might be needed.
Omitting the value can also be useful if we're using something like
the ip-masq-agent to manage masquerade rules for us.

nodeup: don't set up masquerade if nonMasqueradeCIDR not set

---

pkg/dump/dumper.go

This is helpful debugging information when we see network issues.

tests: Capture iptables chains

---

tests/e2e/scenarios/addon-resource-tracking/run-test.sh

Feature flags need to be set before sourcing common.sh

Fix resource-tracking scenario

---

cmd/kops-controller/pkg/server/server.go
upup/pkg/fi/cloudup/openstack/verifier.go

Add IPv6 support to the openstack verifier and polish up a few error messages.

openstack verifier: support IPv6

---

upup/pkg/fi/executor.go

This is likely safe without a mutex, but I don't believe it is
guaranteed to be safe.

executor: Avoid writing into slice without a mutex

---

pkg/nodeidentity/openstack/identify.go

OpenStack: add k8s node labels 

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.12.2

Bump AWS CNI to 1.12.2

---

nodeup/pkg/model/bootstrap_client.go
pkg/apis/kops/model/features.go
upup/pkg/fi/nodeup/nodetasks/bootstrap_client.go

It's a little simpler and should speed up our boot.

Use cloud-discovery on GCE in gossip mode

---

pkg/resources/dump.go
pkg/resources/hetzner/resources.go
upup/pkg/fi/cloudup/hetzner/utils.go

hetzner: support toolbox dump of instances

---

util/pkg/vfs/gsfs.go
util/pkg/vfs/tests/gsfs_test.go

We are using the schema of google_storage_object_acl.

gce terraform: Use google_storage_object_acl

---

nodeup/pkg/bootstrap/install.go
nodeup/pkg/bootstrap/tests/simple/tasks.yaml

Reverts kubernetes/kops#15078
/cc @zetaab @justinsb

Revert "disable kops-configuration.service after successful execution"

---

nodeup/pkg/bootstrap/install.go
nodeup/pkg/bootstrap/tests/simple/tasks.yaml

Reverts kubernetes/kops#15085
/cc @zetaab @justinsb

Revert "Automated cherry pick of #15078: disable kops-configuration.service after successful execution"

---

pkg/model/openstackmodel/firewall.go

Cherry pick of #15147 on release-1.26.
#15147: remove cadvisor and etcd client fw rule
```release-note
```

Automated cherry pick of #15147: remove cadvisor and etcd client fw rule

---

pkg/resources/hetzner/resources.go

Cherry pick of #15141 on release-1.26.
#15141: hetzner: add dependency logic to deletion
```release-note
```

Automated cherry pick of #15141: hetzner: add dependency logic to deletion

---

pkg/model/awsmodel/autoscalinggroup.go
tests/integration/update_cluster/minimal-warmpool/kubernetes.tf
upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go
upup/pkg/fi/cloudup/awstasks/warmpool.go

Addresses https://github.com/kubernetes/kops/issues/11633

Add terraform target support for configuring Warm Pool

---

pkg/apis/kops/validation/aws.go
pkg/apis/kops/validation/aws_test.go
pkg/apis/kops/validation/validation.go
tests/integration/update_cluster/complex/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
tests/integration/update_cluster/complex/in-v1alpha2.yaml
tests/integration/update_cluster/complex/kubernetes.tf
upup/pkg/fi/cloudup/defaults.go

Ensure that everything on AWS that tests NetworkCIDR also considers AdditionalNetworkCIDRs appropriately.

Improve support for AdditionalNetworkCIDRs

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

Update Go to v1.19.7

---

nodeup/pkg/model/bootstrap_client.go
pkg/apis/kops/model/features.go
upup/pkg/fi/nodeup/nodetasks/bootstrap_client.go

#15121: Use cloud-discovery on GCE in gossip mode

Automated cherry pick of #15121 release 1.26

---

docs/getting_started/scaleway.md
docs/state.md

This PR adds documentation to the Scaleway provider.

scaleway: documentation

---

channels/alpha
channels/stable
docs/releases/1.26-NOTES.md

/cc @justinsb @olemarkus @zetaab @rifelpet

Update channels and release note for 1.26

---

README.md

**Safe to merge PR**:
Added *CI* and *latest release* status badges to readme:
[![CI](https://github.com/kubernetes/kops/actions/workflows/main.yml/badge.svg)](https://github.com/kubernetes/kops/actions/workflows/main.yml) ![GitHub release (latest SemVer)](https://img.shields.io/github/v/release/kubernetes/kops)

Documentation: add CI and latest release badges

---

upup/pkg/fi/cloudup/gcetasks/httphealthcheck.go

Add terraform rendering to GCP HTTP Health Check

---

pkg/kubeconfig/create_kubecfg.go
pkg/kubeconfig/create_kubecfg_test.go

Fix behaviour for `kops export kubeconfig --internal`

---

channels/alpha
channels/stable

- https://github.com/kubernetes/kubernetes/releases/tag/v1.26.3
- https://github.com/kubernetes/kubernetes/releases/tag/v1.25.8
- https://github.com/kubernetes/kubernetes/releases/tag/v1.24.12

Bump k8s versions to latest

---

upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template
upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/template_functions.go

images are same than in docker hub, so it should not make big difference

switch to use registry.k8s.io images for openstack

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.12.5

Bump AWS CNI to 1.25.5

---

pkg/model/awsmodel/spotinst.go

This PR adds setting support for VNG size limits in launch spec.

feat(spot): Setting the VNG Size Limits in Launch Spec

---

upup/pkg/fi/cloudup/bootstrapchannelbuilder/cilium.go

We allow the cilium manifest to be specified as an addon, to enable
better testing of new cilium versions.

Allow Cilium manifest to be replaced (for testing)

---

tests/e2e/scenarios/scalability/README.md
tests/e2e/scenarios/scalability/run-test.sh

We want to try some scalability testing on AWS.

test scenarios: create simple scalability test

---

tests/e2e/scenarios/lib/common.sh
tests/e2e/scenarios/scalability/run-test.sh
upup/pkg/fi/cloudup/awsup/aws_cloud.go

Update the scalability test so it passes: use calico, also a fix misc fixes.

Update scalability test so it passes

---

pkg/model/gcemodel/storageacl.go

The parameters were the wrong way round.

gce: Fix log message about bucket level IAM

---

pkg/model/gcemodel/autoscalinggroup.go
pkg/model/gcemodel/network.go
tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/many-addons-gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
upup/pkg/fi/cloudup/gcetasks/instance.go
upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
upup/pkg/fi/cloudup/gcetasks/subnet.go

We need to specify StackType & IPv6AccessType

gce: Add IPv6 support to subnet/instances

---

go.mod
vendor/modules.txt

Fixes failure in dependencies update job: https://github.com/kubernetes/kops/actions/workflows/update-deps.yml
Ref: https://github.com/helm/helm/issues/11821

Pin github.com/docker/* to v20.10.21+incompatible

---

docs/architecture/kops-controller.md

link for non existing feature was not available so removed.
https://github.com/kubernetes/kops/blob/master/docs/architecture/kops-controller.md

broken link removed as not available

---

tests/e2e/scenarios/aws-boskos/README.md
tests/e2e/scenarios/aws-boskos/run-test.sh

A simple e2e test for running with boskos on AWS.

Create simple test that runs with boskos

---

upup/pkg/fi/cloudup/scaleway/cloud.go
upup/pkg/fi/cloudup/scalewaytasks/lb_backend.go
upup/pkg/fi/cloudup/scalewaytasks/lb_frontend.go
upup/pkg/fi/cloudup/scalewaytasks/loadbalancer.go

This PR fixes a few errors a noticed since the merge of the loadbalancer part (#14933)

scaleway: small fixes in loadbalancer tasks

---

cmd/kops-controller/main.go
cmd/kops-controller/pkg/server/server.go

We now do this across all clouds, as it has been demonstrated on
OpenStack.

Block bootstrap when the node already exists

---

docs/releases/1.26-NOTES.md
docs/releases/1.27-NOTES.md

This change is clarify that Spotinst is to support this tool

Spotinst: update  help wanted in release doc

---

tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
upup/models/cloudup/resources/addons/gcp-pd-csi-driver.addons.k8s.io/k8s-1.23.yaml.template

Update gcp-compute-persistent-disk-csi-driver to v1.10.1

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

**What this PR does / why we need it**: Bumping AWS CNI to latest version
**Special notes for your reviewer**: 
- https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.12.6

Bump AWS CNI version to 1.12.6

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/networking.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/in-v1alpha2.yaml
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.12.yaml.template

**What this PR does / why we need it**: Add support for customizing annotations on the Cilium Operator Deployment / Pod
fixes #15310

Support Cilium Operator Pod Annotations

---

channels/alpha
channels/stable
tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.23/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.24/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.25/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-arm64/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-irsa/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

Promotes #15386 from alpha channel to stable channel

Promote alpha to stable (channels)

---

pkg/model/awsmodel/spotinst.go
upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
upup/pkg/fi/cloudup/spotinsttasks/ocean.go

add AWS instance metadata v2 support. fix Ocean Capacity in mod SpotinstOceanTemplate .

Spotinst: integrate AWS instance metadata config to instance groups #2

---

upup/pkg/fi/cloudup/scaleway/cloud.go
upup/pkg/fi/cloudup/scalewaytasks/instance.go

This PR makes sure that all commercial types of instances are supported with Scaleway clusters and not just the default one (`DEV1-M`). Some of our offers have no local storage so in those cases we have to specify the size of the block storage volume used to boot so that it has enough space.
We also decided to terminate the instances when deleting them because it's much faster than to stop and delete, as no backup is created.

scaleway: instance resize and termination

---

nodeup/pkg/model/context.go
nodeup/pkg/model/networking/common.go
tests/integration/update_cluster/minimal/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal/data/aws_s3_object_nodeupconfig-nodes_content
upup/pkg/fi/cloudup/networking.go

Ref: https://github.com/kubernetes/kubernetes/pull/115125

Update CNI plugins to v1.2.0 for K8s 1.27+

---

upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstack/cloud_test.go

With this change the external network info will be set, even if there is no loadbalancer support enabled. Otherwise this leads to an error when kOps creates a network with router.
fixes #15401

OpenStack: Set FloatingIP support if router spec exists

---

cmd/kops-controller/pkg/server/server.go

/cc @justinsb @zetaab 
/assign @justinsb 
/hold

kops-controller: Return `http.StatusConflict` only when node is ready

---

upup/pkg/fi/cloudup/hetznertasks/loadbalancer.go

Extend the task to allow adding services - this is needed if we want
to support kops-controller where we didn't previously.

Hetzner LoadBalancer: support adding services

---

pkg/apis/kops/model/features.go
pkg/model/hetznermodel/loadbalancer.go
upup/pkg/fi/cloudup/apply_cluster.go

This is a more secure configuration.

Use kops-controller on hetzner, even with gossip

---

pkg/model/openstackmodel/firewall.go

These new security group rules to allow scraping of metrics for kubeControllerManager on port 10257/tcp and kubeScheduler on port 10259/tcp

New OpenStack security group rules for metrics

---

cloudbuild.yaml

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/kops-postsubmit-push-to-staging/1670852544638750720
/cc @johngmyers @justinsb @rifelpet

Fix promotion of `kops-utils-cp` - cloudbuild

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Bump AWS CNI to 1.13.2 (minor & patch version bump)
Vendored from https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.13.2

Bump AWS CNI to version 1.13.2

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Bump Cert Manager to v1.12.2 (patch version bump)
Vendored from released asset: https://github.com/cert-manager/cert-manager/releases/tag/v1.12.2

Bump cert-manager to version 1.12.2

---

cloudmock/scaleway/mockdns/api.go
dns-controller/cmd/dns-controller/main.go
dnsprovider/pkg/dnsprovider/providers/scaleway/dns.go
dnsprovider/pkg/dnsprovider/providers/scaleway/dns_test.go
dnsprovider/pkg/dnsprovider/providers/scaleway/domain_api_interface.go
docs/getting_started/scaleway.md
pkg/resources/scaleway/resources.go
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-dns-controller.addons.k8s.io-k8s-1.12_content
upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/scaleway/cloud.go
upup/pkg/fi/cloudup/template_functions.go
vendor/github.com/scaleway/scaleway-sdk-go/api/domain/v2beta1/domain_sdk.go
vendor/github.com/scaleway/scaleway-sdk-go/api/domain/v2beta1/domain_utils.go
vendor/modules.txt

Cherry pick of #15393 on release-1.27.
#15393: added domain to vendor
```release-note
```

Automated cherry pick of #15393: scaleway: dns support

---

pkg/model/azuremodel/vmscaleset.go
pkg/model/azuremodel/vmscaleset_test.go
upup/pkg/fi/cloudup/azure/azure_cloud.go
upup/pkg/fi/cloudup/azuretasks/vmscaleset.go
upup/pkg/fi/cloudup/new_cluster.go

azure: Enable support for public load balancer

---

cmd/kops/create_cluster.go
cmd/kops/create_cluster_integration_test.go
cmd/kops/integration_test.go
docs/cli/kops_create_cluster.md
docs/operations/karpenter.md
docs/releases/1.26-NOTES.md
docs/releases/1.27-NOTES.md
pkg/apis/kops/validation/validation.go
pkg/featureflag/featureflag.go
tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/scenarios/lib/common.sh
tests/e2e/scenarios/upgrade-ab/run-test.sh
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

Cherry pick of #15144 on release-1.27.
#15144: feat(karpenter): Upgrade to version 0.27.0
```release-note
```

Automated cherry pick of #15144: Upgrade Karpenter to v0.27.5

---

docs/getting_started/openstack.md

OpenStack needs an additional option to get access to NodePorts for loadbalancers.
This PR is aiming to document this behavior.

doc: Added documentation about loadbalancer and security group configuration

---

cmd/kops/util/factory.go

Cherry pick of #15593 on release-1.27.
#15593: Increase client-side throttling limits
```release-note
```

Automated cherry pick of #15593: Increase client-side throttling limits

---

pkg/model/awsmodel/network.go

aws: Allow using the same instance ID as egress for multiple subnets

---

docs/getting_started/scaleway.md

This PR improves the documentation for Scaleway. It adds :
- information about the profiles feature
- information about a few default values and how to override them
- links to other pages
It also removes the temporary fix added in #15350 which is no longer needed.

scaleway: documentation improvement

---

nodeup/pkg/model/context.go
nodeup/pkg/model/kubelet.go
pkg/apis/kops/validation/validation.go
pkg/model/bootstrapscript.go
pkg/model/components/kubecontrollermanager.go
pkg/model/components/kubelet.go

I don't think we have to release-note this because bootstrap tokens don't work with kops-controller bootstrap.

Remove support for bootstrap tokens

---

cmd/kops-controller/controllers/awsipam.go

Cleanup; no change in behavior.

Fix comment on patchNodePodCIDRs

---

tests/integration/update_cluster/minimal-etcd/data/aws_launch_template_master-us-test-1a.masters.minimal-etcd.example.com_user_data
tests/integration/update_cluster/minimal-etcd/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-etcd/data/aws_s3_object_manifests-etcdmanager-events-master-us-test-1a_content
upup/pkg/fi/cloudup/defaults.go

Fix modifying backupRetentionDays

---

go.mod
go.sum
upup/pkg/fi/cloudup/scalewaytasks/instance.go
vendor/github.com/scaleway/scaleway-sdk-go/api/domain/v2beta1/domain_sdk.go
vendor/github.com/scaleway/scaleway-sdk-go/api/iam/v1alpha1/iam_sdk.go
vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_sdk.go
vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_utils.go
vendor/github.com/scaleway/scaleway-sdk-go/api/lb/v1/lb_sdk.go
vendor/github.com/scaleway/scaleway-sdk-go/scw/config.go
vendor/github.com/scaleway/scaleway-sdk-go/scw/custom_types.go
vendor/modules.txt

This breaks the automatic dependencies update workflow:
https://github.com/kubernetes/kops/actions/workflows/update-deps.yml

Update scaleway-sdk-go to v1.0.0-beta.19

---

upup/pkg/fi/cloudup/azuretasks/networksecuritygroup.go

azure: Avoid spurious changes in NetworkSecurityGroup

---

pkg/apis/kops/v1alpha2/cluster.go
tests/e2e/pkg/tester/skip_regex.go

Fix tests bug introduced by #15676

Skip ssh-to-all-nodes test in private topology

---

pkg/assets/builder.go

Print error message when digest image fails

---

upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go

Fixes https://testgrid.k8s.io/kops-misc#kops-warm-pool
I believe kops hasn't created the nodes ASG because it interpreted the WarmPool field as a dependency (introduced in https://github.com/kubernetes/kops/pull/15153), so it tries to create the WarmPool before the ASG.
The toolbox dump doesn't mention any instances from the nodes ASG: https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-warm-pool/1685665134501957632/artifacts/toolbox-dump.yaml

Fix WarmPool with --target direct

---

upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go

Cherry pick of #15722 on release-1.27.
#15722: Fix WarmPool with --target direct

Automated cherry pick of #15722: Fix WarmPool with --target direct

---

upup/pkg/fi/cloudup/scalewaytasks/volume.go

This PR implements changes to volumes which were not handled until now.

scaleway: handle changes to volumes

---

tests/e2e/scenarios/scalability/run-test.sh

Also waiting for this PR to merge - https://github.com/kubernetes/test-infra/pull/30268

Add prefix delegation for amazon vpc cni in scale tests

---

tests/e2e/kubetest2-kops/deployer/up.go

Use `--master-count` in testing for backwards compatibility

---

tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/in-v1alpha2.yaml
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.13.yaml.template

Fix hubble certificate dnsname

---

tests/e2e/scenarios/scalability/run-test.sh

/cc @johngmyers @rifelpet @dims 
@prateekgogia

Use dns=none for scale tests

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go

That's a fix for buildKarpenterGroup func.
That's an edge case that happens only when an AWS account has more than 200 launch templates (the max per page) and the one with Karpenter as a manager is on the second page. 
The aws-sdk ec2 func DescribeLaunchTemplates does not return directly a single launch template given the filters if the launch template is on the second page. Instead of that the return is empty with a nextToken, and the paginator fixes that behavior.
Without the paginator the code panics if the function returns a nextToken

aws: implement paginator for DescribeLaunchTemplate on buildKarpenterGroup

---

cmd/kops/create_cluster.go
cmd/kops/create_sshpublickey.go
cmd/kops/rolling-update_cluster.go
cmd/kops/toolbox_template.go

Mark flags as deprecated instead of normalizing

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

Will be needed for scale tests.
@prateekgogia

kcm: Add support for `--endpoint/slice-updates-batch-period`

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go

Cherry pick of #15785 on release-1.27.
#15785: fix: implement LaunchTemplate with paginator on
```release-note
```

Automated cherry pick of #15785: fix: implement LaunchTemplate with paginator on

---

pkg/util/subnet/subnet.go
tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_openstack/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.23/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.24/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.25/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-arm64/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-irsa/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.27/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/subnets.go
upup/pkg/fi/cloudup/subnets_test.go

Follow-up to https://github.com/kubernetes/kops/pull/15791.

Split network CIDR into even bigger subnets

---

pkg/apis/kops/model/features.go
upup/pkg/fi/cloudup/apply_cluster.go

Cherry pick of #15815 on release-1.27.
#15815: Fix gossip on DigitalOcean
```release-note
```

Automated cherry pick of #15815: Fix gossip on DigitalOcean

---

tests/e2e/scenarios/scalability/run-test.sh

implement one suggestion from Amazon Support:
https://kubernetes.slack.com/archives/C09QZTRH7/p1693477242164839?thread_ts=1693477191.647929&cid=C09QZTRH7

Let us spread across all AZ(s) in us-east-2

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha3/networking.go

Should not have any code impact.

Clarify comment on nonMasqueradeCIDR field.

---

Makefile

https://github.com/ko-build/ko/releases/tag/v0.14.1

Update ko to v0.14.1

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.25_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.25_content
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.25.yaml.template

https://github.com/projectcalico/calico/releases/tag/v3.25.2

Update Calico to v3.25.2

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

/cc @justinsb @johngmyers @rifelpet

Update Go to v1.21.1

---

upup/pkg/fi/cloudup/template_functions.go

This reverts commit f80a66903bc6beaf129b6efb794065b028db7a32.
I think the commit is actually a good one, but I accidentally included it in another unrelated PR, and we didn't get the chance to discuss it properly!

Revert "WIP: Need to publish IPv4 DNS records"

---

tests/e2e/scenarios/scalability/run-test.sh

- we need to split etcd for better performance.

scale-test: Need for separate etcd cluster for events

---

tests/e2e/scenarios/scalability/run-test.sh

scale-test: Re-enable etcd metrics

---

pkg/model/gcemodel/firewall.go

These work with IPv6, and this means we don't need to set up the (more
fragile) CIDR based rules.

gce ipv6: we can use network tags with ipv6 addresses

---

pkg/model/components/gcpcloudcontrollermanager.go
tests/e2e/kubetest2-kops/deployer/dumplogs.go
tests/integration/update_cluster/ha_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
upup/models/cloudup/resources/addons/gcp-cloud-controller.addons.k8s.io/k8s-1.23.yaml.template

https://kubernetes.slack.com/archives/C09QZ4DQB/p1695816800117139

bump gcp ccm image and dump more resources

---

tests/e2e/kubetest2-kops/deployer/dumplogs.go

ref: https://github.com/kubernetes/kops/issues/15973

Attempt to dump cluster info when encountering earlier errors

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/cluster.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/cluster.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
upup/pkg/fi/cloudup/apply_cluster.go

Add support for installing additional packages at cluster level

---

pkg/model/awsmodel/api_loadbalancer.go
pkg/model/awsmodel/firewall.go
tests/integration/update_cluster/minimal-dns-none/kubernetes.tf

This was broken in #15993
/cc @johngmyers @rifelpet

aws: Attach security group to NLBs for kops-controller

---

upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstack/server_group.go

Cherry pick of #16022 on release-1.28.
#16022: fix instance group validation if using serverGroupName
```release-note
```

Automated cherry pick of #16022: fix instance group validation if using serverGroupName

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

Refs: https://github.com/kubernetes/kops/issues/15909

Add support for --cluster-signing-duration KCM flag

---

pkg/apis/kops/validation/validation.go
pkg/apis/kops/validation/validation_test.go

We aren't aiming to do this in general, but if we can easily help
users find the new option for deprecated flags, that will save
everyone time.
Closes #15909

Add validation to help users move from experimentClusterSigningDuration

---

docs/addons.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/components/clusterautoscaler.go
tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_cluster-completed.spec_content
upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template

Closes https://github.com/kubernetes/kops/issues/16057

Support setting CAS skip-nodes-with-custom-controller-pods parameter

---

nodeup/pkg/model/kubectl.go
nodeup/pkg/model/protokube.go
nodeup/pkg/model/update_service.go
pkg/kubemanifest/visitor.go
pkg/nodeidentity/openstack/identify.go
pkg/nodeidentity/scaleway/identify.go
protokube/cmd/protokube/main.go
upup/pkg/fi/cloudup/awstasks/iamrole.go

See failed tests in https://github.com/kubernetes/kops/pull/16075.

Fix vet errors

---

docs/networking/aws-vpc.md
docs/operations/images.md
docs/releases/1.27-NOTES.md
docs/releases/1.28-NOTES.md
docs/releases/1.29-NOTES.md

Relates to https://github.com/kubernetes/kops/issues/15720

Document incompatability with Amazon VPC CNI and 22.04

---

docs/getting_started/openstack.md

Fix Designate naming typo

---

cmd/kops/edit_cluster.go
docs/cli/kops_edit_cluster.md

Improve kops edit command

---

docs/getting_started/openstack.md

Update OpenStack documentation to replace deprecated arguments

---

tests/e2e/scenarios/scalability/run-test.sh

Order instances in terms of lowest to highest cost basis for cost efficiency - https://docs.aws.amazon.com/autoscaling/ec2/userguide/allocation-strategies.html#on-demand-allocation-strategy

Order instances in terms of cost

---

tests/e2e/scenarios/scalability/run-test.sh

Related issue - https://github.com/kubernetes/k8s.io/issues/6165

Reduce disk volume size to reduce cost

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

Includes some security fixes in net/http

chore: Bump go to 1.21.5

---

pkg/applylib/applyset/health.go

Ignore HPA status when applying addons

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml

Bump metrics-server to 0.6.4

---

pkg/dump/podlogs.go

Should make it easier to spot pods with restarts.
/cc @rifelpet

Dump previous and current container logs separately

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template

/cc @dims @hakuna-matatah @rifelpet @olemarkus

aws: Add option for setting QPS and Burst for EBS CSI Driver

---

pkg/dump/resourcedumper.go

Another followup to https://github.com/kubernetes/kops/pull/16196. This will help with troubleshooting some [cert-manager issues](https://testgrid.k8s.io/kops-misc#kops-aws-aws-load-balancer-controller) where secrets aren't being created
Example:
```yaml
apiVersion: v1
items:
- apiVersion: v1
data:
foo1: REDACTED
foo2: REDACTED
kind: Secret
metadata:
creationTimestamp: "2024-01-04T01:47:53Z"
name: foo
namespace: default
resourceVersion: "268757"
uid: 4118f35b-b1b1-47ec-a3ae-676415ff3b27
type: Opaque
kind: SecretList
metadata:
resourceVersion: "269090"
```

Dump and redact secrets

---

tests/e2e/scenarios/scalability/run-test.sh

scale-test: Reduce validation count and interval

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
tests/integration/update_cluster/complex/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-bootstrap_content
tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
tests/integration/update_cluster/complex/in-v1alpha2.yaml

/cc @rifelpet @hakuna-matatah @dims

Add option for setting CCM ConcurrentNodeSyncs

---

pkg/resources/aws/aws.go

/cc @rifelpet 
This seems to be slower though

aws: Skip deleting ASG instances without volumes

---

cmd/kops/delete_cluster.go
docs/cli/kops_delete_cluster.md
tests/e2e/kubetest2-kops/deployer/down.go

test: Improve cluster deletion defaults

---

pkg/resources/aws/aws.go

Delete became too slow for 5k nodes (about 50 min).
/cc @rifelpet

Revert "aws: Skip deleting ASG instances without volumes"

---

pkg/resources/aws/aws.go

/cc @rifelpet @upodroid @olemarkus @zetaab

aws: Terminate ASG instances in batches of 100 instances

---

mkdocs.yml

Add 1.28 release notes to docs menu

---

pkg/model/awsmodel/api_loadbalancer.go
pkg/model/awsmodel/bastion.go

Tweak: Set Scheme on NLB tasks for public load balancers

---

channels/stable
tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.24/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.25/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-arm64/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-irsa/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.27/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.28/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.29/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

Promotes alpha channel to stable channel with changes from #16284

chore(channels): promote alpha to stable

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml.template

https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.7.0

Upgrade AWS Load Balancer Controller to v2.7.0

---

docs/welcome/office_hours.md

Spotted one typo and so ran a spellcheck on the page.

Docs: fix typos in office hours page

---

cloudmock/aws/mocksqs/api.go
pkg/resources/aws/sqs.go

deletion: tolerate concurrent SQS queue deletion

---

pkg/model/azuremodel/api_loadbalancer.go
upup/pkg/fi/cloudup/azuretasks/loadbalancer.go
upup/pkg/fi/cloudup/azuretasks/loadbalancer_test.go

Similar to https://github.com/kubernetes/kops/pull/16271.
/cc @zetaab @rifelpet

azure: Replace lb.ForAPIServer with lb.WellKnownServices

---

cmd/kops/create.go
docs/cli/kops_create.md

create command: remove example docs say is not implemented yet.

---

.devcontainer/devcontainer.json
.devcontainer/setup.sh
.devcontainer/welcome-message.txt
.gitignore

Related to https://github.com/kubernetes/kubernetes/pull/121561

add support for devcontainer

---

upup/pkg/fi/cloudup/azuretasks/loadbalancer.go
upup/pkg/fi/cloudup/openstacktasks/port.go

This will ensure I don't mistakenly break the contract again.

azure: Mark a few tasks as implementing HasAddress

---

tests/e2e/pkg/tester/skip_regex.go

ref: https://github.com/kubernetes/test-infra/pull/32056
https://github.com/kubernetes/kops/issues/16349
https://github.com/kubernetes/kubernetes/issues/123255

Skip hostname test for all aws jobs by default

---

pkg/model/gcemodel/api_loadbalancer.go
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/gcetasks/forwardingrule.go

- gce: Always create an internal load balancer
- gce: Prune old forwarding rules
- gce: use internal IP address for node -> control-plane communication

GCE: Use internal load balancer for node to control-plane traffic

---

docs/releases/1.29-NOTES.md

Document our deferred deletion flows.

docs: Update relnotes for 1.29 for deferred deletion

---

clusterapi/bootstrap/controllers/kopsconfig_controller.go
hack/set-version
pkg/commands/toolbox_enroll.go
pkg/nodemodel/fileassets.go
pkg/nodemodel/wellknownassets/cni.go
pkg/nodemodel/wellknownassets/cni_test.go
pkg/nodemodel/wellknownassets/kopsassets.go
pkg/nodemodel/wellknownassets/kopsassets_test.go
upup/pkg/fi/cloudup/apply_cluster.go

Continuing the node/infra splitting.

refactor: isolate asset construction out of cloudup

---

pkg/apis/kops/cluster.go
pkg/apis/nodeup/config.go
pkg/instancegroups/instancegroups.go
pkg/model/azuremodel/context.go
upup/pkg/fi/cloudup/azure/applicationsecuritygroup.go
upup/pkg/fi/cloudup/azure/azure_cloud.go
upup/pkg/fi/cloudup/azure/loadbalancer.go
upup/pkg/fi/cloudup/azure/natgateway.go
upup/pkg/fi/cloudup/azure/networksecuritygroup.go
upup/pkg/fi/cloudup/azure/publicipaddress.go
upup/pkg/fi/cloudup/azure/routetable.go
upup/pkg/fi/cloudup/azure/status_test.go
upup/pkg/fi/cloudup/azure/virtualnetwork.go
upup/pkg/fi/cloudup/azure/vmscaleset.go
upup/pkg/fi/cloudup/azure/vmscalesetvm.go
upup/pkg/fi/cloudup/azuretasks/subnet.go
upup/pkg/fi/cloudup/azuretasks/testing.go

azure: Various updates

---

upup/pkg/fi/cloudup/azure/verifier.go

Closes https://github.com/kubernetes/kops/issues/16464

azure: Use lowercase for node names

---

nodeup/pkg/bootstrap/install.go
nodeup/pkg/model/protokube.go
util/pkg/vfs/context.go

/cc @rifelpet @justinsb @zetaab

aliyun: Remove some leftovers

---

upup/pkg/fi/cloudup/azure/azure_cloud.go
upup/pkg/fi/cloudup/utils.go

azure: Fix instance deletion

---

pkg/model/components/hetznercloudcontrollermanager.go
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.example.com-addons-hcloud-cloud-controller.addons.k8s.io-k8s-1.22_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.example.com-addons-hcloud-csi-driver.addons.k8s.io-k8s-1.22_content
upup/models/cloudup/resources/addons/hcloud-cloud-controller.addons.k8s.io/k8s-1.22.yaml.template
upup/models/cloudup/resources/addons/hcloud-csi-driver.addons.k8s.io/k8s-1.22.yaml.template

/cc @justinsb @rifelpet @zetaab

hetzner: Update components before release 

---

pkg/model/components/clusterautoscaler.go
tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cas-priority-expander-custom.example.com-addons-bootstrap_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cas-priority-expander-custom.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cas-priority-expander.example.com-addons-bootstrap_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cas-priority-expander.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content

/cc @rifelpet @zetaab @justinsb

Update cluster-autoscaler to v1.30.0

---

pkg/model/components/containerd.go
tests/integration/update_cluster/additionalobjects/data/aws_launch_template_master-us-test-1a.masters.additionalobjects.example.com_user_data
tests/integration/update_cluster/additionalobjects/data/aws_launch_template_nodes.additionalobjects.example.com_user_data
tests/integration/update_cluster/additionalobjects/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/additionalobjects/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/additionalobjects/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.28/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.28/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.28/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.28/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.28/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.29/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.29/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.29/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.29/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.29/data/aws_s3_object_nodeupconfig-nodes_content

/cc @rifelpet @zetaab @justinsb

Update containerd to v1.7.16

---

docs/operations/images.md
util/pkg/distributions/distributions.go
util/pkg/distributions/identify.go
util/pkg/distributions/identify_test.go
util/pkg/distributions/tests/ubuntu2404/etc/os-release

/cc @rifelpet @justinsb @zetaab

Initial support for Ubuntu 24.04 (Noble Numbat)

---

tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
upup/models/cloudup/resources/addons/gcp-pd-csi-driver.addons.k8s.io/k8s-1.23.yaml.template

- Update gcp-csi driver patch version to 1.10.13
- autogen: update expected output for gcp-csi bump to 1.10.13

Update gcp-csi driver patch version to 1.10.13

---

util/pkg/vfs/s3context.go

Ref: https://github.com/kubernetes/cloud-provider-aws/pull/914#issuecomment-2115591516
Inspired by https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/endpoints/.
/cc @rifelpet @justinsb

aws: Use EndpointResolverV2 for enabling dual-stack

---

channels/alpha

/cc @zetaab @rifelpet @justinsb

chore: Bump alpha channel with June releases

---

pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

We'll see if this fixes #16597
https://github.com/cilium/cilium/releases/tag/v1.15.6
https://github.com/cilium/cilium/releases/tag/v1.15.5

Upgrade Cilium to v1.15.6

---

mkdocs.yml

added release 1.29  in doc menu

---

dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go

This should fix #16645
The dns-controller pods can have AWS_WEB_IDENTITY_TOKEN_FILE set when OIDC is set up. This causes the route53 client constructor to initialize an sts client internally and call AssumeRoleWithWebIdentity. This STS client needs a region configured, so we attempt to discover one via IMDS.
If IMDS is disabled on the dns-controller pod's node, the cluster operator will need to set AWS_DEFAULT_REGION as a workaround.

Set the STS client's region via IMDS for AssumeRoleWithWebIdentity

---

pkg/model/iam/iam_builder.go

We were returning a value but really we were modifying the passed-in
value in-place.

refactor: simplify signature of AddS3Permissions function

---

tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/in-v1alpha2.yaml
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template

Copied from https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/hubble/metrics-service.yaml
Fixes #16032

Add the hubble-metrics service for cilium

---

tests/e2e/scenarios/scalability/OWNERS

Helps with iteration of the script!

Add OWNERS file in tests/e2e/scenarios/scalability

---

docs/getting_started/spot-ocean.md

This table is not formatted, and the rendering is wrong, which affects reading. Just format the table.

Fix table not format of docs

---

dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go

Cherry pick of #16647 on release-1.30.
#16647: Set the STS client's region via IMDS for
```release-note
```

Automated cherry pick of #16647: Set the STS client's region via IMDS for

---

cmd/kops/toolbox_instance-selector.go

aws: Fix conversion for instance-selector flags

---

cloudbuild.yaml
go.mod
hack/go.mod
tests/e2e/go.mod

Mostly just testing if the imds e2e errors happens on a hopefully unrelated PR

versionbump: update golang to 1.22.6

---

nodeup/pkg/model/bootstrap_client.go
pkg/model/components/apiserver.go
pkg/model/components/etcdmanager/model.go
pkg/model/master_volumes.go
tests/e2e/scenarios/bare-metal/run-test
tools/metal/storage/main.go
tools/metal/storage/pkg/objectstore/interfaces.go
tools/metal/storage/pkg/objectstore/testobjectstore/testobjectstore.go
tools/metal/storage/pkg/s3model/api.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/metal/api_target.go
upup/pkg/fi/cloudup/metal/cloud.go
upup/pkg/fi/cloudup/new_cluster.go
upup/pkg/fi/cloudup/template_functions.go
upup/pkg/fi/cloudup/utils.go

Start adding the minimal implementation such that we can `kops create cluster`

metal: stub out functions to enable cluster creation

---

.github/workflows/e2e.yml
tests/e2e/scenarios/bare-metal/dump-artifacts

We use the ARTIFACTS idea from prow, should be compatible.

tests: capture logs etc as github artifacts

---

pkg/flagbuilder/build_flags.go
pkg/model/components/etcdmanager/model.go
tests/e2e/scenarios/bare-metal/dump-artifacts
tests/e2e/scenarios/bare-metal/run-test

- **tests: use latest dev etcd-manager image in bare-metal test**
- **bare-metal: configure etcd with static configuration**

etcd manager static config

---

tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template

Fixes: https://github.com/kubernetes/kops/issues/16802
Update version of AWS EKS Pod Identity Webhook

chore: update aws pod identity webhook

---

nodeup/pkg/model/kube_apiserver.go

It looks like the kube-apiserver startup has slowed down a lot
(e.g. creating a lot of RBAC stuff), and this likely times out with
the current settings on smaller machines (as found by our
VMs-in-github-actions tests).
Increase the timeouts, aligning with k/k and using the newer healthcheck endpoints.

Tweak kube-apiserver timeouts

---

.github/workflows/e2e.yml
hack/dev-build-metal.sh
tests/e2e/scenarios/bare-metal/dump-artifacts
tests/e2e/scenarios/bare-metal/run-test
tests/e2e/scenarios/bare-metal/start-vms
tools/metal/storage/main.go
tools/metal/storage/pkg/objectstore/fsobjectstore/fsobjectstore.go
tools/metal/storage/pkg/objectstore/interfaces.go
tools/metal/storage/pkg/objectstore/testobjectstore/testobjectstore.go
tools/metal/storage/pkg/s3model/api.go

Because we now push much larger files, replace our in-memory storage with disk-backed storage.

tests: build and push locally for metal tests

---

cloudbuild.yaml
go.mod
hack/go.mod
tests/e2e/go.mod
tools/otel/traceserver/go.mod

Update Go to v1.22.7

---

tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-node-problem-detector.addons.k8s.io-k8s-1.17_content
upup/models/cloudup/resources/addons/node-problem-detector.addons.k8s.io/k8s-1.17.yaml.template

Disable node-problem-detector containerd and kubelet checks

---

tests/e2e/scenarios/bare-metal/start-vms

Observed some OOMs on the control plane.

tests: give bare-metal test VMs 2 gig

---

pkg/commands/toolbox_enroll.go

Export from the current package (we can always move it later), and
move it to an on-demand processing model to enable use in more
scenarios.

Refactor: make bootstrap-data building more reusable

---

dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go

Suppress request logging for IMDS within Route53 client

---

dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go

Cherry pick of #16857 on release-1.30.
#16857: Suppress request logging for IMDS within Route53 client
```release-note
```

Automated cherry pick of #16857: Suppress request logging for IMDS within Route53 client

---

docs/releases/1.30-NOTES.md

Closes #16860
/cc @rifelpet @zetaab @justinsb

Remove beta warning from kOps 1.30 release notes

---

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template

Addresses this comment: https://github.com/kubernetes/kops/pull/16800#discussion_r1758108163

Remove unused cilium template variables

---

nodeup/pkg/model/networking/amazon-vpc-routed-eni.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/template_functions.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

aws: Update VPC CNI to v1.18.5

---

cmd/kops/upgrade_cluster.go

Currently it relies on us updating the channel version in two places,
but this makes `kops upgrade cluster` inconsistent with `kops update cluster`.
`kops update cluster` also tells us to run `kops upgrade cluster`,
which then might not recommend an upgrade.

fix: `kops upgrade cluster` kubernetes selection logic

---

pkg/apis/kops/containerdconfig.go
tests/integration/update_cluster/nvidia/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/nvidia/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/nvidia/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/nvidia/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/nvidia/data/aws_s3_object_nodeupconfig-nodes_content

Close https://github.com/kubernetes/kops/issues/16557

Bump nvidia-driver-535 for CUDA 12 support

---

upup/pkg/fi/cloudup/openstack/instance_test.go

I got confusing error messages while working on #16911.

tests: Fix argument order in assertions

---

Makefile
hack/upload
tests/e2e/scenarios/bare-metal/start-vms

metal: Run apt-get update before install

---

tests/e2e/scenarios/bare-metal/dump-artifacts

e2e tests: dump ip information for each VM

---

channels/alpha

Alpha channel is a bit out of date with versions- time to align it :smile:

chore(channels): update alpha k8s and ubuntu ami versions

---

channels/alpha
channels/stable

Closes #16956.
/cc @rifelpet @justinsb

Fix channels for K8s 1.26

---

pkg/assets/assetdata/containerd.yaml

Avoids needing to look them up.

Add hashes for containerd 1.17.22

---

nodeup/pkg/model/kubelet_test.go

A small cleanup to keep the linter happier.

tests: fix linter-detected problem with error handling

---

upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template

Update CSI sidecar versions to latest. Update related RBAC.

OpenStack: update csi images

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.19.0

chore(networking): bump aws-cni to 1.19.0

---

pkg/dump/dumper.go

This will help troubleshoot networking issues we're seeing with Ubuntu 24.04

Dump ip routes as job artifacts

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.25_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.25_content
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.25.yaml.template
upup/pkg/fi/cloudup/template_functions.go

https://github.com/projectcalico/calico/releases/tag/v3.29.1

Update calico to 3.29.1

---

util/pkg/vfs/s3fs.go

We were not checking for errors when deleting all versions of a file,
as these errors were not returned at the call level, but instead
we need to check the returned DeleteObjectsOutput.

s3 vfs: fix delete all versions to handle errors

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.19.2

chore(networking): bump aws-vpc-cni version to 1.19.2

---

dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go

This PR fixes https://github.com/kubernetes/kops/issues/16849

Only configure STS region for Route 53 when we obtain it using IDMS

---

dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go

Cherry pick of #17161 on release-1.30.
#17161: Only configure STS region for Route 53 when we obtain it using IDMS
```release-note
```

Automated cherry pick of #17161: Only configure STS region for Route 53 when we obtain it using IDMS

---

pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Update Cilium to v1.16.5

---

cloudbuild.yaml
go.mod
hack/go.mod
tests/e2e/go.mod
tools/otel/traceserver/go.mod

/cc @rifelpet @justinsb @ameukam

Update Go to v1.23.4

---

upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go

Cherry pick of #17180 on release-1.31.
#17180: fix the random order of block_device_mappings render Include
```release-note
```

Automated cherry pick of #17180: fix the random order of block_device_mappings render Include

---

util/pkg/vfs/s3fs.go
util/pkg/vfs/s3fs_test.go

Cherry pick of #17183 on release-1.30.
#17183: Use SDK's built-in resolver for S3Path.GetHTTPsUrl
```release-note
```

Automated cherry pick of #17183: Use SDK's built-in resolver for S3Path.GetHTTPsUrl

---

tests/e2e/scenarios/scalability/run-test.sh

gce: Update scale test scenario

---

cloudbuild.yaml
go.mod
hack/go.mod
tests/e2e/go.mod
tools/otel/traceserver/go.mod

/cc @rifelpet @moshevayner @justinsb

Update Go to v1.23.5

---

docs/operations/images.md

Promote Ubuntu 24.04 to stable in Kops 1.31

---

channels/alpha

- https://github.com/kubernetes/kubernetes/releases/tag/v1.29.14
- https://github.com/kubernetes/kubernetes/releases/tag/v1.30.10
- https://github.com/kubernetes/kubernetes/releases/tag/v1.31.6
- https://github.com/kubernetes/kubernetes/releases/tag/v1.32.2

chore(channels): bump k8s and ubuntu ami versions in alpha channel

---

pkg/commands/toolbox_enroll.go

This avoids the needs for these nodes to have access to the state store.
* We no longer need S3/GCS credentials on the node.
* We don't depend on S3/GCS being reachable from the control
plane - at least here!

metal: copy control plane config to nodes

---

channels/stable
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.27/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.28/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.29/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.30/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.31/expected-v1alpha2.yaml

Promotes #17264 from alpha to stable channel

chore(channels): promote alpha to stable - k8s and Ubuntu ami versions

---

nodeup/pkg/model/kube_apiserver.go
nodeup/pkg/model/tests/golden/minimal/cluster.yaml
nodeup/pkg/model/tests/golden/minimal/tasks-kube-apiserver.yaml
nodeup/pkg/model/tests/golden/minimal/tasks-kube-controller-manager.yaml
nodeup/pkg/model/tests/golden/minimal/tasks-kube-proxy.yaml
nodeup/pkg/model/tests/golden/minimal/tasks-kube-scheduler.yaml
pkg/apis/kops/validation/legacy.go
pkg/model/components/apiserver.go

Remove cloud-config and cloud-provider from 1.33 apiserver

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Bumps AWS CNI addon to latest version
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.19.3

chore(networking): upgrade amazon vpc cni to 1.19.3

---

upup/pkg/fi/cloudup/gce/gce_cloud.go
upup/pkg/fi/cloudup/gce/labels.go
upup/pkg/fi/cloudup/gcetasks/disk.go
upup/pkg/fi/cloudup/gcetasks/poolhealthcheck.go

Use maps and slices to simplify the codebase

cloudup/gce: use slices and maps

---

.github/workflows/main.yml

Introduce arm64 for Linux tests on Github Actions

gha: Introduce arm64 for tests

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml

Update metrics-server to v0.7.2

---

pkg/model/gcemodel/service_accounts.go
pkg/model/gcemodel/storageacl.go
tests/integration/update_cluster/many-addons-gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
upup/pkg/fi/cloudup/gcetasks/projectiambinding.go
upup/pkg/fi/cloudup/gcetasks/projectiambinding_test.go
upup/pkg/fi/cloudup/gcetasks/serviceaccount.go
upup/pkg/fi/cloudup/gcetasks/storagebucketiam.go
upup/pkg/fi/cloudup/gcetasks/storagebucketiam_test.go

This gives us an automatic dependency in our evaluation,
and lets us write out a dependency to terraform also.

gce: use typed ServiceAccount in IAM tasks

---

docs/releases/1.32-NOTES.md

Update release notes to reflect release of 1.32.0

Release notes for 1.32.0

---

channels/stable

Followup to https://github.com/kubernetes/kops/pull/17404

Update requiredVersion for 1.31 and 1.32 in stable

---

pkg/apis/kops/validation/aws.go

Cherry-pick PR of #17383 for 1.32.

cherry-pick of #17383: Remove securityGroupOverride validation for NLB

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.25_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.25_content
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.25.yaml.template

Fixes https://github.com/kubernetes/kops/issues/17424

Upgrade calico to 3.29.4

---

cmd/kops/upgrade_cluster.go

Fixes https://github.com/kubernetes/kops/issues/17417
We used to recommend a kubernetes minor version that matches the kops minor version until https://github.com/kubernetes/kops/pull/16897.
Now we check if the next kubernetes minor version exists in channels and is supported by this kops version.

Fix minor version upgrade recommendations

---

docs/getting_started/production.md

Fixes https://github.com/kubernetes/kops/issues/17409

Add documentation on max node lifetime

---

channels/alpha
channels/stable
pkg/apis/kops/channel.go
tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.27/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.28/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.29/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.30/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.31/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.32/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-arm64/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-gce-dns-none/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-gce/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-irsa/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

Closes #17440
Closes #17437
/cc @rifelpet @ameukam @justinsb

chore: Bump node images

---

cmd/kops/delete_instance.go
cmd/kops/export_kubeconfig.go
cmd/kops/get_instances.go
cmd/kops/rolling-update_cluster.go
cmd/kops/toolbox_enroll.go
cmd/kops/update_cluster.go
cmd/kops/util/factory.go
cmd/kops/validate_cluster.go
docs/cli/kops_delete_instance.md
docs/cli/kops_export_kubeconfig.md
docs/cli/kops_get_instances.md
docs/cli/kops_rolling-update_cluster.md
docs/cli/kops_toolbox_enroll.md
docs/cli/kops_update_cluster.md
docs/cli/kops_validate_cluster.md
pkg/commands/commandutils/factory.go
pkg/commands/toolbox_enroll.go
pkg/kubeconfig/create_kubecfg.go
pkg/kubeconfig/create_kubecfg_test.go

Create flag api-server which allows for custom DNS setups

---

docs/tutorial/working-with-instancegroups.md

Add an example script to setup RAID-10 for instances with multiple NVMe disks.

Add an example script to setup RAID-10 for instances with multiple NVMe disks

---

pkg/resources/azure/azure.go
pkg/resources/azure/azure_test.go

azure: Track resources by ID during deletion

---

protokube/cmd/protokube/main.go

protokube: Initialize CloudProvider only with Gossip

---

upup/pkg/fi/cloudup/gcetasks/disk.go

fix #17511
Not totally sure how this should be tested. Looks like this whole file is missing tests?

Wait for GCE disk creation operation

---

cmd/kops/create_cluster.go
docs/releases/1.34-NOTES.md

Prefer using `id_ed25519.pub` instead of `id_rsa.pub`

---

docs/metal.md
tests/e2e/scenarios/bare-metal/start-vms

/cc @rifelpet @justinsb @ameukam

metal: Update Debian image

---

AGENTS.md
CLAUDE.md
GEMINI.md
QWEN.md

Provide a starting place for AI code assistance.
Add a baseline AGENTS.md file.
Add symlinks for Gemini, Claude and Qwen

Add AGENTS.md

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml.template

https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.13.4

Upgrade AWS Load Balancer Controller to v2.13.4

---

docs/releases/1.33-NOTES.md
mkdocs.yml

This fell through the cracks...
/cc @rifelpet @ameukam 
/approve

Update release notes for kOps 1.33

---

nodeup/pkg/model/azure.go
nodeup/pkg/model/resources/80-azure-disk.rules
upup/pkg/fi/nodeup/command.go

This should make it easier to map local disk to LUN in `etcd-manager`.
/cc @ameukam @rifelpet

azure: Add udev disk rules

---

images/mkdocs/Dockerfile
images/mkdocs/requirements.txt
netlify.toml

Bump versions in netlify and mkdocs

---

tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-networking.flannel-k8s-1.25_content
upup/models/cloudup/resources/addons/networking.flannel/k8s-1.25.yaml.template

Update Flannel to v0.27.4
