- pkg/nodeidentity/azure/BUILD.bazel
- pkg/nodeidentity/azure/identify.go
Cherry pick of #10619 on release-1.20.
#10619: Use correct tag when creating node labels from azure cloud
> Automated cherry pick of #10619: Use correct tag when creating node labels from azure cloud

- upup/pkg/fi/cloudup/dns.go
We're seeing test failures in prow because nodes are not able to resolve the kops-controller dns record.
Judging by timestamps, dns-controller adds the record after it is first queried by nodeup.
The negative TTL is long enough that the cluster doesn't validate within the alotted time.
Rather than increasing the validation timeout I think its better to precreate the DNS record the same way we do for the other records.
[example job](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-distro-imagerhel7/1361419015221678080), [nodeup logs](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-distro-imagerhel7/1361419015221678080/artifacts/3.8.162.43/journal.log), and [dns-controller logs](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-distro-im …
> Precreate the kops-controller DNS name

- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/tests/containerdbuilder/flatcar/tasks.yaml
Even if we don't install containerd (e.g. ContainerOS or Flatcar), we
likely still need to configure it; particularly in the case of
kubenet.
Additionally, on ContainerOS we can't change the path from
/etc/containerd/config.toml, so we have to write it there.  We may in
future be able to use this on all distros.
> containerd installation: always configure, even if we don't install

- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/tests/containerdbuilder/flatcar/tasks.yaml
Cherry pick of #10813 on release-1.19.
#10813: containerd installation: always configure, even if we don't
> Automated cherry pick of #10813: containerd installation: always configure, even if we don't

- .shipbot.yaml
- Makefile
- channels/cmd/channels/BUILD.bazel
- protokube/cmd/protokube/BUILD.bazel
Prerequisite for #10574, as discussed during office hours.
/cc @bharath-123 @justinsb @rifelpet @olemarkus
> Release binaries for protokube and channels

- upup/pkg/fi/cloudup/dns.go
Cherry pick of #10833 on release-1.20.
#10833: Precreate the kops-controller DNS name
> Automated cherry pick of #10833: Precreate the kops-controller DNS name

- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/kubetest2-kops/deployer/create.go
- tests/e2e/kubetest2-kops/deployer/deployer.go
- tests/e2e/kubetest2-kops/deployer/down.go
- tests/e2e/kubetest2-kops/deployer/up.go
- tests/e2e/pkg/target/terraform.go
- tests/e2e/pkg/util/zip.go
This adds support for `--target terraform` and applying/destroying the cluster using terraform.
The specified terraform version is downloaded and unzipped each run, ideally we could cache this or use tfenv or something.
> Kubetest2 - terraform support

- .github/workflows/main.yml
- WORKSPACE
Cherry pick of #10853 on release-1.20.
#10853: Update Go to v1.15.8
> Automated cherry pick of #10853: Update Go to v1.15.8

- upup/pkg/fi/cloudup/openstack/cloud.go
- upup/pkg/fi/cloudup/openstack/floatingip.go
- upup/pkg/fi/cloudup/openstack/instance.go
- upup/pkg/fi/cloudup/openstack/keypair.go
- upup/pkg/fi/cloudup/openstack/loadbalancer.go
- upup/pkg/fi/cloudup/openstack/network.go
- upup/pkg/fi/cloudup/openstack/port.go
- upup/pkg/fi/cloudup/openstack/router.go
- upup/pkg/fi/cloudup/openstack/security_group.go
- upup/pkg/fi/cloudup/openstack/server_group.go
- upup/pkg/fi/cloudup/openstack/subnet.go
- upup/pkg/fi/cloudup/openstack/volume.go
This PR fixes #10724 with these two changes:
1) Add missing RetryWithBackoff to DeleteInstanceWithID
2) Fix broken retry logic in all other delete functions. In the current implementation, as the first Delete request will almost certainly return nil, the function will return true and the retry will not try again, resulting in potentially some assets not getting deleted from OpenStack
Also, the current writeBackoff is a bit too aggressive and I introduced less hasty deleteBackoff.
The change has been tested with OpenStack. I verified that all APIs we are hitting will eventually return the 404 (type) we are looking for.
> Fix OpenStack delete functions

- docs/addons.md
- k8s/crds/kops.k8s.io_instancegroups.yaml
- pkg/apis/kops/instancegroup.go
- pkg/apis/kops/v1alpha2/instancegroup.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/clusterautoscaler.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
Cherry pick of #10857 on release-1.20.
#10857: Add support for cluster autoscaler 1.20.x
> Automated cherry pick of #10857: Add support for cluster autoscaler 1.20.x

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #10856 on release-1.20.
#10856: Add liveness probe for calico-kube-controllers
> Automated cherry pick of #10856: Add liveness probe for calico-kube-controllers

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #10700 #10856 on release-1.19.
#10700: Fix rendering issue created by #10414
#10856: Add liveness probe for calico-kube-controllers
> Automated cherry pick of #10700: Fix rendering issue created by #10414 #10856: Add liveness probe for calico-kube-controllers

- channels/alpha
- channels/stable
- tests/integration/create_cluster/minimal-1.16/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.17/expected-v1alpha2.yaml
Also pushing the image updates from alpha to stable, since I noticed these were pushed to alpha 11 days ago.
K8s releases from earlier today:
- https://github.com/kubernetes/kubernetes/releases/tag/v1.18.16
- https://github.com/kubernetes/kubernetes/releases/tag/v1.19.8
- https://github.com/kubernetes/kubernetes/releases/tag/v1.20.3
> K8s Version Updates February 2021

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
Cherry pick of #10635 on release-1.19.
#10635: enableRemoteNodeIdentity actually defaults to true
> Automated cherry pick of #10635: enableRemoteNodeIdentity actually defaults to true

- tests/e2e/kubetest2-kops/deployer/up.go
Previously we were only recognizing it with `kops create --filename` (when kubetest2's `--template-path` is set)
extends https://github.com/kubernetes/kops/pull/10697
it turns out we werent actually using terraform in the new testgrid job: https://testgrid.k8s.io/kops-misc#kops-grid-scenario-terraform
> kubetest2 - support terraform with `kops create cluster`

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template
Cherry pick of #10863 on release-1.20.
#10863: Bump aws node termination handler
> Automated cherry pick of #10863: Bump aws node termination handler

- pkg/apis/kops/validation/BUILD.bazel
- pkg/apis/kops/validation/aws.go
- pkg/apis/kops/validation/aws_test.go
- upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
When an ami and instanceType of different architectures are specified,`kops update cluster` does not fail even though its an invalid combination.
This can cause side effects like creation of unwanted versions of a launch template, failed cluster creations and so on. 
This PR adds checks to validate the chosen instance type architecture against the ami architecture. This PR adds the validation for launch configuration, launch templates and mixed instance policies.
**Open question:** We are making a `DescribeInstanceType` call for each instance when validating for mixed instance policies. This can be expensive as more instances are added. Should we feature flag this validation?
**UPDATE:** I think the number of calls to DescribeInstanceType should be fine as this done only during spec …
> Add validation for instanceType and ami architecture 

- channels/alpha
The 1.20 patch arrived a bit late, aligning alpha to reflect latest k8s patch version.
https://github.com/kubernetes/kubernetes/releases/tag/v1.20.4
> Upgrade k8s 1.20 to latest patch version

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Cherry pick of #10876 on release-1.20.
#10876: Update AWS CNI to latest patch version
> Automated cherry pick of #10876: Update AWS CNI to latest patch version

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
Cherry pick of #10858 on release-1.20.
#10858: Bump metrics-server to 0.4.2
> Automated cherry pick of #10858: Bump metrics-server to 0.4.2

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
AWS CNI version 1.7.9 was just released: 
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.7.9
I'll also create matching cherry-pick PRs to back port this update to 1.19 & 1.20 branches in a minute.
> Update AWS CNI to latest patch version

- pkg/apis/kops/validation/BUILD.bazel
- pkg/apis/kops/validation/aws.go
- pkg/apis/kops/validation/aws_test.go
- pkg/testutils/integrationtestharness.go
- upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
Cherry pick of #10747 #10884 on release-1.20.
#10747: Add validation for ami arch to instance type arch
#10884: Improve machine type and image validation
> Automated cherry pick of #10747: Add validation for ami arch to instance type arch #10884: Improve machine type and image validation

- upup/pkg/fi/cloudup/azuretasks/vmscaleset.go
Cherry pick of #10886 on release-1.20.
#10886: fix loadBalancerID null pointer
> Automated cherry pick of #10886: fix loadBalancerID null pointer

- pkg/apis/kops/validation/validation.go
- pkg/model/components/clusterautoscaler.go
- pkg/model/components/etcd.go
- pkg/model/components/kubecontrollermanager_test.go
- pkg/model/components/kubelet.go
- upup/pkg/fi/cloudup/apply_cluster.go
Also remove bits of code referencing 1.14 version
> Enforce 1.14 deprecation

- pkg/apis/kops/cluster.go
- pkg/model/azuremodel/network.go
- pkg/resources/azure/azure.go
- upup/pkg/fi/cloudup/azure/azure_cloud.go
- upup/pkg/fi/cloudup/azuretasks/routetable.go
- upup/pkg/fi/cloudup/azuretasks/subnet.go
- upup/pkg/fi/cloudup/azuretasks/virtualnetwork.go
- adds support tag update of virtual networks (mentioned here #10412)
- adds support for shared route table and subnet resources
- note: azure does not support subnet tagging so shared subnet is determined by sharedVPC
- fixes infrequent panic during export kubecfg task of cluster creation due to race condition where scaleSets are being reported
@kenji-cloudnatix
> add usage of subnet and routetable shared resources in azure

- cloudmock/aws/mockelbv2/loadbalancers.go
- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/validation/aws.go
- pkg/apis/kops/validation/aws_test.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/awsmodel/api_loadbalancer.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
- upup/pkg/fi/cloudup/awstasks/subnet_mapping.go
This is an implementation of https://github.com/kubernetes/kops/issues/10706
This allows (static) Elastic IP's to be added to the external loadbalancer of admin interface.
The Loadbalancer must be Network and Public for this change
> Adding Elastic IP Allocations to NLB API

- cloudmock/aws/mockelbv2/loadbalancers.go
- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/validation/aws.go
- pkg/apis/kops/validation/aws_test.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/awsmodel/api_loadbalancer.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
- upup/pkg/fi/cloudup/awstasks/subnet_mapping.go
Cherry pick of #10872 on release-1.20.
#10872: Adding Elastic IP Allocations to NLB API
> Automated cherry pick of #10872: Adding Elastic IP Allocations to NLB API

- pkg/apis/kops/cluster.go
- pkg/model/azuremodel/network.go
- pkg/resources/azure/azure.go
- upup/pkg/fi/cloudup/azure/azure_cloud.go
- upup/pkg/fi/cloudup/azuretasks/routetable.go
- upup/pkg/fi/cloudup/azuretasks/subnet.go
- upup/pkg/fi/cloudup/azuretasks/virtualnetwork.go
Cherry pick of #10900 on release-1.20.
#10900: add usage of subnet and routetable shared resources in azure
> Automated cherry pick of #10900: add usage of subnet and routetable shared resources in azure

- cloudmock/aws/mockiam/iaminstanceprofile.go
- cloudmock/aws/mockiam/iamrole.go
- cloudmock/aws/mockiam/iamrolepolicy.go
- cloudmock/aws/mockiam/oidcprovider.go
- k8s/crds/kops.k8s.io_clusters.yaml
- k8s/crds/kops.k8s.io_instancegroups.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/instancegroup.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/instancegroup.go
- pkg/model/awsmodel/oidc_provider.go
- pkg/model/iam.go
- pkg/resources/aws/aws.go
- upup/pkg/fi/cloudup/awstasks/iaminstanceprofile.go
- upup/pkg/fi/cloudup/awstasks/iaminstanceprofilerole.go
- upup/pkg/fi/cloudup/awstasks/iamoidcprovider.go
- upup/pkg/fi/cloudup/awstasks/iamrole.go
- upup/pkg/fi/cloudup/awstasks/iamrolepolicy.go
Also some misc error handling cleanup and improving the CloudLabels API field description
Marking WIP until terraform support which will likely come soon. https://github.com/hashicorp/terraform-provider-aws/issues/17594
> Add Tagging to Instance Profiles and OIDC Providers

- pkg/resources/spotinst/resources.go
This PR prevents instance groups with the same suffix from being deleted. For example, all instance groups associated with a cluster with the name `foo-bar.k8s.local` should be ignored when a cluster with the name `bar.k8s.local` is being deleted.
> Spotinst: Prevent instance groups with the same suffix from being deleted

- upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
> Fix nil pointer deference for image ID with spotinst

- pkg/resources/spotinst/resources.go
Cherry pick of #10918 on release-1.20.
#10918: fix: prevent igs with same suffix from being deleted
> Automated cherry pick of #10918: fix: prevent igs with same suffix from being deleted

- upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
Cherry pick of #10924 on release-1.19.
#10924: Fix nil pointer deference for image ID with spotinst
> Automated cherry pick of #10924: Fix nil pointer deference for image ID with spotinst

- docs/security.md
We've found that, with kops 1.19, the bastion and k8s nodes user is `ubuntu` when using the default kops configuration
> Update SSH documentation for ubuntu

- docs/gpu.md
The existing manifest doesn't work due to the proposed node taint. This fixes it.
> Fix no-schedule issue

- pkg/model/iam.go
- upup/pkg/fi/cloudup/awstasks/iamrolepolicy.go
Cherry pick of #10940 on release-1.19.
#10940: Sort external policies when checking for changes
> Automated cherry pick of #10940: Sort external policies when checking for changes

- .gitattributes
Since these are generated, viewing their diff is not of much value when viewing a commit or PR.
I would include a trivial change to a BUILD.bazel file to demonstrate but it would fail the gazelle verification CI
See https://github.com/github/linguist#using-gitattributes
> Instruct GH to collapse BUILD.bazel diffs by default

- pkg/apis/kops/validation/cluster.go
- pkg/apis/kops/validation/instancegroup.go
- pkg/apis/kops/validation/instancegroup_test.go
We were too strict on some labels that blocked common use cases such as CAS. At the same time we allowed IG-level cloudLabels that could result in broken clusters.
Fixes #10862
> Further improve cloudLabel validation

- pkg/apis/kops/validation/cluster.go
- pkg/apis/kops/validation/instancegroup.go
- pkg/apis/kops/validation/instancegroup_test.go
Cherry pick of #10910 on release-1.20.
#10910: Further improve cloudLabel validation
> Automated cherry pick of #10910: Further improve cloudLabel validation

- pkg/kubemanifest/visitor.go
- pkg/model/components/addonmanifests/BUILD.bazel
- pkg/model/components/addonmanifests/remap.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/anonymous-issuer-discovery.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/aws-cloud-controller.addons.k8s.io-k8s-1.18.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/authentication.aws-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/anonymous-issuer-discovery.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
This PR will use the manifest remap functionality to add a standardised set of labels to all manifests.
I think this one is useful in many ways:
1. it ensures the addon selector is actually available on all resources and that they are set correctly (which was not the case)
2. it makes it easy for users to see what comes from kOps and what came from elsewhere
3. it makes it easy to see what version of an addon was installed
4. further down the line we could implement some naïve "delete all resources that has the managed-by label and a lower addon version"
5. we could implement addon deletion functionality into channels that users could use to remove addons (or "vendor" that into kOps CLI)
> Add a standardised set of labels on all resources

- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Changes:
* Add user agent to etcd-manager requests [#395](https://github.com/kopeio/etcd-manager/pull/395)
* Add etcd-manager metrics, add openstack API metrics [#396](https://github.com/kopeio/etcd-manager/pull/396)
* Make discovery poll interval configurable [#397](https://github.com/kopeio/etcd-manager/pull/397)
* Add log levels to prevent too verbose logging [#394](https://github.com/kopeio/etcd-manager/pull/394)
> Update etcd-manager to 3.0.20210228

- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Cherry pick of #10949 on release-1.20.
#10949: Update etcd-manager to 3.0.20210228
> Automated cherry pick of #10949: Update etcd-manager to 3.0.20210228

- cloudmock/aws/mockec2/routetable.go
- docs/cluster_spec.md
- pkg/apis/kops/cluster.go
- pkg/apis/kops/validation/validation.go
- pkg/model/network.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/route.go
closes #8837
I opted to just use a `*string` for the TGW ID in `awstasks.Route` rather than a new `awstasks.TransitGateway` because kops will never be creating TGWs itself, they will always be defined by ID, therefore we don't need any Find or Render logic.
> Add AWS Transit Gateway support

- pkg/model/azuremodel/context.go
- pkg/model/azuremodel/context_test.go
- pkg/nodeidentity/azure/BUILD.bazel
- pkg/nodeidentity/azure/identify.go
As Azure doesn't allow "/" in label keys, we used to convert "/" to
"_", but we didn't convert back "_" to "/" in kops-controller. This
commit fixes this.
Change the conversion semantics so that "/" is converted to "_s".  "_"
is converted to "__" so that we can distinguish the original "_" and
"_s".
> Fix node label conversion in Azure

- pkg/apis/kops/validation/validation.go
Cherry pick of #10828 on release-1.19.
#10828: validation.go: remove checks on CNI
> Automated cherry pick of #10828: validation.go: remove checks on CNI

- pkg/apis/kops/validation/validation.go
This PR removes a previously introduced check on the CNI plugin presence. 
The original PR https://github.com/kubernetes/kops/pull/8617 seems to introduce some checks on the use of incompatible CNI plugins, but in fact the CNI plugin is used to set the `--node-ip` Kubelet option in case the `useSecondaryIP` flag is set to true. A Kops cluster operator should be able to declare that when using a CNI plugin like Calico for example.
> Allow multi-CNI setups to set usesSecondaryIP

- pkg/model/awsmodel/autoscalinggroup.go
This PR resolves an issue with LB attachments of non-Spotinst managed instance groups. LB attachments shouldn't be skipped entirely when the `SpotinstHybrid` feature is enabled.
> Spotinst: Don't skip LB attachments when SpotinstHybrid is enabled

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://docs.projectcalico.org/archive/v3.17/release-notes/
/cc @seh
> Update Calico to v3.17.3 for kOps 1.19

- pkg/model/awsmodel/autoscalinggroup.go
Cherry pick of #10961 on release-1.20.
#10961: fix: don't skip lb attachments when hybrid is enabled
> Automated cherry pick of #10961: fix: don't skip lb attachments when hybrid is enabled

- cloudmock/aws/mockec2/routetable.go
- docs/cluster_spec.md
- pkg/apis/kops/cluster.go
- pkg/apis/kops/validation/validation.go
- pkg/model/network.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/route.go
Cherry pick of #10948 on release-1.20.
#10948: Add support for defining a transit gateway for a default
> Automated cherry pick of #10948: Add support for defining a transit gateway for a default

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
Cherry pick of #10944 on release-1.20.
#10944: gce doesn't suffix the IG names with ClusterName
> Automated cherry pick of #10944: gce doesn't suffix the IG names with ClusterName

- pkg/model/azuremodel/context.go
- pkg/model/azuremodel/context_test.go
- pkg/nodeidentity/azure/BUILD.bazel
- pkg/nodeidentity/azure/identify.go
Cherry pick of #10935 on release-1.20.
#10935: Fix node label conversion in Azure
> Automated cherry pick of #10935: Fix node label conversion in Azure

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #10960 on release-1.20.
#10960: feat(spot/addon): bump ocean-controller to 1.0.73
> Automated cherry pick of #10960: feat(spot/addon): bump ocean-controller to 1.0.73

- docs/getting_started/digitalocean.md
- docs/getting_started/production.md
Found a typo while going through these docs. I then ran a quick check on everything under `getting_started/` and found another one.
Admins: feel free to patch directly instead of approving the PR.
> Fix typos in docs/getting_started

- k8s/crds/kops.k8s.io_clusters.yaml
- k8s/crds/kops.k8s.io_instancegroups.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/zz_generated.deepcopy.go
Kubernetes 1.18 disables this by default.
For backwards compatibility with monitoring tools, it would be nice to
be able to re-enable this.
https://github.com/kubernetes/kubernetes/issues/68522
> Add support for enable-cadvisor-json-endpoints with Kubelet

- k8s/crds/kops.k8s.io_clusters.yaml
- k8s/crds/kops.k8s.io_instancegroups.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/zz_generated.deepcopy.go
Cherry pick of #10957 on release-1.20.
#10957: Add support for enable-cadvisor-json-endpoints with Kubelet
> Automated cherry pick of #10957: Add support for enable-cadvisor-json-endpoints with Kubelet

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #10966 on release-1.19.
#10966: Add explicit RBAC permissions for finalizers subresources
> Automated cherry pick of #10966: Add explicit RBAC permissions for finalizers subresources

- k8s/crds/kops.k8s.io_instancegroups.yaml
- pkg/apis/kops/instancegroup.go
- pkg/apis/kops/v1alpha2/instancegroup.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/validation/aws.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/awsmodel/autoscalinggroup.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/launchtemplate.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
Cherry pick of #10934 on release-1.20.
#10934: Add new CPUCredits field to instance group spec
> Automated cherry pick of #10934: Add new CPUCredits field to instance group spec

- tests/integration/update_cluster/existing_iam/kubernetes.tf
- tests/integration/update_cluster/ha/kubernetes.tf
- tests/integration/update_cluster/launch_templates/kubernetes.tf
- tests/integration/update_cluster/mixed_instances/kubernetes.tf
- tests/integration/update_cluster/mixed_instances_spot/kubernetes.tf
- upup/pkg/fi/cloudup/terraform/target_hcl2.go
- upup/pkg/fi/cloudup/terraform/target_hcl2_test.go
- upup/pkg/fi/cloudup/terraform/target_json.go
Cherry pick of #10978 on release-1.20.
#10978: Removing duplicate local and output values in
> Automated cherry pick of #10978: Removing duplicate local and output values in

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
This PR adds `cloudLabels` from the cluster spec as tags to EBS volumes created by the aws-ebs-csi driver. This allows us to fulfil company wide policies on tagging rules.
> Add CloudLabels as --extra-tags to aws-ebs-csi driver

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
Cherry pick of #10976 on release-1.20.
#10976: Add CloudLabels as --extra-tags to aws-ebs-csi driver
> Automated cherry pick of #10976: Add CloudLabels as --extra-tags to aws-ebs-csi driver

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
Cherry pick of #10982 on release-1.19.
#10982: Disable Calico Prometheus metrics by default
> Automated cherry pick of #10982: Disable Calico Prometheus metrics by default

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
Fixes the incorrect defaults implementation but also defaults to the official Calico values.
Fixes: #10539
> Disable Calico Prometheus metrics by default

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/model_test.go
- pkg/model/components/etcdmanager/tests/pollinterval/cluster.yaml
- pkg/model/components/etcdmanager/tests/pollinterval/tasks.yaml
This PR adds the discovery-poll-interval configuration option for etcd-manager, which was recently [merged](https://github.com/kopeio/etcd-manager/pull/397) to etcd-manager.
> Add etcd-manager discoveryPollInterval option

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/authentication.kope.io/k8s-1.12.yaml
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.flannel/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.kope.io/k8s-1.12.yaml
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
This removes `role.kubernetes.io/networking: "1"` and `role.kubernetes.io/authentication: "1"` labels which are now added automatically since https://github.com/kubernetes/kops/pull/10796.
/cc @olemarkus
> Remove manually added labels from addons

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/model_test.go
- pkg/model/components/etcdmanager/tests/pollinterval/cluster.yaml
- pkg/model/components/etcdmanager/tests/pollinterval/tasks.yaml
Cherry pick of #10975 on release-1.20.
#10975: Add etcd-manager discoveryPollInterval option
> Automated cherry pick of #10975: Add etcd-manager discoveryPollInterval option

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
This one was merged to 1.20 branch, but not master. But since the controller-runtime also was updated now, we need this for a working master branch.
/cc @hakman 
/approve
> Fix kops-controller rbac due to leader election change

- tests/e2e/kubetest2-kops/deployer/up.go
- tests/e2e/kubetest2-kops/deployer/up_test.go
Previously we would incorrectly append create cluster arguments if they had already been specified and used --foo=bar notation.
This resulted in arguments being specified multiple times causing undesired behavior.
We now check for both `--foo bar` and `--foo=bar` when attempting to add a `--foo` argument.
fixes this test job: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-scenario-arm64/1368962983325077504
`I0308 16:33:38.407993     609 up.go:125] /tmp/kops448488603 create cluster --name e2e-30c5bc0bf2-6b775.test-cncf-aws.k8s.io --cloud aws --kubernetes-version v1.21.0-beta.0 --ssh-public-key /etc/aws-ssh/aws-ssh-public --override cluster.spec.nodePortAccess=0.0.0.0/0 --yes --channel=alpha --networking=kubenet --container-runtime=docker --zones=us-east-2b …
> kubetest2 - don't overwrite create args that use equals signs

- dns-controller/pkg/dns/dnscontroller.go
The AWS Route53 API is severely rate-limited and makes periodic e2e tests fail. This may happen to users also, as they see DNS records not being updated quite often lately. 
Not sure if AWS changed something or we're just noticing this, but there's not much that can be done except do this less often.
> Use exponential backoff for DNS updates

- pkg/apis/kops/validation/validation_test.go
- pkg/model/components/BUILD.bazel
- pkg/model/components/cloudconfiguration.go
- pkg/model/components/cloudconfiguration_test.go
When choosing a default value for the _Cluster_ spec's "cloudConfig.manageStorageClasses" field, first check whether a user specified a concrete value for the related OpenStack "blockStorage.createStorageClass" field. If so, use that value as the effective default value for the former field as well, so as to avoid an unnecessary conflict between the field values on the second validation pass.
See #10733, @zetaab's [findings there](https://github.com/kubernetes/kops/pull/10733/files#r590046073), and [the ensuing discussion in the "kops-dev" channel](https://kubernetes.slack.com/archives/C8MKE2G5P/p1615296250086900?thread_ts=1615291312.086800&cid=C8MKE2G5P) in the "Kubernetes" Slack workspace for context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Storage: Amend default choice for StorageClass management to honor a specified OpenStack-related value

- pkg/apis/kops/validation/validation_test.go
- pkg/model/components/BUILD.bazel
- pkg/model/components/cloudconfiguration.go
- pkg/model/components/cloudconfiguration_test.go
Cherry pick of #11002 on release-1.20.
#11002: Honor an OpenStack StorageClass management choice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/kops/11003)
> Automated cherry pick of #11002: Honor an OpenStack StorageClass management choice

- tests/e2e/e2e.mk
- tests/e2e/pkg/version/kubernetes.go
Have kops' --kubernetes-version flag value include the bucket's url
This matches the kubetest1 behavior.
See an example kops create cluster command here: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-misc-arm64-conformance/1369076996193128448#1:build-log.txt%3A174
The kubetest 1 logic is here: https://github.com/kubernetes/test-infra/blob/37b80c5e3b3c5e1d0fdabd734ed54176849d1953/kubetest/kops.go#L390-L400
> Kubetest2 - Fix kops' --kubernetes-version with k8s version markers

- tests/e2e/scenarios/upgrade/run-test
This updates the upgrade scenario script to support building kops when ran locally, or using the version markers when ran in a periodic prow job.
hoping to fix the upgrade tests here: https://testgrid.k8s.io/kops-kubetest2#kops-aws-upgrade
> Don't build kops during periodic upgrade tests

- tests/e2e/pkg/version/kubernetes.go
Should fix the trailing "%0A" here: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-misc-arm64-ci/1369566440318832640#1:build-log.txt%3A90
> Remove trailing newline from kubernetes version marker

- dns-controller/pkg/dns/dnscontroller.go
Cherry pick of #10996 on release-1.19.
#10996: Use exponential backoff for DNS updates
> Automated cherry pick of #10996: Use exponential backoff for DNS updates

- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/pkg/kops/download.go
- tests/e2e/scenarios/upgrade/run-test
This ensures that the same binary is used for kubetest2-kops commands as well as the kops commands invoked directly in the scenario script.
Periodic jobs will create a temp file that will be used to save the kops binary from the provided version marker.
non-periodic jobs (local invocation) will use the bazel build binary, preserving original behavior but using this same binary for kops commands rather than relying on PATH.
> Kubetest2 - use same kops binary for all commands in upgrade scenario

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #11018 on release-1.20.
#11018: Update Calico to v3.18.1
> Automated cherry pick of #11018: Update Calico to v3.18.1

- dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go
Hoping to fix failures like this: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-distro-imagecentos8/1370176524702978048
The default value is 3: https://github.com/aws/aws-sdk-go/blob/d87d92b4412739c6ef8917979e922fae98b7654c/aws/client/default_retryer.go#L39-L40
> Increase route53 retry count from 3 to 5

- pkg/apis/kops/validation/validation.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/cilium.go
We just reuse the 1.9 templates. Seems to work for now.
> Allow cilium 1.10

- nodeup/pkg/model/docker_test.go
- pkg/apis/kops/dockerconfig.go
- pkg/apis/kops/v1alpha2/dockerconfig.go
Cherry pick of #11027 on release-1.19.
#11027: Fix rendering of multiple Docker insecure registries
> Automated cherry pick of #11027: Fix rendering of multiple Docker insecure registries

- upup/pkg/fi/cloudup/azuretasks/vmscaleset.go
Null pointer exception occurs when trying to update cluster in place on azure. This occurs because other virtual machine scale sets aside from the master do not have backend loadbalancer pools. 
This checks to make sure that the name of the scale set contains "masters" to differentiate between the master and other virtual machine scale sets.
> azure: fix null pointer when updating in place cluster

- upup/pkg/fi/cloudup/azuretasks/vmscaleset.go
Cherry pick of #11015 on release-1.20.
#11015: azure: fix null pointer when updating in place cluster
> Automated cherry pick of #11015: azure: fix null pointer when updating in place cluster

- tests/e2e/pkg/kops/download.go
Fixes the extra newline character in this job failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-misc-updown/1370242214826872832#1:build-log.txt%3A91
> Trim space on kops version markers

- k8s/crds/kops.k8s.io_clusters.yaml
- k8s/crds/kops.k8s.io_instancegroups.yaml
- nodeup/pkg/model/update_service.go
- pkg/apis/kops/cluster.go
- pkg/apis/kops/instancegroup.go
- pkg/apis/kops/labels.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/instancegroup.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/validation/instancegroup.go
- pkg/apis/kops/validation/instancegroup_test.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/zz_generated.deepcopy.go
- upup/pkg/fi/cloudup/validation_test.go
- upup/pkg/fi/nodeup/nodetasks/package.go
As with the _Cluster_ "spec.updatePolicy" field, add a similar field at the _InstanceGroup_ level, allowing overriding of the cluster-level choice in each _InstanceGroup_.
Introduce a new value for the field ("automatic") as equivalent to the default value applied when the field is absent. Honoring this new value allows disabling automatic updates at the cluster level, but then enabling them again for particular _InstanceGroups_. Without such a positive affirmation, it's not possible to override a cluster-level "external" policy at the _InstanceGroup_ level, as there's no way to specify positively that you want to recover the default value. Instead, expressing the explicit "automatic" value is clear and unambiguous.
See [this thread in the "kops-users" …
> Honor OS update policy at InstanceGroup level too

- k8s/crds/kops.k8s.io_clusters.yaml
- k8s/crds/kops.k8s.io_instancegroups.yaml
- nodeup/pkg/model/update_service.go
- pkg/apis/kops/cluster.go
- pkg/apis/kops/instancegroup.go
- pkg/apis/kops/labels.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/instancegroup.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/validation/instancegroup.go
- pkg/apis/kops/validation/instancegroup_test.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/zz_generated.deepcopy.go
- upup/pkg/fi/cloudup/validation_test.go
- upup/pkg/fi/nodeup/nodetasks/package.go
Cherry pick of #10913 on release-1.20.
#10913: Honor OS update policy at InstanceGroup level too
> Automated cherry pick of #10913: Honor OS update policy at InstanceGroup level too

- pkg/apis/kops/validation/aws.go
- pkg/apis/kops/validation/aws_test.go
- upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
This should be reasonably safe as the machineInfo field should not be nil on a valid instance type. Would like some opinions on this.
> Improve instance type validation error message

- tests/e2e/scenarios/upgrade/run-test
There were too many issues with downloading kops from a version marker with this setup.
We'll need to move this logic into kubetest2 itself since it has sufficient knowledge for eg. KOPS_BASE_URL, where the kops binary was downloaded, etc.
Also rearrange script to upgrade the cluster first, then run tests
> Revert upgrade script to build kops

- cmd/kops/validate_cluster.go
Previously with --wait if a cluster successfully validated and then a subsequent validation failed
(perhaps due to a new critical pod being scheduled and not being ready) we would previously fail the `validate cluster` command immediately.
This will now reset the success counter that approaches --count, allowing validation attempts to continue until we timeout from --wait.
I'm hoping this fixes prow job failures like [this](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-u1804-k18-containerd/1370875829445201920) where `kops validate cluster --count 10 --wait 15m` was invoked at `23:15:48` but exited with failure at `23:22:59` (a duration of only 7m11s). It passed validation 4 consecutive times but failed when a kube-proxy pod became pending. In that case we should just …
> cluster validation - allow flapping of validation errors

- channels/pkg/channels/apply.go
- protokube/pkg/protokube/kube_boot.go
- util/pkg/proxy/proxy.go
Removing some noise I see in protokube and nodeup logs. Also log a channels error that we're seeing on flatcar to help with troubleshooting.
https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-distro-imageflatcar/1371259092688965632/artifacts/3.34.196.168/protokube.log
```
I0315 00:53:47.644156    6154 apply.go:67] Running command: kubectl apply -f /tmp/channel266979825/manifest.yaml
I0315 00:53:47.644171    6154 apply.go:70] error running kubectl apply -f /tmp/channel266979825/manifest.yaml
I0315 00:53:47.644176    6154 apply.go:71]
error updating "limit-range.addons.k8s.io": error applying update from "s3://k8s-kops-prow/e2e-785a7f373f-91d99.test-cncf-aws.k8s.io/addons/limit-range.addons.k8s.io/v1.5.0.yaml": error running kubectl
```
> Cleanup some nodeup & protokube logging

- channels/alpha
- channels/stable
- cmd/kops/upgrade_cluster.go
- docs/operations/cluster_template.md
- docs/releases/1.20-NOTES.md
- pkg/apis/kops/BUILD.bazel
- pkg/apis/kops/channel.go
- pkg/util/templater/BUILD.bazel
- pkg/util/templater/template_functions.go
- pkg/util/templater/templater_test.go
- tests/integration/channel/BUILD.bazel
- tests/integration/channel/integration_test.go
- tests/integration/channel/simple/channel.yaml
- upup/pkg/fi/cloudup/populate_instancegroup_spec.go
This should fix most requests around having correct images for new clusters and upgrades.
Fixes: #11023
/cc @rifelpet @olemarkus @bharath-123
> Add channels entries for image architecture

- docs/operations/troubleshoot.md
This is just a small issue I noticed while troubleshooting a kops cluster, the path to the CNI binaries is wrong.
> fix CNI bin path in troubleshoot.md

- channels/pkg/channels/apply.go
- protokube/pkg/protokube/kube_boot.go
- util/pkg/proxy/proxy.go
Cherry pick of #11052 on release-1.20.
#11052: Cleanup some nodeup & protokube logging
> Automated cherry pick of #11052: Cleanup some nodeup & protokube logging

- tests/e2e/kubetest2-kops/deployer/common.go
kubetest 1 was referencing these values here: https://github.com/kubernetes/test-infra/blob/432c6e7dca38f0785901a6159275524cec369c4a/scenarios/kubernetes_e2e.py#L202-L205
the preset is referenced in our gce jobs here: https://github.com/kubernetes/test-infra/blob/432c6e7dca38f0785901a6159275524cec369c4a/config/jobs/kubernetes/kops/kops-periodics-gce.yaml#L5
> Kubetest2 - Add GCE default SSH key values from prow jobs

- cmd/kops/upgrade_cluster.go
- docs/operations/cluster_template.md
- pkg/apis/kops/BUILD.bazel
- pkg/apis/kops/channel.go
- pkg/util/templater/BUILD.bazel
- pkg/util/templater/template_functions.go
- pkg/util/templater/templater_test.go
- tests/integration/channel/BUILD.bazel
- tests/integration/channel/integration_test.go
- tests/integration/channel/simple/channel.yaml
- upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Cherry pick of #11046 on release-1.20.
#11046: Add channels entries for image architecture
> Automated cherry pick of #11046: Add channels entries for image architecture

- nodeup/pkg/model/context.go
- nodeup/pkg/model/protokube.go
Also add it to protokube's PATH.
[All of our flatcar jobs](https://testgrid.k8s.io/kops-distro-flatcar#Summary) are currently failing because channels arent being applied.
A newly added error log reports that kubectl isn't in protokube's PATH.
This adds the kubectl's location (/opt/bin) to protokube's PATH.
See https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-distro-imageflatcar/1371379886664454144/artifacts/54.206.100.130/protokube.log (search `error running kubectl` )
> Download kubectl to /opt/kops/bin on Flatcar OS

- channels/alpha
- channels/stable
- docs/releases/1.20-NOTES.md
- tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
- tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
Previously k8s 1.18+ would always match with COS rather than Ubuntu 20.04 because of the unbound version range.
This should fix the failure to download logs via SSH here: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-gce-kubetest2/1373013584195358720
The instance groups confirm the use of COS rather than u2004: https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-gce-kubetest2/1373013584195358720/artifacts/instancegroups.yaml
we may need to cherrypick the test updates to release-1.20
> Fix GCE channels version constraints

- channels/alpha
Update alpha channel with recent k8s releases:
* https://github.com/kubernetes/kubernetes/releases/tag/v1.20.5
* https://github.com/kubernetes/kubernetes/releases/tag/v1.19.9
* https://github.com/kubernetes/kubernetes/releases/tag/v1.18.17
> Update k8s versions with March 2021 releases

- pkg/model/iam/iam_builder.go
Should not be needed; dns-controller should run on the control-plane
node so there should not be a bootstrapping problem with the nodes.
Reverts #10529
> Don't add control-plane DNS permissions with UseServiceAccountIAM

- docs/cluster_spec.md
[`CustomCPUCFSQuotaPeriod`](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features) feature gate is [required](https://github.com/kubernetes/kubernetes/pull/94687/files#diff-22e050d3cefdd68e1601d3aab0f1a7d42f1c2563bd04ae9b3dae5f43af80a205R56-R58) to set custom `cpuCFSQuotaPeriod`.
> fix(docs): cpuCFSQuotaPeriod needs a feature gate

- channels/alpha
- channels/stable
- pkg/util/templater/templater_test.go
- tests/integration/channel/integration_test.go
- tests/integration/channel/simple/channel.yaml
- tests/integration/create_cluster/complex/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
- tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
- tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
Update Ubuntu 20.04 LTS (Focal) AMI to latest `20210315`.
N/A
None
> Update Ubuntu 20.04 to latest AMI

- pkg/nodelabels/builder.go
The constant was unused, confusing and deprecated.  I shouldn't have
introduced it!
> Remove unused RoleLabelName16

- pkg/model/master_volumes.go
This PR fixes the problem described in #10842. 
As described in the issue, AWS allows gp3 volumes of any size to have a baseline of 3000 IOPS. This PR adds the additional condition necessary to validate IOPS to size ratio correctly.
> Add additional IOPS validation for AWS EBS gp3 volumes

- dns-controller/README.md
- dns-controller/pkg/watchers/BUILD.bazel
- dns-controller/pkg/watchers/pod_test.go
Follow up to #11069; use cmp.Diff to compare got vs want.
> Deeper validation in dns controller tests

- protokube/pkg/protokube/kube_boot.go
This commit will have protokube eagerly retry to connect to kube-apiserver instead of the 1 minute sync loop.
Another benefit is that we know that tasks are run in order and that labels are always applied before channels etc
With very few samples, it looks like a cluster gets the DNS entry about 1-2 minutes earlier, which I think makes sense.
Ref #11050
> Ensure protokube can connect to kube-apiserver before starting the sync loop

- nodeup/pkg/model/protokube.go
With protokube now a service, I think we can remove the dbus dependency. 
I have tested this with kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-11-19 image on master build and i was able to successfully bring up a cluster.
> Remove dbus dependency

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Cherry pick of #11078 on release-1.20.
#11078: Update aws-cni image to 1.7.10
> Automated cherry pick of #11078: Update aws-cni image to 1.7.10

- upup/pkg/fi/nodeup/nodetasks/BUILD.bazel
- upup/pkg/fi/nodeup/nodetasks/bootstrap_client.go
ref: https://github.com/kubernetes/kops/issues/11050#issuecomment-803620244
> Have nodeup retry kops-controller bootstrapping sooner if DNS isn't setup

- tests/e2e/kubetest2-kops/aws/zones.go
This adds zones that have been released since this list was updated.
This also reenables some that were disabled due to capacity for c4 instance types - we use c5 now so hopefully they'll have sufficient coverage.
We can disable them if we continue to run into availability issues.
Long term I could see us using the ec2.DescribeAvailabilityZones and ec2.DescribeInstanceTypeOfferings APIs to pick random zone(s) in a random region and guarantee that it has the needed instance types.
I'm doing this to try to avoid Route53 API throttling mentioned in https://github.com/kubernetes/kops/pull/11099#issuecomment-803666505
> Update AWS zones used by e2e tests

- protokube/pkg/protokube/kube_boot.go
Cherry pick of #11093 on release-1.20.
#11093: Ensure protokube can connect to kube-apiserver before
> Automated cherry pick of #11093: Ensure protokube can connect to kube-apiserver before

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.9.yaml.template
Cherry pick of #11091 on release-1.20.
#11091: Put awslbcontroller on the control-plane
> Automated cherry pick of #11091: Put awslbcontroller on the control-plane

- upup/pkg/fi/nodeup/nodetasks/BUILD.bazel
- upup/pkg/fi/nodeup/nodetasks/bootstrap_client.go
Cherry pick of #11101 on release-1.20.
#11101: Have nodeup retry kops-controller bootstrapping sooner if DNS
> Automated cherry pick of #11101: Have nodeup retry kops-controller bootstrapping sooner if DNS

- cloudmock/aws/mockec2/address.go
- cloudmock/aws/mockelbv2/loadbalancers.go
- cloudmock/aws/mockelbv2/targetgroups.go
- upup/pkg/fi/cloudup/awstasks/elastic_ip.go
- upup/pkg/fi/cloudup/awstasks/elastic_ip_test.go
- upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
- upup/pkg/fi/cloudup/awstasks/targetgroup.go
- upup/pkg/fi/cloudup/awsup/aws_utils.go
These are the remaining resources that support "tag on create" of which we werent taking advantage.
This allows more fine-grained IAM permissions for the kops cli.
ref: https://github.com/kubernetes/kops/issues/9640
> Use "tag on create" for EIPs, NLBs, and TargetGroups

- nodeup/pkg/bootstrap/BUILD.bazel
- nodeup/pkg/bootstrap/install.go
- nodeup/pkg/bootstrap/install_test.go
- nodeup/pkg/bootstrap/tests/simple/tasks.yaml
> Load env vars from file for kops-configuration service

- pkg/model/domodel/droplets.go
We add tags to the droplets in order to match the correct volume that needs to be attached. The volumes for etcd-main and etcd-events are also tagged and the etcd-manager does this mapping.
Due to this [change](https://github.com/kubernetes/kops/commit/31f8cbd571964f19d3c31024ddba918998d29929), this was breaking DO droplets to volume matching logic and the new clusters wasn't coming up.
FYI - @rifelpet @timoreimann 
I can work on a better logic going further, but would need this change to go in so I can continue to test the e2e tests.
Please let me know your thoughts, thanks !
> [DigitalOcean] Fix DO Tag issue

- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/kubetest2-kops/gce/ssh.go
Originally I had thought we were relying on ssh keys mounted from a secret,
it turns out kubetest 1 generated the keys indirectly through gcloud.
This runs the [same command as kubetest 1](https://github.com/kubernetes/test-infra/blob/de07aa4b89f1161778856dc0fed310bd816aad72/kubetest/main.go#L808), creating and uploading the SSH keys.
I'm hoping to get [this failing job](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-gce-kubetest2/1373617563581288448) to get ssh access and dump the node logs as artifacts so we can fix the job.
> Kubetest2 - Setup SSH keys for GCE

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #11124 on release-1.20.
#11124: Update kube-router to v1.2.0
> Automated cherry pick of #11124: Update kube-router to v1.2.0

- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
> Validate that kube-apiserver has the necessary authz modes set

- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
Cherry pick of #11127 on release-1.19.
#11127: Validate that kube-apiserver has the necessary authz modes
> Automated cherry pick of #11127: Validate that kube-apiserver has the necessary authz modes

- cmd/kops/toolbox_instance_selector.go
Cherry pick of #11048 on release-1.19.
#11048: remove instance-selector label
> Automated cherry pick of #11048: remove instance-selector label

- cmd/kops/toolbox_instance_selector.go
`kops toolbox instance-selector` fails due to https://github.com/kubernetes/kops/pull/10910 which improves the label validation. Making kops.k8s.io/instance-selector: "1" a node label rather than a cloud label should bypass this validation check. I also think it should make more sense to make it a node label rather than a cloud label.
> Remove instance-selector label

- tests/e2e/kubetest2-kops/deployer/publish.go
- tests/e2e/kubetest2-kops/deployer/template.go
- tests/e2e/kubetest2-kops/gce/ssh.go
- tests/e2e/pkg/kops/download.go
- tests/e2e/pkg/target/terraform.go
- tests/e2e/pkg/tester/kubectl.go
- tests/e2e/pkg/util/zip.go
Also update all ioutil references to their go 1.16 replacements
Should fix this error: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-gce-kubetest2/1374583912889585664#1:build-log.txt%3A105
> Kubetest2 - fix temp directory created for GCE SSH keys

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
This reverts commit b32689ba.
Seems that this is not just an easy version bump and should not block the release.
> Revert "Update kube-router to v1.2.0"

- pkg/model/BUILD.bazel
- pkg/model/iam.go
- pkg/model/iam/BUILD.bazel
- pkg/model/iam/iam_builder.go
- pkg/model/iam/iam_builder_test.go
- pkg/model/iam_test.go
future proof AWS endpoint and IAM Prefix generation to handle new AWS Partitions and future new ones. Offload to AWS SDK
> replace hard coded aws region checks with aws sdk calls

- pkg/model/BUILD.bazel
- pkg/model/iam.go
- pkg/model/iam/BUILD.bazel
- pkg/model/iam/iam_builder.go
- pkg/model/iam/iam_builder_test.go
- pkg/model/iam_test.go
Cherry pick of #11119 on release-1.20.
#11119: replace hard coded aws region checks with aws sdk calls
> Automated cherry pick of #11119: replace hard coded aws region checks with aws sdk calls

- tests/e2e/kubetest2-kops/aws/zones.go
- tests/e2e/kubetest2-kops/deployer/up.go
Kops defaults to a network named "default" and has issues with network modes.
Apparently there is a "default" network within the projects that boskos issues,
causing `kops create cluster` to fail some cloudup validation.
By specifying a cluster-specific network, kops will create this new network with the non-deprecated settings.
Hoping to fix this error: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-gce-kubetest2/1374704711222956032
and here is the line number in question, notice that `a` is not nil at this point, indicating that `Find` was able to find an existing Network:
https://github.com/kubernetes/kops/blob/42fbb1c1c5b1f46405294ded37395906743c5b16/upup/pkg/fi/cloudup/gcetasks/network.go#L141-L143
Also disabling ap-northeast-3 zones for now
> kubetest2 - Specify GCE network name 

- docs/addons.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/clusterautoscaler.go
- upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
Resolves #11117
Added some parameters to the docs that weren't specified before as well.
> Add scaleDownDelayAfterAdd to clusterAutoscaler spec

- docs/addons.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/clusterautoscaler.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
Cherry pick of #11140 on release-1.20.
#11140: Add scaleDownDelayAfterAdd to clusterAutoscaler spec
> Automated cherry pick of #11140: Add scaleDownDelayAfterAdd to clusterAutoscaler spec

- pkg/instancegroups/instancegroups.go
In some rare cases, we hit an NPR because the k8s code tries to use the
ctx we are not passing.
> Pass ctx to drain helper

- docs/creating_subdomain.md
- docs/examples/kops-test-route53-subdomain.md
- docs/getting_started/aws.md
An issue was raised to the product security commitee that the
aws example domains in kops documentation were registrable and
could be used for various attacks against users (should they
run the specific examples)
Signed-off-by: Luke Hinds <lhinds@redhat.com>
> Change registrable domains to placeholders

- docs/releases/1.19-NOTES.md
Make a clearer distinction between exporting kubeconfig (including
server endpoints / certificates) vs exporting credentials.
Issue #11021
> Clarify release notes around exporting kubeconfig

- cmd/kops/export_kubecfg.go
- cmd/kops/update_cluster.go
- docs/cli/kops_export_kubecfg.md
- docs/cli/kops_update_cluster.md
It wasn't entirely clear to me that this had to be the name of a user
kubeconfig section.
> Expand flag help on --user flags

- docs/getting_started/aws.md
Fix some markdown linting and also fix headings.
The "Creating your first cluster" heading was top level heading so it breaks the right hand side table of contents as it will stop listing the headings after that point.
> Update Getting Started AWS guide

- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
This will in most cases mean kops-controller is only updated when the CP node is rolled and should increase the chances of compatible controller<->CP updates
> Only update kops-controller pods on deletion

- tests/e2e/kubetest2-kops/builder/build.go
this fix is needed for the network plugin presubmits to pass in https://github.com/kubernetes/kops/pull/11166. they were recently migrated to kubetest2 in https://github.com/kubernetes/test-infra/pull/21609
> kubetest2 - Pass GOPATH when building kops

- upup/pkg/fi/cloudup/awstasks/BUILD.bazel
- upup/pkg/fi/cloudup/awstasks/natgateway.go
current solution is not filtering multiple natgateways from route table. We do have use-case where we have multiple natgateways. So when I add filtering to this function, it will only manage kops natgateways and not others.
> Filter kOps NatGateways from route table

- cmd/kops/create_cluster.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/new_cluster.go
The main motivation for this is to get some e2e using api servers.
The rest of the instance group flags should be supported before we remove the feature flag.
> Allow setting dedicated apiserver node count from create cluster cmd

- cloudbuild.yaml
The most recent job timed out: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/kops-postsubmit-push-to-staging/1378826272158781440
This increases the timeout and updates the images it uses.
> Increase timeout and update images for postsubmit job

- tests/e2e/kubetest2-kops/deployer/deployer.go
- tests/e2e/kubetest2-kops/deployer/up.go
The flatcar jobs are failing because the OS performs package updates and a reboot after initial launch, even with the latest AMI.
This causes the cluster to timeout on its validation.
Exposing a flag will allow us to conditionally extend the validation for the flatcar tests
See https://testgrid.k8s.io/kops-distro-flatcar
> Kubetest2 - Add flag to expose cluster validation wait time

- upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
This PR removes the setting of the obsolete `rootVolumeSize` field in order to resolve a validation error returned from the Spot backend:
```
{
"request": {
"id": "dedd14d9-7f56-4bee-951b-redacted",
"url": "/ocean/aws/k8s/launchSpec",
"method": "POST",
"timestamp": "2021-04-06T19:33:53.885Z"
},
"response": {
"status": {
"code": 400,
"message": "Bad Request"
},
"errors": [
{
"code": "ValidationError",
"message": "\"rootVolumeSize\" must not exist simultaneously with [blockDeviceMappings]",
"field": "body:launchSpec"
}
]
}
}
```
> Spotinst: Use BDM to configure the root volume size at VNG level

- pkg/model/awsmodel/spotinst.go
- upup/pkg/fi/cloudup/spotinsttasks/ocean.go
The PR removes the headroom configuration from the cluster level. Custom headroom should now be applied only at the VNG level, while the cluster should use automatic headroom.
> Spotinst: Configure headroom resources only at the VNG level

- upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
Cherry pick of #11179 on release-1.20.
#11179: fix(spot/ocean): configure root volume size using bdm
> Automated cherry pick of #11179: fix(spot/ocean): configure root volume size using bdm

- pkg/model/awsmodel/spotinst.go
- upup/pkg/fi/cloudup/spotinsttasks/ocean.go
Cherry pick of #11181 on release-1.20.
#11181: fix(spot/ocean): configure headroom resources only at the vng
> Automated cherry pick of #11181: fix(spot/ocean): configure headroom resources only at the vng

- docs/cluster_spec.md
- tests/e2e/kubetest2-kops/deployer/up_test.go
> Correct typos

- docs/releases/1.19-NOTES.md
- docs/releases/1.20-NOTES.md
Also fix a small typo I noticed in the 1.19 notes.
> Docs: Remove 'prerelease' warning from 1.20

- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/kubetest2-kops/deployer/deployer.go
- tests/e2e/kubetest2-kops/deployer/down.go
- tests/e2e/kubetest2-kops/deployer/template.go
- tests/e2e/kubetest2-kops/deployer/up.go
- tests/e2e/kubetest2-kops/gce/gcs.go
Since we use boskos to get a random GCP project, we need to create a bucket per project so that permissions will be setup properly.
This matches the existing kubetest1 behavior. It turns out kubetest1 never actually used `gs://k8s-kops-gce`.
Ref: https://github.com/kubernetes/test-infra/blob/726b9ea2a24eaaa152ab6c63f443f45941d45116/kubetest/kops.go#L880-L903
This should fix the gce kubetest2 job: https://testgrid.k8s.io/kops-gce#kops-gce-kubetest2
specifically the permission errors in etcd manager: https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-gce-kubetest2/1380986173320597504/artifacts/34.105.15.245/etcd.log
> Kubetest2 - Create project-specific state store buckets in GCP

- tests/e2e/kubetest2-kops/deployer/build.go
Previously we would upload the custom kops build to the stage location but the kops commands would not have their KOPS_BASE_URL overridden.
This ensures that all kops commands have KOPS_BASE_URL correctly set.
We only support gs:// paths for --stage-location, as verified earlier in this function.
[Here](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kops-e2e-kubernetes-aws/1377343455298064384#1:build-log.txt%3A635) is a kubetest1 presubmit demonstrating that KOPS_BASE_URL was overridden (line 635). [Kubetest2](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kops-e2e-kubernetes-aws/1381294979149729792#1:build-log.txt%3A438) does not have that logging statement, confirming that it wasn't being overridden.
This also updates the default …
> Kubetest2 - Set KOPS_BASE_URL to --build's stage location

- tests/e2e/kubetest2-kops/deployer/up.go
- tests/e2e/kubetest2-kops/gce/gcs.go
The job seems to be failing to check if the bucket exists or not. This should cause the job to fail sooner and hopefully log more info about why it failed.
See https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-gce-kubetest2/1381529768943423488#1:build-log.txt%3A121
You see the `gsutil ls` command but not the `gsutil mb` command,
> Kubetest2 - detect errors creating GCS bucket

- tests/e2e/kubetest2-kops/gce/gcs.go
should fix this error: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-gce-kubetest2/1381650445893636096#1:build-log.txt%3A122
> Kubetest2 - Ensure the bucket path is the final gsutil arg

- pkg/util/templater/template_functions.go
Cherry pick of #11220 on release-1.20.
#11220: Use "string" for architecture type in ChannelRecommendedImage
> Automated cherry pick of #11220: Use "string" for architecture type in ChannelRecommendedImage

- pkg/util/templater/template_functions.go
> Use "string" for architecture type in ChannelRecommendedImage

- nodeup/pkg/model/context.go
- nodeup/pkg/model/kube_apiserver.go
- nodeup/pkg/model/kubelet.go
- nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
Without secure node auth enabled, commands like `kubectl logs` may fail with certain configurations.
As of kubernetes 1.11, we explicitly disable anonymousauth on kubelet for new clusters. We also always disable AlwaysAllow auth mode for kubelet as of 1.19. This combination works for new clusters and those who have already disabled anonymousAuth for kubelet, which accounts for most users, it seems.
But old clusters upgrading from pre 1.11 face issues with commands like `kubectl logs` because for these clusters, apiserver is anonymous and anonymous users are not allowed to talk to kubelet per our RBAC rules.
The logic for this is 
```
// UseSecureKubelet checks if the kubelet api should be protected by a client certificate.
func (c *NodeupModelContext) UseSecureKubelet() bool {
return …
```
> Always secure api -> kubelet communication

- nodeup/pkg/model/context.go
- nodeup/pkg/model/kube_apiserver.go
- nodeup/pkg/model/kubelet.go
- nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
Cherry pick of #11185 on release-1.20.
#11185: Use secure kubelet auth
> Automated cherry pick of #11185: Use secure kubelet auth

- pkg/model/BUILD.bazel
- pkg/model/master_volumes.go
The extra validation in the task was failing for various reported cases related to Gp3 logic like volumes smaller than 7 GB.
Next step would be to move this in the validation section and do it for all volumes, not just the etcd ones.
> Fix etcd volume validation logic

- pkg/model/BUILD.bazel
- pkg/model/master_volumes.go
Cherry pick of #11225 on release-1.20.
#11225: Fix etcd volume validation logic
> Automated cherry pick of #11225: Fix etcd volume validation logic

- docs/releases/1.19-NOTES.md
> fix a typo

- pkg/apis/kops/validation/cluster.go
Cherry pick of #11228 on release-1.20.
#11228: Remove validations for EBS from cluster validation
> Automated cherry pick of #11228: Remove validations for EBS from cluster validation

- pkg/apis/kops/validation/cluster.go
Refs: https://github.com/kubernetes/kops/issues/11062
We can create clusters without specifying `encryptedVolume`, but default encryption is determined by [this setting in AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default). And default value of `encryptedVolume` in kops spec is `false`. As a result,  there is a difference between the kops spec and the AWS entity. 
To resolve this difference, we have to update `encryptedVolume` in our kops spec. But at the moment kops rejects changes to `encryptedVolume`.
Therefore, I removed a validation for `encryptedVolume` in `kops edit`.
Even if I remove the validation in `kops edit`, there is a validation for `encryptedVolume` in `kops update` so it is no problem.
> Remove validations for EBS from cluster validation

- pkg/model/context.go
'sv' may have 'nil' or other unexpected value
> 'sv' may have 'nil' or other unexpected value 

- protokube/pkg/protokube/channels.go
- upup/pkg/fi/executor.go
- upup/pkg/fi/task.go
After staring at prow job outputs and nodeup logs for a long time, i'm removing some of the unnecessary logging statements.
The first will remove these in the kops cli:
```
I0318 08:50:47.113867    2772 executor.go:111] Tasks: 80 done / 82 total; 2 can run
I0318 08:50:48.918239    2772 executor.go:137] Task "AutoscalingGroup/master-ap-northeast-1a.masters.e2e-e6110d5e7d-a98da.test-cncf-aws.k8s.io" not ready: waiting for the IAM Instance Profile to be propagated
I0318 08:50:48.918286    2772 executor.go:137] Task "AutoscalingGroup/nodes-ap-northeast-1a.e2e-e6110d5e7d-a98da.test-cncf-aws.k8s.io" not ready: waiting for the IAM Instance Profile to be propagated
I0318 08:50:48.918297    2772 executor.go:155] No progress made, sleeping before retrying 2 task(s) 
```
The second will remove these …
> Logging cleanup

- cloudmock/aws/mockautoscaling/api.go
- cloudmock/aws/mockautoscaling/group.go
- cmd/kops/get_instances.go
- pkg/cloudinstances/cloud_instance.go
- pkg/cloudinstances/cloud_instance_group.go
- pkg/instancegroups/BUILD.bazel
- pkg/instancegroups/instancegroups.go
- pkg/instancegroups/rollingupdate_test.go
- pkg/instancegroups/rollingupdate_warmpool_test.go
- pkg/resources/digitalocean/cloud.go
- pkg/resources/spotinst/resources.go
- pkg/validation/validate_cluster.go
- upup/pkg/fi/cloudup/aliup/status.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/azure/status.go
- upup/pkg/fi/cloudup/openstack/server_group.go
* `kops get instances` mark warm pool nodes
* rolling update warm pool
* Warm pool instances will terminate first
* Warm pool instances will terminate without validation as they are not part of the cluster
Based on #11216 
/hold
> Give kOps CLI knowledge about ASG warm pools

- channels/alpha
* https://github.com/kubernetes/kubernetes/releases/tag/v1.20.6
* https://github.com/kubernetes/kubernetes/releases/tag/v1.19.10
* https://github.com/kubernetes/kubernetes/releases/tag/v1.18.18
> Bump k8s versions with April 2021 releases in Alpha channel

- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/kubetest2-kops/deployer/up.go
If --up is specified then we always delete any previous cluster with the same name since it would conflict otherwise and ensures leaked resources are cleaned up.
We don't do this if --terraform is specified because Down() will run `terraform destroy` but each kubetest2 invocation uses a random temp directory for its terraform state, so it wouldn't know of any resources to destroy
> Kubetest2 - Cleanup leaked resources from previous clusters

- channels/pkg/channels/addon.go
On brand new clusters, all CP nodes will become `NeedUpdate` as kops-controller installs for the first time. This PR do not mark nodes as `NeedUpdate` on first addon install.
> Don't set NeedUpdate on first addon install

- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
- upup/pkg/fi/dryrun_target.go
Refs: #11253 
When I remove mixedInstancesPolicy using `kops edit`, there are difference actual and expected. But kops don't detect that changes. So, it was causing `internal consistency error`.
I changed `buildChangeList`, so kops can detect field changes when I remove mixedInstancePolicy.
> Make it possible to detect field changes when mixedInstancePolicy is removed

- nodeup/pkg/model/context.go
- nodeup/pkg/model/kube_proxy.go
- nodeup/pkg/model/kube_proxy_test.go
- nodeup/pkg/model/networking/cilium.go
- nodeup/pkg/model/tests/golden/minimal/tasks-warmpool.yaml
- upup/pkg/fi/nodeup/nodetasks/BUILD.bazel
- upup/pkg/fi/nodeup/nodetasks/pull_image.go
- upup/pkg/fi/nodeup/nodetasks/service.go
This PR will optimise Node initialisation time by pulling kube-proxy and cilium images if we are in warming mode.
> Pre-pull cilium and kube-proxy in warming mode

- channels/alpha
- channels/stable
- pkg/apis/kops/channel.go
- upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Remove the default image hard-coded in populate_instancegroup_spec.go.
> Add Azure image to alpha/stable channel

- pkg/apis/kops/channel.go
- upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Cherry pick of #11271 on release-1.20.
#11271: Add Azure image to alpha/stable channel
> Automated cherry pick of #11271: Add Azure image to alpha/stable channel

- pkg/instancegroups/instancegroups.go
- pkg/instancegroups/rollingupdate_test.go
Per kubernetes/kubernetes#90823 (k8s 1.19), nodes that are unschedulable are no longer removed from load balancers. Rolling update needs to add the appropriate label to preserve this functionality.
/area rolling-update
/kind bug
> Exclude nodes from load balancers upon cordoning

- pkg/instancegroups/instancegroups.go
- pkg/instancegroups/rollingupdate_test.go
Cherry pick of #11273 on release-1.19.
#11273: Exclude nodes from load balancers upon cordoning
> Automated cherry pick of #11273: Exclude nodes from load balancers upon cordoning

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
Cherry pick of #11270 on release-1.20.
#11270: Fix cilium template scoping typo
> Automated cherry pick of #11270: Fix cilium template scoping typo

- upup/pkg/fi/cloudup/awstasks/elastic_ip.go
Cherry pick of #11276 on release-1.20.
#11276: If one tries to use eip with a public ip that doesn't exist,
> Automated cherry pick of #11276: If one tries to use eip with a public ip that doesn't exist,

- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
This PR upgrades `spotinst/ocean-controller` to v1.0.74.
> Spotinst: Update spotinst/ocean-controller to v1.0.74

- nodeup/pkg/model/context.go
- nodeup/pkg/model/kube_proxy.go
- nodeup/pkg/model/kubectl.go
- nodeup/pkg/model/kubelet.go
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
This PR includes two fixes for issues I ran into when stress testing the API. Both are technically around kops-controller going into crashloop, preventing more api servers to join the cluster. See the individual commits for details.
* Make kops-controller use the local apiserver
* Make APIServer role less dependent on kops-controller
> Apiserver fixes

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #11286 on release-1.20.
#11286: feat(spot/addon): bump ocean-controller to 1.0.74
> Automated cherry pick of #11286: feat(spot/addon): bump ocean-controller to 1.0.74

- cmd/kops/create.go
When you execute `kops create`, it will prompt:
`To deploy these resources, run: kops update cluster %s --yes`, and if you copy/paste this line it wont work.
The correct line is:
`To deploy these resources, run: kops update cluster --name %s --yes`
> fix: create.go doesnt add --name flag to the prompt: kops update cluster

- docs/addons.md
- docs/releases/1.21-NOTES.md
- pkg/resources/aws/eventbridge.go
There were more missing permissions for NTH Queue Processor for deleting/updating the resources. Perhaps at this point it would be reasonable to grant full access to sqs and eventbridge, similar to how the other kops user permissions are configured? 
Additionally I noticed a small error when deleting EventBridge rules that had already had their targets removed, so that check is included in here. I can split it into a different pr if that's the preference
> fix permissions required for NTH Queue Processor

- docs/addons.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
This PR allows to set a default clusterIssuer in cert-manager
We're using this heavily to enable automated certs in many ingresses only with the acme annotation
> Add ability to set a default Issuer in certManager addon

- docs/addons.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
Cherry pick of #11281 on release-1.20.
#11281: Add ability to set a default Issuer in certManager addon
> Automated cherry pick of #11281: Add ability to set a default Issuer in certManager addon

- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
> Use the full operator instead of the generic one

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #11312 on release-1.20.
#11312: Use the full operator instead of the generic one
> Automated cherry pick of #11312: Use the full operator instead of the generic one

- upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
- Bump image to v0.4.3
- Set new default kubelet options based on upstream behavior
- Set default requested resources
As part of https://github.com/kubernetes/kops/issues/11251
> [metrics-server] Bump manifest to latest stable

- k8s/crds/kops.k8s.io_clusters.yaml
- nodeup/pkg/model/BUILD.bazel
- nodeup/pkg/model/awsebscsidriver.go
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/BUILD.bazel
- pkg/model/components/awsebscsidriver.go
- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/populate_cluster_spec.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- upup/pkg/fi/nodeup/command.go
AWS EBS CSI Driver:
- Update manifests
- Bump components version
- Add API capability of setting Version + VolumeLimit
- Add support for warm pools
- Remove snapshot-controller resources as it should be independent from
any CSI driver, check here --> https://kubernetes.io/blog/2020/12/10/kubernetes-1.20-volume-snapshot-moves-to-ga/#how-to-deploy-volume-snapshots
> [csi/aws] Bump templates + add support for warm pools

- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
Parameters for leader elections have changed in v2.2.0, which causes the
csi-provisioner to not start anymore.
> Fix arguments to csi-provisioner after bump to v2.2.0

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/commands/set_cluster_test.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
After upgrading Cilium to 1.8 via kops one of our clusters had a total
outage due to cilium reporting errors as below:
```
level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=592 error="Failed to load tc filter: exit status 1" identity=40147 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```
upon searching Cilium slack we found the below thread:
https://cilium.slack.com/archives/C1MATJ5U5/p1616400216167600
which recommended setting `enable-host-reachable-services` to true will
address the problems. We set the field and it fixed our issues too,
however we observed that kops does not have a means to configure this
hence this PR.
We will like to have this backported after it has been merged.
> Add support for configuring Cilium enable-host-reachable-services.

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #11339 on release-1.20.
#11339: Update Calico to v3.18.2
> Automated cherry pick of #11339: Update Calico to v3.18.2

- pkg/model/awsmodel/nodeterminationhandler.go
- tests/integration/update_cluster/nth_sqs_resources/cloudformation.json
- tests/integration/update_cluster/nth_sqs_resources/data/aws_sqs_queue_nthsqsresources-example-com-nth_policy
- upup/pkg/fi/cloudup/awstasks/sqs.go
* one case of AWS returning different JSON than we passed
* AWS returning a field we do not (and can not) build an expected value of
> Fix SQS resource flapping

- channels/pkg/channels/addon.go
Cherry pick of #11328 on release-1.20.
#11328: Set SAN for addon CAs
> Automated cherry pick of #11328: Set SAN for addon CAs

- channels/pkg/channels/addon.go
We currently don't set alternative names on addon CAs, which results in failure for anything running go 1.16.
> Set SAN for addon CAs

- tests/e2e/go.mod
- tests/e2e/go.sum
- tests/e2e/scenarios/upgrade/run-test
This should fix the upgrade jobs: https://testgrid.k8s.io/kops-misc#kops-aws-upgrade
> Update kubetest2 dependency and fix install method for upgrade scenario

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/commands/set_cluster_test.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
Cherry pick of #11333 #11337 on release-1.20.
#11333: Add support for configuring Cilium
#11337: Add `enable-host-reachable-services` to 1.8 and generic
> Automated cherry pick of #11333: Add support for configuring Cilium #11337: Add `enable-host-reachable-services` to 1.8 and generic

- tests/e2e/kubetest2-kops/deployer/common.go
Fixes `panic: runtime error: slice bounds out of range [:-1]` found here: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-scenario-aws-cloud-controller-manager/1387534126441041920
Also fixes a logging statement to include the cluster name (empty cluster name is seen in those same logs)
> Fix kubetest2 panic inheriting env vars

- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/pollinterval/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
xRef: https://github.com/kubernetes-sigs/etcdadm/pull/213
This will have no effect without the necessary binaries in the `etcd-manager` image.
`/run` is already available in `/rootfs/run` so there are no new security concerns.
/cc @olemarkus
> Mount /run inside etcd-manager pods for systemd mounts

- pkg/validation/validate_cluster.go
- pkg/validation/validate_cluster_test.go
Ran into this issue while doing rolling-update on our cluster today. The rolling updated was cancelled (for unrelated reasons) before it could complete.
> Ignore detached nodes when doing validate cluster

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/nodeterminationhandler.go
- upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template
Node termination handler as all daemonSets may play a critical role in
capacity planning, define resource policy for chosing instanceType etc.
In this commit, we enable users to define resources themselves to meet
their needs and also removed limits to convey with the chosen strategy
to avoid limits on such components.
> [addons/nth] Add capability to define resources

- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/pollinterval/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Cherry pick of #11352 on release-1.20.
#11352: Mount /run inside etcd-manager pods for systemd mounts
> Automated cherry pick of #11352: Mount /run inside etcd-manager pods for systemd mounts

- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/cilium.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
> Expose hubble agent when hubble is enabled

- docs/addons.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
This PR allows provisioning of cert-manager externally. It actually leads to a no-op, but makes checks (`IsCertManagerEnabled`) succeed so that other dependent addons are deployable.
> Allow cert-manager to be provisioned externally

- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/cilium.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #11314 on release-1.20.
#11314: Expose hubble agent when hubble is enabled
> Automated cherry pick of #11314: Expose hubble agent when hubble is enabled

- pkg/model/bootstrapscript.go
- tests/integration/update_cluster/minimal-gp3/cloudformation.json
- tests/integration/update_cluster/minimal-gp3/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/minimal-gp3/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
- tests/integration/update_cluster/minimal-gp3/in-v1alpha2.yaml
- tests/integration/update_cluster/minimal-gp3/kubernetes.tf
etcd-manager expands the data volume on restart to the max available.
> Mark control-plane node for update when etcd volume size changes

- pkg/model/bootstrapscript.go
- tests/integration/update_cluster/minimal-gp3/cloudformation.json
- tests/integration/update_cluster/minimal-gp3/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/minimal-gp3/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
- tests/integration/update_cluster/minimal-gp3/in-v1alpha2.yaml
- tests/integration/update_cluster/minimal-gp3/kubernetes.tf
Cherry pick of #11365 on release-1.20.
#11365: Mark control-plane node for update when etcd volume size
> Automated cherry pick of #11365: Mark control-plane node for update when etcd volume size

- upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template
https://github.com/kubernetes/controller-manager/blob/v0.21.0/pkg/clientbuilder/client_builder_dynamic.go#L201
seems that controller manager needs new permission that is not documented anywhere.
> add permission to create sa tokens

- nodeup/pkg/model/logrotate.go
"unused variable" linting didn't catch this because we were referencing `k8sVersion` in the error check conditional.
> Remove unused k8s version parsing

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
https://docs.projectcalico.org/archive/v3.18/release-notes/#v3183
/cc @olemarkus
> Update Calico to v3.18.3 for kOps 1.20

- tests/e2e/scenarios/kops-upgrade/run-test.sh
apparently it is significantly different from BSD.
fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-misc-kops-upgrade/1389903687089917952
> Kubetest2 - Fix GNU mktemp syntax

- tests/e2e/scenarios/k8s-upgrade/run-test.sh
- tests/e2e/scenarios/kops-upgrade/run-test.sh
The test arg logic is now handled internally within kubetest2-tester-kops so we don't need these flags
fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-misc-upgrade/1390082366361309184#1:build-log.txt%3A1483
> kubetest2 - remove unnecessary flags from upgrade scripts

- docs/rotate-secrets.md
This should work more reliably independent of shell config.
> Quote `grep` patterns in docs/rotate-secrets.md

- pkg/model/iam/iam_builder.go
Cherry pick of #11393 on release-1.20.
#11393: Add elasticloadbalancing:ModifyTargetGroupAttributes to aws
> Automated cherry pick of #11393: Add elasticloadbalancing:ModifyTargetGroupAttributes to aws

- pkg/apis/kops/validation/legacy.go
- pkg/model/issuerdiscovery.go
Allows enabling trust by AWS with an externally-pubished or public-apiserver provider.
> Don't publish OIDC discovery if DiscoveryStore not set

- pkg/model/iam/iam_builder.go
- tests/integration/update_cluster/aws-lb-controller/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
> Add elasticloadbalancing:ModifyTargetGroupAttributes to aws lb controller

- docs/cluster_spec.md
The default volume type for root & etcd has been updated from `gp2` to `gp3` as of v1.20.0
Updating the doc to reflect this change.
https://github.com/kubernetes/kops/releases/tag/v1.20.0
> Update default volumes types in Cluster Documentation

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/pollinterval/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
We can now use etcd-manager as built from the kubernetes-sigs/etcdadm
repo.
> Use etcd-manager built from etcdadm repo

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/pollinterval/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Cherry pick of #11098 on release-1.20.
#11098: Use etcd-manager built from etcdadm repo
> Automated cherry pick of #11098: Use etcd-manager built from etcdadm repo

- pkg/model/components/awsebscsidriver.go
- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
Bump version and manifests of AWS EBS CSI Driver to the first GA release.
> [addons/awscsidriver] Bump to GA release

- pkg/model/components/awsebscsidriver.go
- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
Cherry pick of #11418 on release-1.21.
#11418: Bump to GA release
> Automated cherry pick of #11418: Bump to GA release

- Makefile
- docs/development/release.md
- docs/release-process.md
- hack/set-version
- hack/verify-versions.sh
Cherry pick of #11413 on release-1.19.
#11413: Simplify use of hack/set-version
> Automated cherry pick of #11413: Simplify use of hack/set-version

- nodeup/pkg/model/kubelet_test.go
- nodeup/pkg/model/secrets.go
- pkg/model/pki.go
- upup/pkg/fi/fitasks/keypair.go
- upup/pkg/fi/vfs_castore.go
> Backport rename of service-account key to 1.20

- hack/verify-terraform.sh
Cherry pick of #11433 on release-1.21.
#11433: Update verify-terraform to use 0.15.3
> Automated cherry pick of #11433: Update verify-terraform to use 0.15.3

- hack/verify-terraform.sh
ref: https://github.com/kubernetes/kops/pull/11433
> release-1.19: Update verify-terraform to use latest 0.14 and 0.11 versions

- tests/e2e/kubetest2-kops/deployer/up.go
ExternalIPRange doesn't currently support IPv6 machines, so only call
it if we need to.  This allows local testing even with IPv6 enabled
machines.
> e2e: only get ExternalIPRange if we need it

- tests/e2e/scenarios/upgrade-ab/README.md
- tests/e2e/scenarios/upgrade-ab/run-test.sh
While trying to reproduce #11370.
> e2e upgrade-ab: a few more fixes and notes on how to run locally

- cmd/kops/create_cluster.go
- docs/cli/kops_create_cluster.md
- tests/integration/create_cluster/complex/expected-v1alpha2.yaml
- tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
- tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.16/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.17/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
- tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
- tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
Cherry pick of #11428 on release-1.21.
#11428: Create new clusters without forcing a container runtime
> Automated cherry pick of #11428: Create new clusters without forcing a container runtime

- cmd/kops/create_cluster.go
- docs/cli/kops_create_cluster.md
- tests/integration/create_cluster/complex/expected-v1alpha2.yaml
- tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
- tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.17/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
- tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
- tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
Decide which container runtime to use later in model, based on Kubernetes version and other settings.
Fixes: https://github.com/kubernetes/kops/issues/11402
> Create new clusters without forcing a container runtime

- hack/verify-terraform.sh
This updates the GPG key according to https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512
will cherry-pick something similar to fix https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/11390/pull-kops-verify-terraform/1391450673828073472
> Update verify-terraform to use 0.15.3

- upup/pkg/fi/cloudup/template_functions.go
Without sorting, the order is random and thus causes unnecessary cluster
updates.
> Sort --extra-tags of ebs-csi-driver

- upup/pkg/fi/cloudup/template_functions.go
Cherry pick of #11444 on release-1.21.
#11444: Sort --extra-tags of ebs-csi-driver
> Automated cherry pick of #11444: Sort --extra-tags of ebs-csi-driver

- tests/e2e/scenarios/aws-ebs-csi/run-test.sh
/cc @rifelpet 
If this works as intended, it should run tests both against the shim and against the CSI driver directly.
> Add test scenario for aws ebs csi driver

- Makefile
```
> fitask --help
-o, --output-base string               Output base; defaults to $GOPATH/src/ or ./ if $GOPATH is not set.
```
> Set the output base for fitask

- nodeup/pkg/model/kube_controller_manager.go
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-controller-manager.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-amd64.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-arm64.yaml
The hourly test that uses the HEAD of k/k [has been failing](https://testgrid.k8s.io/kops-latest#kops-aws-k8s-latest&show-stale-tests=) due to connection refused errors on the KCM livenessProbe. 
The failure is due to [this PR](https://github.com/kubernetes/kubernetes/pull/96216) which landed around the same time.
This updates the KCM livenessProbe to match upstream.
[This commit](https://github.com/kubernetes/kubernetes/commit/eb27b61cdbddd17a2990d61f3fb8250636220f74) shows the secure port has been present since k8s 1.12 so I think it should be safe to update unconditionally, but feedback is welcome.
> Fix KCM livenessProbe to use secure port

- pkg/model/components/clusterautoscaler.go
Cherry pick of #11462 on release-1.21.
#11462: Add support for CAS 1.21.0
> Automated cherry pick of #11462: Add support for CAS 1.21.0

- channels/alpha
* https://github.com/kubernetes/kubernetes/releases/tag/v1.20.7
* https://github.com/kubernetes/kubernetes/releases/tag/v1.19.11
* https://github.com/kubernetes/kubernetes/releases/tag/v1.18.19
> Update alpha channel with K8s releases from May-12 2021

- upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
- upup/pkg/fi/cloudup/gcetasks/router.go
Use the last component of the self-url for a router's region, rather
than the full URL.
Explicitly set the boolean pointer for `HasExternalIP` if the interface
attached to the instance does not have an access config (i.e. has no
public internet access).
Without this patch, both the router and instance template show pending
updates, neither of which can be applied as both are immutable
resources.
Signed-off-by: Nick Travers <n.e.travers@gmail.com>
> upup: gcetasks: fix diffs in instance template and router

- tests/e2e/scenarios/aws-ebs-csi/run-test.sh
> Discover what zone the cluster is in for the aws-ebs-csi driver tests

- upup/pkg/fi/cloudup/gcetasks/network.go
When a struct contains a default value, it is not present in the
serialized output attached to request bodies sent to GCP. In the case
that a user wishes to explicitly set the `AutoCreateSubnetworks` field
to `false`, the request sent to GCP does not contain this directive, and
the network is provisioned with the default of `true`.
Explicitly specify that the `false` value should be present on the
request sent to the GCP API, making use of the `ForceSendFields` field
in the requset struct.
Signed-off-by: Nick Travers <n.e.travers@gmail.com>
> upup: gcetasks: force send AutoCreateSubnetworks field when set to false

- tests/e2e/scenarios/aws-ebs-csi/run-test.sh
This should set the necessary tags for the iam roles to be able to use the test volumes
/cc @rifelpet
> Set the test cluster-tag

- upup/models/cloudup/resources/addons/aws-cloud-controller.addons.k8s.io/k8s-1.18.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/aws-cloud-controller.addons.k8s.io-k8s-1.18.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
Permission to create servcice account tokens
* We need the ability to create service account token because this is required by clientbuilder/controller-manager framework which we will be using in 1.21.
* This is required for the CCM to use 1 SA per controller, which follows principle of least privilege and makes audit logs easier to understand
Note: edited to remove change from daemonset -> deployment.  I think that change might still be valuable, at least as an option, but should be distinct from this change.
> [AWS CCM] Permission to create SA token

- upup/pkg/fi/cloudup/apply_cluster.go
This is the release-1.21 branch component of #11489.
> 1.21 branch: Announce k8s removals two kOps versions in advance

- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Following the changes on CoreDNS 1.8.3 (added in [commit](https://github.com/coredns/coredns/commit/9f72db12e73d6f1b7f69812baa4381fc7a1f04b3)), this PR adds permission to list and watch EndpointSlices resources.
> fix(coredns/rbac): add permission to list and watch endpointslices

- upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.9.yaml.template
- upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
- upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
Cherry pick of #11495 on release-1.21.
#11495: Set priorityClassName on critical addons
> Automated cherry pick of #11495: Set priorityClassName on critical addons

- upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
- upup/pkg/fi/cloudup/gcetasks/router.go
Cherry pick of #11460 on release-1.21.
#11460: upup: gcetasks: fix diffs in instance template and router
> Automated cherry pick of #11460: upup: gcetasks: fix diffs in instance template and router

- upup/pkg/fi/cloudup/gcetasks/network.go
Cherry pick of #11457 on release-1.21.
#11457: upup: gcetasks: force send AutoCreateSubnetworks field when
> Automated cherry pick of #11457: upup: gcetasks: force send AutoCreateSubnetworks field when

- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
This PR upgrades `spotinst/ocean-controller` to v1.0.75.
> Spotinst: Update spotinst/ocean-controller to v1.0.75

- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #11512 on release-1.21.
#11512: feat(spot/addon): bump ocean-controller to 1.0.75
> Automated cherry pick of #11512: feat(spot/addon): bump ocean-controller to 1.0.75

- tests/e2e/scenarios/aws-lb-controller/run-test.sh
With the way the two e2e suites are implemented, the last suite will overwrite the junit report of the former suites. So we need to split this in order to capture the output from both suites
> Split genkgo in two

- tests/e2e/kubetest2-kops/deployer/up.go
@timoreimann helped in updating the DO account to make it work on large droplets.
We used get an error like below before.
```
W0506 19:29:15.005456   11744 executor.go:139] error running task "Droplet/master-nyc1-3.masters.e2e-test-do.k8s.local" (7m28s remaining to succeed): POST https://api.digitalocean.com/v2/droplets: 422 This size is currently restricted, please send an additional payment to unlock.
```
I'll be testing this against our DO test and check if that works.
> [DigitalOcean] [WIP] Increase droplet size for e2e tests

- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
This should make the `groupchangepolicy` tests pass.
> Set default fstype for ebs volumes to ext4

- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
Cherry pick of #11525 on release-1.21.
#11525: Set default fstype for ebs volumes to ext4
> Automated cherry pick of #11525: Set default fstype for ebs volumes to ext4

- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
When EnablePromethesMetrics is enabled the
required metrics endpoints are exposed but
no annotations is included in the agents.
This commit includes the prometheus.io/scrape
and prometheus.io/port annotations that
prometheus scrappers can use for auto-discovery
Co-authored-by: tchatzig <t.chatzigeorgiou@thebeat.co>
> [addons/networking.cilium.io] enable prometheus scraping

- pkg/model/openstackmodel/servergroup.go
- pkg/model/openstackmodel/servergroup_test.go
- pkg/model/openstackmodel/tests/servergroup/configures-server-group-affinity-with-annotations.yaml
- upup/pkg/fi/cloudup/openstack/instance.go
This enables us to change the ServerGroup affinity policies using
annotations on instance groups.
The default affinity policy still is "anti-affinity".
> feat(openstack): enable configuration of servergroup affinities

- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
Cherry pick of #11514 on release-1.21.
#11514: enable prometheus scraping
> Automated cherry pick of #11514: enable prometheus scraping

- tests/integration/update_cluster/minimal-json/data/aws_launch_template_master-us-test-1a.masters.minimal-json.example.com_user_data
- tests/integration/update_cluster/minimal-json/data/aws_launch_template_nodes.minimal-json.example.com_user_data
- tests/integration/update_cluster/minimal-json/kubernetes.tf.json
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
- upup/pkg/fi/cloudup/terraformWriter/literal.go
Originally the JSON output was meant as a bridge between the 0.11 and 0.12 support.
Now that we've dropped support for 0.11, we can use filebase64() instead of encoding the userdata in the file ourselves.
> Support terraform 0.12+'s filebase64() in json output

- .shipbot.yaml
- Makefile
kOps releases contain a considerable number of files, out of which only the binaries are currently used for mirrors.
As agreed during Office Hours, images should be bundled into a single archive file.
> Release images bundle instead of separate images

- .shipbot.yaml
- Makefile
Cherry pick of #11522 on release-1.21.
#11522: Release images bundle instead of separate images
> Automated cherry pick of #11522: Release images bundle instead of separate images

- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
In this commit, we update manifest files of CoreDNS. We also do a small
refactoring on yaml blocks to match the upstream source and to make
updating and reviewing procedures easier on the future.
> Bump CoreDNS manifests to latest stable version 1.8.3

- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #11500 on release-1.21.
#11500: Bump patch version
> Automated cherry pick of #11500: Bump patch version

- docs/addons.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #11354 on release-1.20.
#11354: Allow cert-manager to be provisioned externally
> Automated cherry pick of #11354: Allow cert-manager to be provisioned externally

- upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
Cherry pick of #11491 on release-1.21.
#11491: Update CAS manifest
> Automated cherry pick of #11491: Update CAS manifest

- upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
Upstream examples were missing a number of improvements.
This commit also adds template functions for making controllers such as CAS more HA on HA clusters
> Update CAS manifest

- upup/pkg/fi/cloudup/terraform/hcl2.go
- upup/pkg/fi/cloudup/terraform/hcl2_test.go
- upup/pkg/fi/cloudup/terraformWriter/literal.go
- upup/pkg/fi/cloudup/terraformWriter/writer.go
This allows `terraformWriter.LiteralFunctionExpression` to be used with any terraform function.
The arguments must be strings, which means that any string arguments must include quotes. I was debating between this and using a slice of interfaces for `Literal.FnArgs` and passing each to `json.Marshal` to get their string representations (which would quote the strings for us). This would require either returning the `json.Marshal` error up through all of the HCL2 rendering (which doesn't currently return errors) or adding a panic which I'm not excited about.
Feedback welcome.
/hold
> Add support for arbitrary terraform functions

- pkg/model/components/cilium.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #11554 on release-1.21.
#11554: Bump default cilium to 1.9.7
> Automated cherry pick of #11554: Bump default cilium to 1.9.7

- upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
> Allow using insecure TLS for metrics-server with Kubernetes 1.19+

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #11319 #11559 on release-1.20.
#11319: Bump manifest to latest stable
#11559: Allow using insecure TLS for metrics-server with
> Automated cherry pick of #11319: Bump manifest to latest stable #11559: Allow using insecure TLS for metrics-server with

- upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #11559 on release-1.21.
#11559: Allow using insecure TLS for metrics-server with
> Automated cherry pick of #11559: Allow using insecure TLS for metrics-server with

- pkg/apis/kops/validation/aws.go
This is not ideal, but it's an already used behaviour, broken by the improved instance type field validation introduced recently.
Fixes: https://github.com/kubernetes/kops/issues/11513
> Allow Spotinst to use comma separated instance types

- pkg/model/components/BUILD.bazel
- pkg/model/components/awscloudcontrollermanager.go
- upup/pkg/fi/cloudup/populate_cluster_spec.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/aws-cloud-controller.addons.k8s.io-k8s-1.18.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
With this PR, my local setup is down to 13 failures.
> Set flags on AWS CCM mimicking KCM

- upup/pkg/fi/cloudup/awstasks/vpcamazonipv6cidrblock.go
When the VPC isn't yet created, the search for associations was failing
as we were trying to pass an empty ID.
> Avoid error when first creating VPC with IPv6

- docs/release-process.md
> Improve some small issues with the release process

- pkg/resources/aws/aws.go
Refs #8823 
I change the logic for deleting IAM Instance Profiles from name to using ownership tags. This change is using the same logic as #11497 .
After this change, kops avoid deleting IAM Instance Profiles which were managed outside kops when delete cluster.
> Cleanup InstanceProfile only that have ownership tags in delete cluster

- pkg/model/components/awscloudcontrollermanager.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/aws-cloud-controller.addons.k8s.io-k8s-1.18.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
Use the kubernetes.default service for now. Ideally we would not rely on this as this in turn relies on CNI. But fixing this means also fixing PKI, so we have to revisit this later
> Don't set the master address for aws ccm

- dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/awsup/aws_utils.go
- util/pkg/vfs/s3context.go
Remove the annoyance of having to set `AWS_SDK_LOAD_CONFIG=1` when using assumed roles.
> Enable reading shared config when possibly from CLI

- pkg/kubeconfig/kubecfg_builder.go
This preserves existing user configuration.
Issue #11537
> Only update kubeconfig user when we have user info

- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
> Use the OnDelete updateStrategy for AWS VPC CNI DaemonSet

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #11594 on release-1.21.
#11594: Update Calico to v3.19.1
> Automated cherry pick of #11594: Update Calico to v3.19.1

- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Cherry pick of #11590 on release-1.21.
#11590: Use the OnDelete updateStrategy for AWS VPC CNI DaemonSet
> Automated cherry pick of #11590: Use the OnDelete updateStrategy for AWS VPC CNI DaemonSet

- channels/operators/coredns.addons.x-k8s.io/0.1.0-kops.1/manifest.yaml
- channels/src/operators/coredns.addons.x-k8s.io/kustomization.yaml
- channels/src/operators/coredns.addons.x-k8s.io/resources.yaml
- pkg/apis/kops/channel.go
- pkg/featureflag/featureflag.go
- pkg/kubemanifest/manifest.go
- pkg/kubemanifest/visitor.go
- pkg/wellknownoperators/BUILD.bazel
- pkg/wellknownoperators/operators.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/BUILD.bazel
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Hidden behind a feature-flag, but when the UseAddonOperators flag is set,
we now use the cluster-addons CoreDNS operator instead of our built-in
manifests.
> First addon operator integration: CoreDNS

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
Cherry pick of #11602 on release-1.21.
#11602: add init image field
> Automated cherry pick of #11602: add init image field

- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/urls.go
It's unnecessary and it breaks using FileRepository with developer builds.
> Don't stage kops as file assets

- tests/e2e/scenarios/kops-upgrade/run-test.sh
A bit brutish, but I need to have a look at the logs at test failure time to understand why dns-controller is not doing its thing.
/cc @rifelpet @hakman
> Dump all CP node logs to artifacts

- upup/pkg/fi/cloudup/loader.go
Cherry pick of #11619 on release-1.20.
#11619: Fix duplicate CopyFile tasks
> Automated cherry pick of #11619: Fix duplicate CopyFile tasks

- docs/contributing/release-process.md
The `-p` flag isn't very helpful for release commits, since those contain a lot of autogenerated changes.
Presubmit jobs will take care of verifying the release commit builds OK.
Dryrunning an image promotion created by `cip` doesn't appear to serve any purpose.
> Simplify release steps

- docs/contributing/adding_a_feature.md
- pkg/apis/kops/validation/validation.go
- pkg/featureflag/featureflag.go
- pkg/model/iam/iam_builder.go
- pkg/model/iam/iam_builder_test.go
- upup/pkg/fi/cloudup/new_cluster.go
This was feature-flagged in kops 1.19 and announced as scheduled to be completely removed as of kops 1.20.
> Remove fallback support for legacy IAM

- cloudmock/aws/mockautoscaling/warmpool.go
- pkg/model/awsmodel/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/warmpool.go
Cherry pick of #11618 on release-1.21.
#11618: Set lifecycle on WarmPool task
> Automated cherry pick of #11618: Set lifecycle on WarmPool task

- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
This manifest includes two liveness-probe containers but they use different images.
The k8s.gcr.io image is multi-arch but the quay.io image is not.
By only using the k8s.gcr.io one we should fix arm64 clusters now that EBS CSI is enabled by default.
ref: https://testgrid.k8s.io/kops-misc#kops-aws-misc-arm64-ci&show-stale-tests=
https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-misc-arm64-ci/1397862870238105600/artifacts/cluster-info/kube-system/ebs-csi-node-g2wjb/logs.txt
```
==== START logs for container liveness-probe of pod kube-system/ebs-csi-node-g2wjb ====
standard_init_linux.go:219: exec user process caused: exec format error
==== END logs for container liveness-probe of pod kube-system/ebs-csi-node-g2wjb ====
```
> Consolidate CSI livenessprobe images for multi-arch support

- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
Cherry pick of #11652 on release-1.21.
#11652: Consolidate CSI livenessprobe images for multi-arch support
> Automated cherry pick of #11652: Consolidate CSI livenessprobe images for multi-arch support

- tests/e2e/scenarios/aws-ebs-csi/run-test.sh
- tests/e2e/scenarios/aws-lb-controller/run-test.sh
- tests/e2e/scenarios/digital-ocean/run-test
- tests/e2e/scenarios/upgrade-ab/run-test.sh
This improves the consistency of the scenario scripts. My initial intention was to fix [this command failure](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kops-e2e-aws-ebs-csi-driver/1399525045788741632#1:build-log.txt%3A5092) so I'm hoping the `set -x` will help with visibility into whats going wrong.
> Kubetest2 scenario script cleanup

- pkg/model/awsmodel/spotinst.go
- pkg/model/pki.go
I did a quick scan through the codebase using something similar the below to find any other tasks that were missing lifecycles.
```
for task in $(grep -rl HasLifecycle . | grep fitask | xargs basename | sed -e 's/_.*//'); do
grep -r -A 10 --exclude-dir=vendor --exclude="*test.go" -i "${task}{" .
done
```
followup to https://github.com/kubernetes/kops/pull/11650
> Add more lifecycles to HasLifecycle tasks

- pkg/model/issuerdiscovery.go
Cherry pick of #11682 on release-1.21.
#11682: Drop trailing slash from oidc issuer
> Automated cherry pick of #11682: Drop trailing slash from oidc issuer

- .github/workflows/main.yml
- WORKSPACE
Cherry pick of #11686 on release-1.21.
#11686: Update Go to v1.16.5
> Automated cherry pick of #11686: Update Go to v1.16.5

- docs/releases/1.22-NOTES.md
- tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
- upup/pkg/fi/cloudup/new_cluster.go
This should mitigate security concerns around things like e.g enabling lifecycle hooks by default
> Set IMDSv2 on by default for nodes and apiservers

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
Sample config to get started with AWS, Calico and IPv6, using a kOps cluster with public topology:
```yaml
kubeAPIServer:
bindAddress: "::"
nonMasqueradeCIDR: fd00:10:96::/64
serviceClusterIPRange: fd00:10:96::/108
kubeControllerManager:
clusterCIDR: fd00:10:96::/80
allocateNodeCIDRs: false
kubeDNS:
provider: CoreDNS
upstreamNameservers:
- 2620:119:35::35
- 2620:119:53::53
networking:
calico:
ipv4Support: false
ipv6Support: true
subnets:
- type: Public
ipv6CIDR: 2a05:d014:...::/64
```
Ref: #8432 
/cc @justinsb @johngmyers @aojea
> Add options for configuring IPv4 and IPv6 support with Calico

- .gitignore
- Makefile
- hack/set-version
Cherry pick of #11691 on release-1.20.
#11691: Fix set-version leaving backup files with "-e" suffix
> Cherry pick of #11691: Fix set-version leaving backup files with "-e" suffix

- .gitignore
- hack/set-version
Cherry pick of #11691 on release-1.21.
#11691: Fix set-version leaving backup files with "-e" suffix
> Automated cherry pick of #11691: Fix set-version leaving backup files with "-e" suffix

- upup/pkg/fi/assettasks/docker_api.go
When copying image assets, it pulls the image and then looks for it by name. When the name starts with "docker.io/", it doesn't find it because Docker omits that prefix for images in that domain.
/kind bug
> Fix copying of images from docker.io

- docs/releases/1.21-NOTES.md
- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
We copied the bugs fixed upstream by:
* https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/874
* https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/894
> Fix the CSI EBS DS CRB.

- upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.9.yaml.template
Use v1 certificate instead of v1alpha2.
> Use v1 certificate for LB controller

- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
Cherry pick of #11701 on release-1.21.
#11701: Fix the CSI EBS DS CRB.
> Automated cherry pick of #11701: Fix the CSI EBS DS CRB.

- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
https://github.com/cloudnativelabs/kube-router/releases/tag/v1.2.3
> Update kube-router to v1.2.3

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
After 1.19 update calico was also updated and source-destination check was included in calico natively. So when you're using proxy and cluster created it can't be validated without manual patch:
```
kubectl set env daemonset/calico-node -n kube-system http_proxy=http://<proxy_url>:<proxy_port>
kubectl set env daemonset/calico-node -n kube-system https_proxy=http://<proxy_url>:<proxy_port>
kubectl set env daemonset/calico-node -n kube-system no_proxy=<no_proxy_list>
```
Signed-off-by: Dmytro Oboznyi <dmytro.oboznyi@syncier.com>
> Add proxy envs to calico to make possible usage of AWS source destination check

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
Cherry pick of #11709 on release-1.21.
#11709: Add proxy envs to calico to make possible usage of AWS source
> Automated cherry pick of #11709: Add proxy envs to calico to make possible usage of AWS source

- pkg/model/components/awsebscsidriver.go
- tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-a-ha-gce-example-com_metadata_startup-script
- tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-b-ha-gce-example-com_metadata_startup-script
- tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-c-ha-gce-example-com_metadata_startup-script
- tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_nodes-ha-gce-example-com_metadata_startup-script
- tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
- tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
- tests/integration/update_cluster/minimal_gce_private/data/google_compute_instance_template_master-us-test1-a-minimal-gce-private-example-com_metadata_startup-script
- tests/integration/update_cluster/minimal_gce_private/data/google_compute_instance_template_nodes-minimal-gce-private-example-com_metadata_startup-script
Cherry pick of #11716 on release-1.21.
#11716: Generate AWSEBSCSIDriver model only when using AWS
> Automated cherry pick of #11716: Generate AWSEBSCSIDriver model only when using AWS

- nodeup/pkg/model/networking/cilium.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
a) again I got a request for this over docker rate limiting
b) Since with containerd, docker credentials are not valid for image pulls outside of kubelet, docker.io images will hit rate limiting
c) upstream use quay by default
cilium with hubble already has a dependency on cert-manager, which is hosted on quay so quay is to some extent a dependency anyway.
> Use quay images for cilium

- nodeup/pkg/model/networking/cilium.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #11722 on release-1.21.
#11722: Use quay images for cilium
> Automated cherry pick of #11722: Use quay images for cilium

- docs/contributing/release-process.md
ref: https://github.com/kubernetes/test-infra/pull/22505
> Update release branch docs with kubetest2 presubmit job

- pkg/apis/kops/validation/validation.go
- pkg/model/awsmodel/spotinst.go
- upup/pkg/fi/cloudup/spotinsttasks/BUILD.bazel
- upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
This PR complements #9011 by adding support for API Load Balancer with AWS/NLB for the Spotinst provider.
> Spotinst: Support for API Load Balancer with AWS/NLB

- go.mod
- go.sum
- pkg/apis/kops/validation/validation.go
- pkg/model/awsmodel/network.go
- pkg/model/names.go
- tests/e2e/go.sum
- upup/pkg/fi/cloudup/awstasks/subnet.go
- upup/pkg/fi/cloudup/awstasks/subnet_test.go
- upup/pkg/fi/cloudup/awstasks/vpcamazonipv6cidrblock.go
- upup/pkg/fi/utils/BUILD.bazel
- upup/pkg/fi/utils/cidr.go
- vendor/github.com/apparentlymart/go-cidr/LICENSE
- vendor/github.com/apparentlymart/go-cidr/cidr/BUILD.bazel
- vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
- vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
- vendor/modules.txt
Ref: https://github.com/kubernetes/kops/issues/8432#issuecomment-843777374
Inspired by https://github.com/kubernetes/kops/pull/11163.
This PR makes it possible to set subnet CIDR based on VPC CIDR on cluster creation similarly to:
* https://www.terraform.io/docs/language/functions/cidrsubnet.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-cidr.html
There is some feedback from @johngmyers in https://github.com/kubernetes/kops/pull/11442#discussion_r631712081, which suggests using a `cidrsubnet(8,1)` syntax instead of a `cidrsubnet-8-1` syntax for configuring a subnet.
The reason I chose the `cidrsubnet-8-1` is to maybe allow using this as a flag on create cluster and that it seems similar to other places, like …
> Calculate IPv6 subnet CIDR based on cluster CIDR

- nodeup/pkg/model/awsebscsidriver.go
Pulling the Deployment images serves no purpose as they tend not to run on normal nodes
> Only warm-pull images used by the CSI DS

- docs/operations/etcd_backup_restore_encryption.md
We just did such a backup restore and ended up with Pods in Pending state without any events or errors indicating what may be wrong. Also had issues with EndpointSlices. Rolling the cluster solved all these issues.
> Add small note about rotating cluster after backup restore

- upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
This fixes https://github.com/kubernetes/kops/issues/11742 which discusses the broken rendering of the Corefile of the NodeLocal DNSCache template when setting forwardToKubeDNS to false (or not setting it).
Previously, due to not dereferencing the bool pointer, the Corefile was always rendered with the true clause, due to checking the address instead of the actual value of the variable.
With this fix, the templating mechanism will actually respect the value of forwardToKubeDNS and render it accordingly.
> Make forwardToKubeDNS work in the NodeLocal DNSCache template

- docs/operations/cluster_template.md
Adds link on documentation site. GitHub will auto-link but the site doesn't.
> Hyperlink Sprig reference

- upup/pkg/fi/cloudup/openstacktasks/port.go
- upup/pkg/fi/cloudup/openstacktasks/securitygroup.go
This fixes #11740 by sorting the security groups of the port model and when querying the cloud, which will result in tasks comparing those slices deterministically.
> Compare OpenStack security groups deterministically

- pkg/model/awsmodel/network.go
> Don't set Subnet dependency on AmazonIPv6CIDR for shared VPCs

- cmd/kops/create_cluster.go
- cmd/kops/create_cluster_integration_test.go
- pkg/featureflag/featureflag.go
- tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
- tests/integration/create_cluster/ipv6/options.yaml
- upup/pkg/fi/cloudup/new_cluster.go
/hold for #11523
/cc @johngmyers @justinsb
> Add --ipv6 experimental cli flag

- docs/networking/cilium.md
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/commands/set_cluster_test.go
- pkg/model/components/cilium.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
It doesn't make much sense to default to a non-working configuration.
/cc @olemarkus
> Cilium: disable masquerade by default when in ENI IPAM mode

- pkg/model/components/kubecontrollermanager.go
- upup/pkg/fi/cloudup/populate_cluster_spec.go
/kind bug
The AWS CCM and some GCE code pulls directly from `spec.podCIDR` instead of from `spec.kubeControllerManager.clusterCIDR`.
> Set default ClusterCIDR through the PodCIDR

- pkg/apis/kops/validation/validation.go
- pkg/model/context.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
/cc @olemarkus @hakman 
Needs `--override=spec.kubeControllerManager.nodeCIDRMaskSize=80`. Will send that as a separate PR as it isn't specific to Cilium.
> Enable IPv6 support for Cilium

- cmd/kops/create_cluster.go
- tests/integration/create_cluster/overrides/options.yaml
- util/pkg/reflectutils/access.go
- util/pkg/reflectutils/access_test.go
* Rename `--override` to `--set`, leaving backwards compatibility to allow a transition period for our e2e jobs.
* Append to slices instead of replacing them. Replacement can be done by combining an unset with a set.
> Adjustments to SpecOverride

- cmd/kops/create_cluster.go
- docs/cli/kops_create_cluster.md
- tests/integration/create_cluster/complex/expected-v1alpha2.yaml
- tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
- tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.17/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
- tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
- tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
- upup/pkg/fi/cloudup/new_cluster.go
The previous behavior did not match the documentation.
> Make the AdminAccess default inclusive of IPv6

- upup/pkg/fi/cloudup/populate_instancegroup_spec.go
APIServrNodes -> APIServerNodes
> Fix typo in populate_instancegroup_spec.go

- upup/models/cloudup/resources/addons/storage-aws.addons.k8s.io/v1.15.0.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/service-account-iam/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Looks like we are not installing a default StorageClass if AWS EBS CSI driver is disabled.
@justinsb @johngmyers another one that probably should go into 1.21.
/kind bug
> fix enable default SC when EBS driver is not installed

- tests/e2e/scenarios/aws-ebs-csi/run-test.sh
- tests/e2e/scenarios/aws-lb-controller/run-test.sh
- tests/e2e/scenarios/lib/common.sh
This allows us to run `KOPS_IRSA=true tests/e2e/scenarios/lib/common.sh` for an IRSA version of the given scenario (only lbc scenario ported to this right now as it is the only one supporting IRSA).
> Make it easy to run scenarios with irsa enabled

- upup/models/cloudup/resources/addons/storage-aws.addons.k8s.io/v1.15.0.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/service-account-iam/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #11771 on release-1.21.
#11771: fix enable default SC when EBS driver is not installed
> Automated cherry pick of #11771: fix enable default SC when EBS driver is not installed

- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Between kOps 1.19 and 1.20, the version went from 1.19.1 to 1.19.0, which prevents any further changes from being applied to the cluster. Bumping to 1.19.2 so that channels can apply again.
fixes #11759
> Bump the cas addon version.

- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #11780 on release-1.21.
#11780: Bump the cas addon version.
> Automated cherry pick of #11780: Bump the cas addon version.

- pkg/kubeconfig/kubecfg_builder.go
Without setting it to true, --user is completely ignored.
> Also set haveUserInfo=true in case --user was provided in "kops export kubecfg"

- nodeup/pkg/model/etcd_manager_tls.go
- nodeup/pkg/model/networking/BUILD.bazel
- nodeup/pkg/model/networking/cilium_test.go
- pkg/model/components/etcdmanager/model.go
Ciliium etcd mode is broken at the moment as both etcd TLS builder and cilium builder tries to create certificates. As the logic for cilium certs is slightly different, I am keeping the older logic and skipping cilium in the etcd TLS builder.
/kind bug
@johngmyers @justinsb it may be that you want to cherry-pick this one before the 1.21.0 release.
> Don't try to build etcd-manager secrets for cilium twice

- nodeup/pkg/model/etcd_manager_tls.go
- nodeup/pkg/model/networking/BUILD.bazel
- nodeup/pkg/model/networking/cilium_test.go
- pkg/model/components/etcdmanager/model.go
Cherry pick of #11764 on release-1.21.
#11764: Don't try to build etcd-manager secrets for cilium twice
> Automated cherry pick of #11764: Don't try to build etcd-manager secrets for cilium twice

- channels/alpha
* https://github.com/kubernetes/kubernetes/releases/tag/v1.21.2
* https://github.com/kubernetes/kubernetes/releases/tag/v1.20.8
* https://github.com/kubernetes/kubernetes/releases/tag/v1.19.12
* https://github.com/kubernetes/kubernetes/releases/tag/v1.18.20
[Ubuntu EC2 Locator](https://cloud-images.ubuntu.com/locator/ec2/) shows that `20210503` is the latest available in Gov Cloud, so I went with this one to maintain the highest level of availability across every possible AWS region.
> Update alpha channel k8s versions and ec2 ami base image

- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
[Release page](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.8.0)
> Upgrade AWS CNI to latest release 1.8.0

- go.mod
- go.sum
- tests/e2e/go.sum
- vendor/github.com/gophercloud/gophercloud/.zuul.yaml
- vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
- vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/results.go
- vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/results.go
- vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/results.go
- vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go
- vendor/github.com/gophercloud/gophercloud/provider_client.go
- vendor/modules.txt
Since the v1.19.0 release of kOps the OpenStack integration has been
broken because gophercloud made a change to start escaping all path
names for files stored in swift. kOps used a file with a slash in it
which was getting escaped and then not handled correctly. This has been
fixed in upstream gophercloud with gophercloud/gophercloud#2160 which
was included in gophercloud v0.18.0. Bump to that version to fix #9933.
> bump the version of gophercloud

- pkg/kubeconfig/kubecfg_builder.go
Cherry pick of #11778 on release-1.21.
#11778: Also set haveUserInfo=true in case --user was provided in
> Automated cherry pick of #11778: Also set haveUserInfo=true in case --user was provided in

- docs/contributing/homebrew.md
- `brew switch` removed in Homebrew/brew#10397 PR
- Also update the version bump command
> doc: remove `brew switch` ref and simplify version bump

- pkg/apis/kops/validation/aws.go
- pkg/apis/kops/validation/aws_test.go
- pkg/apis/kops/validation/validation.go
As of k8s 1.22, EBS driver is always installed. This PR makes validation pass when not explicitly enabling EBS CSI Driver.
> Fix validating presence of AWS EBS CSI

- pkg/featureflag/featureflag.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
This is not just about AWS, the OpenStack one for example is stable.
It means that someone should still enable the feature via `spec.cloudControllerManager.cloudProvider`, but no longer need to set the feature flag too.
> Set EnableExternalCloudController to true by default

- tests/e2e/scenarios/upgrade-ab/run-test.sh
These are already being skipped in [certain k8s versions](https://github.com/kubernetes/test-infra/blob/d604f0848c09e03794622948a7e4e809cc5955c7/config/jobs/kubernetes/kops/build_jobs.py#L303-L311). Until we can dynamically determine which tests to skip based on k8s version (like build_jobs.py generates) within these scenario scripts, we can just skip these two tests for all k8s versions.
Should get these 3 upgrade jobs to pass:
* https://testgrid.k8s.io/kops-misc#kops-aws-upgrade&show-stale-tests=
* https://testgrid.k8s.io/kops-misc#kops-aws-upgrade-k120-ko120-to-k121-ko121&show-stale-tests=
* https://testgrid.k8s.io/kops-misc#kops-aws-upgrade-k121-ko121-to-klatest-kolatest&show-stale-tests=
> Ignore failing tests in upgrade scenario

- upup/models/cloudup/resources/addons/aws-cloud-controller.addons.k8s.io/k8s-1.18.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/aws-cloud-controller.addons.k8s.io-k8s-1.18.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
External cloud provider will add a taint `node.cloudprovider.kubernetes.io/uninitialized` with an effect NoSchedule during initialization. This effectively blocks cluster initialization until the cloud controller manager is ready, so it should have higher priority.
As an important side-effect of adding priority class,  kOps validation will track status of AWS CCM pods.
> Set priority class for AWS CCM addon

- tests/e2e/pkg/tester/skip_regex.go
- tests/e2e/pkg/tester/tester.go
This will move the logic from [build_jobs.py](https://github.com/kubernetes/test-infra/blob/e4a29d493d9fa28a4ce506abd544c60375879a2b/config/jobs/kubernetes/kops/build_jobs.py#L284-L312) into kubetest2 itself.
This way we can rely on this logic from scenario scripts and other places that aren't directly set by build_jobs.py.
ref: https://kubernetes.slack.com/archives/C8MKE2G5P/p1624366418361000
> Kubetest2 - Add --skip-regex logic

- docs/getting_started/azure.md
Explicitly mention that a cluster needs to build with Gossip DNS.
Closes: https://github.com/kubernetes/kops/issues/11794
> Clarify the limitations of Azure DNS support

- nodeup/pkg/model/kube_controller_manager.go
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-controller-manager.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-amd64.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-arm64.yaml
Use the new `BuildCertificatePairTask` to get the cluster CA keypair.
Move secrets and mounts around to deny KCM access to api-server's secrets. A future PR will deny api-server access to KCM's secrets.
> Refactor kube-controller-manager secrets

- tests/e2e/pkg/tester/skip_regex.go
jobs using this logic are now skipping all tests: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-cni-amazon-vpc/1407658529614991360
compared to an older job: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-cni-amazon-vpc/1407417059549122560
```diff
- --ginkgo.skip=[Slow]|[Serial]|[Disruptive]|[Flaky]|[Feature:.+]|[HPA]|[Driver:.nfs]|Dashboard|RuntimeClass|RuntimeHandler|Invalid.AWS.KMS.key
+ --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|\[Driver:.nfs\]|Dashboard|RuntimeClass|RuntimeHandler|Services.*functioning.*NodePort|Invalid.AWS.KMS.key
```
> Escape --skip-regex pattern

- pkg/model/awsmodel/oidc_provider.go
- pkg/pki/certificate_test.go
- pkg/pki/csr.go
- pkg/pki/privatekey.go
- upup/pkg/fi/nodeup/nodetasks/bootstrap_client.go
The change of `pki.PrivateKey` to containing a `crypto.Signer` contemplates a future in which we might be able to store keys in HSMs.
> Weaken some interfaces

- nodeup/pkg/model/BUILD.bazel
- nodeup/pkg/model/convenience.go
- nodeup/pkg/model/hooks.go
- nodeup/pkg/model/hooks_test.go
- nodeup/pkg/model/tests/golden/hooks-containerd-exec/cluster.yaml
- nodeup/pkg/model/tests/golden/hooks-containerd-exec/tasks-hooks.yaml
- nodeup/pkg/model/tests/golden/hooks-docker-exec/cluster.yaml
- nodeup/pkg/model/tests/golden/hooks-docker-exec/tasks-hooks.yaml
> Handle containerExec hooks when using containerd

- nodeup/pkg/model/BUILD.bazel
- nodeup/pkg/model/convenience.go
- nodeup/pkg/model/hooks.go
- nodeup/pkg/model/hooks_test.go
- nodeup/pkg/model/tests/golden/hooks-containerd-exec/cluster.yaml
- nodeup/pkg/model/tests/golden/hooks-containerd-exec/tasks-hooks.yaml
- nodeup/pkg/model/tests/golden/hooks-docker-exec/cluster.yaml
- nodeup/pkg/model/tests/golden/hooks-docker-exec/tasks-hooks.yaml
Cherry pick of #11852 on release-1.21.
#11852: Handle containerExec hooks when using containerd
> Automated cherry pick of #11852: Handle containerExec hooks when using containerd

- docs/networking/calico.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/calico.go
- pkg/model/iam/iam_builder.go
- tests/integration/update_cluster/privatecalico/cloudformation.json
- tests/integration/update_cluster/privatecalico/data/aws_iam_role_policy_masters.privatecalico.example.com_policy
- tests/integration/update_cluster/privatecalico/data/aws_iam_role_policy_nodes.privatecalico.example.com_policy
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
Most kOps setup have at least 2 subnets so, the optimal setup is to:
1. disable AWS src/dest checks
2. set encapsulation mode to `CrossSubnet` (other possible options are `Always` and `None`)
/cc @johngmyers @olemarkus
> Enable cross-subnet mode with Calico by default

- upup/pkg/fi/fitasks/keypair.go
/kind bug
A `kops create cluster` without a `--yes` fails with:
```
I0624 22:12:15.919463    4954 executor.go:111] Tasks: 0 done / 95 total; 43 can run
W0624 22:12:16.432849    4954 vfs_castore.go:469] CA private key was not found
I0624 22:12:17.328871    4954 executor.go:111] Tasks: 43 done / 95 total; 19 can run
W0624 22:12:18.036237    4954 executor.go:139] error running task "BootstrapScript/nodes-us-east-1b" (9m59s remaining to succeed): failed to read CA certificates: error opening resource: resource opened before it is ready (task=*fitasks.Keypair {"Name":"ca","alternateNames":null,"Lifecycle":"Sync","Signer":null,"subject":"cn=kubernetes","type":"ca","oldFormat":false})
W0624 22:12:18.036652    4954 executor.go:139] error running task "BootstrapScript/nodes-us-east-1a" (9m59s …
```
> Fix dryrun cluster creation

- docs/contributing/update_ami_versions.md
When updating the AMI version on `stable` channel, there's an additional step required, which is running `hack/update-expected.sh` to prevent the tests from failing.
Figured it's worth adding a note about it in the docs.
> Add a note about running update-expected when updating base AMI

- cloudmock/aws/mockelbv2/loadbalancers.go
- pkg/apis/kops/validation/validation.go
- pkg/model/awsmodel/api_loadbalancer.go
- pkg/model/awsmodel/autoscalinggroup.go
- pkg/model/awsmodel/bastion.go
- pkg/model/awsmodel/dns.go
- pkg/model/context.go
- pkg/resources/aws/aws.go
- tests/integration/update_cluster/minimal-ipv6/cloudformation.json
- tests/integration/update_cluster/minimal-ipv6/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/dnsname.go
- upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
> Use DualStack API NLB for IPv6

- cmd/kops-controller/pkg/server/node_config.go
- pkg/apis/nodeup/bootstrap.go
- pkg/configserver/keystore.go
- upup/pkg/fi/nodeup/command.go
Configserver clients already have the "ca" trust bundle as they need it to talk to configserver in the first place.
/kind cleanup
> Simplify config server protocol

- cmd/kops/integration_test.go
- nodeup/pkg/model/context.go
- nodeup/pkg/model/kops_controller.go
- nodeup/pkg/model/kube_controller_manager.go
- nodeup/pkg/model/networking/BUILD.bazel
- nodeup/pkg/model/networking/cilium.go
- nodeup/pkg/model/networking/cilium_test.go
- pkg/model/awsmodel/autoscalinggroup_test.go
- pkg/model/azuremodel/vmscaleset_test.go
- pkg/model/bootstrapscript.go
- pkg/model/bootstrapscript_test.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/iam/iam_builder.go
- pkg/model/openstackmodel/servergroup_test.go
- tests/integration/update_cluster/privateciliumadvanced/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/privateciliumadvanced/data/aws_launch_template_master-us-test-1a.masters.privateciliumadvanced.example.com_user_data
- tests/integration/update_cluster/privateciliumadvanced/data/aws_launch_template_nodes.privateciliumadvanced.example.com_user_data
- upup/pkg/fi/cloudup/apply_cluster.go
For non-kops-controller-bootstrap worker nodes, gives them a prebaked client cert/key instead of the private key of the CA.
> Refactor etcd-client-cilium secrets

- tests/e2e/pkg/tester/skip_regex.go
- tests/e2e/pkg/tester/tester.go
https://github.com/kubernetes/kubernetes/pull/93000 skips the test we are skipping via regex, if the --node-os-arch flag is not set to amd64. kubetest2-tester-kops will now set --node-os-arch so that the test context itself will skip the test rather than relying on --skip-regex.
> Kubetest2 - set node-os-arch flag instead of skipping kubectl test on arm64

- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
This PR upgrades `spotinst/ocean-controller` to v1.0.76.
> Spotinst: Update `spotinst/ocean-controller` to v1.0.76

- upup/pkg/fi/http.go
current download code was using http.client timeout, that will
interrupt reading of the response body, breaking slow downloads
or very large files.
This patch modified the http client to detect idle downloads, and
fail after 30 seconds of innactivity. It still keeps a global
timeout of 5 minutes.
> support large/slow downloads

- upup/pkg/fi/http.go
Cherry pick of #11884 #11886 on release-1.21.
#11884: support large/slow downloads
#11886: Set download timeout to 3 minutes
> Automated cherry pick of #11884: support large/slow downloads #11886: Set download timeout to 3 minutes

- tests/integration/update_cluster/ha_gce/kubernetes.tf
- tests/integration/update_cluster/minimal_gce/kubernetes.tf
- tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
- upup/pkg/fi/cloudup/terraform/target_hcl2.go
Cherry pick of #11901 on release-1.21.
#11901: Include GCP Project in terraform HCL2 output
> Automated cherry pick of #11901: Include GCP Project in terraform HCL2 output

- tests/e2e/scenarios/lib/common.sh
We already do this in kubetest2-kops:
https://github.com/kubernetes/kops/blob/cf834ce5fc7d65ecf53b56937d35c1e200600f03/tests/e2e/kubetest2-kops/deployer/common.go#L192
This sets it in scenario scripts so that any `kops` commands behave identically.
fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-upgrade-k121-ko121-to-klatest-ko121/1411481827041873920
> Set KOPS_RUN_TOO_NEW_VERSION in scenario scripts

- pkg/model/iam/iam_builder.go
> Allow fsstore to be used for mock s3 rules

- cmd/kops/validate_cluster.go
Cherry pick of #11049 on release-1.20.
#11049: cluster validation - allow flapping of validation errors
Fixes #11920
> Automated cherry pick of #11049: cluster validation - allow flapping of validation errors

- channels/pkg/cmd/apply_channel.go
If a single addon fails, channels will just give up on the rest. This PR makes channels just print an error when an addon fails and continue with the next one.
Skipping on first addon failure is especially problematic with addons depending on cert-manager. These will always fail due to the missing CRDs and if these are executed before cert-manager, channels will exit and we have to hope cert-manager is executed earlier in the next iteration.
> Continue if a single addon fails to be applied

- tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
- upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
This PR allows the cert-manager webhook to run on CP nodes so that certificate resources within addons can be applied before worker nodes have joined the cluster.
> Schedule certmanager webhook on control plane

- upup/pkg/fi/cloudup/dotasks/droplet.go
Per [DO Documetation here](https://docs.digitalocean.com/reference/api/api-reference/#operation/create_droplet) PrivateNetworking option is deprecated and will be eventually replaced by `vpc_uuid`. 
If `private_networking` is not specified, the droplets will be assigned to the account's default VPC, which is the default behavior.
PR to include support for `--vpc` flag will follow soon.
FYI - @timoreimann
> [Digital Ocean] Remove PrivateNetworking option in droplet since it's deprecated

- tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
- upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
Looks like that for #11934 to work, we also need to move ca-injector. It is a dependency of the webhook.
> Run cert-manager cainjector on CP nodes as well

- upup/models/cloudup/resources/addons/aws-cloud-controller.addons.k8s.io/k8s-1.18.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/aws-cloud-controller.addons.k8s.io-k8s-1.18.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
* CCM is crashing on startup because it cannot talk to k8s api using the default k8s service address
* When CCM crashes, we download image again, which takes a long time (some rate limit at play here?)
* Prefix the CCM SA to avoid conflicts (kOps IRSA assumes unique SAs across all addons)
> Fix various CCM issues

- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- k8s/crds/kops.k8s.io_instancegroups.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
Decided to use the same name as in [Kubelet config](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/types.go#L260-L261)
This will allow user to configure the PID limit per pod.
> Add podPidsLimit / --pod-max-pids support

- nodeup/pkg/model/logrotate.go
- pkg/dump/dumper.go
Cherry pick of #11943 on release-1.21.
#11943: Add log rotation for etcd-cilium.log
> Automated cherry pick of #11943: Add log rotation for etcd-cilium.log

- upup/pkg/fi/cloudup/new_cluster.go
Minor fix to remove nonsensical error message.
FYI - @timoreimann @johngmyers 
This is as per issue - https://github.com/kubernetes/kops/issues/11931
> [Digital Ocean] Modify error message when multiple zones are specified

- docs/state.md
Needs a line break or it combines bullet points with the previous paragraph.
Current page at https://kops.sigs.k8s.io/state/looks like this
> Fix bullet point rendering in state doc

- upup/pkg/fi/nodeup/command.go
Nodeup crash when an instance is not created by an AWS Auto-Scaling Group.
Check if the instance is under an ASG before trying to get the lifeCycle value from the ASG.
Related bug: https://github.com/kubernetes/kops/issues/11949
> check if the instance is under an asg

- upup/pkg/fi/nodeup/command.go
Cherry pick of #11958 on release-1.21.
#11958: check if the instance is under an asg
> Automated cherry pick of #11958: check if the instance is under an asg

- tests/e2e/pkg/tester/skip_regex.go
Fixes for these tests have now been released in all applicable k8s version markers
* Invalid KMS Key: https://github.com/kubernetes/kubernetes/pull/101956
GH doesn't mention it on the commit but v1.21.2 includes the commit [here](https://github.com/kubernetes/kubernetes/blob/v1.21.2/test/e2e/storage/volume_provisioning.go#L828). Theoretically this would fail if someone specified k8s v1.21.0 or v1.21.1 but typically we only test with the latest patch version.
* Volume Limits: https://github.com/kubernetes/kubernetes/pull/103074
GH shows it as released in v1.22.0-beta.1: https://github.com/kubernetes/kubernetes/commit/164ce31e7fbe04a4a7509cf7aff62c10c5229583
> Unconditionally reenable KMS and Volume Limit tests

- docs/networking/cilium.md
- tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-bootstrap_content
- tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
- upup/pkg/fi/cloudup/new_cluster.go
First commit fixes an issue where the status object of the CNP becomes too large to write to etcd. Also enables "scalability"
Second fixes #10663
> Cilium etcd fixes

- docs/networking/cilium.md
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
- upup/pkg/fi/cloudup/new_cluster.go
Cherry pick of #11961 on release-1.21.
#11961: Enable k8s event handover when kvstore is used
> Automated cherry pick of #11961: Enable k8s event handover when kvstore is used

- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
This PR upgrades `spotinst/ocean-controller` to v1.0.77.
> Spotinst: Update `spotinst/ocean-controller` to v1.0.77

- README.md
Related to [this](https://github.com/kubernetes/kops/issues/11959#issuecomment-876950002) comment on #11959 
The link to `contributing` page is broken in the main `README.md` file. This PR fixes the broken link
> Fix broken link to contributing

- docs/addons.md
> Add missing IAM permissions to the NTH docs

- hack/upload
This is intended to fix https://testgrid.k8s.io/kops-presubmits#kops-postsubmit which has been failing since https://github.com/kubernetes/test-infra/pull/22840 merged
It's not clear to me whether this will need to be backported into other release branches or not
> hack/upload: avoid ACLs for GCS buckets with UBLA enabled

- pkg/model/azuremodel/vmscaleset.go
- upup/pkg/fi/cloudup/azure/azure_utils.go
- upup/pkg/fi/cloudup/azure/azure_utils_test.go
- upup/pkg/fi/cloudup/azuretasks/vmscaleset.go
- upup/pkg/fi/cloudup/azuretasks/vmscaleset_test.go
Azure's subnets are regional so we use similar functionality to GCE where we reference the InstanceGroup's zones rather than a subnet's zone.
IG Zones are already populated from `--zones` and `--master-zones` at cluster creation time here:
https://github.com/kubernetes/kops/blob/b35803789627345f58eb979cf53fa87bfe422f28/upup/pkg/fi/cloudup/new_cluster.go#L682-L684
fixes #11955
> Azure - support VMSS availability zones

- pkg/apis/kops/util/versions_test.go
- tests/e2e/pkg/version/kubernetes.go
this is mostly about getting kubernetes/kops out of search results for a
cs.k8s.io query that's looking for all repos that reference
kubernetes-release-dev in their default branch
if there's no compelling reason to keep the old value, use
k8s-release-dev instead
ref: https://github.com/kubernetes/k8s.io/issues/2318
> remove references to kubernetes-release-dev

- docs/operations/rotate-secrets.md
- nodeup/pkg/model/context.go
- nodeup/pkg/model/networking/kube_router.go
- upup/pkg/fi/cloudup/apply_cluster.go
And with this, the keypair rotation feature is complete.
I don't have any test infrastructure on cloud providers that don't use kops-controller for bootstrap, so this is untested.
Closes #8774
> Use keypair IDs for non-kops-controller-issued worker node certs

- channels/alpha
* https://github.com/kubernetes/kubernetes/releases/tag/v1.19.13
* https://github.com/kubernetes/kubernetes/releases/tag/v1.20.9
* https://github.com/kubernetes/kubernetes/releases/tag/v1.21.3
The newest globally available [Ubuntu AMI release on EC2](https://cloud-images.ubuntu.com/locator/ec2/) for `focal` is `20210518` (the stragglers are `cn-north` and `cn-northwest`. Thus, I went with that one for now.
> Update alpha channel with July k8s releases and bump Ubuntu EC2 AMI version

- tests/e2e/scenarios/keypair-rotation/run-test.sh
I copied the commands out of https://kops.sigs.k8s.io/operations/rotate-secrets/
/cc @johngmyers
> Add keypair rotation test scenario

- nodeup/pkg/model/kubelet.go
Fixes OpenStack and other non-kops-controller-bootstrap providers with k8s < 1.19.
> Issue kubelet cert on apiserver nodes for k8s before 1.19

- tests/e2e/scenarios/keypair-rotation/run-test.sh
fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-keypair-rotation
this shell function assigns a value to KOPS, rather than echoing to stdout like some of the other functions:
https://github.com/kubernetes/kops/blob/4048d0caf19c09419b34d35a8850a1cf7ac86eae/tests/e2e/scenarios/lib/common.sh#L104
> Fix keypair rotation scenario kops binary

- tests/e2e/scenarios/keypair-rotation/run-test.sh
Fixes https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-keypair-rotation/1416714756152102912/build-log.txt
```
./tests/e2e/scenarios/keypair-rotation/run-test.sh: line 32: /logs/artifacts/keypair-rotation//create.kubeconfig: No such file or directory
```
> Keypair rotation scenario - create report directory

- upup/pkg/fi/cloudup/azure/azure_cloud.go
- upup/pkg/fi/cloudup/azuretasks/testing.go
- upup/pkg/fi/cloudup/defaults.go
This allows the `create cluster --vpc` flag to specify the vnet ID for using shared vnets.
This makes an assumption that the cluster will use the first address prefix in the vnet. If that's not the case, the user should specify the address prefix with `--network-cidr`.
This is mostly untested, I may get a chance to at least confirm API behavior sometime this week.
Fixes #11950
/cc @kenji-cloudnatix
> Add azure support for specifying a shared vpc

- tests/e2e/scenarios/keypair-rotation/run-test.sh
fixes https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-keypair-rotation/1416956350969155584/build-log.txt
```
+ kubectl --kubeconfig=/tmp/kubeconfig.W8ihK1JYy config view
++ kubectl --kubeconfig=/tmp/kubeconfig.W8ihK1JYy config view --raw -o 'jsonpath={.clusters[0].cluster.certificate-authority-data}'
++ base64 -D
base64: invalid option -- 'D'
```
> keypair rotation scenario - fix base64 decoding

- cmd/kops/create_cluster.go
- cmd/kops/update_cluster.go
- upup/pkg/fi/cloudup/apply_cluster.go
ref: #11951
How I determined the list of supported providers:
```
$ grep -rl RenderTerraform upup/pkg/fi/cloudup  | xargs -L1 dirname | uniq -c
3 upup/pkg/fi/cloudup/spotinsttasks
13 upup/pkg/fi/cloudup/gcetasks
36 upup/pkg/fi/cloudup/awstasks
16 upup/pkg/fi/cloudup/alitasks
1 upup/pkg/fi/cloudup/dotasks
```
> Return a clearer error when terraform is used on an unsupported provider

- tests/e2e/scenarios/keypair-rotation/run-test.sh
- tests/e2e/scenarios/lib/common.sh
The keypair rotation test is failing because there are two CAs where we expected 1: https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-keypair-rotation/1417258356002787328/build-log.txt 
After reviewing the steps, I think it _should_ have 2 CAs at that point, and then one CA after the distrust command. This updates the scenario to reflect that.
> Assert the correct number of kubeconfig CAs during keypair rotation

- tests/e2e/scenarios/keypair-rotation/run-test.sh
The test is now failing during the third `rolling-update` (after `distrust`) with unauthorized errors:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-keypair-rotation/1417620742954029056
`I0721 00:38:31.819943    4501 instancegroups.go:513] Cluster did not validate within deadline: error listing nodes: Unauthorized.`
Rereading [the docs](https://kops.sigs.k8s.io/operations/rotate-secrets/#export-and-distribute-new-kubeconfig-admin-credentials), it seems like we _do_ need to export new credentials after promoting the new CA and before distrusting the old CA, that way the credentials will be signed from the new CA.
followup to https://github.com/kubernetes/kops/pull/12029
> keypair rotation - export new credentials between promote and distruts

- docs/releases/1.22-NOTES.md
- k8s/crds/kops.k8s.io_clusters.yaml
- nodeup/pkg/model/kube_controller_manager.go
- nodeup/pkg/model/kube_scheduler.go
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-controller-manager.yaml
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-scheduler.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-amd64.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-arm64.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-scheduler-amd64.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-scheduler-arm64.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
Fixes #12016 
I put in an escape hatch: setting `tlsCertFile: ""` in the respective componentconfig will revert to the previous behavior of using a self-signed cert.
> Provision TLS server certs for controller-manager and scheduler

- upup/pkg/fi/cloudup/awsup/aws_authenticator.go
- upup/pkg/fi/cloudup/awsup/aws_verifier.go
> Use regional STS endpoint

- upup/pkg/fi/cloudup/awsup/aws_authenticator.go
- upup/pkg/fi/cloudup/awsup/aws_verifier.go
Cherry pick of #12043 on release-1.21.
#12043: Use regional STS endpoint
> Automated cherry pick of #12043: Use regional STS endpoint

- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.9.0
To stay aligned with our documentation of ENVs that ship with the original manifest which we vendor from, I've added both newly-introduced ENVs with their original values, and commented-them out so that they will pick up the default values.
> Update AWS CNI to v1.9.0

- docs/boot-sequence.md
- docs/contributing/adding_a_feature.md
- docs/security_groups.md
- docs/terraform.md
- k8s/crds/kops.k8s.io_instancegroups.yaml
- pkg/apis/kops/instancegroup.go
- pkg/apis/kops/v1alpha2/instancegroup.go
- pkg/model/awsmodel/autoscalinggroup_test.go
The note in the API documentation is incorrect, the field _is_ used in LaunchTemplates:
https://github.com/kubernetes/kops/blob/a0a6e3c9741df4d647018aa7072be5f2e2640bd2/pkg/model/awsmodel/autoscalinggroup.go#L250-L253
> Cleanup various references to LaunchConfigurations

- cmd/kops/get_cluster.go
Restoring the behaviour of `kops get cluster`, where it lists clusters
even if one is configured in kubeconfig.
> Fix cluster list action

- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #12062 on release-1.21.
#12062: Update core-dns to v1.8.4
> Automated cherry pick of #12062: Update core-dns to v1.8.4

- upup/pkg/fi/cloudup/gcetasks/targetpool.go
It's an internal field, it shouldn't be detected as a change to apply.
> GCE: TargetPool should ignore Lifecycle field

- tests/e2e/pkg/tester/skip_regex.go
The fix won't make it into 1.22.0, instead slated for 1.22.1.
https://kubernetes.slack.com/archives/CJH2GBF7Y/p1627938879019800
To avoid additional jobs failing (those that use the `release/stable` k8s version marker) we can ignore the test now that the issue is known and the fix is ready to be merged.
> Temporarily skip MetricsGrabber test

- tests/e2e/scenarios/lib/common.sh
This allows the rest of the scenario to change directories and the "down" step still uses the correct location of the kops binary
This should fix https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kops-e2e-aws-ebs-csi-driver/1413601399341584384
I confirmed all scenario scripts set REPO_ROOT.
/cc @olemarkus I'm curious why that job is building kops from source given that it is a periodic test. I would expect this `kops-acquire-latest()` function to be downloading it from a kops version marker, any idea why that is?
> Kubetest2 scenarios - provide absolute path to kops binary

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/nodeterminationhandler.go
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
- tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_nthsqsresources.example.com-addons-bootstrap_content
- tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_nthsqsresources.example.com-addons-node-termination-handler.aws-k8s-1.11_content
- upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template
> Add nth rebalance recommendation configs

- tests/e2e/pkg/tester/skip_regex.go
ci/latest is already using 1.23 alpha tags so we need to skip these tests for 1.23 until the PR is merged.
Example job not yet skipping the test: https://testgrid.k8s.io/kops-misc#kops-aws-misc-arm64-ci
> Also skip MetricsGrabber tests on 1.23 version marker

- cmd/kops/create_cluster.go
- docs/cli/kops_create_cluster.md
- docs/getting_started/openstack.md
- upup/pkg/fi/cloudup/new_cluster.go
In newer version of OpenStack, there are multiple octavia provider to
choose from instead of only "octavia" as provider. This commit added a
command line option "os-octavia-provider", enabling user to specify the
octavia provider that will be use to create load balancers.
> Add Option to Specify OpenStack Octavia Provider

- tests/e2e/pkg/tester/skip_regex.go
GlusterFS tests fail on ARM64. It is mostly irrelevant for kOps and skipping it always seems the most convenient.
https://testgrid.k8s.io/kops-misc#kops-aws-misc-arm64-ci
> Skip GlusterFS tests

- tests/e2e/pkg/tester/skip_regex.go
https://github.com/kubernetes/kubernetes/pull/104061 has been merged, so CI builds should now pass these tests. Once it is backported to 1.22 we'll remove it from there as well.
> Stop skipping MetricsGrabber tests on CI k8s versions

- docs/operations/images.md
- pkg/resources/aws/aws.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- util/pkg/distributions/distributions.go
- util/pkg/distributions/identify.go
- util/pkg/distributions/identify_test.go
- util/pkg/distributions/tests/debian11/etc/os-release
Add support for Debian 11 ahead of the impending release on August 14th. 
Tested by creating a cluster with the `debian-11-amd64-daily-20210805-725` image and verifying that both the cluster came up and that node logs did not contain any errors. Tested kubenet and cilium networking and both containerd and docker runtimes.
> Support Debian 11 Bullseye

- addons/README.md
- channels/pkg/cmd/BUILD.bazel
- channels/pkg/cmd/apply_channel.go
- docs/releases/1.22-NOTES.md
These are no longer maintained and kept around to not break very old versions of kOps.
/cc @olemarkus @johngmyers @rifelpet
> Disallow the use of legacy addons

- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
Cherry pick of #12114 on release-1.21.
#12114: Make metrics-server insecure if insecure is true
> Automated cherry pick of #12114: Make metrics-server insecure if insecure is true

- pkg/model/bootstrapscript.go
This allows nodeup to use the same azure environment as the kops cli, working towards support for azure government.
https://github.com/kubernetes/kops/blob/b858297fa4f34148374c882c64ebd3025ed59d5a/vendor/github.com/Azure/go-autorest/autorest/azure/auth/auth.go#L48
https://github.com/kubernetes/kops/blob/b858297fa4f34148374c882c64ebd3025ed59d5a/vendor/github.com/Azure/go-autorest/autorest/azure/environments.go#L34-L39
> Pass AZURE_ENVIRONMENT to nodeup

- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.kope.io/k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/authentication.aws-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
for k8s 1.22 support.
ref: https://github.com/kubernetes/kops/issues/11689
> Update addon manifests referencing RBAC v1beta1

- upup/pkg/fi/cloudup/awstasks/vpccidrblock.go
Similarly to the code here, we should catch cases when the VPC doesn't exist yet.  
This is similar to: https://github.com/kubernetes/kops/blob/e7b52981abd9c510106ab4e43a5fa7ae19f80fec/upup/pkg/fi/cloudup/awstasks/vpcamazonipv6cidrblock.go#L44-L48
> Fix cases when the VPC doesn't exist yet

- upup/pkg/fi/cloudup/awstasks/vpccidrblock.go
Backported version of https://github.com/kubernetes/kops/pull/12124.
> Fix cases when the VPC doesn't exist yet for vpccidrblocks in 1.21

- channels/alpha
* https://github.com/kubernetes/kubernetes/releases/tag/v1.19.14
* https://github.com/kubernetes/kubernetes/releases/tag/v1.20.10
* https://github.com/kubernetes/kubernetes/releases/tag/v1.21.4
* https://github.com/kubernetes/kubernetes/releases/tag/v1.22.0
> Bump alpha channel's k8s versions with August releases and add kOps version 1.22 along with k8s 1.22

- docs/operations/images.md
As https://github.com/kubernetes/kops/pull/12132 was approved, docs need updating.
> Update Debian 11 first supported kOps version

- upup/pkg/fi/http.go
The default http transport uses the proxy if the proxy environment variables exist.
However, since we are creating a new transport to define our own timeout, we should set that proxy option.
https://pkg.go.dev/net/http#DefaultTransport
Fixes:  https://github.com/kubernetes/kops/issues/12140
> leverage proxy env variables

- .github/workflows/main.yml
- WORKSPACE
Cherry pick of #12153 on release-1.21.
#12153: Update Go to v1.16.7
> Automated cherry pick of #12153: Update Go to v1.16.7

- docs/operations/images.md
- pkg/resources/aws/aws.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
Now that the release has happened it appears the Debian cloud team is using a different AWS account for release images compared to the daily images.
> Debian 11: Release AMIs use same AWS Owner ID as Buster

- tests/e2e/scenarios/metrics-server/run-test.sh
following the pattern here:
https://github.com/kubernetes/kops/blob/51b22f062f5250c7a0e525362059c598fb493605/tests/e2e/scenarios/aws-ebs-csi/run-test.sh#L22-L24
ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-metrics-server/1427460871503745024#1:build-log.txt%3A160
> Fix unbound variable in metrics server scenario

- docs/operations/images.md
- pkg/resources/aws/aws.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
Cherry pick of #12161 on release-1.21.
#12161: Debian 11: Release AMIs use same AWS Owner ID as Buster
> Automated cherry pick of #12161: Debian 11: Release AMIs use same AWS Owner ID as Buster

- docs/networking/cilium.md
- docs/releases/1.22-NOTES.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/validation/validation.go
- pkg/model/components/cilium.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
- upup/pkg/fi/cloudup/apply_cluster.go
This is a continuation of #11786 which went inactive.
/cc @dntosas
> Cilium wireguard support

- util/pkg/vfs/s3fs.go
Direct to 1.21. This is already fixed as part of a larger change in master.
> Log s3 acl in additional cases

- channels/alpha
Currently running into this on our alpha fleet:
```
W0817 16:17:58.105635    4764 channel.go:239] unable to parse range in channel version spec: ">=v1.22.0-alpha.1"
```
Unless I missed something with versioning changes, I believe this should fix the issue.
> Fix parse channels error

- util/pkg/vfs/swiftfs.go
Swift path prefix in ReadTree and ReadDir should not be empty
when adding "/" to it.
> Incorrect url to the swift container

- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/tests/containerdbuilder/flatcar/tasks.yaml
As part of https://github.com/kinvolk/coreos-overlay/pull/931 and https://github.com/kinvolk/update_engine/pull/13, Flatcar decided to change the containerd exec command and not allow an easy override of the config file.
https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/customizing-docker/#use-a-custom-containerd-configuration
/cc @rifelpet
> Hardcode Flatcar containerd exec command

- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/tests/containerdbuilder/flatcar/tasks.yaml
Cherry pick of #12177 on release-1.21.
#12177: Hardcode Flatcar containerd exec command
> Automated cherry pick of #12177: Hardcode Flatcar containerd exec command

- tests/e2e/pkg/tester/skip_regex.go
The release/latest version marker will stay on 1.23.0-alpha.0 until another 1.23 pre-release is tagged which isn't for a while.
This will skip the MetricsGrabber test for that tag which has been fixed in master ([example failing job](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-scenario-arm64/1427307647635296256#1:build-log.txt%3A140)). This won't match CI builds since they have a [commit hash suffix](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-misc-arm64-ci/1427457851500007424#1:build-log.txt%3A142)
Once a new 1.23 pre-release has been tagged we can remove this.
Alternatively we migrate all jobs off of the release/latest version marker since it isn't particularly valuable.
/hold until 1.22.1 is tagged on Wednesday which includes the cherry-picked …
> Fix MetricsGrabber skip regex condition

- docs/advanced/experimental.md
- pkg/featureflag/featureflag.go
Since dropping support for terraform <0.12, this feature flag is no longer used. The generated HCL2 is always formatted
> Cleanup unused TerraformFmt feature flag

- pkg/model/gcemodel/api_loadbalancer.go
- pkg/model/gcemodel/external_access.go
- pkg/model/gcemodel/firewall.go
- pkg/resources/gce/gce.go
- tests/integration/update_cluster/ha_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/ha_gce/in-v1alpha2.yaml
- tests/integration/update_cluster/ha_gce/kubernetes.tf
- tests/integration/update_cluster/minimal_gce/kubernetes.tf
- tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
- upup/pkg/fi/cloudup/gcetasks/firewallrule.go
Supporting IPv6 values where they can be set by the user, and ensuring
that IPv4 and IPv6 firewall rules are split because on GCP they cannot
be in the same rule.
> Initial IPv6 support for GCE

- docs/addons.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/clusterautoscaler.go
- upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
Cherry pick of #12187 on release-1.21.
#12187: Add option in Cluster Autoscaler AddOn for AWS EC2 Static instance list
```release-note
```
> Automated cherry pick of #12187: Add option in Cluster Autoscaler AddOn for AWS EC2 Static instance list

- tests/integration/update_cluster/aws-lb-controller/kubernetes.tf
- tests/integration/update_cluster/irsa/kubernetes.tf
- tests/integration/update_cluster/many-addons-ccm-irsa/kubernetes.tf
- tests/integration/update_cluster/public-jwks-apiserver/kubernetes.tf
- tests/integration/update_cluster/vfs-said/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/iamoidcprovider.go
These fields are valuable because their fields are used in the assume role policies of service account IAM roles, based on the docs [here](https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html#aws-cli). This allows terraform users to pass these directly to their IAM role definitions.
The reason I'm using a hard-coded string for the issuer is because the provider doesn't output the issuer without a protocol (see docs [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_openid_connect_provider)). The other option would be using a terraform `replace()` function but we don't have support for rendering multi-argument function calls yet.
> Add terraform outputs for OIDC provider ARN and issuer

- hack/dev-build-gce.sh
> Script for iterating development on GCE

- upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
Updating image and manifest to latest stable version.
> [addons/metrics-server] Bump minor version

- upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
Cherry pick of #12198 on release-1.22.
#12198: Bump minor version
> Automated cherry pick of #12198: Bump minor version

- cloudbuild.yaml
We were likely releases kops builds with outdated go patch versions before this. This should get cherry-picked to release-1.22
> Bump cloudbuild images to latest

- hack/go.mod
- hack/go.sum
With https://github.com/kubernetes/kops/pull/12215 merged we should be passing all checks now
> Update staticcheck to latest

- docs/cluster_spec.md
As etcd is running directly as a service on the master nodes it is easy to overlook that different ports are needed to expose metrics for multiple etcd clusters on the master nodes. It can be easy to forget this if you otherwise just deal with containers and pods... 😅  A reminder and clarification doesn't hurt.
> [Documentation update] Note for the metrics configuration for etcd

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
> check does iface has associations

- upup/pkg/fi/cloudup/openstack/cloud.go
Cherry pick of #12227 on release-1.22.
#12227: fix parse semver
> Automated cherry pick of #12227: fix parse semver

- tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
- upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
Cherry pick of #12229 on release-1.22.
#12229: Bump cert-manager to 1.5.3
> Automated cherry pick of #12229: Bump cert-manager to 1.5.3

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
Cherry pick of #12232 on release-1.22.
#12232: check does iface has associations
> Automated cherry pick of #12232: check does iface has associations

- docs/operations/etcd_administration.md
Came across this broken link when working on upgrading some older clusters. Pretty minor fix, validated as working locally. I've signed an individual CLA, and made this contribution from a personal machine.
> Fix etcd3-migration docs link

- tests/e2e/scenarios/metrics-server/run-test.sh
ref: https://github.com/kubernetes/kops/pull/12198
fixes these test failures due to the port change: https://testgrid.k8s.io/kops-misc#kops-aws-metrics-server
> Update metrics-server tag used in e2e scenario

- nodeup/pkg/model/kube_apiserver.go
- nodeup/pkg/model/tests/golden/awsiam/tasks-kube-apiserver.yaml
- nodeup/pkg/model/tests/golden/dedicated-apiserver/tasks-kube-apiserver.yaml
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-apiserver.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-amd64.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-arm64.yaml
- nodeup/pkg/model/tests/golden/without-etcd-events/tasks-kube-apiserver.yaml
With this, we don't have to add the kube-apiserver container name when calling `kubectl logs kube-apiserver-xxx`
> Set kube-apiserver as default logs container

- nodeup/pkg/model/sysctls.go
- pkg/model/components/kubelet.go
I think enabling protectKernelDefaults by default as of 1.22 is a good thing.
We either way need to set these sysctls in nodeup.
ref #12192
> Enable protect-kernel-defaults by default and set the correct sysctls in nodeup

- nodeup/pkg/model/kube_apiserver.go
- nodeup/pkg/model/tests/golden/awsiam/tasks-kube-apiserver.yaml
- nodeup/pkg/model/tests/golden/dedicated-apiserver/tasks-kube-apiserver.yaml
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-apiserver.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-amd64.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-arm64.yaml
- nodeup/pkg/model/tests/golden/without-etcd-events/tasks-kube-apiserver.yaml
Cherry pick of #12246 on release-1.22.
#12246: Set kube-apiserver as default logs container
> Automated cherry pick of #12246: Set kube-apiserver as default logs container

- upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
Now that kubelet certs contains node IPs, metrics-server can use InternalIP. This makes metrics-server work with ipv6.
> Use node internal IP for metrics-server

- pkg/model/components/kubedns.go
AWS now provides ipv6 DNS server endpoint at a fixed address (rather than ipv4, which depends on the VPC CIDR block). This isn't provided in dhcp, and anyways we want to ensure we use this endpoint in ipv6 mode and not have ipv4 in the mix.
> Set ipv6 nameservers on aws

- upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
Cherry pick of #12251 on release-1.22.
#12251: update openstack CSI
> Automated cherry pick of #12251: update openstack CSI

- upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/metrics-server.addons.k8s.io-k8s-1.11.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
Cherry pick of #12260 on release-1.22.
#12260: Use node internal IP for metrics-server
> Automated cherry pick of #12260: Use node internal IP for metrics-server

- pkg/model/components/kubedns.go
Cherry pick of #12259 on release-1.22.
#12259: Set ipv6 nameservers on aws
> Automated cherry pick of #12259: Set ipv6 nameservers on aws

- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
- tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-bootstrap_content
- tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
- tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-bootstrap_content
- tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
Cherry pick of #12265 on release-1.22.
#12265: Disable masquerade means disable masquerade if ipv6 too
> Automated cherry pick of #12265: Disable masquerade means disable masquerade if ipv6 too

- upup/pkg/fi/nodeup/nodetasks/bootstrap_client.go
Should make things faster when there is at least one non-placeholder IP is available:
https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-scenario-ipv6-cilium/1434126561480544256/artifacts/18.119.163.204/kops-configuration.log
```
Task "BootstrapClientTask/BootstrapClient" not ready: kops-controller DNS not setup yet (placeholder IP found: [2600:1f16:caa:f601:f747:6351:1a1a:8af3 203.0.113.123])
```
> Try to bootstrap when at least one IP is available

- nodeup/pkg/model/sysctls.go
Cherry pick of #12271 on release-1.22.
#12271: Fix kernel parameter for IPv6 forwarding
> Automated cherry pick of #12271: Fix kernel parameter for IPv6 forwarding

- pkg/dump/dumper.go
to be consistent with the other log files: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kops/12104/pull-kops-e2e-aws-cloud-controller-manager/1434530384313323520/artifacts/34.220.14.111/
> Add .log suffix to dumped pod logs

- upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
Issue https://github.com/kubernetes/cloud-provider-openstack/issues/1362 mentioned that after csi-provisioner update fstype on provisioned PVs no longer defaults to "ext4". Therefore it has to be set explicitly for volumes to work correctly.
> Set explicit fsType to be able to mount volumes

- upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
Cherry pick of #12280 on release-1.22.
#12280: Set explicit fsType to be able to mount volumes
```release-note
```
> Automated cherry pick of #12280: Set explicit fsType to be able to mount volumes

- pkg/kubemanifest/BUILD.bazel
- pkg/kubemanifest/manifest.go
This allows the object to be treated as a runtime.Object
> Add helper to convert kubemanifest.Object to unstructured

- upup/pkg/fi/cloudup/template_functions.go
Cherry pick of #12286 on release-1.22.
#12286: use ipip Always by default in OpenStack
> Automated cherry pick of #12286: use ipip Always by default in OpenStack

- upup/pkg/fi/cloudup/template_functions.go
CrossSubnet ipip mode does not work in OpenStack. That is why old behaviour "Always" is needed
> use ipip Always by default in OpenStack

- upup/pkg/fi/cloudup/dns.go
This matches the --txt-owner-id flag we specify in the external-dns pod:
https://github.com/kubernetes/kops/blob/8dee92b2f32cbb4e147bbca0f763db01701fb1ae/upup/pkg/fi/cloudup/template_functions.go#L600
/cc @olemarkus
> Include kops- prefix in external-dns TXT record

- pkg/model/components/awscloudcontrollermanager.go
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons-ccm-irsa/in-v1alpha2.yaml
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons-ccm/in-v1alpha2.yaml
- upup/models/cloudup/resources/addons/aws-cloud-controller.addons.k8s.io/k8s-1.18.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/aws-cloud-controller.addons.k8s.io-k8s-1.18.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
WIP pending any action from https://github.com/kubernetes/cloud-provider-aws/issues/244
> Update AWS CCM tags

- pkg/model/components/BUILD.bazel
- pkg/model/components/discovery.go
- tests/integration/update_cluster/minimal_gossip/data/aws_launch_template_master-us-test-1a.masters.minimal.k8s.local_user_data
- tests/integration/update_cluster/minimal_gossip/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/minimal_gossip/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
This reverts https://github.com/kubernetes/kops/pull/11470 introduced earlier in 1.22 that resulted in existing service account tokens becoming invalid after a kops upgrade. Now gossip clusters will continue to use the the master internal name, as was the case in kops <=1.21
As discussed during office hours today
FYI @zetaab this will result in _another_ token invalidation if `serviceAccountIssuer` isn't set in the cluster spec while upgrading from an earlier 1.22 pre-release.
> Use MasterInternalName for gossip cluster SA issuer

- pkg/apis/kops/validation/validation.go
This flag is removed from Kubelet starting from v1.20 of k8s so in here
we add a validation to prevent users from deploying a configuration which
breaks Kubelet and thus nodes from getting ready.
This setting can now only be set on [Kubelet config file.](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/)
Error msg:
```
kubelet[5122]: F0909 11:49:28.458628    5122 server.go:215] invalid configuration: cpuCFSQuotaPeriod {10ms}
```
> [kubelet] Add validation for cpuCFSQuotaPeriod after k8s>=1.20

- util/pkg/distributions/distributions.go
- util/pkg/distributions/identify.go
- util/pkg/distributions/identify_test.go
- util/pkg/distributions/tests/ubuntu2110/etc/os-release
Cherry pick of #12300 on release-1.22.
#12300: Recognize Ubuntu 21.10 (Impish Indri)
> Automated cherry pick of #12300: Recognize Ubuntu 21.10 (Impish Indri)

- pkg/kopscodecs/BUILD.bazel
- pkg/kopscodecs/codecs.go
This is not only cleaner (eliminate a function that panics), but adds
the ability to marshal unstructured.
> Add ability to yaml-encode unstructured

- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
- upup/models/cloudup/resources/addons/snapshot-controller.addons.k8s.io/k8s-1.20.yaml.template
Cherry pick of #12303 on release-1.22.
#12303: Bump snapshot-controller to 4.2.1
> Automated cherry pick of #12303: Bump snapshot-controller to 4.2.1

- upup/pkg/fi/cloudup/dns.go
- upup/pkg/fi/cloudup/dns_test.go
Precreating DNS records that kops cli will overwrite shortly after doesn't provide much benefit. It is also hard to say to external-dns it doesn't own those records.
> Do not precreate dns record for api lbs

- pkg/model/components/awsebscsidriver.go
- tests/e2e/scenarios/aws-ebs-csi/run-test.sh
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_launch_template_nodes.minimal.example.com_user_data
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
- tests/integration/update_cluster/many-addons-ccm/data/aws_launch_template_nodes.minimal.example.com_user_data
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
- tests/integration/update_cluster/many-addons/data/aws_launch_template_nodes.minimal.example.com_user_data
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_master-us-test-1a.masters.minimal-warmpool.example.com_user_data
- tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_nodeupconfig-nodes_content
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
Cherry pick of #12310 on release-1.22.
#12310: Bump aws ebs csi driver to 1.2.1
> Automated cherry pick of #12310: Bump aws ebs csi driver to 1.2.1

- .github/workflows/main.yml
- WORKSPACE
Cherry pick of #12306 on release-1.22.
#12306: Update Go to v1.16.8
> Automated cherry pick of #12306: Update Go to v1.16.8

- pkg/model/components/awscloudcontrollermanager.go
> Default to latest staging image for AWS CCM

- k8s/crds/kops.k8s.io_clusters.yaml
- nodeup/pkg/model/BUILD.bazel
- nodeup/pkg/model/cloudconfig.go
- nodeup/pkg/model/cloudconfig_test.go
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/cloudconfiguration.go
Default to IPv6 + IPv4 but allow setting IPv6 or IPv4 only.
> Make AWS CCM NodeIPFamilies configurable

- upup/pkg/fi/cloudup/dns.go
- upup/pkg/fi/cloudup/dns_test.go
Cherry pick of #12308 on release-1.22.
#12308: Do not precreate dns record for api lbs
> Automated cherry pick of #12308: Do not precreate dns record for api lbs

- go.mod
- go.sum
- tests/e2e/go.sum
- upup/pkg/fi/cloudup/terraform/hcl2.go
- upup/pkg/fi/cloudup/terraform/hcl2_test.go
- upup/pkg/fi/cloudup/terraformWriter/literal.go
- vendor/github.com/hashicorp/hcl/v2/CHANGELOG.md
- vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go
- vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression_template.go
- vendor/github.com/hashicorp/hcl/v2/hclsyntax/parser.go
- vendor/github.com/hashicorp/hcl/v2/hclsyntax/spec.md
- vendor/github.com/hashicorp/hcl/v2/ops.go
- vendor/modules.txt
[Terraform provider aliases](https://www.terraform.io/docs/language/providers/configuration.html#selecting-alternate-provider-configurations) are referenced with two "tokens": `aws.files`
This adds support for literal references with an arbitrary number of tokens for eventual use by a provider alias in aws_s3_bucket_object resources.
> Allow arbitrary length terraform literals

- nodeup/pkg/model/kube_scheduler.go
I believe this is what is causing the e2e fail right now.
> Use TLS for kubescheduler health check as of k8s 1.23

- channels/alpha
* https://github.com/kubernetes/kubernetes/releases/tag/v1.22.2
* https://github.com/kubernetes/kubernetes/releases/tag/v1.21.11
* https://github.com/kubernetes/kubernetes/releases/tag/v1.20.5
* https://github.com/kubernetes/kubernetes/releases/tag/v1.19.15
Also update the recommended `kOps` version from `1.22.0-alpha.2` to `1.22.0-beta.1`
> Update ALPHA k8s versions with Sept releases

- tests/e2e/pkg/tester/skip_regex.go
The SCTP tests in k8s 1.23 are currently failing in all cilium jobs (examples: [kops-warm-pool](https://testgrid.k8s.io/kops-misc#kops-warm-pool), [kops-grid-scenario-cilium10-amd64](https://testgrid.k8s.io/kops-misc#kops-grid-scenario-cilium10-amd64), [kops-aws-external-dns](https://testgrid.k8s.io/kops-misc#kops-aws-external-dns))
The cilium issue linked in the comments suggests that SCTP support is not yet supported, so we can skip them for now. There is also a k/k PR that cleans up the SCTP tests that we can keep an eye on and reevaluate whether we need this skip once it merges.
Also removing the MetricsGrabber skip now that the fix is in 1.23.0-alpha.2.
> Skip SCTP e2e tests on cilium + k8s 1.23

- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
> Use EC2 and Metadata IPv6 endpoints in IPv6 mode for EBS CSI Driver

- pkg/resources/aws/aws.go
They should be deleted as they will presumably be running shortly.
Also, this function is used from `kops dump cluster` where presumably
instances are more likely to be pending.
> Recognize pending EC2 instances as needed deletion

- pkg/resources/aws/aws.go
Cherry pick of #12357 on release-1.22.
#12357: Recognize pending EC2 instances as needed deletion
> Automated cherry pick of #12357: Recognize pending EC2 instances as needed deletion

- pkg/model/components/kubecontrollermanager.go
The previous logic would override the controller slice in each
condition, instead of building it up.
> Fix controller defaults for both bootstrap tokens and ipv6

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
https://docs.projectcalico.org/archive/v3.19/release-notes/#v3193
> Update Calico to v3.19.3 for kOps 1.21

- pkg/model/components/BUILD.bazel
- pkg/model/components/discovery.go
- tests/integration/update_cluster/minimal_gossip/data/aws_launch_template_master-us-test-1a.masters.minimal.k8s.local_user_data
- tests/integration/update_cluster/minimal_gossip/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/minimal_gossip/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
Cherry pick of #12297 on release-1.22.
#12297: Use MasterInternalName for gossip cluster SA issuer
```release-note
```
> Automated cherry pick of #12297: Use MasterInternalName for gossip cluster SA issuer

- upup/pkg/fi/cloudup/populate_instancegroup_spec.go
We need to check for nil.
We could consider using Getters.
> Fix nil pointer error where containerd is not in use

- tests/e2e/go.sum
- tests/e2e/kubetest2-kops/deployer/dumplogs.go
Some of our jobs ([example](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-upgrade-k121-ko121-to-klatest-kolatest/1439693519793950720)) are currently failing because `kops validate cluster` times out waiting for the k8s API DNS record to be updated.
To assist in troubleshooting, we can get insight into the k8s resources present on the cluster even though the DNS record hasnt been set if we use kubectl on the control plane host via SSH.
This will SSH into a control plane host when the local kubectl dump fails.
> kubetest2 - add support for dumping k8s resources via SSH

- upup/pkg/fi/task.go
Remove the log message at V(8), it doesn't include any real
signal.  This method also gets called a lot!
Also differentiate between the expected and unexpected cases when a
task implements/does not implement HasLifecycle.
> Better logging in setLifecycleOverride

- tests/e2e/go.mod
- tests/e2e/kubetest2-kops/deployer/dumplogs.go
The output is in yaml, not json. Should fix [this](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-upgrade-k121-ko121-to-klatest-kolatest/1439904914728816640#1:build-log.txt%3A11798) error.
`W0920 11:33:33.229371    5232 down.go:34] Dumping cluster logs at the start of Down() failed: invalid character 'i' looking for beginning of value`
Also add logging to help troubleshoot which command is failing
> Fix parsing of kops toolbox dump yaml output

- tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-bootstrap_content
- tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
Cherry pick of #12360 on release-1.22.
#12360: Update Calico to v3.20.1
> Automated cherry pick of #12360: Update Calico to v3.20.1

- tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
- upup/pkg/fi/cloudup/new_cluster.go
We don't need them on GCE, and in fact we don't support them with IP Alias.
> GCE: Don't create utility subnets in private topology

- pkg/model/context.go
- pkg/model/gcemodel/firewall.go
We need to open up the ipip protocol, which wasn't previously enabled.
Future work could construct the firewall rules in a common library,
and then adapt them to the various clouds.
> GCE: When using calico, need to open up ipip protocol

- nodeup/pkg/model/sysctls.go
The ipv4 and ipv6 forwarding is usually set by default. Also, seems that the original reason behind adding it is gone.
`net.ipv6.conf.all.accept_ra` is not working as expected and is mostly ignored.
/cc @olemarkus
> Remove unneeded network related sysctls

- nodeup/pkg/model/sysctls.go
Cherry pick of #12385 on release-1.22.
#12385: Remove unneeded network related sysctls
> Automated cherry pick of #12385: Remove unneeded network related sysctls

- pkg/dump/dumper.go
This is currently over 2 minutes. This change should speed up the end of tests when SSH isn't available.
> Decrease connection timeout when dumping logs from instances

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
CNI chaining allows using Cilium in combination with other CNI plugins.
With Cilium CNI chaining, the base network connectivity and IP address management is managed by the non-Cilium CNI plugin, but Cilium attaches eBPF programs to the network devices created by the non-Cilium plugin to provide L3/L4 network visibility, policy enforcement and other advanced features.
https://docs.cilium.io/en/v1.9/gettingstarted/cni-chaining/#cni-chaining
In our case, to be able to use the `HostPort` feature in our cluster, we need to enable the `portmap` plugin.
> Add support to configure Cilium CNI chaining

- hack/verify-terraform.sh
Cherry pick of #12403 on release-1.22.
#12403: Upgrade terraform to 1.0.7
```release-note
```
> Automated cherry pick of #12403: Upgrade terraform to 1.0.7

- nodeup/pkg/model/sysctls.go
This reverts commit ce08ec68dfb5bdf2c74d61dfd008c5fa671ef200.
Removing these sysctls broke a number of CNIs (weave, aws vpc, and canal), and possibly breaks configurations we do not test as well.
The accept_ra sysctls can be removed in a followup.
> Revert "Remove unneeded network related sysctls"

- nodeup/pkg/model/sysctls.go
Cherry pick of #12415 on release-1.22.
#12415: Revert "Remove unneeded network related sysctls"
> Automated cherry pick of #12415: Revert "Remove unneeded network related sysctls"

- pkg/model/components/cilium.go
- tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_nodeupconfig-nodes_content
- tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-bootstrap_content
- tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
- tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-bootstrap_content
- tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
- Cilium versions 1.10.4 and 1.9.10 now auto-mount the bpf file-system automatically. This logic depends on the specific version of Cilium in use so that users who are manually specifying a different version keep the previous behavior.
- Also remove redundant capabilities (these are already automatically granted by virtue of this being a privileged container)
Reference Cilium PRs/commits:
- https://github.com/cilium/cilium/pull/16656
- https://github.com/cilium/cilium/commit/1b20f7f90bace440f52195cefa4df8cbe6fe4cf9#diff-264b5e646aa5ad3db682a4a0a9cd4b4cbbae238d88b033d340e901060c89394a
- https://github.com/cilium/cilium/pull/17131
> Add bidirectional BPF mount for Cilium >= 1.9.10 or >= 1.10.4

- docs/contributing/release-process.md
Closes: https://github.com/kubernetes-sigs/promo-tools/issues/424
ref: https://github.com/kubernetes/k8s.io/pull/2711
Signed-off-by: Stephen Augustus <foo@auggie.dev>
/assign @hakman @johngmyers @justinsb @mikesplain @rifelpet
cc: @kubernetes/release-engineering
> release-process.md: Update references to artifact promotion

- protokube/pkg/protokube/kube_boot.go
We run protokube on the nodes in gossip mode; however protokube tries
to connect to the apiserver on localhost, and that simply won't work
if running on a node.
This doesn't cause any actual problems beyond logspam, but it's an
easy fix.
> protokube: don't try to connect to apiserver if not control-plane

- pkg/dump/dumper.go
This should help troubleshoot DNS issues in gossip clusters.
For example, [this GCE job](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-gce-cilium-u2004-k22-docker/1442007600894840832) is failing to validate because nodes arent joining the cluster. [kubelet logs](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-gce-cilium-u2004-k22-docker/1442007600894840832/artifacts/34.106.20.139/kubelet.log) on an unjoined node report not being able to resolve the API DNS record. [protokube logs](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-gce-cilium-u2004-k22-docker/1442007600894840832/artifacts/34.106.20.139/protokube.log) on the same node report updating /etc/hosts but it will be easier to troubleshoot if we can see the final contents …
> Have toolbox dump include contents of /etc/hosts

- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/authentication.aws-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
Also adding the CCM toleration to match dns-controller in https://github.com/kubernetes/kops/pull/12389
Fixes #12390
> Allow aws-iam-authenticator to be scheduled onto dedicated apiserver nodes

- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/authentication.aws-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
Cherry pick of #12426 on release-1.22.
#12426: Allow aws-iam-authenticator to be scheduled onto dedicated
```release-note
```
> Automated cherry pick of #12426: Allow aws-iam-authenticator to be scheduled onto dedicated

- nodeup/pkg/model/networking/cilium.go
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
- tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-bootstrap_content
- tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
- tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-bootstrap_content
- tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
This should fix cilium for AL2 5.10 kernel.
> Mount cgroupv2 for cilium at a custom location

- docs/operations/images.md
- docs/releases/1.22-NOTES.md
ref: https://github.com/kubernetes/kops/issues/12429
ref: https://github.com/kubernetes/test-infra/pull/23764
/hold to see the results of https://testgrid.k8s.io/kops-distros#kops-aws-distro-imageamazonlinux2 and the grid jobs.
> Update Amazon Linux 2 documentation to mention the 5.10 kernel

- tests/e2e/pkg/tester/skip_regex.go
These tests will never work with how kOps configures GCE clusters, so skip them for now.
Using this job as a reference: https://testgrid.k8s.io/kops-gce#kops-grid-gce-u2004-k22-docker
These tests are already being skipped in the original GCE jobs: https://github.com/kubernetes/test-infra/blob/6f7377aa20ea5c7b0e1284c0934114d1849d6dcd/config/jobs/kubernetes/kops/kops-periodics-gce.yaml#L39
> Skip certain e2e tests in GCE

- docs/releases/1.22-NOTES.md
I was reading the documentation and `acount` stood out to me.
> Fix typo in name of new 'UseServiceAccountExternalPermissions' variable.

- nodeup/pkg/model/networking/cilium.go
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
- tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-bootstrap_content
- tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
- tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-bootstrap_content
- tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
Cherry pick of #12431 on release-1.22.
#12431: Mount cgroupv2 for cilium at a custom location
```release-note
```
> Automated cherry pick of #12431: Mount cgroupv2 for cilium at a custom location

- pkg/apis/kops/validation/validation.go
- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/authentication.aws-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
Cherry pick of #12425 on release-1.22.
#12425: aws-iam-authenticator - use v1 CRD API for k8s 1.22
```release-note
```
> Automated cherry pick of #12425: aws-iam-authenticator - use v1 CRD API for k8s 1.22

- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Vendoring [this PR](https://github.com/aws/amazon-vpc-cni-k8s/pull/1618) following release [1.9.1](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.9.1).
> Bump  aws-cni version to 1.9.1

- tests/e2e/pkg/tester/skip_regex.go
This skips the last failure on the ipv6 calico jobs: https://testgrid.k8s.io/kops-misc#kops-grid-scenario-ipv6-calico
> Skip load balancer test in IPv6 clusters

- nodeup/pkg/model/sysctls.go
`net.ipv6.conf.all.accept_ra=2` is unnecessary and possibly conflicting with `syststemd-networkd`.
xRef: https://github.com/systemd/systemd/issues/13061
> Remove unnecessary sysctl "net.ipv6.conf.all.accept_ra=2"

- nodeup/pkg/model/sysctls.go
Cherry pick of #12461 on release-1.22.
#12461: Remove unnecessary sysctl "net.ipv6.conf.all.accept_ra=2"
> Automated cherry pick of #12461: Remove unnecessary sysctl "net.ipv6.conf.all.accept_ra=2"

- cmd/kops/toolbox_template.go
Cherry pick of #12464 on release-1.20.
#12464: Don't ignore channel value in toolbox template
> Automated cherry pick of #12464: Don't ignore channel value in toolbox template

- pkg/model/components/clusterautoscaler.go
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
Cherry pick of #12463 on release-1.22.
#12463: Bump CAS images
```release-note
```
> Automated cherry pick of #12463: Bump CAS images

- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
This PR upgrades `spotinst/ocean-controller` to v1.0.78.
> Spotinst: Update `spotinst/ocean-controller` to v1.0.78

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha3/networking.go
- pkg/apis/kops/v1alpha3/zz_generated.conversion.go
- pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
Annotations is pretty useful when you need third-party tool to add additional behavior
for a k8s resource.
Lots of auto-discovery tools are based on this annotations.
> Add Cilium agent pod annotations support to improve personalization

- pkg/model/domodel/droplets.go
- upup/pkg/fi/cloudup/dotasks/droplet.go
This PR introduces minor changes to create KOPS DO cluster in an existing VPC.
It uses the `--vpc` flag that already exists to pass the vpc uuid where the droplets must be created.
Example:
./kops create cluster --cloud=digitalocean --name=dev1.example.co.in --vpc=af287488-862e-46c7-a783-5e5fa89cb256 --networking=cilium --zones=tor1 --ssh-public-key=~/.ssh/id_rsa_github.pub
Tested to make sure the droplets are created in the vpc specified.
Next steps, may include additional support for creating new vpc as part of the kops create cluster option.
> [DigitalOcean] Incorporate existing vpc support for kops

- nodeup/pkg/model/kube_scheduler.go
Ref: https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/785-scheduler-component-config-api/README.md
Hopefully fixes:
https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-scenario-ipv6-conformance/1445174305280233472/artifacts/cluster-info/kube-system/kube-scheduler-ip-172-20-43-37.eu-west-1.compute.internal/logs.txt
> E1005 00:04:12.105552       1 run.go:120] "command failed" err="no kind \"KubeSchedulerConfiguration\" is registered for version \"kubescheduler.config.k8s.io/v1beta1\" in scheme \"k8s.io/kubernetes/pkg/scheduler/apis/config/scheme/scheme.go:30\""
> Add kubescheduler.config.k8s.io/v1beta2 for k8s 1.22+

- nodeup/pkg/model/kube_scheduler.go
Cherry pick of #12486 on release-1.22.
#12486: Add kubescheduler.config.k8s.io/v1beta2 for k8s 1.22+
> Automated cherry pick of #12486: Add kubescheduler.config.k8s.io/v1beta2 for k8s 1.22+

- protokube/pkg/protokube/kube_boot.go
Cherry pick of #12424 on release-1.22.
#12424: protokube: don't try to connect to apiserver if not
```release-note
```
> Automated cherry pick of #12424: protokube: don't try to connect to apiserver if not

- tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-bootstrap_content
- tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
https://docs.projectcalico.org/archive/v3.20/release-notes/#v3202
> Update Calico to v3.20.2

- tests/e2e/kubetest2-kops/deployer/dumplogs.go
This should reduce some of the verbose clutter in the job logs during cluster teardown
/cc @hakman
> Log `kops toolbox dump` output to artifacts dir rather than stdout

- pkg/model/iam/iam_builder.go
- tests/integration/update_cluster/minimal-ipv6-calico/cloudformation.json
- tests/integration/update_cluster/minimal-ipv6-calico/data/aws_iam_role_policy_masters.minimal-ipv6.example.com_policy
- tests/integration/update_cluster/minimal-ipv6-cilium/cloudformation.json
- tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_iam_role_policy_masters.minimal-ipv6.example.com_policy
- tests/integration/update_cluster/minimal-ipv6/cloudformation.json
- tests/integration/update_cluster/minimal-ipv6/data/aws_iam_role_policy_masters.minimal-ipv6.example.com_policy
Still needed by kops-controller for cloud IPAM:
https://testgrid.k8s.io/kops-ipv6#kops-grid-scenario-ipv6-cilium-cloudipam
https://github.com/kubernetes/kops/blob/fa29c9a6b29f21becb9453f204759f6a07a644f0/cmd/kops-controller/controllers/awsipam.go#L127
/cc @johngmyers @rifelpet @olemarkus
> Allow kops-controller to describe network interfaces

- nodeup/pkg/model/sysctls.go
Test run using Calico and Debian 11 here:
https://testgrid.k8s.io/kops-ipv6#pull-kops-e2e-ipv6-conformance
/cc @olemarkus @johngmyers @rifelpet
> Enable Router Advertisements for Debian 11

- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- pkg/model/components/calico.go
- tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.16_content
- tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-bootstrap_content
- tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
Time for Calico to join the party. Seems to work pretty well with the Debian 11 image and the return of `net.ipv6.conf.ens5.accept_ra=2`.
/cc @johngmyers @olemarkus @rifelpet
> Use prefixes for IPv6 with Calico

- docs/operations/rotate-secrets.md
Number the subsections of the rotate-secrets document that are ordered steps in a procedure. This is to discourage people from picking and choosing steps as if they were isolated options.
> doc: Number subsections that are procedural steps

- dns-controller/pkg/dns/dnscontroller.go
This reverts commit c58f104e4de205ccd49effb4126f052114c31dd9.
From the logs, it appears that the node's IPv4 addresses appear in the node resource some time after the node's IPv6 internal address does. This causes dns-controller to delete the placeholder address upon new cluster creation.
Since #12616 fixed the generation of placeholder addresses to just the appropriate address families, revert #12605.
> Revert "Make dns-controller delete placeholder addresses for IPv6 cluster"

- nodeup/pkg/model/kube_proxy.go
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-proxy.yaml
followup to https://github.com/kubernetes/kops/pull/12494
ref: https://github.com/kubernetes/kops/pull/12494
> Migrade kube-proxy manifest to use go-runner for logging

- tests/e2e/kubetest2-kops/deployer/dumplogs.go
Make directories prior to creating files in them. Also cleanup some error handling so that the remaining teardown steps can run even if dumplogs fails.
Add --request-timeout to some kubectl commands to shorten wait times when the cluster isnt up
> Fix error handling in kubetest2 dumplogs

- nodeup/pkg/model/kube_proxy.go
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-proxy.yaml
This reverts commit b0e585c751ba07d92bc25414f5403c2aa7e67d16.
The latest CI builds of the kube-proxy image don't have /go-runner. I will bring this up with the relevant team
ref: https://github.com/kubernetes/kops/pull/12664#issuecomment-957116852
ref: https://github.com/kubernetes/kops/issues/12663#issuecomment-957372273
> Revert "Migrate kube-proxy manifest to use go-runner for logging"

- pkg/model/iam/iam_builder.go
- tests/integration/update_cluster/minimal-warmpool/data/aws_iam_role_policy_nodes.minimal-warmpool.example.com_policy
- tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_cluster-completed.spec_content
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_nodeupconfig-nodes_content
- tests/integration/update_cluster/minimal-warmpool/in-v1alpha2.yaml
- tests/integration/update_cluster/minimal-warmpool/kubernetes.tf
Cherry pick of #12672 on release-1.22.
#12672: Enable lifecycle hook in integration test
```release-note
```
> Automated cherry pick of #12672: Fix cluster name used in IAM policies

- pkg/resources/aws/aws.go
According to [aws-cli docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/delete-role.html#examples),
it is needed to delete any Instance profile that uses a role before deleting
the actual role. This fix adds a "blocks" statement to the IAM Instance Profile,
to declare that it should block the IAM Role deletion.
> Fix that states AWS IAM Instance Profile blocks IAM Role

- k8s/crds/kops.k8s.io_clusters.yaml
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-controller-manager.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha3/componentconfig.go
- pkg/apis/kops/v1alpha3/zz_generated.conversion.go
- pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/awscloudcontrollermanager.go
- pkg/model/components/kubecontrollermanager.go
This is a proposal for how to migrate existing AWS clusters to external CCM
* In k8s 1.23 we default to enabling [leader migration](https://cloud-provider-aws.sigs.k8s.io/getting_started/#using-leader-migration) if using KCM on AWS
* In k8s 1.24 and higher we only support CCM for AWS.
* In k8s 1.24 we default to enabling leader migration on AWS.
* In k8s 1.25 and higher we default to disabling leader migration.
> Migrate to AWS CCM in k8s 1.24

- upup/pkg/fi/http.go
We deploy multiple clusters in different AWS regions, and since upgrading kops to `v1.21.1` we've noticed issues during the `nodeup` phase for nodes in the `ap-southeast-2` region.
After some debugging we've tracked it down to an asset that is taking > 10 seconds just to return response headers, the specific asset in question is: `https://github.com/containerd/containerd/releases/download/v1.4.9/cri-containerd-cni-1.4.9-linux-amd64.tar.gz`.
While it's highly likely this is caused by some networking issues between the AWS `ap-southeast-2` region and the above github mirror, we are seeing nodes fail to join the cluster and response headers for that asset constantly taking > 10 seconds. 
We didn't previously hit any issues with these assets when managing our clusters with older versions of …
> Increase upup http response header timeout

- upup/pkg/fi/http.go
Cherry pick of #12694 on release-1.22.
#12694: Increase upup http response header timeout
> Automated cherry pick of #12694: Increase upup http response header timeout

- docs/operations/cluster_template.md
> Add docs on how to assign arrays with toolbox template

- upup/pkg/fi/cloudup/awstasks/iamrolepolicy.go
The [AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html#reference_iam-quotas-entity-length) mentions:
> IAM does not count white space when calculating the size of a policy against these quotas.
Therefore we should be excluding white space when performing this validation client-side.
fixes https://github.com/kubernetes/kops/issues/12606
> Ignore white space when validating IAM policy size limits

- upup/pkg/fi/cloudup/awstasks/iamrolepolicy.go
Cherry pick of #12700 on release-1.22.
#12700: Ignore white space when validating IAM policy size limits
```release-note
```
> Automated cherry pick of #12700: Ignore white space when validating IAM policy size limits

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha3/networking.go
- pkg/apis/kops/v1alpha3/zz_generated.conversion.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
This is a needed configuration option for calico users that want to set **allow_ip_forwarding** within the container namespace. 
Ref issue: #12678
> [calico] Add support for allow_ip_forwarding field

- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
Provide calico-node with more time to come up.
> set calico-node readiness/liveness timeout to 10s

- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
Cherry pick of #12713 on release-1.22.
#12713: set calico-node readiness/liveness timeout to 10s
> Automated cherry pick of #12713: set calico-node readiness/liveness timeout to 10s

- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/authentication.aws-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
Cherry pick of #12716 on release-1.22.
#12716: Add missing status fields to IAMIdentityMapping v1 CRD
```release-note
```
> Automated cherry pick of #12716: Add missing status fields to IAMIdentityMapping v1 CRD

- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/authentication.aws-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/authentication.aws-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/manifest.yaml
ref: https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/411
regression from https://github.com/kubernetes/kops/pull/12425 and will need cherrypicking to 1.22
> Add missing status fields to IAMIdentityMapping v1 CRD

- pkg/nodelabels/builder.go
We were relying on the featureflag, but this isn't available
server-side, and we're in kops-controller here.
> Populate api-server role label on node

- k8s/crds/kops.k8s.io_clusters.yaml
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-controller-manager.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha3/componentconfig.go
- pkg/apis/kops/v1alpha3/zz_generated.conversion.go
- pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/awscloudcontrollermanager.go
- pkg/model/components/kubecontrollermanager.go
It appears we need to also patch the `system::leader-locking-kube-controller-manager` Role. Revert until we can figure out how best to do this.
> Revert leader migration

- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
The type of `Cilium.AgentPrometheusPort` is Int, golang template function `printf` with format `%q` is used for unicode character.
Fixes #12717
> Fix render template cilium AgentPrometheusPort into a UNICODE char error

- docs/releases/1.23-NOTES.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha3/cluster.go
- tests/integration/update_cluster/external_dns/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/external_dns/data/aws_s3_bucket_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.12_content
- tests/integration/update_cluster/external_dns_irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/external_dns_irsa/data/aws_s3_bucket_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.12_content
- upup/pkg/fi/cloudup/template_functions.go
When using dns-controller, it's likely that there would be an externally installed external-dns creating DNS records for ingresses, so in order to avoid two controllers fighting over the same domains the default of `false` for `watchIngress` makes sense.
With a kops-managed external-dns, it makes more sense to enable `watchIngress` by default.
> Watch Ingress by default when using the external-dns provider

- pkg/instancegroups/instancegroups.go
- pkg/instancegroups/rollingupdate_test.go
> Fix out of bounds error when instance detach fails

- pkg/apis/kops/validation/validation.go
Cherry pick of #12729 on release-1.22.
#12729: Don't fail validation if Nvidia and containerRuntime defaults
> Automated cherry pick of #12729: Don't fail validation if Nvidia and containerRuntime defaults

- pkg/apis/kops/validation/validation.go
- pkg/instancegroups/settings.go
`GetValueFromIntOrPercent()` treated all string values as percentages, even if they didn't have a trailing percent sign. `GetScaledValueFromIntOrPercent()` treats string values not followed by a percent sign as errors.
> Fix use of deprecated method

- pkg/instancegroups/instancegroups.go
- pkg/instancegroups/rollingupdate_test.go
Cherry pick of #12698 on release-1.21.
#12698: Fix out of bounds error when instance detach fails
> Automated cherry pick of #12698: Fix out of bounds error when instance detach fails

- pkg/commands/set_cluster_test.go
- pkg/commands/unset_cluster_test.go
- util/pkg/reflectutils/access.go
Cherry pick of #12728 on release-1.22.
#12728: Support setting empty maps and structs
> Automated cherry pick of #12728: Support setting empty maps and structs

- cmd/kops/integration_test.go
- tests/integration/update_cluster/external_dns/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/external_dns/data/aws_s3_bucket_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.19_content
- tests/integration/update_cluster/external_dns/kubernetes.tf
- tests/integration/update_cluster/external_dns_irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/external_dns_irsa/data/aws_s3_bucket_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.19_content
- tests/integration/update_cluster/external_dns_irsa/kubernetes.tf
- upup/models/BUILD.bazel
- upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/k8s-1.19.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
> Upgrade external-dns to 0.10.1 for Kubernetes >= 1.19

- cmd/kops/integration_test.go
- tests/integration/update_cluster/external_dns/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/external_dns/data/aws_s3_bucket_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.19_content
- tests/integration/update_cluster/external_dns/kubernetes.tf
- tests/integration/update_cluster/external_dns_irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/external_dns_irsa/data/aws_s3_bucket_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.19_content
- tests/integration/update_cluster/external_dns_irsa/kubernetes.tf
- upup/models/BUILD.bazel
- upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/k8s-1.19.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #12724 on release-1.22.
#12724: Upgrade external-dns to 0.10.1 for Kubernetes >= 1.19
> Automated cherry pick of #12724: Upgrade external-dns to 0.10.1 for Kubernetes >= 1.19

- nodeup/pkg/model/networking/cilium.go
Cherry pick of #12744 on release-1.22.
#12744: Do not return error when there is no error checking for
```release-note
```
> Automated cherry pick of #12744: Do not return error when there is no error checking for

- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
Cherry pick of #12721 on release-1.22.
#12721: Fix render template cilium AgentPrometheusPort into a UNICODE
> Automated cherry pick of #12721: Fix render template cilium AgentPrometheusPort into a UNICODE

- pkg/resources/aws/aws.go
Cherry pick of #12677 on release-1.21.
#12677: Fix that states AWS IAM Instance Profile blocks IAM Role
```release-note
```
> Automated cherry pick of #12677: Fix that states AWS IAM Instance Profile blocks IAM Role

- upup/pkg/fi/assetstore.go
> Shorten filenames in the asset store

- upup/pkg/fi/assetstore.go
Cherry pick of #12765 on release-1.21.
#12765: Shorten filenames in the asset store
> Automated cherry pick of #12765: Shorten filenames in the asset store

- nodeup/pkg/model/kube_proxy.go
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-proxy.yaml
Second attempt followup to https://github.com/kubernetes/kops/pull/12664
/hold for k8s 1.23.0-beta.0 next week to include https://github.com/kubernetes/kubernetes/issues/106086
Fixes #12663
> Migrate kube-proxy manifest to use go-runner for logging

- tests/e2e/scenarios/lib/common.sh
This allows us to easily test arbitrary versions (e.g. PR builds)
> e2e tests: recognize a full KOPS_BASE_URL as a KOPS_VERSION

- upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
- upup/pkg/fi/cloudup/awstasks/subnet_mapping.go
This ensures a stable order, even if/when the IDs aren't set (e.g. in terraform)
> Stable-sort subnets by Name

- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
Otherwise the objects overwrite each other, because YAML.
> Fix AWS authentication separator to support multiple objects

- pkg/model/BUILD.bazel
- pkg/model/master_volumes.go
- pkg/model/master_volumes_test.go
Our ratio checks check for e.g == 50, which is actually allowed by AWS.
Fixes #12038
> Fix volume ratio comparisons

- cmd/kops/create_cluster.go
- docs/cli/kops_create_cluster.md
- upup/pkg/fi/cloudup/new_cluster.go
Cherry pick of #12741 on release-1.22.
#12741: Add create cluster flag for enabling IRSA
> Automated cherry pick of #12741: Add create cluster flag for enabling IRSA

- upup/pkg/fi/cloudup/new_cluster.go
Looks like there's no going back and the current IPv6 setup and this is already part of the documentation.
/cc @johngmyers
> Remove warning about IPv6 being experimental

- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/pollinterval/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Cherry pick of #12763 on release-1.21.
#12763: Bump etcd-manager version
> Automated cherry pick of #12763: Bump etcd-manager version

- pkg/model/components/discovery.go
- util/pkg/vfs/s3context.go
- util/pkg/vfs/s3fs.go
If we are launching kops in an environment with only ipv6, we need to use dualstack endpoints for fetching things from S3.
There is a challenge in that for existing clusters, this will change the issuer urls, and we have run into problems with this in the past.
> Use dualstack endpoint for s3

- pkg/resources/gce/BUILD.bazel
- pkg/resources/gce/gce.go
Because the control-plane can recreate routes, there's a race between
deleting instances and deleting routes.  Add a dependency so we don't
try to delete routes until after we've deleted all the instances.
> GCE: Fix race around route deletion

- pkg/edit/BUILD.bazel
- pkg/edit/edit.go
- pkg/edit/edit_test.go
When we check for extra fields, we check only check for byte equality. But because of omitEmpty, fields set explicitly to false are removed, which cause a diff of removed line. This change introduces an actual strict unmarshal to ensure all the fields are known. Then it continues with the existing logic to preserve the output.
> Check that there are extra fields and not fields explicitly false

- upup/models/cloudup/resources/addons/node-problem-detector.addons.k8s.io/k8s-1.17.yaml.template
When deploy node-problem-detector in kubernetes cluster, needs rolebinding to patch the node.
Fixes #12817
> Add NodeProblemDetector clusterRoleBinding

- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
- tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-bootstrap_content
- tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-bootstrap_content
- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
- upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- Add missing namespace for aws-ebs-csi-driver pdb template
- Add missing namespace for cluster-autoscaler pdb template
Fixes https://github.com/kubernetes/kops/issues/12815
> Add missing namespaces for addon templates

- upup/models/cloudup/resources/addons/node-problem-detector.addons.k8s.io/k8s-1.17.yaml.template
PR #12819 not specifiy `serviceAccountName` at daemonset.
Fixes #12817
> Add nodeProblemDetector daemonset serviceAccountName

- k8s/crds/kops.k8s.io_clusters.yaml
- nodeup/pkg/model/docker_test.go
- pkg/apis/kops/dockerconfig.go
- pkg/apis/kops/v1alpha2/dockerconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha3/dockerconfig.go
- pkg/apis/kops/v1alpha3/zz_generated.conversion.go
- pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
This commit adds support for the --dns flag which is provided as a
Docker daemon startup flag. The flag is used to set the IP address of
the DNS server that the daemon injects into containers. Multiple --dns
flags are supported.
Closes https://github.com/kubernetes/kops/issues/12755
> Add support for --dns flag in Docker config

- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/pollinterval/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Cherry pick of #12826 on release-1.21.
#12826: Update etcd-manager to v3.0.20211124
> Automated cherry pick of #12826: Update etcd-manager to v3.0.20211124

- tests/e2e/pkg/tester/skip_regex.go
With the first k8s 1.24 tag cut, prow jobs are now testing with k8s 1.24 and this test is no longer being skipped even though the PR and issues mentioned in the comments are still open. This skips the test in k8s 1.24 as well.
fixes https://testgrid.k8s.io/kops-misc#kops-grid-scenario-cilium10-arm64
> Skip SCTP test on cilium clusters in k8s 1.24 as well

- pkg/model/components/awscloudcontrollermanager.go
- pkg/model/components/kubecontrollermanager.go
/kind bug
The code disabled KCM in 1.24, but didn't enable CCM. This broke the kops-aws-k8s-latest periodic test, as latest now identifies as 1.24.
> Fix enabling of AWS CCM

- pkg/model/awsmodel/network.go
- tests/integration/update_cluster/minimal-ipv6-private/kubernetes.tf
Routes the well-known NAT64 prefix to the NAT gateway (or Transit Gateway if that's what's specified in `egress`) in IPv6 clusters with private topology.
A future PR will need to provide this option for public topology, but we will might want an option in the cluster spec in case the user doesn't need NAT64 and thus doesn't want to pay for a NAT Gateway.
We might want to later provide option to route NAT64 differently than IPv4 egress.
> Route NAT64 to NAT Gateway in IPv6 private topology

- tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
- tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
- tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
- tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
This is most useful when nodes are in dual-stack subnets.
In IPv6-only subnets we will want to enable AWS's DNS64 on the subnet, but having it also enabled in CoreDNS will not hurt.
> Enable DNS64 in CoreDNS if IPv6 enabled

- k8s/crds/kops.k8s.io_clusters.yaml
- nodeup/pkg/model/docker_test.go
- pkg/apis/kops/dockerconfig.go
- pkg/apis/kops/v1alpha2/dockerconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
Cherry pick of #12789 on release-1.21.
#12789: Add support for --dns flag in Docker config
> Automated cherry pick of #12789: Add support for --dns flag in Docker config

- nodeup/pkg/model/BUILD.bazel
- nodeup/pkg/model/context.go
- upup/pkg/fi/nodeup/BUILD.bazel
- upup/pkg/fi/nodeup/command.go
Cloud Provider: AWS
This PR changes nodeups method of looking up an instance private DNS name from a DescribeInstances call to an instance metadata lookup. DescribeInstances is prone to throttling with large clusters and can cause significant delays when a node is trying to join a cluster.
> Use AWS metadata to retrieve local-hostname in nodeup

- tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
- tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
- upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
`AWS_EC2_ENDPOINT=https://api.ec2.us-east-1.aws` is broken as it overrides both EC2 and STS endpoint:
https://github.com/kubernetes/kops/pull/12843#issuecomment-980827347
The above is not needed with NAT64 and using `AWS_USE_DUALSTACK_ENDPOINT=true` needs more testing.
/cc @johngmyers @olemarkus @rifelpet
> Use NAT64 instead of dual-stack for AWS EBS CSI driver

- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/pollinterval/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
- pkg/model/openstackmodel/tests/servergroup/adds-additional-security-groups.yaml
- pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-ClusterSpec.yaml
- pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-InstanceGroupSpec.yaml
- pkg/model/openstackmodel/tests/servergroup/configures-server-group-affinity-with-annotations.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-auto-zone-distribution.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-external-router.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion-2.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-without-bastion-no-public-ip-association.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node.yaml
- pkg/model/openstackmodel/tests/servergroup/uses-instance-group-subnet-as-availability-zones-fallback.yaml
- pkg/model/openstackmodel/tests/servergroup/uses-instance-group-zones-as-availability-zones.yaml
- upup/pkg/fi/fitasks/keypair.go
/kind bug
`Keypair` was not reissuing client certificates when their issuer changed.
Fixes #12343.
> Reissue client keypairs on issuer change

- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/pollinterval/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
- pkg/model/openstackmodel/tests/servergroup/adds-additional-security-groups.yaml
- pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-ClusterSpec.yaml
- pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-InstanceGroupSpec.yaml
- pkg/model/openstackmodel/tests/servergroup/configures-server-group-affinity-with-annotations.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-auto-zone-distribution.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-external-router.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion-2.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-without-bastion-no-public-ip-association.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node.yaml
- pkg/model/openstackmodel/tests/servergroup/uses-instance-group-subnet-as-availability-zones-fallback.yaml
- pkg/model/openstackmodel/tests/servergroup/uses-instance-group-zones-as-availability-zones.yaml
- upup/pkg/fi/fitasks/keypair.go
Cherry pick of #12846 on release-1.22.
#12846: Reissue client keypairs on issuer change
> Automated cherry pick of #12846: Reissue client keypairs on issuer change

- docs/contributing/testing.md
- tests/e2e/kubetest2-kops/deployer/up.go
This reverts commit 064fd9215cb59baefb27a4e2fb7ff0dde18adcd2.
Breaks e2e tests of kOps 1.21 and before.
> Revert "Open nodeport to IPv6 in e2e tests"

- pkg/model/components/kubedns.go
- upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
The `dns64` plugin is not supported by node-cache, so I had to temporarily remove that from our template. I filed kubernetes/dns#489 to add the plugin.
IPv6 doesn't have unscoped link-local addresses, so I had to invent an ULA.
> Support NodeLocalDNS on IPv6 clusters

- tests/e2e/scenarios/aws-ebs-csi/run-test.sh
the linked issue's PR was merged into 1.22 so we'll see if we can stop skipping these tests
> Stop skipping snapshot fields tests in EBS CSI e2e

- tests/integration/update_cluster/ha_gce/data/aws_s3_bucket_object_ha-gce.example.com-addons-bootstrap_content
- tests/integration/update_cluster/ha_gce/data/aws_s3_bucket_object_ha-gce.example.com-addons-metadata-proxy.addons.k8s.io-v0.1.12_content
- tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_minimal-gce.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_minimal-gce.example.com-addons-metadata-proxy.addons.k8s.io-v0.1.12_content
- tests/integration/update_cluster/minimal_gce_private/data/aws_s3_bucket_object_minimal-gce-private.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal_gce_private/data/aws_s3_bucket_object_minimal-gce-private.example.com-addons-metadata-proxy.addons.k8s.io-v0.1.12_content
- upup/models/cloudup/resources/addons/metadata-proxy.addons.k8s.io/v0.1.12.yaml
Cilium doesn't seem to react well to a redirect to 127.0.0.1, but if
we redirect to an IP then it works well.  This should also work
with other CNI providers.
Similar to what upstream kubernetes does, we bind to 169.254.169.252.
Upstream: https://github.com/kubernetes/kubernetes/blob/108c284a330a82ce1a1f80238e4f54bf5e8b045a/cluster/gce/gci/configure-helper.sh#L181-L184
> GCE: fix for metadata-proxy on cilium

- upup/pkg/fi/cloudup/do/BUILD.bazel
- upup/pkg/fi/cloudup/do/cloud.go
- upup/pkg/fi/cloudup/dotasks/BUILD.bazel
- upup/pkg/fi/cloudup/dotasks/loadbalancer.go
The [e2e tests for Digital Ocean cloud provider](https://testgrid.k8s.io/sig-cluster-lifecycle-kops#e2e-kops-do-calico) was failing after this PR got merged - https://github.com/kubernetes/kops/pull/12624/files
With the above changes, kubetest2 was modified to do a create and then followed by an update with `--yes`. But the DO's load balancer logic didn't handle the create logic previously. It assumed that creation happens with `--yes`. So when the args wasn't passed, it kept waiting until the IP address is created, and eventually timesout.
The fix now only checks if loadbalancer IP is created during ingress status check which includes an exponential backoff retry logic. This gets triggered only when cluster creation is triggered.
FYI - @rifelpet @timoreimann
> [Digital Ocean] Fix load balancer retry logic while retrieving ip

- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
This PR updates `spotinst/ocean-controller` to v1.0.80.
> Spotinst: Update spotinst/ocean-controller to v1.0.80

- tests/e2e/kubetest2-kops/gce/gcs.go
Because we don't actually need to pass the project when deleting
objects (as it can be inferred from the bucket), the syntax for
passing it is a little different.
> tests gce: fix project arg on gsutil rm

- protokube/pkg/protokube/aws_volume.go
This code seems to only be used for gossip, but it is always run. This fixes IPv6 only networking
> If RBN, use IPv6 address instead of IPv4

- util/pkg/vfs/gsfs.go
- util/pkg/vfs/tests/BUILD.bazel
- util/pkg/vfs/tests/gsfs_test.go
- util/pkg/vfs/tests/mock_gcp_credentials.json
- util/pkg/vfs/tests/s3fs_test.go
This adds support for google storage objects rendered in Terraform.
I also added unit tests for both GS and S3. Ideally we could generate their HCL representations and save them to their own .tf files that could be checked by ./hack/verify-terraform.sh but our terraform target would require significant refactoring to be usable in isolated tests like this. Instead we just marshal the resources to JSON.
closes https://github.com/kubernetes/kops/issues/11929
WIP until I get around to testing a `terraform apply` with this.
> Support GSFS Terraform Managed Files

- pkg/resources/gce/BUILD.bazel
- pkg/resources/gce/gce.go
- pkg/resources/gce/network.go
- pkg/resources/gce/subnet.go
Now that we're better managing networks & subnets on GCE, we should
include them.
> gce: Add network & subnet to toolbox dump

- cmd/kops-controller/pkg/config/options.go
- cmd/kops-controller/pkg/server/server.go
- docs/releases/1.23-NOTES.md
- nodeup/pkg/model/kubelet.go
- pkg/apis/nodeup/config.go
- pkg/bootstrap/authenticate.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/awsup/aws_verifier.go
- upup/pkg/fi/cloudup/gce/tpm/gcetpmverifier/tpmverifier.go
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/nodeup/command.go
> Use instance ID as node name when AWS CCM supports it

- .github/workflows/main.yml
- WORKSPACE
Cherry pick of #12897 on release-1.21.
#12897: Update Go to v1.16.11
> Automated cherry pick of #12897: Update Go to v1.16.11

- pkg/model/awsmodel/api_loadbalancer.go
- tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
- tests/integration/update_cluster/existing_sg/kubernetes.tf
- tests/integration/update_cluster/externalpolicies/kubernetes.tf
- tests/integration/update_cluster/private-shared-ip/cloudformation.json
- tests/integration/update_cluster/private-shared-ip/kubernetes.tf
- tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
- tests/integration/update_cluster/privatecalico/cloudformation.json
- tests/integration/update_cluster/privatecalico/kubernetes.tf
- tests/integration/update_cluster/privatecanal/kubernetes.tf
- tests/integration/update_cluster/privatecilium/cloudformation.json
- tests/integration/update_cluster/privatecilium/kubernetes.tf
- tests/integration/update_cluster/privatecilium2/cloudformation.json
- tests/integration/update_cluster/privatecilium2/kubernetes.tf
- tests/integration/update_cluster/privateciliumadvanced/cloudformation.json
- tests/integration/update_cluster/privateciliumadvanced/kubernetes.tf
- tests/integration/update_cluster/privatedns1/kubernetes.tf
- tests/integration/update_cluster/privatedns2/kubernetes.tf
- tests/integration/update_cluster/privateflannel/kubernetes.tf
- tests/integration/update_cluster/privatekopeio/kubernetes.tf
- tests/integration/update_cluster/privateweave/kubernetes.tf
- tests/integration/update_cluster/unmanaged/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/classic_loadbalancer_attributes.go
This PR enables connection draining for aws classic LBs by default. 
Currently, kops doesn't enable connection draining and dropped connections can happen while cycling instanceGroups (master instanceGroups in particular).
> enable connection-draining for aws classic lb

- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/tests/containerdbuilder/flatcar/tasks.yaml
The containerd command used in
https://github.com/kubernetes/kops/pull/12177 is a modification from
the torcx containerd unit. However, how torcx starts containerd is a
implementation detail and it's better to not hardcode torcx in case it
isn't used anymore.
Change the ExecStard command to use /usr/bin/containerd directly,
making it simpler and more future-proof.
> Simplify Flatcar containerd exec command

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/dockerconfig.go
- pkg/apis/kops/v1alpha2/dockerconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha3/dockerconfig.go
- pkg/apis/kops/v1alpha3/zz_generated.conversion.go
- pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
YAML config options are maxConcurrentDownloads, maxConcurrentUploads, and maxDownloadAttempts.
Defaults are maxConcurrentDownloads=3, maxConcurrentUploads=5, and maxDownloadAttempts=5.
> pkg/apis/kops: Allow configuring dockerd --max-* upload and download concurrency and retry options.

- tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_minimal.example.com-addons-leader-migration.rbac.addons.k8s.io-k8s-1.23_content
- upup/models/cloudup/resources/addons/leader-migration.rbac.addons.k8s.io/k8s-1.23.yaml
/cc @johngmyers 
```
NAME					CURRENT	UPDATE									PKI
leader-migration.rbac.addons.k8s.io	-	28f51292768602b07c2a63edff29a60b818e7e79e5aa05fca48fac14c5f924ef	no
I1207 16:49:28.867828   14441 request.go:597] Waited for 198.301494ms due to client-side throttling, not priority and fairness, request: GET:https://127.0.0.1/api/v1/namespaces/kube-system
I1207 16:49:28.870601   14441 addon.go:170] Applying update from "s3://k8s-kops-prow/e2e-83f3478299-ead63.test-cncf-aws.k8s.io/addons/leader-migration.rbac.addons.k8s.io/k8s-1.23.yaml"
I1207 16:49:28.870638   14441 s3fs.go:329] Reading file "s3://k8s-kops-prow/e2e-83f3478299-ead63.test-cncf-aws.k8s.io/addons/leader-migration.rbac.addons.k8s.io/k8s-1.23.yaml"
I1207 16:49:29.033004   14441 apply.go:60] Running command: kubectl apply -f …
```
> Fix error applying AWS CCM leader migration

- tests/integration/update_cluster/external_dns/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/external_dns/data/aws_s3_bucket_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.19_content
- tests/integration/update_cluster/external_dns_irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
- tests/integration/update_cluster/external_dns_irsa/data/aws_s3_bucket_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.19_content
- upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/k8s-1.19.yaml.template
Cherry pick of #12893 on release-1.22.
#12893: Fix external-dns service name
> Automated cherry pick of #12893: Fix external-dns service name

- cloudmock/gce/mockcompute/BUILD.bazel
- cloudmock/gce/mockcompute/api.go
- cloudmock/gce/mockcompute/http_healthcheck.go
- pkg/resources/gce/gce.go
- upup/pkg/fi/cloudup/gce/compute.go
before
```
kops delete cluster jessegcp2.k8s.local
I1205 11:34:08.230365   66651 featureflag.go:164] FeatureFlag "AlphaAllowGCE"=true
I1205 11:34:08.251038   66651 s3context.go:89] Found S3_ENDPOINT="https://s3.eu-north-1.amazonaws.com", using as non-AWS S3 backend
I1205 11:34:08.457794   66651 gce_cloud.go:120] Will load GOOGLE_APPLICATION_CREDENTIALS from /Users/jessehaka/Downloads/sose-sre-5737-c707cbd8f8c9.json
I1205 11:34:09.046010   66651 gce.go:92] Scanning zones: [europe-north1-a europe-north1-b europe-north1-c]
TYPE			NAME							ID
Address			api-jessegcp2-k8s-local					api-jessegcp2-k8s-local
Disk			a-etcd-events-jessegcp2-k8s-local			a-etcd-events-jessegcp2-k8s-local
Disk			a-etcd-main-jessegcp2-k8s-local				a-etcd-main-jessegcp2-k8s-local
Disk …
```
> Cleanup GCE loadbalancers created by k8s

- tests/e2e/pkg/tester/tester.go
If we specify a zone to the e2e tests, it will try to pre-provision
volumes into it for the inline tests.  We then will be unable to
attach a volume to test pods if we don't have (normal) nodes in that
zone.
Pick a zone that is schedulable for test pods.
> e2e: fix test flakes where we specify a non-schedulable zone

- cloudmock/aws/mockiam/iaminstanceprofile.go
- upup/pkg/fi/cloudup/awstasks/iaminstanceprofile.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
Ref #12184
This has the unfortunate side-effect of constantly reporting tag additions to instance profiles in dryrun outputs of `kops update cluster` but they can be ignored.
/hold for manual testing
> Ignore InvalidAction errors when tagging IAM Instance Profiles
