kubernetes/kops

pkg/kubeconfig/create_kubecfg.go
pkg/kubeconfig/kubecfg_builder.go

Otherwise the password / key is used in preference to the auth plugin,
so these are used even if they have expired.

kops auth-plugin: need to clear any existing password / key

---

hack/verify-shellcheck.sh

Currently shell check will fail if one has a folder called for example `karpenter.sh`. This PR ensures we are only checking files.

Only shellcheck files

---

nodeup/pkg/model/bootstrap_client.go
nodeup/pkg/model/cloudconfig.go
nodeup/pkg/model/cloudconfig_test.go
nodeup/pkg/model/context.go
nodeup/pkg/model/kube_apiserver.go
nodeup/pkg/model/kubelet.go
nodeup/pkg/model/kubelet_test.go
nodeup/pkg/model/ntp.go
nodeup/pkg/model/protokube.go
nodeup/pkg/model/sysctls.go
nodeup/pkg/model/warm_pool.go
upup/pkg/fi/nodeup/command.go

This is a bit simpler than fetching it from the cluster every time, and also can allow things like mixed-cloud clusters (in future).

nodeup: store the CloudProvider in the context

---

Makefile

This makes the build much faster because we don't have to rebuild, and
was our intent anyway.
The binaries affected: kops-controller, dns-controller and kube-apiserver-healthcheck;
all of these should not have CGO dependencies.

bazel: always build with pure (CGO_ENABLED=0)

---

pkg/pki/privatekey.go
pkg/pki/privatekey_test.go

EC keys are much shorter (at a given security level); we should support them.

PKI library: Add initial support for EC keys

---

util/pkg/distributions/distributions.go

Debian bullseye also has the loopback resolv.conf that needs special
handling.

Recognize debian bullseye as having "broken" resolv.conf

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/dockerconfig.go
pkg/apis/kops/v1alpha2/dockerconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

Cherry pick of #12320 on release-1.22.
#12320: pkg/apis/kops: Allow configuring dockerd --max-* upload and

Automated cherry pick of #12320: pkg/apis/kops: Allow configuring dockerd --max-* upload and

---

docs/networking.md
docs/networking/weave.md
docs/releases/1.23-NOTES.md
pkg/apis/kops/validation/validation.go

Cherry pick of #12941 on release-1.23.
#12941: Remove support for Weave as of k8s 1.23

Automated cherry pick of #12941: Remove support for Weave as of k8s 1.23

---

docs/cluster_spec.md

Cluster spec settings to override the default resource request and limit values of CoreDNS . Currently not documented.
Reference:
- [coredns k8s-1.12.yaml.template](https://github.com/kubernetes/kops/blob/1c78abb288a06b5719e4750b63b7ef06c967de84/upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template#L156-L161)
- [cluster.go](https://github.com/kubernetes/kops/blob/1c78abb288a06b5719e4750b63b7ef06c967de84/pkg/apis/kops/v1alpha2/cluster.go#L476-L515)

Document CoreDNS configuration settings

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/networking.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/validation/validation.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #12918 on release-1.23.
#12918: Make service topology for cilium configurable
```release-note
```

Automated cherry pick of #12918: Make service topology for cilium configurable

---

cmd/kops/create_keypair.go
cmd/kops/distrust_keypair.go
cmd/kops/get_keypairs.go
cmd/kops/promote_keypair.go
docs/cli/kops_create_keypair.md
docs/cli/kops_distrust_keypair.md
docs/cli/kops_get_keypairs.md
docs/cli/kops_promote_keypair.md
docs/custom_ca.md

/kind documentation
Extracting the CA of an existing cluster is not a use case we support.
Closes #12910

Update name of kubernetes-ca keypair in documentation

---

util/pkg/distributions/distributions.go

Revert "Recognize debian bullseye as having "broken" resolv.conf"

---

cloudmock/aws/mockec2/launch_templates.go
upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go

Needed for Karpenter, which will always use the default version of a Launch Template.

Set the default LT version to the new LT version

---

.github/workflows/main.yml
WORKSPACE

Cherry pick of #12954 on release-1.23.
#12954: Update Go to v1.17.5

Automated cherry pick of #12954: Update Go to v1.17.5

---

.github/workflows/main.yml
WORKSPACE

Cherry pick of #12956 on release-1.21.
#12956: Update Go to v1.16.12

Automated cherry pick of #12956: Update Go to v1.16.12

---

tests/e2e/pkg/tester/skip_regex.go

Ref:
* https://github.com/kubernetes/kubernetes/pull/106992

Skip IPv6 LB test in the k/s e2e

---

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template

Upstream also have no tolerations on relay. Not sure how this got added.

Hubble relay should not tolerate anything

---

tests/e2e/pkg/tester/skip_regex.go

Should be covered by the `[Feature:.+` pattern now.
xRef: https://github.com/kubernetes/kubernetes/pull/80044
/cc @rifelpet

Do not explicitly skip Dashboard tests

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go

Now that we've enabled connection draining by default for all classic LBs (https://github.com/kubernetes/kops/pull/12881), we need to ensure that we're waiting for connectionDraining to complete before terminating the instance.
Deleting the instance without waiting doesn't allow for connections to drain. We need to call `DeregisterInstancesFromLoadBalancer` which will ensure that there aren't any ongoing connections to the instance before we terminate.
Gathering the corresponding loadBalancers by describing the underlying ASG.
Confirmed that rolling-updates continue to behave as expected and 0% of requests are dropped from corresponding load balancers.

wait for instances to drain from classic LB

---

pkg/model/components/containerd.go
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

Cherry pick of #12968 on release-1.23.
#12968: Update containerd to v1.6.0-beta.4

Automated cherry pick of #12968: Update containerd to v1.6.0-beta.4

---

upup/pkg/fi/cloudup/gcetasks/instance.go
upup/pkg/fi/cloudup/gcetasks/instancetemplate.go

Though it's currently an error to create an instance with more than
one serviceaccount, the GCE API and Terraform both support expressing
it in the model.  It's simpler to support the full model
expressiveness.

gce: map multiple serviceaccounts

---

pkg/model/BUILD.bazel
pkg/model/bootstrapscript.go
pkg/model/bootstrapscript_test.go
pkg/model/resources/BUILD.bazel
pkg/model/resources/nodeup.go
pkg/model/resources/nodeup_test.go
pkg/model/resources/template_resource.go

We had a tight coupling with the template, so we should move the variables into the same package.
Builds on #12991 
(The resources package could also be renamed to nodeupscript or similar, but that's a follow-on PR)

Refactor nodeup script to avoid action-at-a-distance

---

pkg/model/gcemodel/autoscalinggroup.go
pkg/model/gcemodel/context.go
pkg/model/gcemodel/service_accounts.go
pkg/model/gcemodel/storageacl.go
pkg/model/iam/BUILD.bazel
pkg/model/iam/types.go
pkg/truncate/BUILD.bazel
pkg/truncate/truncate.go
pkg/truncate/truncate_test.go
tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-a-ha-gce-example-com_metadata_startup-script
tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-b-ha-gce-example-com_metadata_startup-script
tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-c-ha-gce-example-com_metadata_startup-script
tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_nodes-ha-gce-example-com_metadata_startup-script
tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/data/google_compute_instance_template_master-us-test1-a-minimal-gce-private-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce_private/data/google_compute_instance_template_nodes-minimal-gce-private-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/awsup/BUILD.bazel
upup/pkg/fi/cloudup/awsup/aws_utils.go
upup/pkg/fi/cloudup/awsup/aws_utils_test.go
upup/pkg/fi/cloudup/gce/BUILD.bazel
upup/pkg/fi/cloudup/gce/utils.go
upup/pkg/fi/cloudup/gcetasks/projectiambinding.go
upup/pkg/fi/cloudup/new_cluster.go

We no longer set the cloudconfig serviceaccount on new clusters, and instead use a per-IG setting if this is not set.

gce: use per InstanceGroup serviceaccounts

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go

This flag determines which IPs are advertised inside the cluster, in
the "kubernetes" service in the "default" namespace.

componentconfig: expose advertise-address flag for kube-apiserver

---

upup/pkg/fi/cloudup/apply_cluster.go

WarmPools with amazonvpc just loops because nodeup never finish.
/kind bug

Ignore images hosted in private ECR repositories as containerd cannot pull these

---

upup/pkg/fi/cloudup/apply_cluster.go

Cherry pick of #13000 on release-1.23.
#13000: Ignore images hosted in private ECR repositories as
```release-note
```

Automated cherry pick of #13000: Ignore images hosted in private ECR repositories as

---

tests/e2e/pkg/tester/skip_regex.go

This should fix the failing tests: https://testgrid.k8s.io/kops-versions#Summary.
Ref: https://github.com/kubernetes/kops/pull/12974

Skip RuntimeClass tests for older Kubernetes versions

---

tests/e2e/kubetest2-kops/deployer/deployer.go
tests/e2e/kubetest2-kops/deployer/up.go

This allows us to disable IMDSv2 on flatcar tests

Add kubetest2-kops flags for overriding instance group fields

---

tests/e2e/pkg/tester/skip_regex.go

We checked explicitly for the .0 patch version. Tests started failing once .1 was released.

Skip SCTP check for all versions of k8s 1.23/1.24

---

nodeup/pkg/model/cloudconfig_test.go
nodeup/pkg/model/sysctls.go
nodeup/pkg/model/volumes.go

These pop up in VSCode and are pretty simple to fix:
```
nodeup/pkg/model/cloudconfig_test.go:86:17: possible nil pointer dereference (SA5011)
nodeup/pkg/model/cloudconfig_test.go:83:5: this check suggests that the pointer can be nil
nodeup/pkg/model/cloudconfig_test.go:155:17: possible nil pointer dereference (SA5011)
nodeup/pkg/model/cloudconfig_test.go:152:5: this check suggests that the pointer can be nil
nodeup/pkg/model/sysctls.go:172:12: error strings should not be capitalized (ST1005)
nodeup/pkg/model/sysctls.go:184:12: error strings should not be capitalized (ST1005)
nodeup/pkg/model/volumes.go:59:11: error strings should not be capitalized (ST1005)
```

staticcheck cleanup: fixup nodeup/pkg/model

---

pkg/apis/kops/validation/validation.go

If a user were to add a custom etcd cluster, kops will half-way create it before hitting various parts that fails on unknown etcd cluster names. At this point it is not possible to remove the etcd cluster again.

Prevent creation of unsupported etcd clusters

---

pkg/apis/kops/validation/validation.go

Cherry pick of #13011 on release-1.23.
#13011: Prevent creation of unsupported etcd clusters
```release-note
```

Automated cherry pick of #13011: Prevent creation of unsupported etcd clusters

---

tests/e2e/kubetest2-kops/deployer/up.go
tests/e2e/pkg/kops/state.go
tests/e2e/pkg/tester/tester.go

The GetInstanceGroup function was used in kubetest2-tester-kops which has the desired `kops` set in PATH and KOPS_STATE_STORE already set.
Now that we're using GetInstanceGroups in kubetest2-kops (the deployer) we need to override these to the values that the deployer determines.
This should this empty error in the flatcar jobs now that we override their instance groups to disable IMDSv2: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-distro-imageflatcar/1472938989487919104#1:build-log.txt%3A666
`W1220 14:38:09.103159    4731 state.go:63] failed to run kops get instancegroups --name e2e-b5f84bd12b-91d99.test-cncf-aws.k8s.io -ojson; stderr=`

kubetest2 - Use the same binary path and env when fetching IGs

---

pkg/model/bootstrapscript.go
pkg/model/bootstrapscript_test.go
pkg/model/openstackmodel/servergroup_test.go
upup/pkg/fi/ca.go
upup/pkg/fi/cloudup/BUILD.bazel
upup/pkg/fi/cloudup/apply_cluster.go

Using a task leads to layering complexity.  We could introduce a new type, but fi.Keyset is the type we seem to want.
(We could move Keyset out of fi, but we don't need to yet)

Use fi.Keyset instead of passing tasks around

---

go.mod
upup/pkg/fi/cloudup/awsup/BUILD.bazel
upup/pkg/fi/cloudup/awsup/aws_cloud.go

This builds on https://github.com/kubernetes/kops/pull/12902 to add graceful connection draining for associated targetGroups.
Today, one can define `targetGroupArns` in an instanceGroup spec to associate instances in a corresponding instanceGroup with. When instances in the instanceGroup are cycled via rolling-updates, those instances aren't first properly deregistered with the corresponding `targetGroupArns`, causing dropped connections. 
This PR fixes this issue by ensuring that we're properly draining instances from their corresponding classic load balancers and NLB targetGroups before terminating the instance. This is a big improvement to the overall client experience when running rolling-updates on production clusters.

add instance connection draining for NLBs

---

cloudmock/aws/mockec2/BUILD.bazel
cloudmock/aws/mockec2/eni.go
pkg/resources/aws/BUILD.bazel
pkg/resources/aws/aws.go
pkg/resources/aws/eni.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/pkg/fi/cloudup/template_functions.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

This should fix future dangling ENIs from AWS VPC CNI should it occur in the future.
Cilium already tags its ENIs so should the same problem happen there, this should fix that as well.

Fix dangling ENIs from AWS VPC CNI 

---

cmd/kops/create_cluster.go
cmd/kops/create_cluster_integration_test.go
tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
tests/integration/create_cluster/karpenter/options.yaml
tests/integration/update_cluster/karpenter/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_bucket_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template
upup/pkg/fi/cloudup/new_cluster.go

This PR adds a flag `--instance-manager` if the karpenter feature flag is enabled. This flag will create one single karpenter IG instead of per-AZ ASG IGs.
This will allow us to easily test karpenter-only clusters, and give users an easy way of testing karpenter.
At the moment, this PR also includes various other fixes as well required for Karpenter to work.

Add a CLI flag for creating one karpenter-managed IG for worker nodes instead of ASG-managed ones

---

nodeup/pkg/model/kube_apiserver.go
nodeup/pkg/model/kube_controller_manager.go
nodeup/pkg/model/kube_proxy.go
nodeup/pkg/model/kube_scheduler.go
nodeup/pkg/model/tests/golden/minimal/tasks-kube-apiserver.yaml
nodeup/pkg/model/tests/golden/minimal/tasks-kube-controller-manager.yaml
nodeup/pkg/model/tests/golden/minimal/tasks-kube-proxy.yaml
nodeup/pkg/model/tests/golden/minimal/tasks-kube-scheduler.yaml

When we moved to go-runner, we stopped getting logs on stdout. This adds stdout logging back in again so we can do `kubectl logs`

Kube components log to stdout

---

pkg/nodeidentity/aws/identify.go

Since karpenter creates the node object immediately after ec2.RunInstance return, the instance is likely in Pending state when kops-controller first tries to identify. By allowing Pending instances to be identified, we avoid some DescribeInstance churn.

Identify pending instances

---

nodeup/pkg/model/kube_proxy.go
nodeup/pkg/model/tests/golden/minimal/tasks-kube-proxy.yaml
nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-amd64.yaml
nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-arm64.yaml

In order to do #6527 gracefully we add a label to the static version of the kube-proxy manifest. By then adding an podAntiAffinity on this label in the addon-version of kube-proxy, we do not end up with multiple kube-proxies on a host.

Add managed-by label to static kube-proxy pods

---

tests/integration/update_cluster/karpenter/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_bucket_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template

The default name Karpenter/knative is using has a high chance of colliding with something else. This PR adds a prefix to it and configures karpenter accordingly.

Prefix karpenter logging-config name

---

nodeup/pkg/model/kube_proxy.go
nodeup/pkg/model/tests/golden/minimal/tasks-kube-proxy.yaml
nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-amd64.yaml
nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-arm64.yaml

Cherry pick of #13039 on release-1.23.
#13039: Add managed-by label to static kube-proxy pods
```release-note
```

Automated cherry pick of #13039: Add managed-by label to static kube-proxy pods

---

nodeup/pkg/model/kube_apiserver.go
nodeup/pkg/model/kube_controller_manager.go
nodeup/pkg/model/kube_proxy.go
nodeup/pkg/model/kube_scheduler.go
nodeup/pkg/model/tests/golden/minimal/tasks-kube-apiserver.yaml
nodeup/pkg/model/tests/golden/minimal/tasks-kube-controller-manager.yaml
nodeup/pkg/model/tests/golden/minimal/tasks-kube-proxy.yaml
nodeup/pkg/model/tests/golden/minimal/tasks-kube-scheduler.yaml

Cherry pick of #13038 on release-1.23.
#13038: Kube components log to stdout
```release-note
```

Automated cherry pick of #13038: Kube components log to stdout

---

pkg/model/gcemodel/storageacl.go

If we're using a cluster-level service-account, we shouldn't try to
set bucket permissions on a per-IG level.
For compatibility with the existing behavior, we simply don't set any
permissions in this case.

gce: don't set per-IG permissions when using shared account

---

pkg/model/components/BUILD.bazel
pkg/model/components/gcpcloudcontrollermanager.go
upup/models/BUILD.bazel
upup/models/cloudup/resources/addons/gcp-cloud-controller.addons.k8s.io/k8s-1.23.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/populate_cluster_spec.go

Cherry pick of #13017 on release-1.23.
#13017: external CCM for GCE

Automated cherry pick of #13017: external CCM for GCE

---

upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
upup/pkg/fi/cloudup/openstacktasks/lblistener.go
upup/pkg/fi/cloudup/openstacktasks/securitygrouprule.go

When creating security group rule, the default EtherType is IPv4.
Currently, AdminAccess default includes IPv6 CIDR, in this case
EtherType should be changed to IPv6.
Similar issue also happens with load balancer creation as the VIP is
IPv4.
This commit fixed this issue by checking if the CIDR is IPv6 before
creating the rule, if it is, EtherType will be changed to IPv6. When
creating load balancer, if allowed CIDR doesn't match VIP type, remove
it from the list.
Fixes: #12980

Fix OpenStack SecurityGroupRule/LB When CIDR is IPv6

---

upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
upup/pkg/fi/cloudup/openstacktasks/lblistener.go
upup/pkg/fi/cloudup/openstacktasks/securitygrouprule.go

Cherry pick of #13032 on release-1.23.
#13032: Fix OpenStack SecurityGroupRule/LB with IPv6 CIDR
```release-note
```

Automated cherry pick of #13032: Fix OpenStack SecurityGroupRule/LB with IPv6 CIDR

---

pkg/model/components/clusterautoscaler.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template

Cherry pick of #13050 on release-1.23.
#13050: Bump Cluster Autoscaler and update manifest
```release-note
```

Automated cherry pick of #13050: Bump Cluster Autoscaler and update manifest

---

docs/releases/1.23-NOTES.md
pkg/apis/kops/install/BUILD.bazel
pkg/apis/kops/install/install.go
tests/codecs/BUILD.bazel
tests/codecs/componentconfig_test.go
tests/integration/conversion/integration_test.go

There is no reason to release this work in progress with 1.23.

Remove the v1alpha3 API version

---

cloudmock/aws/mockec2/instances.go
cmd/kops/integration_test.go
pkg/model/awsmodel/autoscalinggroup.go
tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
tests/integration/update_cluster/karpenter/data/aws_launch_template_karpenter-nodes-default.minimal.example.com_user_data
tests/integration/update_cluster/karpenter/data/aws_launch_template_karpenter-nodes-single-machinetype.minimal.example.com_user_data
tests/integration/update_cluster/karpenter/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_bucket_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
tests/integration/update_cluster/karpenter/data/aws_s3_bucket_object_nodeupconfig-karpenter-nodes-default_content
tests/integration/update_cluster/karpenter/data/aws_s3_bucket_object_nodeupconfig-karpenter-nodes-single-machinetype_content
tests/integration/update_cluster/karpenter/in-v1alpha2.yaml
tests/integration/update_cluster/karpenter/kubernetes.tf
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template
upup/pkg/fi/cloudup/BUILD.bazel
upup/pkg/fi/cloudup/awstasks/helper.go
upup/pkg/fi/cloudup/awstasks/launchtemplate.go
upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
upup/pkg/fi/cloudup/new_cluster.go
upup/pkg/fi/cloudup/populate_instancegroup_spec.go
upup/pkg/fi/cloudup/template_functions.go
upup/pkg/fi/cloudup/template_functions_test.go

This PR uses the getInstanceTypesFromInstanceRequirements API to add appropriate instance types to the Karpenter providers. This adds the flexibility one expects from using Karpenter without having to maintain ones own lists of instance types, and also allows us to ensure we have valid combinations of instance types (e.g not combining arm and amd).

Use instance requirements with Karpenter

---

.github/workflows/tag-release.yml
hack/tag-release.sh

Tested in the johngmyers/testactions repository.
Will tag an alpha to verify before removing the restriction to alpha. Then will backport script to release branches before enabling there.

Add action for automatically tagging releases

---

.github/workflows/tag-release.yml
hack/tag-release.sh

Cherry pick of #12805 #13071 on release-1.23.
#12805: Add action for automatically tagging releases
#13071: Remove temporary restrictions on automatically tagging

Automated cherry pick of #12805: Add action for automatically tagging releases #13071: Remove temporary restrictions on automatically tagging

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
upup/models/cloudup/resources/addons/snapshot-controller.addons.k8s.io/k8s-1.20.yaml.template

Cherry pick of #13067 on release-1.23.
#13067: Bump external-snapshotted to v5.0.0
```release-note
```

Automated cherry pick of #13067: Bump external-snapshotted to v5.0.0

---

cloudmock/gce/mock_gce_cloud.go
pkg/instancegroups/instancegroups.go
pkg/kubeconfig/create_kubecfg_test.go
pkg/model/openstackmodel/servergroup.go
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
upup/pkg/fi/cloud.go
upup/pkg/fi/cloudup/awsup/aws_cloud.go
upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
upup/pkg/fi/cloudup/azure/azure_cloud.go
upup/pkg/fi/cloudup/azuretasks/testing.go
upup/pkg/fi/cloudup/do/cloud.go
upup/pkg/fi/cloudup/do/mock_do_cloud.go
upup/pkg/fi/cloudup/gce/instancegroups.go
upup/pkg/fi/cloudup/openstack/BUILD.bazel
upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstack/instance.go
upup/pkg/fi/cloudup/openstack/loadbalancer.go
upup/pkg/fi/cloudup/openstack/mock_cloud.go
upup/pkg/fi/cloudup/openstacktasks/poolassociation.go

Why OpenStack cannot use current structure at all if we want drain connections? Delete kubernetes node is executed before delete instance https://github.com/kubernetes/kops/blob/master/pkg/instancegroups/instancegroups.go#L418 in OpenStack cloudprovider this means that when node is deleted, it will automatically remove all loadbalancer members -> we cannot drain anything anymore.
Now when we add `DeregisterInstance` function to clouds, we have way to execute things BEFORE node is deleted from Kubernetes. By using this we should be able to do real draining in all clouds including for instance google cloud. AWS works in little bit different way than others (it keeps terminated instances in API lists for sometime).
I also was thinking could we use …

Drain OpenStack loadbalancers

---

upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template

This PR updates `spotinst/ocean-controller` to v1.0.81.

Spotinst: Update `spotinst/ocean-controller` to v1.0.81

---

docs/addons.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/validation/validation.go

This PR adds support for both of the remaining cluster-autoscaler expanders kops doesn't currently support. The `price` expander requires no additional configuration. The `priority` expander requires configuration in a separate ConfigMap, so I've added notes to the docs to that effect.

Support price and priority cluster-autoscaler expanders

---

docs/addons.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/validation/validation.go

Cherry pick of #13081 on release-1.23.
#13081: Support price and priority cluster-autoscaler expanders.
```release-note
```

Automated cherry pick of #13081: Support price and priority cluster-autoscaler expanders.

---

upup/pkg/fi/cloudup/new_cluster.go

old default values were pretty high - it took 3 minutes to get failing node dropped from the load. Now it takes about 45 seconds with new default settings which is much better.
note! this does not affect existing loadbalancers in clusters, it will affect only new loadbalancers that are created by kubernetes. The value can be overriden in kOps configuration

decrease the openstack monitoring default timeout

---

cmd/kops/get_instances.go

Cherry pick of #13106 on release-1.22.
#13106: Don't try to add node name to instances without node object
```release-note
```

Automated cherry pick of #13106: Don't try to add node name to instances without node object

---

pkg/model/openstackmodel/BUILD.bazel
pkg/model/openstackmodel/firewall.go
pkg/model/openstackmodel/servergroup.go
upup/pkg/fi/cloudup/openstacktasks/lblistener.go

seems that https://github.com/kubernetes/kops/pull/13032 is not working correctly when updating the existing cluster. It do solves the problem that cluster can be created from the scratch, but updating existing clusters does not work at all.
This PR is modifying security groups working correctly. However, there is no easy way to make api loadbalancer to support ipv6 addresses like this. It needs more investigation how that can be done. I am pretty sure that none is using ipv6 api loadbalancer because it has not been supported by kOps
cc @iGene

fix ipv4+ipv6 sec groups/listeners in OpenStack

---

pkg/model/openstackmodel/BUILD.bazel
pkg/model/openstackmodel/firewall.go
pkg/model/openstackmodel/servergroup.go
upup/pkg/fi/cloudup/openstacktasks/lblistener.go

Cherry pick of #13093 on release-1.23.
#13093: fix ipv4+ipv6 sec groups/listeners in OpenStack

Automated cherry pick of #13093: fix ipv4+ipv6 sec groups/listeners in OpenStack

---

docs/networking/ipv6.md
pkg/apis/kops/cluster.go
pkg/apis/kops/validation/validation.go
pkg/apis/kops/validation/validation_test.go
pkg/model/awsmodel/api_loadbalancer.go
pkg/model/awsmodel/autoscalinggroup.go
pkg/model/awsmodel/bastion.go
pkg/model/awsmodel/network.go
pkg/model/awsmodel/spotinst.go
pkg/model/azuremodel/api_loadbalancer.go
pkg/model/azuremodel/vmscaleset.go
pkg/model/gcemodel/network.go
pkg/model/openstackmodel/servergroup.go
pkg/testutils/cluster.go
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-private/in-v1alpha2.yaml
tests/integration/update_cluster/minimal-ipv6-private/kubernetes.tf
upup/pkg/fi/cloudup/deepvalidate_test.go
upup/pkg/fi/cloudup/new_cluster.go
upup/pkg/fi/cloudup/populate_cluster_spec_test.go
upup/pkg/fi/cloudup/populate_instancegroup_spec.go
upup/pkg/fi/cloudup/subnets.go
upup/pkg/fi/cloudup/subnets_test.go

One alternative would be to omit creating dualstack subnets in zones that don't have control plane nodes when there are no apiserver nodes.
/cc @olemarkus @hakman 
Closes #12886

Use IPv6-only subnets for worker nodes in private IPv6 topology

---

pkg/model/components/kubelet.go
pkg/model/components/networking.go
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content

K/k master is currently failing because the network plugin flags et.al got removed.

Remove networking flags as of k8s 1.24

---

cmd/kops/create_cluster.go
cmd/kops/integration_test.go
docs/cli/kops_create_cluster.md
pkg/featureflag/featureflag.go

Makes it easier for operators to create IPv6 clusters, which and should be pretty good already in 1.23.

Remove featureflag for creating IPv6 clusters

---

channels/pkg/channels/addon.go
channels/pkg/channels/addons_test.go
channels/pkg/channels/channel_version.go
channels/pkg/cmd/BUILD.bazel
channels/pkg/cmd/apply_channel.go
channels/pkg/cmd/apply_channel_test.go
channels/pkg/cmd/get_addons.go

Channels is a bit spammy towards the k8s API. This will reduce some of the spam by not loading all namespaces multiple times per installed addon.

Preload channel versions from namespaces

---

pkg/model/components/awscloudcontrollermanager.go

Cherry pick of #13143 on release-1.22.
#13143: Bump CCM images

Automated cherry pick of #13143: Bump CCM images

---

pkg/apis/kops/v1alpha2/defaults.go
pkg/apis/kops/v1alpha3/defaults.go
tests/integration/update_cluster/minimal/cloudformation.json.extracted.yaml
tests/integration/update_cluster/minimal/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal/in-v1alpha2.yaml

Cherry pick of #13111 on release-1.23.
#13111: No need to set kubelet in tests
```release-note
```

Automated cherry pick of #13111: No need to set kubelet in tests

---

channels/stable
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.23/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

https://ubuntu.com/security/CVE-2022-0185

Promote alpha AMIs to stable

---

go.mod
go.sum
tests/e2e/go.sum
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
vendor/modules.txt

Should anyone be curious why I am not bumping to 1.7.0, it is because 1.7.0 removes the code for parsing earlier CRD versions meaning if any certificate stored in etcd with those older versions, they will be gone. Want to see how this plays out before forcing our users onto something like that. Many probably migrated from very old self-managed cert managers and then migrated to our addon.

Bump cert-manager and related godep to 1.6.2

---

cmd/kops/rolling-update_cluster.go
docs/cli/kops_rolling-update_cluster.md
docs/releases/1.23-NOTES.md
pkg/instancegroups/instancegroups.go
pkg/instancegroups/rollingupdate.go

sets default eviction timeout to 15minutes. Previously, rolling-updates would retry infinitely when failing to drain a given node.
We can now properly rely on `--fail-on-drain-error=false/true` in the event that it takes longer than 15 minutes to drain a node. 
Additionally, expose a new `--drain-timeout` flag to configure the max drain timeout if needed.
I decided to name the flag `drain-timeout` to be consistent with the naming conventions of other flags. Specifically, `drain-timeout` aligns with flags:
- `validation-timeout`
- `fail-on-drain-error`
- `post-drain-delay`

add node-drain-timeout flag to rolling-update

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go

aws.BackgroundContext was intended for go 1.6 and earlier.

Replace deprecated aws.BackgroundContext with context.Background

---

upup/pkg/fi/cloudup/template_functions.go

Unlikely to happen outside of tests, but an easy fix.

Fix nil pointer when IAM not populated

---

tests/integration/update_cluster/aws-lb-controller/kubernetes.tf
tests/integration/update_cluster/digit/kubernetes.tf
tests/integration/update_cluster/external_dns_irsa/kubernetes.tf
tests/integration/update_cluster/irsa/kubernetes.tf
tests/integration/update_cluster/many-addons-ccm-irsa/kubernetes.tf
tests/integration/update_cluster/minimal_gossip_irsa/kubernetes.tf
tests/integration/update_cluster/public-jwks-apiserver/kubernetes.tf
tests/integration/update_cluster/vfs-said/kubernetes.tf
upup/pkg/fi/fitasks/managedfile.go

Cherry pick of #13166 on release-1.23.
#13166: JWKS / IRSA: Expose public ACLs to terraform

Automated cherry pick of #13166: JWKS / IRSA: Expose public ACLs to terraform

---

tests/integration/update_cluster/aws-lb-controller/kubernetes.tf
tests/integration/update_cluster/digit/kubernetes.tf
tests/integration/update_cluster/external_dns_irsa/kubernetes.tf
tests/integration/update_cluster/irsa/kubernetes.tf
tests/integration/update_cluster/karpenter/kubernetes.tf
tests/integration/update_cluster/many-addons-ccm-irsa/kubernetes.tf
tests/integration/update_cluster/many-addons-ccm-irsa23/kubernetes.tf
tests/integration/update_cluster/minimal_gossip_irsa/kubernetes.tf
tests/integration/update_cluster/public-jwks-apiserver/kubernetes.tf
tests/integration/update_cluster/vfs-said/kubernetes.tf
upup/pkg/fi/fitasks/managedfile.go

Otherwise terraform wasn't correctly / consistently exposing these
files for JWKS/IRSA/OIDC.

JWKS / IRSA: Expose public ACLs to terraform

---

cmd/kops/rolling-update_cluster.go
docs/cli/kops_rolling-update_cluster.md
docs/releases/1.23-NOTES.md
pkg/instancegroups/instancegroups.go
pkg/instancegroups/rollingupdate.go

Cherry pick of #13103 on release-1.23.
#13103: add drain-timeout flag to rolling-update cluster
```release-note
```

Automated cherry pick of #13103: add drain-timeout flag to rolling-update cluster

---

tests/e2e/kubetest2-kops/deployer/template.go

The error looks like:
```
Error: error reading public key file: "open : no such file or directory"
```
instead of:
```
Error: open : no such file or directory
```

More descriptive error message when public key file can't be opened

---

tests/integration/update_cluster/ha_gce/data/aws_s3_bucket_object_ha-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/ha_gce/data/aws_s3_bucket_object_ha-gce.example.com-addons-metadata-proxy.addons.k8s.io-v0.1.12_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_minimal-gce.example.com-addons-metadata-proxy.addons.k8s.io-v0.1.12_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_bucket_object_minimal-gce-private.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_bucket_object_minimal-gce-private.example.com-addons-metadata-proxy.addons.k8s.io-v0.1.12_content
upup/models/cloudup/resources/addons/metadata-proxy.addons.k8s.io/v0.1.12.yaml

This is more correct anyway, but also ensures it will be rewritten
correctly by mirroring.
Only used on GCE.

Pull k8s-custom-iptables from k8s.gcr.io

---

tests/e2e/kubetest2-kops/deployer/build.go
tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/scenarios/upgrade-ab/run-test.sh

We need to get some version -> branch e2e testing in place. This should let us create upgrade tests that starts with a version and ends with a branch CI marker.

Add support for AB tests starting out with released kops version

---

upup/pkg/fi/fitasks/managedfile.go
util/pkg/vfs/memfs.go

They weren't fully wired up previously

tests: ensure that we use ACLs with memfs

---

pkg/model/components/containerd.go
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

Cherry pick of #13198 on release-1.23.
#13198: Update containerd to v1.6.0-rc.2

Automated cherry pick of #13198: Update containerd to v1.6.0-rc.2

---

tests/integration/update_cluster/karpenter/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_bucket_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template

A fix for shared subnets (they don't have the KubernetesCluster tag) and for quoting "true" in yaml.

Karpenter fixes

---

pkg/model/components/awscloudcontrollermanager.go
pkg/model/components/gcpcloudcontrollermanager.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_cluster-completed.spec_content

... for aws & gcp cloud-controller-manager.
/kind feature
There is no significant downside. Plus, it is required for replicating the controller plane
Note that we already force leader election to be enabled for KCM.

Always enable Leader Election for cloud-controller-manager

---

tests/e2e/kubetest2-kops/deployer/build.go

motivation for this is that I can remotely figure out the KOPS_BASE_URL to test a PR without having to locally fetch the branch and run `git describe` myself. With this change, I can just fetch the hash from the GH API.

Use short commit sha for default stage location instead of git-describe

---

upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #13136 on release-1.23.
#13136: use 1.23.1 ccm for openstack

Automated cherry pick of #13136: use 1.23.1 ccm for openstack

---

upup/pkg/fi/cloudup/template_functions.go

There are two known issues currently in 1.23.0 ccm
- https://github.com/kubernetes/cloud-provider-openstack/pull/1750
- https://github.com/kubernetes/cloud-provider-openstack/pull/1755
these will be (hopefully) cherry-picked to release-1.23 and we will get new patch release.
This PR can be merged if we can see the patch release to be released.
/hold

use 1.23.1 ccm for openstack

---

pkg/model/components/kubecontrollermanager.go

The LogLevel was forced to be 2, which can be painful for troubleshooting. Changed to make it default to 2 but the value will be honored if set.
Downside is that there is no way to disable logging by setting `-v=0`. However muting logging should be rarely used.

fix KCM LogLevel setting not honored

---

pkg/apis/kops/validation/validation.go

Cherry pick of #13213 on release-1.22.
#13213: Remove snapshot controller dependency on ebs csi driver
```release-note
```

Automated cherry pick of #13213: Remove snapshot controller dependency on ebs csi driver

---

cmd/kops/upgrade_cluster.go

Solves #13171 for v1.22
Not needed in v1.23, since instance types for spotinst are moved to `mixedInstancesPolicy`: #12549

upgrade cluster: support comma separated list for machineType [1.22]

---

cmd/kops/upgrade_cluster.go

Solves #13171 for v1.21
Not needed in v1.23, since instance types for spotinst are moved to `mixedInstancesPolicy`: #12549

upgrade cluster: support comma separated list for machineType [1.21]

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
upup/pkg/fi/cloudup/BUILD.bazel
upup/pkg/fi/cloudup/template_functions.go
upup/pkg/fi/cloudup/template_functions_test.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/aws-cloud-controller.addons.k8s.io-k8s-1.18.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml

Because CCM did not use flagbuilder, flags defined in the configuration were not applied. Rewrite the argv building to use standard approach.  Also reorder flags in tests, and add tests for other flags.
/kind feature

CCM: use flagbuilder instead of manually building argv

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
upup/models/cloudup/resources/addons/snapshot-controller.addons.k8s.io/k8s-1.20.yaml.template

Cherry pick of #12874 on release-1.22.
#12874: Use v1 certificate for snapshot-validation-service
```release-note
```

Automated cherry pick of #12874: Use v1 certificate for snapshot-validation-service

---

pkg/model/components/containerd.go
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

Cherry pick of #13224 on release-1.23.
#13224: Update containerd to v1.6.0-rc.3

Automated cherry pick of #13224: Update containerd to v1.6.0-rc.3

---

channels/stable
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.23/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

Kubernetes versions were bumped 3 weeks ago in Alpha, and Ubuntu AMI was bumped a week ago. Seems safe to promote.

Promote alpha to stable

---

pkg/model/components/openstack.go

Leader Election is a must-have for replicated/HA control plane.
Kind of scary to think of current HA clusters running without leader election.
Needs https://github.com/kubernetes/kops/pull/13219 to be merged first.

always enable Leader Election for openstack CCM

---

pkg/model/components/openstack.go

Cherry pick of #13220 on release-1.23.
#13220: always enable Leader Election

Automated cherry pick of #13220: always enable Leader Election

---

cmd/kops/create_cluster.go
cmd/kops/create_instancegroup.go
cmd/kops/get.go
cmd/kops/get_cluster.go
cmd/kops/get_instancegroups.go
cmd/kops/toolbox_instance-selector.go
docs/releases/1.23-NOTES.md

A minor fix, tested and works as expected.
For a single cluster you would still return an array as seen below.
```
./kops get clusters -o json | jq .
[
{
"kind": "Cluster",
"apiVersion": "kops.k8s.io/v1alpha2",
"metadata": {
"name": "dev***ds.co.in",
"creationTimestamp": "2022-02-01T14:17:41Z"
},
"spec": {
"channel": "stable",
"configBase": "do://sri-k***e/de****ds.co.in",
"cloudProvider": "digitalocean",
"kubernetesVersion": "1.22.5",
"subnets": [
{
"name": "tor1",
"zone": "tor1",
"region": "tor1",
"type": "Public"
}
],
"masterPublicName": "ap*****.co.in",
"topology": {
"masters": "public",
"nodes": "public",
"dns": {
"type": "Public"
}
},
"nonMasqueradeCIDR": "100.64.0.0/10",
"sshAccess": [
"0.0.0.0/0",
"::/0"
],
"kubernetesApiAccess": [
"0.0.0.0/0",
"::/0"
],
"etcdClusters": [
{ …
```

[Issue-12293] Fix json output to keep it consistent for single or multiple objects

---

upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

This will allow pruning CCM addon during a rollback. 
This PR is part of the Leader Migration upgrade/rollback test.

enable pruning for CCM

---

tests/e2e/scenarios/lib/common.sh

`kubetest2 kops` require a gcp project even for `--build`, which is not true for other providers. This PR allows setting the project manually (instead of borrowing from boskos) to allow easier local development.

allow specify GCP project via env.

---

pkg/model/components/kubecontrollermanager.go
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content

AWS CCM is enabled by default in k8s 1.24, and KCM builder is now aware of that and will not enabled leader migration.
Fixes #12723
(again)

KCM should not run with leader migraton when aws ccm is enabled

---

nodeup/pkg/model/kubelet.go

Fix nilpointer when graceful shutdown is not configured

---

nodeup/pkg/model/containerd.go
nodeup/pkg/model/containerd_test.go
nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml
pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

In the past, it made sense to use the bundle package to install contained, as it contained a compatible `runc` binary.
Since #13240, we ca switch to using the release package instead and reduce the download size from 130MB to 43MB.

Install contained from the release package 

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
upup/pkg/fi/cloudup/template_functions_test.go

This PR enables the `Controllers` field for CCM, just like KCM.
Currently, it is possible to set the `--controllers` flag via the config for kube-controller-manager, but not `cloud-controller-manager`. However, being able to enable/disable some controllers for CCM is as important as that for KCM, if not more so. This is because for the same cloud provider, the cloud environment may have significant variation, for example, hosted Kubernetes, self-deployed Kubernetes, third-party hosted Kubernetes for the same cloud. The added flexibility of CCM config would help such use cases.

CCM: allow setting Controllers for cloudControllerManagerConfig

---

upup/models/cloudup/resources/addons/gcp-cloud-controller.addons.k8s.io/k8s-1.23.yaml.template

Our CCM addons are missing `livenessProbe`. This PR adds the probe to GCP CCM. Other cloud providers should do the same.

CCM: add livenessProbe for GCP CCM

---

tests/e2e/go.mod
tests/e2e/go.sum
tests/e2e/scenarios/upgrade-ha-leader-migration/cmd/recorder/main.go
tests/e2e/scenarios/upgrade-ha-leader-migration/cmd/recorder/recorder.go
tests/e2e/scenarios/upgrade-ha-leader-migration/resources.yaml
tests/e2e/scenarios/upgrade-ha-leader-migration/run-test.sh

This PR adds a new scenario that
- create a 1.23 cluster with 3 control plane nodes
- upgrade and rolling-upgrade the control plane to 1.24, performing Leader Migration between 1.23 KCM to 1.24 CCM
- rollback and rolling-upgrade the control plane back to 1.23, performing Leader Migration between 1.23 KCM to 1.24 CCM
This PR implements a controller-to-manager recorder with `client-go` that runs in the cluster, because connections from the 
test host to the cluster may be interrupted during the rolling-upgrade. Also, this is a good way to ensure the data plane is not disturbed during the control plane upgrade.
This test also uses (and thus covers) per-controller health-check implemented as https://github.com/kubernetes/kubernetes/pull/104667
This PR is designed to run as a periodic job in …

E2E HA Upgrade/Rollback for Leader Migration

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Version 1.10.2 was released 4 days ago - https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.10.2

Bump AWS CNI to 1.10.2

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Cherry pick of #13228 on release-1.23.
#13228: Bump aws-cni to 1.10.2

Automated cherry pick of #13228: Bump aws-cni to 1.10.2

---

docs/networking/ipv6.md

Ref: https://testgrid.k8s.io/kops-ipv6#kops-aws-cni-calico-ipv6-u2204

Update supported distros for IPv6

---

tests/e2e/scenarios/upgrade-ha-leader-migration/run-test.sh

see https://github.com/kubernetes/test-infra/pull/24755
This flag is unfortunately needed for all tests on GCE.

service account workaround for gce

---

pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go
upup/pkg/fi/cloudup/runc.go

Cherry pick of #13262 on release-1.23.
#13262: Update containerd to v1.6.0

Automated cherry pick of #13262: Update containerd to v1.6.0

---

tests/e2e/scenarios/lib/common.sh
tests/e2e/scenarios/upgrade-ha-leader-migration/run-test.sh
tests/e2e/scenarios/upgrade-ha-leader-migration/test-leader-migration.sh

There was a flaw in my approach to run the test - the test needs kubetest2 to setup environment, and thus needs to be invoked by kubetest2. Fortunately we can easily do that with `kubetest2-tester-exec`.
This PR re-organizes Leader Migration test in this way.

re-organize Leader Migration test with exec tester

---

cmd/kops/integration_test.go
pkg/apis/kops/validation/validation.go
tests/e2e/scenarios/aws-lb-controller/run-test.sh
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/kubernetes.tf
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/kubernetes.tf
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_iam_role_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/in-v1alpha2.yaml
tests/integration/update_cluster/many-addons-ccm-irsa23/kubernetes.tf
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/kubernetes.tf
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/kubernetes.tf
upup/models/BUILD.bazel
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

The old manifest is there just to make it easier to cherry-pick to 1.23. Should be removed in master afterwards.

Update LBC to 2.4.0

---

docs/networking/ipv6.md
pkg/apis/kops/validation/legacy.go
pkg/apis/kops/validation/validation.go
pkg/apis/nodeup/config.go
pkg/model/awsmodel/network.go
upup/pkg/fi/cloudup/template_functions.go

Now that CCM for Kubernetes 1.22 has been upgraded to 1.22-alpha.1, we can enable RBN on that version of Kubernetes.

Enable RBN with AWS CCM 1.22.0-alpha.1

---

nodeup/pkg/model/kube_apiserver.go

Cherry pick of #13264 on release-1.23.
#13264: Disable some flags in kube-apiserver when logging-format is

Automated cherry pick of #13264: Disable some flags in kube-apiserver when logging-format is

---

nodeup/pkg/model/kube_apiserver.go

Fixes #13245 
Disable these flags because these are not accepted when I use `json` as `logging-format`.
* `--logtostderr`
* `--alsologtostderr`
* `--log-file`
According to Kubernetes document: 
> Non-default formats don't honor these flags: --add-dir-header, --alsologtostderr, --log-backtrace-at, --log-dir, --log-file, --log-file-max-size, --logtostderr, --one-output, --skip-headers, --skip-log-headers, --stderrthreshold, --vmodule.
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
And when I specify these flags, kube-apiserver says an error.

Disable some flags in kube-apiserver when logging-format is not text

---

nodeup/pkg/model/containerd.go
nodeup/pkg/model/tests/containerdbuilder/flatcar/tasks.yaml

Cherry pick of #12900 on release-1.21.
#12900: Simplify Flatcar containerd exec command

Automated cherry pick of #12900: Simplify Flatcar containerd exec command

---

channels/alpha

* https://github.com/kubernetes/kubernetes/releases/tag/v1.21.10
* https://github.com/kubernetes/kubernetes/releases/tag/v1.22.7
* https://github.com/kubernetes/kubernetes/releases/tag/v1.23.4

Bump k8s versions in alpha with Feb 2022 releases

---

pkg/apis/kops/util/BUILD.bazel
pkg/apis/kops/util/taints.go
pkg/apis/kops/validation/instancegroup.go
pkg/apis/kops/validation/instancegroup_test.go
pkg/testutils/cluster.go
upup/pkg/fi/cloudup/populate_instancegroup_spec.go
upup/pkg/fi/cloudup/populate_instancegroup_spec_test.go
upup/pkg/fi/cloudup/template_functions.go

Validate taints in IG spec

---

pkg/apis/kops/util/BUILD.bazel
pkg/apis/kops/util/taints.go
pkg/apis/kops/validation/instancegroup.go
pkg/apis/kops/validation/instancegroup_test.go
pkg/testutils/cluster.go
upup/pkg/fi/cloudup/populate_cluster_spec_test.go
upup/pkg/fi/cloudup/populate_instancegroup_spec.go
upup/pkg/fi/cloudup/populate_instancegroup_spec_test.go
upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #13266 on release-1.23.
#13266: Validate taints in IG spec
```release-note
```

Automated cherry pick of #13266: Validate taints in IG spec

---

protokube/pkg/gossip/dns/hosts/hosts_test.go
upup/pkg/fi/cloudup/awstasks/render_test.go
upup/pkg/fi/files_test.go
util/pkg/vfs/fs_test.go

A small testing enhancement here.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir

test: use `T.TempDir` to create temporary test directory

---

pkg/model/iam/iam_builder.go
tests/integration/update_cluster/aws-lb-controller/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm/data/aws_iam_role_policy_masters.minimal.example.com_policy
tests/integration/update_cluster/many-addons/data/aws_iam_role_policy_masters.minimal.example.com_policy

Cherry pick of #13280 on release-1.22.
#13280: Add missing permissions to aws lbc for irsa
```release-note
```

Automated cherry pick of #13280: Add missing permissions to aws lbc for irsa

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #13284 on release-1.23.
#13284: Do not create a cert-manager namespace
```release-note
```

Automated cherry pick of #13284: Do not create a cert-manager namespace

---

pkg/model/iam/iam_builder.go
tests/integration/update_cluster/aws-lb-controller/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm/data/aws_iam_role_policy_masters.minimal.example.com_policy
tests/integration/update_cluster/many-addons/data/aws_iam_role_policy_masters.minimal.example.com_policy

Looks like we are missing a lot of permissions for LBC. 
fixes #13020

Add missing permissions to aws lbc for irsa

---

channels/alpha

Includes fixes for etcd 3.5.0 vs 3.5.1

alpha channel: recommend kOps 1.22.4

---

docs/networking/cilium.md

This PR adds documentation to deploy Hubble UI using Helm.

docs: add hubble ui helm chart deployment

---

cloudmock/gce/BUILD.bazel
cloudmock/gce/mock_gce_cloud.go
cloudmock/gce/mockiam/BUILD.bazel
cloudmock/gce/mockiam/api.go
cloudmock/gce/mockiam/serviceaccounts.go
pkg/model/gcemodel/context.go
pkg/resources/gce/BUILD.bazel
pkg/resources/gce/gce.go
upup/pkg/fi/cloudup/gce/BUILD.bazel
upup/pkg/fi/cloudup/gce/gce_cloud.go
upup/pkg/fi/cloudup/gce/iam.go
upup/pkg/fi/cloudup/gce/labels.go
upup/pkg/fi/cloudup/gcetasks/serviceaccount.go

cleanup GCP Cluster Service Accounts

---

docs/contributing/release-process.md

`gh pr create` will prompt to push upstream, and our docs assumed that
origin was the user's fork, but that is often not the case.

docs for release process shouldn't assume remotes

---

upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #13311 on release-1.23.
#13311: use own function to define CSI image version

Automated cherry pick of #13311: use own function to define CSI image version

---

upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/template_functions.go

this PR fixes 2 bugs:
1) there is typo in CCM tag, it should be `v1.23.1` not `1.23.1`
2) currently kOps assumes that CSI uses same version than CCM uses in OpenStack. However, that is not true currently.

use own function to define CSI image version

---

pkg/pki/sshkey.go
pkg/pki/sshkey_test.go

AWS EC2 supports `ed25519` keys from the start of this year [(blog)](https://aws.amazon.com/about-aws/whats-new/2022/01/ed25519-keys-authentication-ec2-instance-connect/), updating the `ComputeAWSKeyFingerprint` func to match this.
I trimmed the "SHA256" prefix that the `ssh.FingerprintSHA256` call adds to keep it consistent with the fingerprint format presented both in the console and the API. Happy to undo this if folks think this is incorrect :smile: 
```
$ aws ec2 describe-key-pairs --key-names jake-test-ed25519
{
"KeyPairs": [
{
...
"KeyFingerprint": "HvE7+gmH78VS53+iPuRDh/gKjVo26OzYU/qOnJWAgyk=",
"KeyName": "jake-test-ed25519",
"KeyType": "ed25519",
}
]
}
```
This issue was originally discovered here https://github.com/weaveworks/eksctl/issues/4779

Add support for ed25519 keys in AWS

---

nodeup/pkg/model/kube_scheduler.go

Existing condition appends the policy config map arguments even if the UsePolicyConfigMap is set to false.

Append policy config map arguments only if UsePolicyConfigmap is true

---

pkg/pki/sshkey.go
pkg/pki/sshkey_test.go

Cherry pick of #13304 on release-1.23.
#13304: add support for ed25519 keys

Automated cherry pick of #13304: add support for ed25519 keys

---

pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

Cherry pick of #13325 on release-1.23.
#13325: Update containerd to v1.6.1

Automated cherry pick of #13325: Update containerd to v1.6.1

---

nodeup/pkg/model/kube_scheduler.go

Cherry pick of #13308 on release-1.23.
#13308: check if UsePolicyConfigMap flag is true

Automated cherry pick of #13308: check if UsePolicyConfigMap flag is true

---

Makefile
pkg/model/components/kubeapiserver/model.go
pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.18/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.18/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/service-account-iam/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/service-account-iam/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/service-account-iam/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
upup/pkg/fi/cloudup/urls_test.go
version.go

- Release 1.21.0-beta.1
- Use etcd-manager built from etcdadm repo
- Use etcd-backup built from etcdadm repo
- Simplify use of hack/set-version
- Verify all versions are set correctly
- Bump to GA release
- Update verify-terraform to use 0.15.3
- Create new clusters without forcing a container runtime
- Sort --extra-tags of ebs-csi-driver
- Allow AWS instance types with multiple architectures
- Add support for CAS 1.21.0
- upup: gcetasks: fix diffs in instance template and router
- upup: gcetasks: force send AutoCreateSubnetworks field when set to false
- Announce k8s removals two kOps versions in advance
- Update cert-manager
- Set priorityClassName on critical addons
- fix(coredns/rbac): add permission to list and watch endpointslices
- tests: fixing the coredns manifest hash
- …

release 1.21.5

---

pkg/instancegroups/instancegroups.go
pkg/instancegroups/rollingupdate_test.go

I don't see why the GCE CCM shouldn't have deleted the node object before the new kublet registers given that the NodeLifecycle controller runs every 40 seconds ... But until we can test, we keep this for GCE.
/cc @justinsb @hakman @johngmyers 
fixes #13259

Only delete node object on GCE

---

pkg/model/components/awscloudcontrollermanager.go
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content

That CCM 1.22 branch is pushed to their latest breaks a sizeable portion of our e2e tests.
Possible culprit of the OIDC issues as well, as the failure (waiting for ELB to be ready, which never happens) may cause timeouts, which again may cause the cleanup never to happen.

Bump CCM 1.22 image. Use the 1.23 image for 1.24 due to latest being broken

---

docs/getting_started/aws.md

This flag was introduced in 1.23, so hold for 1.23 to go GA
/hold

Recommend enabling IRSA for new clusters

---

tests/e2e/kubetest2-kops/do/zones.go

The e2e tests [here ](https://testgrid.k8s.io/google-aws#e2e-kops-do-calico)was always picking up the default zone (nyc1) since seed wasn't specified.
Hopefully this should fix the issue.

[Digital Ocean] e2e tests - Fix seeding for generating random zones

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go

**Problem**
Currently, `deregisterInstanceFromTargetGroups` attempts to drain a given instance from all corresponding targetGroups. However, it'll complete once _any_ of the targetGroups report that the instance is drained. This can potentially cause interruptions in other tagetGroups that haven't fully drained before the node is terminated. 
**Solution**
This PR ensures that all targetGroups have an instance fully drained before moving to delete the instance. In the event that a goroutine fails to drain the instance from a targetGroup, `deregisterInstanceFromTargetGroups` will stop all goroutines, return the corresponding error, and prevent the instance from being deleted.
**Example Execution**
```
❯ ~/go/bin/kops rolling-update cluster --instance-groups <redacted> --force --yes
I0315 …
```

wait for all targetGroups to drain

---

docs/gpu.md
k8s/crds/kops.k8s.io_instancegroups.yaml
pkg/apis/kops/containerdconfig.go
pkg/apis/kops/instancegroup.go
pkg/apis/kops/v1alpha2/instancegroup.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/instancegroup.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/validation/instancegroup.go
pkg/apis/kops/validation/validation.go
pkg/apis/kops/validation/validation_test.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/components/containerd.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/populate_instancegroup_spec.go
upup/pkg/fi/nodeup/command.go

Support GPU in OpenStack

---

pkg/model/iam/iam_builder.go
tests/integration/update_cluster/aws-lb-controller/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm/data/aws_iam_role_policy_masters.minimal.example.com_policy
tests/integration/update_cluster/many-addons/data/aws_iam_role_policy_masters.minimal.example.com_policy

Cherry pick of #13369 on release-1.23.
#13369: Add missing permissions to aws lbc for IP targeting
```release-note
```

Automated cherry pick of #13369: Add missing permissions to aws lbc for IP targeting

---

cmd/kops/upgrade_cluster.go

We don't allow empty image anymore, but some users may already have this in the state store.
Fixes #12630

If image is empty, have kops upgrade fill it in

---

upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/manifest.yaml

AWS IAM Authenticator has been released to v0.5.5 bringing ARM64 compatible container image.
With this version, the run user and group are not fixed anymore. 
Since we are forcing the certificates to be generated with user and group to 10000 in [kube_apiserver.go](https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/kube_apiserver.go#L297), 
I also added a `securityContext.runAsUser` and `securityContext.runAsGroup` to match the owner.

Upgrade aws-iam-authenticator to v0.5.5

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_bucket_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml.template
upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template

See https://github.com/kubernetes/kubernetes/issues/92332
Basically, server-side apply fails if protocol is not set on k8s 1.20 and older.

Add protocol explicitly to services

---

docs/getting_started/digitalocean.md
pkg/zones/wellknown.go
tests/e2e/kubetest2-kops/do/zones.go

Saw e2e tests failing for SFO2 region - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-do-calico/1504078673064497152
Per discussion with @timoreimann this is expected and customers should use the new `SFO3` region going forward. We currently have `SFO3` already in the list of supported regions.

[Digital Ocean] Remove sfo2 region from the list of supported DO regions

---

tests/e2e/kubetest2-kops/deployer/up.go

Cherry pick of #13373 on release-1.22.
#13373: If kubetest2 fails cluster validation, we run down before
```release-note
```

Automated cherry pick of #13373: If kubetest2 fails cluster validation, we run down before

---

pkg/apis/kops/validation/instancegroup.go
pkg/apis/kops/validation/instancegroup_test.go

Cherry pick of #13366 on release-1.23.
#13366: Allow taints with unique key,value,effect
```release-note
```

Automated cherry pick of #13366: Allow taints with unique key,value,effect

---

hack/run-e2e-from-source.sh
hack/run-e2e.sh

Assumes an existing cluster, but then example usage:
```
./hack/run-e2e-from-source.sh aws.*Pre-provisioned.*ext4
```

dev: create scripts to make it easier to run e2e tests

---

pkg/zones/wellknown.go
tests/e2e/kubetest2-kops/do/zones.go

Per latest docs - the region availability matrix supports regions as mentioned [here](https://docs.digitalocean.com/products/platform/availability-matrix/).
Remove regions that doesn't match this list (ams2, nyc2, sfo1)

[Digital Ocean] Use available regions as per the latest DO documentation

---

nodeup/pkg/model/kube_apiserver.go
nodeup/pkg/model/kube_controller_manager.go
nodeup/pkg/model/kube_proxy.go
nodeup/pkg/model/kube_scheduler.go
nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-amd64.yaml
nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-arm64.yaml
nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-amd64.yaml
nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-arm64.yaml
nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-amd64.yaml
nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-arm64.yaml
nodeup/pkg/model/tests/golden/side-loading/tasks-kube-scheduler-amd64.yaml
nodeup/pkg/model/tests/golden/side-loading/tasks-kube-scheduler-arm64.yaml

Use k8s.gcr.io for k8s side-loaded images

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/components/nodeterminationhandler.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_nthsqsresources.longclustername.example.com-addons-bootstrap_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_nthsqsresources.longclustername.example.com-addons-node-termination-handler.aws-k8s-1.11_content
upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template

Add the possibility into the AWS `node-termination-handler` addon to set a different image tag version.
It can help to have last fixes if it's needed.

AWS-NODE-TERMINATION: Add possibility to set a tune image version

---

util/pkg/vfs/s3context.go
util/pkg/vfs/s3context_test.go

This PR correctly detects S3 HTTP URLs in GovCloud regions for `spec.assets.fileRepository`.
e.g.  this is the S3 object URL format for GovCloud
```
spec:
assets:
fileRepository: https://bucket-name.s3-us-gov-west-1.amazonaws.com/bucket-path
```
Prior to this PR, the bucket name is captured incorrectly in the example above as `s3-us-gov-west-1`.

Correctly detect GovCloud regions

---

util/pkg/vfs/s3context.go
util/pkg/vfs/s3context_test.go

Cherry pick of #13410 on release-1.22.
#13410: Correctly detect GovCloud regions

Automated cherry pick of #13410: Correctly detect GovCloud regions

---

.github/workflows/main.yml
.github/workflows/tag-release.yml

- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
Also, dependabot supports upgrading based on SHA.
Signed-off-by: …

Pin actions to a full length commit SHA

---

cmd/kops/get_sshpublickeys.go

In our CI scripts we wanted to adapt to the new `sshpublickey` command, however for a new cluster this will exit non-successfully if there are no keys yet. It is possible to work around this with some ugly hacks, however for scripts I think we should return successfully if there are no public keys. It's not like something bad happened.
This PR ensures that for json/yaml output, which is for machine consumption, that even for an empty list it will exit with a `0` exit code if no errors happen.

Do not return a '-1' exit if no keys found and json/yaml output

---

cmd/kops/get_sshpublickeys.go

Cherry pick of #13378 on release-1.23.
#13378: Do not return a '-1' exit if no keys found and json/yaml

Automated cherry pick of #13378: Do not return a '-1' exit if no keys found and json/yaml

---

tests/e2e/pkg/tester/tester.go

E2E has its own log dump script that e2e consistently fail to execute because of a path issue. 
```
Mar 29 17:20:38.405: INFO: Error running cluster/log-dump/log-dump.sh: fork/exec ../../cluster/log-dump/log-dump.sh: no such file or directory
```
This script wouldn't work with kOps anyway, and we have our own dumper. So best to just explicitly skip it.

Skip upstream e2e log dump

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/cluster.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/cluster.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template

Annotations is pretty useful when you need third-party tool to add additional behavior for a k8s resource.
Lots of auto-discovery tools are based on this annotations.
This PR add the possibility to set tune pod annotations in the node-local-dns daemonsets.app.

Add possibility to set PodAnnotations into NodeLocalDNS

---

tests/integration/update_cluster/apiservernodes/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/apiservernodes/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
upup/pkg/fi/cloudup/template_functions.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml

The controller just runs and spams the logs with entries about missing CRDs.

Don't run the CSI snapshot plugin if snapshot controller is not installed

---

pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

Cherry pick of #13455 on release-1.23.
#13455: Update containerd to v1.6.2
```release-note
```

Automated cherry pick of #13455: Update containerd to v1.6.2

---

upup/pkg/fi/cloudup/containerd.go

Ref: https://github.com/kubernetes/kops/commit/42289b7faaf7066e8a1fe1d25be791e2dc1c46f5
/cc @olemarkus

Add back hash for containerd v1.6.1

---

upup/pkg/fi/cloudup/containerd.go

Cherry pick of #13462 on release-1.23.
#13462: Add back hash for containerd v1.6.1
```release-note
```

Automated cherry pick of #13462: Add back hash for containerd v1.6.1

---

pkg/model/components/cilium.go
tests/e2e/pkg/tester/skip_regex.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_bucket_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cilium 1.11 released today: https://isovalent.com/blog/post/2021-12-release-111
Not sure we want this one in 1.23 or wait. Or maybe upgrade cilium based on k8s version.
Either way, this is the first version that formally supports 1.23 (although 1.10 should work fine as well).

Use Cilium 1.11 as default

---

upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstack/server_group.go

This fixes an issue where kops picks the last server group found on OpenStack instead of the right one when getting the cloud groups.
For example, lets assume that kops created those server groups and they are returned in the order as shown here by the OpenStack API:
```
cluster-name-bastion
cluster-name-cp-0
cluster-name-worker
````
Now kops looks for nodes associated with the IG "bastion" and the expected behavior would be that it ends up using "cluster-name-bastion". However, it will actually end up  associating the cloud group with the last server group, which is in this case "cluster-name-worker" due to the reference switching to the last item when the loop is done.
In the worst case this could lead to kops deleting the wrong instances when deleting an IG.
Not using the server group …

Pick the right OS server group when creating cloud groups

---

pkg/model/components/etcdmanager/options.go
tests/integration/update_cluster/apiservernodes/cloudformation.json.extracted.yaml
tests/integration/update_cluster/apiservernodes/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/apiservernodes/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/apiservernodes/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/apiservernodes/data/aws_s3_bucket_object_manifests-etcdmanager-main_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_manifests-etcdmanager-main_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_manifests-etcdmanager-main_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_manifests-etcdmanager-main_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/privatecanal/data/aws_launch_template_master-us-test-1a.masters.privatecanal.example.com_user_data
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_manifests-etcdmanager-main_content

Cherry pick of #13454 on release-1.23.
#13454: Enable etcd corruption check as mitigatio of 3.5 corruption
```release-note
```

Automated cherry pick of #13454: Enable etcd corruption check as mitigatio of 3.5 corruption

---

upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstack/server_group.go

Cherry pick of #13461 on release-1.23.
#13461: Pick the right OS server group when creating cloud groups
```release-note
```

Automated cherry pick of #13461: Pick the right OS server group when creating cloud groups

---

pkg/instancegroups/instancegroups.go
pkg/instancegroups/rollingupdate_test.go

Cherry pick of #13289 on release-1.23.
#13289: Only delete node object on GCE

Automated cherry pick of #13289: Only delete node object on GCE

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/components/nodeterminationhandler.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_nthsqsresources.longclustername.example.com-addons-bootstrap_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_bucket_object_nthsqsresources.longclustername.example.com-addons-node-termination-handler.aws-k8s-1.11_content
upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template

- Bump NTH 1.16 and add excludeFromLoadBalancers option #13465

Bump NTH 1.16 and add excludeFromLoadBalancers option

---

Makefile
hack/verify-apimachinery.sh

Without setting `--output-base` flag to `./`, it defaults to `$GOPATH`:
```
-o, --output-base string               Output base; defaults to $GOPATH/src/ or ./ if $GOPATH is not set. (default "./")
```
/cc @olemarkus

Remove GOPATH dependency for apimachinery

---

docs/releases/1.22-NOTES.md

Document NodeLocalDNS forwardToKubeDNS breaking change

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Cherry pick of #13488 on release-1.23.
#13488: bump aws cni to version 1.10.3
```release-note
```

Automated cherry pick of #13488: bump aws cni to version 1.10.3

---

docs/getting_started/aws.md

- Added `--name` and `--cloud` flags for  `kops create cluster` command as they are required options. 
> kops create cluster \
--name=${NAME} \
--cloud=aws \
--zones=us-west-2a \
--discovery-store=s3://prefix-example-com-oidc-store/${NAME}/discovery \
- Added `--name` flag to `kops edit cluster` and `kops update cluster` for consistency across the docs.
Closes https://github.com/kubernetes/kops/issues/13474

Docs getting started aws

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.16_content
tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-networking.projectcalico.org.canal-k8s-1.22_content
upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.22.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template

Cherry pick of #13497 on release-1.23.
#13497: Update Calico to v3.21.5
```release-note
```

Automated cherry pick of #13497: Update Calico to v3.21.5

---

pkg/model/components/etcdmanager/options.go
tests/integration/update_cluster/apiservernodes/cloudformation.json.extracted.yaml
tests/integration/update_cluster/apiservernodes/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/apiservernodes/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/apiservernodes/data/aws_s3_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/apiservernodes/data/aws_s3_object_manifests-etcdmanager-main_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_manifests-etcdmanager-main_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_object_manifests-etcdmanager-main_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_manifests-etcdmanager-main_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_manifests-etcdmanager-main_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_manifests-etcdmanager-main_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/privatecanal/data/aws_launch_template_master-us-test-1a.masters.privatecanal.example.com_user_data
tests/integration/update_cluster/privatecanal/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_manifests-etcdmanager-main_content

This reverts commit 6d75f8f9f09d7cbaee46399b91a1f14478a28647.
Now done in etcd-manager: https://github.com/kubernetes-sigs/etcdadm/pull/304.
/cc @justinsb @olemarkus

Revert "Enable etcd corruption check"

---

pkg/model/components/etcdmanager/options.go
tests/integration/update_cluster/apiservernodes/cloudformation.json.extracted.yaml
tests/integration/update_cluster/apiservernodes/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/apiservernodes/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/apiservernodes/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/apiservernodes/data/aws_s3_bucket_object_manifests-etcdmanager-main_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_manifests-etcdmanager-main_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_manifests-etcdmanager-main_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_manifests-etcdmanager-main_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/privatecanal/data/aws_launch_template_master-us-test-1a.masters.privatecanal.example.com_user_data
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_manifests-etcdmanager-events_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_manifests-etcdmanager-main_content

Cherry pick of #13495 on release-1.23.
#13495: Revert "Enable etcd corruption check as mitigatio of 3.5
```release-note
```

Automated cherry pick of #13495: Revert "Enable etcd corruption check"

---

pkg/model/components/etcd.go
pkg/model/components/etcdmanager/options.go
tests/integration/update_cluster/apiservernodes/cloudformation.json.extracted.yaml
tests/integration/update_cluster/apiservernodes/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/apiservernodes/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/apiservernodes/data/aws_s3_bucket_object_etcd-cluster-spec-events_content
tests/integration/update_cluster/apiservernodes/data/aws_s3_bucket_object_etcd-cluster-spec-main_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_etcd-cluster-spec-events_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_etcd-cluster-spec-main_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_etcd-cluster-spec-events_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_etcd-cluster-spec-main_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_etcd-cluster-spec-events_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_etcd-cluster-spec-main_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/privatecanal/data/aws_launch_template_master-us-test-1a.masters.privatecanal.example.com_user_data
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_etcd-cluster-spec-events_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_etcd-cluster-spec-main_content

Cherry pick of #13501 on release-1.23.
#13501: Use etcd 3.5.3 instead of 3.5.1
```release-note
```

Automated cherry pick of #13501: Use etcd 3.5.3 instead of 3.5.1

---

pkg/model/components/awscloudcontrollermanager.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content

Cherry pick of #13506 on release-1.23.
#13506: Bump CCM 1.22 and 1.23 images to stable versions
```release-note
```

Automated cherry pick of #13506: Bump CCM 1.22 and 1.23 images to stable versions

---

pkg/model/components/clusterautoscaler.go

We made this explicitly fail before because there is a risk of us forgetting to bump. I think, however, history has shown this risk is not very real

Use Cluster Autoscaler 1.23 for k8s 1.24

---

go.mod
go.sum
tests/e2e/go.mod
tests/e2e/go.sum
vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
vendor/github.com/aws/aws-sdk-go/aws/request/retryer.go
vendor/github.com/aws/aws-sdk-go/aws/version.go
vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/eventstreamapi/transport.go
vendor/github.com/aws/aws-sdk-go/private/protocol/rest/build.go
vendor/github.com/aws/aws-sdk-go/service/autoscaling/api.go
vendor/github.com/aws/aws-sdk-go/service/cloudformation/api.go
vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface/interface.go
vendor/github.com/aws/aws-sdk-go/service/eventbridge/api.go
vendor/github.com/aws/aws-sdk-go/service/eventbridge/eventbridgeiface/interface.go
vendor/github.com/aws/aws-sdk-go/service/iam/api.go
vendor/github.com/aws/aws-sdk-go/service/kms/api.go
vendor/github.com/aws/aws-sdk-go/service/route53/api.go
vendor/github.com/aws/aws-sdk-go/service/s3/api.go
vendor/github.com/aws/aws-sdk-go/service/sqs/api.go
vendor/github.com/aws/aws-sdk-go/service/sts/api.go
vendor/modules.txt

Cherry pick of #13515 on release-1.23.
#13515: Update aws-sdk-go to v1.43.41
```release-note
```

Automated cherry pick of #13515: Update aws-sdk-go to v1.43.41

---

pkg/model/components/awscloudcontrollermanager.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content

Cherry pick of #13514 on release-1.23.
#13514: Revert to using 1.23.0-alpha.0 for AWS CCM
```release-note
```

Automated cherry pick of #13514: Revert to using 1.23.0-alpha.0 for AWS CCM

---

tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_bucket_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-networking.projectcalico.org.canal-k8s-1.22_content
upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.22.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template

Ref: https://projectcalico.docs.tigera.io/archive/v3.20/release-notes/#v3205

Update Calico and Canal to v3.20.5 for kOps 1.22

---

pkg/model/components/awscloudcontrollermanager.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content

Ref: https://github.com/kubernetes/cloud-provider-aws/issues/339
/cc @olemarkus

Revert to using 1.23.0-alpha.0 for AWS CCM

---

pkg/model/gcemodel/context.go
pkg/model/gcemodel/firewall.go

fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-gce-u2004-k22-docker/1515837173192986624
`W0417 23:40:26.970906    5906 executor.go:139] error running task "FirewallRule/ssh-external-to-master-ipv6-e2e-e2e-kops-grid-gce-u2004-k22-docker-k8s-local" (9m59s remaining to succeed): error listing FirewallRules: googleapi: Error 400: Invalid value for field 'firewall': 'ssh-external-to-master-ipv6-e2e-e2e-kops-grid-gce-u2004-k22-docker-k8s-local'. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}', invalid`
https://cloud.google.com/compute/docs/naming-resources#resource-name-format
This should be safe for existing clusters given that the integration test terraform files aren't changing as a result of this, it only allows the creation of clusters …

Trim GCE firewall rule names to their max length

---

tests/e2e/go.mod
tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/pkg/util/pki.go

This should create an ~EDSCA~ (AWS doesn't support EDSCA) ED25519 ssh keypair in a temp directory that persists for the cluster name. This allows separate `kubetest2-kops` commands to reuse the same SSH key (useful for our scenario scripts).
Ubuntu 22.04 drops support for RSA keys by default so we use ED25519 keys instead.
Once this is working and merged we can:
* Drop the env vars elsewhere: [here](https://github.com/kubernetes/kops/blob/db57ef49218f303b6be5e4a36a3867478fc80cc0/tests/e2e/scenarios/lib/common.sh#L55-L60) and [here](https://github.com/kubernetes/test-infra/blob/edf2b71e7967294e307340d7d3fa1ef3a5f036be/config/jobs/kubernetes/kops/templates/periodic.yaml.jinja#L7) for example
* Expand this to cover other cloud providers (assuming kOps uploads public keys to them, when …

kubetest2-kops - Create ephemeral SSH keys

---

tests/e2e/pkg/tester/skip_regex.go

fixes one test in https://testgrid.k8s.io/kops-misc#kops-aws-misc-ha-euwest1
It is enabled by default in 1.24 so we only ever need to skip it in 1.23: https://github.com/kubernetes/kubernetes/commit/1183f270cb5aefbe8ae2d4ff6624adf4a65eb96c

Skip topology hints tests in k8s 1.23

---

tests/integration/update_cluster/external_dns/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/external_dns/data/aws_s3_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/external_dns_irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/external_dns_irsa/data/aws_s3_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.16_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.16_content
upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
upup/models/cloudup/resources/addons/authentication.kope.io/k8s-1.12.yaml
upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/k8s-1.19.yaml.template
upup/models/cloudup/resources/addons/gcp-cloud-controller.addons.k8s.io/k8s-1.23.yaml.template
upup/models/cloudup/resources/addons/gcp-pd-csi-driver.addons.k8s.io/k8s-1.23.yaml.template
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template
upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/manifest.yaml

followup to https://github.com/kubernetes/kops/pull/13452
fixes failing jobs like this: https://testgrid.k8s.io/kops-misc#kops-aws-external-dns

Update remaining addon manifests for the control-plane node role

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template

Cherry pick of #13511 on release-1.23.
#13511: add cluster autoscaler pod annotations
```release-note
```

Automated cherry pick of #13511: add cluster autoscaler pod annotations

---

pkg/model/components/addonmanifests/clusterautoscaler/iam.go
pkg/model/iam/iam_builder.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_iam_role_policy_cluster-autoscaler.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_iam_role_policy_cluster-autoscaler.kube-system.sa.minimal.example.com_policy

When the cluster autoscaler builds its EC2 instance type catalog dynamically instead of using only its statically defined set, grant it the additional IAM permissions—as prescribed in [the cluster autoscaler documentation](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#full-cluster-autoscaler-features-policy-recommended)—required to fetch the instance types from the AWS API.
Fixes #13520.

Allow cluster autoscaler to read EC2 instance types to build catalog dynamically

---

util/pkg/vfs/gsfs.go
util/pkg/vfs/tests/gsfs_test.go

When creating a new cluster for GCP and using the Terraform target, fix kops panic by using expected pointer type in a type assertion in `util/pkg/vfs/gsfs.go` instead of interface type.
Fixes #13533

Use expected pointer type in type assertion when iterating over GS ACLs

---

util/pkg/vfs/gsfs.go
util/pkg/vfs/tests/gsfs_test.go

Cherry pick of #13534 on release-1.23.
#13534: Use a pointer type in type assertion
```release-note
```

Automated cherry pick of #13534: Use a pointer type in type assertion

---

tests/e2e/go.mod
tests/e2e/pkg/util/pki.go

Go's crypto modules can't generate ed25519 keys in the openssh format, so we rely on ssh-keygen instead
should fix https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-cni-cilium-ipv6/1516859892369985536#1:build-log.txt%3A2150
```
I0420 19:42:00.202343    5615 dumplogs.go:217] ssh -i /tmp/kops/e2e-e2e-kops-aws-cni-cilium-ipv6.test-cncf-aws.k8s.io/id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null admin@34.217.22.127 -- kubectl cluster-info dump --all-namespaces -o yaml --output-directory /tmp/cluster-info
Warning: Permanently added '34.217.22.127' (ECDSA) to the list of known hosts.
Load key "/tmp/kops/e2e-e2e-kops-aws-cni-cilium-ipv6.test-cncf-aws.k8s.io/id_ed25519": invalid format
admin@34.217.22.127: Permission denied (publickey).
```

Shell out to ssh-keygen for creating ed25519 keys

---

tests/integration/update_cluster/external_dns/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/external_dns/data/aws_s3_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/external_dns_irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/external_dns_irsa/data/aws_s3_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.19_content
upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/k8s-1.19.yaml.template

clusters are failing to validate: https://testgrid.k8s.io/kops-misc#kops-aws-external-dns
[kube-scheduler logs](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-external-dns/1516181215399383040/artifacts/3.138.101.39/kube-scheduler.log) show:
`I0418 22:41:15.011259      10 scheduler.go:351] "Unable to schedule pod; no fit; waiting" pod="kube-system/external-dns-695c9468f9-dbl5q" err="0/1 nodes are available: 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling."`

Update control plane toleration for external-dns

---

pkg/model/components/addonmanifests/clusterautoscaler/BUILD.bazel
pkg/model/components/addonmanifests/clusterautoscaler/iam.go
pkg/model/iam/iam_builder.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_iam_role_policy_cluster-autoscaler.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_iam_role_policy_cluster-autoscaler.kube-system.sa.minimal.example.com_policy

Cherry pick of #13532 on release-1.23.
#13532: Allow cluster autoscaler to get EC2 instance types

Automated cherry pick of #13532: Allow cluster autoscaler to get EC2 instance types

---

pkg/model/components/awscloudcontrollermanager.go

With the k8s 1.24 rc.0 published, our prow jobs that use k8s CI builds are now on k8s 1.25.
To avoid https://github.com/kubernetes/cloud-provider-aws/issues/339 in the latest AWS CCM tag we have to pin 1.25 to the same tag as k8s 1.23 and 1.24
Should fix https://testgrid.k8s.io/kops-misc#kops-aws-misc-arm64-ci
you can see `latest` is being used in the daemonset here: https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-misc-arm64-ci/1517088467119509504/artifacts/cluster-info/kube-system/daemonsets.yaml
and the panic is occurring: https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-misc-arm64-ci/1517088467119509504/artifacts/cluster-info/kube-system/aws-cloud-controller-manager-kw82b/logs.txt

Pin AWS CCM image tag for k8s 1.25

---

tests/integration/update_cluster/many-addons/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons/in-v1alpha2.yaml
upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template

PodAnnotations in both cluster autoscaler and node-local-dns are failing.
Changing the yaml definitions to correctly unmarshal `map[string][string]` to valid annotations.
Testing:
```
❯ ~/go/bin/kops update cluster
...
ManagedFile/bronson.cluster.doordash.cloud-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15
Contents
...
prometheus.io/port: "8085"
prometheus.io/scrape: "true"
+         test1: test
+         test2: "123"
creationTimestamp: null
labels:
...
ManagedFile/bronson.cluster.doordash.cloud-addons-nodelocaldns.addons.k8s.io-k8s-1.12
Contents
...
prometheus.io/port: "9253"
prometheus.io/scrape: "true"
+         test1: test
+         test2: "123"
creationTimestamp: null
labels:
...
❯ kd po node-local-dns-2qvz5
Name:                 node-local-dns-2qvz5
Namespace: …
```

fix pod annotations in addon yamls

---

tests/e2e/pkg/tester/skip_regex.go

fixes https://testgrid.k8s.io/kops-misc#kops-aws-external-dns and other cilium jobs using CI k8s builds

Skip SCTP tests in k8s 1.25 as well

---

pkg/model/gcemodel/context.go
pkg/model/master_volumes.go

GCE jobs are still failing due to cluster names being too long:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-gce-u2004-k22-containerd/1516912053338509312
`W0420 23:01:47.344909    5875 executor.go:139] error running task "Disk/a-etcd-main-e2e-e2e-kops-grid-gce-u2004-k22-containerd-k8s-local" (6s remaining to succeed): error listing Disks: googleapi: Error 400: Invalid value for field 'disk': 'a-etcd-main-e2e-e2e-kops-grid-gce-u2004-k22-containerd-k8s-local'. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}', invalid`
`W0420 23:01:47.344921    5875 executor.go:139] error running task "Subnet/us-central1-e2e-e2e-kops-grid-gce-u2004-k22-containerd-k8s-local" (6s remaining to succeed): error listing Subnets: googleapi: Error 400: Invalid value …

Trim GCE Subnet and Disk names

---

tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-networking.flannel-k8s-1.12_content
upup/models/cloudup/resources/addons/networking.flannel/k8s-1.12.yaml.template

The images were moved from quay back to dockerhub in https://github.com/flannel-io/flannel/pull/1516. I checked and 0.17.0 is not published to the quay image, so we may not have a choice there

Upgrade flannel to 0.17.0

---

nodeup/pkg/model/protokube.go
nodeup/pkg/model/tests/protokube/tasks-protokube.yaml
protokube/cmd/protokube/main.go
protokube/pkg/protokube/aws_volume.go
protokube/pkg/protokube/azure_volume.go
protokube/pkg/protokube/gce_volume.go
protokube/pkg/protokube/openstack_volume.go

Getting the cluster ID from the cloud provider is just not needed.
NodeUp knows the cluster ID and can set it when configuring Protokube.

Always set cluster-id flag for Protokube

---

nodeup/pkg/model/kubectl_test.go
nodeup/pkg/model/tests/golden/minimal/tasks-kubectl.yaml
util/pkg/distributions/distributions.go

Some Ubuntu images use the `root` user as the initial SSH user.

Creaate kubeconfig for the root user on Ubuntu

---

docs/operations/images.md
docs/releases/1.23-NOTES.md
util/pkg/distributions/distributions.go
util/pkg/distributions/identify.go
util/pkg/distributions/identify_test.go

Cherry pick of #13557 on release-1.23.
#13557: Add back support for Ubuntu 18.04
```release-note
```

Automated cherry pick of #13557: Add back support for Ubuntu 18.04

---

nodeup/pkg/model/sysctls.go

This was originally only set on Centos 7 / RHEL 7 but we're experiencing similar issues on Amazon Linux 2
backstory:
This PR's lengthy discussion to remove support for flannel/vxlan after the same issues were causing grid failures for Centos 7 / RHEL 7: https://github.com/kubernetes/kops/pull/8614
These sysctl settings were added for centos/rhel which supposedly fixed our grid jobs: https://github.com/kubernetes/kops/pull/8381
These settings were removed when we dropped support for those distros: https://github.com/kubernetes/kops/pull/12882/files#diff-5326919ae93590b94b210fb2373f8374d5567d146aadaf815ca6a1f7b68179dd
Hoping this fixes these grid jobs: https://testgrid.k8s.io/kops-grid#kops-grid-flannel-amzn2-k23-docker

Re-add net.bridge settings for flannel

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/template_functions.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.11.0
As far as manifest changes, it doesn't seem like there are any changes whatsoever besides bumping the image (I followed up on their [manifest update PR](https://github.com/aws/amazon-vpc-cni-k8s/pull/1970) to confirm, as well as a side-by-side comparison with the [v1.11 source chart](https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.11/config/master/aws-k8s-cni.yaml)).
From the release page:
> This release addresses introduce an optional new mode for [Security groups for pods feature](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html) along with other improvements

Bump AWS CNI to version 1.11.0

---

pkg/resources/aws/aws.go

A race can occur where an OIDC provider being deleted is in the List results but is not found in the following Get request (especially if there are many providers in the region and the provider being deleted is later in the list)
See the end of [this](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-misc-arm64-release/1519661407237312512) job

Fix OIDC Provider cleanup

---

pkg/dump/dumper.go

Cherry pick of #13570 on release-1.23.
#13570: Include sysctls in toolbox dump
```release-note
```

Automated cherry pick of #13570: Include sysctls in toolbox dump

---

pkg/resources/aws/aws.go

Cherry pick of #13571 on release-1.23.
#13571: Fix OIDC Provider cleanup
```release-note
```

Automated cherry pick of #13571: Fix OIDC Provider cleanup

---

pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

Cherry pick of #13578 on release-1.23.
#13578: Update containerd to v1.6.3
```release-note
```

Automated cherry pick of #13578: Update containerd to v1.6.3

---

nodeup/pkg/model/sysctls.go

Cherry pick of #13564 on release-1.23.
#13564: Re-add net.bridge settings for flannel
```release-note
```

Automated cherry pick of #13564: Re-add net.bridge settings for flannel

---

pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

Cherry pick of #13582 on release-1.23.
#13582: Revert "Update containerd to v1.6.3"
```release-note
```

Automated cherry pick of #13582: Revert "Update containerd to v1.6.3"

---

docs/releases/1.24-NOTES.md
nodeup/pkg/model/packages.go
tests/e2e/pkg/tester/skip_regex.go

This adds too much overhead by default and also is a security risk (automatically start `rpcbind` on port 111).
Random ref: https://book.hacktricks.xyz/pentesting/pentesting-rpcbind

Don't install nfs-common/nfs-utils by default

---

docs/mfa.md

Add doc to use [aws-vault](https://github.com/99designs/aws-vault) as it's a common tool for MFA.

doc(mfa): add another workaround using aws-vault

---

pkg/kubemanifest/yaml.go

Before:
```
yaml.go:53] MetadataObj: map[creationTimestamp:<nil> labels:map[discovery.kops.k8s.io/internal-name:api.internal.test1.k8s.local] name:api-internal namespace:kube-system]:
yaml.go:58] unexpected type for object metadata: map[string]interface {}
yaml.go:63] MetadataObj: map[creationTimestamp:<nil> labels:map[discovery.kops.k8s.io/internal-name:api.internal.test1.k8s.local] name:api-internal namespace:kube-system]:
yaml.go:53] MetadataObj: map[creationTimestamp:<nil> labels:map[discovery.kops.k8s.io/internal-name:kops-controller.internal.test1.k8s.local] name:kops-controller-internal namespace:kube-system]:
yaml.go:58] unexpected type for object metadata: map[string]interface {}
yaml.go:63] MetadataObj: map[creationTimestamp:<nil> …
```

Fix unexpected type for object metadata when using gossip DNS

---

pkg/kubemanifest/yaml.go

Cherry pick of #13592 on release-1.23.
#13592: Fix unexpected type for object metadata when using gossip DNS
```release-note
```

Automated cherry pick of #13592: Fix unexpected type for object metadata when using gossip DNS

---

k8s/crds/kops.k8s.io_instancegroups.yaml
nodeup/pkg/model/packages.go
pkg/apis/kops/instancegroup.go
pkg/apis/kops/v1alpha2/instancegroup.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/instancegroup.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/apis/nodeup/config.go
tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
tests/integration/update_cluster/complex/data/aws_launch_template_nodes.complex.example.com_user_data
tests/integration/update_cluster/complex/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
tests/integration/update_cluster/complex/in-v1alpha2.yaml
upup/pkg/fi/cloudup/apply_cluster.go

Easy way to install additional packages. Should allow kOps to not install optional packages, like https://github.com/kubernetes/kops/pull/13577.
/cc @rifelpet @justinsb

Add support for installing additional packages

---

pkg/model/components/containerd.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/containerd.go

Cherry pick of #13596 on release-1.23.
#13596: Update containerd to v1.6.4
```release-note
```

Automated cherry pick of #13596: Update containerd to v1.6.4

---

upup/pkg/fi/cloudup/containerd.go
upup/pkg/fi/cloudup/docker.go

According to [this](https://www.crowdstrike.com/blog/understanding-cve-2022-23648-kubernetes-vulnerability/) article from crowdstrike, containerd version 1.4.13 is the recommended version to fully PATH CVE-2022-23648.
This PR adds 1.4.13 hash to kops binary.
Suggestion: cherrypick this to 1.23 and 1.22

Add hashes for containerd and Docker in order to fix CVE-2022-23648

---

upup/pkg/fi/cloudup/containerd.go
upup/pkg/fi/cloudup/docker.go

Cherry pick of #13606 on release-1.22.
#13606: Add hashes for containerd and Docker in order to fix
```release-note
```

Automated cherry pick of #13606: Add hashes for containerd and Docker

---

pkg/model/components/addonmanifests/kuberouter/iam.go
pkg/model/components/addonmanifests/remap.go
pkg/model/iam/iam_builder.go
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

[kube-router jobs are failing](https://testgrid.k8s.io/kops-network-plugins#kops-aws-cni-kuberouter) now that k8s 1.24 is released. the jobs use the release/stable k8s version marker, so they're now on 1.24 which kops defaults to enabling IRSA.
[kube-router pod logs](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-cni-kuberouter/1521995867320487936/artifacts/cluster-info/kube-system/kube-router-c69fn/logs.txt) show failed attempts to disable the src/dest check on ec2 instances:
`E0504 23:37:12.829945       1 aws.go:60] Node does not have necessary IAM creds to modify instance attribute. So skipping disabling src-dst check.`
Before 1.24, [pod logs](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-cni-kuberouter/1521392063394877440/artifacts/cluster-inf …

Add IRSA for kube-router

---

util/pkg/distributions/distributions.go

In [Flatcar Container Linux versions at 2748.0](https://www.flatcar-linux.org/releases#release-2748.0.0) and later, configure the kubelet to use an alternate DNS resolver configuration. Rather than using the _/etc/resolv.conf_ file, use _systemd-resolved_'s _/run/systemd/resolve/resolv.conf_ file.
Without this configuration, pods like CoreDNS that use [the "Default" DNS policy](https://github.com/kubernetes/api/blob/5e2f5add2db54c6b8eec87c2e467b53d2409dbf3/core/v1/types.go#L2716-L2718) wind up with [a DNS forwarding loop](https://coredns.io/plugins/loop/#troubleshooting).
See flatcar-linux/Flatcar#285 for pertinent discussion, as well as [a thread in the "kops-users" channel](https://kubernetes.slack.com/archives/C3QUFP0QM/p1650573952888199) of the "Kubernetes" Slack workspace that arose …

Avoid "/etc/resolv.conf" file loopback for Flatcar Container Linux distribution

---

util/pkg/distributions/distributions.go

Cherry pick of #13617 on release-1.23.
#13617: Avoid resolv.conf file loopback for Flatcar distro
```release-note
```

Automated cherry pick of #13617: Avoid resolv.conf file loopback for Flatcar distro

---

tests/e2e/pkg/tester/skip_regex.go

Background:
We had been skipping this test ourselves until https://github.com/kubernetes/kops/pull/11966 when the skip logic in the test itself was updated to not run when CSI was enabled. 
Now https://github.com/kubernetes/kubernetes/pull/109649 removed the skip logic altogether due to improper use and the test is incorrectly not being skipped. The PR discussion mentions these tests can be removed since they _should_ be unconditionally skipped, but until that happens we can skip it ourselves.
This will fix many test jobs using CI or release/latest k8s version markers:
https://testgrid.k8s.io/kops-misc#kops-grid-scenario-terraform
https://testgrid.k8s.io/kops-misc#kops-grid-scenario-no-irsa
https://testgrid.k8s.io/kops-misc#kops-aws-external-dns

Skip in-tree volume limits test

---

upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template

if we use bind-address 127.0.0.1 we cannot fetch for instance prometheus metrics from the controller.

remove bind address for occm

---

pkg/model/bootstrapscript.go
upup/pkg/fi/cloudup/awstasks/classic_load_balancer.go
upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
upup/pkg/fi/cloudup/dotasks/loadbalancer.go
upup/pkg/fi/cloudup/gcetasks/address.go
upup/pkg/fi/cloudup/openstacktasks/floatingip.go
upup/pkg/fi/cloudup/openstacktasks/instance.go
upup/pkg/fi/has_address.go

Hetzner load balancers have internal IPv4, external IPv4 and external IPv6.
This PR makes it possible for tasks with `HasAddress` implemented to return multiple addresses via `FindAddresses()`.

Allow returning multiple addresses for API

---

upup/pkg/fi/cloudup/dotasks/droplet.go

we might as well remove the checks, but it's ok to keep them I guess.
Fixes: #13627

[DigitalOcean]: make droplet image constant when building droplet in for fitask

---

pkg/model/components/awscloudcontrollermanager.go
pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content

/cc @olemarkus @rifelpet 
The `Test_RunKubeApiserverBuilder` test should be fixed in a more permanent way separately.

Use fixed staging AWS CCM for k8s 1.24+

---

tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_master-us-test-1a.masters.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_launch_template_nodes.minimal-ipv6.example.com_user_data
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/runc.go
upup/pkg/fi/http.go

Ref: https://github.com/opencontainers/runc/releases/tag/v1.1.2

Update runc to v1.1.2

---

docs/cluster_spec.md

`spec.cloudConfig.manageStorageClasses` is undocumented despite being
cloud-wide setting. Adding description for that option.

Update documentation for manageStorageClasses

---

docs/instance_groups.md

Fix a typo found in instance groups documentation.

fix typo in docs/instance-groups.md

---

tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/runc.go
upup/pkg/fi/http.go

Cherry pick of #13638 on release-1.23.
#13638: Update runc to v1.1.2
```release-note
```

Automated cherry pick of #13638: Update runc to v1.1.2

---

pkg/model/components/awscloudcontrollermanager.go
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-1.24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content

/hold for images to be published
https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/US/provider-aws/cloud-controller-manager
The build for 1.21.0 has failed so image cannot be promoted for now:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-aws-push-images/1524937450936340480
The build for 1.22.1 cannot start due to a version related bug:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/13644/pull-kops-latest-e2e-aws-k8s-1-22/1525104500518424576/artifacts/cluster-info/kube-system/aws-cloud-controller-manager-kbrzg/logs.txt

Update AWS CCM to 13.05.2022 releases

---

cmd/kops/integration_test.go
pkg/testutils/golden/compare.go

We require that all generated files are in the data directory, so we
can simplify the logic here.

Tweak integration tests to be simpler

---

upup/pkg/fi/cloudup/hetzner/cloud.go

Somehow editing clusters is conditioned by `FindClusterStatus`.

Allow editing clusters with Hetzner

---

docs/addons.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template

Provide a way to override the pod's list of DNS nameservers to use so
that split-view DNS zones still work for things like DNS01 challenges.
Without this the DNS TXT records are searched for in the private DNS
zone instead of the public one and the challenge will never succeed.

Add a nameservers parameter for cert-manager.

---

cmd/kops/upgrade_cluster.go
docs/cli/kops_upgrade_cluster.md
docs/releases/1.24-NOTES.md

This will allow setting the exact (patch) k8s version when upgrading a cluster:
```sh
$ kops upgrade cluster --kubernetes-version=1.23.6
```
Fixes: #13614

Allow overriding the kubernetes version when upgrading the cluster

---

upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstack/loadbalancer.go
upup/pkg/fi/cloudup/openstack/mock_cloud.go
upup/pkg/fi/cloudup/openstacktasks/lb.go
upup/pkg/fi/cloudup/openstacktasks/lblistener.go
upup/pkg/fi/cloudup/openstacktasks/poolassociation.go

In the last PR to support OVN provider for LB, listener will refer to
load balancer provider for ACL settings. While currently get listener
API returns empty Pools, which will cause nil pointer dereference when
referring Pool.Loadbalancer.Provider.
This commit fix this issue by getting pool information with
DefaultPoolID when Pools is empty. As I added GetPool function, the
origin GetPool function is renamed to GetPoolMember.

Fix kops update for OpenStack with LB

---

channels/alpha

* https://github.com/kubernetes/kubernetes/releases/tag/v1.21.13
* https://github.com/kubernetes/kubernetes/releases/tag/v1.22.10
* https://github.com/kubernetes/kubernetes/releases/tag/v1.23.7

bump alpha k8s versions with May releases

---

protokube/cmd/protokube/main.go

Cherry pick of #13692 on release-1.23.
#13692: Fix Protokube gossip flag
```release-note
```

Automated cherry pick of #13692: Fix Protokube gossip flag

---

docs/index.md
docs/manifests_and_customizing_via_api.md

/kind documentation
Go doc link path is case-sensitive, so use all-lowercase `kops` in the path.

Fix links to go docs

---

nodeup/pkg/model/kube_apiserver.go
nodeup/pkg/model/kube_controller_manager.go
nodeup/pkg/model/kube_proxy.go
nodeup/pkg/model/kube_scheduler.go

1.25 is when official images have been migrated to registry.k8s.io, so we only need to rewrite until 1.25
This should fix all the prow jobs using the CI k8s version markers like https://testgrid.k8s.io/kops-misc#kops-grid-scenario-cilium10-amd64
They started failing between these k/k commits which include the upstream registry migration: https://github.com/kubernetes/kubernetes/compare/5219122d0ccd36...8415ae647d2c43

Only rewrite to k8s.gcr.io until k8s 1.25

---

pkg/model/bootstrapscript.go
pkg/model/resources/nodeup.go

Digital Ocean cloud provider image has `/etc/machine-id` baked into the image. And as a result when nodeup executes `system-id-machine-setup` it re-creates a new machine-id and as a result we lose track of journal entries. The only fix is to restart journald to view the system logs again. 
The fix here will ensure that journald is restarted on node startup so we don't need an explicit restart manually.
This should also help us to view the logs in our test-grid artifacts. Currently it shows empty [here](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-do-calico/1532344823695020032/artifacts/10.124.0.7/journal.log) 
FYI - @timoreimann 
Reference - https://serverfault.com/questions/1058259/journalctl-stops-working-randomly-after-boot-on-digitalocean-droplet

[DigitalOcean] Restart journald service on node startup

---

channels/pkg/cmd/apply_channel.go
go.mod

Cherry pick of #13749 on release-1.24.
#13749: Channels to have exit status 1 on apply failure
```release-note
```

Automated cherry pick of #13749: Channels to have exit status 1 on apply failure

---

Makefile
docs/cluster_spec.md
k8s/crds/kops.k8s.io_clusters.yaml
k8s/crds/kops.k8s.io_instancegroups.yaml
nodeup/pkg/model/file_assets.go
pkg/apis/kops/cluster.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/cluster.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go

Add a `Mode` field to `FileAssetSpec` so the mode of a file asset can be specified, maintaining the current default of `0440`.
---
The motivating example for this is as follows:
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
name: hello-world.local
spec:
fileAssets:
- content: |
#! /usr/bin/env bash
echo "Hello, world!"
mode: "0550"
name: hello-world
path: /usr/local/bin/hello-world
hooks:
- manifest: |
[Unit]
Description=Say hello to the world
[Service]
Type=oneshot
Restart=no
ExecStart=/usr/local/bin/hello-world
name: hello-world.service
useRawManifest: true
```

Add support for setting mode field on file assets

---

Makefile
docs/cluster_spec.md
k8s/crds/kops.k8s.io_clusters.yaml
k8s/crds/kops.k8s.io_instancegroups.yaml
nodeup/pkg/model/file_assets.go
pkg/apis/kops/cluster.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/cluster.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go

Cherry pick of #13715 on release-1.24.
#13715: Fix codegen targets and whitespace errors in Makefile
```release-note
```

Automated cherry pick of #13715: Add support for setting mode field on file assets

---

channels/pkg/channels/apply.go

Fixes: #13754
This reverts commit 18c5d184e77508b9e742fa1067175761a01c398a.

Revert "Use kubectl replace instead of apply when updating addons"

---

channels/pkg/channels/apply.go

Cherry pick of #13761 on release-1.24.
#13761: Revert "Use kubectl replace instead of apply when updating
```release-note
```

Automated cherry pick of #13761: Revert "Use kubectl replace instead of apply when updating

---

tests/integration/update_cluster/nvidia/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/nvidia/data/aws_s3_object_minimal.example.com-addons-nvidia.addons.k8s.io-k8s-1.16_content
upup/models/cloudup/resources/addons/nvidia.addons.k8s.io/k8s-1.16.yaml

nvidia has stopped publishing to docker hub:
> As of the v0.12.0 release, no new images will be published to dockerhub
> 
> Please use the images from the NGC catalog instead https://catalog.ngc.nvidia.com/orgs/nvidia/containers/k8s-device-plugin
ref https://github.com/kubernetes/kops/pull/13580#issuecomment-1148576210

Bump nvidia device plugin to 0.12.0

---

pkg/model/components/awscloudcontrollermanager.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/aws-cloud-controller.addons.k8s.io-k8s-1.18.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml

Cherry pick of #13748 on release-1.24.
#13748: Update AWS CCM images for k8s 1.20-1.22
```release-note
```

Automated cherry pick of #13748: Update AWS CCM images for k8s 1.20-1.22

---

tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/runc.go

Cherry pick of #13763 on release-1.23.
#13763: Update runc to v1.1.3
```release-note
```

Automated cherry pick of #13763: Update runc to v1.1.3

---

upup/pkg/fi/cloudup/awstasks/sshkey.go

Trying to fix the issue described in https://github.com/kubernetes/kops/pull/13768#issuecomment-1152518095.

Avoid spurious changes with ed25519 keys

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #13773 on release-1.24.
#13773: Fix namespace for cert manager webhook config
```release-note
```

Automated cherry pick of #13773: Fix namespace for cert manager webhook config

---

docs/releases/1.24-NOTES.md

The reason kops 1.23 is that SSA will ensure the API version of the snapshot controller is updated. CSA does not support this.

Make the cert-manager breaking change more visible.

---

upup/pkg/fi/cloudup/awstasks/sshkey.go

Cherry pick of #13774 on release-1.23.
#13774: Avoid spurious changes with ed25519 keys
```release-note
```

Automated cherry pick of #13774: Avoid spurious changes with ed25519 keys

---

upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml

Cherry pick of #13779 on release-1.24.
#13779: Add back the metrics-server 443 port with a new name
```release-note
```

Automated cherry pick of #13779: Add back the metrics-server 443 port with a new name

---

upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml

SSA is keyed on port, but requires unqiue name. So we need to add this back to avoid a duplicate port name error.
After this change, kops does own the value and we can remove this some time in the future.

Add back the metrics-server 443 port with a new name

---

upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template

Cherry pick of #13781 on release-1.24.
#13781: Fix broken node selector for node termination handler
```release-note
```

Automated cherry pick of #13781: Fix broken node selector for node termination handler

---

pkg/pki/sshkey.go

Don't rely on the `golang.org/x/crypto` library to keep consistent,
non-exported type names.

Use exported interface to detect SSH key type

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.23_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.23_content
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.23.yaml.template

Cherry pick of #13809 on release-1.24.
#13809: replace flexdriver with busybox
```release-note
```

Automated cherry pick of #13809: replace flexdriver with busybox

---

channels/alpha

* https://github.com/kubernetes/kubernetes/releases/tag/v1.21.14
* https://github.com/kubernetes/kubernetes/releases/tag/v1.22.11
* https://github.com/kubernetes/kubernetes/releases/tag/v1.23.8
* https://cloud-images.ubuntu.com/locator/ec2/

bump k8s versions and ubuntu ami (aws) in alpha channel

---

tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_object_nthsqsresources.longclustername.example.com-addons-bootstrap_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_object_nthsqsresources.longclustername.example.com-addons-node-termination-handler.aws-k8s-1.11_content
upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template

I am missing the port declaration for metrics in the nth deployment.
Also it seems its not possible to enable it at all.

add metric port to nth deployment

---

tests/e2e/pkg/tester/skip_regex.go

All cilium tests started failing recently: https://testgrid.k8s.io/kops-network-plugins#kops-aws-cni-cilium
Related to https://github.com/cilium/cilium/issues/18241

Skip known failing cilium e2e test

---

docs/releases/1.24-NOTES.md
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template

Cherry pick of #13846 on release-1.24.
#13846: Do not run CAS on spot instances
```release-note
```

Automated cherry pick of #13846: Do not run CAS on spot instances

---

pkg/model/gcemodel/autoscalinggroup.go
pkg/resources/gce/gce.go
tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf

Issues:
* resource tracking misses some of the FirewallRule resources:
```
Network:e2e-pr13857-pull-kops-e2e-k8s-gce-k8s-local
E0623 10:05:51.789873   38732 op.go:136] GCE operation failed: googleapi: Error 400: The network resource 'projects/k8s-jkns-gce-serial-1-4/global/networks/e2e-pr13857-pull-kops-e2e-k8s-gce-k8s-local' is already being used by 'projects/k8s-jkns-gce-serial-1-4/global/firewalls/ssh-external-to-node-ipv6-e2e-pr13857-pull-kops-e2e-k8s--dkfkq0'
Network:e2e-pr13857-pull-kops-e2e-k8s-gce-k8s-local	error deleting resources, will retry: googleapi: Error 400: The network resource 'projects/k8s-jkns-gce-serial-1-4/global/networks/e2e-pr13857-pull-kops-e2e-k8s-gce-k8s-local' is already being used by 'projects/k8s-jkns-gce-serial-1-4/global/firewalls/ssh-external-to-node-ipv6-e …
```

Fix GCE resource tracking

---

upup/pkg/fi/cloudup/gce/labels.go
upup/pkg/fi/cloudup/gce/utils.go

Some tests still fail:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-gce-calico-u2004-k22-containerd/1540027335678365696
```
W0623 17:44:09.192151    6112 executor.go:139] error running task "FirewallRule/master-to-master-e2e-e2e-kops-grid-gce-calico-u2004-k22--1m2qc6" (9m46s remaining to succeed): error creating FirewallRule: googleapi: Error 400: Invalid value for field 'resource.sourceTags[0]': 'e2e-e2e-kops-grid-gce-calico-u2004-k22-containerd-k8s-local-k8s-io-role-master'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'
More details:
Reason: invalid, Message: Invalid value for field 'resource.sourceTags[0]': 'e2e-e2e-kops-grid-gce-calico-u2004-k22-containerd-k8s-local-k8s-io-role-master'. Must be a match of regex …
```

Limit GCE tag for role to 63 chars

---

pkg/model/gcemodel/autoscalinggroup.go
pkg/resources/gce/gce.go
tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf

Cherry pick of #13857 on release-1.24.
#13857: Fix GCE resource tracking
```release-note
```

Automated cherry pick of #13857: Fix GCE resource tracking

---

upup/pkg/fi/cloudup/gce/labels.go
upup/pkg/fi/cloudup/gce/utils.go

Cherry pick of #13866 on release-1.24.
#13866: Limit GCE tag for role to 63 chars
```release-note
```

Automated cherry pick of #13866: Limit GCE tag for role to 63 chars

---

channels/pkg/channels/apply.go
tests/e2e/scenarios/upgrade-ab/run-test.sh

* `kubectl replace --force=true` always deletes and creates objects, causing havoc and breakage everywhere.
* `kubectl apply` can update and create objects, but does a strategic merge, which means in many cases arrays are merged. This leaves behind containers, ports and other things that causes apply to fail.
* `kubectl replace --force=false` cannot create objects, but does a "normal" merge of objects, meaning lists are _not_ merged, but replaced entirely. This is the behavior we want.
Combining `kubectl apply` with `kubectl replace` seems to be what we want right now until we know the kubectl client side apply doesnt' manage any fields.
/kind office-hours

Replace manifests after apply

---

channels/pkg/channels/apply.go
tests/e2e/scenarios/upgrade-ab/run-test.sh

Cherry pick of #13819 on release-1.24.
#13819: Replace manifests after apply
```release-note
```

Automated cherry pick of #13819: Replace manifests after apply

---

tests/e2e/go.mod
tests/e2e/go.sum

Ref https://github.com/kubernetes-sigs/kubetest2/pull/183
I faintly remember something about us assuming binaries are in artifacts.

Bump kubetest2 to test rundir

---

.github/workflows/update-deps.yml
Makefile

Some dependencies require updated cli docs, as it can be seen in https://github.com/kubernetes/kops/pull/13882.

Generate cli docs after updating dependencies

---

pkg/instancegroups/instancegroups.go

Cherry pick of #13896 on release-1.24.
#13896: Log errors from detachInstance
```release-note
```

Automated cherry pick of #13896: Log errors from detachInstance

---

cmd/kops/create_cluster.go
cmd/kops/integration_test.go
cmd/kops/lifecycle_integration_test.go
docs/cli/kops_create_cluster.md
docs/getting_started/gce.md
hack/dev-build-gce.sh
pkg/clouds/supported.go
pkg/featureflag/featureflag.go
tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/scenarios/upgrade-ha-leader-migration/run-test.sh
upup/pkg/fi/cloudup/apply_cluster.go

GCE support seems stable now, and we have good clarity at the API
level and how that translates to GCP resources, which was our blocker
previously.
Drop the need for the feature-flag.

gce: Move out of beta, drop feature flag

---

upup/pkg/fi/cloudup/gcetasks/instancetemplate.go

Because of how we compare InstanceTemplates, this was causing spurious
differences.
Add the minimal support, setting the value to the default.

gce: set ProvisioningModel on InstanceTemplate

---

upup/pkg/fi/cloudup/gcetasks/instancetemplate.go

Cherry pick of #13902 on release-1.24.
#13902: gce: set ProvisioningModel on InstanceTemplate
```release-note
```

Automated cherry pick of #13902: gce: set ProvisioningModel on InstanceTemplate

---

cmd/kops/create_cluster.go
cmd/kops/integration_test.go
cmd/kops/lifecycle_integration_test.go
docs/cli/kops_create_cluster.md
docs/getting_started/gce.md
hack/dev-build-gce.sh
pkg/clouds/supported.go
pkg/featureflag/featureflag.go
tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/scenarios/upgrade-ha-leader-migration/run-test.sh
upup/pkg/fi/cloudup/apply_cluster.go

Cherry pick of #13903 on release-1.24.
#13903: gce: Move out of beta, drop feature flag
```release-note
```

Automated cherry pick of #13903: gce: Move out of beta, drop feature flag

---

pkg/apis/kops/validation/legacy.go

Fixes: https://github.com/kubernetes/kops/issues/13817
I add validation for S3 bucket name of IRSA.
It should not contain dots because of the wildcard certificate.

Add validation for IRSA bucket name which contains dots

---

pkg/resources/gce/gce.go

Cluster name hashes should be calculated on the safe cluster name.
Ref: https://github.com/kubernetes/kops/pull/13869

Fix cleanup of firewall rules that contain targets with the cluster name hash

---

pkg/resources/gce/gce.go

Cherry pick of #13907 on release-1.24.
#13907: Fix cleanup of firewall rules that contain the cluster name
```release-note
```

Automated cherry pick of #13907: Fix cleanup of firewall rules that contain the cluster name

---

pkg/model/gcemodel/context.go
pkg/model/master_volumes.go
pkg/resources/gce/gce.go
upup/pkg/fi/cloudup/gce/utils.go

This will help simplify long resource name fixing for GCE.

gce: Refactor ClusterPrefixedName and ClusterSuffixedName to not return error

---

pkg/model/gcemodel/context.go
pkg/model/master_volumes.go
pkg/resources/gce/gce.go
upup/pkg/fi/cloudup/gce/utils.go

Cherry pick of #13920 on release-1.24.
#13920: Refactor ClusterPrefixedName and ClusterSuffixedName to not
```release-note
```

Automated cherry pick of #13920: Refactor ClusterPrefixedName and ClusterSuffixedName to not

---

tests/integration/update_cluster/minimal_gossip/data/aws_s3_object_minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_gossip/data/aws_s3_object_minimal.k8s.local-addons-coredns.addons.k8s.io-k8s-1.12_content
tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_object_minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_object_minimal.k8s.local-addons-coredns.addons.k8s.io-k8s-1.12_content
upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template

This should fix the failing `ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer` test for GCE:
https://testgrid.k8s.io/kops-gce#kops-grid-gce-calico-u2004-k24-containerd

Mount /etc/hosts from host for CoreDNS

---

docs/addons.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/model/components/addonmanifests/awsloadbalancercontroller/iam.go
pkg/model/iam/iam_builder.go
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml.template

I sort of broke my own principle of adding something to 1.24 now, but this completes the work done by allowing WAF plugins to be enabled. The plugin is marked as beta in the docs and disabled by default, so the risk should be low.

Make it possible to enable the shield addon for LBC

---

docs/addons.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/model/components/addonmanifests/awsloadbalancercontroller/iam.go
pkg/model/iam/iam_builder.go
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml.template

Cherry pick of #13929 on release-1.24.
#13929: Make it possible to enable the shield addon for LBC
```release-note
```

Automated cherry pick of #13929: Make it possible to enable the shield addon for LBC

---

tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template

Cherry pick of #13926 on release-1.24.
#13926: Make IRSA webhook configure apps to use regional STS and set
```release-note
```

Automated cherry pick of #13926: Make IRSA webhook configure apps to use regional STS and set

---

pkg/apis/kops/validation/validation_test.go
pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.11.yaml.template
upup/pkg/fi/cloudup/template_functions.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

- Upstream changed the default health port to 9879 so add support for that in a backwards compatible way ([ref](https://github.com/cilium/cilium/pull/19830))
- Upstream also removed the `scheduler.alpha.kubernetes.io/critical-pod` annotation from their manifests so do the same to ours as the last version of Kubernetes to support that annotation was 1.16 which is not supported by Kops ([ref](https://github.com/cilium/cilium/pull/18667))

Update Cilium to 1.11.6

---

pkg/model/gcemodel/context.go
upup/pkg/fi/cloudup/gce/gce_cloud.go

Cherry pick of #13873 on release-1.24.
#13873: Limit GCE names to 63 chars for various resources
```release-note
```

Automated cherry pick of #13873: Limit GCE names to 63 chars for various resources

---

tests/integration/update_cluster/minimal_gossip/data/aws_s3_object_minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_gossip/data/aws_s3_object_minimal.k8s.local-addons-coredns.addons.k8s.io-k8s-1.12_content
tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_object_minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_object_minimal.k8s.local-addons-coredns.addons.k8s.io-k8s-1.12_content
upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template

Cherry pick of #13922 on release-1.24.
#13922: Mount /etc/hosts from host for CoreDNS
```release-note
```

Automated cherry pick of #13922: Mount /etc/hosts from host for CoreDNS

---

pkg/apis/kops/validation/validation_test.go
pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.11.yaml.template
upup/pkg/fi/cloudup/template_functions.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #13917 on release-1.24.
#13917: Update Cilium to 1.11.6
```release-note
```

Automated cherry pick of #13917: Update Cilium to 1.11.6

---

pkg/model/awsmodel/autoscalinggroup.go
tests/integration/update_cluster/mixed_instances/cloudformation.json
tests/integration/update_cluster/mixed_instances/kubernetes.tf
upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go

Cherry pick of #13852 on release-1.24.
#13852: Fix unsetting ASG max price
```release-note
```

Automated cherry pick of #13852: Fix unsetting ASG max price

---

upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml

Cherry pick of #13940 on release-1.24.
#13940: Revert "Add back the metrics-server 443 port with a new name"
```release-note
```

Automated cherry pick of #13940: Revert "Add back the metrics-server 443 port with a new name"

---

protokube/pkg/protokube/openstack_volume.go
protokube/pkg/protokube/openstack_volume_test.go
protokube/pkg/protokube/testdata/metadata_drive.json
protokube/pkg/protokube/testdata/metadata_service.json
vendor/k8s.io/utils/exec/testing/fake_exec.go
vendor/modules.txt

This adds the config drive as an additional source for instance metadata when using OpenStack.
The reasoning behind this is that the Metadata Service may not always be reachable. For example when not using DHCP on a tenant network, or using a provider network (and at least according to our OpenStack support, the config drive is far more stable to use than the Metadata Service).
Currently, the search order is hard coded to `configDrive, metadataService`. So the code tries to look up the metadata in the config drive first and if not successful it will query the Metadata Service Endpoint. I did it this way because I think/assume the config drive lookup will fail faster in case it is not available.
Basically, the code is lifted/borrowed and adapted from the external OpenStack provider:
* …

Add config drive as a source for OpenStack instance metadata

---

upup/pkg/fi/cloudup/openstacktasks/instance.go
upup/pkg/fi/cloudup/openstacktasks/instance_test.go

This adds an additional filter for ports attached to an instance, so that only ports tagged with the cluster name will be considered.
Basically, this enables adding ports to the server independent from the provisioning process.
Without the change updating the cluster after adding custom ports it will throw the following error:
```
W0623 22:18:29.426867   27313 executor.go:139] error running task "Instance/instance-name" (9m59s remaining to succeed): found more than one port for instance edb5ab73-1234-1234-1234-01b3b5565ba4
```

Be more specific when filtering OS instance ports

---

docs/README.md

Fix broken links.
> **note**
> The diagram has been already removed in the following PR.
> ref: https://github.com/kubernetes/kops/commit/9187f3bd8d8579831ed5fe6dea8b8ed6708f3938

Fix broken links

---

cmd/kops/integration_test.go
tests/integration/update_cluster/complex/cloudformation.json
tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
tests/integration/update_cluster/complex/data/aws_iam_role_policy_masters.complex.example.com_policy
tests/integration/update_cluster/complex/data/aws_launch_template_master-us-test-1a.masters.complex.example.com_user_data
tests/integration/update_cluster/complex/data/aws_launch_template_nodes.complex.example.com_user_data
tests/integration/update_cluster/complex/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-authentication.aws-k8s-1.12_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-bootstrap_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-kops-controller.addons.k8s.io-k8s-1.16_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-leader-migration.rbac.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-storage-aws.addons.k8s.io-v1.15.0_content
tests/integration/update_cluster/complex/data/aws_s3_object_etcd-cluster-spec-events_content
tests/integration/update_cluster/complex/data/aws_s3_object_etcd-cluster-spec-main_content
tests/integration/update_cluster/complex/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/complex/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
tests/integration/update_cluster/complex/in-v1alpha2.yaml
tests/integration/update_cluster/complex/kubernetes.tf
upup/pkg/fi/cloudup/template_functions.go

1.24 stopped including the master node-role label:
https://github.com/kubernetes/kops/blob/d0583189fdbe8627edbe371c947cff5a9b7bbea1/pkg/nodelabels/builder.go#L87-L93

Fix AWS IAM Authenticator nodeSelector in k8s 1.24 

---

cmd/kops/integration_test.go
tests/integration/update_cluster/complex/cloudformation.json
tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
tests/integration/update_cluster/complex/data/aws_iam_role_policy_masters.complex.example.com_policy
tests/integration/update_cluster/complex/data/aws_launch_template_master-us-test-1a.masters.complex.example.com_user_data
tests/integration/update_cluster/complex/data/aws_launch_template_nodes.complex.example.com_user_data
tests/integration/update_cluster/complex/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-authentication.aws-k8s-1.12_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-bootstrap_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-kops-controller.addons.k8s.io-k8s-1.16_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-leader-migration.rbac.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-storage-aws.addons.k8s.io-v1.15.0_content
tests/integration/update_cluster/complex/data/aws_s3_object_etcd-cluster-spec-events_content
tests/integration/update_cluster/complex/data/aws_s3_object_etcd-cluster-spec-main_content
tests/integration/update_cluster/complex/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/complex/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
tests/integration/update_cluster/complex/in-v1alpha2.yaml
tests/integration/update_cluster/complex/kubernetes.tf
upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #13965 on release-1.24.
#13965: Use control-plane node role for AWS IAM Authenticator
```release-note
```

Automated cherry pick of #13965: Use control-plane node role for AWS IAM Authenticator

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go

Cherry pick of #13970 on release-1.24.
#13970: Skip deregistering the instance during rolling update for
```release-note
```

Automated cherry pick of #13970: Skip deregistering the instance during rolling update for

---

channels/alpha

* https://github.com/kubernetes/kubernetes/releases/tag/v1.22.12
* https://github.com/kubernetes/kubernetes/releases/tag/v1.23.9
* https://github.com/kubernetes/kubernetes/releases/tag/v1.24.3

bump alpha channel k8s releases

---

tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-authentication.aws-k8s-1.12_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/manifest.yaml

Cherry pick of #13979 on release-1.24.
#13979: Upgrade aws-iam-authenticator to v0.5.9
```release-note
```

Automated cherry pick of #13979: Upgrade aws-iam-authenticator to v0.5.9

---

pkg/model/hetznermodel/servers.go
upup/pkg/fi/cloudup/hetznertasks/server.go

Recently, Hetzner started allowing to configure the Primary IPs for their servers. This makes it possible to disable IPv6.
/cc @justinsb @olemarkus @rifelpet

Use only IPv4 for Hetzner servers

---

pkg/model/hetznermodel/servers.go
upup/pkg/fi/cloudup/hetznertasks/server.go

Cherry pick of #13982 on release-1.24.
#13982: Use only IPv4 for Hetzner servers
```release-note
```

Automated cherry pick of #13982: Use only IPv4 for Hetzner servers

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/cluster.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/cluster.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template

Add option to set number of replicas for pod-identity-webhook

---

docs/cluster_spec.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/cluster.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/cluster.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/components/etcdmanager/model.go
pkg/model/components/etcdmanager/model_test.go
pkg/model/components/etcdmanager/tests/interval/cluster.yaml
pkg/model/components/etcdmanager/tests/interval/tasks.yaml

Cherry pick of #13975 on release-1.24.
#13975: Add option to set etcd-manager backup interval
```release-note
```

Automated cherry pick of #13975: Add option to set etcd-manager backup interval

---

.github/workflows/main.yml
cloudbuild.yaml

Cherry pick of #13994 on release-1.24.
#13994: Update Go to v1.18.4
```release-note
```

Automated cherry pick of #13994: Update Go to v1.18.4

---

docs/getting_started/hetzner.md

Mentions the need to set `S3_REGION` when using AWS S3 with Hetzner.

Add S3_REGION to Hetzner docs

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/cluster.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/cluster.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template

Cherry pick of #13986 on release-1.24.
#13986: Add option to set number of replicas for pod-identity-webhook
```release-note
```

Automated cherry pick of #13986: Add option to set number of replicas for pod-identity-webhook

---

tests/integration/update_cluster/external_dns/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/external_dns/data/aws_s3_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/external_dns_irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/external_dns_irsa/data/aws_s3_object_minimal.example.com-addons-external-dns.addons.k8s.io-k8s-1.19_content
upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/k8s-1.19.yaml.template

external-dns e2e job [started failing recently](https://testgrid.k8s.io/kops-misc#kops-aws-external-dns). The external-dns pods are never created and protokube reports these logs:
`I0718 22:38:45.861661    6318 apply.go:70] applying objects of kind: Deployment.apps`
`I0718 22:38:45.868537    6318 apply.go:116] updating apps/v1, Resource=deployments kube-system/external-dns`
`I0718 22:38:45.876239    6318 apply.go:70] applying objects of kind: Service`
`I0718 22:38:45.883606    6318 apply.go:123] creating /v1, Resource=services /external-dns
updating "external-dns.addons.k8s.io": error applying update from "s3://k8s-kops-prow/e2e-e2e-kops-aws-external-dns.test-cncf-aws.k8s.io/addons/external-dns.addons.k8s.io/k8s-1.19.yaml": failed to apply objects of kind Service: failed to create …

Add missing namespace to external-dns Service

---

upup/models/cloudup/resources/addons/digitalocean-csi-driver.addons.k8s.io/k8s-1.22.yaml.template

Fixes #14004
Sourced from https://github.com/digitalocean/csi-digitalocean/tree/master/deploy/kubernetes/releases/csi-digitalocean-v4.2.0

Upgrade DO CSI controller to 4.2.0

---

upup/models/cloudup/resources/addons/digitalocean-csi-driver.addons.k8s.io/k8s-1.22.yaml.template

Cherry pick of #14005 on release-1.24.
#14005: Upgrade DO CSI driver to 4.2.0
```release-note
```

Automated cherry pick of #14005: Upgrade DO CSI driver to 4.2.0

---

.github/workflows/main.yml

The CI workflow for MacOS stopped working, probably due to https://github.com/actions/virtual-environments/issues/5583.

Switch to latest MacOS version for CI

---

util/pkg/vfs/tests/gsfs_test.go
util/pkg/vfs/tests/s3fs_test.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>
Fatalf is equivalent to Logf followed by FailNow.There is no need to explicitly call FailNow

delete t.FailNow after t.Fatalf

---

.github/workflows/main.yml

Cherry pick of #14015 on release-1.24.
#14015: Switch to latest MacOS version for CI
```release-note
```

Automated cherry pick of #14015: Switch to latest MacOS version for CI

---

docs/networking/calico.md

This PR fixes hyperlinks in Calico docs in order to be displayed properly

fix hyperlinks in calico docs

---

upup/pkg/fi/nodeup/command.go

https://github.com/kubernetes/kops/pull/13542 explains the reasons behind this change.
Also the various reports on the issue: https://github.com/kubernetes/kops/issues/13540 https://github.com/kubernetes/kops/issues/13492 and https://github.com/kubernetes/kops/issues/13358.
/cc @justinsb @olemarkus

Revert to using instance private DNS name to lookup hostname

---

upup/pkg/fi/nodeup/BUILD.bazel
upup/pkg/fi/nodeup/command.go

Cherry pick of #14024 on release-1.23.
#14024: Revert to using instance private DNS name to lookup hostname
```release-note
```

Automated cherry pick of #14024: Revert to using instance private DNS name to lookup hostname

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.22_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.22_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_privatecanal.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_privatecanal.example.com-addons-networking.projectcalico.org.canal-k8s-1.22_content
upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.22.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.22.yaml.template

Cherry pick of #13908 #14009 on release-1.24.
#13908: Update Calico to v3.23.2
#14009: Update Calico to v3.23.3
```release-note
```

Automated cherry pick of #13908: Update Calico to v3.23.2 #14009: Update Calico to v3.23.3

---

cmd/kops/distrust_keypair.go

Fixes #14040
```bash
λ kops distrust keypair this-is-not-a-keypair 12345678910
Using cluster from kubectl context: my-cluster.local
Error: keyset not found
```

 Check keyset existence before attempting to distrust

---

cmd/kops/distrust_keypair.go

Cherry pick of #14041 on release-1.23.
#14041: Check keyset existence before attempting to distrust
```release-note
```

Automated cherry pick of #14041: Check keyset existence before attempting to distrust

---

cmd/kops/delete_instance.go

OpenStack and DigitalOcean should exhibit a similar behaviour:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x1071272b4]
goroutine 1 [running]:
k8s.io/kops/pkg/instancegroups.(*RollingUpdateCluster).reconcileInstanceGroup(0x1400111bc78)
k8s.io/kops/pkg/instancegroups/instancegroups.go:450 +0x2e4
k8s.io/kops/pkg/instancegroups.(*RollingUpdateCluster).drainTerminateAndWait(0x1400111bc78, 0x14000678c80, 0x19?)
k8s.io/kops/pkg/instancegroups/instancegroups.go:430 +0x7f8
k8s.io/kops/pkg/instancegroups.(*RollingUpdateCluster).UpdateSingleInstance(0x1400101fc78?, 0x14000678c80?, 0x50?)
k8s.io/kops/pkg/instancegroups/instancegroups.go:699 +0x194
main.RunDeleteInstance({0x108bb1b28, 0x140001a6008}, 0x0?, …
```

Fix SIGSEGV when deleting a Hetzner instance

---

cmd/kops/delete_instance.go

Cherry pick of #14046 on release-1.24.
#14046: Fix SIGSEGV when deleting a Hetzner instance
```release-note
```

Automated cherry pick of #14046: Fix SIGSEGV when deleting a Hetzner instance

---

nodeup/pkg/model/etcd_manager_tls.go

etcd-manager should accept using bundles already, and it will match current cert by matching with the primary key.
Fixes #14037

Use cabundle for etcd CA files to fix key rotation in HA clusters

---

tests/e2e/scenarios/addon-resource-tracking/run-test.sh

The staging artifacts for 1.21 has been removed, so using stable instead.

Use stable kops release for kops 1.21

---

tests/integration/update_cluster/privatedns1/data/aws_s3_object_privatedns1.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatedns1/data/aws_s3_object_privatedns1.example.com-addons-networking.weave-k8s-1.12_content
tests/integration/update_cluster/privateweave/data/aws_s3_object_privateweave.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateweave/data/aws_s3_object_privateweave.example.com-addons-networking.weave-k8s-1.12_content
upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml

should fix these jobs:
https://testgrid.k8s.io/kops-network-plugins#kops-aws-cni-kuberouter
https://testgrid.k8s.io/kops-network-plugins#kops-aws-cni-weave
[protokube](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-cni-weave/1552757304317710336/artifacts/ip-172-20-59-182.ap-northeast-2.compute.internal/protokube.log) reports these errors:
`updating "networking.weave": error applying update from "s3://k8s-kops-prow/e2e-e2e-kops-aws-cni-weave.test-cncf-aws.k8s.io/addons/networking.weave/k8s-1.12.yaml": failed to apply objects of kind rbac.authorization.k8s.io/v1, Kind=ClusterRole: namespace was set for cluster-scoped object "kube-system/weave-net"; failed to apply objects of kind rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding: namespace was set for cluster-scoped …

Remove namespaces from cluster-scoped resources in CNI manifests

---

tests/integration/update_cluster/privatedns1/data/aws_s3_object_privatedns1.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatedns1/data/aws_s3_object_privatedns1.example.com-addons-networking.weave-k8s-1.12_content
tests/integration/update_cluster/privateweave/data/aws_s3_object_privateweave.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateweave/data/aws_s3_object_privateweave.example.com-addons-networking.weave-k8s-1.12_content
upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml

Cherry pick of #14053 on release-1.24.
#14053: Remove namespaces from cluster-scoped resources in CNI
```release-note
```

Automated cherry pick of #14053: Remove namespaces from cluster-scoped resources in CNI

---

docs/getting_started/hetzner.md
pkg/model/hetznermodel/servers.go
upup/pkg/fi/cloudup/hetzner/cloud.go
upup/pkg/fi/cloudup/hetznertasks/servergroup.go

Follow-up to #14018.
/cc @justinsb @olemarkus

Enable rolling updates for Hetzner

---

pkg/model/bootstrapscript.go
upup/pkg/fi/cloudup/hetznertasks/loadbalancer.go

`FindAddresses()` may run before the public addresses are allocated and the Kubernetes API certificate will not work.

Wait for load balancer to be ready for Hetzner

---

nodeup/pkg/model/etcd_manager_tls.go

Cherry pick of #14054 on release-1.24.
#14054: Use cabundle for etcd CA files
```release-note
```

Automated cherry pick of #14054: Use cabundle for etcd CA files

---

channels/pkg/channels/apply.go

Current implementation is effectively a `kubectl replace` and will remove fields not in the objects (i.e those set by other controllers). This PR should make channels use server-side apply instead with a non-strategic merge.

Use SSA for updating addon channel objects

---

protokube/pkg/protokube/openstack_volume.go
protokube/pkg/protokube/openstack_volume_test.go
protokube/pkg/protokube/testdata/metadata_drive.json
protokube/pkg/protokube/testdata/metadata_service.json
vendor/k8s.io/utils/exec/testing/fake_exec.go
vendor/modules.txt

Cherry pick of #13845 on release-1.24.
#13845: Fix doc of NewOpenStackCloudProvider
```release-note
```

Automated cherry pick of #13845: Add config drive as a source for OpenStack instance metadata

---

k8s/crds/kops.k8s.io_clusters.yaml
nodeup/pkg/model/cloudconfig.go
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

This will allow to configure the [OpenStack CCM networking options](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#networking).

Allow configuring OpenStack CCM networking options

---

k8s/crds/kops.k8s.io_clusters.yaml
nodeup/pkg/model/cloudconfig.go
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

Cherry pick of #14017 on release-1.24.
#14017: Allow configuring OpenStack CCM networking options
```release-note
```

Automated cherry pick of #14017: Allow configuring OpenStack CCM networking options

---

util/pkg/vfs/s3context.go

I don't see a good reason to always print this message.

Set higher verbosity when logging the endpoint of non-AWS S3 backend

---

tests/integration/update_cluster/apiservernodes/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/apiservernodes/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/many-addons/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_minimal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/minimal-ipv6-private/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/minimal-ipv6/data/aws_s3_bucket_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_bucket_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/privatecanal/data/aws_s3_bucket_object_privatecanal.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml

Cherry pick of #14081 on release-1.23.
#14081: aws-ebs-csi-driver: remove preStop hook
```release-note
```

Automated cherry pick of #14081: aws-ebs-csi-driver: remove preStop hook

---

cmd/kops/root.go

Otherwise we break piped output with -ojson etc.

Positional deprecation warning should go to stderr

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

A combination of apiserver map handling when using server-side apply, CA injection and resource validation made it impossible for kops to remove this struct. However, kops should claim ownership of all fields so we can remove them all in a future version

Add back conversion struct to cert-manager CRDs

---

tests/e2e/templates/staticcpumanagerpolicy.tmpl

Since we update containerd/runc quite aggressively, and probably will continue to do so, we should run this test once a day or so.
Refs #14007

Add template for e2e test with cpuManagerPolicy: static

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

CI builds are stored in a different bucket

Specify the full url for CI versions in upgrade-ab tests

---

tests/integration/update_cluster/nvidia/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/nvidia/data/aws_s3_object_minimal.example.com-addons-nvidia.addons.k8s.io-k8s-1.16_content
upup/models/cloudup/resources/addons/nvidia.addons.k8s.io/k8s-1.16.yaml

Cherry pick of #13745 on release-1.24.
#13745: Bump nvidia device plugin to 0.12.0
```release-note
```

Automated cherry pick of #13745: Bump nvidia device plugin to 0.12.0

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

[Release Page](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.11.30)
Aligned according to https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.11/config/master/aws-k8s-cni.yaml
Noticed a couple of additional changes that were made within the past 2-3 weeks in the 1.11 release branch: 
- addition of a new RBAC rule (via https://github.com/aws/amazon-vpc-cni-k8s/pull/2032)
- Increase CPU requests (via https://github.com/aws/amazon-vpc-cni-k8s/pull/2040)

Bump AWS CNI to 1.11.3

---

tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_bucket_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/in-v1alpha2.yaml
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template

This patch fixes cilium pod annotations templating for 1.9 & 1.10.
very similar to https://github.com/kubernetes/kops/pull/13536

cilium: fix wrong pod annotations templating #1.23

---

upup/pkg/fi/cloudup/template_functions.go

Previous-gen instances lack a lot of features. For example CCM will fail to update NLBs if these are added to the cluster.

Don't add previous-gen instances to Karpenter provisioners

---

tests/e2e/pkg/tester/skip_regex.go

Skip testing the in-tree aws-ebs driver if CSI driver is enabled

---

tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/in-v1alpha2.yaml
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.11.yaml.template

Same as https://github.com/kubernetes/kops/pull/14105 but for latest kops version

cilium: fix wrong pod annotations templating

---

tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_object_nthsqsresources.longclustername.example.com-addons-bootstrap_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_object_nthsqsresources.longclustername.example.com-addons-node-termination-handler.aws-k8s-1.11_content
upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template

If not, when migrating from imds-mode to sqs-mode, the selectors will match the daemonset pods, which doesn't work with pdb.
This will only break when upgrading from a somewhat old kops version, but it's the cause of https://testgrid.k8s.io/kops-k8s-ci#kops-aws-addon-resource-tracking flakiness.

Add deployment-specific selectors to nth pdb

---

nodeup/pkg/model/kube_controller_manager.go
nodeup/pkg/model/kube_scheduler.go

Fixes #14100 
`kube-controller-manager` and `kube-scheduler` version of https://github.com/kubernetes/kops/pull/13264 .
Disable these flags because these are not accepted when logging-format is `json`.
* --logtostderr
* --alsologtostderr
* --log-file
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
And I confirmed kube-proxy, but there is no option regarding logging-format in [kube-proxy](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/). Of course, kops does not have such an option.
https://github.com/kubernetes/kops/blob/6f4bb0e4daf52084407491fb875f8621c1927eca/pkg/apis/kops/componentconfig.go#L238-L278

Disable some flags in kube-controller-manager and kube-scheduler when logging-format is not text

---

tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_object_nthsqsresources.longclustername.example.com-addons-bootstrap_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_object_nthsqsresources.longclustername.example.com-addons-node-termination-handler.aws-k8s-1.11_content
upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template

Cherry pick of #14113 on release-1.24.
#14113: Add deployment-specific selectors to nth pdb
```release-note
```

Automated cherry pick of #14113: Add deployment-specific selectors to nth pdb

---

nodeup/pkg/model/kube_controller_manager.go
nodeup/pkg/model/kube_scheduler.go

Cherry pick of #14115 on release-1.23.
#14115: Disable some flags in kube-controller-manager and
```release-note
```

Automated cherry pick of #14115: Disable some flags in kube-controller-manager and

---

channels/pkg/channels/addon.go
channels/pkg/channels/clientapplier.go
channels/pkg/channels/kubectlapplier.go
channels/pkg/cmd/apply_channel.go

I think it will take a while to get the custom client production grade. Reverting to 1.24 behavior so that we get working tests and that this does not block any release.
Introduces an Applier interface and keeps the custom client based implementation.

Revert back to using kubectl in channels

---

pkg/model/gcemodel/context.go
pkg/resources/gce/gce.go
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
upup/pkg/fi/cloudup/gce/utils.go

Cherry pick of #14134 on release-1.24.
#14134: Limit GCE network names to 63 chars
```release-note
```

Automated cherry pick of #14134: Limit GCE network names to 63 chars

---

cloudmock/aws/mockautoscaling/group.go
pkg/model/awsmodel/autoscalinggroup.go
pkg/model/awsmodel/nodeterminationhandler.go
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/in-v1alpha2.yaml
upup/pkg/fi/cloudup/awstasks/autoscalinglifecyclehook.go
upup/pkg/fi/cloudup/awstasks/sqs.go

If one enables warm pool, then disables it, kops does not clean up life cycle hooks. This PR fixes that.

Remove life cycle hooks when warmpool is disabled

---

pkg/resources/aws/aws.go
pkg/resources/aws/aws_test.go

Looks like we were indeed leaking IAM roles. The code has assumed that all roles are prefixed with the cluster name, which is true for the instance profile roles, but rarely true for the SA roles. The SA roles have almost always truncated names.

Plug the IAM role leak

---

channels/pkg/channels/clientapplier.go
pkg/applylib/applyset/applyset.go
pkg/applylib/applyset/applyset_test.go
pkg/applylib/applyset/health.go
pkg/applylib/applyset/interfaces.go
pkg/applylib/applyset/results.go
pkg/applylib/applyset/testdata/testapplyset/expected.yaml
pkg/applylib/applyset/tracker.go
pkg/applylib/doc.go
pkg/applylib/mocks/harness.go
pkg/applylib/mocks/mockkubeapiserver/apigrouplist.go
pkg/applylib/mocks/mockkubeapiserver/apiresourcelist.go
pkg/applylib/mocks/mockkubeapiserver/apiserver.go
pkg/applylib/mocks/mockkubeapiserver/apiversions.go
pkg/applylib/mocks/mockkubeapiserver/controllers.go
pkg/applylib/mocks/mockkubeapiserver/getresource.go
pkg/applylib/mocks/mockkubeapiserver/patchresource.go
pkg/applylib/mocks/mockkubeapiserver/putresource.go
pkg/kubemanifest/manifest.go

As per discussions in office hours, there are a few projects in the
community that all need this same functionality; introducing it using
"copy and paste" sharing for now.
This pulls code from the kpt and kubebuilder-declarative-pattern
projects; I am original author on it all.
- Introduce applylib
- Introduce mock kubeapiserver to applylib
- Introduce controller-oriented RESTMapper into applylib

Introduce library for applying objects

---

channels/alpha

* https://github.com/kubernetes/kubernetes/releases/tag/v1.22.13
* https://github.com/kubernetes/kubernetes/releases/tag/v1.23.10
* https://github.com/kubernetes/kubernetes/releases/tag/v1.24.4
* Found `20220810` to be the latest revision for all AWS regions through https://cloud-images.ubuntu.com/locator/ec2/ (under `focal`)

Bump k8s releases and Ubuntu AMI version in Alpha

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

/cc @hakman @rifelpet 
This should hopefully take case of the klatest upgrades, which are the last of the e2e unexpectedly failing.

Fix the non-ci markers

---

docs/addons.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

**What is this PR about? / Why do we need it?**
- This PR allows provisioning of aws-ebs-csi-driver externally. kOps 1.24 with K8s 1.24 enables `external-cloud-controller-manager` which requires CSI. If you disable the CSI driver: 
```
cloudConfig:
awsEBSCSIDriver:
enabled: false
```
you will encounter the following error: 
```
Error: completed cluster failed validation: spec.externalCloudControllerManager: Forbidden: AWS external CCM cannot be used without enabling spec.cloudConfig.AWSEBSCSIDriver.
```
**What testing is done?** 
- Old behavior:
```
$ ./kops update cluster --name old-behavior.k8s.local | grep ebs-csi-driver
I0822 17:02:48.070331  455254 apply_cluster.go:822] Populating instance group from upgradeSpecs
I0822 17:02:48.070369  455254 populate_instancegroup_spec.go:65] …
```

Allow self-managed aws-ebs-csi-driver

---

nodeup/pkg/model/kubelet.go
nodeup/pkg/model/kubelet_test.go
nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
nodeup/pkg/model/tests/kubelet/warmpool/tasks.yaml
pkg/apis/nodeup/config.go
pkg/model/tests/data/bootstrapscript_0.txt
pkg/model/tests/data/bootstrapscript_1.txt
pkg/model/tests/data/bootstrapscript_2.txt
pkg/model/tests/data/bootstrapscript_3.txt
pkg/model/tests/data/bootstrapscript_4.txt
pkg/model/tests/data/bootstrapscript_5.txt
pkg/model/tests/data/nodeupconfig_0.txt
pkg/model/tests/data/nodeupconfig_1.txt
pkg/model/tests/data/nodeupconfig_2.txt
pkg/model/tests/data/nodeupconfig_3.txt
pkg/model/tests/data/nodeupconfig_4.txt
pkg/model/tests/data/nodeupconfig_5.txt
pkg/testutils/cluster.go
upup/pkg/fi/cloudup/populate_instancegroup_spec.go

There are three places where one can configure `kubeletConfig` in our API: `kubelet` and `masterKubelet` in the cluster config, and `kubelet` in the `instancegroup`. If you want to do any sort of testing or validation of the kubeletconfig you have to validate all three places now as the configs are not merged until one tries to build nodeup config.
This PR does the merge in `populateInstanceGroup` instead so that one can always test against the IGs kubelet config.
Also some minor cleanups along the way. The golden output changes that comes a part of this should be fine.

Merge kubeletConfigs earlier

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
upup/models/cloudup/resources/addons/snapshot-controller.addons.k8s.io/k8s-1.20.yaml.template

Upstream has very inconsistent example deployments, and are not even using the latest images there. But I verified this to be working using the k8s e2e suite with snapshotting enabled.

Bump snapshot-controller to 6.0.1

---

pkg/model/issuerdiscovery.go

When reading the _kOps_ "service-account" key set in preparation for publishing the OIDC JWKS file (such as to S3 alongside the discovery document), in some cases the set contains items that either lack an X.509 certificate or contain such a certificate issued for a subject with common name other than "service-account." Ignore these extra key set items and instead only project JWKS keys for those with an X.509
certificate with the expected subject common name.
Refs: #14174

OIDC: Tolerate extra service-account key set items

---

pkg/model/issuerdiscovery.go

Cherry pick of #14175 on release-1.24.
#14175: OIDC: Tolerate extra service-account key set items
```release-note
```

Automated cherry pick of #14175: OIDC: Tolerate extra service-account key set items

---

nodeup/pkg/model/sysctls.go
pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #14137 on release-1.24.
#14137: Always disable rp_filter when using cilium
```release-note
```

Automated cherry pick of #14137: Always disable rp_filter when using cilium

---

tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.23/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-master-us-test1-a_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_bucket_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
upup/pkg/fi/cloudup/runc.go

Cherry pick of #14188 on release-1.23.
#14188: Update runc to v1.1.4
```release-note
```

Automated cherry pick of #14188: Update runc to v1.1.4

---

tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.k8s.local-addons-hcloud-csi-driver.addons.k8s.io-k8s-1.22_content
upup/models/cloudup/resources/addons/hcloud-csi-driver.addons.k8s.io/k8s-1.22.yaml.template

The last release for Hetzner CSI driver was 1 year ago. There were many improvements since then.
Until there is a new release, the latest build can be used.
Ref: https://github.com/hetznercloud/csi-driver/issues/310

Update CSI driver to latest for Hetzner

---

tests/e2e/pkg/tester/kubectl.go
tests/e2e/pkg/tester/tester.go

This is more or less an alternative version of https://github.com/kubernetes/kops/pull/13217 that uses the `artifacts.RunDir()` instead of interpreting `KUBETEST2_RUN_DIR` directly.
/cc @nckturner @rifelpet

Use runpath for kubectl binary

---

upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.22.yaml.template

In Calico's released versions, per projectcalico/calico#6522, when using the eBPF data plane, containers using host ports cannot respond to connection attempts correctly. These container receive the packets from the client forwarded after DNAT, but when they reply, there is no conntrack entry for the would-be connection, so _netfilter_ drops the reply packets, preventing the connection from completing. The client never receives the reply packets. The conntrack entry is missing because Calico mistakenly attempts to optimize it away.
Work around the problem by disabling [the Calico Felix program's 
"BPFHostConntrackBypass" feature](https://projectcalico.docs.tigera.io/reference/felix/configuration#ebpf-dataplane-configuration). This is a temporary measure until the Calico maintainers can …

Calico: Work around host port/conntrack problem

---

pkg/resources/aws/aws.go

If the error was an AWS error, but not one of the recognized ones, we
ignored it.

AWS IAM Role listing: don't ignore "other" errors

---

Makefile

This was broken in newer versions of go.

Makefile: Don't assume GOBIN is set

---

cmd/kops/integration_test.go
tests/integration/update_cluster/privateflannel/data/aws_iam_role_policy_masters.privateflannel.example.com_policy
tests/integration/update_cluster/privateflannel/data/aws_launch_template_master-us-test-1a.masters.privateflannel.example.com_user_data
tests/integration/update_cluster/privateflannel/data/aws_launch_template_nodes.privateflannel.example.com_user_data
tests/integration/update_cluster/privateflannel/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_etcd-cluster-spec-events_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_etcd-cluster-spec-main_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-aws-ebs-csi-driver.addons.k8s.io-k8s-1.17_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-kops-controller.addons.k8s.io-k8s-1.16_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-leader-migration.rbac.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-networking.flannel-k8s-1.25_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-storage-aws.addons.k8s.io-v1.15.0_content
tests/integration/update_cluster/privateflannel/in-v1alpha2.yaml
tests/integration/update_cluster/privateflannel/kubernetes.tf
upup/models/cloudup/resources/addons/networking.flannel/k8s-1.25.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

Cherry pick of #14226 on release-1.25.
#14226: Update Flannel to v0.19.2
```release-note
```

Automated cherry pick of #14226: Update Flannel to v0.19.2

---

pkg/resources/aws/aws.go

Cherry pick of #14215 on release-1.25.
#14215: AWS IAM Role listing: don't ignore "other" errors
```release-note
```

Automated cherry pick of #14215: AWS IAM Role listing: don't ignore "other" errors

---

upup/pkg/fi/cloudup/hetzner/cloud.go

Cherry pick of #14223 on release-1.25.
#14223: Remove warning for FindClusterStatus not implemented for
```release-note
```

Automated cherry pick of #14223: Remove warning for FindClusterStatus not implemented for

---

tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/populate_instancegroup_spec.go

This better matches the AWS machine, which is also a burstable 2 core
machine.  Without this pods sometimes fail to schedule on single core
machines.

GCE: change default control-plane instance type to e2-medium

---

pkg/model/components/clusterautoscaler.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content

Cherry pick of #14235 on release-1.25.
#14235: Bump cluster-autoscaler images
```release-note
```

Automated cherry pick of #14235: Bump cluster-autoscaler images

---

docs/releases/1.25-NOTES.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template

This feature was added on k8s autoscaler on Oct 2020: https://github.com/kubernetes/autoscaler/pull/3649
but kops didn't provide support to add it via the autoscaler addon
This PR adds it
Implements issue: https://github.com/kubernetes/kops/issues/14171

Add suport to --cordon-node-before-terminating autoscaler flag

---

docs/releases/1.25-NOTES.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template

Cherry pick of #14236 on release-1.25.
#14236: Add support to --cordon-node-before-terminating on the
```release-note
```

Automated cherry pick of #14236: Add support to --cordon-node-before-terminating on the

---

pkg/model/openstackmodel/servergroup.go
pkg/model/openstackmodel/servergroup_test.go
pkg/model/openstackmodel/tests/servergroup/truncate-cluster-names-to-42-characters.yaml
upup/pkg/fi/cloudup/openstacktasks/instance.go
upup/pkg/fi/cloudup/openstacktasks/instance_test.go

Openstack is not allowing object tag size of more than 60 characters, as
we can not rename a cluster we have to truncate and limit length to 42
for the tag value.

Fix openstack tag limitation

---

tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_object_nthsqsresources.longclustername.example.com-addons-bootstrap_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_object_nthsqsresources.longclustername.example.com-addons-node-termination-handler.aws-k8s-1.11_content
upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template

Cherry pick of #14244 on release-1.25.
#14244: aws-node-termination-handler: Add option to fetch node name
```release-note
```

Automated cherry pick of #14244: aws-node-termination-handler: Add option to fetch node name

---

tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_object_nthsqsresources.longclustername.example.com-addons-bootstrap_content
tests/integration/update_cluster/nth_sqs_resources/data/aws_s3_object_nthsqsresources.longclustername.example.com-addons-node-termination-handler.aws-k8s-1.11_content
upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template

on `aws-node-termination-handler`, fetch node name through Kubernetes node `.spec.providerID` since Kops use InstanceID as node name.
Ref:
- https://github.com/aws/aws-node-termination-handler/commit/701db81ccfb58d94c2b6df2b1bd273a442a4d05e

aws-node-termination-handler to match node using providerID instead of AWS DNS name

---

pkg/apis/kops/validation/validation.go

It's assumed users will manage the OIDC provider themselves in that case.
Fixes #13667

kOps managed OIDC provider is no longer needed for IRSA

---

channels/alpha
channels/stable

Currently pointing to `1.24.0` for `1.24+` and to `1.23.2` for all previous versions.
Bumping the recommended to the latest and greatest kOps 1.24.2 in both channels.

Update recommended kOps versions in alpha and stable

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template

Cherry pick of #14254 on release-1.25.
#14254: Fix CAS cordon flag
```release-note
```

Automated cherry pick of #14254: Fix CAS cordon flag

---

pkg/model/iam/iam_builder.go
tests/integration/update_cluster/aws-lb-controller/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm/data/aws_iam_role_policy_masters.minimal.example.com_policy
tests/integration/update_cluster/many-addons/data/aws_iam_role_policy_masters.minimal.example.com_policy

Cherry pick of #14255 on release-1.24.
#14255: AWS LBC needs ec2:DescribeVpcPeeringConnections for IPv6
```release-note
```

Automated cherry pick of #14255: AWS LBC needs ec2:DescribeVpcPeeringConnections for IPv6

---

.gitignore

Cherry pick of #13914 on release-1.24.
#13914: Ignore the _rundir that kubetest2 now creates
```release-note
```

Automated cherry pick of #13914: Ignore the _rundir that kubetest2 now creates

---

pkg/model/components/etcdmanager/model.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/populate_instancegroup_spec.go

Cherry pick of #14260 on release-1.25.
#14260: Bump verbosity level for some log statements
```release-note
```

Automated cherry pick of #14260: Bump verbosity level for some log statements

---

pkg/instancegroups/instancegroups.go
pkg/instancegroups/instancegroups_test.go

Cherry pick of #14251 on release-1.25.
#14251: Warm pool-enabled ASGs scaled to zero will no longer panic
```release-note
```

Automated cherry pick of #14251: Warm pool-enabled ASGs scaled to zero will no longer panic

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Cherry pick of #14265 on release-1.25.
#14265: bump aws-cni to version 1.11.4
```release-note
```

Automated cherry pick of #14265: bump aws-cni to version 1.11.4

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Backporting https://github.com/aws/amazon-vpc-cni-k8s/pull/2058
Missed that in previous PR

aws-cni clusterRole fix

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Cherry pick of #14272 on release-1.25.
#14272: remove 'get' from aws-cni clusterRole to reflect
```release-note
```

Automated cherry pick of #14272: remove 'get' from aws-cni clusterRole to reflect

---

cmd/kops/rolling-update_cluster.go
pkg/instancegroups/instancegroups.go
pkg/instancegroups/rollingupdate.go

If we do, we can't drain the node afterwards.  We also are going to
have dropped connections in this case anyway.

rolling-update: don't deregister our only apiserver

---

upup/pkg/fi/cloudup/hetznertasks/servergroup.go

Cherry pick of #14282 on release-1.25.
#14282: Delete the oldest servers when over the desired count for
```release-note
```

Automated cherry pick of #14282: Delete the oldest servers when over the desired count for

---

cmd/kops/edit_instancegroup.go
cmd/kops/edit_instancegroup_test.go
cmd/kops/test/edit_instance_group.yaml
pkg/model/awsmodel/autoscalinggroup_test.go
pkg/testutils/cluster.go
upup/pkg/fi/cloudup/awsup/aws_utils_test.go
upup/pkg/fi/cloudup/deepvalidate_test.go
upup/pkg/fi/cloudup/populate_cluster_spec_test.go
upup/pkg/fi/cloudup/populate_instancegroup_spec_test.go
upup/pkg/fi/cloudup/validation_test.go

Cherry pick of #14287 on release-1.25.
#14287: Add test for ensuring taints are merged correctly
```release-note
```

Automated cherry pick of #14287: Add test for ensuring taints are merged correctly

---

cmd/kops/edit_instancegroup_test.go
cmd/kops/test/edit_instance_group.yaml
pkg/client/simple/vfsclientset/instancegroup.go
pkg/commands/helpers_readwrite.go
pkg/testutils/integrationtestharness.go

This is technically a regression. kOps had the behavior where empty image meant use from channel. But this got removed due to strict validation of user input

User IG without image should be allowed

---

cmd/kops/edit_instancegroup_test.go
cmd/kops/test/edit_instance_group.yaml
pkg/client/simple/vfsclientset/instancegroup.go
pkg/commands/helpers_readwrite.go
pkg/testutils/integrationtestharness.go

Cherry pick of #14290 on release-1.25.
#14290: User IG without image should be allowed
```release-note
```

Automated cherry pick of #14290: User IG without image should be allowed

---

pkg/apis/kops/validation/legacy.go
pkg/model/hetznermodel/network.go
upup/models/cloudup/resources/addons/hcloud-cloud-controller.addons.k8s.io/k8s-1.22.yaml.template
upup/pkg/fi/cloudup/hetznertasks/loadbalancer.go
upup/pkg/fi/cloudup/hetznertasks/network.go
upup/pkg/fi/cloudup/hetznertasks/servergroup.go
upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #14294 on release-1.25.
#14294: Add support for using an existing network for Hetzner
```release-note
```

Automated cherry pick of #14294: Add support for using an existing network for Hetzner

---

tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.k8s.local-addons-hcloud-cloud-controller.addons.k8s.io-k8s-1.22_content
upup/models/cloudup/resources/addons/hcloud-cloud-controller.addons.k8s.io/k8s-1.22.yaml.template

Cherry pick of #14297 on release-1.25.
#14297: Update Hetzner CCM to v1.13.0
```release-note
```

Automated cherry pick of #14297: Update Hetzner CCM to v1.13.0

---

cmd/kops/create_cluster.go
docs/cli/kops_create_cluster.md

Backport of https://github.com/kubernetes/kops/pull/14295.

Add --network-id alias for --vpc flag

---

cmd/kops/create_cluster.go
docs/cli/kops_create_cluster.md

Cherry pick of #14326 on release-1.24.
#14326: Add --network-id alias for --vpc flag
```release-note
```

Automated cherry pick of #14326: Add --network-id alias for --vpc flag

---

docs/addons.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha3/componentconfig.go

When trying to enable Prometheus metrics for NTH, I naively set:
```
nodeTerminationHandler:
enablePrometheusMetrics: true
```
Add `prometheusEnable` to the docs to try to prevent such mistakes in the future. Also add `enableRebalanceMonitoring` for good measure, and a couple missing defaults to the struct field docstrings.
N.B. I almost certainly missed some code generation step or something. Please advise.

Add more details to the NTH documentation

---

pkg/model/bootstrapscript.go
tests/integration/update_cluster/private-shared-ip/cloudformation.json
tests/integration/update_cluster/private-shared-ip/cloudformation.json.extracted.yaml
tests/integration/update_cluster/privatecalico/cloudformation.json
tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
tests/integration/update_cluster/privatecilium/cloudformation.json
tests/integration/update_cluster/privatecilium/cloudformation.json.extracted.yaml
tests/integration/update_cluster/privatecilium2/cloudformation.json
tests/integration/update_cluster/privatecilium2/cloudformation.json.extracted.yaml
tests/integration/update_cluster/privateciliumadvanced/cloudformation.json
tests/integration/update_cluster/privateciliumadvanced/cloudformation.json.extracted.yaml

Cherry pick of #14318 on release-1.24.
#14318: Avoid spurious changes with bastion hosts due to user
```release-note
```

Automated cherry pick of #14318: Avoid spurious changes with bastion hosts due to user

---

docs/addons.md

Following the doc resulted in an error from kOps CLI
```
Error: error creating cluster: spec.certManager: Forbidden: Cert Manager requires that service accounts use external permissions in order to do dns-01 validation
```
because there is a typo in the doc

Fix typo in doc for enabling cert-manager dns-01 challenges

---

upup/pkg/fi/cloudup/new_cluster.go

Cherry pick of #14343 on release-1.25.
#14343: Validate `--zones` flag earlier
```release-note
```

Automated cherry pick of #14343: Validate `--zones` flag earlier

---

upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml

Reverts kubernetes/kops#14336 in favor of kubernetes/kops#14350.
/cc @olemarkus

Revert "Set metrics-server `--kubelet-preferred-address-types` by k8s version"

---

upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template

Alternative to https://github.com/kubernetes/kops/pull/14336.
/cc @olemarkus

hetzner: Fix metrics-server config to use internal IP

---

upup/pkg/fi/cloudup/apply_cluster.go

Similar to https://github.com/kubernetes/kops/pull/11657:
https://github.com/kubernetes/kops/blob/0be79b25b74e5bec3ddd0907918605b39600e1dd/upup/pkg/fi/cloudup/dns.go#L102

Set higher verbosity when logging Gossip DNS info

---

upup/pkg/fi/cloudup/apply_cluster.go

Cherry pick of #14339 on release-1.25.
#14339: Set higher verbosity when logging Gossip DNS info
```release-note
```

Automated cherry pick of #14339: Set higher verbosity when logging Gossip DNS info

---

cmd/kops/create_cluster.go
cmd/kops/create_cluster_integration_test.go
tests/integration/create_cluster/minimal-1.26-arm64/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-arm64/options.yaml
tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/private_gce/options.yaml
upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
upup/pkg/fi/cloudup/new_cluster.go

Cherry pick of #14347 on release-1.25.
#14347: Add create cluster test for arm64
```release-note
```

Automated cherry pick of #14347: Add create cluster test for arm64

---

k8s/crds/kops.k8s.io_clusters.yaml
nodeup/pkg/model/kubelet_test.go
pkg/apis/kops/cluster.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha3/cluster.go
upup/pkg/fi/cloudup/populate_cluster_spec_test.go
upup/pkg/fi/cloudup/populate_instancegroup_spec.go
upup/pkg/fi/cloudup/populate_instancegroup_spec_test.go
util/pkg/reflectutils/walk.go
util/pkg/reflectutils/walk_test.go

Cherry pick of #14333 on release-1.25.
#14333: Add test confirming json merge behavior
```release-note
```

Automated cherry pick of #14333: Ensure kubelet configuration from IG takes precedence

---

pkg/model/gcemodel/firewall.go

The memberlist gossip protocol exchange happens over TCP and UDP, so
we need to open both protocols.

gce: memberlist needs TCP also

---

nodeup/pkg/model/dns/builder.go
nodeup/pkg/model/kube_proxy.go
nodeup/pkg/model/protokube.go
pkg/apis/kops/validation/validation.go
pkg/dns/gossip.go
pkg/dns/gossip_test.go
pkg/kubeconfig/create_kubecfg.go
pkg/model/awsmodel/api_loadbalancer.go
pkg/model/awsmodel/dns.go
pkg/model/awsmodel/iam.go
pkg/model/azuremodel/api_loadbalancer.go
pkg/model/components/etcdmanager/model.go
pkg/model/components/kopscontroller/template_functions.go
pkg/model/context.go
pkg/model/domodel/api_loadbalancer.go
pkg/model/openstackmodel/firewall.go
pkg/model/openstackmodel/servergroup.go
pkg/resources/aws/aws.go
pkg/resources/gce/gce.go
pkg/resources/openstack/dns.go
pkg/validation/validate_cluster.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/dns.go
upup/pkg/fi/cloudup/new_cluster.go
upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/populate_cluster_spec.go
upup/pkg/fi/cloudup/template_functions.go

Always infer gossip DNS from cluster name

---

nodeup/pkg/model/sysctls.go

The rp_filter change in https://github.com/kubernetes/kops/pull/14137 was incomplete. This PR should further ensure rp_filter is not enabled when using cilium, and should make cilium work on Jammy.

Disable rp_filter on cilium hosts

---

nodeup/pkg/model/sysctls.go

Cherry pick of #14369 on release-1.24.
#14369: Disable rp_filter on cilium hosts
```release-note
```

Automated cherry pick of #14369: Disable rp_filter on cilium hosts

---

pkg/model/gcemodel/firewall.go

Cherry pick of #14364 on release-1.24.
#14364: gce: memberlist needs TCP also
```release-note
```

Automated cherry pick of #14364: gce: memberlist needs TCP also

---

docs/operations/karpenter.md
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template

Hi,
Having ondemand and spot in capacity type can secure the usage of karpenter by always having a solution to spawn a new instance if there is no capacity in spot. 
The karpenter [documentation](https://karpenter.sh/v0.16.3/faq/#what-if-there-is-no-spot-capacity-will-karpenter-use-on-demand) : `If your Karpenter Provisioner specifies flexibility to both Spot and On-Demand capacity, Karpenter will attempt to provision On-Demand capacity if there is no Spot capacity available`
This will not change the basic behavior of karpenter spawning a spot instance if possible first, but it adds a fallback to start an ondemand instance if there is no spot available.
Thanks for your time !

Karpenter : fallback on ondemand instance by default

---

pkg/model/components/hetznercloudcontrollermanager.go
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.k8s.local-addons-hcloud-cloud-controller.addons.k8s.io-k8s-1.22_content

Cherry pick of #14386 on release-1.25.
#14386: hetzner: Update CCM to v1.13.2
```release-note
```

Automated cherry pick of #14386: hetzner: Update CCM to v1.13.2

---

upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #14401 on release-1.25.
#14401: update k8s cloudprovider openstack images
```release-note
```

Automated cherry pick of #14401: update k8s cloudprovider openstack images

---

upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #14406 on release-1.25.
#14406: update k8s openstack
```release-note
```

Automated cherry pick of #14406: update k8s openstack

---

channels/alpha

k8s versions for October 2022:
* https://github.com/kubernetes/kubernetes/releases/tag/v1.23.13
* https://github.com/kubernetes/kubernetes/releases/tag/v1.24.7
* https://github.com/kubernetes/kubernetes/releases/tag/v1.25.3

Bump k8s and ubuntu ami version in alpha

---

upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #14417 on release-1.25.
#14417: bump Openstack ccm version
```release-note
```

Automated cherry pick of #14417: bump Openstack ccm version

---

nodeup/pkg/model/containerd.go
nodeup/pkg/model/context.go
nodeup/pkg/model/kube_controller_manager.go
nodeup/pkg/model/kubelet.go
nodeup/pkg/model/kubelet_test.go
nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
nodeup/pkg/model/tests/kubelet/warmpool/tasks.yaml
upup/pkg/fi/nodeup/command.go

We should always use the one on the nodeup config.

Remove usage of cluster kubelet config in nodeup

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
upup/models/cloudup/resources/addons/snapshot-controller.addons.k8s.io/k8s-1.20.yaml.template

Cherry pick of #14413 on release-1.25.
#14413: Allow snapshot controller to create volumesnapshotcontent
```release-note
```

Automated cherry pick of #14413: Allow snapshot controller to create volumesnapshotcontent

---

cmd/kops/get_keypairs.go
cmd/kops/promote_keypair.go
upup/pkg/fi/vfs_castore.go

Allow the _kops get keypairs_ command to consume key sets with old key pair items that lack an associated X.509 certificate. When the command is invoked without the `--distrusted` flag set to true, omit these old items as if they're distrusted. Conversely, when the command is invoked with the `--distrusted` flag set to true, include these items, but omit their details that would be contingent on the nonexistent certificate.
In order to supply only information that is known to be true, treat the following fields in the output as newly optional:
- _issuer_
- _notAfter_
- _notBefore_
- _subject_
With no certificate present, it's not possible to present concrete values for those fields.
Fixes #14174.

get-keypairs: Tolerate key set items without certificates

---

cmd/kops/get_keypairs.go
cmd/kops/promote_keypair.go
upup/pkg/fi/vfs_castore.go

Cherry pick of #14370 on release-1.25.
#14370: get-keypairs: Tolerate items without certificates
```release-note
```

Automated cherry pick of #14370: get-keypairs: Tolerate items without certificates

---

pkg/instancegroups/rollingupdate.go

Cherry pick of #14436 on release-1.25.
#14436: Log and aggregate errors from rolling update
```release-note
```

Automated cherry pick of #14436: Log and aggregate errors from rolling update

---

upup/pkg/fi/cloudup/new_cluster.go

Creating an IPv6 cluster with private topology previously failed with:
```
Error: cannot find subnet "dualstack-us-east-1a" (declared in instance group "master-us-east-1a", not found in cluster)
```
This is because `setupMasters()` tried to validate the control plane IG's subnet before `setupTopology()` created the dualstack subnets.

Need to setup topology before control plane for IPv6 private topology

---

tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template

The Service annotation for the pod-identity-webhook is asking Prometheus to scrape its metrics from `https://` but this results in a HTTP 404 Not Found response.
The pod-identity-webhook pods expose their metrics via HTTP on TCP port 9999 (the same port where the healthz checks go).
Therefore update the annotations to use `http://:9999` instead.

Fix Prometheus scraping for pod-identity-webhook

---

tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template

Cherry pick of #14463 on release-1.25.
#14463: Fix Prometheus scraping for pod-identity-webhook

Automated cherry pick of #14463: Fix Prometheus scraping for pod-identity-webhook

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go
upup/pkg/fi/cloudup/new_cluster.go

With this, an IPv6 cluster with private topology comes up (though without LBC).

ipv6: NPE fixes for IPv6-only instances

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.25_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.25_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_privatecanal.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_privatecanal.example.com-addons-networking.projectcalico.org.canal-k8s-1.25_content
upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.22.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.25.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.22.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.25.yaml.template

Cherry pick of #14466 on release-1.25.
#14466: Update Calico to v3.21.6 for k8s 1.16+
```release-note
```

Automated cherry pick of #14466: Update Calico and Canal

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

/cc @rifelpet @hakman @olemarkus @johngmyers 
Hey y'all!
Wanted to point out the below updates from the release page:
> This new version removes dependency on CRI socket(e.g. dockershim.sock).
> 
> 🚨 🚨 🚨 Action Required For Upgrading
> 
> To upgrade to VPC CNI >=v1.12.0, you must upgrade to VPC CNI >=v1.7.x first. We recommend that you update one minor version at a time.
> aws-vpc-cni Helm chart v1.2.0 is released with VPC CNI v1.12.0, thus no longer supports the cri.hostPath.path. If you need to install a VPC CNI <v1.12.0 with helm chart, a aws-vpc-cni Helm chart with version <v1.2.0 should be used.
Regarding the `dockershim.sock` removal, I suppose we should be good since it was already remove everywhere else already, correct?
And about the requirement to have a minimum version of v1.7 …

Upgrade Amazon VPC CNI to v1.12.0

---

tests/e2e/templates/apiserver-dns-none.yaml.tmpl

To be used in the future, when adding support for the feature. Should be pretty easy to add some new target groups for `etcd.main` and `etcd.events` (in theory).

Add e2e template for dedicated APIserver nodes without DNS

---

cmd/kops/root.go

What's the point of making people type an extra seven characters every time they create or delete a cluster?

Revert deprecation of positional clustername args

---

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/coredns/coredns.addons.k8s.io-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/coredns/manifest.yaml

Cherry pick of #14503 on release-1.24.
#14503: use the same tolerations config for coredns-autoscaler
```release-note
```

Automated cherry pick of #14503: use the same tolerations config for coredns-autoscaler

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/template_functions.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Fixes #14495 
1. As listed in the above issue, this PR introduces a template update to account for a case of `ANNOTATE_POD_IP` env. When set to `true`- the `ClusterRole` should also allow patching a pod. Based on the upstream template [here](https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.12/charts/aws-vpc-cni/templates/clusterrole.yaml#L17-L27)
2. I also noticed that there were some newly introduced default ENVs that I overlooked in previous bumps, so adding those (based on the default values.yaml of the upstream chart [here](https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.12/charts/aws-vpc-cni/values.yaml#L35-L56))

AWS CNI template updates

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/template_functions.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Cherry pick of #14513 on release-1.25.
#14513: add a condition for the aws-cni ClusterRole based on the
```release-note
```

Automated cherry pick of #14513: add a condition for the aws-cni ClusterRole based on the

---

channels/alpha

* https://github.com/kubernetes/kubernetes/releases/tag/v1.22.16
* https://github.com/kubernetes/kubernetes/releases/tag/v1.23.14
* https://github.com/kubernetes/kubernetes/releases/tag/v1.24.8
* https://github.com/kubernetes/kubernetes/releases/tag/v1.25.4

bump k8s patch versions in alpha for November releases

---

channels/stable
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.23/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.24/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.25/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-arm64/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

Version was updated in alpha over 3 weeks ago, seems ready to promote (ref #14433)

Promote Ubuntu Version from Alpha to Stable

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

Cherry pick of #14549 on release-1.25.
#14549: Update Go to v1.19.3
```release-note
```

Automated cherry pick of #14549: Update Go to v1.19.3

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.25_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.25_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_privatecanal.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_privatecanal.example.com-addons-networking.projectcalico.org.canal-k8s-1.25_content
upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.22.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.25.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.22.yaml.template
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.25.yaml.template

Cherry pick of #14551 on release-1.25.
#14551: Update Calico to v3.24.5 for k8s 1.25+
```release-note
```

Automated cherry pick of #14551: Update Calico and Canal to latest versions

---

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/template_functions.go

Switching template `join` function to Sprig's `join`, which can handle `[]interface{}` inputs instead of `[]string` only. This makes `join` easier to use in templates that define variables within the template itself.
Updates existing uses of `join` to fix the new function signature.
related to: https://github.com/kubernetes/kops/pull/14547

use sprig join for template functions

---

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #14564 on release-1.25.
#14564: use sprig join for template functions

Automated cherry pick of #14564: use sprig join for template functions

---

pkg/apis/kops/instancegroup.go

Cherry pick of #14573 on release-1.25.
#14573: Allow using the price-capacity-optimized spot allocation

Automated cherry pick of #14573: Allow using the price-capacity-optimized spot allocation

---

pkg/model/iam/iam_builder.go

Cherry pick of #14563 on release-1.25.
#14563: Add missing create tags permissions for cilium operator in
```release-note
```

Automated cherry pick of #14563: Add missing create tags permissions for cilium operator in

---

cmd/kops/toolbox_instance-selector.go
upup/pkg/fi/cloudup/awsup/aws_cloud.go
upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go

Cherry pick of #14576 on release-1.24.
#14576: aws: Fix SIGSEGV when using instance selector
```release-note
```

Automated cherry pick of #14576: aws: Fix SIGSEGV when using instance selector

---

pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.11.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #14586 on release-1.25.
#14586: Bump cilium to 1.11.11
```release-note
```

Automated cherry pick of #14586: Bump cilium to 1.11.11

---

upup/models/cloudup/resources/addons/storage-aws.addons.k8s.io/v1.15.0.yaml.template
upup/models/cloudup/resources/addons/storage-gce.addons.k8s.io/v1.7.0.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

Previously this was done in the manifests leading to empty files. kubectl doesn't like this, so protokube will always fail updating the addon when StorageClass management is disabled.
/kind bug

Fix disabling StorageClass management

---

upup/models/cloudup/resources/addons/storage-aws.addons.k8s.io/v1.15.0.yaml.template
upup/models/cloudup/resources/addons/storage-gce.addons.k8s.io/v1.7.0.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

Cherry pick of #14589 on release-1.25.
#14589: Fix disabling StorageClass management
```release-note
```

Automated cherry pick of #14589: Fix disabling StorageClass management

---

tests/e2e/pkg/tester/skip_regex.go

All the loadbalancer tests in the kubernetes e2e suite fail on IPv6, however, they were skipped until now because they were tagged as [Slow]. Antonio messed it up adding a new loadbalancer test without  the Slow tag and now it fails trying to run on IPv6.
Skip these tests temporary since they fail always on IPv6

skip Loadbalancer UDP tests

---

upup/pkg/fi/values.go

As discussed during office hours splitting https://github.com/kubernetes/kops/pull/14592 for easy cherry-picking.
/cc @johngmyers @justinsb @rifelpet

Add generics alternatives for fi.Bool/Float*/Int*/String*()

---

upup/pkg/fi/values.go

Cherry pick of #14595 on release-1.25.
#14595: Add generics alternatives for fi.Bool/Float*/Int*/String*()
```release-note
```

Automated cherry pick of #14595: Add generics alternatives for fi.Bool/Float*/Int*/String*()

---

upup/pkg/fi/nodeup/nodetasks/service.go

When node images are sideloaded, the kubelet service should start after sideloading all the images.

Load images before starting the kubelet service

---

docs/networking/ipv6.md

```
Nov 21 03:39:18 debian dhclient[469]: DHCPREQUEST for 169.254.61.153 on ens5 to 169.254.0.1 port 67
Nov 21 03:39:18 debian dhclient[469]: send_packet: Network is unreachable
Nov 21 03:39:18 debian dhclient[469]: send_packet: please consult README file regarding broadcast address.
Nov 21 03:39:18 debian dhclient[469]: dhclient.c:2756: Failed to send 300 byte long packet over fallback inter>
```

Remove support for IPv6 on Debian

---

tests/e2e/templates/many-addons.yaml.tmpl
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template

Cherry pick of #14442 on release-1.25.
#14442: Fix pdb for identity webhook

Automated cherry pick of #14442: Fix pdb for identity webhook

---

tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template

Cherry pick of #14442 on release-1.24.
#14442: Fix pdb for identity webhook

Cherry pick of #14442: Fix pdb for identity webhook

---

docs/getting_started/gce.md

The purpose of these changes is to document some best practices when using kOps to create and administer a k8s cluster in GCP. For each best practice, I included a description of why it is considered a best practice, as well as example kops commands to utilize it.
Currently the best practices I have included are:
- Using spot instances to reduce cost for fault-tolerant workloads
- Using a multi-zonal cluster to ensure high availability in the event of an datacenter/rack/server outage
I tested these changes using `make live-docs` to view my changes locally.
Let me know if there are additional best practices we should add and I will be happy to do so.

Add best practices to getting started with GCE docs

---

tests/e2e/kubetest2-kops/deployer/dumplogs.go

Should help diagnose what's going on in some of our complex upgrade
tests when we detect conflicts.
Issue #14520

kubetest: dump poddisruptionbudgets and fieldManagers

---

docs/instance_groups.md
docs/releases/1.26-NOTES.md
k8s/crds/kops.k8s.io_instancegroups.yaml
pkg/apis/kops/instancegroup.go
pkg/apis/kops/v1alpha2/instancegroup.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/instancegroup.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/awsmodel/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go

Exposes a new `CapacityRebalance` flag which enables/disables ASG capacity rebalancing: https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-capacity-rebalancing.html
This is very helpful for users who have spot instanceGroups and want to proactively have ASG replace instances that have received a rebalance recommendation (meaning they're at elevated risk of interruption by AWS).

aws: Add capacityRebalance flag for ASGs

---

pkg/featureflag/featureflag.go
pkg/featureflag/featureflag_test.go
upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template
upup/pkg/fi/cloudup/template_functions.go
upup/pkg/fi/cloudup/template_functions_test.go

Add a new feature gate `SELinuxMount` that configures AWS EBS CSI driver installed by kOps  for SELinuxMount support.
* It projects necessary SELinux `/etc` and `/sys` directories from the host to the CSI driver (see [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1710-selinux-relabeling#volume-mounting) for details)
* It sets `CSIDriver.Spec.SELinuxMount: true`
I added `KopsFeatureEnabled` function to templates to have a nice `{{ if KopsFeatureEnabled "SELinuxMount" }}` there.

Add SELinuxMount feature gate

---

tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.k8s.local-addons-hcloud-csi-driver.addons.k8s.io-k8s-1.22_content
upup/models/cloudup/resources/addons/hcloud-csi-driver.addons.k8s.io/k8s-1.22.yaml.template

Cherry pick of #14632 on release-1.25.
#14632: hetzner: Update CSI driver to v2.0.0
```release-note
```

Automated cherry pick of #14632: hetzner: Update CSI driver to v2.0.0

---

upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go

Closes: #14646
Ref: https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-quotas.html
Amazon EC2 Auto Scaling provides API operations to make changes to your Auto Scaling groups in batches. The following are the API limits on the maximum number of items (maximum array members) that are allowed in a single operation. They cannot be changed.
Operation | Maximum array members
-- | --
AttachInstances | 20 instance IDs
AttachLoadBalancers | 10 load balancers
AttachLoadBalancerTargetGroups | 10 target groups
BatchDeleteScheduledAction | 50 scheduled actions
BatchPutScheduledUpdateGroupAction | 50 scheduled actions
DetachInstances | 20 instance IDs
DetachLoadBalancers | 10 load balancers
DetachLoadBalancerTargetGroups | 10 target groups
EnterStandby | 20 instance IDs
ExitStandby …

aws: Limit the number of target groups updated per operation

---

upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go

Cherry pick of #14648 on release-1.25.
#14648: aws: Limit the number of target groups updated per

Automated cherry pick of #14648: aws: Limit the number of target groups updated per

---

pkg/model/gcemodel/firewall.go
pkg/wellknownports/wellknownports.go

Cherry pick of #14655 on release-1.25.
#14655: gce: Allow Cilium to connect to its etcd cluster
```release-note
```

Automated cherry pick of #14655: gce: Allow Cilium to connect to its etcd cluster

---

tests/e2e/kubetest2-kops/builder/build.go
tests/e2e/kubetest2-kops/deployer/build.go
upup/pkg/fi/nodeup/nodetasks/load_image.go

Otherwise on our first upload we were truncating one level of the
upload path.
Issue #14639

e2e: always upload to a versioned directory

---

upup/pkg/fi/cloudup/awstasks/targetgroup.go
upup/pkg/fi/cloudup/terraform/hcl2.go
upup/pkg/fi/cloudup/terraformWriter/literal.go

This is a first step in refactoring the rendering logic of `terraformWriter.Literal` into the respective constructors. This refactors `LiteralFunctionExpression()`; the other constructors would switch to using `String` in subsequent PRs.
What do you think @rifelpet ?
/assign @rifelpet

Refactor rendering Terraform functions into constructor

---

.shipbot.yaml

Cherry pick of #14667 on release-1.24.
#14667: We no longer release an images.tar.gz
```release-note
```

Automated cherry pick of #14667: We no longer release an images.tar.gz

---

tests/integration/update_cluster/complex/kubernetes.tf
tests/integration/update_cluster/existing_sg/kubernetes.tf
tests/integration/update_cluster/externalpolicies/kubernetes.tf
upup/pkg/fi/cloudup/terraform/hcl2.go
upup/pkg/fi/cloudup/terraform/hcl2_test.go
upup/pkg/fi/cloudup/terraformWriter/literal.go
upup/pkg/fi/cloudup/terraformWriter/writer.go
util/pkg/vfs/gsfs.go
util/pkg/vfs/tests/gsfs_test.go
util/pkg/vfs/tests/s3fs_test.go

This is probably best reviewed commit-by-commit.
Moves logic for Literal into the constructors.
/assign @rifelpet

Refactor terraformWriter.Literal

---

cmd/kops/create_cluster.go

In the cmd/kops/create_cluster.go:RunCreateCluster function, the auto-loading of ssh keys only looks for keys at `~/.ssh/id_rsa.pub` so we could add another path to also take ed25519 keys into account.

Add id_ed25519 to auto-loaded ssh keys

---

cmd/kops/edit_cluster.go
cmd/kops/edit_instancegroup.go
pkg/edit/edit.go
pkg/edit/edit_test.go

The current implementation assumes that the v1alpha1 form is the same as the internal form. There are a bunch of logic errors in both the implementation and test.
The new version is much simpler and does not rely on conversion to the internal API.

Fix edit.HasExtraFields()

---

pkg/apis/kops/channel.go
upup/pkg/fi/cloudup/new_cluster.go

When I refactored `Spec.Networking` to be a non-pointer, this code started forcing new clusters to have Kubenet.
This seems to be an extremely dubious feature.

Stop trying to populate arbitrary cluster fields from the channel

---

pkg/resources/aws/aws.go
pkg/resources/ops/collector.go

Small cleanup improvement to get tests passing again in https://github.com/kubernetes/cloud-provider-aws/pull/532:
```
Ginkgo ran 1 suite in 2m57.709627616s
Test Suite Passed
/home/prow/go/src/k8s.io/cloud-provider-aws
I1202 08:29:47.704238   27602 delete_cluster.go:128] Looking for cloud resources to delete
Error: error querying for route53 zones: AccessDenied:
User: arn:aws:iam::607362164682:user/awstester is not authorized to perform: route53:ListHostedZones
because no identity-based policy allows the route53:ListHostedZones action
status code: 403, request id: 911b0c35-ba05-4950-880f-3d78acabfddb
make: *** [Makefile:133: test-e2e] Error 1
```
/cc @olemarkus @johngmyers @rifelpet

aws: Skip Route53 cleanup for clusters without DNS

---

tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template

metrics-server: Set preferred address type to `InternalIP` when non AWS

---

docs/releases/1.26-NOTES.md
tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-gce/expected-v1alpha2.yaml
tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/populate_instancegroup_spec.go

These instance types seems newer and with better availability and cost/performance ratio (same type for masters and nodes).
/cc @justinsb 

gce: Update default instance types

---

pkg/model/awsmodel/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go

This optimises the way we reference shared (external) target groups by using `EnsureTask()` instead of pre-pending the autoscaling group name.
Ref: https://github.com/kubernetes/kops/pull/10335

aws: Use EnsureTask to reference shared target groups

---

tests/e2e/scenarios/lib/common.sh

This should hopefully make scenario tests fail earlier than the rather obscure `exec format error` when trying to execute the xml error output.

Make curl fail on 404 in scenario tests

---

cloudmock/aws/mockelbv2/api.go
cloudmock/aws/mockelbv2/targetgroups.go
pkg/model/awsmodel/api_loadbalancer.go
pkg/model/awsmodel/bastion.go
tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
tests/integration/update_cluster/complex/kubernetes.tf
tests/integration/update_cluster/minimal-dns-none/kubernetes.tf
tests/integration/update_cluster/minimal-ipv6-calico/kubernetes.tf
tests/integration/update_cluster/minimal-ipv6-cilium/kubernetes.tf
tests/integration/update_cluster/minimal-ipv6-no-subnet-prefix/kubernetes.tf
tests/integration/update_cluster/minimal-ipv6/kubernetes.tf
tests/integration/update_cluster/private-shared-ip/kubernetes.tf
tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
tests/integration/update_cluster/privatecalico/kubernetes.tf
tests/integration/update_cluster/privatecanal/kubernetes.tf
tests/integration/update_cluster/privatecilium-eni/kubernetes.tf
tests/integration/update_cluster/privatecilium/kubernetes.tf
tests/integration/update_cluster/privatecilium2/kubernetes.tf
tests/integration/update_cluster/privateciliumadvanced/kubernetes.tf
tests/integration/update_cluster/privatedns1/kubernetes.tf
tests/integration/update_cluster/privatedns2/kubernetes.tf
tests/integration/update_cluster/privateflannel/kubernetes.tf
tests/integration/update_cluster/privatekopeio/kubernetes.tf
tests/integration/update_cluster/privateweave/kubernetes.tf
tests/integration/update_cluster/shared_vpc_ipv6/kubernetes.tf
tests/integration/update_cluster/unmanaged/kubernetes.tf
upup/pkg/fi/cloudup/awstasks/targetgroup.go

With this change, kOps now sets the following [NLB TG attributes](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#deregistration-delay):
* `deregistration_delay.connection_termination.enabled` with value `true`, instead of `false`
* `deregistration_delay.timeout_seconds` with value `30`, instead of `300`

aws: Add support for managing target group attributes

---

cmd/kops/create_cluster_integration_test.go
tests/integration/create_cluster/ha_openstack_octavia/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_openstack_octavia/options.yaml
upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstack/cloud_test.go

This should make the code more easier to reason about. It should also help uncover what breaks in #14546.
An additional error case is tested after this refactor. If octavia is configured, but no router is set, no LB client would be set on the cloud. Now we return error instead. This should be caught earlier by validation, but these additional tests doesn't hurt.
/cc @zetaab

OpenStack: Refactor Load Balancer builder

---

cmd/kops-controller/controllers/hosts_controller.go

These log lines happens very frequently on large clusters.

kops-controller: increase verbosity level on logs in gossip controller

---

channels/alpha

* https://github.com/kubernetes/kubernetes/releases/tag/v1.25.5
* https://github.com/kubernetes/kubernetes/releases/tag/v1.24.9
* https://github.com/kubernetes/kubernetes/releases/tag/v1.23.15

bump k8s versions and ubuntu ami version in alpha channel

---

docs/extra.css

On https://kops.sigs.k8s.io/iam_roles/ the json links go under the right sidebar. I also can't copy the whole URL because as soon as I get to the part that's under the right sidebar it freaks out and cancels my click and drag highlighting. 
This means the content is not wrapped when it's wider than the content column. Easy CSS fix for this.

Overflow wrap the content column so content doesn't go under right sidebar and not be readable

---

docs/iam_roles.md

*PLEASE NOTE* Before you approve, can someone show me how to see if this works before it's merged in? In my md preview, it looks fine, but it also looked fine before.

trying to fix the broken list items for ECR permissions

---

OWNERS
pkg/model/openstackmodel/OWNERS
pkg/resources/openstack/OWNERS
pkg/resources/spotinst/OWNERS
upup/pkg/fi/cloudup/openstack/OWNERS
upup/pkg/fi/cloudup/openstacktasks/OWNERS
upup/pkg/fi/cloudup/spotinsttasks/OWNERS

Cherry pick of #14704 on release-1.25.
#14704: Update OWNERS files
```release-note
```

Automated cherry pick of #14704: Update OWNERS files

---

channels/stable
tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.21/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.22/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.23/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.24/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.25/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-arm64/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-irsa/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

Latest k8s releases fix a few CVEs. I vote for early promotion to stable channel:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#changelog-since-v1254
/cc @olemarkus @johngmyers @moshevayner

Promote alpha channel to stable

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

Cherry pick of #14779 on release-1.25.
#14779: Update Go to v1.19.4
```release-note
```

Automated cherry pick of #14779: Update Go to v1.19.4

---

nodeup/pkg/bootstrap/install.go
pkg/testutils/integrationtestharness.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/awstasks/egressonlyinternetgateway_test.go
upup/pkg/fi/cloudup/awstasks/elastic_ip_test.go
upup/pkg/fi/cloudup/awstasks/internetgateway_test.go
upup/pkg/fi/cloudup/awstasks/securitygroup_test.go
upup/pkg/fi/cloudup/awstasks/subnet_test.go
upup/pkg/fi/cloudup/awstasks/vpc_test.go
upup/pkg/fi/cloudup/gcetasks/projectiambinding_test.go
upup/pkg/fi/cloudup/gcetasks/serviceaccount_test.go
upup/pkg/fi/cloudup/gcetasks/storagebucketiam_test.go
upup/pkg/fi/cloudup/loader.go
upup/pkg/fi/context.go
upup/pkg/fi/nodeup/command.go
upup/pkg/fi/task.go
util/pkg/vfs/context.go

The rule of thumb is that we shouldn't be embedding a context.Context,
but it is reasonable when the lifetime is similar and when the
refactor would otherwise be unacceptably large.
This is a minimal way to introduce it, based on adding the support
needed in the GCS support for serviceAccountIssuerDiscovery.  We will
need to plumb through the context in many more places over time.

Introduce context.Context into some of our "Context" objects

---

cmd/kops-controller/main.go
pkg/nodeidentity/scaleway/OWNERS
pkg/nodeidentity/scaleway/identify.go

This PR allows the kops-controller to identify Scaleway nodes.

scaleway : nodeidentity

---

upup/pkg/fi/cloudup/openstack/cloud.go

Since OS' client builder can build a cloud without load balancer client, we need to account for this here.

OpenStack: allow no lbclient when checking for vipacl

---

pkg/resources/ops/collector.go
pkg/resources/scaleway/OWNERS
pkg/resources/scaleway/resources.go
upup/pkg/fi/cloudup/scaleway/cloud.go
upup/pkg/fi/cloudup/scalewaytasks/sshkey.go

Now that the `kops create cluster` command actually creates a Scaleway cluster, this new PR should add everything that is needed for the `kops delete cluster` command to be able to destroy it, which will be useful to implement automated testing.

scaleway: list and delete resources

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template

Remove configuration settings that don't affect Queue Processor mode (modulo bugs) from the Deployment template, so that they don't act as red herrings.
Works around aws/node-termination-handler#735 and aws/node-termination-handler#743.
Corresponds to aws/node-termination-handler#745.

NTH: Remove unnecessary configuration in Queue Processor mode

---

pkg/model/openstackmodel/context.go
pkg/model/openstackmodel/firewall.go
pkg/model/openstackmodel/servergroup.go
tests/integration/update_cluster/minimal_openstack/in-v1alpha2.yaml

We no longer expect the API's public name being set for gossip clusters as they don't really make sense. This fixes some incorrect assumptions in the OpenStack models.
Should get us one step further with #14546

Base OpenStack API resources on cluster name if public name is not set

---

nodeup/pkg/model/bootstrap_client.go
pkg/kopscontrollerclient/client.go
upup/pkg/fi/nodeup/command.go
upup/pkg/fi/nodeup/nodetasks/bootstrap_client.go

Move kops-controller client into its own package

---

util/pkg/vfs/k8scontext.go

We somehow ended up with 2 license headers here (the same, though with
different dates).

Cleanup double-license header in file

---

pkg/apis/kops/validation/instancegroup.go
pkg/apis/kops/validation/instancegroup_test.go

Cherry pick of #14848 on release-1.25.
#14848: Validate control-plane IG size
```release-note
```

Automated cherry pick of #14848: Validate control-plane IG size

---

cmd/kops/integration_test.go
pkg/assets/copyfile.go
pkg/client/simple/vfsclientset/addons.go
pkg/client/simple/vfsclientset/commonvfs.go
pkg/model/components/image_test.go
pkg/testutils/testcontext/context.go
upup/models/vfs.go
upup/pkg/fi/fitasks/managedfile.go
upup/pkg/fi/secrets/clientset_secretstore.go
upup/pkg/fi/secrets/vfs_secretstore.go
upup/pkg/fi/vfs_castore.go
util/pkg/vfs/azureblob.go
util/pkg/vfs/fs.go
util/pkg/vfs/fs_test.go
util/pkg/vfs/gsfs.go
util/pkg/vfs/k8sfs.go
util/pkg/vfs/memfs.go
util/pkg/vfs/memfs_test.go
util/pkg/vfs/s3fs.go
util/pkg/vfs/sshfs.go
util/pkg/vfs/swiftfs.go
util/pkg/vfs/vfs.go

As "request" methods, these should have context parameters.
Note I also had to move ContextForTest into its own package to avoid circular dependencies, I think this makes sense though.

VFS: Add context to CreateFile & WriteFile

---

channels/pkg/channels/addon.go
cmd/kops-controller/pkg/server/keystore.go
cmd/kops-controller/pkg/server/server.go
cmd/kops/create_keypair.go
cmd/kops/distrust_keypair.go
cmd/kops/export_kubeconfig.go
cmd/kops/promote_keypair.go
cmd/kops/trust_keypair.go
cmd/kops/update_cluster.go
nodeup/pkg/model/context.go
nodeup/pkg/model/fakes_test.go
pkg/commands/helpers/kubectl_auth.go
pkg/configserver/keystore.go
pkg/kubeconfig/create_kubecfg.go
pkg/kubeconfig/create_kubecfg_test.go
pkg/pki/issue.go
pkg/pki/issue_test.go
upup/pkg/fi/ca.go
upup/pkg/fi/clientset_castore.go
upup/pkg/fi/fitasks/keypair.go
upup/pkg/fi/nodeup/nodetasks/issue_cert.go
upup/pkg/fi/vfs_castore.go
upup/pkg/fi/vfs_castore_test.go

We had missed a case in nodeup; add a Context argument to force us to
revisit the codepaths.

FindKeyset can return nil

---

upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/template_functions.go

Release commits modify the dns-controller and kops-controller manifests, triggering the `pull-kops-e2e-aws-upgrade-126-ko126-to-klatest-kolatest-many-addons` test. That test always fails because images with the new versions never exist yet.
Use a template function in those manifests so that they avoid triggering that test.

Avoid triggering upgrade tests on release commits

---

cmd/kops/create_cluster.go

Cherry pick of #14897 on release-1.26.
#14897: Include SSHCredentials in create cluster dryrun output

Automated cherry pick of #14897: Include SSHCredentials in create cluster dryrun output

---

nodeup/pkg/model/kube_apiserver.go
nodeup/pkg/model/tests/golden/dedicated-apiserver/tasks-kube-apiserver.yaml

Dedicated APIServer nodes were broken by #14880

Etcd domains are now under .internal.

---

nodeup/pkg/model/kube_apiserver.go
nodeup/pkg/model/tests/golden/dedicated-apiserver/tasks-kube-apiserver.yaml

Cherry pick of #14902 on release-1.25.
#14902: etcd domains are now under .internal.

Automated cherry pick of #14902: etcd domains are now under .internal.

---

tests/integration/create_cluster/ha_openstack/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/new_cluster.go
upup/pkg/fi/cloudup/openstack/cloud.go

Cherry pick of #14887 on release-1.26.
#14887: set loadbalancer configs before initializing the OS
```release-note
```

Automated cherry pick of #14887: set loadbalancer configs before initializing the OS

---

tests/integration/create_cluster/ha_openstack/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/new_cluster.go
upup/pkg/fi/cloudup/openstack/cloud.go

fixes #14886 
the problem was that Openstack cloud clients were called and initialised before setting up base setup for loadbalancer.
cc @olemarkus I think you modified this part of code sometime ago.

set loadbalancer configs before initializing the OS clients

---

upup/pkg/fi/cloudup/apply_cluster.go

Cherry pick of #14907 on release-1.26.
#14907: APIServer nodes also need apiserverAdditionalIPs

Automated cherry pick of #14907: APIServer nodes also need apiserverAdditionalIPs

---

upup/pkg/fi/cloudup/apply_cluster.go

A latent bug exposed by #14729

APIServer nodes also need apiserverAdditionalIPs

---

pkg/apis/kops/validation/legacy.go
pkg/apis/kops/validation/validation.go
pkg/apis/kops/validation/validation_test.go

Move most networking validation from `legacy.go` to `networking.go`.
Preparation for combining `spec.networking.networkCIDR` and `spec.networking.additionalNetworkCIDRs`.

Move networking validations inside validateNetworking()

---

pkg/apis/kops/validation/validation.go

From a cursory review of the code, it looks like Hetzner can imply a subnet from the network's CIDR range and DO doesn't have the concept of subnets.
It's unfortunate that there aren't integration tests validating these code paths.

Don't require subnets on DO and Hetzner

---

pkg/model/awsmodel/network.go
pkg/model/gcemodel/autoscalinggroup.go
tests/integration/update_cluster/complex/kubernetes.tf

I'm questioning why we have the `topology.nodes` and `topology.controlPlane` fields in the cluster spec. They're redundant with the cluster subnet specs.
This changes AWS subnet tagging to be based on the existence or not of private subnets. It changes GCE assignment of public IPs to nodes to behave like AWS: based on the subnet the instance is in, not whether the topology spec thinks the control plane is public.

Reduce use of cluster topology field

---

nodeup/pkg/model/cloudconfig.go

fixes #14931
include cloud.config in normal nodes in case of OpenStack. It is currently used by cinder-csi driver. This is how it has been working.
@johngmyers could you check this

OpenStack: include cloud config in normal nodes

---

upup/pkg/fi/cloudup/defaults.go

Cherry pick of #14937 on release-1.26.
#14937: Improve error message when trying to use IPv6 with amazonvpc

Automated cherry pick of #14937: Improve error message when trying to use IPv6 with amazonvpc

---

upup/pkg/fi/cloudup/openstacktasks/volume.go

Cherry pick of #14923 on release-1.26.
#14923: Do not include tags when searching existing volumes in
```release-note
```

Automated cherry pick of #14923: Do not include tags when searching existing volumes in

---

upup/pkg/fi/cloudup/openstacktasks/volume.go

fixes #14922
if we include tags when searching volumes, it basically means that we cannot modify tags at all.
After this PR the `kops update cluster` output is: (it will add tag `k8s.io/role/control-plane: 1` to all volumes)
```
Will modify resources:
Volume/espsti.etcd-events.sre-sandbox.k8s.local
Tags                     {k8s.io/role/master: 1, KubernetesCluster: sre-sandbox.k8s.local, k8s.io/etcd/events: espsti/espsti,esptnl,helpa} -> {k8s.io/etcd/events: espsti/espsti,esptnl,helpa, k8s.io/role/control-plane: 1, k8s.io/role/master: 1, KubernetesCluster: sre-sandbox.k8s.local}
Volume/espsti.etcd-main.sre-sandbox.k8s.local
Tags                     {KubernetesCluster: sre-sandbox.k8s.local, k8s.io/etcd/main: espsti/espsti,esptnl,helpa, k8s.io/role/master: 1} -> {k8s.io/etcd/main: …
```

Do not include tags when searching existing volumes in OpenStack

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-bootstrap_content
tests/integration/update_cluster/nth-imds-processor-irsa/data/aws_s3_object_nthimdsprocessor.longclustername.example.com-addons-bootstrap_content
tests/integration/update_cluster/nth-imds-processor/data/aws_s3_object_nthimdsprocessor.longclustername.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_privatecanal.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatekopeio/data/aws_s3_object_privatekopeio.example.com-addons-bootstrap_content
upup/pkg/fi/cloudup/bootstrapchannelbuilder/pruning.go
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #14929 on release-1.26.
#14929: Prune admission webhooks

Automated cherry pick of #14929: Prune admission webhooks

---

pkg/model/awsmodel/network.go

Don't tag public subnets for internal LBs in IPv6 clusters

---

pkg/model/awsmodel/network.go

Cherry pick of #14941 on release-1.26.
#14941: Don't tag public subnets for internal LBs in IPv6 clusters

Automated cherry pick of #14941: Don't tag public subnets for internal LBs in IPv6 clusters

---

pkg/mutexes/localmutexes.go
upup/pkg/fi/cloudup/gce/gce_cloud.go
upup/pkg/fi/cloudup/gcetasks/projectiambinding.go

We set up a process-wide table of mutexes, to avoid concurrent IAM
operations on GCE projects.  Best-effort is reasonable here, we will
retry, but avoiding concurrent operations just avoids logspam and a
needless retry from self-conflicts.

gce: try to avoid concurrent IAM project operations

---

pkg/kubemanifest/containerargs.go
pkg/kubemanifest/visitor.go
pkg/model/components/addonmanifests/remap.go
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/bootstrapchannelbuilder/pruning.go

We identify the external manifests by checking for our labels.
Currently that label is kOps specific, and we'll likely have to evolve
that to something ecosystem-netural.
We only support the GCE CCM addon and the kopeio-networking addon at
first.
For the GCE CCM addon, we need to replace the arguments, in particular
we likely need the Pod CIDR.  Here we need to work with the GCE CCM to
find a mechanism that can allow some of these flags to be communicated
via a more extensible mechanism (env vars or config maps, likely,
though possibly CRDs).
This is all behind the ClusterAddons feature flag at the moment, so we
can figure this out with other projects safely.

Allow built-in manifests to be replaced by external addons

---

tests/e2e/templates/many-addons.yaml.tmpl

This reverts commit a64ae909e13f6d8abaa72912838dfc201cef0a92 (PR #14934).
Issue should be fixed by #14952

Revert "Temporarily disable cluster-autoscaler in many-addons test"

---

tests/e2e/kubetest2-kops/deployer/dumplogs.go

We're seeing some logs that don't include any output from kops toolbox
dump, but probably should.  Make sure we're including any stderr
output in our logs.

kubetest2-kops: include stderr when calling kops toolbox dump

---

nodeup/pkg/model/cloudconfig.go
upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template
upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/template_functions.go

This will move openstack cloud.config usage to k8s secrets instead.
after this etcd-manager is only component that really needs cloud.config from control-plane local volume. in-tree configs can be removed afaik (remove the --cloud-config flag from kubelet, apiserver, control-manager?). https://github.com/kubernetes-sigs/etcdadm/blob/master/etcd-manager/pkg/volumes/openstack/volumes.go#L268

move openstack cloud config to k8s secrets

---

tests/e2e/kubetest2-kops/deployer/common.go

This allows us to test with a fast single-architecture build, useful
when running kubetest locally.

kubetest: pass through KOPS_ARCH if set

---

pkg/model/components/kubecontrollermanager.go

When the GCE cloud-controller-controlller is in use, it allocates node
IPs, and so the kube-controller-manager should not allocate node IPs.

gce: KCM should not allocate IPs when CCM is in use.

---

docs/contributing/adding_a_feature.md

Tiny command fix - remove extraneous `--` which caused the actual `--short` flag to be ignored.

Fix `kops version` command when dev-building nodeup

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

Cherry pick of #14978 on release-1.26.
#14978: Update Go to v1.19.5
```release-note
```

Automated cherry pick of #14978: Update Go to v1.19.5

---

cmd/kops/replace.go

Similar to what is done in `kops create` and `kops edit`, I believe `kops replace` should also augment the cluster definition with the defaults provided by the `PerformAssignments` method.
I stumbled upon this while trying to follow this guide: https://kops.sigs.k8s.io/manifests_and_customizing_via_api/#yaml-examples.
After creating a cluster from a manifest file using `kops create -f ...`, I changed the `cloudLabels` field and run a `kops replace -f ...` which threw an error related to a non-existing field nonMasqueradeCIDR. I believe this is one of the values that are populated by the `PerformAssignments` method during `kops create` but not `kops replace`.

Populate cluster with default values in `kops replace`

---

cmd/kops/replace.go

Cherry pick of #14920 on release-1.26.
#14920: Populate cluster with default values in `kops replace`
```release-note
```

Automated cherry pick of #14920: Populate cluster with default values in `kops replace`

---

pkg/model/components/etcdmanager/model.go
tests/integration/update_cluster/minimal_gossip/data/aws_s3_object_manifests-etcdmanager-events-master-us-test-1a_content
tests/integration/update_cluster/minimal_gossip/data/aws_s3_object_manifests-etcdmanager-main-master-us-test-1a_content
tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_object_manifests-etcdmanager-events-master-us-test-1a_content
tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_object_manifests-etcdmanager-main-master-us-test-1a_content

The internal domain name is fixed to `"internal." + <cluster_name>`.
We can send the dns suffix (aka internal domain name) to etcd-manager with or without the "." prefix.
https://github.com/kubernetes-sigs/etcdadm/blob/2b149c1337940dad3805a33db6197a6d5a3a43e4/etcd-manager/pkg/controller/newcluster.go#L93-L95
/cc @zetaab @olemarkus

Infer the dns suffix from the cluster name for etcd-manager

---

pkg/model/components/etcdmanager/model.go
tests/integration/update_cluster/minimal_gossip/data/aws_s3_object_manifests-etcdmanager-events-master-us-test-1a_content
tests/integration/update_cluster/minimal_gossip/data/aws_s3_object_manifests-etcdmanager-main-master-us-test-1a_content
tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_object_manifests-etcdmanager-events-master-us-test-1a_content
tests/integration/update_cluster/minimal_gossip_irsa/data/aws_s3_object_manifests-etcdmanager-main-master-us-test-1a_content

Cherry pick of #14986 on release-1.26.
#14986: Infer the dns suffix from the cluster name for
```release-note
```

Automated cherry pick of #14986: Infer the dns suffix from the cluster name for

---

cmd/kops/create_cluster.go
cmd/kops/edit_cluster.go
cmd/kops/edit_instancegroup.go
cmd/kops/lifecycle_integration_test.go
docs/advanced/experimental.md
pkg/featureflag/featureflag.go
tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/scenarios/digital-ocean/run-test
tests/e2e/scenarios/lib/common.sh
tests/e2e/scenarios/upgrade-ab/run-test.sh
tests/e2e/scenarios/upgrade-ha-leader-migration/run-test.sh

`SpecOverrideFlag` has been around for a long time. It was enabled by default for some time also and it's not going away.
Any missing feature should be addressed in separate issues.

Remove the SpecOverrideFlag feature flag

---

cmd/kops-controller/pkg/server/server.go

Fixes regression from #12997 which caused only one of the kops-controller pods to respond to client requests.

Run kops-controller server on non-leaders as well

---

cmd/kops-controller/pkg/server/server.go

Cherry pick of #15002 on release-1.26.
#15002: Run kops-controller server on non-leaders as well
```release-note
```

Automated cherry pick of #15002: Run kops-controller server on non-leaders as well

---

pkg/model/components/awscloudcontrollermanager.go
tests/integration/update_cluster/karpenter/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-1.25/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.25/data/aws_s3_object_minimal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-1.25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_privatecanal.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/privatecanal/data/aws_s3_object_privatecanal.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-aws-cloud-controller.addons.k8s.io-k8s-1.18_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-bootstrap_content

Cherry pick of #15011 on release-1.25.
#15011: Upgrade AWS CCM to 1.25.2

Automated cherry pick of #15011: Upgrade AWS CCM to 1.25.2

---

cmd/kops-controller/main.go
pkg/nodeidentity/openstack/identify.go

Cherry pick of #15006 on release-1.26.
#15006: update OpenStack node identifier to use Identifier instead of
```release-note
```

Automated cherry pick of #15006: update OpenStack node identifier to use Identifier instead of

---

cmd/kops-controller/main.go
pkg/nodeidentity/openstack/identify.go

The old solution did use LegacyIdentifier. The only difference is that with LegacyIdentifier the kOps for OpenStack added also `node-role.kubernetes.io/node: ""` to control plane. However, I think that is not correct so I think this new model is better.

update OpenStack node identifier to use Identifier

---

hack/go.mod
hack/go.sum

There are 1 security vulnerabilities found in gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
- [CVE-2022-28948](https://www.oscs1024.com/hd/CVE-2022-28948)
Upgrade gopkg.in/yaml.v3 from v3.0.0-20210107192922-496545a6307b to 3.0.0 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

fix(sec): upgrade gopkg.in/yaml.v3 to 3.0.0

---

pkg/model/components/nodeterminationhandler.go
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/nth-imds-processor-irsa/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/nth-imds-processor-irsa/data/aws_s3_object_nthimdsprocessor.longclustername.example.com-addons-bootstrap_content
tests/integration/update_cluster/nth-imds-processor-irsa/data/aws_s3_object_nthimdsprocessor.longclustername.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/nth-imds-processor/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/nth-imds-processor/data/aws_s3_object_nthimdsprocessor.longclustername.example.com-addons-bootstrap_content
tests/integration/update_cluster/nth-imds-processor/data/aws_s3_object_nthimdsprocessor.longclustername.example.com-addons-node-termination-handler.aws-k8s-1.11_content
upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template

Cherry pick of #15020 on release-1.26.
#15020: Upgrade Node Termination Handler to 1.18.3

Automated cherry pick of #15020: Upgrade Node Termination Handler to 1.18.3

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml.template

Not entirely sure about taking the upstream limits.
The change of image name might be incompatible for people who have explicitly configured an LBC version.

Upgrade AWS LBC to v2.4.6

---

tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
upup/models/cloudup/resources/addons/gcp-cloud-controller.addons.k8s.io/k8s-1.23.yaml.template

This permission is needed to update the podCIDR.
When we fix --use-service-account-credentials in GCE CCM, this
permission will not be needed (moving instead to a different
serviceaccount).

gce cloud-controller-manager: Add nodes/patch permission

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.12.1
I noticed that there was some misalignment in the order of the manifests, to I adjusted according to the upstream manifest for a cleaner diff comparison

Bump aws-cni to 1.12.1

---

channels/alpha

- https://github.com/kubernetes/kubernetes/releases/tag/v1.23.16
- https://github.com/kubernetes/kubernetes/releases/tag/v1.24.10
- https://github.com/kubernetes/kubernetes/releases/tag/v1.25.6

bump k8s versions and ubuntu ami version in alpha

---

cmd/kops-controller/pkg/server/server.go
nodeup/pkg/bootstrap/install.go
nodeup/pkg/bootstrap/tests/simple/tasks.yaml
pkg/bootstrap/authenticate.go
upup/pkg/fi/cloudup/awsup/aws_verifier.go
upup/pkg/fi/cloudup/gce/tpm/gcetpmverifier/tpmverifier.go
upup/pkg/fi/cloudup/hetzner/verifier.go
upup/pkg/fi/cloudup/openstack/verifier.go

Cherry pick of #15024 on release-1.26.
#15024: make openstack kops-controller boostrap auth better
```release-note
```

Automated cherry pick of #15024: make openstack kops-controller boostrap auth better

---

docs/releases/1.26-NOTES.md
nodeup/pkg/bootstrap/install.go
nodeup/pkg/bootstrap/tests/simple/tasks.yaml
nodeup/pkg/model/update_service.go

https://flatcar-linux.org/docs/latest/setup/releases/update-strategies/
> For Kubernetes the recommended reboot manager is [FLUO](https://github.com/flatcar/flatcar-linux-update-operator/) which replaces locksmithd because it knows how to gracefully reboot a Kubernetes node. The [kured](https://github.com/weaveworks/kured) reboot manager will be supported as well starting from Flatcar versions with a release number greater than 3067.0.0.

Always disable the reboot manager for Flatcar

---

nodeup/pkg/bootstrap/install.go
nodeup/pkg/bootstrap/tests/simple/tasks.yaml

Cherry pick of #15055 on release-1.26.
#15055: remove condition path exists
```release-note
```

Automated cherry pick of #15055: remove condition path exists

---

docs/releases/1.26-NOTES.md
nodeup/pkg/model/update_service.go

Cherry pick of #15054 on release-1.26.
#15054: Always disable the reboot manager for Flatcar
```release-note
```

Automated cherry pick of #15054: Always disable the reboot manager for Flatcar

---

upup/pkg/fi/http.go

We were capturing the time before waiting for the download.

nodeup: fix logging of download times

---

upup/models/cloudup/resources/addons/scaleway-cloud-controller.addons.k8s.io/k8s-1.24.yaml.template
upup/models/cloudup/resources/addons/scaleway-csi-driver.addons.k8s.io/k8s-1.24.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

This PR adds the manifests for the cloud-controller-manager and the container-storage-interface driver. This is the last step before we can have the cluster verified by `kops validate cluster`. After that we can start implementing e2e tests.

scaleway: CCM and CSI driver

---

upup/pkg/fi/cloudup/azuretasks/loadbalancer.go
upup/pkg/fi/cloudup/azuretasks/publicipaddress.go
upup/pkg/fi/cloudup/new_cluster.go

Using the Standard Load Balancer SKU allows using the LB with AZs and VMSSs:
https://learn.microsoft.com/en-us/azure/load-balancer/skus
This is the last piece from https://github.com/kubernetes/kops/pull/14514.

azure: Use Basic SKU for the API LB

---

nodeup/pkg/bootstrap/install.go
nodeup/pkg/bootstrap/tests/simple/tasks.yaml

Cherry pick of #15078 on release-1.26.
#15078: disable kops-configuration.service after successful execution
```release-note
```

Automated cherry pick of #15078: disable kops-configuration.service after successful execution

---

nodeup/pkg/bootstrap/install.go
nodeup/pkg/bootstrap/tests/simple/tasks.yaml

fixes #15057
cc @johngmyers 
I do not know is this mistake that we enable the `kops-configuration.service` in cloud-init after the nodeup is successfully executed? If we do not do that (this PR), we can reboot machines easily in OpenStack and kops controller bootstrap will work fine (because its not executed anymore after initial execution)

disable kops-configuration.service after successful execution

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstack/cloud_test.go

Cherry pick of #15083 on release-1.26.
#15083: Allow setting 'ignore-volume-microversion' for OCCP
```release-note
```

Automated cherry pick of #15083: Allow setting 'ignore-volume-microversion' for OCCP

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstack/cloud_test.go

This will allow setting the option `ignore-volume-microversion` for the cinder-csi-plugin.
Setting this is necessary for older OpenStack APIs so that OCCP can create PVs.
Note: This will work with cinder-csi-plugin >= 1.25.
For reference:
* https://github.com/kubernetes/cloud-provider-openstack/pull/1986/

Allow setting 'ignore-volume-microversion' for OCCP

---

pkg/nodeidentity/openstack/identify.go

Cherry pick of #15091 on release-1.26.
#15091: add k8s node labels
```release-note
```

Automated cherry pick of #15091: add k8s node labels

---

nodeup/pkg/model/nvidia.go

This PR updates the repositories and the installation of the NVIDIA Container Toolkit.
This ensures that #15094 is less likely to occur in future.

Fix nvidia container toolkit repos

---

nodeup/pkg/model/nvidia.go

Cherry pick of #15096 on release-1.26.
#15096: Use ubuntu18.04 repos for nvidia-container-toolkit
```release-note
```

Automated cherry pick of #15096: Use ubuntu18.04 repos for nvidia-container-toolkit

---

util/pkg/vfs/s3context.go

The bucket validation prevents otherwise correct regions (unknown to the SDK) to be validated.
Fixes: https://github.com/kubernetes/kops/issues/15099

aws: Remove S3 region validation

---

util/pkg/vfs/s3context.go

Cherry pick of #15105 on release-1.26.
#15105: aws: Remove S3 region validation
```release-note
```

Automated cherry pick of #15105: aws: Remove S3 region validation

---

nodeup/pkg/model/containerd.go
nodeup/pkg/model/tests/containerdbuilder/flatcar/tasks.yaml
nodeup/pkg/model/tests/containerdbuilder/from_docker_19.03.11/tasks.yaml
nodeup/pkg/model/tests/containerdbuilder/from_docker_19.03.14/tasks.yaml
nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml

Cherry pick of #15111 on release-1.26.
#15111: Switch contained config file path to
```release-note
```

Automated cherry pick of #15111: Switch contained config file path to

---

docs/releases/1.26-NOTES.md
nodeup/pkg/model/containerd.go
nodeup/pkg/model/tests/containerdbuilder/flatcar/tasks.yaml
nodeup/pkg/model/tests/containerdbuilder/from_docker_19.03.11/tasks.yaml
nodeup/pkg/model/tests/containerdbuilder/from_docker_19.03.14/tasks.yaml
nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml

Using `/etc/containerd/config-kops.toml` was useful when kOps installed deb/rpm packages from https://download.docker.com and was not safe to overwrite the package config file.
Since switching to `.tgz` packages, there is no longer a need for a special config file name, which is mostly confusing for operators.

Switch contained config file path to `/etc/containerd/config.toml`

---

tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-gce-dns-none/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-gce/expected-v1alpha2.yaml
tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/new_cluster.go

This restores the behaviour before #14127, which wasn't documented /
intended.

gce: Always apply the metadata-proxy-ready node label

---

docs/addons.md

Kops 1.25.3 failed to create the SQS queue for aws node termination handler addon in SQS mode:
```
W0209 14:52:45.394593     231 executor.go:139] error running task "SQS/<cluster name redacted>-nth" (7m34s remaining to succeed): error creating SQS queue: AccessDenied: Access to the resource https://sqs.us-east-1.amazonaws.com/ is denied.
15:52:45  	status code: 403, request id: 1cd940c8-db6c-5038-a172-1c97d1911040
```
Adding `"sqs:TagQueue"` to the kops role fixed the error.
The PR adjusts the documented permissions that kops requires to setup infrastructure for kops NTH addon in SQS mode.

Document missing kops permission for aws NTH addon in SQS mode

---

.github/workflows/update-deps.yml

Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Resolve #15115 
Update `update-deps.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find .github/workflows -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
echo "::set-output name=changes::$(git status --porcelain)"
```
**TO-BE**
```yml
echo "changes=$(git status --porcelain)" >> $GITHUB_OUTPUT
```

Replace deprecated command with environment file

---

pkg/resources/digitalocean/resources.go

Now we have some IPv6 support, we were printing an empty address when
machines did not have an IPv6 address.

digitalocean: don't print empty IP addresses

---

tests/integration/create_cluster/ha_openstack/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_openstack_nodns/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_openstack_octavia/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/new_cluster.go

fixes #15108
We cannot add it to existing clusters (this value is used things like loadbalancer and routes), we can add it only to new clusters.

Add cluster name to OCCM opts

---

tests/e2e/kubetest2-kops/aws/zones_test.go

We previously tested that we could not generate 4 zones in a region,
but now us-east-1 has 6 zones, so we need to update the tests to fail
only when even more zones are requested.

kubetest2-kops: update tests for new zones

---

tests/integration/create_cluster/ha_openstack/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_openstack_nodns/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_openstack_octavia/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/new_cluster.go

Cherry pick of #15139 on release-1.26.
#15139: add clustername to ccm opts
```release-note
```

Automated cherry pick of #15139: add clustername to ccm opts

---

pkg/model/iam/iam_builder.go
tests/integration/update_cluster/minimal-dns-none/data/aws_iam_role_policy_nodes.minimal.example.com_policy

Normal nodes does not need S3 access after using none dns

remove AWS S3 access from nodes if using none dns

---

pkg/model/iam/iam_builder.go
tests/integration/update_cluster/minimal-dns-none/data/aws_iam_role_policy_nodes.minimal.example.com_policy

Cherry pick of #15145 on release-1.26.
#15145: remove s3 access from nodes if using none dns
```release-note
```

Automated cherry pick of #15145: remove s3 access from nodes if using none dns

---

pkg/resources/hetzner/resources.go

This avoids warnings about deleting e.g. the volume while it is still
attached to a server.

hetzner: add dependency logic to deletion

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
tests/integration/create_cluster/ha_openstack/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_openstack_nodns/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_openstack_octavia/expected-v1alpha2.yaml
upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/new_cluster.go

This passes the acutal cluster name to the cinder-csi-plugin, so that the plugin will add the name as metadata to the backing volume in OpenStack.
Effectively, the change will help to better identify which volume in OpenStack belongs to which cluster, which is especially helpful when running multiple clusters in one OpenStack tenant/project.
Setting the cluster name in both - the controller and the nodeplugin - pods will ensure that dynamic and ephemeral volumes will receive the correct metadata.

Pass actual cluster name to cinder-csi-plugin

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
tests/integration/create_cluster/ha_openstack/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_openstack_nodns/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_openstack_octavia/expected-v1alpha2.yaml
upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/new_cluster.go

Cherry pick of #15095 on release-1.26.
#15095: Pass actual cluster name to cinder-csi-plugin
```release-note
```

Automated cherry pick of #15095: Pass actual cluster name to cinder-csi-plugin

---

pkg/model/awsmodel/autoscalinggroup.go
tests/integration/update_cluster/minimal-warmpool/kubernetes.tf
upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go
upup/pkg/fi/cloudup/awstasks/warmpool.go

Cherry pick of #15153 on release-1.26.
#15153: Add terraform target support for configuring Warm Pool
```release-note
```

Automated cherry pick of #15153: Add terraform target support for configuring Warm Pool

---

docs/releases/1.26-NOTES.md

This adds a release note documenting setting the cluster name flags for OCCM and Cinder CSI plugin.
For reference:
* https://github.com/kubernetes/kops/pull/15139
* https://github.com/kubernetes/kops/pull/15095

Document setting cluster name flag for OCCM and Cinder CSI plugin

---

tests/e2e/scenarios/smoketest/run-test.sh

This is a simple minimal scenario designed to make it easy to run with
a particular version of kOps.
The initial use-case is for testing artifacts-sandbox.k8s.io.

tests: create smoketest scenario

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

Cherry pick of #15160 on release-1.26.
#15160: Update Go to v1.19.6
```release-note
```

Automated cherry pick of #15160: Update Go to v1.19.6

---

cmd/kops-controller/pkg/server/server.go
pkg/bootstrap/authenticate.go
pkg/kopscontrollerclient/client.go
upup/pkg/fi/cloudup/openstack/verifier.go

Original issue for this is https://github.com/kubernetes/kops/issues/15057 but it was reverted due to other issues in https://github.com/kubernetes/kops/pull/15129
some discussion available in https://github.com/kubernetes/kops/pull/15114#pullrequestreview-1287780870
I have verified that this solution works in OpenStack. When existing instance tries to join again to cluster (it does that when rebooting server OR restarting kops-configuration.service):
kops-controller log:
```
kops-controller-t4b8j kops-controller I0212 14:11:02.063861       1 server.go:148] 10.2.96.248:59480: instance already exists in kubernetes cluster
```
node log
```
Feb 12 14:11:03 nodes-helpa-fctnib nodeup[669]: I0212 14:11:03.187949     669 client.go:156] bootstrap request responded with code 204
Feb 12 14:11:03 …
```

exit nodeup gracefully if server already exists in k8s

---

upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #15169 on release-1.26.
#15169: update openstack csi & ccm versions
```release-note
```

Automated cherry pick of #15169: update openstack csi & ccm versions

---

docs/iam_roles.md

This feature was renamed during its [development](https://github.com/kubernetes/kops/pull/7837) and a remnant of that original name was in the docs. Fixing this because it confused me enough to have to look up what the correct config was in the code.

[docs] Fix External IAM Policy Docs

---

pkg/apis/kops/validation/aws.go
pkg/apis/kops/validation/validation.go
pkg/apis/kops/validation/validation_test.go

We split out the "add to a slice" logic, as this is then easier to
reason about.
Should be a no-op in terms of valid inputs, might avoid some crashes
with invalid inputs.

validation cleanup: simplify signature of validateCIDR

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/components/openstack.go

like it says in code
```
// Node status updates are happening unnecessarily often in kOps OpenStack.
// Node status updates are useful if we are updating existing node flavor type or node addresses.
// However, that will not happen when using kOps.
// see more discussion in https://github.com/kubernetes/cloud-provider-openstack/pull/2133
```

set node status update freq to 60min in OpenStack

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/components/openstack.go

Cherry pick of #15180 on release-1.26.
#15180: set node status update freq to 60min in OpenStack
```release-note
```

Automated cherry pick of #15180: set node status update freq to 60min in OpenStack

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/cluster.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/cluster.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template

Allow users to provide entirely custom CoreFile for NodeLocalDNS to provide improved flexibility.

feat(NodeLocalDNS): Add possibility to set an ExternalCoreFile

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/cluster.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/cluster.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template

Cherry pick of #15183 on release-1.26.
#15183: feat(nodelocaldns): Add possibility to set an
```release-note
```

Automated cherry pick of #15183: nodelocaldns: Add possibility to set ExternalCoreFile

---

upup/pkg/fi/cloudup/defaults.go
upup/pkg/fi/cloudup/gce/network.go

We do need a non-masquerade CIDR, and we can use the range we draw the pod CIDRs from (10.0.0.0/8).

Set the nonMasqueradeCIDR for GCE networking

---

pkg/model/gcemodel/api_loadbalancer.go
pkg/model/gcemodel/external_access.go

If we're not masquerading the pod IPs, we need an explicit firewall
rule for the pods to reach the kube-apiserver.  Normally this is
permitted anyway, but if the apiserver has a locked-down CIDR range
(as the e2e tests do) then we need our own rule.

gce: When using network native pod IPs, open firewall to apiserver

---

pkg/model/gcemodel/api_loadbalancer.go
pkg/model/gcemodel/external_access.go

Cherry pick of #15040 on release-1.26.
#15040: gce: When using network native pod IPs, open firewall to
```release-note
```

Automated cherry pick of #15040: gce: When using network native pod IPs, open firewall to

---

tests/e2e/kubetest2-kops/deployer/publish.go

When uploading the version marker, make sure we turn off caching.
Otherwise we see jobs using older versions than they should be
running.

kubetest2: don't cache version markers

---

.github/workflows/update-deps.yml

After https://github.com/kubernetes/kops/pull/15116, the `Update Dependencies` workflow fails with:
```
2023-03-03T06:10:37.2632799Z ##[error]Unable to process file command 'output' successfully.
2023-03-03T06:10:37.2643940Z ##[error]Invalid format ' M go.sum'
```
This should be fixed by applying https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings.

Fix error in dependencies update workflow

---

pkg/model/components/gcpcloudcontrollermanager.go
tests/integration/update_cluster/ha_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content

Cherry pick of #15186 on release-1.26.
#15186: gce: Don't reconcile routes when running with "gce"
```release-note
```

Automated cherry pick of #15186: gce: Don't reconcile routes when running with "gce"

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

Cherry pick of #15198 on release-1.25.
#15198: Update Go to v1.19.7
```release-note
```

Automated cherry pick of #15198: Update Go to v1.19.7

---

pkg/model/components/apiserver.go
pkg/model/components/kubecontrollermanager.go
pkg/model/components/kubelet.go
pkg/model/components/kubescheduler.go
tests/integration/update_cluster/minimal/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal/in-v1alpha2.yaml
tests/integration/update_cluster/minimal/kubernetes.tf

All AWS e2e jobs using CI builds of k/k started failing after the AWS in-tree provider was removed:
https://testgrid.k8s.io/kops-ipv6#kops-aws-cni-cilium-ipv6
https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-cni-cilium-ipv6/1633186496192188416/artifacts/2600:1f13:831:2b01:7a9c:e176:b0fb:800d/kubelet.log
`E0307 19:29:58.709805    3441 run.go:74] "command failed" err="failed to set feature gates from initial flags-based config: unrecognized feature gate: CSIMigrationAWS"`
This removes the feature gate starting in k8s 1.27

Don't set CSIMigrationAWS in k8s 1.27

---

pkg/model/components/clusterautoscaler.go
tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cas-priority-expander-custom.example.com-addons-bootstrap_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cas-priority-expander-custom.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cas-priority-expander.example.com-addons-bootstrap_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cas-priority-expander.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content

Cherry pick of #14952 on release-1.26.
#14952: Bump cluster autoscaler to 1.26.1
```release-note
```

Automated cherry pick of #14952: Bump cluster autoscaler to 1.26.1

---

protokube/pkg/protokube/scaleway_volumes.go

In #15122 I removed the default region from the client options when creating a Scaleway client for protokube (as I thought it was no use since protokube only makes requests to zoned APIs). 
But it turns out I have to rollback this change because now I get this error, which I haven't encountered earlier :
`Error initializing Scaleway: "error creating client: scaleway-sdk-go: default region cannot be empty"`

scaleway: fix client for protokube

---

docs/operations/images.md
util/pkg/distributions/distributions.go
util/pkg/distributions/identify.go
util/pkg/distributions/identify_test.go
util/pkg/distributions/tests/debian12/etc/os-release

Initial support for the upcoming Debian 12
This currently requires a custom image to be built. That image will need to have the debian package base-files 12.4 installed which is not yet available in testing (but is available in unstable and is expected to be migrated soon).

Initial support for Debian 12 Bookworm

---

pkg/model/awsmodel/iam.go

Fixes https://github.com/kubernetes/kops/issues/15232
Same as for external policies:
https://github.com/kubernetes/kops/blob/071f9a86ad5ee2c0fcf7388206a92beeed743714/pkg/model/awsmodel/iam.go#L326-L332

aws: Use `control-plane` for additional policies instead of `master`

---

pkg/model/awsmodel/iam.go

Cherry pick of #15238 on release-1.26.
#15238: aws: Use `control-plane` for additional policies instead of
```release-note
```

Automated cherry pick of #15238: aws: Use `control-plane` for additional policies instead of

---

tests/e2e/pkg/tester/skip_regex.go

This new test is failing. It was added in k8s 1.27 (currently only CI builds). All CI+cilium kops jobs are failing. [Example](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-scenario-no-irsa/1636557404302741504).
Skipping this test until we're upgraded to 1.13 to see if that fixes the failing test

Skip multiple-port multiple-endpointslice e2e test with Cilium

---

pkg/kubeconfig/create_kubecfg.go
pkg/kubeconfig/create_kubecfg_test.go

Cherry pick of #15244 on release-1.26.
#15244: Fix behaviour for `kops export kubeconfig --internal`
```release-note
```

Automated cherry pick of #15244: Fix behaviour for `kops export kubeconfig --internal`

---

upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template
upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #15249 on release-1.26.
#15249: switch to use registry.k8s.io images for openstack
```release-note
```

Automated cherry pick of #15249: switch to use registry.k8s.io images for openstack

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Cherry pick of #15248 on release-1.26.
#15248: bump aws cni to 1.12.5 and align with vendor chart
```release-note
```

Automated cherry pick of #15248: bump aws cni to 1.12.5 and align with vendor chart

---

cloudmock/openstack/mockcompute/servers.go
upup/pkg/fi/cloudup/openstack/instance.go
upup/pkg/fi/cloudup/openstack/instance_test.go
upup/pkg/fi/cloudup/openstacktasks/instance.go

This aims to improve the experience when creating openstack servers and they run into issues during scheduling, which is not covered by the create API request.
So after creating the instance kops waits for it to become ACTIVE and if not, tries to reprovision the instance by deleting the failed instance and creating a new one.
If the last attempt was still not successful, erroneous instances will persist to allow further investigation, and the task will fail, which will ultimately fail the update call.

Retry creating failed OpenStack servers

---

cloudmock/openstack/mockcompute/servers.go
upup/pkg/fi/cloudup/openstack/instance.go
upup/pkg/fi/cloudup/openstack/instance_test.go
upup/pkg/fi/cloudup/openstacktasks/instance.go

Cherry pick of #15102 on release-1.26.
#15102: Retry creating failed OpenStack servers
```release-note
```

Automated cherry pick of #15102: Retry creating failed OpenStack servers

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
upup/pkg/fi/cloudup/openstack/cloud.go

This will add the OCCM config to specify an address sort order:
* https://github.com/kubernetes/cloud-provider-openstack/pull/1946

OpenStack: Add OCCM address sort order config

---

upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template

Update kube-router to v1.5.3
Tried in aws provider using kops ans other components built based on master and it worked as it was in v1.2.3

Update kube-router to v1.5.3

---

docs/getting_started/openstack.md
pkg/model/openstackmodel/servergroup.go
pkg/model/openstackmodel/servergroup_test.go
pkg/model/openstackmodel/tests/servergroup/adds-additional-security-groups.yaml
pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-ClusterSpec.yaml
pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-InstanceGroupSpec.yaml
pkg/model/openstackmodel/tests/servergroup/configures-allowed-address-pairs-with-annotations.yaml
pkg/model/openstackmodel/tests/servergroup/configures-server-group-affinity-with-annotations.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-auto-zone-distribution.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer-dns-none.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-external-router.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion-2.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node-without-bastion-no-public-ip-association.yaml
pkg/model/openstackmodel/tests/servergroup/truncate-cluster-names-to-42-characters.yaml
pkg/model/openstackmodel/tests/servergroup/uses-instance-group-subnet-as-availability-zones-fallback.yaml
pkg/model/openstackmodel/tests/servergroup/uses-instance-group-zones-as-availability-zones.yaml
upup/pkg/fi/cloudup/openstack/instance.go
upup/pkg/fi/cloudup/openstacktasks/port.go
upup/pkg/fi/cloudup/openstacktasks/port_test.go

This enables setting allowed address pairs for ports via IG annotations, which can be beneficial when hosting workloads on the nodes which need to work around the spoofing protection of OpenStack (keepalived, Calico without IPIP or other encapsulation, etc.). 
It works by adding multiple annotations to an IG config, like so:
```yaml
metadata:
annotations:
openstack.kops.io/allowedAddressPair/N: <IP>(,<MAC>)
```
Where `N` can be an arbitrary identifier, and the MAC address is optional.

OpenStack: Allow setting allowed address pairs for ports

---

docs/getting_started/openstack.md

This basically formats the getting started doc of OpenStack to adhere to the markdownlint rules and also includes some minor tweaks, like adapt the headings to make the TOC work again, remove trailing spaces, and use more consistent punctuation for pointing out examples.
It also adds some missing docu about Instance Group config which can be achieved by annotations and thus is not visible in the Instance Group API reference.

OpenStack: Format and improve getting started docu

---

pkg/model/gcemodel/firewall.go
upup/pkg/fi/cloudup/gcetasks/firewallrule.go

We were previously relying on the name, but the name was "fooled" by
cluster names like ipv6.example.com

GCE FirewallRule: Use an explicit field for ipv4 vs ipv6

---

upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template

Cherry pick of #15270 on release-1.26.
#15270: Update kube-router to v1.5.3
```release-note
```

Automated cherry pick of #15270: Update kube-router to v1.5.3

---

docs/networking/calico.md

Multiple Calico link is broken in https://github.com/kubernetes/kops/blob/master/docs/networking/calico.md

Corrected multiple broken link in calico.md
