pkg/featureflag/featureflag.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/dotasks/droplet.go
upup/pkg/fi/cloudup/dotasks/sshkey.go
upup/pkg/fi/cloudup/dotasks/volume.go
upup/pkg/fi/cloudup/terraform/target_hcl2.go
util/pkg/vfs/s3fs.go

Initial work to get the terraform support for DO.
- Tested by creating a cluster with `--out terraform` like below.
```
kops create cluster --cloud=digitalocean --name=dev6.****.co.in --node-count=2 --networking=calico --zones=sfo3 --ssh-public-key=~/.ssh/id_ed25519.pub --target=terraform --out=./terraform-test -v=6
```
- kubernetes.tf file gets created with digitial ocean specific resources. snippet below.
```
output "cluster_name" {
value = "dev6.test.co.in"
}
output "region" {
value = "sfo3"
}
provider "digitalocean" {
}
resource "digitalocean_droplet" "control-plane-sfo3-1-masters-dev6-test-co-in" {
image     = "ubuntu-20-04-x64"
name      = "control-plane-sfo3-1.masters.dev6.test.co.in"
region    = "sfo3"
size      = "s-2vcpu-4gb"
ssh_keys  = …
```

[DigitalOcean] support terraform provider for DO

---

pkg/model/components/etcdmanager/model.go

This add the possibility of setting `--network-cidr` for etcd-manager when using OpenStack, which was introduced with https://github.com/kubernetes-sigs/etcdadm/pull/317

OpenStack: Add network-cidr config for etcd-manager

---

nodeup/pkg/model/sysctls.go

We need to increase this value because we can't deploy Arangodb.
Logs from the pod
```
2023-04-13T07:07:14Z [1] INFO [e52b0] {general} ArangoDB 3.9.1 [linux] 64bit, using jemalloc, build tags/v3.9.1-0-g55736e046ee, VPack 0.1.35, RocksDB 6.27.0, ICU 64.2, V8 7.9.317, OpenSSL 1.1.1n  15 Mar 2022
2023-04-13T07:07:14Z [1] INFO [75ddc] {general} detected operating system: Linux version 5.4.0-135-generic (buildd@lcy02-amd64-066) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022
2023-04-13T07:07:14Z [1] INFO [25362] {memory} Available physical memory: 8343769088 bytes, available cores: 4
2023-04-13T07:07:14Z [1] INFO [144fe] {general} using storage engine 'rocksdb'
2023-04-13T07:07:14Z [1] INFO [3bb7d] {cluster} Starting up with role SINGLE …
```

Increase max_map_count in sysctls.go

---

nodeup/pkg/model/sysctls.go

Cherry pick of #15311 on release-1.26.
#15311: Increase max_map_count in sysctls.go
```release-note
```

Automated cherry pick of #15311: Increase max_map_count in sysctls.go

---

upup/pkg/fi/cloudup/gcetasks/forwardingrule.go

```
Will modify resources:
ForwardingRule/europe-central2-my-k8s-my-k8s
LoadBalancingScheme 	 <nil> -> INTERNAL
Network             	 <nil> -> name:my-k8s id:my-k8s
Subnetwork          	 <nil> -> name:europe-central2-my-k8s id:europe-central2-my-k8s
BackendService      	 <nil> -> name:api-my-k8s id:api-my-k8s
```
/cc @justinsb

gce: Avoid spurious changes for ForwardingRule

---

docs/releases/1.22-NOTES.md

* Brea_c_king -> Breaking
* Stumbled upon this while looking over the 1.22 Notes searching for a change note about https://github.com/kubernetes/kops/pull/11921
* See my other PR: https://github.com/kubernetes/kops/pull/15324

docs(release): fix typo in 1.22 Notes

---

docs/releases/1.19-NOTES.md

Link to `kops delete instance` doc was broken
Same as #15325 , I had started this and some other docs changes a while ago, finally got to them while making other docs PRs 😅 
Also this command is super useful! How have I not known about it for years??

docs(release): fix broken CLI link in 1.19 notes

---

pkg/model/gcemodel/api_loadbalancer.go
pkg/model/gcemodel/external_access.go

We had missed a few code paths previously.

gce: set ip address family on all FirewallRule tasks

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/openstackmodel/firewall.go
upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template

add support for enabling prometheus metrics for csi https://github.com/kubernetes/cloud-provider-openstack/pull/2077

add csi cinder metrics

---

pkg/model/gcemodel/firewall.go

IPv6 in firewalls must use icmpv6, not icmp.  Remap in our ipv6
generator for simplicity.

gce: fix icmpv6 in firewalls

---

docs/getting_started/scaleway.md

Until the integration of #15230 in the next release of protokube, we specify in the doc that we have to use the environment variable KOPS_BASE_URL to pull the version from master.

scaleway: doc: temporary env var to pull protokube

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go
upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go

Since we use kops as lib, we need to reset this variable so that we can create clients with another AWS account.
Here is an example that also follows the same idea and was recently changed:
https://github.com/kubernetes/kops/blob/v1.26.2/util/pkg/vfs/context.go#L65

Create func to reset awsCloudInstances

---

cmd/kops-controller/main.go
cmd/kops-controller/pkg/config/options.go
nodeup/pkg/model/bootstrap_client.go
pkg/apis/kops/model/features.go
pkg/apis/kops/validation/validation.go
pkg/model/bootstrapscript.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/do/authenticator.go
upup/pkg/fi/cloudup/do/verifier.go
upup/pkg/fi/cloudup/dotasks/loadbalancer.go
upup/pkg/fi/cloudup/openstack/verifier.go
upup/pkg/fi/cloudup/template_functions.go
upup/pkg/fi/nodeup/command.go

Update DigitalOcean to support bootstrapping nodes through kops-controller.
This means we no longer need to put the DO credentials onto the nodes.

DigitalOcean support for node bootstrap

---

hack/upload

Similar to GCS with UBLA, S3 is now encouraging buckets that block
ACLs.  When we upload to one of these buckets, we cannot set ACLs.
When we detect one of these buckets, we simply skip setting the ACL,
assuming the object ACLs are instead managed at the bucket level, when
the bucket was created.

upload helper: support upload to S3 buckets that block ACLs

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go

What is our current problem? We are hosting kOps management portal in AWS (which has AWS role). We are using that to provision clusters to another AWS accounts. Currently we are using management portal role and calling assumerole to another account role. However, because its called "role chaining" we can get maximum 1 hour long credentials from STS. In all cases the 1 hour long credentials are not enough (for instance kops rolling-update). My goal in this PR is that kOps could automatically refresh assumed role. So in future I could just specify `AWS_ASSUME_ROLE_ARN` to kOps cli binary, and it will automatically assume and refresh itself if needed.

Make it possible to use assume role

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Cherry pick of #15387 on release-1.26.
#15387: bump aws cni to 1.12.6
```release-note
```

Automated cherry pick of #15387: bump aws cni to 1.12.6

---

channels/alpha

**What this PR does / why we need it**: Bumping k8s versions and ubuntu ami version in alpha to most recent ones
- https://github.com/kubernetes/kubernetes/releases/tag/v1.26.4
- https://github.com/kubernetes/kubernetes/releases/tag/v1.25.9
- https://github.com/kubernetes/kubernetes/releases/tag/v1.24.13
- https://cloud-images.ubuntu.com/locator/ec2/

bump k8s versions and ubuntu ami to latest in alpha

---

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.12.yaml.template

Cherry pick of #15360 on release-1.26.
#15360: If the Cluster Name is not default the hubble relay shows TLS
```release-note
```

Automated cherry pick of #15360: If the Cluster Name is not default the hubble relay shows TLS

---

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.12.yaml.template

This change uses the ClusterName value to correctly set the dnsName for certificate generation
Updated Files
* Update: upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.12.yaml.template

If the Cluster Name is not default the hubble relay shows TLS errors

---

pkg/nodeidentity/scaleway/identify.go
upup/models/cloudup/resources/addons/scaleway-cloud-controller.addons.k8s.io/k8s-1.24.yaml.template
upup/models/cloudup/resources/addons/scaleway-csi-driver.addons.k8s.io/k8s-1.24.yaml.template
upup/pkg/fi/cloudup/scaleway/cloud.go

This PR fixes a few details in various files:
- in the manifests for CCM and CSI: there were typos in the comments
- in node identifier: we can get the zone from the uuid instead of the client
- in GetClusterServers: the parameter serverName is not well named, I think it would be better to call it instanceGroupName instead

scaleway: fix naming and typos

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-snapshot-controller.addons.k8s.io-k8s-1.20_content
upup/models/cloudup/resources/addons/snapshot-controller.addons.k8s.io/k8s-1.20.yaml.template

Deployment manifest of snapshot-validation-deployment was missing a service account and hence was using the default one that exists in kube-system namespace.
This caused it to log `Failed to watch *v1.VolumeSnapshotClass` errors

Add missing ServiceAccount in snapshot-validation-deployment

---

pkg/model/master_volumes.go
pkg/model/scalewaymodel/api_loadbalancer.go
pkg/model/scalewaymodel/instances.go
tests/integration/update_cluster/minimal_scaleway/kubernetes.tf
upup/pkg/fi/cloudup/scalewaytasks/instance.go

In this PR, we make sure that every resource (that supports tags) gets tagged with the cloud labels at creation. 
For now only load-balancers had this feature.

scaleway: tag resources with cloud labels

---

nodeup/pkg/model/kube_apiserver.go
nodeup/pkg/model/kube_controller_manager.go
nodeup/pkg/model/kube_proxy.go
nodeup/pkg/model/kube_scheduler.go
pkg/kubemanifest/volumes.go
pkg/model/components/etcdmanager/model.go

This means that the object is not mutated after construction, making
it easier to do validity checks (such as whether we have mounted the
same path twice).

nodeup: Use functional options pattern for HostPathMapping

---

pkg/model/awsmodel/api_loadbalancer.go
pkg/model/awsmodel/bastion.go
pkg/model/awsmodel/dns.go
pkg/model/context.go
tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
tests/integration/update_cluster/complex/kubernetes.tf
tests/integration/update_cluster/existing_sg/kubernetes.tf
tests/integration/update_cluster/externalpolicies/kubernetes.tf
tests/integration/update_cluster/private-shared-ip/kubernetes.tf
tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
tests/integration/update_cluster/privatecalico/kubernetes.tf
tests/integration/update_cluster/privatecanal/kubernetes.tf
tests/integration/update_cluster/privatecilium-eni/kubernetes.tf
tests/integration/update_cluster/privatecilium/kubernetes.tf
tests/integration/update_cluster/privatecilium2/kubernetes.tf
tests/integration/update_cluster/privateciliumadvanced/kubernetes.tf
tests/integration/update_cluster/privatedns1/kubernetes.tf
tests/integration/update_cluster/privatedns2/kubernetes.tf
tests/integration/update_cluster/privateflannel/kubernetes.tf
tests/integration/update_cluster/privatekopeio/kubernetes.tf
tests/integration/update_cluster/privateweave/kubernetes.tf
tests/integration/update_cluster/unmanaged/kubernetes.tf
upup/pkg/fi/cloudup/awstasks/network_load_balancer.go

Makes NLBs be dualstack whenever possible, which is when the subnets assigned to the load balancer have IPv6 addresses. Previously kOps would try to decide based on whether the control plane or apiserver instance groups were in at least one subnet with IPv6, but a bug in that code would cause it to incorrectly make IPv4-only NLBs.
Also makes the bastion NLB dualstack when possible.
Always registers AAAA alias records for the API and bastion load balancers. There is no downside to this.

Make NLBs dualstack when they're in IPv6-capable subnets

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/networking.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/in-v1alpha2.yaml
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.12.yaml.template

Cherry pick of #15389 on release-1.26.
#15389: Support Cilium operator pod annotations
```release-note
```

Automated cherry pick of #15389: Support Cilium operator pod annotations

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/openstackmodel/servergroup.go
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer-dns-none.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstacktasks/lb.go

Support for OpenStack Octavia FlavorID parameter

OpenStack Octavia FlavorID

---

nodeup/pkg/model/kube_apiserver.go

I am trying the current master and the error is
```
syslog:May 11 07:52:10 master-helpa-6hqpcj kubelet[3235]: E0511 07:52:10.874853    3235 file.go:187] "Could not process manifest file" err="invalid pod: [spec.containers[0].volumeMounts[14].mountPath: Invalid value: \"/srv/kubernetes/kube-apiserver\": must be unique]" path="/etc/kubernetes/manifests/kube-apiserver.manifest"
```
full kube-apiserver spec https://gist.github.com/zetaab/bb55d42b4a998a9ee7695b4e98d40274
like can be seen `/srv/kubernetes/kube-apiserver` is two times there. We have been using following kops spec for years:
```
auditPolicyFile: /srv/kubernetes/kube-apiserver/policy.yaml
auditWebhookConfigFile: /srv/kubernetes/kube-apiserver/audit.yaml
```
but now it looks like it will break the apiserver because it will try to …

do not mount same dir twice

---

dns-controller/cmd/dns-controller/main.go
dnsprovider/pkg/dnsprovider/providers/openstack/designate/designate.go
pkg/resources/openstack/dns.go
upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstack/dns.go
upup/pkg/fi/cloudup/openstack/mock_cloud.go
upup/pkg/fi/cloudup/template_functions.go

fixes #15337
@fchiacchiaretta this at least now makes new cluster and designate zone records are updated after masters are started.
tested in devstack, so I could not roll out full cluster to test everything - but at least master was starting.
```
./kops create cluster \
--cloud openstack \
--name jessetesti.foo.com \
--state ${KOPS_STATE_STORE} \
--zones nova \
--network-cidr 10.2.0.0/16 \
--image ubuntu-2004-170423-devops \
--master-count=1 \
--node-count=1 \
--node-size m1.small \
--master-size m1.medium \
--etcd-storage-type lvmdriver-1 \
--topology private \
--networking calico \
--api-loadbalancer-type public \
--os-octavia=true \
--os-ext-net public
```
```
openstack recordset list 316634f8-1e74-45e7-a1fe-43006d9c30c2
+--------------------------------------+------------------------- …
```

openstack designate fixes

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go
upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go

We're using terraform kops provider to manage our AWS kops clusters. Time to time we hit a race condition with the stack trace points to `awsup.NewAWSCloud` function, when writing to a concurrent map, that maintains a map between regions and `AWSCloud` objects.
This PR changes this to variable so it belongs to a new type, that wraps the map into its own struct where access is controlled by a mutex lock.
Let me know if that makes sense to you all.
Thanks for building this awesome project!

Add a mutex lock to 'awsCloudInstances' map

---

pkg/model/openstackmodel/tests/servergroup/adds-additional-security-groups.yaml
pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-ClusterSpec.yaml
pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-InstanceGroupSpec.yaml
pkg/model/openstackmodel/tests/servergroup/configures-allowed-address-pairs-with-annotations.yaml
pkg/model/openstackmodel/tests/servergroup/configures-server-group-affinity-with-annotations.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-auto-zone-distribution.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer-dns-none.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-external-router.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion-2.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node-without-bastion-no-public-ip-association.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node.yaml
pkg/model/openstackmodel/tests/servergroup/truncate-cluster-names-to-42-characters.yaml
pkg/model/openstackmodel/tests/servergroup/uses-instance-group-subnet-as-availability-zones-fallback.yaml
pkg/model/openstackmodel/tests/servergroup/uses-instance-group-zones-as-availability-zones.yaml
upup/pkg/fi/cloudup/openstack/instance.go
upup/pkg/fi/cloudup/openstacktasks/instance.go

This will make use of the kOps taks engine to retry failed servers.
The [former approach](https://github.com/kubernetes/kops/pull/15102) had the side effect of not making kOps fail when the last retry failed:
Because there is now a server present - although in an erroneous state - the "instance task" which the task engine retried reconciled the server (port, floating ip) instead of recreating it again.
With the approach of letting the task engine retry the failed servers this will be handled correctly.

OpenStack: Use task engine to retry failed servers

---

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.12.yaml.template

Starting cilium version `1.12.8` and to reduces the potential security surface of the agent, Cilium removes the bind-mount of `/opt/cni/bin` into the template. Instead, write the binaries once in an initContainer.
Ref:
- https://github.com/cilium/cilium/pull/24075

fix(cilium): install CNI plugin binary in an InitContainer

---

upup/pkg/fi/cloudup/openstack/server_group.go

This will allow kOps to build an OpenStack InstanceGroup with a missing fixed IP.
In essence this will get rid of `interface name X not found` errors, when there are servers present which do not have an interface attached or are in a state (e.g. `ERROR`) which does not allow this. And will mark such a server with `NeedsUpdate`.
Currently this will happen:
```log
❯ openstack server list --status ERROR
2b2a77cc-8edb-4b21-b23c-dca515264aea worker-avjtq4    ERROR
6cf7570c-78d2-49e9-af5a-7376246d7cce worker-ijaqik    ERROR
❯ kops get instances
Error: error getting cloud instance group "worker": error creating cloud instance group member: server `6cf7570c-78d2-49e9-af5a-7376246d7cce` interface name `my-cluster-network` not found
❯ kops validate cluster
Validating cluster my-cluster.k8s.local …
```

OpenStack: Build InstanceGroup despite missing IP

---

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.11.yaml.template

Cherry pick of #15336 on release-1.25.
#15336: fix(cilium): install CNI plugin binary in an InitContainer
```release-note
```

Automated cherry pick of #15336: fix(cilium): install CNI plugin binary in an InitContainer

---

upup/pkg/fi/cloudup/openstacktasks/instance.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces/results.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces/urls.go
vendor/modules.txt

This makes use of the interface attach method when reconciling server ports.
The difference between just setting the `DeviceID` on the Port and this is that with the attachment process the server is also validated. Which means for example that a Port cannot be attached to a server in `ERROR`
state.

OpenStack: Use interface attach when reconciling server ports 

---

pkg/model/components/hetznercloudcontrollermanager.go
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.example.com-addons-hcloud-cloud-controller.addons.k8s.io-k8s-1.22_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.example.com-addons-hcloud-csi-driver.addons.k8s.io-k8s-1.22_content
upup/models/cloudup/resources/addons/hcloud-csi-driver.addons.k8s.io/k8s-1.22.yaml.template

This pull request bumps the default version of the Hetzner `cloud-controller-manager` and `csi-driver`. Hetzner has recently released ARM instances and these versions have multi arch support.

feat(hetzner): bump cloud-controller-manager and csi-driver

---

docs/getting_started/scaleway.md
pkg/apis/kops/validation/validation.go
upup/pkg/fi/cloudup/apply_cluster.go

This PR adds the possibility for Scaleway clusters to use no DNS.

scaleway: none DNS option available

---

docs/getting_started/spot-ocean.md
pkg/model/awsmodel/spotinst.go
upup/pkg/fi/cloudup/spotinsttasks/ocean.go

Ocean will spread the nodes across markets by this value,"vcpu" or "count"

Spotinst: add feature spread nodes by count/vcpu to markets

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Vendored manifest from the [official release](https://github.com/cert-manager/cert-manager/releases/tag/v1.12.1)
Made sure to change back every namespace ref from `cert-manager` to `kube-system` to maintain the current structure. Also re-added all the specific logic for `nodeAffinity` and `tolerations`, and some of the templated variables that were previously there.

Bump cert-manager addon to v1.12.1 (latest release)

---

docs/releases/1.19-NOTES.md

Note that the change to the kubelet serving cert allows one to avoid `--kubelet-insecure-tls` usage with _any_ installation of `metrics-server`
- I had brought attention to this issue in https://github.com/kubernetes/kops/issues/6879#issuecomment-642966333 and https://github.com/kubernetes-sigs/metrics-server/issues/541 (but did not know how to fix it myself -- big thanks to Ole again!). I also mentioned the lack of security details in https://github.com/kubernetes/kops/pull/10022#discussion_r608871128
- was requested to submit a PR for this note as well, finally got to pushing this up 😅
- this is good encouragement for folks to remove `--kubelet-insecure-tls` from their code for better security
Same as #15326 and #15325 , I had started this and some other docs changes a while ago, …

docs(release): add improved security of `metrics-server` note to 1.19

---

tests/integration/create_cluster/minimal_hetzner/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/new_cluster.go

For new clusters only, default to dns=none on hetzner and
digitalocean.
Hetzner previously used dns=private (with the same behaviour), but
dns=none is more specific.
DigitalOcean previously defaulted to peer-to-peer gossip, but dns=none
is simpler and requires fewer permissions.

Default to dns=none for hetzner and digitalocean

---

tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/many-addons-gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
upup/pkg/fi/cloudup/gcetasks/instancetemplate.go

Add a `lifecycle` block that enables `create_before_destroy` in the generated Terraform code for GCP instance templates, similar to the AWS launch template counterpart, and following [Terraform recommendations](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template#using-with-instance-group-manager).

GCP Terraform: enable create_before_destroy in instance templates

---

docs/operations/images.md
nodeup/pkg/model/miscutils.go
nodeup/pkg/model/packages.go
upup/pkg/fi/nodeup/nodetasks/package.go
util/pkg/distributions/distributions.go
util/pkg/distributions/identify.go
util/pkg/distributions/identify_test.go
util/pkg/distributions/tests/rhel9/etc/os-release

Add support for RHEL 9.
RHEL 9 does not ship python2 and libcgroup. I am able to create a RHEL9 cluster with this PR, I did not check any older distro.

Add RHEL9 support

---

pkg/acls/gce/storage.go

This message is way too verbose to be logged on default log verbosity level, floods the output a lot, set it to a higher level.

Increase verbosity level of log message about object ACLs

---

tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-scaleway-cloud-controller.addons.k8s.io-k8s-1.24_content
upup/models/cloudup/resources/addons/scaleway-cloud-controller.addons.k8s.io/k8s-1.24.yaml.template

We had to rollback the version of the CCM in #15333 while waiting for the next release. It is now available so we can use the latest version again.

scaleway: use latest version of the ccm

---

tests/e2e/scenarios/scalability/run-test.sh

For Kubernetes upstream scale testing in AWS, we are trying to run large number of nodes and CL2 tests. 
Creating this PR to get feedback on this approach for configuring test definitions defined here - https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/kops/kops-presubmits-scale.yaml#L30

Make create args for scale testing configurable in the run-test.sh

---

nodeup/pkg/model/kubelet.go

We were trying to set up a Kubernetes cluster in AWS China and kept getting Unauthorized errors when pulling images. After some digging, we found that the current hard-coded Amazon ECR endpoint in China is not correct (see the [offical docs](https://docs.aws.amazon.com/general/latest/gr/ecr.html)).
With this fix, we can now pull images from our private ECR normally in China. This should also fix #13494

Fix Amazon ECR endpoint in China

---

docs/getting_started/aws.md

Refs: https://github.com/kubernetes/kops/issues/15454
Recently AWS disabled ACLs by default (see: https://aws.amazon.com/jp/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/), so we need to update s3 commands to create public buckets. 
I update the s3api command in the document.

[doc] Update s3api command to create OIDC bucket

---

util/pkg/distributions/distributions.go

Debian Bookworm switched to using systemd-resolved by default which means that /etc/resolv.conf is a loopback stub. This causes issues with coredns, so apply the same fix as Ubuntu 16.10 and later.

Debian 12 Bookworm: Fix DNS resolution

---

nodeup/pkg/model/containerd.go

Extend #15033 to cover cases where masquerade is excluded for the entire IP family's range.

Don't set up masquerade if NonMasqueradeCIDR is /0

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

Cherry pick of #15501 on release-1.26.
#15501: Update Go to v1.20.5
```release-note
```

Automated cherry pick of #15501: Update Go to v1.20.5

---

util/pkg/distributions/distributions.go

Cherry pick of #15502 on release-1.26.
#15502: Debian 12 Bookworm: Fix DNS resolution
```release-note
```

Automated cherry pick of #15502: Debian 12 Bookworm: Fix DNS resolution

---

pkg/model/components/etcdmanager/model.go

I was testing out kops v1.27.0-beta.1 and noticed that the new `kops-utils-cp` init container image for etcd-manager hasn't been remapped via the asset builder and thus not copied to our custom container proxy when we run `kops get assets --copy`. 
This PR adds the missing code to remap the `kops-utils-cp` image.

Remap all init container images of etcd-manager

---

cloudbuild.yaml

Cherry pick of #15523 on release-1.27.
#15523: Fix promotion of `kops-utils-cp` - cloudbuild
```release-note
```

Automated cherry pick of #15523: Fix promotion of `kops-utils-cp` - cloudbuild

---

Makefile

Cherry pick of #15527 on release-1.27.
#15527: Fix promotion of `kops-utils-cp` - push
```release-note
```

Automated cherry pick of #15527: Fix promotion of `kops-utils-cp` - push

---

cmd/kops-controller/controllers/legacy_node_controller.go
pkg/model/context.go
pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion-2.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion.yaml
pkg/nodelabels/builder.go
pkg/nodelabels/builder_test.go
tests/integration/update_cluster/bastionadditional_user-data/data/aws_s3_object_nodeupconfig-bastion_content
tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
tests/integration/update_cluster/private-shared-ip/kubernetes.tf
tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
tests/integration/update_cluster/privatecalico/kubernetes.tf
tests/integration/update_cluster/privatecanal/kubernetes.tf
tests/integration/update_cluster/privatecilium-eni/kubernetes.tf
tests/integration/update_cluster/privatecilium/kubernetes.tf
tests/integration/update_cluster/privatecilium2/kubernetes.tf
tests/integration/update_cluster/privateciliumadvanced/kubernetes.tf
tests/integration/update_cluster/privatedns1/kubernetes.tf
tests/integration/update_cluster/privatedns2/kubernetes.tf
tests/integration/update_cluster/privateflannel/kubernetes.tf
tests/integration/update_cluster/privatekopeio/kubernetes.tf
tests/integration/update_cluster/privateweave/kubernetes.tf
tests/integration/update_cluster/unmanaged/kubernetes.tf
upup/pkg/fi/cloudup/populate_instancegroup_spec.go

Cherry pick of #15515 on release-1.27.
#15515: node labeling: don't ignore unknown roles
```release-note
```

Automated cherry pick of #15515: node labeling: don't ignore unknown roles

---

pkg/model/awsmodel/autoscalinggroup_test.go
pkg/model/azuremodel/vmscaleset_test.go
pkg/model/bootstrapscript.go
pkg/model/bootstrapscript_test.go
pkg/model/iam/types.go
pkg/model/openstackmodel/servergroup_test.go
upup/pkg/fi/cloudup/apply_cluster.go

We had an identically named Cluster field in the "base class" (the
unnamed embedded objects we inherit), causing shadowing and the
potential for a nil-pointer panic.

Remove duplicate Cluster field in BootstrapScriptBuilder

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #15536 on release-1.27.
#15536: bump cert-manager to v1.12.2
```release-note
```

Automated cherry pick of #15536: bump cert-manager to v1.12.2

---

cmd/kops/edit_instancegroup_test.go
cmd/kops/test/edit_instance_group.yaml
util/pkg/reflectutils/access.go

When using the **edit instancegroup with --set** option , a parsing error occurs if it is not a primitive type. The **instance group** struct has a custom type, and supporting it makes using cmd more comfortable.
e.g)
When trying to **updatespec.rollingUpdate.maxUnavailable** with edit instancegroup, a type error occurs because maxUnavailable is of type **intstr.IntOrString**.
```
./kops edit instancegroup --set 'spec.rollingUpdate.maxUnavailable=100%'
=> Unhandled type...
```
This PR supports processing the **intstr.IntOrString** type.

Support intstr.IntOrString type  in cmd

---

cmd/kops/create_cluster.go
cmd/kops/create_cluster_integration_test.go
cmd/kops/integration_test.go
docs/cli/kops_create_cluster.md
docs/operations/karpenter.md
docs/releases/1.26-NOTES.md
docs/releases/1.27-NOTES.md
pkg/apis/kops/validation/validation.go
pkg/featureflag/featureflag.go
tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/scenarios/lib/common.sh
tests/e2e/scenarios/upgrade-ab/run-test.sh
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

Upgrade Karpenter to the current last stable version `0.27.0`. Templates have been updated to use the same templates as the Helm chart.
Some noticeable changes:
- Rename `karpenter-config-logging` ConfigMap to `config-logging`
- Some environment variables configurations are now in the `karpenter-global-settings` ConfigMap
- Karpenter use now a common pod for the controller and webhook.
To set Launch Templates is deprecated into the provisioner, it is recommended to use the `AWSNodeTemplate` to set it.
Ref:
- https://karpenter.sh/v0.27.0/concepts/node-templates/
Drop the `Karpenter` feature flag.  it's fairly well-supported now.

Upgrade Karpenter to v0.27.5

---

cmd/kops/edit_instancegroup_test.go
cmd/kops/test/edit_instance_group.yaml
util/pkg/reflectutils/access.go

Cherry pick of #15458 on release-1.27.
#15458: Support intstr.IntOrString type
```release-note
```

Automated cherry pick of #15458: Support intstr.IntOrString type

---

pkg/model/awsmodel/autoscalinggroup_test.go
pkg/model/azuremodel/vmscaleset_test.go
pkg/model/bootstrapscript.go
pkg/model/bootstrapscript_test.go
pkg/model/iam/types.go
pkg/model/openstackmodel/servergroup_test.go
upup/pkg/fi/cloudup/apply_cluster.go

Cherry pick of #15526 on release-1.27.
#15526: Remove duplicate Cluster field in BootstrapScriptBuilder
```release-note
```

Automated cherry pick of #15526: Remove duplicate Cluster field in BootstrapScriptBuilder

---

tests/integration/update_cluster/containerd-custom/data/aws_launch_template_master-us-test-1a.masters.containerd.example.com_user_data
tests/integration/update_cluster/containerd-custom/data/aws_launch_template_nodes.containerd.example.com_user_data
tests/integration/update_cluster/containerd-custom/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/containerd-custom/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/containerd-custom/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/containerd-custom/in-v1alpha2.yaml
upup/pkg/fi/cloudup/apply_cluster.go

For now, this only works when `SkipInstall=true` is set at cluster level.
Closes #15558

Don't download container runtime assets when skipping the installation

---

pkg/apis/kops/install/install.go
tests/codecs/componentconfig_test.go
tests/integration/conversion/integration_test.go

Cherry pick of #14893 on release-1.27.
#14893: Don't expose v1alpha3 API

Automated cherry pick of #14893: Don't expose v1alpha3 API

---

pkg/model/components/hetznercloudcontrollermanager.go
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.example.com-addons-hcloud-cloud-controller.addons.k8s.io-k8s-1.22_content
upup/models/cloudup/resources/addons/hcloud-cloud-controller.addons.k8s.io/k8s-1.22.yaml.template
upup/models/cloudup/resources/addons/hcloud-csi-driver.addons.k8s.io/k8s-1.22.yaml.template

Cherry pick of #15577 on release-1.27.
#15577: hetzner: Update CCM to v1.16.0
```release-note
```

Automated cherry pick of #15577: hetzner: Update CCM to v1.16.0

---

upup/pkg/fi/cloudup/awstasks/ebsvolume.go

aws: Avoid spurious changes in EBSVolume for KmsKeyId

---

upup/pkg/fi/cloudup/awstasks/ebsvolume.go

Cherry pick of #15573 on release-1.26.
#15573: aws: Avoid spurious changes in EBSVolume for KmsKeyId
```release-note
```

Automated cherry pick of #15573: aws: Avoid spurious changes in EBSVolume for KmsKeyId

---

docs/networking/cilium.md

Fix some broken links on the Cilium docs page
- `stable` route no longer has some of the links, so instead used a specific version of the Cilium docs
- follows the convention in the rest of this doc to use versions
- I used the latest version that has the link available
I updated anything with `stable` but left already versioned ones. The versioned ones still work, but some could be updated to newer versions of the docs. I can do that if wanted, but not sure if y'all would prefer it be an older link closer in time to when the features were added. **EDIT**: See #15583 which updates the rest of the links that were already versioned
I had started this and some other docs changes a while ago, finally got to them while making other docs PRs 😅

docs(cilium): fix several broken links

---

docs/cluster_spec.md

Per https://github.com/kubernetes/kops/issues/6318#issuecomment-830490064 and related comments, the `kube-dns-autoscaler` is no longer needed when upgrading to CoreDNS.
- there is a separate `coredns-autoscaler` that is spun up in more recent kOps versions
- so the `kube-dns-autoscaler` is no longer needed after an upgrade to CoreDNS - and possibly could conflict if they both targeted the same deployment
- updating the `kube-dns-autoscaler` was the most confusing part, so this simplifies things a good bit!
- also fix some minor inconsistent spacing in this doc
Was teaching folks about k8s DNS so came back to the issue to see what the progress was w/ CoreDNS as I had to do this upgrade a couple years ago

docs: remove `kube-dns-autoscaler` when upgrading to CoreDNS

---

docs/networking/cilium.md

In tandem with #15325, update all links on the Cilium page to the latest v1.13 version of the Cilium docs
- links still worked before, but some were as old as Cilium v1.6, so update to newest proactively
- also makes it consistent / easier for readers when all of the links go to the same version of the docs

docs(cilium): update links to latest v1.13

---

tests/integration/update_cluster/containerd-custom/data/aws_launch_template_master-us-test-1a.masters.containerd.example.com_user_data
tests/integration/update_cluster/containerd-custom/data/aws_launch_template_nodes.containerd.example.com_user_data
tests/integration/update_cluster/containerd-custom/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/containerd-custom/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/containerd-custom/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/containerd-custom/in-v1alpha2.yaml
upup/pkg/fi/cloudup/apply_cluster.go

Cherry pick of #15579 on release-1.27.
#15579: Don't download containerd assets when skipping the
```release-note
```

Automated cherry pick of #15579: Don't download containerd assets when skipping the

---

channels/pkg/channels/addon.go
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template

Update Karpenter to v0.28.1

---

channels/pkg/channels/addon.go
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template

Cherry pick of #15585 on release-1.27.
#15585: Update Karpenter to v0.28.1
```release-note
```

Automated cherry pick of #15585: Update Karpenter to v0.28.1

---

cmd/kops/util/factory.go

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kops-e2e-aws-upgrade-k126-ko126-to-k127-kolatest-karpenter/1676436267178397696
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/15585/pull-kops-e2e-aws-upgrade-k126-ko126-to-k127-kolatest-karpenter/1676436267178397696/build-log.txt
```
I0705 04:02:52.253250   37011 addon.go:192] Applying update from "s3://k8s-kops-prow/e2e-aad0fd40c9-67b85.test-cncf-aws.k8s.io/addons/karpenter.sh/k8s-1.19.yaml"
I0705 04:02:52.253274   37011 s3fs.go:320] Reading file "s3://k8s-kops-prow/e2e-aad0fd40c9-67b85.test-cncf-aws.k8s.io/addons/karpenter.sh/k8s-1.19.yaml"
I0705 04:02:52.892013   37011 health.go:61] status conditions not found for Secret:kube-system/karpenter-cert
I0705 04:02:53.024635   37011 request.go:628] …
```

Increase client-side throttling limits

---

nodeup/pkg/model/containerd.go
nodeup/pkg/model/tests/containerdbuilder/flatcar/tasks.yaml
nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml

If using IPv6 and a kubenet-style CNI (which is more common with
IPv6), we need to support an IPv6 route on the pod, or else Pods will
be unable to reach other Pods.

ipv6: containerd routes support for IPv6

---

pkg/apis/kops/validation/validation.go

Cherry pick of #14921 on release-1.27.
#14921: Validate additionalNetworkCIDRs only set on AWS
```release-note
```

Automated cherry pick of #14921: Validate additionalNetworkCIDRs only set on AWS

---

tests/e2e/templates/apiserver.yaml.tmpl

Because anyone needing dedicated apiserver nodes is unlikely to be using public topology.

Use private topology for apiserver e2e test

---

pkg/model/gcemodel/autoscalinggroup.go
pkg/model/gcemodel/external_access.go
pkg/model/gcemodel/firewall.go
tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/new_cluster.go

Closes https://github.com/kubernetes/kops/issues/15590
More fixes coming as part of https://github.com/kubernetes/kops/pull/15332
/cc @justinsb 

gce: Add support for bastions

---

pkg/model/gcemodel/api_loadbalancer.go
pkg/model/gcemodel/firewall.go
tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
upup/pkg/fi/cloudup/gce/gce_cloud.go
upup/pkg/fi/cloudup/gcetasks/address.go
upup/pkg/fi/cloudup/gcetasks/backend_service.go
upup/pkg/fi/cloudup/gcetasks/healthcheck.go

gce: Update logic for internal LB

---

pkg/model/gcemodel/api_loadbalancer.go
tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf

It seems we can use the exact same rules.

gce: Set firewall rules for Internal LBs also

---

upup/pkg/fi/cloudup/scaleway/utils.go
upup/pkg/fi/cloudup/scaleway/utils_test.go
upup/pkg/fi/cloudup/scalewaytasks/loadbalancer.go

This PR switches the reading order of the two credentials sources to be consistent with the other Scaleway DevTools (see [here](https://github.com/scaleway/scaleway-sdk-go/blob/master/scw/README.md)). 
From now on, the profile will be loaded first if it exists, and then the environment variables will be read, overriding the values in the profile.
This change is already documented in #15604

scaleway: switched credentials reading order

---

upup/pkg/fi/cloudup/scaleway/utils.go
upup/pkg/fi/cloudup/scaleway/utils_test.go
upup/pkg/fi/cloudup/scalewaytasks/loadbalancer.go

Cherry pick of #15618 on release-1.27.
#15618: switched credentials reading order
```release-note
```

Automated cherry pick of #15618: switched credentials reading order

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

https://go.dev/doc/devel/release#go1.20.6

Update Go to v1.20.6

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

Cherry pick of #15621 on release-1.27.
#15621: Update Go to v1.20.6
```release-note
```

Automated cherry pick of #15621: Update Go to v1.20.6

---

pkg/nodeidentity/scaleway/identify.go
protokube/pkg/protokube/scaleway_volumes.go
upup/pkg/fi/cloudup/scaleway/cloud.go
upup/pkg/fi/cloudup/scaleway/utils.go
upup/pkg/fi/cloudup/scaleway/verifier.go

This PR adds 3 new utils functions to get:
- the cluster's name
- the instance's role
- the instance's instance group name
from the given tags.
This avoids a few `for _, tag := range tags` type loops.

scaleway: refactoring: utils functions to get info from tags

---

tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #15605 on release-1.27.
#15605: Fix Karpenter failure to start on IPv6 clusters

Automated cherry pick of #15605: Fix Karpenter failure to start on IPv6 clusters

---

docs/networking.md
docs/networking/canal.md
docs/networking/flannel.md
docs/networking/kube-router.md
docs/releases/1.27-NOTES.md
docs/releases/1.28-NOTES.md
pkg/apis/kops/validation/validation.go
pkg/apis/kops/validation/validation_test.go

Per Office Hours discussion.
These three CNIs have been without a maintainer or updates for some time. A call for maintainers in the kOps 1.26 release notes has not resulted in any volunteers submitting updates.
This removes support for these CNIs as of Kubernetes 1.28.

Deprecate Canal, Flannel, and Kube-router

---

pkg/model/openstackmodel/firewall.go

Cherry pick of #15635 on release-1.27.
#15635: open hubble port 4244
```release-note
```

Automated cherry pick of #15635: openstack: Open hubble port 4244

---

k8s/crds/kops.k8s.io_clusters.yaml
k8s/crds/kops.k8s.io_instancegroups.yaml
nodeup/pkg/model/kubelet.go
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/validation/validation.go

Reduced version of #15352 (thanks the inspiration @tomesm)
Closes #14950

Add support for using swap memory

---

k8s/crds/kops.k8s.io_clusters.yaml
k8s/crds/kops.k8s.io_instancegroups.yaml
nodeup/pkg/model/kubelet.go
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/validation/validation.go

Cherry pick of #15632 on release-1.27.
#15632: Add support for using swap memory
```release-note
```

Automated cherry pick of #15632: Add support for using swap memory

---

cmd/kops/create.go
cmd/kops/delete.go
cmd/kops/replace.go
cmd/kops/util/factory.go
cmd/kops/version.go
examples/kops-api-example/apply.go
examples/kops-api-example/up.go
nodeup/pkg/model/kubelet_test.go
pkg/client/simple/api/clientset.go
pkg/client/simple/clientset.go
pkg/client/simple/vfsclientset/clientset.go
pkg/client/simple/vfsclientset/clientset_test.go
pkg/instancegroups/rollingupdate_os_test.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
upup/pkg/fi/cloudup/new_cluster.go
upup/pkg/fi/cloudup/populate_cluster_spec.go
upup/pkg/fi/cloudup/populate_cluster_spec_test.go
util/pkg/vfs/context.go

`VFSContext` is not a context, it is a clientset. This starts to refactor some references to `VFSContext` so that the pull it from a higher-level clientset.
There will be more work to push either a `VFSContext` or a higher-level clientset into the things that currently reference the global variable. The next thing to hold a reference to `VFSContext` is probably `ModelBuilderContext`.
/cc @justinsb

Add VFSContext to various clientsets

---

pkg/client/simple/vfsclientset/clientset.go
upup/models/vfs.go
util/pkg/vfs/azureblob.go
util/pkg/vfs/fs.go
util/pkg/vfs/gsfs.go
util/pkg/vfs/k8sfs.go
util/pkg/vfs/memfs.go
util/pkg/vfs/s3fs.go
util/pkg/vfs/sshfs.go
util/pkg/vfs/swiftfs.go
util/pkg/vfs/vfs.go

Adds `RemoveAll` to vfs interface.
The goal of this method is to avoid deleting files one by one if the implementation allows it.
When deleting a cluster that ran for a while, it can take a very long time to delete all backups.
I personally use s3 as state-store, I tried to implement it for other providers when I could find useful methods in their APIs. For other providers I resolved to use a loop, it does not change from the current implementation and it could be improved later on.
For the swift implementation, I used the default 10k bulk items but I'm not sure about this one as this seems to be configurable per swift instance. 
I also found partially the same code with `RemoveAllVersion` although this only target object versions/snapshots. But this one does not seems to be used …

add removeAll to vfs

---

cmd/kops-controller/controllers/legacy_node_controller.go
pkg/nodelabels/builder.go
upup/pkg/fi/utils/yaml.go

If we deserialize the yaml, we don't go through the version-conversion
logic.  That logic maps from Master -> ControlPlane, so without that
logic we see unexpected values in the "string enums".

kops-controller: load objects with version conversion

---

cmd/kops-controller/controllers/legacy_node_controller.go
pkg/nodelabels/builder.go
upup/pkg/fi/utils/yaml.go

Cherry pick of #15608 on release-1.27.
#15608: kops-controller: load objects with version conversion

Automated cherry pick of #15608: kops-controller: load objects with version conversion

---

docs/getting_started/spot-ocean.md

This PR update spot-ocean doc about setting support for VNG size limits in launch spec.
this PR is equivalent to an old PR #15355

spot: update docs about setting the VNG Size Limits in Launch Spec

---

cmd/kops-controller/controllers/legacy_node_controller.go
cmd/kops-controller/controllers/node_controller.go

Cherry pick of #15650 on release-1.27.
#15650: Support removal of managed node labels

Automated cherry pick of #15650: Support removal of managed node labels

---

cmd/kops-controller/controllers/legacy_node_controller.go
cmd/kops-controller/controllers/node_controller.go

kops-controller manages a few node-role node-labels.  We
now remove any extra managed labels that land on the node.
This means we will now actively remove the extra node label if we
previously erroneously applied to a control-plane node; previous code
changes stopped applying it.

Support removal of managed node labels

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/cluster.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/cluster.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/model/components/karpenter.go
tests/integration/update_cluster/karpenter/data/aws_s3_object_cluster-completed.spec_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template
upup/pkg/fi/cloudup/populate_cluster_spec.go

After discussion on https://github.com/kubernetes/kops/pull/15585#pullrequestreview-1512237273, add variables to give the possibility to set the log format for Karpenter and set the version.

feat(karpenter): Variabilize image, logFormat and logLevel

---

tests/integration/update_cluster/minimal-etcd/data/aws_launch_template_master-us-test-1a.masters.minimal-etcd.example.com_user_data
tests/integration/update_cluster/minimal-etcd/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-etcd/data/aws_s3_object_manifests-etcdmanager-events-master-us-test-1a_content
upup/pkg/fi/cloudup/defaults.go

Cherry pick of #15655 on release-1.27.
#15655: Fix modifying backupRetentionDays
```release-note
```

Automated cherry pick of #15655: Fix modifying backupRetentionDays

---

pkg/resources/azure/azure.go
pkg/resources/azure/azure_test.go
upup/pkg/fi/cloudup/azure/azure_utils.go
upup/pkg/fi/cloudup/azuretasks/vmscaleset.go
upup/pkg/fi/cloudup/azuretasks/vmscaleset_test.go
vendor/k8s.io/utils/set/OWNERS
vendor/k8s.io/utils/set/ordered.go
vendor/k8s.io/utils/set/set.go
vendor/modules.txt

azure: Add mode dependency logic to deletion

---

docs/releases/1.27-NOTES.md

Update release nodes for kOps 1.27

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/cluster.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/cluster.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/model/components/karpenter.go
tests/integration/update_cluster/karpenter/data/aws_s3_object_cluster-completed.spec_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template
upup/pkg/fi/cloudup/populate_cluster_spec.go

Cherry pick of #15601 on release-1.27.
#15601: feat(karpenter): Variabilize Image, logFormat and logLevel
```release-note
```

Automated cherry pick of #15601: feat(karpenter): Variabilize Image, logFormat and logLevel

---

docs/bastion.md

- Updated the username variable to avoid encountering the "Permission denied (publickey)" error in different AMIs
- Removed redundant description.

docs: revise the bastion ssh guideline to mitigate permission denied errors

---

pkg/commands/helpers/kubectl_auth.go
pkg/commands/helpers/kubectl_auth_test.go

The `kops helpers kubectl-auth` command tries to create a cache file that is long in proportion to the length of the `cluster` and `state` parameters, and outputs the following message. This PR corrects this behavior so that it always generates cache file names of the same length.
> I0623 12:21:51.479433    8889 kubectl_auth.go:114] cached credential "/home/vscode/.kube/cache/kops-authentication/my_kops_cluster_test_my_domain_net_73333a2f2f6d792d6b6f70732d73746174652d6d792d6177732d6163636f756e742d69642d61702d6e6f727468656173742d31006d792d6b6f70732d636c75737465722e746573742e6d792d646f6d61696e2e6e657400e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" was not valid: open /home/vscode/.kube/cache/kops-authentication/my_kops_cluster_test_my_domain_net_73333a2f2f6d792d6b6f70732d …

Fix long auth helper cache file name

---

hack/__init__.py
hack/boilerplate/boilerplate.py
hack/boilerplate/boilerplate.py.txt
hack/mkdocs_macros/__init__.py
hack/mkdocs_macros/feature_stability_table.py
hack/verify-boilerplate.sh

If python isn't found, without this fix the script exits with code 0,
despite not checking boilerplate.

verify-boilerplate: stricter error checking

---

pkg/commands/helpers/kubectl_auth_test.go

Just so we can verify that the value looks as we expect it to.  The
actual value doesn't much matter, but it's still helpful for us to be
able to see changes to the value in the PR workflow.

Add golden-output test for cacheFilePath

---

cmd/kops/create_cluster.go
cmd/kops/edit_cluster.go
cmd/kops/edit_instancegroup.go
nodeup/pkg/model/kubelet_test.go
pkg/apis/kops/v1alpha2/defaults.go
pkg/apis/kops/v1alpha3/defaults.go
pkg/apis/kops/validation/aws.go
pkg/apis/kops/validation/aws_test.go
pkg/apis/kops/validation/validation.go
pkg/commands/helpers_readwrite.go
pkg/instancegroups/rollingupdate_os_test.go
pkg/model/components/kubescheduler/tests/kubeschedulerconfig/completed-cluster.yaml
pkg/model/components/kubescheduler/tests/minimal/completed-cluster.yaml
pkg/model/components/kubescheduler/tests/mixing/completed-cluster.yaml
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/populate_cluster_spec.go
upup/pkg/fi/cloudup/populate_cluster_spec_test.go

I believe this is the last substantive reference to the control-plane and node topology field in the cluster spec.

Determine default API access method by IG subnet type

---

pkg/apis/kops/validation/legacy.go
pkg/apis/kops/validation/validation.go
pkg/apis/kops/validation/validation_test.go
pkg/util/subnet/subnet.go

Fixes #15034 
Removes the requirement (on non-GCE) that the ServiceClusterIPRange be within NonMasqueradeCIDR, as kube-proxy reroutes the ServiceClusterIPRange before masquerading.
Prohibits overlap between the PodCIDR and the ServiceClusterIPRange
Prohibits overlap between either the PodCIDR and the ServiceClusterIPRange and any subnet CIDR or IPv6CIDR. (except IPv6 doesn't have a PodCIDR, so can't overlap).
Adds validation of any podCIDR and requires it be within any NonMasqueradeCIDR.

Improve validation of PodCIDR and ServiceClusterIPRange

---

tests/e2e/pkg/tester/skip_regex.go

This skip was removed in https://github.com/kubernetes/kops/pull/15449 but is failing because we're still on cilium 1.12:
https://testgrid.k8s.io/kops-grid#kops-grid-cilium-eni-u2004-k25-ko26
Add it back under the comment for skips to be removed after we upgrade to 1.13.
This will need cherrypicking to release-1.27

Continue skipping SCTP tests for cilium until we upgrade to 1.13

---

tests/e2e/scenarios/addon-resource-tracking/run-test.sh
tests/e2e/scenarios/cilium-connectivity-test/run-test.sh
tests/e2e/scenarios/digital-ocean/run-test

Some of these were failing because the versions used were too old:
https://testgrid.k8s.io/kops-misc#kops-aws-addon-resource-tracking
```
Error: kubernetes upgrade is required 
```
This bumps the scenario scripts to use newer versions.

Bump k8s and kops versions used in scenario scripts

---

mkdocs.yml

as mentioned in the release process:
https://github.com/kubernetes/kops/blob/691978734b56fd83984ba0a4c6ce411c5d654d31/docs/contributing/release-process.md#add-link-to-release-notes

Add 1.27 release notes to docs menu

---

pkg/nodeidentity/azure/identify.go

azure: Populate node labels from tags

---

tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/kubetest2-kops/deployer/deployer.go
tests/e2e/kubetest2-kops/deployer/up.go
tests/e2e/scenarios/lib/common.sh
tests/e2e/scenarios/upgrade-ab/run-test.sh

- kubetest2-kops: rename control-plane-size flag to control-plane-count
- test scenarios: recognize KOPS_CONTROL_PLANE_COUNT

kubetest2-kops: rename control-plane-size flag to control-plane-count

---

pkg/assets/builder.go

Cherry pick of #15689 on release-1.27.
#15689: Print error message when digest image fails
```release-note
```

Automated cherry pick of #15689: Print error message when digest image fails

---

cmd/kops/validate_cluster.go

update logs with "cannot render instance groups" instead of "cannot render nodes"

update logs with "cannot render instance groups" instead of "cannot render nodes" in validate_cluster.go

---

tests/integration/update_cluster/minimal/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal/in-v1alpha2.yaml

Cherry pick of #15699 on release-1.27.
#15699: Use release version of k8s 1.27 in integration test

Automated cherry pick of #15699: Use release version of k8s 1.27 in integration test

---

pkg/model/components/clusterautoscaler.go
tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cas-priority-expander-custom.example.com-addons-bootstrap_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cas-priority-expander-custom.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cas-priority-expander.example.com-addons-bootstrap_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cas-priority-expander.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content

Cherry pick of #15703 on release-1.27.
#15703: Upgrade cluster-autoscaler

Automated cherry pick of #15703: Upgrade cluster-autoscaler

---

upup/pkg/fi/cloudup/gcetasks/firewallrule.go

The error message was ambiguous.

gce: fix message around getting firewall rule

---

upup/pkg/fi/cloudup/awstasks/warmpool.go
upup/pkg/fi/context.go

troubleshooting this job failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-warm-pool/1685061166742638592
```
I0728 23:06:25.787156    5835 executor.go:111] Tasks: 118 done / 122 total; 1 can run
I0728 23:06:26.978907    5835 executor.go:155] No progress made, sleeping before retrying 1 task(s)
I0728 23:06:36.979171    5835 executor.go:111] Tasks: 118 done / 122 total; 1 can run
I0728 23:06:38.155155    5835 executor.go:155] No progress made, sleeping before retrying 1 task(s)
Error: error running tasks: deadline exceeded executing task WarmPool/nodes-eu-central-1c.e2e-e2e-kops-warm-pool.test-cncf-aws.k8s.io. Example error: waiting for ASG to become ready
```

Log error when PutWarmPool fails

---

cloudmock/gce/mockcompute/forwarding_rule.go
pkg/model/components/etcdmanager/model.go
pkg/model/gcemodel/api_loadbalancer.go
pkg/model/gcemodel/autoscalinggroup.go
pkg/model/master_volumes.go
pkg/resources/gce/gce.go
tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
upup/pkg/fi/cloudup/gce/compute.go
upup/pkg/fi/cloudup/gce/gce_cloud.go
upup/pkg/fi/cloudup/gce/labels.go
upup/pkg/fi/cloudup/gce/utils.go
upup/pkg/fi/cloudup/gcetasks/forwardingrule.go
upup/pkg/fi/cloudup/utils.go

We add the cluster-name label, now that labels are supported on
ForwardingRules.

gce: Set labels on ForwardingRules

---

pkg/model/gcemodel/api_loadbalancer.go
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf

This avoids a spurious change being printed, and is more correct - we
actually want this to be external (vs nil, which implicitly means
"don't care").

gce load balancers: set LoadBalancingScheme to EXTERNAL explicitly

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

Because upgrade-ab needs to run with older versions, we must use the
older flags.
Issue #15698

upgrade-ab test should use old (deprecated) flags

---

tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/kubetest2-kops/deployer/deployer.go
tests/e2e/kubetest2-kops/deployer/up.go
tests/e2e/scenarios/lib/common.sh
tests/e2e/scenarios/upgrade-ab/run-test.sh

Cherry pick of #15674 on release-1.26.
#15674: kubetest2-kops: rename control-plane-size flag to
```release-note
```

Automated cherry pick of #15674: kubetest2-kops: rename control-plane-size flag to

---

pkg/resources/aws/aws.go
pkg/resources/aws/eventbridge.go

`eventbridge` itself is too generic given there are many resource types within the eventbridge service

Rename eventbridge rule in toolbox dump output

---

tests/e2e/kubetest2-kops/deployer/deployer.go

Using `SetNormalizeFunc()` is not working for some reason. Using `MarkDeprecated()` seems a better option.
See failing tests: https://testgrid.k8s.io/kops-upgrades#Summary
/cc @justinsb @rifelpet @dims 
Closes #15698

kubetest2: Mark `--control-plane-size` as deprecated

---

tests/e2e/kubetest2-kops/deployer/deployer.go

Cherry pick of #15725 on release-1.26.
#15725: kubetest2: Mark `--control-plane-size` as deprecated
```release-note
```

Automated cherry pick of #15725: kubetest2: Mark `--control-plane-size` as deprecated

---

tests/e2e/scenarios/digital-ocean/run-test
tests/e2e/scenarios/scalability/run-test.sh
tests/e2e/scenarios/upgrade-ha-leader-migration/run-test.sh

kubetest2-kops searches for create-args values of --control-plane-count. While kops recognizes both --control-plane-count and --master-count, kubetest2-kops will add --control-plane-count if it isn't already set in --create-args. This means any references to --master-count need to be updated to --control-plane-count.
This should fix at least this job: https://testgrid.k8s.io/kops-gce#kops-leader-migration
`I0801 22:50:40.366862    5814 local.go:42] ⚙️ /home/prow/go/src/k8s.io/kops/_rundir/121db271-a4e7-46bc-842f-abf92494756d/kops create cluster --name ha-migration.k8s.local --cloud gce --kubernetes-version v1.23.17 --ssh-public-key /tmp/kops-ssh2613636737/key.pub --set cluster.spec.nodePortAccess=0.0.0.0/0 --channel=alpha --node-count=1 --master-count=3 …

Update references to control-plane-count

---

docs/getting_started/openstack.md
pkg/model/openstackmodel/servergroup.go
pkg/model/openstackmodel/servergroup_test.go
pkg/model/openstackmodel/tests/servergroup/adds-additional-security-groups.yaml
pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-ClusterSpec.yaml
pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-InstanceGroupSpec.yaml
pkg/model/openstackmodel/tests/servergroup/configures-allowed-address-pairs-with-annotations.yaml
pkg/model/openstackmodel/tests/servergroup/configures-server-group-affinity-with-annotations.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-auto-zone-distribution.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer-dns-none.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-external-router.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion-2.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node-without-bastion-no-public-ip-association.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node.yaml
pkg/model/openstackmodel/tests/servergroup/single-zone-setup-3-masters-1-node-without-bastion-with-API-loadbalancer-dns-none.yaml
pkg/model/openstackmodel/tests/servergroup/truncate-cluster-names-to-42-characters.yaml
pkg/model/openstackmodel/tests/servergroup/uses-instance-group-subnet-as-availability-zones-fallback.yaml
pkg/model/openstackmodel/tests/servergroup/uses-instance-group-zones-as-availability-zones.yaml
upup/pkg/fi/cloudup/openstack/instance.go
upup/pkg/fi/cloudup/openstacktasks/instance.go
upup/pkg/fi/cloudup/openstacktasks/poolassociation.go
upup/pkg/fi/cloudup/openstacktasks/servergroup.go

fixes #15734
makes it possible to override server group name used in instance group.
Example:
```yaml
kind: InstanceGroup
metadata:
annotations:
openstack.kops.io/serverGroupName: control-plane
```

OpenStack: add server group name override annotation

---

tests/e2e/kubetest2-kops/aws/zones.go

Refs #15732 
/cc @johngmyers @justinsb @rifelpet

aws: Don't use `ap-northeast-2d` and `us-east-1e` for testing

---

tests/e2e/scenarios/aws-lb-controller/run-test.sh
tests/e2e/scenarios/podidentitywebhook/cluster.yaml.tmpl

Ref: https://github.com/kubernetes/kops/pull/15745#issuecomment-1666752940
Also updating the podidentitywebhook E2E scenario to use the latest 20.04 AMI from SSM rather than a hard-coded AMI that doesn't get updated automatically.

Use Ubuntu 20.04 in load-balancer-controller E2E scenario

---

tests/e2e/kubetest2-kops/deployer/up.go

Previously we were only not setting --master-count if --master-count was in --create-args. Now we recognize either flag. This fixes E2E jobs that specify --control-plane-count and kops create cluster ends up having both flags
followup to https://github.com/kubernetes/kops/pull/15742
Fixes https://testgrid.k8s.io/kops-upgrades#kops-leader-migration

E2E - Dont set --master-count if --control-plane-count is provided

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/networking.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/validation/validation_test.go
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/in-v1alpha2.yaml
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.13.yaml.template

Fixes #15633
Question regarding testing: How can I test a case where the clusterID is set to `253` ? I tried adding it [here](https://github.com/kubernetes/kops/blob/master/tests/integration/update_cluster/minimal-ipv6-cilium/in-v1alpha2.yaml#L37) but it did not work.

feature: Add cluster-id for Cilium

---

tests/e2e/scenarios/aws-lb-controller/run-test.sh

Fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-aws-load-balancer-controller/1688303425676120064
`Error: control-plane-eu-west-1a.spec.machineType: Invalid value: "t4g.medium": machine type architecture "arm64" does not match image architecture "x86_64"`

Use arm64 AMI for LBC scenario

---

tests/e2e/scenarios/podidentitywebhook/cluster.yaml.tmpl

followup to https://github.com/kubernetes/kops/pull/15747/files#diff-9200dd891c42dc71f164e8f0b4d8bb9785fc003b7482b9d95124ddc9d82cc268
fixes https://testgrid.k8s.io/kops-misc#kops-aws-pod-identity-webhook

Fix AMI SSM parameter for podidentitywebhook scenarioo

---

pkg/model/hetznermodel/firewall.go

Hello there kOps Mantainers :)
While we were using kOps for managing our Hetzner Cloud Production Clusters, we found that the cluster spec attribute `spec.nodePortAccess` (of `kind: Cluster`) was misbehaving with following error:
```
W0810 11:17:19.121986      56 executor.go:139] error running task "Firewall/nodes.<my-cluster-name>.k8s.local" (56s remaining to succeed): rules contain duplicates (invalid_input)
``` 
Going deeper by analyzing the commits, it seems that a typo error was creating twice same firewall rules that triggered an hcloud package error (constraint: two rules can't be identical).
Since the fact that file was and remained untouched for several months (and the support for Hetzner clusters is still in beta), it seems to me a typo to double create **TCP** rules for …

Fixing a typo in Hetzner Firewall Model management

---

pkg/model/hetznermodel/firewall.go

Cherry pick of #15762 on release-1.26.
#15762: fix: fixed an edge case with setting NodePort access in
```release-note
```

Automated cherry pick of #15762: fix: fixed an edge case with setting NodePort access in

---

util/pkg/reflectutils/access.go
util/pkg/reflectutils/access_test.go

Usage:
```
kops edit cluster --set cluster.spec.networking.amazonvpc.env=ENABLE_PREFIX_DELEGATION=true
```
Closes #15759

Allow setting env vars from the command line

---

util/pkg/reflectutils/access.go
util/pkg/reflectutils/access_test.go

Cherry pick of #15767 on release-1.27.
#15767: Allow setting env vars from the command line
```release-note
```

Automated cherry pick of #15767: Allow setting env vars from the command line

---

tests/e2e/pkg/kops/state.go
tests/e2e/pkg/tester/skip_regex.go
tests/e2e/pkg/tester/tester.go

Trim e2e skip regexes for Cilium

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/15599/presubmit-kops-aws-scale-amazonvpc-using-cl2/1690212199458410496/build-log.txt
```
Error: control-plane-ap-northeast-2a-1.spec.image: Invalid value: "ssm:/aws/service/canonical/ubuntu/server/20.04/stable/current/arm64/hvm/ebs-gp2/ami-id":
specified image "ssm:/aws/service/canonical/ubuntu/server/20.04/stable/current/arm64/hvm/ebs-gp2/ami-id" is invalid:
failed to get value for SSM Parameter "/aws/service/canonical/ubuntu/server/20.04/stable/current/arm64/hvm/ebs-gp2/ami-id"
```
/cc @johngmyers @rifelpet @dims
@prateekgogia

Pass error when failing to get SSM parameter

---

pkg/model/openstackmodel/firewall.go

openstack: Add missing security groups for cilium etcd

---

tests/e2e/scenarios/aws-lb-controller/run-test.sh

Previously we were running tests from the head of the LBC repo. Now we clone the same version as what is deployed to ensure e2e tests match.
Also using a static AMI ID until kops permissions are fixed in the e2e accounts: https://github.com/kubernetes/kops/pull/15599#issuecomment-1675808982

Use the same LBC version for e2e tests as what is deployed

---

pkg/resources/aws/aws.go

There's no point to try and delete volumes that are already set to delete on instance termination.
During scale tests, with 100+ instances, the following can be seen a lot during cluster deletion:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/15778/presubmit-kops-aws-scale-amazonvpc-using-cl2/1691068965809295360/build-log.txt
```
W0814 13:38:55.239051    7068 retry_handler.go:55] Inserting delay before AWS request
(ec2::DeleteVolume) to avoid RequestLimitExceeded: 9s
```

aws: Ignore volumes set to delete on instance termination

---

tests/e2e/pkg/tester/skip_regex.go
tests/e2e/scenarios/scalability/run-test.sh

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/15778/presubmit-kops-aws-scale-amazonvpc-using-cl2/1691438764041179136
/cc @rifelpet @dims @justinsb

Use us-east-2 region for scale tests

---

tests/e2e/pkg/tester/skip_regex.go

See failures in https://testgrid.k8s.io/kops-network-plugins.

Skip failing ProxyTerminatingEndpoints test

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/networking.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.13.yaml.template

Fixes #15786.
There is a bit more context in the issue, but this adds a `Registry` field to the `CiliumNetworkingSpec` so that users can override the image registry used to pull Cilium images.
This copies the method used for similar Networking add ons when specifying a `Registry` argument in their NetworkingSpec; defaulting to `quay.io` when the `Registry` field is empty.

Add a new field for using a custom registry for Cilium

---

util/pkg/reflectutils/access.go
util/pkg/reflectutils/access_test.go

```shell
$ kops create cluster --set spec.kubeControllerManager.endpointSliceUpdatesBatchPeriod=500ms
Error: cannot set field "spec.kubeControllerManager.endpointSliceUpdatesBatchPeriod": unhandled type "v1.Duration"
```
/cc @dims @rifelpet @justinsb 
@prateekgogia

Allow setting metav1.Duration from the command line

---

pkg/resources/gce/gce.go

Observed this when a machine was first starting up.

gce: don't logspam when next-route-hop is starting

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/networking.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.12.yaml.template

Cherry pick of #15787 on release-1.27.
#15787: Add a new field for using a custom registry for Cilium
```release-note
```

Automated cherry pick of #15787: Add a new field for using a custom registry for Cilium

---

tests/e2e/pkg/tester/skip_regex.go

After no longer skipping these in kops 1.28, the e2e tests began failing again (examples [1](https://testgrid.k8s.io/kops-grid#kops-grid-cilium-amzn2-k23) and [2](https://testgrid.k8s.io/kops-grid#kops-grid-cilium-deb10-k25))
It turns out cilium doesn't enable SCTP support by default, it is guarded by a `enable-sctp` [config boolean](https://github.com/cilium/cilium/pull/20033/files#diff-83e9b8b2ccacddb2fbdb28fbcfa148473d05056c0b4c955fc971709b469d7331).
In k8s 1.27 the test [was also renamed](https://github.com/kubernetes/kubernetes/pull/113335/files#diff-e9b5b9ac3748355ab1c53360290889c0a4e1d6f4bba01395e425088882619d13) and added `[Serial]`, so it is still being skipped on k8s 1.27+ test jobs
/cc @hakman

Continue skipping SCTP HostPort tests in older k8s versions

---

pkg/apis/kops/validation/validation.go
pkg/util/subnet/subnet.go
tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/different-amis/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_openstack/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_openstack_nodns/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_openstack_octavia/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.23/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.24/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.25/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-arm64/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26-irsa/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.26/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.27/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/subnets.go
upup/pkg/fi/cloudup/subnets_test.go

When creating a cluster, the network CIRD is split into 8 subnets.
For AWS, the network CIDR is at max a /16, which results in /19 subnets (8192 IPs). This is quite small for AWS VPC CNI.
When doing scalability tests, even 500 nodes are too many for such small subnets, considering 16 IPs / node.
Even using multi-AZ, we still get a max of 48 IPs / node, again, not so great.
This PR proposes to split the network CIDR into bigger subnets, when the number of subnets allows it.
This only affects AWS and OpenStack:
https://github.com/kubernetes/kops/blob/73159cd6f50f72e004d972ce2ade21dcf40b7860/upup/pkg/fi/cloudup/defaults.go#L122-L128
/cc @johngmyers @justinsb @zetaab

Create clusters with bigger default subnets

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

**What this PR does / why we need it**: Bump AWS CNI to latest patch version (1.13.4)
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.13.4

Bump AWS CNI to 1.13.4

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #15810 on release-1.27.
#15810: bump cert manager to 1.12.3
```release-note
```

Automated cherry pick of #15810: bump cert manager to 1.12.3

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

**What this PR does / why we need it**: Bump AWS CNI to latest patch version (1.12.3): https://github.com/cert-manager/cert-manager/releases/tag/v1.12.3

Bump Cert Manager to 1.12.3

---

pkg/apis/kops/model/features.go
upup/pkg/fi/cloudup/apply_cluster.go

We don't have a seeding mechanism for DigitalOcean (this relies on
cloud credentials, which we don't want to put on the nodes).
Instead, use the (stable) load balancer IP to connect.

Fix gossip on DigitalOcean

---

channels/alpha

following k8s releases yesterday with high CVE fixes, bumping alpha channel.
I'll submit a separate PR to promote to stable soon as well.
- https://github.com/kubernetes/kubernetes/releases/tag/v1.24.17
- https://github.com/kubernetes/kubernetes/releases/tag/v1.25.13
- https://github.com/kubernetes/kubernetes/releases/tag/v1.26.8
- https://github.com/kubernetes/kubernetes/releases/tag/v1.27.5

update alpha channel with k8s emergency release and ubuntu ami versions

---

tests/e2e/pkg/tester/skip_regex.go

fixes these e2e jobs:
https://testgrid.k8s.io/kops-distro-amzn2#kops-grid-cilium-amzn2-k26
https://testgrid.k8s.io/kops-distro-amzn2#kops-grid-calico-amzn2-k26
https://testgrid.k8s.io/kops-distro-u2204#kops-grid-cilium-eni-u2204-k26
etc.

Skip UDP LoadBalancer test on k8s 1.26

---

k8s/crds/kops.k8s.io_clusters.yaml
k8s/crds/kops.k8s.io_instancegroups.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

Cherry pick of #15824 on release-1.27.
#15824: Add support for --experimental-allocatable-ignore-eviction
```release-note
```

Automated cherry pick of #15824: Add support for --experimental-allocatable-ignore-eviction

---

cmd/kops/create_cluster.go
cmd/kops/create_cluster_integration_test.go
docs/cli/kops_create_cluster.md
tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
tests/integration/create_cluster/complex-private/options.yaml
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/complex/options.yaml
tests/integration/create_cluster/ha_hetzner/options.yaml
tests/integration/create_cluster/ha_openstack/options.yaml
tests/integration/create_cluster/ha_openstack_nodns/options.yaml
tests/integration/create_cluster/ha_openstack_octavia/options.yaml
tests/integration/create_cluster/minimal_hetzner/options.yaml
upup/pkg/fi/cloudup/new_cluster.go
upup/pkg/fi/cloudup/subnets.go

This will be needed for scale tests, to be able to use clusters with more than 500 nodes.

aws: Create subnets for additional network CIDRs

---

k8s/crds/kops.k8s.io_clusters.yaml
k8s/crds/kops.k8s.io_instancegroups.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

Add support for --experimental-allocatable-ignore-eviction kubelet flag

---

upup/pkg/fi/cloudup/openstack/cloud.go

Small typo-level fix to match the function name.

cleanup: Fix comment on GetExternalNetwork

---

docs/getting_started/openstack.md

Changes "clouster" to "cluster" in the getting started docs for OpenStack.

Fix small typo in documentation

---

cloudmock/gce/mockcompute/forwarding_rule.go
pkg/model/components/etcdmanager/model.go
pkg/model/gcemodel/api_loadbalancer.go
pkg/model/gcemodel/autoscalinggroup.go
pkg/model/master_volumes.go
pkg/resources/gce/gce.go
tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
upup/pkg/fi/cloudup/gce/compute.go
upup/pkg/fi/cloudup/gce/gce_cloud.go
upup/pkg/fi/cloudup/gce/labels.go
upup/pkg/fi/cloudup/gce/utils.go
upup/pkg/fi/cloudup/gcetasks/forwardingrule.go
upup/pkg/fi/cloudup/utils.go

Cherry pick of #15709 on release-1.27.
#15709: gce: Set labels on ForwardingRules
```release-note
```

Automated cherry pick of #15709: gce: Set labels on ForwardingRules

---

docs/getting_started/scaleway.md
go.mod
go.sum
pkg/instancegroups/instancegroups.go
upup/pkg/fi/cloudup/scaleway/cloud.go
upup/pkg/fi/cloudup/scalewaytasks/instance.go
vendor/github.com/scaleway/scaleway-sdk-go/api/domain/v2beta1/domain_sdk.go
vendor/github.com/scaleway/scaleway-sdk-go/api/instance/v1/instance_sdk.go
vendor/github.com/scaleway/scaleway-sdk-go/api/lb/v1/lb_sdk.go
vendor/github.com/scaleway/scaleway-sdk-go/api/marketplace/v2/marketplace_sdk.go
vendor/github.com/scaleway/scaleway-sdk-go/api/marketplace/v2/marketplace_utils.go
vendor/github.com/scaleway/scaleway-sdk-go/scw/locality.go
vendor/modules.txt

This PR adds the possibility to edit the image and the size of the instances on a live cluster by performing a rolling-update.
This feature will also be useful for the Terraform support that's coming up next.

scaleway: rolling-update feature

---

pkg/model/awsmodel/network.go
upup/pkg/fi/cloudup/awstasks/subnet.go

```
I0830 21:46:21.956837    6319 executor.go:111] Tasks: 47 done / 143 total; 32 can run
W0830 21:46:22.741524    6319 executor.go:139] error running task "Subnet/us-east-2a-3.e2e-ff02749ef8-a423a.test-cncf-aws.k8s.io" (9m59s remaining to succeed):
error creating subnet: InvalidSubnet.Range: The CIDR '10.3.0.0/16' is invalid.
status code: 400, request id: fee55917-abd5-4508-a0a8-724aefcdcbd6
W0830 21:46:22.741566    6319 executor.go:139] error running task "Subnet/us-east-2a-4.e2e-ff02749ef8-a423a.test-cncf-aws.k8s.io" (9m59s remaining to succeed):
error creating subnet: InvalidSubnet.Range: The CIDR '10.4.0.0/16' is invalid.
status code: 400, request id: 5bb3cddc-287f-4047-8ae0-01da001d4a9a
W0830 21:46:22.741577    6319 executor.go:139] error running task …
```

aws: Add dependency on additional network cidrs for subnets

---

pkg/model/issuerdiscovery.go

Cherry pick of #14991 on release-1.27.
#14991: Allow custom service account issuer without public bucket
```release-note
```

Automated cherry pick of #14991: Allow custom service account issuer without public bucket

---

pkg/model/issuerdiscovery.go

Allow custom service account issuer without public bucket

---

upup/pkg/fi/topological_sort.go

We weren't previously adding the direct dependency (though we were
adding indirect dependencies) when a task implemented
fi.HasDependencies.
Issue #15751

Dependency analysis: include the direct task

---

cmd/kops/create_cluster.go
docs/cli/kops_create_cluster.md
tests/integration/create_cluster/ha_openstack_nodns/options.yaml
tests/integration/create_cluster/minimal-1.26-arm64/options.yaml
tests/integration/create_cluster/private_gce/options.yaml
upup/pkg/fi/cloudup/new_cluster.go

Alternative to #15849, for use in scalability tests.
/cc @justinsb @johngmyers @dims

aws: Add option to provide multiple instance types on cluster creation

---

pkg/model/awsmodel/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/warmpool.go

We should populate the AutoscalingGroup field, so that it can be used
by dependency analysis.

Fix warmpool to expose dependencies for dependency analysis

---

pkg/model/awsmodel/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/warmpool.go

Cherry pick of #15848 on release-1.27.
#15848: Fix warmpool to expose dependencies for dependency analysis

Automated cherry pick of #15848: Fix warmpool to expose dependencies for dependency analysis

---

upup/pkg/fi/topological_sort.go

Cherry pick of #15846 on release-1.27.
#15846: Dependency analysis: include the direct task

Automated cherry pick of #15846: Dependency analysis: include the direct task

---

upup/pkg/fi/executor.go

Previously we were implying that the tasks were somehow failing,but
this isn't quite right when they emit the try-again-later error.
Also pretty-print the pluralization while we're here.

Improve status printing when tasks are in progress

---

tests/e2e/scenarios/scalability/run-test.sh

```
AutoscalingGroup/nodes-us-east-2a.e2e-ff02749ef8-a423a.test-cncf-aws.k8s.io
MixedInstanceOverrides	[c7g.large, c6g.large, t4g.large, m7g.large, m6g.large, r7g.large, r6g.large]
```

Use mixed instances for scale tests

---

Makefile

Cherry pick of #15879 on release-1.28.
#15879: Update ko to v0.14.1
```release-note
```

Automated cherry pick of #15879: Update ko to v0.14.1

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.25_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.25_content
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.25.yaml.template

Cherry pick of #15878 on release-1.28.
#15878: Update Calico to v3.25.2
```release-note
```

Automated cherry pick of #15878: Update Calico to v3.25.2

---

cloudmock/aws/mockec2/eni.go
pkg/resources/aws/eni.go

Attempting to fix the scalability tests: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2/1699576183240265728
* Paginate DescribeNetworkInterfaces which should help with large VPCs containing many ENIs. A similar change was made to the AWS VPC CNI: https://github.com/aws/amazon-vpc-cni-k8s/pull/1333
* Filter for unattached ENIs in the API rather than after the fact, reducing the number of response pages.

ENI Cleanup Improvements

---

cmd/kops/create_cluster_integration_test.go
docs/releases/1.28-NOTES.md
tests/integration/create_cluster/minimal-1.29-gce/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.29-gce/options.yaml
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
upup/pkg/fi/cloudup/new_cluster.go

/cc @justinsb 
More details for why: https://kubernetes.slack.com/archives/C8MKE2G5P/p1694044152804789

Remove metadata-proxy from GCE Clusters from 1.29+ onwards

---

pkg/resources/gce/gce.go

- Capitalized a few resources to match their names
- If you cancel kubetest2 before the tests start running, you end up in a weird state where it tries to delete service accounts after they had been deleted. This change fixes that

Handle 404 properly from Service Accounts API

---

tests/e2e/scenarios/scalability/run-test.sh

- Pods and nodes are not coming up due to insufficient IPs, so increasing CIDRs to accommodate this.

Increase vpc cidrs to allocate more ip's for large scale k8s clusters

---

cmd/kops-controller/main.go

Follow-up to https://github.com/kubernetes/kops/pull/15593.
kOps controller is at the core of the cluster. It should be able to check nodes registration on large clusters, without blocking:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/15836/presubmit-kops-aws-scale-amazonvpc-using-cl2/1701807832023699456/artifacts/cluster-info/kube-system/kops-controller-2qgsh/logs.txt
```
I0913 05:49:15.260083       1 server.go:190] bootstrap 10.0.71.103:37030 error querying for node "i-0f5820f600c12a0e9": client rate limiter Wait returned an error: context canceled
I0913 05:49:15.275159       1 server.go:190] bootstrap 10.0.83.79:56446 error querying for node "i-0da05fd199796fe79": client rate limiter Wait returned an error: context canceled
I0913 05:49:15.342441       1 …
```

kops-controller: Increase client-side throttling limits

---

pkg/model/iam/iam_builder.go
tests/integration/update_cluster/aws-lb-controller/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm/data/aws_iam_role_policy_masters.minimal.example.com_policy
tests/integration/update_cluster/many-addons/data/aws_iam_role_policy_masters.minimal.example.com_policy

This is needed for configuring [Cognito authentication](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/tasks/cognito_authentication/). The `cognito-idp:DescribeUserPoolClient` permission has been present in the [upstream install docs](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/e619a48553981e153860044f8c14bc6cb27e891c/docs/install/iam_policy.json#L48) for a long time. I haven't looked into the integration test infrastructure so I have no idea if I should have updated all of the stuff in `tests/integration/update_cluster`.

Add Cognito permissions for AWS LBC

---

nodeup/pkg/model/kubelet.go

There is a bug caused by the CDN switch recently that is causing COS e2e clusters to not provision properly.
https://github.com/kubernetes/k8s.io/issues/5659

Fix COS image mounter URL

---

tests/e2e/scenarios/scalability/run-test.sh

scale-test: Increase validation wait time to 45m

---

cmd/kops/rolling-update_cluster.go
docs/cli/kops_rolling-update_cluster.md

Make `--cloudonly` sound less innocuous

---

pkg/model/iam/iam_builder.go
tests/integration/update_cluster/aws-lb-controller/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_iam_role_policy_aws-load-balancer-controller.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/many-addons-ccm/data/aws_iam_role_policy_masters.minimal.example.com_policy
tests/integration/update_cluster/many-addons/data/aws_iam_role_policy_masters.minimal.example.com_policy

Cherry pick of #15910 on release-1.27.
#15910: Add Cognito permissions for AWS LBC.
```release-note
```

Automated cherry pick of #15910: Add Cognito permissions for AWS LBC.

---

docs/cluster_spec.md
k8s/crds/kops.k8s.io_clusters.yaml
k8s/crds/kops.k8s.io_instancegroups.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

Updating the kubelet config spec with the `SeccompDefault` feature gate and `--seccomp-default` boolean flag.

Add `SeccompDefault` kubelet config

---

tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/new_cluster.go

The main CIDR is considered special. It will be split into smaller CIDRs to allow it to hold all the control-plane instance groups. This makes these smaller CIDRs less suitable for worker nodes as they will run out of IPs faster, especially when ENIs are used.
@hakuna-matatah

Optimize subnets asignment to IGs for clusters with multiple CIDRs

---

cmd/kops-controller/controllers/gceipam.go
pkg/applylib/mocks/mockkubeapiserver/apiserver.go
upup/pkg/fi/cloudup/template_functions.go
upup/pkg/fi/vfs_castore.go

- WIP: Need to publish IPv4 DNS records
- Cleanup a few places where we used Warningf with %w

fix a few log with percent w

---

pkg/assets/builder.go
pkg/truncate/truncate.go

We had hard-coded k8s.gcr.io, but this is also available in registry.k8s.io
Also cleanup a few comments

fix some comments

---

docs/cluster_spec.md
k8s/crds/kops.k8s.io_clusters.yaml
k8s/crds/kops.k8s.io_instancegroups.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

Cherry pick of #15919 on release-1.28.
#15919: Update kubelet API with SeccompDefault option.
```release-note
```

Automated cherry pick of #15919: Update kubelet API with SeccompDefault option.

---

pkg/dump/dumper.go

scale-test: Optimise node dumping for large clusters

---

protokube/pkg/gossip/dns/hosts.go

Though we likely want to stop using this code altogether, it is still
used on GCE (for now).  dns-controller will "gossip" AAAA records, and
they are valid (and work) in /etc/hosts.

protokube: support writing AAAA records to /etc/hosts

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/networking.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.13.yaml.template

Fixes: https://github.com/kubernetes/kops/issues/15853
In 1.13 and below, the node encryption only works with IPsec and from 1.14 and above it only works with wireguard.
There is no extra validation added, because the setting will be ignored if you have `wiredguard` + `nodeEncryption` + cilum 1.13 or `ipsec` + `nodeEncryption` + cilium 1.14.

Cilium: Implement node encryption

---

tests/e2e/e2e.mk
tests/e2e/go.mod
tests/e2e/kubetest2-kops/deployer/deployer.go
tests/e2e/kubetest2-kops/deployer/dumplogs.go
tests/e2e/kubetest2-kops/deployer/up.go
tests/e2e/kubetest2-kops/gce/gcs.go
tests/e2e/pkg/util/publicip.go

I cleaned up some logic in the kubetest2-kops deployer. Some flags are automatically enabled when testing on GCE.

Fix e2e testing logic

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/networking.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.13.yaml.template

Cherry pick of #15901 on release-1.28.
#15901: Implement node encryption
```release-note
```

Automated cherry pick of #15901: Implement node encryption

---

pkg/model/components/addonmanifests/karpenter/iam.go
tests/integration/update_cluster/karpenter/data/aws_iam_role_policy_karpenter.kube-system.sa.minimal.example.com_policy
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template

`on-demand` is the right string to indicate OnDemand in Karpenter. See: https://github.com/aws/karpenter-core/blob/main/pkg/apis/v1alpha5/labels.go#L30 As the result it does not fall back to ondemand instances.
Also add `ec2:DescribeImages` to karpenter IAM policies -- it's noted in https://karpenter.sh/docs/getting-started/migrating-from-cas/#create-iam-roles (the list also has DeleteLaunchTemplates but I don't think this is necessary for kOps).

aws: Fix minor typos for Karpenter setup

---

docs/cluster_spec.md

Just a note with info on path [changes](https://github.com/kubernetes/kops/blob/master/docs/releases/1.22-NOTES.md#control-plane-pods-no-longer-mount-srvkubernetes) in 1.22-1.25 when audit logging is to be enabled.

Add info for kOps 1.22-1.24 on audit logging path changes

---

channels/alpha

Bump versions in alpha channel. Stable update to follow next week.
k8s release notes:
- https://github.com/kubernetes/kubernetes/releases/tag/v1.25.14
- https://github.com/kubernetes/kubernetes/releases/tag/v1.26.9
- https://github.com/kubernetes/kubernetes/releases/tag/v1.27.6
- https://github.com/kubernetes/kubernetes/releases/tag/v1.28.2
Ubuntu versions taken from https://cloud-images.ubuntu.com/locator/ec2/ (search for `focal` and `jammy` accordingly)

bump k8s releases and ubuntu ami versions in alpha channel

---

pkg/model/components/gcpcloudcontrollermanager.go
tests/integration/update_cluster/ha_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
upup/models/cloudup/resources/addons/gcp-cloud-controller.addons.k8s.io/k8s-1.23.yaml.template

I'm confused about something.
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-cos-gce-slow-canary/1707140514421149696
kops deploys the ccm like this:
```yaml
- metadata:
name: cloud-controller-manager
namespace: kube-system
resourceVersion: "428"
uid: 1a8d26de-01fa-4248-bc40-9e4eca30d70e
spec:
spec:
containers:
- args:
- --allocate-node-cidrs=true
- --cidr-allocator-type=CloudAllocator
- --cluster-cidr=100.96.0.0/11
- --cluster-name=e2e-e2e-ci-kubernetes-e2e-cos-gce-slow-canary-k8s-local
- --leader-elect=true
- --v=2
- --cloud-provider=gce
- --use-service-account-credentials=true
- --cloud-config=/etc/kubernetes/cloud.config
command:
- /cloud-controller-manager
env:
- name: KUBERNETES_SERVICE_HOST
value: 127.0.0.1
image: …
```

Add missing rbac roles and don't run gkenetparams controller

---

pkg/model/awsmodel/network.go

`VPCCIDRBlock` tasks are not created when the VPC is shared:
https://github.com/kubernetes/kops/blob/ecda9e8652e660e29dc8f25a56e7a8b834eeb574/pkg/model/awsmodel/network.go#L97-L116

aws: Don't add dependency on additional CIDR for shared VPC

---

pkg/model/awsmodel/network.go

Cherry pick of #15987 on release-1.28.
#15987: aws: Don't add dependency on additional CIDR for shared VPC
```release-note
```

Automated cherry pick of #15987: aws: Don't add dependency on additional CIDR for shared VPC

---

util/pkg/reflectutils/access.go
util/pkg/reflectutils/access_test.go
util/pkg/reflectutils/field_path.go

```shell
> kops create cluster \
--set spec.kubeAPIServer.runtimeConfig=extensions/v1beta1=true \
--set spec.kubeAPIServer.runtimeConfig=scheduling.k8s.io/v1alpha1=true
...
> kops get cluster -o yaml
...
kubeAPIServer:
runtimeConfig:
extensions/v1beta1: "true"
scheduling.k8s.io/v1alpha1: "true"
...
```
/cc @upodroid

Allow setting map[string]string from the command line

---

upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
upup/models/cloudup/resources/addons/digitalocean-csi-driver.addons.k8s.io/k8s-1.22.yaml.template

The DO e2e presubmits will likely fail with the same ongoing failure as the periodics.

Update DigitalOcean addons

---

tests/e2e/kubetest2-kops/deployer/build.go
tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/kubetest2-kops/deployer/down.go
tests/e2e/kubetest2-kops/deployer/up.go
tests/e2e/kubetest2-kops/gce/gcs.go

Right now, kops assets get staged at the `kops-ci` bucket which is not writable if you migrate the job to the community cluster.
This change creates a public temporary staging bucket if you lease a project from boskos, similar to how we create the state buckets today.
@rjsadow You should be able to migrate kops GCE presubmits after this is merged.
Part of https://github.com/kubernetes/test-infra/issues/29722

Create a temporary staging bucket for kops builds

---

cmd/kops/create_cluster.go
tests/integration/create_cluster/different-amis/options.yaml
tests/integration/create_cluster/ha_openstack/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_openstack_octavia/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/new_cluster.go

/cc @justinsb @johngmyers @rifelpet @zetaab

Use dns=none for newly created clusters except for AWS and GCE

---

docs/releases/1.29-NOTES.md
nodeup/pkg/model/context.go
nodeup/pkg/model/kubelet.go
pkg/apis/kops/cluster.go
pkg/apis/kops/model/features.go
pkg/apis/kops/v1alpha3/cluster.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
upup/pkg/fi/cloudup/apply_cluster.go

Should fix these failing tests: 
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeup-to-kops#ci-kubernetes-e2e-cos-gce-canary&include-filter-by-regex=private.image

Configure GCP Kubelet Credentials Provider

---

pkg/dump/dumper.go

Fixes: https://github.com/kubernetes/kops/issues/15973

Dump nodes even if controlplane is broken

---

pkg/client/simple/api/clientset.go
pkg/client/simple/vfsclientset/clientset.go
pkg/client/simple/vfsclientset/cluster.go
pkg/client/simple/vfsclientset/commonvfs.go
pkg/templates/templates.go
upup/models/vfs.go
upup/pkg/fi/secrets/vfs_secretstore.go
upup/pkg/fi/vfs_castore.go
upup/pkg/fi/vfs_castore_test.go
util/pkg/vfs/azureblob.go
util/pkg/vfs/fs.go
util/pkg/vfs/gsfs.go
util/pkg/vfs/k8sfs.go
util/pkg/vfs/memfs.go
util/pkg/vfs/memfs_test.go
util/pkg/vfs/s3fs.go
util/pkg/vfs/sshfs.go
util/pkg/vfs/swiftfs.go
util/pkg/vfs/vfs.go

This allows for propagation of opentelemetry traces.

Refactor: Add context.Context to more VFS methods

---

tests/e2e/scenarios/scalability/run-test.sh

~- This PR makes CL2 to install prometheus stack locally before kicking off the load test~
~- Update go deps from https://github.com/kubernetes-sigs/kubetest2/pull/244~
- Also update the worker node architecture to `amd64` for prometheus and grafana nodes to come up successfully.
- Also this [https://github.com/kubernetes/kops/pull/15963#issuecomment-1760718194](url)
- Also this [https://github.com/kubernetes/kops/pull/15963#issuecomment-1766864001](url)
- Also this [https://github.com/kubernetes/kops/pull/15963#issuecomment-1767112397](url)
- Clean up to make the script to only run CL2 and not conformance

scale-test: Measure APIServer SLOs

---

pkg/model/gcemodel/autoscalinggroup.go
tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/many-addons-gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
upup/pkg/fi/cloudup/gcetasks/instance.go

This changes adds the `cloud-platform` scope to the GCP instances created by kOps. 
This is the [Google recommended best practice](https://cloud.google.com/compute/docs/access/service-accounts#scopes_best_practice), and it allows setting instance permissions via the IAM roles granted to the Service Account associated with the VM.
Also, [code comments in kops indicate this a desirable change](https://github.com/kubernetes/kops/blob/66835ecaa4050db7c36bcc2a926c8e06508f5cf6/pkg/model/gcemodel/autoscalinggroup.go#L167). 
In our case, we needed the bastion nodes to be able to read secrets out of Google Secret Manager, which the current VM scopes wouldn't have allowed.
Closes #11768

Add cloud-platform GCP VM scope

---

protokube/pkg/gossip/scaleway/seeds.go
protokube/pkg/protokube/scaleway_volumes.go
upup/pkg/fi/cloudup/scaleway/cloud.go
upup/pkg/fi/cloudup/scaleway/verifier.go
upup/pkg/fi/cloudup/scalewaytasks/instance.go
upup/pkg/fi/cloudup/scalewaytasks/lb_backend.go
vendor/github.com/scaleway/scaleway-sdk-go/api/ipam/v1alpha1/ipam_sdk.go
vendor/modules.txt

Since the release of IPAM at Scaleway, some services (like load-balancers) no longer work with the IP provided by the instance API.
This PR makes all kOps components use the IPs from IPAM instead.
A PR has also been made on the [etcd-manager](https://github.com/kubernetes-sigs/etcdadm/pull/385) and works together with this one. 
This is the first step for the integration of private networks, which is coming soon.

scaleway: IPAM integration

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

Cherry pick of #16038 on release-1.27.
#16038: Add support for --cluster-signing-duration KCM flag
```release-note
```

Automated cherry pick of #16038: Add support for --cluster-signing-duration KCM flag

---

tests/e2e/kubetest2-kops/deployer/build.go
tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/kubetest2-kops/deployer/deployer.go

kOps assumes that both ARM64 and AMD64 binaries are built when creating a new cluster.
When building Kubernetes for testing, we want a specific build arch, but only in that case.
/cc @upodroid @aojea @justinsb

Fix tests for multi-arch clusters

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go

Cherry pick of #16051 on release-1.28.
#16051: aws: Skip ASG cleanup on Karpenter managed IG deletion
```release-note
```

Automated cherry pick of #16051: aws: Skip ASG cleanup on Karpenter managed IG deletion

---

pkg/model/components/containerd.go
tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-nodes_content
upup/pkg/fi/cloudup/runc.go

Cherry pick of #16043 on release-1.28.
#16043: Update containerd to v1.7.7
```release-note
```

Automated cherry pick of #16043: Update containerd to v1.7.7

---

docs/releases/1.27-NOTES.md
docs/releases/1.28-NOTES.md

When upgrading from kOps 1.25/26 to 1.27/1.28 I experienced some breaking changes:
I relied on the calculation of the `serviceClusterIPRange` from `nonMasqueradeCIDR` which was removed in https://github.com/kubernetes/kops/pull/15866. This resulted in an error with the certificate as the certificate for the API was still issued for the previous service IP. Setting the `serviceClusterIPRange` to the previously calculated one was doing the trick.
Also, when having clusters running on OpenStack with gossip and the state stored in S3, newly created nodes will not join the cluster, as the `S3_*` variables are not passed on to the nodes anymore, [due to the change here](https://github.com/kubernetes/kops/pull/15646/files#diff-c1c852aea92883d3117fae99c1610c5cdcbc217f5aa3b340f23b5dd02e971d99L137-L …

Document breaking changes for serviceClusterIPRange and OpenStack with S3 state store

---

tests/e2e/kubetest2-kops/deployer/down.go
tests/e2e/kubetest2-kops/deployer/dumplogs.go

This change skips dumping logs if the cluster doesn't exist.
These lines should disappear
```
I1014 18:57:08.799731    6300 dumplogs.go:46] /home/prow/go/src/k8s.io/kops/.build/dist/linux/amd64/kops toolbox dump --name e2e-pr16011.pull-kops-e2e-k8s-gce-cilium.k8s.local --dir /logs/artifacts --private-key /tmp/kops-ssh3199524214/key --ssh-user prow
I1014 18:57:08.799751    6300 local.go:42] ⚙️ /home/prow/go/src/k8s.io/kops/.build/dist/linux/amd64/kops toolbox dump --name e2e-pr16011.pull-kops-e2e-k8s-gce-cilium.k8s.local --dir /logs/artifacts --private-key /tmp/kops-ssh3199524214/key --ssh-user prow
Error: Cluster.kops.k8s.io "e2e-pr16011.pull-kops-e2e-k8s-gce-cilium.k8s.local" not found
W1014 18:57:09.079398    6300 dumplogs.go:54] kops toolbox dump failed: exit status 1
I1014 …
```

don't dump logs if the cluster doesn't exist

---

k8s/crds/kops.k8s.io_clusters.yaml
k8s/crds/kops.k8s.io_instancegroups.yaml
nodeup/pkg/model/containerd.go
nodeup/pkg/model/containerd_test.go
nodeup/pkg/model/tests/containerdbuilder/complex/cluster.yaml
nodeup/pkg/model/tests/containerdbuilder/complex/tasks.yaml
pkg/apis/kops/containerdconfig.go
pkg/apis/kops/v1alpha2/containerdconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/containerdconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
util/pkg/reflectutils/access.go

Adding containerd `configAdditions` in the cluster config:
```yaml
containerd:
configAdditions:
plugins."io.containerd.grpc.v1.cri".containerd.runtimes.test-handler.test_bool_false: "false"
plugins."io.containerd.grpc.v1.cri".containerd.runtimes.test-handler.test_bool_true: "true"
plugins."io.containerd.grpc.v1.cri".containerd.runtimes.test-handler.test_int: 1
plugins."io.containerd.grpc.v1.cri".containerd.runtimes.test-handler.test_intstr: "1"
plugins."io.containerd.grpc.v1.cri".containerd.runtimes.test-handler.test_str: test
```
will create additional containerd config file entries:
```toml
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.test-handler]
test_bool_false = false
test_bool_true = true
test_int = 1
test_intstr = "1"
test_str = "test"
```
Refs: …

Add option to provide additional config entries for containerd

---

pkg/resources/aws/aws.go
pkg/resources/aws/natgateway.go

I think we were leaking egress-only-internet-gateways, it would be
helpful to see their status in the dump.

dump: include the various gateways on AWS

---

pkg/resources/aws/aws.go
pkg/resources/aws/natgateway.go

I had forgotten to populate the object itself, so it was not appearing
in the raw dump.

dump: actually dump the gateway objects

---

upup/pkg/fi/cloudup/gce/gce_cloud.go

@justinsb this is the fix for the concurrent map write panic that we discussed.
It only occurs when kops is invoked by Terraform, which is parallelising updates to multiple instance groups at the same time.
The stack trace looked liked:
```
fatal error: concurrent map writes
fatal error: concurrent map writes
goroutine 102 [running]:
k8s.io/kops/upup/pkg/fi/cloudup/gce.CacheGCECloudInstance(...)
/Users/matt/git/kops/upup/pkg/fi/cloudup/gce/gce_cloud.go:182
k8s.io/kops/upup/pkg/fi/cloudup/gce.NewGCECloud({0x14001c8a010, 0xb}, {0x14001ff1f96, 0xa}, 0x140007be720)
/Users/matt/git/kops/upup/pkg/fi/cloudup/gce/gce_cloud.go:165 +0x4d0
k8s.io/kops/upup/pkg/fi/cloudup.BuildCloud(0x140006cd400)
/Users/matt/git/kops/upup/pkg/fi/cloudup/utils.go:63 +0xd20 …
```

fix: concurrent map write panic

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

Cherry pick of #16085 on release-1.27.
#16085: Update Go to v1.21.4
```release-note
```

Automated cherry pick of #16085: Update Go to v1.21.4

---

cloudmock/aws/mockautoscaling/group.go
cloudmock/aws/mockautoscaling/tags.go
cloudmock/aws/mockautoscaling/warmpool.go
cloudmock/aws/mockec2/launch_templates.go
pkg/instancegroups/rollingupdate_test.go
pkg/resources/aws/aws.go
upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/autoscalinglifecyclehook.go
upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
upup/pkg/fi/cloudup/awstasks/warmpool.go
upup/pkg/fi/cloudup/awsup/aws_cloud.go
upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
upup/pkg/fi/nodeup/command.go

There are still too many context.TODOs here for this to join all the
way up, but we should be able to better understand the slowest tasks.

Thread context through some slower AWS tasks

---

tests/e2e/kubetest2-kops/deployer/down.go
tests/e2e/pkg/kops/state.go
tests/e2e/pkg/tester/tester.go

If a job's --down was interrupted, the state store can be in an inconsistent state. This can cause `kops get cluster --full` to fail if certain additional objects are missing, yet `kops get cluster` would succeed:
https://github.com/kubernetes/kops/blob/cef906f1a64594813a0598de53eb58402295c0f8/cmd/kops/get_cluster.go#L159-L167
https://github.com/kubernetes/kops/blob/b7befc1cb521001a21181188237c12430f5894ae/cmd/kops/get_cluster.go#L282-L293
We omit `--full` to ensure `kops get cluster` succeeds and leak cleanup is reattempted.
Fixes these jobs:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-arm64-ci/1724140038914052096
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-metrics-server/1724256557673222144
* …

Don't get cluster --full when attempting leak cleanup

---

upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstack/server_group.go

this should fix issue #16106
The missing piece was that resources were not filtered by cluster information.
cc @Wieneo

Check cluster information when filtering instances

---

upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstack/server_group.go

Cherry pick of #16112 on release-1.28.
#16112: check kops cluster name when filtering instances in
```release-note
```

Automated cherry pick of #16112: check kops cluster name when filtering instances in

---

docs/networking/kube-router.md
docs/releases/1.27-NOTES.md
docs/releases/1.28-NOTES.md
pkg/apis/kops/validation/validation.go
upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template

This PR, updates kube-router to the latest stable 1.X release (1.6.0). It is primarily a dependency update release and has been released for several months. If this goes well, the next step would be to upgrade to kube-router 2.X which is the most recent stable release, but comes with a few breaking changes.
I have also removed the deprecation notices for kube-router since I'm now committing to maintaining it. I have split out a 3rd commit that removes the deprecation notices for kube-router from the kops release notes. However, I left it as a separate commit, because I'm not sure if the project considers release notes like that immutable. Let me know the best way to proceed, and I can modify the PR accordingly.
After upgrading it, I have tested it against my own kops cluster and I have …

Update kube-router to 1.6

---

pkg/assets/copyfile.go

currently it is not possible to use local file:// vfs when copying assets. This makes it easier to generate files for asset `fileRepository`. It can be done like:
1)
```
spec:
assets:
fileRepository: file:///tmp/kops
```
2) `kops get assets --name mycluster.k8s.local --copy` (after this the assets are available in local disk)
3) copy assets from local disk to place that can serve static files. It can be for instance just nginx
4) edit spec again
```
spec:
assets:
fileRepository: https://path/to/my/nginx/foo
```

allow local file VFS in asset copy

---

docs/networking/kube-router.md
docs/releases/1.27-NOTES.md
docs/releases/1.28-NOTES.md
pkg/apis/kops/validation/validation.go
upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template

Cherry pick of #16110 on release-1.28.
#16110: Update kube-router to v1.6.0
```release-note
```

Automated cherry pick of #16110: Update kube-router to v1.6.0

---

pkg/model/context.go
tests/integration/update_cluster/irsa/kubernetes.tf

Cherry pick of #16113 on release-1.28.
#16113: Replace * in IAM tags when IRSA namespace has wildcard
```release-note
```

Automated cherry pick of #16113: Replace * in IAM tags when IRSA namespace has wildcard

---

channels/alpha

bumping versions for k8s and ubuntu ec2 ami (focal and jammy) to latest
k8s releases:
- https://github.com/kubernetes/kubernetes/releases/tag/v1.25.16
- https://github.com/kubernetes/kubernetes/releases/tag/v1.26.11
- https://github.com/kubernetes/kubernetes/releases/tag/v1.27.8
- https://github.com/kubernetes/kubernetes/releases/tag/v1.28.4
Ubuntu AMI page ec2 locator:
https://cloud-images.ubuntu.com/locator/ec2/
/cc @hakman

bump k8s and ubuntu ami versions in alpha

---

pkg/apis/kops/util/versions.go
pkg/apis/kops/util/versions_test.go

Now that k/k's CI version markers point to 1.30 builds, kops' e2e jobs have started failing:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-amd64-conformance/1727421344523489280

Fix parsing of newer kubernetes version URLs

---

cmd/kops/create_cluster.go
cmd/kops/edit_cluster.go
cmd/kops/edit_instancegroup.go
cmd/kops/flags_stringslice_lazyquotes.go
docs/cli/kops_create_cluster.md
docs/cli/kops_edit_cluster.md
docs/cli/kops_edit_instancegroup.md

The pflag library tries to split comma separated values using strict
CSV semantics, which requires quoting of the full value if the value
contains a quote.  We switch to LazyQuotes which is much more
tolerant.

kops: Support quotes in --set flags

---

pkg/assets/builder.go

what is the use-case for this? I do have KOPS_BASE_URL located in same object storage. It does not make sense to make 2 copies from same files basically.
blue: before
red: after

skip file remapping if same host

---

tests/e2e/kubetest2-kops/deployer/common.go

Limit jobName length 80 to avoid long job names from failing.
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-al2023-aws-conformance-aws-cni-canary/1730167438948962304
```
Error: error running tasks: deadline exceeded executing task SQS/e2e-e2e-ci-kubernetes-e2e-al2023-aws-conformance-aws-cni-canary-test-cncf-aws-k8s-io-nth. Example error: error creating SQS queue: InvalidParameterValue: Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length
```
/cc @hakman @dims

limit jobname value to 80

---

cmd/kops-controller/main.go
pkg/bootstrap/authenticate.go
pkg/bootstrap/chain.go
upup/pkg/fi/cloudup/awsup/aws_verifier.go
upup/pkg/fi/cloudup/azure/verifier.go
upup/pkg/fi/cloudup/do/verifier.go
upup/pkg/fi/cloudup/gce/tpm/gcetpmverifier/tpmverifier.go
upup/pkg/fi/cloudup/hetzner/verifier.go
upup/pkg/fi/cloudup/openstack/verifier.go
upup/pkg/fi/cloudup/scaleway/verifier.go

This will allow us to support nodes running in multiple clouds.  If we
don't configure multiple verifiers, this should be a no-op.

feat: Support multiple token verifiers in kops-controller

---

tests/e2e/pkg/tester/skip_regex.go

Fixes https://testgrid.k8s.io/kops-misc#e2e-kops-do-calico-gossip and https://testgrid.k8s.io/kops-misc#e2e-kops-do-calico-dns-none
See the linked issue for more context

Skip hostname test in DigitalOcean

---

tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
upup/models/cloudup/resources/addons/gcp-pd-csi-driver.addons.k8s.io/k8s-1.23.yaml.template

When the the GCE CSI driver is enabled, kOps installs a single StorageClass called `standard-csi`. This SC is backed by the Google Cloud `pd-standard` disk type, which is the slowest spinning disk variety.
https://cloud.google.com/compute/docs/disks#disk-types
On top of being slow, the `pd-standard` disks are not supported on some of the newer GCP Machine Types, such as the C3 family:
https://cloud.google.com/compute/docs/general-purpose-machines#c3_disks
For these reasons it would be great if kOps installed additional StorageClasses, for better performance and broader compatibility.
This change adds two additional StorageClasses named `balanced-csi` and `ssd-csi` to support the `pd-balanced` and `pd-ssd` GCP Persistent Disk types respectively. (I was trying to follow the pattern of the …

gce: Support additional StorageClasses and change default

---

tests/e2e/pkg/tester/skip_regex.go

@hakman 
Since we un-pinned the kube-router tests from 1.27 in https://github.com/kubernetes/test-infra/pull/31278 kube-router now has a couple of new tests that fail consistently.
I'm still working through these, but since the project likes to avoid having consistently failing tests, I figure it would be better to exclude these ones for now.
See: https://testgrid.k8s.io/kops-network-plugins#kops-aws-cni-kuberouter

kube-router: skip 1.28 tests that fail consistently

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-aws-load-balancer-controller.addons.k8s.io-k8s-1.19_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml.template

https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.6.2
closes #16152

Upgrade AWS Load Balancer Controller to v2.6.2

---

cmd/kops/toolbox_dump.go
cmd/kops/toolbox_dump_test.go
docs/cli/kops_toolbox_dump.md
docs/releases/1.29-NOTES.md

ref: https://github.com/kubernetes/k8s.io/issues/6165#issuecomment-1844422503
/cc @dims @hakman
I default this to 500 so we don't have to worry about setting this flag in kubetest2-kops and ensuring we only set it for kops versions that include this addition, as opposed to older kops releases. We (kops maintainers) don't have any need to set this to a higher value in any of our e2e testing, so anyone that does can choose to override it themselves.
I'm also fine with using a lower limit like 100

Add --max-nodes flag to toolbox dump, default to 500

---

tests/e2e/kubetest2-kops/deployer/common.go

Allow env variables required by EKS Pod identity for authentification are passed to the kops binary.
See https://docs.aws.amazon.com/eks/latest/userguide/pod-id-how-it-works.html

Allow EKS Pod identity env variables

---

pkg/model/components/karpenter.go
tests/integration/update_cluster/karpenter/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template

According to the [beta migration guide](https://karpenter.sh/docs/upgrading/v1beta1-migration/) this is the most recent version that can be downgraded to before migrating to the beta APIs.
See the upgrade plan mentioned in https://github.com/kubernetes/kops/issues/16143

Upgrade Karpenter to 0.31.3

---

pkg/model/components/karpenter.go
tests/integration/update_cluster/karpenter/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/karpenter/data/aws_s3_object_minimal.example.com-addons-karpenter.sh-k8s-1.19_content
upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template

Cherry pick of #16163 on release-1.28.
#16163: Upgrade Karpenter to v0.31.3
```release-note
```

Automated cherry pick of #16163: Upgrade Karpenter to v0.31.3

---

tests/e2e/scenarios/scalability/run-test.sh

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2/1733004377897046016
`Error: error running tasks: deadline exceeded executing task AutoscalingGroup/nodes-us-east-2c.scale-1000.periodic.test-cncf-aws.k8s.io. Example error: error creating AutoScalingGroup: Cannot add same instance type override more than once. Remove these duplicates from the request and try again: [m5.large]`
Followup to https://github.com/kubernetes/kops/pull/16156

Remove duplicate m5.large from scalability test

---

pkg/applylib/applyset/health.go

Cherry pick of #16167 on release-1.28.
#16167: Ignore HPA status when applying addons
```release-note
```

Automated cherry pick of #16167: Ignore HPA status when applying addons

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

Cherry pick of #16168 on release-1.28.
#16168: chore: Bump go to 1.21.5
```release-note
```

Automated cherry pick of #16168: chore: Bump go to 1.21.5

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Bump cert-manager to 1.12.7
I'm not sure how to handle breaking changes in cert-manager 1.13, but I want the latest CVE patches released for 1.12 last week. If you people feel unnecessary please ignore me ;)

bump cert-manager to 1.12.7

---

pkg/model/gcemodel/autoscalinggroup.go
tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/many-addons-gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
upup/pkg/fi/cloudup/gcetasks/instancegroupmanager.go

This is required to support MIGs with >1000 instances.
See https://cloud.google.com/compute/docs/instance-groups/add-remove-vms-in-mig#increase_the_groups_size_limit
Kops already uses pagination to get instances from instance groups so no other changes are necessary https://github.com/kubernetes/kops/blob/62fcb00f8c6ff3f86adbbaddf9cfe0dbf79c4498/upup/pkg/fi/cloudup/gce/compute.go#L712-L721

Enable pagination on GCE Instance Groups

---

cmd/kops/validate_cluster.go
docs/cli/kops_validate_cluster.md
tests/e2e/kubetest2-kops/deployer/deployer.go
tests/e2e/kubetest2-kops/deployer/dumplogs.go
tests/e2e/kubetest2-kops/deployer/up.go

Required for #16181 
kops validate has a few critical problems:
- every 10 sec, it will try to fetch a complete list of every instance which eats in to the API quotas. A new flag allows you to adjust this duration, with the default set to 10s
- count is also adjustable via kubetest2 as well as the new flag

`kops validate cluster` improvements

---

tests/e2e/pkg/tester/skip_regex.go

@hakman 
Requires https://github.com/kubernetes/kubernetes/pull/122440 to be merged first.
Once those two are merged, kube-router should be passing both of the service affinity tests in the e2e suite, so we can allow those to run and no longer worry about failures.

skip_regex.go: kube-router add back in service afinity test

---

channels/alpha

Update k8s versions and Ubuntu AMI versions (focal/jammy) to latest
- https://github.com/kubernetes/kubernetes/releases/tag/v1.28.5
- https://github.com/kubernetes/kubernetes/releases/tag/v1.27.9
- https://github.com/kubernetes/kubernetes/releases/tag/v1.26.12
- https://cloud-images.ubuntu.com/locator/ec2/ (use search bar to lookup `focal` and `jammy`)
/cc @hakman

chore(channels): bump k8s and ubuntu ami versions in alpha channel

---

tests/e2e/kubetest2-kops/deployer/dumplogs.go

The LBC prow job is flaking. I believe its due to a race condition that still exists. I'm adding the cert-manager resources that the LBC addon includes to help with troubleshooting
https://testgrid.k8s.io/kops-misc#kops-aws-aws-load-balancer-controller

Add cert-manager resource types to kubetest2-kops artifacts

---

cmd/kops/toolbox_dump.go
docs/cli/kops_toolbox_dump.md
pkg/dump/resourcedumper.go
tests/e2e/kubetest2-kops/deployer/dumplogs.go

This adds support for dumping k8s resources with `kops toolbox dump` rather than kubetest2-kops. A few changes compared to the kubetest2-kops logic:
* Resources are dumped in parallel with a worker pool. This should drastically speed up the resource dumps in scalability tests.
* The list of resource kinds to dump is sourced dynamically from the discovery client rather than relying on `kubectl cluster-info dump` + our own static list
One regression is that when the control plane isn't available (due to a kops bug, for example), kubetest2-kops will SSH into control plane nodes and run `kubectl cluster-info dump` on the control plane node and copy the artifacts back locally. `kops toolbox dump` doesn't support this yet. We haven't relied on that for troubleshooting recent prow job failures …

Parallelize k8s resource dumps with kops toolbox dump

---

cmd/kops/toolbox_dump.go
pkg/dump/podlogs.go
pkg/dump/resourcedumper.go

Followup to #16196 I forgot to include pod logs which were being handled by `kubectl cluster-info` ([example artifacts with missing logs](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kops/16181/presubmit-kops-gce-scale-calico-using-cl2/1741588176922742784/artifacts/cluster-info/kube-system/)). This adds back pod logs with a few changes:
* Separate log files per container rather than concatenating them all together in one `logs.txt` file
* Include logs from previous containers when they exist. This should help with troubleshooting cluster validation issues that cause controllers to restart.

Include pod logs in toolbox dump

---

tests/e2e/kubetest2-kops/deployer/up.go

Should be useful to have this again:
```
I0102 08:51:38.744132   13973 up.go:220] /home/prow/go/src/k8s.io/kops/.build/dist/linux/amd64/kops create cluster
--name e2e-pr16202.pull-kops-e2e-k8s-aws-calico.test-cncf-aws.k8s.io
--cloud aws
--kubernetes-version https://dl.k8s.io/release/v1.29.0
--ssh-public-key /tmp/kops/e2e-pr16202.pull-kops-e2e-k8s-aws-calico.test-cncf-aws.k8s.io/id_ed25519.pub
--set cluster.spec.nodePortAccess=0.0.0.0/0
--set spec.containerd.configAdditions=plugins."io.containerd.grpc.v1.cri".containerd.runtimes.test-handler.runtime_type=io.containerd.runc.v2
--channel=alpha
--networking=calico
--discovery-store=s3://k8s-kops-prow/discovery
--admin-access 35.222.3.8/32
--master-count 1 --master-size c5.large --master-volume-size 48 --node-count 4 --node-volume-size 48 …
```

test: Print the `create cluster` command

---

cmd/kops/toolbox_dump.go

/cc @rifelpet
```
I0103 05:06:02.213472   14553 up.go:58] Cleaning up any leaked resources from previous cluster
I0103 05:06:02.424454   14553 dumplogs.go:47] /home/prow/go/src/k8s.io/bin/kops toolbox dump --name e2e-ff02749ef8-a423a.test-cncf-aws.k8s.io --dir /logs/artifacts --private-key /tmp/kops/e2e-ff02749ef8-a423a.test-cncf-aws.k8s.io/id_ed25519 --ssh-user ubuntu
I0103 05:06:02.431913   14592 featureflag.go:168] FeatureFlag "AWSSingleNodesInstanceGroup"=true
W0103 05:06:04.850989   14592 toolbox_dump.go:172] cannot load kubeconfig settings for "e2e-ff02749ef8-a423a.test-cncf-aws.k8s.io": context "e2e-ff02749ef8-a423a.test-cncf-aws.k8s.io" does not exist
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or …
```

Check if kubeconfig exists before dumping resources

---

pkg/model/iam/iam_builder.go
upup/pkg/fi/nodeup/command.go

This should eliminate some of the API throttling during scale tests and help with time for nodes to join the cluster
See the example userdata [here](https://docs.aws.amazon.com/autoscaling/ec2/userguide/tutorial-lifecycle-hook-instance-metadata.html#instance-metadata-create-hello-world-function) for usage of this instance metadata endpoint. I confirmed the 404 behavior works on non-ASG instances.

aws: Use instance metadata to get warm pool state

---

pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

This fixes Cilium ENI mode tests
/cc @rifelpet

Update to Cilium 1.14.5

---

nodeup/pkg/model/kubelet.go

/cc @zetaab @rifelpet
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/16204/presubmit-kops-aws-scale-amazonvpc-using-cl2/1742822642840244224/artifacts/i-0005fc01059a34f29/kops-configuration.log
```
I0104 08:28:05.708287    1346 request_logger.go:45] AWS request: ec2/DescribeInstances
I0104 08:28:05.833709    1346 request_logger.go:45] AWS request: ec2/DescribeInstanceTypes
W0104 08:28:06.034361    1346 retry_handler.go:99] Got RequestLimitExceeded error on AWS request (ec2::DescribeInstanceTypes)
I0104 08:28:06.034430    1346 logging_retryer.go:60] Retryable error (RequestLimitExceeded: Request limit exceeded.
status code: 503, request id: 7bd37a68-e0a7-4edc-b5aa-ccd2f5d144a1) from ec2/DescribeInstanceTypes - will retry after delay of 854.685499ms
W0104 08:28:06.889975 …
```

aws: Retrieve instance info only when max pods is not set

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Continuing to troubleshoot the cluster validation flakes in https://testgrid.k8s.io/kops-misc#kops-aws-aws-load-balancer-controller 
This matchExpression was removed upstream in https://github.com/cert-manager/cert-manager/pull/6129

Remove kube-system cert-manager webhook exclusion

---

nodeup/pkg/model/kubelet.go
nodeup/pkg/model/kubelet_test.go

Seeing this in scale-test logs:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/16204/presubmit-kops-aws-scale-amazonvpc-using-cl2/1742962895290896384/artifacts/cluster-info/kube-system/kops-controller-6zn8r/kops-controller.log
```
E0104 17:49:08.753991       1 controller.go:329] "msg"="Reconciler error" "error"="error identifying node \"i-010f7ccf4cfd4f129\":
providerID was not set for node i-010f7ccf4cfd4f129" "Node"={"name":"i-010f7ccf4cfd4f129"} "controller"="node" "controllerGroup"="" "controllerKind"="Node" "name"="i-010f7ccf4cfd4f129" "namespace"="" "reconcileID"="c14b9e58-c70b-489e-9166-99d86a4ec093"
```
/cc @rifelpet

aws: Set provider ID when starting kubelet

---

cmd/kops/delete_cluster.go
docs/cli/kops_delete_cluster.md
pkg/resources/ops/delete.go

Cluster deletion fails on large clusters (5k node) due to no progress being made while waiting for the ASG to be deleted in the background.
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/16204/presubmit-kops-aws-scale-amazonvpc-using-cl2/1743704473194205184
Making cluster deleting configurable, similar to validation options should help with that.
/cc @rifelpet @upodroid @hakuna-matatah @dims

Make cluster deletion configurable

---

tests/e2e/kubetest2-kops/deployer/down.go
tests/e2e/scenarios/scalability/run-test.sh

/cc @dims @hakuna-matatah @upodroid

scale-test: Use single nodes instance group for AWS

---

tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/many-addons-gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
upup/pkg/fi/cloudup/terraform/target_hcl2.go

From skimming all the [major version upgrade guides](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_5_upgrade), it doesn't appear there are any changes needed

Bump GCP terraform provider to latest

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml

Cherry pick of #16245 on release-1.28.
#16245: Update Go to v1.21.6
```release-note
```

Automated cherry pick of #16245: Update Go to v1.21.6

---

pkg/kubeconfig/create_kubecfg.go
upup/pkg/fi/cloud.go
upup/pkg/fi/cloudup/gce/gce_cloud.go

This means that if/when we have multiple load balancers, we will go
through the external one by default.

Prefer external endpoints when building kubeconfig

---

pkg/resources/aws/aws.go

https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-conformance-1-28/1746126431886249984/build-log.txt
```
Deleted kubectl config for e2e-e2e-kops-aws-conformance-1-28.test-cncf-aws.k8s.io
Deleted cluster: "e2e-e2e-kops-aws-conformance-1-28.test-cncf-aws.k8s.io"
Error: error from DescribeRouteTables: InvalidRouteTableID.NotFound: The routeTable ID 'rtb-0676c9cb5faa7c9c2' does not exist
status code: 400, request id: c0edba9d-4053-441e-8a32-c1f304b46776
```

aws: Ignore InvalidRouteTableID.NotFound errors during cluster deletion

---

nodeup/pkg/model/kubelet.go

**What does this PR introduce?**
This PR addresses the issue where kubelet is configured with maxPods 100 in the AWS environment and when cilium with ipam=eni is used.
**Why is this change needed?**
The number of IP addresses is connected to the AWS instance type and is much less than 100 which is the default maxPods value. So, for small instance types we in most cases end up with the pod not being able to schedule because of 'No IP's left to assign on aws instances'
**How does it address the issue?**
We use the same code to determine maxPods per AWS instance type as for amazonvpc networking.
**Related Issue**
Fixes https://github.com/kubernetes/kops/issues/16064

aws: fix maxPods when cilium ipam=eni is used

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

`--test-package-bucket` is removed on https://github.com/kubernetes-sigs/kubetest2/pull/251

Switch to GCS url for upgrades tests

---

go.mod
go.sum
tests/e2e/go.mod
tests/e2e/go.sum
vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
vendor/github.com/aws/aws-sdk-go/aws/version.go
vendor/modules.txt

This is done to fix authentication issues related to EKS Pod identity.
Picking https://github.com/aws/aws-sdk-go/pull/4961

Update aws-sdk-go to v1.49.24

---

tests/e2e/pkg/tester/skip_regex.go
tests/e2e/pkg/tester/tester.go

There is a bug in the test framework where the -num-nodes flag must be explicitly set to avoid tests being skipped. It should be autocalculated but it is not working as intended.
Also, node-os-distro should be set to skip various tests that are OS specific in the kubernetes e2e test suite.
@dims

test: Set num-nodes flag

---

pkg/model/gcemodel/firewall.go
tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
upup/pkg/fi/cloudup/gce/network.go
upup/pkg/fi/cloudup/gce/op.go

Splitting #16181 to separate PRs
This one fixes bugs in GCE infra creation.
- Uses WAIT instead of GET polling for operations. This uses [fewer](https://cloud.google.com/compute/docs/reference/rest/v1/globalOperations/wait) API calls to track operations.
- Increases the GCE alias mode subnet sizes to support 5k nodes
- Fixes a [missing](https://cloud.google.com/load-balancing/docs/health-checks#fw-netlb) firewall rule for NLBs

gce: fix nlb firewall rules, operations and alias network subnets

---

pkg/model/openstackmodel/servergroup.go
pkg/model/openstackmodel/tests/servergroup/adds-additional-security-groups.yaml
pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-ClusterSpec.yaml
pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-InstanceGroupSpec.yaml
pkg/model/openstackmodel/tests/servergroup/configures-allowed-address-pairs-with-annotations.yaml
pkg/model/openstackmodel/tests/servergroup/configures-server-group-affinity-with-annotations.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-auto-zone-distribution.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer-dns-none.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion.yaml
pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-external-router.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion-2.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node-without-bastion-no-public-ip-association.yaml
pkg/model/openstackmodel/tests/servergroup/one-master-one-node.yaml
pkg/model/openstackmodel/tests/servergroup/single-zone-setup-3-masters-1-node-without-bastion-with-API-loadbalancer-dns-none.yaml
pkg/model/openstackmodel/tests/servergroup/truncate-cluster-names-to-42-characters.yaml
pkg/model/openstackmodel/tests/servergroup/uses-instance-group-subnet-as-availability-zones-fallback.yaml
pkg/model/openstackmodel/tests/servergroup/uses-instance-group-zones-as-availability-zones.yaml
upup/pkg/fi/cloudup/openstacktasks/port.go

fixes #16270
see discussion (or actually my wall of text) in issue
cc @justinsb @hakman 
with this change I can get working kube_env.yaml like following in normal node:
```
root@nodes-xx-kybe4u:/home/ubuntu# cat /opt/kops/conf/kube_env.yaml 
APIServerIPs:
- 10.2.131.13
- 10.2.192.39
- 10.2.65.84
CloudProvider: openstack
ClusterName: jessetesti.k8s.local
ConfigServer:
CACertificates: |
-----BEGIN CERTIFICATE-----
snip
TdTyytTpZ/HeOvfbyt6p2qd3I5iaJb2W9Ydo3RROsYAi6p2fMDa/IATzSAQ=
-----END CERTIFICATE-----
servers:
- https://10.2.131.13:3988/
- https://10.2.192.39:3988/
- https://10.2.65.84:3988/
InstanceGroupName: nodes-xx
InstanceGroupRole: Node
NodeupConfigHash: HT1Osvmi/hpjF1M1oH8RuCaqyhiO2/D41/wdkQACILE=
```
```
% kubectl get nodes
NAME                          STATUS   ROLES …
```

openstack: Include kube-apiserver controlplane ports in dns=none

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
tests/integration/update_cluster/complex/data/aws_launch_template_master-us-test-1a.masters.complex.example.com_user_data
tests/integration/update_cluster/complex/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/complex/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
tests/integration/update_cluster/complex/in-v1alpha2.yaml

Add support to configure HPA Controller concurrent syncs flag in HPA/KCM Controller
This value requires to be tweaked to get more performance out of HPA controller on large scale clusters using HPAs.
Plan to leverage this in scale tests in future.
https://github.com/kubernetes/kops/issues/16278

Add support to configure HPA Controller concurrent syncs flag in HPA/KCM Controller

---

cloudmock/gce/mockcompute/forwarding_rule.go
pkg/resources/gce/gce.go
upup/pkg/fi/cloudup/gce/compute.go
upup/pkg/fi/cloudup/gcetasks/forwardingrule.go

Helps with more coherent tracing/logging.

Refactor: Plumb context through GCE firewallRule methods

---

cmd/kops/toolbox_dump.go
pkg/dump/dumper.go
pkg/resources/gce/dump.go
tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/kubetest2-kops/deployer/deployer.go
tests/e2e/kubetest2-kops/deployer/dumplogs.go

Splitting https://github.com/kubernetes/kops/pull/16181 to separate PRs
1. When a bastion is being used, kops tries to use it by its hostname which doesn't work with `--dns=none`. Using the IP address is much easier
2. we also dump the bastion IP in the logs
3. `--max-nodes` flag is now respected by the DumpAllNodes function.
4. kubetest2 now sets the `--ssh-private-key` automatically when running kops gce clusters, this flag must be set for the `kops toolbox dump` cmd to work
5. We calculate the correct internal IP addresses of GCE instances to use with bastions.

Fix dumping logs for GCE scale tests

---

tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/kubetest2-kops/deployer/deployer.go
tests/e2e/kubetest2-kops/deployer/up.go
tests/e2e/scenarios/build/run-test.sh

Required for https://github.com/kubernetes/kops/pull/16181
When we are running scale/gpu tests, we need to use a dedicated pool of GCE projects called `scalability-project`, `scalability-scale-project` and `gpu-project`. This PR adds support for that feature.
Defined here https://github.com/kubernetes/k8s.io/blob/main/infra/gcp/terraform/k8s-infra-prow-build/prow-build/resources/test-pods/boskos-resources-configmap.yaml#L174

Add `boskos-resource-type` flag to use different GCE projects for scale/gpu testing

---

pkg/resources/aws/aws.go

We were previously outputing them with the load-balancer target value.

toolbox dump: output correct type for target groups

---

upup/pkg/fi/dryrun_target.go

This avoids printing a change when the before and after values are the
same.

Fix: support comparison of int types in dry-run

---

pkg/model/awsmodel/api_loadbalancer.go
pkg/model/awsmodel/bastion.go
pkg/model/names.go
upup/pkg/fi/cloudup/awstasks/dnsname.go
upup/pkg/fi/cloudup/awstasks/network_load_balancer.go

It was actually the terraform name, and didn't match the tag.
This change should have no externally-visible effect.

refactor: NetworkLoadBalancer Name should match Name tag

---

upup/pkg/fi/cloudup/awstasks/egressonlyinternetgateway_test.go
upup/pkg/fi/cloudup/awstasks/elastic_ip_test.go
upup/pkg/fi/cloudup/awstasks/internetgateway_test.go
upup/pkg/fi/cloudup/awstasks/securitygroup_test.go
upup/pkg/fi/cloudup/awstasks/subnet_test.go
upup/pkg/fi/cloudup/awstasks/vpc_test.go

This mirrors what we do in gce, and eliminates some boilerplate.

refactor: Introduce runTests helper method into aws tests

---

cloudmock/aws/mockelbv2/loadbalancers.go
pkg/resources/aws/aws.go
upup/pkg/fi/cloudup/awsup/aws_cloud.go
upup/pkg/fi/cloudup/awsup/elbv2_loadbalancers.go

As pruning becomes more a part of tasks, there is more overlap between
`kops update cluster` and `kops delete cluster`.

Refactor: Move NLB listing function into awsup

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Update AWS CNI Version to latest release (v1.16.2)
Release page: https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.16.2
/cc @hakman

chore(networking): bump aws cni to 1.16.2

---

pkg/model/awsmodel/api_loadbalancer.go
upup/pkg/fi/cloudup/awstasks/network_load_balancer.go

This approach is more explicit than looking at the names of the target
groups, and using a private field is simpler.

refactor: wait for load balancer readiness using a private field

---

tests/e2e/scenarios/scalability/run-test.sh

Part of https://github.com/kubernetes/enhancements/issues/4224
Fixes: https://github.com/kubernetes/kops/issues/16241
kops will be replacing the current kubeup 5k scale test, which will be developed here

Add GCE scale testing on kops

---

nodeup/pkg/model/networking/amazon-vpc-routed-eni.go
upup/pkg/fi/nodeup/command.go

Following suggestion in https://github.com/aws/amazon-vpc-cni-k8s/issues/2103 to get Amazon VPC to work on Ubuntu 22.04
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: 
fixes #16255  
fixes #15720 
/cc @hakman

fix(nodeup): set `MACAddressPolicy=none` when using AWS VPC CNI

---

nodeup/pkg/model/networking/amazon-vpc-routed-eni.go
upup/pkg/fi/nodeup/command.go

Cherry pick of #16313 on release-1.28.
#16313: fix(nodeup): set `MACAddressPolicy` to `none` when using AWS
```release-note
```

Automated cherry pick of #16313: fix(nodeup): set `MACAddressPolicy` to `none` when using AWS

---

k8s/crds/kops.k8s.io_clusters.yaml
k8s/crds/kops.k8s.io_instancegroups.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

Cherry pick of #16318 on release-1.28.
#16318: added image minimum and maximum gc age
```release-note
```

Automated cherry pick of #16318: added image minimum and maximum gc age

---

k8s/crds/kops.k8s.io_clusters.yaml
k8s/crds/kops.k8s.io_instancegroups.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

fixes #16317 
i hope i added these correctly. tried to follow these docs: https://github.com/kubernetes/kops/blob/master/docs/contributing/api_updates.md#adding-a-field

feat: added image minimum and maximum gc age

---

pkg/model/awsmodel/api_loadbalancer.go
pkg/model/awsmodel/bastion.go
upup/pkg/fi/cloudup/awstasks/network_load_balancer.go

They are not needed, they were only used for dependency ordering (and
we now have that dependency on the split out listener task)

refactor: Drop TargetGroups from NetworkLoadBalancer task

---

tests/e2e/pkg/tester/tester.go

Fixes a panic during karpenter e2e tests introduced by https://github.com/kubernetes/kops/pull/16176
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-karpenter/1754176571796623360
```
I0204 16:34:13.468238   14042 tester.go:75] Adding --host=https://api-e2e-e2e-kops-aws-karp-3r2ait-3bb67354234fd44a.elb.eu-central-1.amazonaws.com/
I0204 16:34:14.085494   14042 tester.go:158] Setting --provider=aws
I0204 16:34:14.808979   14042 tester.go:177] Setting --gce-zone=eu-central-1a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2e280fd]
goroutine 1 [running]:
k8s.io/kops/tests/e2e/pkg/tester.(*Tester).addNodeIG(0xc000c6f260)
/home/prow/go/src/k8s.io/kops/tests/e2e/pkg/tester/tester.go:202 +0xbd …
```

Dont set -num-nodes on karpenter-managed clusters

---

docs/networking/aws-vpc.md
docs/operations/images.md
docs/releases/1.29-NOTES.md

Following merge of #16313, Amazon VPC CNI is now compatible with Ubuntu 22.04, thus we can remove the warnings across the code.
/cc @hakman
/cc @rifelpet
Hey folks!
I took the liberty of removing the note from 1.29 release notes as well, since it's still in alpha and doesn't have a release branch yet, I hope that's okay.
Also- let me know if ya'll think it's worth backporting #16313 to 1.27 and 1.28 release branches, and I can take care of that.
Thanks! :pray:

docs: Remove warning about Amazon VPC CNI not being compatible with Ubuntu 22.04

---

nodeup/pkg/model/containerd.go
nodeup/pkg/model/tests/containerdbuilder/complex/tasks.yaml
nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml

When we set `LimitNOFILE` to `infinity` things break .. for example the nfs based tests in kubernetes harness:
https://testgrid.k8s.io/amazon-ec2-al2023#ci-kubernetes-e2e-al2023-aws-canary&width=20
Also see https://github.com/containerd/containerd/pull/9660 which points to more things that are likely to break with `infinity` https://github.com/containerd/containerd/pull/8924#issuecomment-1903629621

Set LimitNOFILE to 1048576 instead of `infinity`

---

tests/e2e/scenarios/aws-lb-controller/run-test.sh

Hoping to fix these tests: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-aws-load-balancer-controller/1755828286962798592
The test failures seem to be using the wrong kubeconfig settings, potentially using the "in cluster" config of the prow job pod itself.
This explicitly sets KUBECONFIG so that the ginkgo tests will use the kops cluster's admin credentials 
ref: https://kubernetes.slack.com/archives/C8MKE2G5P/p1707502477184889?thread_ts=1707242089.155659&cid=C8MKE2G5P

Set KUBECONFIG for LBC's ginkgo tests

---

cloudmock/aws/mockautoscaling/tags.go
cloudmock/aws/mockelbv2/tags.go
cloudmock/aws/mockelbv2/targetgroups.go
cloudmock/aws/mockroute53/records.go

We're trying to pass more contexts around, but we need the mocks to
support the context forms of the methods.

clockmock: Add more methods that take a context

---

tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/new_cluster.go
upup/pkg/fi/cloudup/new_cluster_test.go

Fixes https://github.com/kubernetes/kops/issues/16336
This is needed because setting the bastion public name field depends on the DNS topology.
We were incorrectly setting bastion.publicName for dns=none clusters because the dns=none field wasn't yet set on the cluster.

Move DNS topology setup earlier in cluster creation

---

pkg/apis/kops/validation/aws_test.go

Not critical, but it was troubling the linter.

Cleanup import of the same package in tests

---

pkg/apis/kops/validation/validation.go
pkg/apis/kops/validation/validation_test.go

We allowed this previously, so this is a regression for existing clusters.
These clusters are not obviously broken, and the
kube-controller-manager (for example) will exclude the service range
when issuing node CIDRs.  As such, remove validation until we can
determine if anything is actually broken by an overlap (and a path
forwards if so).
Issue #16340

validation: Allow overlap of pod/node CIDR and service CIDR

---

tests/integration/update_cluster/minimal-dns-none/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-dns-none/data/aws_s3_object_minimal.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_hetzner/data/aws_s3_object_minimal.example.com-addons-coredns.addons.k8s.io-k8s-1.12_content
upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/template_functions.go

Ref: https://github.com/kubernetes/kops/pull/16335#issuecomment-1937413388

Include /etc/hosts coredns mounts for dns=none clusters

---

nodeup/pkg/model/networking/amazon-vpc-routed-eni.go
nodeup/pkg/model/packages.go

Related to issue : https://github.com/kubernetes/kops/issues/16333
based on the changes in the EKS AMI: 
https://github.com/awslabs/amazon-eks-ami/blob/976fe67e4c359737be71d892a8f55015cc1475f5/scripts/install-worker.sh#L86-L105

Add support for AL2023 AMI to use Amazon VPC CNI

---

docs/addons.md
docs/releases/1.28-NOTES.md
docs/releases/1.29-NOTES.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template

New attempt to fix: https://github.com/kubernetes/kops/issues/14561
(From: https://github.com/kubernetes/kops/pull/14562)

 If specified, posts event data to URL upon instance interruption action. 

---

cloudmock/aws/mockelb/tags.go
cloudmock/aws/mockelbv2/targetgroups.go
pkg/resources/aws/aws.go
upup/pkg/fi/cloudup/awstasks/targetgroup.go
upup/pkg/fi/cloudup/awsup/elbv2_targetgroups.go

This sets us up to support multiple generations of target groups,
needed if we want to support adding SecurityGroups to the NLB.

target group: refactor discovery into awsup

---

upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/awstasks/egressonlyinternetgateway_test.go
upup/pkg/fi/cloudup/awstasks/elastic_ip_test.go
upup/pkg/fi/cloudup/awsup/aws_apitarget.go
upup/pkg/fi/cloudup/azure/azure_apitarget.go
upup/pkg/fi/cloudup/do/api_target.go
upup/pkg/fi/cloudup/gce/gce_apitarget.go
upup/pkg/fi/cloudup/gcetasks/serviceaccount_test.go
upup/pkg/fi/cloudup/hetzner/api_target.go
upup/pkg/fi/cloudup/openstack/apitarget.go
upup/pkg/fi/cloudup/scaleway/api_target.go
upup/pkg/fi/cloudup/terraform/target.go
upup/pkg/fi/context.go
upup/pkg/fi/default_methods.go
upup/pkg/fi/deletions.go
upup/pkg/fi/dryrun_target.go
upup/pkg/fi/nodeup/install/install_target.go
upup/pkg/fi/nodeup/local/local_target.go
upup/pkg/fi/target.go

Deletion processing is not entirely a factor of the target, it is more
a factor of our mode of execution (dry-run vs pre-rolling-update vs
post-rolling-update).  We want to introduce that post-rolling-update
phase, so introduce the DeletionProcessingMode enum and move it from
the target to the context.

refactor: Introduce DeletionProcessingMode

---

cloudmock/aws/mockautoscaling/attach.go
cmd/kops/update_cluster.go
docs/cli/kops_update_cluster.md
pkg/instancegroups/instancegroups.go
pkg/model/awsmodel/api_loadbalancer.go
pkg/model/awsmodel/autoscalinggroup.go
pkg/model/awsmodel/bastion.go
pkg/model/awsmodel/spotinst.go
pkg/resources/aws/aws.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/dnsname.go
upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
upup/pkg/fi/cloudup/awstasks/networkloadbalancer_attributes.go
upup/pkg/fi/cloudup/awstasks/networkloadbalancerlistener.go
upup/pkg/fi/cloudup/awstasks/securitygroup.go
upup/pkg/fi/cloudup/awstasks/subnet.go
upup/pkg/fi/cloudup/awstasks/targetgroup.go
upup/pkg/fi/cloudup/awstasks/vpc.go
upup/pkg/fi/cloudup/awsup/aws_cloud.go
upup/pkg/fi/cloudup/awsup/aws_utils.go
upup/pkg/fi/cloudup/awsup/elbv2_targetgroups.go
upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
upup/pkg/fi/cloudup/awsup/tags.go
upup/pkg/fi/cloudup/openstacktasks/securitygroup.go
upup/pkg/fi/default_methods.go
upup/pkg/fi/deletions.go
upup/pkg/fi/dryrun_target.go
upup/pkg/fi/topological_sort.go

This lets us safely make changes to otherwise immutable fields, in
particular for adding security groups to NLBs created without them.
We detect the older versions, and create deletion tasks to remove
them.  These tasks can be deferred, and we expect them to be
deferred to a "prune" phase that runs after cluster apply.

Generate revisions of NLB objects, and introduce cleanup phase

---

util/pkg/vfs/context.go

This is a fix for the functionality added in https://github.com/kubernetes/kops/pull/16050.
In some cases, kops was unable to query the GCP API to retrieve the bucket IAM policy. 
The API would return a 403 Forbidden. 
e.g.
```
Error: error building tasks: checking if bucket was public: googleapi: Error 403: Access denied., forbidden
```
This PR increases the auth scopes that the GCS client is created with to resolve the permission problem
Strangely this 403 error did not happen until kops was authenticating to GCS using a Service Account created in a different GCP project than where the OIDC Issuer bucket was created.

gce: Update GCE storage service scope to DevstorageFullControlScope to resolve permission error.

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

This should fix some "missing zone" errors on these upgrade tests. Newer kops versions default to --dns=none.
Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-upgrade-k126-ko128-to-k127-kolatest/1758945690790137856

Set --dns=none on upgrade tests from older kops versions

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

Followup to https://github.com/kubernetes/kops/pull/16360
```
bash-5.2$ if [[ "foo.tests-kops-aws.k8s.io" == "*tests-kops-aws.k8s.io" ]]; then echo true; fi
bash-5.2$ if [[ "foo.tests-kops-aws.k8s.io" == *"tests-kops-aws.k8s.io" ]]; then echo true; fi
true
```
/cc @hakman

Fix bash conditional pattern matching in upgrade script

---

.devcontainer/devcontainer.json
.devcontainer/setup.sh

From what I've read, we want the base image to be smaller, with more
of the added functionality in features.  We can build a bigger image
with the features, but that should be an image for devcontainers.
Also it seems that devcontainer tooling will cache the image with the
features - maybe giving similar results to if we had built a more
complete image.

devcontainer: update go version, use features

---

tests/e2e/pkg/tester/skip_regex.go

skipping test due to https://github.com/kubernetes/kops/issues/16349. We're not skipping it in _all_ jobs so that we can still get signal on it in a subset of jobs without dealing with hundreds of failing prow jobs. We also dont have an easy way to only skip for certain distros so we're skipping it for all distros. The easiest way to skip per-distro would be in test-infra's build_jobs.py but this would override all the other behavior in skip_regex.go.
Almost all of these jobs are failing due to this test:
```
curl -SsL https://storage.googleapis.com/k8s-metrics/failures-latest.json | grep -c kops
193
```
Also removing some regexes from old k8s versions we no longer test.
/cc @hakman

Skip known-failing test on most e2e jobs

---

docs/getting_started/aws.md

Minor updates in [docs/getting_started/aws.md](https://github.com/tungbq/kops/blob/master/docs/getting_started/aws.md) by adding a space before the opening parenthesis in "Slack(http://slack.k8s.io/)"
**Current view:**
https://kops.sigs.k8s.io/getting_started/aws/#feedback
**New change from this PR:**

doc/aws: Add space before the k8s slack url

---

tests/e2e/templates/many-addons.yaml.tmpl

All of the many-addons upgrade jobs are failing: https://testgrid.k8s.io/kops-upgrades-many-addons
These prow jobs have been migrated to the new cluster and need to use dns=none since the dns zones are in the old cluster's account.
Diffing the working "not many-addons" jobs' [cluster manifest](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-upgrade-kstable-kolatest-to-kci-kolatest/1760784773682302976/artifacts/cluster.yaml) which doesnt use an e2e template, vs the failing [cluster manifest](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-upgrade-kstable-kolatest-to-kci-kolatest-many-addons/1760746520459612160/artifacts/cluster.yaml), shows these fields as the relevant differences. This updates them to match.

Migrate many-addons e2e template to dns=none

---

upup/pkg/fi/cloudup/gcetasks/address.go
upup/pkg/fi/cloudup/gcetasks/forwardingrule.go

We can have the same internal IP address on different subnets, so when
trying to find the cloud resource by IP address, we need to match
considering the subnet when matching internal IP addresses.

gce: match IP addresses including subnet where relevant

---

Makefile

Our submodules should also get auto-updated and auto-tidied by the
Makefile targets; this should then be done automatically by our github
action scheduled task.

chore: update dependencies in submodules

---

tests/e2e/pkg/tester/skip_regex.go

Followup to https://github.com/kubernetes/kops/pull/16373
https://testgrid.k8s.io/kops-misc#e2e-kops-do-calico-fqdn
These DO jobs are also failing the test for the same reason, so skip them for now.

Skip hostname e2e test on digitalocean

---

pkg/model/gcemodel/context.go
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf

/cc @rifelpet @justinsb 
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/16381/pull-kops-kubernetes-e2e-ubuntu-gce-build/1761600343730294784/build-log.txt
```
I0225 04:26:45.617246   84937 executor.go:171] Continuing to run 1 task(s)
I0225 04:26:55.617745   84937 executor.go:113] Tasks: 71 done / 75 total; 1 can run
W0225 04:26:55.643080   84937 executor.go:141] error running task "HealthCheck/api-e2e-pr16381-pull-kops-kubernetes-e2e-ubuntu-gce-build-k8s-local" (2m17s remaining to succeed): error listing Health Checks: googleapi: Error 400: Invalid value for field 'healthCheck': 'api-e2e-pr16381-pull-kops-kubernetes-e2e-ubuntu-gce-build-k8s-local'. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}', invalid
```

gce: Limit health check names to 63 chars

---

pkg/model/gcemodel/context.go
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf

/cc @justinsb @rifelpet 
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/16363/pull-kops-kubernetes-e2e-ubuntu-gce-build/1761774440057671680/build-log.txt
```
I0225 15:56:30.290869   85974 executor.go:171] Continuing to run 1 task(s)
I0225 15:56:40.291710   85974 executor.go:113] Tasks: 72 done / 75 total; 1 can run
W0225 15:56:40.361587   85974 executor.go:141] error running task "BackendService/api-e2e-pr16363-pull-kops-kubernetes-e2e-ubuntu-gce-build-k8s-local" (4m57s remaining to succeed): error listing Backend Services: googleapi: Error 400: Invalid value for field 'backendService': 'api-e2e-pr16363-pull-kops-kubernetes-e2e-ubuntu-gce-build-k8s-local'. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}', invalid
```

gce: Limit backend names to 63 chars

---

nodeup/pkg/model/nvidia.go

The NVIDIA Container Toolkit packaging has been simplified to produce a single deb (or rpm) package. This means that the URL is no longer distribution dependent and the stable/deb repository path is used instead.
See https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt

Update NVIDIA Container Toolkit URL

---

cmd/kops/toolbox_dump.go

This way if one of the earlier methods fails, we can still get some artifacts from the later methods
Should help with troubleshooting this e2e failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-aws-load-balancer-controller/1762834387029725184
```
I0228 14:03:05.653189   14058 dumplogs.go:51] /tmp/kops.bVBE86uZS toolbox dump --name e2e-4342699135-9b4dd.tests-kops-aws.k8s.io --dir /logs/artifacts --private-key /tmp/kops/e2e-4342699135-9b4dd.tests-kops-aws.k8s.io/id_ed25519 --ssh-user ubuntu
W0228 14:03:45.930637   14081 toolbox_dump.go:181] error listing nodes in cluster: Get "https://api-e2e-4342699135-9b4dd--6fmnhp-2386d72d5d112597.elb.eu-west-1.amazonaws.com/api/v1/nodes": dial tcp 54.195.97.121:443: i/o timeout
2024/02/28 14:03:45 starting to dump 0 nodes fetched …
```

Continue attemps to dump artifacts in `toolbox dump`

---

hack/boilerplate/boilerplate.py

Sync up with upstream https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.py
We want to pick up the new-style go:build tags.

chore: update boilerplate.py to recognize new build tags

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

In our upgrade-ab tests, we might be making non-trivial cloud
infrastructure changes, such as waiting for a new load balancer.
Add a `kops validate cluster` step to wait for those changes to be
applied.

e2e tests: When upgrading, wait for the new configuration

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml

Cherry pick of #16174 on release-1.28.
#16174: Bump metrics-server to 0.6.4
```release-note
```

Automated cherry pick of #16174: Bump metrics-server to 0.6.4

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #16177 on release-1.28.
#16177: bump cert manager to 1.12.7
```release-note
```

Automated cherry pick of #16177: Bump cert manager to 1.12.7

---

go.mod
go.sum
upup/pkg/fi/cloudup/openstack/instance.go
upup/pkg/fi/cloudup/openstack/verifier.go
vendor/github.com/go-viper/mapstructure/v2/.editorconfig
vendor/github.com/go-viper/mapstructure/v2/.envrc
vendor/github.com/go-viper/mapstructure/v2/.gitignore
vendor/github.com/go-viper/mapstructure/v2/.golangci.yaml
vendor/github.com/go-viper/mapstructure/v2/CHANGELOG.md
vendor/github.com/go-viper/mapstructure/v2/LICENSE
vendor/github.com/go-viper/mapstructure/v2/README.md
vendor/github.com/go-viper/mapstructure/v2/decode_hooks.go
vendor/github.com/go-viper/mapstructure/v2/error.go
vendor/github.com/go-viper/mapstructure/v2/flake.lock
vendor/github.com/go-viper/mapstructure/v2/flake.nix
vendor/github.com/go-viper/mapstructure/v2/mapstructure.go
vendor/github.com/go-viper/mapstructure/v2/reflect_go1_19.go
vendor/github.com/go-viper/mapstructure/v2/reflect_go1_20.go
vendor/modules.txt

Update mapstructure with a maintained fork.
See:
- https://github.com/mitchellh/mapstructure/issues/349

Use github.com/go-viper/mapstructure/v2

---

pkg/model/awsmodel/api_loadbalancer.go
tests/integration/update_cluster/complex/kubernetes.tf

We dropped the security group rules for this when moving to NLB
security groups; add them back.
Issue #16024

aws: Expose port 8443 when using NLB with a custom certificate

---

pkg/model/awsmodel/api_loadbalancer.go
tests/integration/update_cluster/complex/kubernetes.tf

Cherry pick of #16403 on release-1.28.
#16403: aws: expose port 8443 when using NLB with a custom
```release-note
```

Cherry pick of #16403: aws: expose port 8443 when using NLB with a custom

---

docs/releases/1.29-NOTES.md
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-gcp-pd-csi-driver.addons.k8s.io-k8s-1.23_content
upup/models/cloudup/resources/addons/gcp-pd-csi-driver.addons.k8s.io/k8s-1.23.yaml.template

This change updates the default `StorageClass` to be `balanced-csi` on GCP clusters. 
Balanced persistent disk type is the default set on GKE clusters.
I've updated the release notes with the breaking change, as discussed in the office hours call last year. LMK if there is anywhere else that needs updating.

gce: Change default storage class to balanced-csi

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Continuing with https://github.com/kubernetes/kops/issues/16177, included more CVE fixes.

upgraded cert-manager to 1.12.9

---

pkg/model/components/addonmanifests/certmanager/iam.go

This change restricts which record types and domain prefixes cert-manager is allowed to change for DNS01 acme challenges.
Only `_acme-challenge.*` TXT records may be created/updated/removed.
Implements kubernetes/kops#15680
I ran `make all examples test` and it compiles, but beyond that I have not created any tests for this (knowledge of go is ankle deep) so I hope someone is kind enough to help me out and add that :-)

aws/cert-manager: Tighten IAM permissions for cert-manager

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa23/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #16410 on release-1.28.
#16410: upgraded cert-manager to 1.12.9
```release-note
```

Automated cherry pick of #16410: upgraded cert-manager to 1.12.9

---

pkg/model/components/addonmanifests/certmanager/iam.go

Cherry pick of #16412 on release-1.29.
#16412: aws/cert-manager: Tighten IAM permissions for cert-manager
```release-note
```

Automated cherry pick of #16412: aws/cert-manager: Tighten IAM permissions for cert-manager

---

pkg/nodemodel/wellknownassets/containerd.go
pkg/nodemodel/wellknownassets/containerd_test.go
pkg/nodemodel/wellknownassets/crictl.go
pkg/nodemodel/wellknownassets/crictl_test.go
pkg/nodemodel/wellknownassets/nerdctl.go
pkg/nodemodel/wellknownassets/runc.go
pkg/nodemodel/wellknownassets/runc_test.go
upup/pkg/fi/cloudup/apply_cluster.go

This refactoring will split nodeup configuration out of cloudup, to
enable us to generate a nodeup configuration more easily, for example
in kops-controller.  That in turn will allow more dynamic usage with
e.g. cluster-api

refactor: move assets into their own package

---

cmd/kops/create_cluster.go
upup/pkg/fi/cloudup/awsup/aws_authenticator.go
upup/pkg/fi/cloudup/awsup/aws_utils.go
upup/pkg/fi/cloudup/awsup/aws_utils_test.go
upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
upup/pkg/fi/cloudup/utils.go
upup/pkg/fi/nodeup/nodetasks/prefix.go

Migrate IMDS, command completion, and region validation to aws-sdk-go-v2

---

clusterapi/bootstrap/controllers/kopsconfig_controller.go
pkg/assets/builder.go
pkg/assets/mirrored_asset.go
pkg/assets/mirrors.go
pkg/commands/toolbox_enroll.go
pkg/model/bootstrapscript.go
pkg/model/bootstrapscript_test.go
pkg/model/openstackmodel/servergroup_test.go
pkg/model/resources/nodeup.go
pkg/nodemodel/fileassets.go
pkg/nodemodel/nodeupconfigbuilder.go
pkg/nodemodel/wellknownassets/kopsassets.go
pkg/nodemodel/wellknownassets/kopsassets_test.go

This seems logically coherent, and is part of the work to start using
compiled-in hashes for most well-known assets.

chore: refactor MirroredAsset into assets

---

cloudmock/aws/mockiam/iaminstanceprofile.go
cloudmock/aws/mockiam/iamrole.go
cloudmock/aws/mockiam/oidcprovider.go
go.mod
pkg/model/awsmodel/iam.go
pkg/resources/aws/aws.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/awstasks/iaminstanceprofile.go
upup/pkg/fi/cloudup/awstasks/iaminstanceprofilerole.go
upup/pkg/fi/cloudup/awstasks/iamrole.go
upup/pkg/fi/cloudup/awstasks/iamrolepolicy.go
upup/pkg/fi/cloudup/awsup/aws_cloud.go
upup/pkg/fi/cloudup/awsup/aws_utils.go
upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go

Ref: https://github.com/kubernetes/kops/issues/16424
Addresses some post-merge feedback in https://github.com/kubernetes/kops/pull/16435 and a few other issues I've found.
/cc @hakman

Various aws-sdk-go-v2 fixes

---

pkg/model/iam/iam_builder.go
tests/e2e/pkg/tester/skip_regex.go
upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template

@hakman for review
Changes:
* Bump kube-router version to v2.1.0 from v1.6.0
* Enable hairpin mode for kube-router by default - From the e2e tests this seems to be expected functionality of a CNI
* Add the runtime endpoint into the container so that user's are able to utilize DSR functionality
* Mount `/etc/iproute2/rt_tables` into the container as well which is used by kube-router to configure source routing for DSR
* Add `hostPID: true` functionality for DSR
* Add environment var `POD_NAME` so that user's can easily enable load-balancing mode for kube-router
* Add additional RBAC for the following:
* leases / services/status - For loadbalancer controller which can be optionally enabled
* endpointslices - This is needed in kube-router v2.X and on so that kube-router is able to handle …

Update kube-router to v2.1.0

---

pkg/model/iam/iam_builder.go
tests/e2e/pkg/tester/skip_regex.go
upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template

Cherry pick of #16440 on release-1.29.
#16440: k8s-1.12.yaml.template: update kube-router
```release-note
```

Automated cherry pick of #16440: Update kube-router to v2.1.0

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.25_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.25_content
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.25.yaml.template

Cherry pick of #16363 on release-1.29.
#16363: Update Calico to v3.27.3
```release-note
```

Automated cherry pick of #16363: Update Calico to v3.27.3

---

cmd/kops-controller/main.go
pkg/nodeidentity/aws/identify.go
protokube/pkg/gossip/aws/seeds.go
protokube/pkg/protokube/aws_volume.go

Ref: https://github.com/kubernetes/kops/issues/16424
These use the EC2 clients, but not the awsup.AWSCloud so I'm getting these out of the way first.

Migrate node controller and identity to aws-sdk-go-v2

---

dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go

This has similar behavior to awsup.ValidateRegion where we dont have access to a kops.Cluster to determine its region.
This is only needed in the dnsprovider client initialized in the kops CLI for creating the placeholder records - it wont be used on control plane nodes because LoadDefaultConfig will query IMDS for the node's region.
This isn't needed for all other usage of awsconfig.LoadDefaultConfig() because the region is known, for example in awsup.NewAWSCloud().
In any other partitions where us-east-1 is not appropriate, the user will already be specifying a region in their ~/.aws/config or via env var.
Fixes a regression from https://github.com/kubernetes/kops/pull/16448
ref: https://github.com/kubernetes/kops/pull/16363#issuecomment-2031069155

Provide default region to route53 client

---

upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template

FYI @hakman 
* Updates the kube-router init container to also be v2.1.0 which is latest at this point
* Adds the service Cluster IP range from the kops configuration so that cluster IPs can be ingressed to the node and then later be processed by NetworkPolicy

kube-router: fix version and cluster ip range

---

upup/pkg/fi/nodeup/command.go

in case nodeupConfig is local and ConfigStore is not set.

nodeup: error message instead of segfault

---

upup/pkg/fi/cloudup/azure/verifier.go

Cherry pick of #16469 on release-1.28.
#16469: azure: Use lowercase for node names
```release-note
```

Cherry pick of #16469: azure: Use lowercase for node names

---

upup/pkg/fi/cloudup/azure/verifier.go

Cherry pick of #16469 on release-1.29.
#16469: azure: Use lowercase for node names
```release-note
```

Automated cherry pick of #16469: azure: Use lowercase for node names

---

upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template

Cherry pick of #16467 on release-1.29.
#16467: k8s-1.12.yaml.template: update kube-router init container
```release-note
```

Automated cherry pick of #16467: k8s-1.12.yaml.template: update kube-router init container

---

pkg/model/awsmodel/iam.go
pkg/model/awsmodel/iam_test.go
pkg/zones/wellknown.go
upup/pkg/fi/cloudup/awsup/aws_utils.go

ref: #16424 
The aws-sdk-go-v2 package does not provide a static list of regions or partitions in order to support forwards compatibility with future regions via regex matching:
https://github.com/aws/aws-sdk-go-v2/issues/557#issuecomment-645507739
This replaces the command completion for `kops create cluster --cloud aws --zones ...` with a static list of zones which should be acceptable for now.

Migrate usage of aws-sdk-go/aws/endpoints

---

upup/pkg/fi/cloudup/awsup/aws_authenticator_test.go

We should guard this so we can be confident in it!

tests: add unit test for aws authenticator

---

nodeup/pkg/model/crictl.go
nodeup/pkg/model/nerdctl.go

because multiple crictl binaries are found when you specify containerd packages. The old format containerd packages contain crictl binary.
Fix #16425

Fix getting crictl assets

---

upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template

@hakman 
Bump kube-router version from v2.1.0 -> v2.1.1 and enable hairpin mode in CNI configuration for the bridge plugin. This obviates the need for a hairpin controller inside kube-router which had a lot of unhandled edge cases.

kube-router: bump version v2.1.0 -> v2.1.1

---

Makefile

```bash
$ time(go env | grep GOPATH | cut -f 2 -d '"' | sed 's/ /\\ /g')
/root/go
real    0m0.004s
user    0m0.003s
sys     0m0.004s
$ time(go env GOPATH)
/root/go
real    0m0.003s
user    0m0.003s
sys     0m0.000s
```

chore: optimize the method for obtaining gopath

---

docs/cluster_spec.md

This PR updates the `fileAssets` section in the documentation to clarify the usage of `ControlPlane`. It also adds a note about the behavior in kOps versions prior to 1.26 to help users with backward compatibility concerns.

chore: update fileAssets documentation

---

k8s/crds/kops.k8s.io_clusters.yaml
nodeup/pkg/model/tests/golden/audit/cluster.yaml
nodeup/pkg/model/tests/golden/audit/tasks-kube-apiserver.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/validation/validation.go
pkg/apis/kops/validation/validation_test.go

this PR will add possibility to use `--authentication-config` flag for apiserver
https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3331-structured-authentication-configuration

Support AuthenticationConfig in APIserver

---

pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #16515 on release-1.29.
#16515: Update Cilium to v1.15.4
```release-note
```

Automated cherry pick of #16515: Update Cilium to v1.15.4

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa24/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-metrics-server.addons.k8s.io-k8s-1.11_content
upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/metrics-server.addons.k8s.io-k8s-1.11.yaml

Cherry pick of #16518 on release-1.29.
#16518: Update metrics-server to v0.7.1
```release-note
```

Automated cherry pick of #16518: Update metrics-server to v0.7.1

---

cmd/kops-controller/main.go
go.mod
nodeup/pkg/model/bootstrap_client.go
upup/pkg/fi/cloudup/awsup/aws_authenticator.go
upup/pkg/fi/cloudup/awsup/aws_authenticator_test.go
upup/pkg/fi/cloudup/awsup/aws_cloud.go
upup/pkg/fi/cloudup/awsup/aws_verifier.go
upup/pkg/fi/cloudup/awsup/aws_verifier_test.go
upup/pkg/fi/nodeup/command.go

Closes https://github.com/kubernetes/kops/issues/16424
From [this comment](https://github.com/kubernetes/kops/issues/16424#issuecomment-2046489720):
[While presigned requests are still supported in V2](https://aws.github.io/aws-sdk-go-v2/docs/migrating/#presigned-requests), the [presign methods and types](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sts#PresignClient) no longer provide access to the request body, only their url and headers. See https://github.com/aws/aws-sdk-go-v2/issues/1137. Kops-controller currently reads the request body to perform some validation:
https://github.com/kubernetes/kops/blob/1c24423d9be20396e62755f6952b415567a56ced/upup/pkg/fi/cloudup/awsup/aws_verifier.go#L153-L157
In V1 the presigned request is a POST however in V2 it is converted to a GET …

Migrate AWS Verifier to aws-sdk-go-v2

---

cloudbuild.yaml

ref: #16533
These were still running on go 1.22.0 and failing because the go.mod version directive now includes patch versions:
https://github.com/kubernetes/kops/blob/02f6b921e1cd03af61e5a0e56ffd3a2c7b4a0d04/go.mod#L3
Should fix these post-submit jobs
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/kops-postsubmit-push-to-staging/1787502731934568448
In the future we'll need to make sure patch updates to the go version also update this file.

Fix postsubmit jobs

---

pkg/model/components/containerd.go
tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.27/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_nodeupconfig-nodes_content

Cherry pick of #16531 on release-1.28.
#16531: Update containerd to v1.7.16
```release-note
```

Automated cherry pick of #16531: Update containerd to v1.7.16

---

tests/e2e/scenarios/aws-ebs-csi/run-test.sh
tests/e2e/scenarios/metrics-server/run-test.sh

This matches the aws-load-balancer-controller scenario script.
Should fix this metrics-server test that began to fail once it started using a kops version that includes metrics-server v0.7.1
https://testgrid.k8s.io/kops-misc#kops-aws-metrics-server

Use addon versions for git repo clone in e2e scenarios

---

docs/operations/images.md
util/pkg/distributions/distributions.go
util/pkg/distributions/identify.go
util/pkg/distributions/identify_test.go
util/pkg/distributions/tests/ubuntu2404/etc/os-release

Cherry pick of #16542 on release-1.29.
#16542: Initial support for Ubuntu 24.04 (Noble Numbat)
```release-note
```

Automated cherry pick of #16542: Initial support for Ubuntu 24.04 (Noble Numbat)

---

.github/workflows/main.yml
.github/workflows/update-deps.yml
cloudbuild.yaml
go.mod
hack/go.mod
tests/e2e/go.mod
tools/otel/traceserver/go.mod

Includes some security fixes, though they don't look likely to impact
us.

Bump golang to 1.22.3

---

tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cas-priority-expander-custom.example.com-addons-bootstrap_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cas-priority-expander-custom.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cas-priority-expander.example.com-addons-bootstrap_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cas-priority-expander.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
upup/pkg/fi/cloudup/template_functions.go
util/pkg/maps/maps.go

Cherry pick of #16556 on release-1.29.
#16556: Use generics in util/pkg/maps
```release-note
```

Automated cherry pick of #16556: cluster-autoscaler: Fix priority expander config

---

tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cas-priority-expander-custom.example.com-addons-bootstrap_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander-custom/data/aws_s3_object_cas-priority-expander-custom.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cas-priority-expander.example.com-addons-bootstrap_content
tests/integration/update_cluster/cluster-autoscaler-priority-expander/data/aws_s3_object_cas-priority-expander.example.com-addons-cluster-autoscaler.addons.k8s.io-k8s-1.15_content
upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
upup/pkg/fi/cloudup/template_functions.go
util/pkg/maps/maps.go

Closes #16546
/cc @rifelpet @zetaab @justinsb

cluster-autoscaler: Fix priority expander config

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go
upup/pkg/fi/cloudup/awsup/aws_utils.go

without this change we got error:
(we have KOPS_AWS_ROLE_ARN=arn:aws:iam::xx:role/yy env defined`
```
% ./kops export kubecfg --admin=87600h
Error: got an error while querying for valid regions (verify your AWS credentials?): operation error EC2: DescribeRegions, https response error StatusCode: 403, RequestID: bee08acb-624f-460d-9a9d-5da92325b6d1, api error UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:iam::xx:user/xx is not authorized to perform: ec2:DescribeRegions because no identity-based policy allows the ec2:DescribeRegions action
```
after this change it works fine
```
% ./kops export kubecfg --admin=87600h     
kOps has set your kubectl context to yyy.k8s.local
```

fix KOPS_AWS_ROLE_ARN assume behaviour

---

.github/workflows/main.yml
.github/workflows/update-deps.yml

- Bump golang to 1.22.3
- tests: use version from go.mod in github actions

tests: use version from go.mod in github actions

---

docs/README.md
docs/cluster_spec.md
docs/operations/service_account_issuer_migration.md

Adds docs for non-disruptive migration of the Service Account Issuer in an existing cluster, as discovered in #16488.
In the future I will update this doc with the same procedure using the kOps official support from #16497, once I have tested it.

add service account issuer migration doc

---

mkdocs.yml

Follow up to #16541. Adds the service account issuer migration doc to the navigation.

fix service account issuer migration doc nav

---

docs/releases/1.29-NOTES.md
docs/releases/1.30-NOTES.md

Remove the "not yet released" note from 1.29, create the 1.30 placeholder.

docs: Update release notes to reflect release of 1.29

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go

https://github.com/aws/aws-sdk-go-v2/pull/1576 introduced support for the experimental Adaptive retry mode to the SDK.
> The adaptive retryer expands on the exponential backoff retry strategies of the Standard mode, adding client attempt rate limiting based on throttle responses received from an API.
This may help fix the Scalability tests that are now failing:
https://testgrid.k8s.io/sig-scalability-aws#ec2-master-scale-performance
> instance:i-06b9c1de0b89a3499	error deleting resources, will retry: error terminating instances: operation error EC2: TerminateInstances, failed to get rate limit token, retry quota exceeded, 0 available, 5 requested
/cc @dims @hakuna-matatah @rifelpet @zetaab

aws: Experiment with Adaptive retry mode

---

docs/operations/images.md

Now there is an official Debian 12 images on AWS

[DOCS] Add docs for Debian 12 on AWS

---

upup/pkg/fi/cloudup/awstasks/warmpool.go

Fixes: https://github.com/kubernetes/kops/issues/16582
When creating a new ASG with a Warmpool using Lifecycle hooks, the instances that first join the Warmpool when the ASG is created could come up before the Lifecycle hook is in effect.
This can lead to problems such as those instances not calling the Lifecycle hook notification when pressed into service, causing the ASG to terminate them approximately 10 mins after they've been performing work in the cluster.
Setting a dependency on for the Warmpool to take into account any Lifecycle hooks means that the Warmpool won't be created until the hooks are ready.

Make ASG Warmpool depend on ASG Lifecycle hook

---

upup/pkg/fi/cloudup/awstasks/warmpool.go

Cherry pick of #16583 on release-1.29.
#16583: Make ASG Warmpool depend on ASG Lifecycle hook
```release-note
```

Automated cherry pick of #16583: Make ASG Warmpool depend on ASG Lifecycle hook

---

k8s/crds/kops.k8s.io_clusters.yaml
nodeup/pkg/model/kube_controller_manager.go
nodeup/pkg/model/kube_scheduler.go
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
tests/integration/update_cluster/complex/data/aws_launch_template_master-us-test-1a.masters.complex.example.com_user_data
tests/integration/update_cluster/complex/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/complex/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
tests/integration/update_cluster/complex/in-v1alpha2.yaml

Add ability to define custom resources for `kube-controller-manager` and `kube-scheduler`
fixes #16604

feat(components): permit to define kube-controller-manager and kube-scheduler resources

---

k8s/crds/kops.k8s.io_clusters.yaml
nodeup/pkg/model/kube_controller_manager.go
nodeup/pkg/model/kube_scheduler.go
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
tests/integration/update_cluster/complex/data/aws_launch_template_master-us-test-1a.masters.complex.example.com_user_data
tests/integration/update_cluster/complex/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/complex/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
tests/integration/update_cluster/complex/in-v1alpha2.yaml

Cherry pick of #16605 on release-1.29.
#16605: feat(components): permit to define kube-controller-manager
```release-note
```

Automated cherry pick of #16605: feat(components): permit to define kube-controller-manager

---

tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-authentication.aws-k8s-1.12_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/manifest.yaml

Temporary workaround for https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/723
Closes #16602
This should unblock the 1.30 beta release

Update aws-iam-authenticator image

---

tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-authentication.aws-k8s-1.12_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-bootstrap_content
upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/manifest.yaml

Cherry pick of #16615 on release-1.29.
#16615: Update aws-iam-authenticator image
```release-note
```

Automated cherry pick of #16615: Update aws-iam-authenticator image

---

nodeup/pkg/model/packages.go

Fixes this nodeup error:
https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-distro-rocky9/1802047093284540416/artifacts/3.26.188.59/journal.log
```
Jun 15 18:47:13.329504 i-02b399f4c3616e238.ap-southeast-2.compute.internal nodeup[966]: I0615 18:47:13.329292     966 executor.go:113] Tasks: 178 done / 195 total; 1 can run
Jun 15 18:47:13.329504 i-02b399f4c3616e238.ap-southeast-2.compute.internal nodeup[966]: I0615 18:47:13.329345     966 executor.go:214] Executing task "Package/libcgroup": Package: libcgroup
Jun 15 18:47:13.329504 i-02b399f4c3616e238.ap-southeast-2.compute.internal nodeup[966]: I0615 18:47:13.329449     966 package.go:216] Listing installed packages: /usr/bin/rpm -q libcgroup --queryformat %{NAME} %{VERSION}
Jun 15 18:47:13.336257 …
```

Dont install libcgroup on Rocky 9

---

upup/pkg/fi/cloudup/new_cluster.go

If we check this later, in some code-paths we can only panic (because
some code paths assume this check has already been done)

Raise errors earlier if we cannot parse the kube version

---

pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #16627 on release-1.29.
#16627: Upgrade cilium to v1.15.6
```release-note
```

Automated cherry pick of #16627: Upgrade cilium to v1.15.6

---

.github/workflows/depsreview.yaml
.github/workflows/main.yml
.github/workflows/tag-release.yml
.github/workflows/update-deps.yml

See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#standard-github-hosted-runners-for-public-repositories

Bump Github Actions jobs to latest distros

---

docs/contributing/index.md
docs/operations/etcd_backup_restore_encryption.md

There is 2 link is broken(404) in the docs.
> https://github.com/kubernetes/community/blob/master/communication.md#social-media
> https://github.com/kubernetes-sigs/etcdadm/etcd-manager
update to:
> https://github.com/kubernetes/community/tree/master/communication#slack
> https://github.com/kubernetes-sigs/etcdadm/tree/master/etcd-manager

Fix 2 broken links in the docs

---

tests/e2e/pkg/tester/skip_regex.go

ref: #16637
Followup to https://github.com/kubernetes/test-infra/pull/32885
A handful of test cases are failing so we can just skip them for as long as these older upgrade jobs still exist

Skip failing tests on older upgrade jobs migrated to EKS

---

go.mod
hack/go.mod
tests/e2e/go.mod
tools/otel/traceserver/go.mod

Cherry pick of #16649 on release-1.30.
#16649: chore: update golang to 1.22.5
```release-note
```

Automated cherry pick of #16649: chore: update golang to 1.22.5

---

cmd/kops/update_cluster.go
examples/kops-api-example/apply.go
pkg/instancegroups/instancegroups.go
upup/pkg/fi/cloudup/apply_cluster.go

By having an explicit return value, we set ourselves up for better reuse.

refactor: ApplyClusterCmd clearly returns results

---

pkg/model/components/addonmanifests/remap.go
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

refactor: use types.NamespacedName for map of serviceAccounts

---

util/pkg/vfs/s3fs.go

This is useful if we want to build an AWSCloud instance for the S3
bucket, rather than where we are installing resources.

refactor: allow access to S3 bucket region

---

cloudbuild.yaml
go.mod

Also add a note for future updates to keep these in sync
Alternative to https://github.com/kubernetes/kops/pull/16660
/cc @upodroid @hakman

Bump cloudbuild to go 1.22.5

---

upup/pkg/fi/cloudup/template_functions.go

We were iterating over a map which has undefined ordering, resulting in inconsistent diffs to the manifest during `kops update cluster`. We now sort the instsance groups to ensure the rendered manifest remains consistent.
Closes #16664

Fix cluster-autoscaler priority expander config

---

upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #16670 on release-1.30.
#16670: Fix cluster-autoscaler priority expander config
```release-note
```

Automated cherry pick of #16670: Fix cluster-autoscaler priority expander config

---

tests/e2e/pkg/tester/skip_regex.go

Fixed in https://github.com/kubernetes/kubernetes/pull/126088
Ref: https://github.com/kubernetes/kubernetes/issues/121018

Stop skipping hostNetwork hostname e2e test

---

tests/e2e/kubetest2-kops/deployer/build.go
tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/kubetest2-kops/deployer/down.go
tests/e2e/kubetest2-kops/deployer/up.go
tests/e2e/kubetest2-kops/gce/gcs.go

Cherry pick of #15981 on release-1.28.
#15981: create a dedicated staging bucket for kops builds
```release-note
```

Automated cherry pick of #15981: create a dedicated staging bucket for kops builds

---

upup/pkg/fi/cloudup/awsup/aws_authenticator_test.go

This ensures the unit tests pass when the current UTC date differs from the local timezone's date.
Example failure:
```
--- FAIL: TestCreateTokenV2 (0.00s)
aws_authenticator_test.go:266: decoded: &{URL:https://sts.us-east-1.amazonaws.com/?Action=GetCallerIdentity&Version=2011-06-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=fakeaccesskey%2F20240718%2Fus-east-1%2Fsts%2Faws4_request&X-Amz-Date=20240718T012100Z&X-Amz-SignedHeaders=host%3Bx-kops-request-sha&X-Amz-Signature=7a851e423b5697c72a68286848c43ef68cfccbb01e46ab96a25cfb63d9e88c6d Method:GET SignedHeader:map[Host:[sts.us-east-1.amazonaws.com] X-Kops-Request-Sha:[2dhlzFTsYGePGxGQhK15rn+TV9HEUZxkV94zFLf7uoo]]}
aws_authenticator_test.go:335: unexpected amzCredential: got "fakeaccesskey/20240718/us-east-1/sts/aws4_request", want …
```

Use UTC for AWS token tests

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/networking.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/in-v1alpha2.yaml
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template

Fixes #16679
For the new field's json struct tag in v1alpha2, note that I didn't use the `Name` suffix that `imageName` and `initImageName` have. I figure the new field can be consistent with the other v1alpha3 fields but if anyone objects I'm happy to change it to `networkPolicyAgentImageName`.

Add new API field for VPC CNI's network policy agent image

---

cloudbuild.yaml
go.mod

Cherry pick of #16661 on release-1.30.
#16661: Bump cloudbuild to go 1.22.5
```release-note
```

Automated cherry pick of #16661: Bump cloudbuild to go 1.22.5

---

tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/in-v1alpha2.yaml
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template

Cherry pick of #16682 on release-1.30.
#16682: Add the hubble-metrics service for cilium
```release-note
```

Automated cherry pick of #16682: Add the hubble-metrics service for cilium

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/networking.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/in-v1alpha2.yaml
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template

Cherry pick of #16681 on release-1.29.
#16681: Add new API field for VPC CNI's network policy agent
```release-note
```

Automated cherry pick of #16681: Add new API field for VPC CNI's network policy agent

---

pkg/model/components/apiserver.go
pkg/model/components/kubecontrollermanager.go
pkg/model/components/kubelet.go
pkg/model/components/kubescheduler.go

possible Fix for CI job failures:
```
E0725 12:16:22.804670   27684 run.go:72] "command failed" err="failed to set feature gates from initial flags-based config: unrecognized feature gate: InTreePluginAWSUnregister"
```
k8s cleanup PR for some feature gates:
https://github.com/kubernetes/kubernetes/pull/124815/files

Drop InTreePluginAWSUnregister feature gate for k8s 1.31 and above

---

tests/integration/update_cluster/ha_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/ha_gce/in-v1alpha2.yaml
tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/in-v1alpha2.yaml
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_ilb/in-v1alpha2.yaml
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/in-v1alpha2.yaml
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_longclustername/in-v1alpha2.yaml
tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_plb/in-v1alpha2.yaml
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_private/in-v1alpha2.yaml
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf

test: Fix rendering of cloudConfig.gceServiceAccount

---

pkg/model/components/apiserver.go
pkg/model/components/kubecontrollermanager.go
pkg/model/components/kubelet.go
pkg/model/components/kubescheduler.go

These BuildOptions methods are ran repeatedly, and the old `else` condition caused the contents of the map to alternate between the feature gate being present and removed.
[Example failure](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/16701/presubmit-kops-aws-scale-amazonvpc-using-cl2/1817026530975420416)
```
I0727 02:47:00.991757   52038 up.go:219] /home/prow/go/src/k8s.io/kops/_rundir/9d9f923e-e44a-48ab-9cfd-aa28cfd2e9e2/kops create cluster --name e2e-ff02749ef8-a423a.test-cncf-aws.k8s.io --cloud aws --kubernetes-version v1.31.0-beta.0 --ssh-public-key /tmp/kops/e2e-ff02749ef8-a423a.test-cncf-aws.k8s.io/id_ed25519.pub --set cluster.spec.nodePortAccess=0.0.0.0/0 --set spec.containerd.configAdditions=plugins."io.containerd.grpc.v1.cri".containerd.runtimes.test-handler.r …
```

Fix InTreePluginAWSUnregister feature gate removal in 1.31

---

tests/e2e/scenarios/scalability/run-test.sh

Want to test 1.31.beta to see if it works on AWS.

test: Use latest K8s build for scale tests

---

cmd/kops-controller/controllers/awsipam.go
cmd/kops-controller/controllers/gceipam.go

Breaking down the metal support into bite-sized chunks.

refactor: support multiple podCIDRs in the node patch

---

tests/e2e/scenarios/scalability/run-test.sh

- Set max-nodes-to-dump to leverage on large scale tests to reduce storage and disable ServiceTrafficDistribution

test: Utilize max-nodes-to-dump to leverage on large scale tests to reduce storage

---

tests/e2e/scenarios/scalability/run-test.sh

Avoid additional logging in `kube-proxy`, until this PR gets merged - https://github.com/kubernetes/kubernetes/pull/126519

Avoid additional logging in kube-proxy for scale tests

---

tests/e2e/scenarios/scalability/run-test.sh

Ensure we test with same image as GCE
https://github.com/kubernetes/kops/blob/4e57ea751401ee1a1076792945dc6c40a165e5dd/tests/e2e/scenarios/scalability/run-test.sh#L75

Use latest ubuntu jammy 22.04 to match GCE

---

tests/e2e/scenarios/scalability/run-test.sh

- Drop KUBE_NODE_COUNT to an even number
- Allow customizing KOPS_VERSION_MARKER from the CI job definition
- Drop duplicated max-nodes-to-dump

Add KOPS_VERSION_MARKER and cleanup some other settings

---

tests/e2e/scenarios/scalability/run-test.sh

We should be using tip of master for scalability tests
```
$ curl -L https://dl.k8s.io/release/latest.txt
v1.32.0-alpha.0
$ curl -L https://storage.googleapis.com/k8s-release-dev/ci/latest.txt
v1.32.0-alpha.0.16+dbc2b0a5c7acc3
```
I can see other jobs that are using it 🤞🏾 : 
https://cs.k8s.io/?q=--kubernetes-version.*k8s-release-dev&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra

Use latest master build from k8s

---

pkg/bootstrap/chain.go
pkg/kopscontrollerclient/client.go
upup/pkg/fi/nodeup/command.go

Fixes already existing nodes behaviour in kops controller

---

cmd/kops/create_cluster_test.go
pkg/k8scodecs/codecs_test.go
pkg/kopscodecs/codecs_test.go
upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
upup/pkg/fi/cloudup/scaleway/utils.go
upup/pkg/fi/executor.go

Ref: https://github.com/kubernetes/kops/pull/16744
```
running golangci-lint 
level=warning msg="[config_reader] The configuration option `run.skip-files` is deprecated, please use `issues.exclude-files`."
cmd/kops/create_cluster_test.go:40:12: printf: non-constant format string in call to (*testing.common).Errorf (govet)
t.Errorf(err.Error())
^
pkg/k8scodecs/codecs_test.go:77:11: printf: non-constant format string in call to (*testing.common).Logf (govet)
t.Logf(diff.FormatDiff(actual, expected))
^
pkg/kopscodecs/codecs_test.go:71:11: printf: non-constant format string in call to (*testing.common).Logf (govet)
t.Logf(diff.FormatDiff(actual, expected))
^
pkg/kopscodecs/codecs_test.go:105:11: printf: non-constant format string in call to (*testing.common).Logf (govet) …
```

Fix verify-golangci-lint

---

docs/releases/1.31-NOTES.md
pkg/model/awsmodel/spotinst.go
upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go

update controller v2, inform user on conflict with AWS nodeTerminationHandler and Ocean

spotinst: Bump k8s cluster controller to v2

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #16743 on release-1.30.
#16743: fix(cert-manager-webhook): fix label name to bypass LBC
```release-note
```

Automated cherry pick of #16743: fix(cert-manager-webhook): fix label name to bypass LBC

---

docs/contributing/test_versions.md
tests/e2e/e2e.mk
tests/e2e/pkg/kops/download.go
tests/e2e/scenarios/aws-boskos/run-test.sh
tests/e2e/scenarios/build/run-test.sh
tests/e2e/scenarios/cilium-connectivity-test/run-test.sh
tests/e2e/scenarios/kops-upgrade/run-test.sh
tests/e2e/scenarios/lib/common.sh
tests/e2e/scenarios/upgrade-ha-leader-migration/run-test.sh

Ref:
- https://github.com/kubernetes/k8s.io/issues/2625

Drop kops-ci references

---

cloudbuild.yaml

The most recent postsubmit job's cloudbuild job was killed:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/kops-postsubmit-push-to-staging/1822021656441262080
```
Step #0 - "images": 2024/08/09 21:36:20 Unexpected error running "go build": exit status 1
Step #0 - "images": github.com/aws/aws-sdk-go-v2/service/ec2: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
Step #0 - "images": 2024/08/09 21:36:20 Unexpected error running "go build": signal: killed
Step #0 - "images": Error: failed to publish images: error building "ko://k8s.io/kops/cmd/kops-controller": build: go build: exit status 1
Step #0 - "images": exit status 1
Step #0 - "images": make: *** [Makefile:771: ko-kops-controller-push] Error 1 
```
Using the next largest machine type according to the docs: …

Allocate more resources to cloudbuild

---

tests/e2e/pkg/tester/skip_regex.go
upup/pkg/fi/nodeup/nodetasks/package.go

This is a fallback against some of nastier edge cases we can fall into
otherwise.

nodeup: if apt-get tells us to run dpkg configure, run it

---

tests/e2e/pkg/tester/skip_regex.go

We were skipping on DigitalOcean and AWS, but it seems this is actually more a property of the OS under test, because it is the hostname vs node-name problem.

tests: skip "service endpoints using hostNetwork" test across all clouds

---

tests/e2e/pkg/tester/skip_regex.go

Seems to be specific to kube-proxy replacement, but that is our default for newer clusters.

tests: skip NodePort tests with cilium

---

tests/e2e/pkg/tester/skip_regex.go

This test tries to query kube-proxy on port 10249, but it appears that the cilium kube-proxy replacement does not implement this.
Upstream issue: https://github.com/kubernetes/kubernetes/issues/126903

tests: skip kube-proxy metric tests with cilium

---

tests/e2e/pkg/tester/skip_regex.go

Ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/16768/pull-kops-e2e-cni-kuberouter/1827690671192936448

Fix tests skips for kube-router

---

cmd/kops/toolbox_instance-selector.go

Cherry pick of #16776 on release-1.30.
#16776: aws: Fix conversion for instance-selector flags
```release-note
```

Automated cherry pick of #16776: aws: Fix conversion for instance-selector flags

---

.devcontainer/devcontainer.json

Ensure Docker is installed for Github Codespaces.
Docker is required to run some commands from the Makefile.

Enable DinD for Github codespaces

---

dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go

This should allow the fallback behaviour to work as expected.

dns: use resolved region rather than re-resolving every time

---

dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go

Cherry pick of #16778 on release-1.30.
#16778: dns: don't use IMDS region resolver when it previously failed
```release-note
```

Automated cherry pick of #16778: dns: don't use IMDS region resolver when it previously failed

---

cmd/kops-controller/pkg/server/server.go

We were not handling this particularly clearly before, although it should only happen in development.

refactor: give clear error message if challenge endpoint cannot be found

---

tests/e2e/kubetest2-kops/deployer/common.go

Ran into this https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/127005/pull-kubernetes-e2e-gce-disruptive-canary/1829211781348724736/build-log.txt
```
I0829 17:57:21.198213   74468 new_cluster.go:1454] Cloud Provider ID: "gce"
Error: error populating configuration: error fetching network "e2e-pr127005-pull-kubernetes-e2e-gce-disruptive-canary-k8s-local": googleapi: Error 400: Invalid value for field 'network': 'e2e-pr127005-pull-kubernetes-e2e-gce-disruptive-canary-k8s-local'. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}', invalid
W0829 17:57:21.625216   15003 state.go:46] failed to run /home/prow/go/src/k8s.io/kubernetes/_rundir/d5760245-a280-4b20-9469-c66a140b00dc/kops get cluster e2e-pr127005.pull-kubernetes-e2e-gce-disruptive-canary.k8s.loca …
```

Enforce GCP limit of 64 chars for cluster name in kubetest2 deployer

---

tests/e2e/kubetest2-kops/deployer/common.go

Avoid creating new SSH keys if they are already specified. Some CI jobs are failing because the e2e tests are using what is in the env vars, but kops ends up creating new keys when these are not picked up. 
Also log what we are doing so if we end up tripping up any CI jobs, we'll know quickly what went wrong.

Use keys specified in env vars for GCP and AWS

---

util/pkg/vfs/sshfs.go

This makes it consistent with other VFS systems, where we can replace existing files.

vfs: fix file replacement for SFTP

---

pkg/assets/assetdata/containerd.yaml

This avoids having to download the hash each time.

chore: add hashes for containerd 1.7.16

---

tests/e2e/kubetest2-kops/deployer/common.go

Followup to https://github.com/kubernetes/kops/pull/16787
[This test](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-disruptive-canary/1829626382510985216) run is using `e2e-pr127005.pull-kubernetes-e2e-gce-disruptive-canary.k8s.loca` where it would be more appropriate to keep `k8s.local` and trim `e2e-pr127005.pull-kubernetes-e2e-gce-disruptive-canary`.
This PR updates the trim logic to end up with `e2e-pr127005.pull-kubernetes-e2e-gce-disruptive-canar.k8s.local`
/cc @dims @hakman

Don't truncate the top level domains for GCP jobs

---

tests/e2e/pkg/tester/skip_regex.go

This was merged into cilium's main branch and will be a part of v1.17: https://github.com/cilium/cilium/pull/33434
Moving this skip regex into a condition as a reminder to confirm these tests pass once v1.17 is released and kops is upgraded to use v1.17.

Stop skipping protocol tests for future Cilium versions

---

tests/e2e/scenarios/bare-metal/run-test
tools/metal/storage/main.go
tools/metal/storage/pkg/objectstore/interfaces.go
tools/metal/storage/pkg/objectstore/testobjectstore/testobjectstore.go
tools/metal/storage/pkg/s3model/api.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/metal/cloud.go

We still have to add VMs, but this is another step closer.

metal: more functions to enable `kops update cluster`

---

pkg/commands/toolbox_enroll.go
pkg/model/bootstrapscript.go
tests/e2e/scenarios/bare-metal/run-test
upup/pkg/fi/cloudup/new_cluster.go

In particular, we want to build the full cluster and instance group.
The control plane does not yet start, because etcd is not configured correctly.

metal: support `kops toolbox enroll` on a control-plane machine

---

pkg/featureflag/featureflag.go
upup/models/cloudup/resources/addons/gcp-pd-csi-driver.addons.k8s.io/k8s-1.23.yaml.template

Implement SELinuxMount feature gate for GCE.
I tested it on GCE + RockyLinux,
(for my future self: `KOPS_FEATURE_FLAGS=SELinuxMount kops create cluster ${DOMAIN} --zones us-central1-a --state ${KOPS_STATE_STORE}/ --project=${PROJECT}  --set=cluster.spec.cloudProvider.gce.useStartupScript=true  --image=rocky-linux-cloud/rocky-linux-9-optimized-gcp-v20240717 --yes --set=cluster.spec.containerd.selinuxEnabled=true`)

Implement SELinuxMount feature gate for GCE

---

tests/e2e/scenarios/bare-metal/dump-artifacts
tests/e2e/scenarios/bare-metal/run-test

At least while we are building out the static functionality.

tests: use latest dev etcd-manager image in bare-metal test

---

pkg/model/gcemodel/context.go

This should fix these GCP jobs that have long cluster names:
https://testgrid.k8s.io/kops-gce#ci-kubernetes-e2e-cos-gce-reboot-canary
`Error: error running tasks: deadline exceeded executing task Subnet/us-central1-e2e-e2e-ci-kubernetes-e2e-cos-gce-reboot-can-a1ernl. Example error: error creating Subnet: googleapi: Error 400: Invalid value for field 'resource.secondaryIpRanges[1].rangeName': 'services-e2e-e2e-ci-kubernetes-e2e-cos-gce-reboot-canary-k8s-local'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid`
https://github.com/kubernetes/kops/blob/3aad69c65530a0b5558227e4bc92f5428b90a06b/pkg/model/gcemodel/context.go#L75-L78

Limit GCP subnet secondary alias names to 63 chars

---

tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-eks-pod-identity-webhook.addons.k8s.io-k8s-1.16_content
upup/models/cloudup/resources/addons/eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml.template

Cherry pick of #16803 on release-1.29.
#16803: chore: update aws pod identity webhook
```release-note
```

Automated cherry pick of #16803: chore: update aws pod identity webhook

---

cmd/kops-controller/controllers/awsipam.go
cmd/kops-controller/controllers/gceipam.go
cmd/kops-controller/controllers/legacy_node_controller.go
cmd/kops-controller/controllers/node_controller.go

This makes progress on fixing ipv6 support.
For IPV6 clusters we enable an ipam controller in kops-controller:
https://github.com/kubernetes/kops/blob/423b640de6cd18c99fea5c43f938e029a8d8aad6/pkg/apis/kops/cluster.go#L949-L951
https://github.com/kubernetes/kops/blob/423b640de6cd18c99fea5c43f938e029a8d8aad6/upup/pkg/fi/cloudup/template_functions.go#L774-L776
https://github.com/kubernetes/kops/blob/423b640de6cd18c99fea5c43f938e029a8d8aad6/cmd/kops-controller/main.go#L221-L227
controller-runtime's manager picks "names" for each controller it manages, and defaults to the `kind` it watches:
https://github.com/kubernetes-sigs/controller-runtime/blob/38546806f2faf5973e3321a7bd5bb3afdbb5767d/pkg/builder/controller.go#L247-L257
This means that alongside the node bootstrap controller, there are …

Give each kops-controller controller unique names

---

upup/pkg/fi/nodeup/nodetasks/prefix.go

Cherry pick of #16809 on release-1.30.
#16809: Fix ipv6 prefix detection with aws-sdk-go-v2
```release-note
```

Automated cherry pick of #16809: Fix ipv6 prefix detection with aws-sdk-go-v2

---

pkg/nodemodel/nodeupconfigbuilder.go
upup/pkg/fi/cloudup/awstasks/network_load_balancer.go

With this plus https://github.com/kubernetes/kops/pull/16812 i'm able to get an ipv6 dns=none cluster to pass validation.
Before we were only including ipv4 addresses because those are the only CIDRs included in the cluster spec - ipv6 CIDRs are provided by AWS. This resulted in nodes failing to bootstrap because they couldn't reach the kops-controller endpoint:
`Sep 06 01:23:11 i-0250853b64092f19d nodeup[1323]: W0906 01:23:11.157536    1323 main.go:133] got error running nodeup (will retry in 30s): failed to get node config from server: Post "https://172.20.5.248:3988/bootstrap": dial tcp 172.20.5.248:3988: connect: network is unreachable`
Even though the ipv6 address and load balancer DNS name both work:
```
$ curl -6 -k  'https://[2600:1f14:1800:ab02:ba1a:4b60:b424:d3f3]:3988/bootstrap' …
```

Include all APIserver addresses for nodeup config

---

tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/pkg/target/terraform.go
util/pkg/vfs/s3fs.go

We used to set SSE to an empty string, now we leave it unset. This should fix [this failing job](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-scenario-ipv6-terraform/1831834061656559616). 
```
[31m│ [31mError: expected server_side_encryption to be one of ["AES256" "aws:kms" "aws:kms:dsse"], got 
[31m│ 
[31m│   with aws_s3_object.cluster-completed-spec,
[31m│   on kubernetes.tf line 1104, in resource "aws_s3_object" "cluster-completed-spec":
[31m│ 1104:   server_side_encryption = ""
[31m│ 
[31m╵
[31m│ [31mError: expected acl to be one of ["private" "public-read" "public-read-write" "authenticated-read" "aws-exec-read" "bucket-owner-read" "bucket-owner-full-control"], got 
[31m│ 
[31m│   with aws_s3_object.e2e-e2e-kops-scenario-ipv6-terraform-test-cncf-aws-k8s-io- …
```

Conditionally set TF aws_s3_object SSE and ACLs

---

tests/e2e/pkg/tester/skip_regex.go

Most GCP in-tree e2e code has been removed, see https://github.com/kubernetes/kubernetes/pull/124519/files#diff-dea92b851e7b09eb22ffa0bcb0e7ccf58684dbc6a4dc0e06be0fb25d9967002c
`test/e2e/framework/providers/gce/gce.go`
However there are still a few test cases that only run on GCP and fail because the e2e framework no longer implements the in-tree functionality. 
```
I0909 22:43:44.814983 15305 resize_nodes.go:152] Unexpected error: 
<*errors.errorString | 0xc0011db630>: 
Provider does not support InstanceGroups
{
s: "Provider does not support InstanceGroups",
} 
```
https://github.com/kubernetes/kubernetes/blob/0aea469b96a1c0fed48dd2d4a0af96d36e24968c/test/e2e/cloud/gcp/resize_nodes.go#L68-L79
https://github.com/kubernetes/kubernetes/blob/7f9a0ef5d2b0ae5e27d008a9225fb04b3a86b694/test/e2e/f …

Skip some GCP in-tree e2e tests

---

.github/workflows/e2e.yml
hack/dev-build-metal.sh
pkg/model/components/etcdmanager/model.go
tests/e2e/scenarios/bare-metal/dump-artifacts
tests/e2e/scenarios/bare-metal/run-test
tests/e2e/scenarios/bare-metal/start-vms
tools/metal/storage/main.go
tools/metal/storage/pkg/objectstore/fsobjectstore/fsobjectstore.go
tools/metal/storage/pkg/objectstore/interfaces.go
tools/metal/storage/pkg/objectstore/testobjectstore/testobjectstore.go
tools/metal/storage/pkg/s3model/api.go

localhost won't work for multiple nodes and turns out not to even work for one node.
Assume that there is a discovery mechanism that sets up /etc/hosts (it might be static configuration).
Add to metal test to get to kube-apiserver responding.

metal: assume etcd discovery is external

---

tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/pkg/target/terraform.go
util/pkg/vfs/s3fs.go

Cherry pick of #16818 on release-1.30.
#16818: Conditionally set TF aws_s3_object SSE and ACLs
```release-note
```

Automated cherry pick of #16818: Conditionally set TF aws_s3_object SSE and ACLs

---

.golangci.yaml

```
WARN [config_reader] The configuration option `run.skip-files` is deprecated, please use `issues.exclude-files`. 
WARN [config_reader] The configuration option `linters.staticcheck.go` is deprecated, please use global `run.go`. 
```
Also bumping the go version 1.20 -> 1.22

Resolve golangci-lint warnings

---

tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-node-problem-detector.addons.k8s.io-k8s-1.17_content
upup/models/cloudup/resources/addons/node-problem-detector.addons.k8s.io/k8s-1.17.yaml.template

Cherry pick of #16831 on release-1.30.
#16831: Disable node-problem-detector containerd and kubelet checks
```release-note
```

Automated cherry pick of #16831: Disable node-problem-detector containerd and kubelet checks

---

pkg/assets/builder.go
pkg/commands/toolbox_enroll.go
pkg/model/components/kubeapiserver/model.go
pkg/nodemodel/nodeupconfigbuilder.go

Used by the kube-apiserver healthcheck.

metal: copy static manifests to the control plane

---

protokube/cmd/protokube/main.go
protokube/pkg/gossip/azure/client.go
protokube/pkg/gossip/azure/client_test.go
protokube/pkg/protokube/aws_volume.go
protokube/pkg/protokube/azure_volume.go
protokube/pkg/protokube/do_volume.go
protokube/pkg/protokube/gce_volume.go
protokube/pkg/protokube/hetzner_volume.go
protokube/pkg/protokube/kube_boot.go
protokube/pkg/protokube/openstack_volume.go
protokube/pkg/protokube/scaleway_volumes.go
protokube/pkg/protokube/volumes.go

Metal support is basically a stub, but should be sufficient as we are
now only using the cloud provider in gossip mode (and metal does not
use gossip).

protokube: remove unused internal IP discovery, add metal support

---

tests/e2e/scenarios/bare-metal/run-test

It should do what we need (mark the node as ready), and not too many
things we don't need.

tests: try kindnet in bare-metal tests

---

pkg/model/awsmodel/oidc_provider.go
upup/pkg/fi/cloudup/apply_cluster.go

This keystore field was not used.  Refactor for clarity/simplicity.

refactor: remove unused keystore parameter

---

tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-kops-controller.addons.k8s.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-kops-controller.addons.k8s.io-k8s-1.16_content
tests/integration/update_cluster/minimal-1.26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-1.26/data/aws_s3_object_minimal.example.com-addons-kops-controller.addons.k8s.io-k8s-1.16_content
tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-1.27/data/aws_s3_object_minimal.example.com-addons-kops-controller.addons.k8s.io-k8s-1.16_content
tests/integration/update_cluster/minimal-1.28/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-1.28/data/aws_s3_object_minimal.example.com-addons-kops-controller.addons.k8s.io-k8s-1.16_content
tests/integration/update_cluster/minimal-1.29/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-1.29/data/aws_s3_object_minimal.example.com-addons-kops-controller.addons.k8s.io-k8s-1.16_content
tests/integration/update_cluster/minimal-1.30/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-1.30/data/aws_s3_object_minimal.example.com-addons-kops-controller.addons.k8s.io-k8s-1.16_content
tests/integration/update_cluster/minimal-dns-none/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-dns-none/data/aws_s3_object_minimal.example.com-addons-kops-controller.addons.k8s.io-k8s-1.16_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-kops-controller.addons.k8s.io-k8s-1.16_content
upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/template_functions.go

This means we can build the bootstrap configuration for newer kube
versions, if running in a mode that requires us to do that on the fly.

fix: plumb through KOPS_RUN_TOO_NEW_VERSION to kops-controller

---

tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/aws-lb-controller/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-certmanager.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-certmanager.io-k8s-1.16_content
upup/models/cloudup/resources/addons/certmanager.io/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Similar to https://github.com/kubernetes/kops/pull/16179
Fixes https://github.com/kubernetes/kops/issues/16742
It changes label `app.kubernetes.io/name` from `webhook` to `cert-manager` in `svc/cert-manager-webhook`. This exclude the service from the AWS Load balancer controller mutating webhook configuration as shown in https://github.com/kubernetes/kops/pull/16179

fix(cert-manager-webhook): fix label name to bypass LBC webhooks

---

tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template

I realized, that after upgrading to Kops master branch, the cilium-relay deployment was not ok.
Further analyzing brought me to https://github.com/cilium/cilium/issues/31516 where people say, there is a problem with dns, but not for me.
`hubble-relay` connects though `hubble-peer`-service to the hubble processes on port 4244.
But the problem was, that Hubble server inside cilium pods did not start, because the files mounted from `hubble-server-certs` have gotten a new name after upgrade to cilium 1.16.
`cilium status` inside cilium pod reported:
```
Hubble:                  Warning Server not initialized
```
while `hubble status` reported
```
Healthcheck (via unix:///var/run/cilium/hubble.sock): Ok
```

correct hubble tls file names as mapped from secret hubble-server-certs

---

tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/kubetest2-kops/deployer/template.go
tests/e2e/scenarios/podidentitywebhook/cluster.yaml.tmpl

This job is currently failing because its trying to reuse the kops state store for discovery documents and the state store s3 bucket doesn't support ACLs
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-pod-identity-webhook/1841974219194241024
`W1003 22:59:03.893406   14665 executor.go:141] error running task "ManagedFile/keys.json" (9m33s remaining to succeed): error creating ManagedFile "openid/v1/jwks": error writing s3://k8s-kops-ci-prow-state-store/e2e-49d63c55eb-ac683.tests-kops-aws.k8s.io/openid/v1/jwks (with ACL="public-read"): operation error S3: PutObject, https response error StatusCode: 400, RequestID: S4Q35EVQAWC6XCSQ, HostID: qwNOSCxjfBeio8cM845/Od/jn/d83NGKVOO8igAOXzUbe3fUUA4/ow51TSY9EBzBXEy2w8XXLnfTT97wRXocGg==, api error AccessControlListNotSupported: The …

Use a different bucket for pod-identity-webhook discovery store

---

pkg/dump/resourcedumper.go

Certain api services have conflicting Resource types, causing resource dumps to overwrite eachother. This ensures filenames remain unique by prefixing them with the api group.
Example: metrics-server installs an api service that as a `kind` of `NodeMetrics` but the resource name is `nodes`, causing the e2e resource dumps to not include node information:
https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-metrics-server/1841911807569039360/artifacts/cluster-info/nodes.yaml
https://github.com/kubernetes-sigs/metrics-server/blob/5a7a444dc27c0061e8c67417779aa344e1342c8f/pkg/api/install.go#L44-L54

Prefix resource dump filenames with group

---

pkg/dump/resourcedumper.go

Some addons install their own APIServices:
https://github.com/kubernetes/kops/blob/7a43629a8e434c1b378c9160846bb98d3fff0e61/upup/models/cloudup/resources/addons/metrics-server.addons.k8s.io/k8s-1.11.yaml.template#L217-L237
These are recognized by `kops toolbox dump` to dump the resources served by this APIService.
If there is an issue with the pods behind the APIService, client-go will be unable to query the service for its resources.
When that happens, we should skip the API and continue.
Client-go makes this scenario easy to recognize:
https://github.com/kubernetes/kops/blob/3b5fa6fc3513102862eb7e6e698db16c9bd784f7/vendor/k8s.io/client-go/discovery/discovery_client.go#L512-L516
Example failure, there are no resources in [this job's](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pu …

Dont fail resource dump if not all APIs can be discovered

---

upup/pkg/fi/cloudup/awstasks/natgateway.go

Cherry pick of #16879 on release-1.29.
#16879: Ignore blackhole NAT routes
```release-note
```

Automated cherry pick of #16879: Ignore blackhole NAT routes

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go

WIP See #16886 
Rewire the non-default AWS SDK `RetryMaxAttempts` constants that may have been lost in the AWS SDK v1 to v2 migration.

aws: Fix awsup default and DescribeTag max retries

---

upup/pkg/fi/cloudup/awsup/aws_cloud.go

Cherry pick of #16887 on release-1.30.
#16887: Fix awsup default and DescribeTag max retries
```release-note
```

Automated cherry pick of #16887: Fix awsup default and DescribeTag max retries

---

tests/e2e/kubetest2-kops/aws/zones.go

Before the migration to community-owned accounts we were skipping the one constrained zone in the old AWS account. Now we run in multiple accounts depending on the prow cluster, and they have different zone mappings. Rather than identify the problematic zone by API call we just skip the us-west-1 zones altogether.
Should prevent this flake: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-upgrade-k129-ko129-to-k130-kolatest/1844488150970273792
```
W1010 21:23:23.992379   14719 aws_cloud.go:2384] cannot find suitable instance type
W1010 21:23:23.992399   14719 aws_cloud.go:2386]   *  instance type "t3.medium" is not available in all zones (available in zones map[:{} us-west-1a:{} us-west-1c:{}], need [us-west-1b])
W1010 21:23:23.992403   14719 aws_cloud.go:2386]   * …
```

Skip all us-west-1 zones

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha3/networking.go

The image below shows the broken link that has been updated: ![image](https://github.com/user-attachments/assets/c3ecc00a-5bf8-46df-a9ab-58b01f5efd47)
And the correct link is:  https://docs.cilium.io/en/stable/observability/metrics/#hubble-exported-metrics
Example of the change in code: [networking.go#L539](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/networking.go#L539).
Other references that were verified:
[clusters.yaml#L5363](https://github.com/kubernetes/kops/blob/master/k8s/crds/kops.k8s.io_clusters.yaml#L5363)
[v1alpha2/networking.go#L660](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/networking.go#L660)
[v1alpha3/networking.go#L502](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha3/networking.go#L502)

doc:fix broken link

---

pkg/apis/kops/fieldmap.go
pkg/commands/set_cluster.go

We remap field paths to their internal forms, where the mapping is well-known.

fix: allow path-remapping in `set` commands

---

docs/advanced/experimental.md

docs: remove reference to old EnableExternalDNS feature flag

---

pkg/apis/kops/fieldmap.go

I encountered a few more that have changed between v1alpha2 and v1alpha3.

chore: add a few more field mappings to our list

---

upup/pkg/fi/context.go

This allows us to invoke methods that accept interfaces, and arguably
the old logic was incorrect (though it worked in the case where we
wanted exact type matches)

chore: fix method-matching on Render method

---

upup/pkg/fi/cloudup/metal/cloud.go

Our metal implementation currently has some stub methods that return a
not-implemented error; make sure the errors are unique.

chore: more self-descriptive not-implemented errors

---

docs/operations/service_account_issuer_migration.md

Update Service Account Issuer Migration documentation to include `additionalServiceAccountIssuers` migration procedure. Follow up from kubernetes/kops#16541 now that I have tested the migration using `additionalServiceAccountIssuers`.

Update Service Account Issuer Migration doc

---

pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

/hold
for https://github.com/kubernetes/test-infra/pull/33718 to land first. We'll use this PR to ensure latest-ci and latest-ci-updown-green are in a good state.

Upgrade Cilium to v1.16.3

---

docs/cluster_spec.md
k8s/crds/kops.k8s.io_clusters.yaml
nodeup/pkg/model/kube_apiserver_test.go
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

This PR removes an unsupported option and adds the existing supported options to have some basic control over some parts of apiserver memory usage
Remove targetRamMb option, which was removed in kubernetes 1.24. Addresses #14276   
Add watchCache and watchCacheSizes apiserver flags

API Server: memory management related flags

---

pkg/apis/kops/containerdconfig.go
tests/integration/update_cluster/nvidia/data/aws_launch_template_master-us-test-1a.masters.minimal.example.com_user_data
tests/integration/update_cluster/nvidia/data/aws_launch_template_nodes.minimal.example.com_user_data
tests/integration/update_cluster/nvidia/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/nvidia/data/aws_s3_object_nodeupconfig-master-us-test-1a_content
tests/integration/update_cluster/nvidia/data/aws_s3_object_nodeupconfig-nodes_content

Cherry pick of #16560 on release-1.30.
#16560: Bump nvidia-driver-535-server
```release-note
```

Automated cherry pick of #16560: Bump nvidia-driver-535-server

---

docs/cluster_spec.md
k8s/crds/kops.k8s.io_clusters.yaml
nodeup/pkg/model/kube_apiserver_test.go
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go

Cherry pick of #16918 on release-1.30.
#16918: Remove targetRamMb option, which was removed in kubernetes
```release-note
```

Automated cherry pick of #16918: API Server: memory management related flags

---

tests/e2e/templates/many-addons.yaml.tmpl

Many of the manyaddons tests are flaky:
https://testgrid.k8s.io/kops-upgrades-many-addons
Mid rotation some nodes fail to join for some reason:
```
I1104 20:04:03.890143   14885 instancegroups.go:567] Cluster did not pass validation, will retry in "30s": InstanceGroup "nodes-us-west-2a" did not have enough nodes 1 vs 4.
I1104 20:04:36.517763   14885 instancegroups.go:567] Cluster did not pass validation, will retry in "30s": InstanceGroup "nodes-us-west-2a" did not have enough nodes 1 vs 4. 
```
I'll revisit https://github.com/kubernetes/kops/pull/16354 to improve our visibility here, but first we can try reducing the number of nodes. The not-manyaddons upgrade tests use 4 nodes total, and most of the extra Deployments in the cluster have very minimal resource requests, so we'll try …

Reduce number of nodes in manyaddons tests

---

cmd/kops/update_cluster.go
docs/cli/kops_update_cluster.md
pkg/model/awsmodel/autoscalinggroup_test.go
pkg/model/awsmodel/iam.go
pkg/model/azuremodel/testing.go
pkg/model/bootstrapscript_test.go
pkg/model/components/etcdmanager/model_test.go
pkg/model/components/kubeapiserver/model_test.go
pkg/model/components/kubescheduler/model_test.go
pkg/model/context.go
pkg/model/openstackmodel/servergroup_test.go
pkg/predicates/function.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
upup/pkg/fi/cloudup/template_functions.go

Co-Authored-By: Ciprian Hacman <ciprianhacman@gmail.com>

Allow updating the cluster one instance group at a time

---

.github/workflows/e2e.yml

These artifacts are not scoped to the job, so we should give them unambiguous names.

e2e: name artifacts after the tests

---

cmd/kops/toolbox_dump.go
docs/cli/kops_toolbox_dump.md
tests/e2e/scenarios/bare-metal/dump-artifacts
tests/e2e/scenarios/bare-metal/run-test

This lets us share the diagnostic-dumping code.
We don't want to recreate the dumping apparatus

tests: run kops toolbox dump in bare-metal e2e

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Cherry pick of #16949 on release-1.30.
#16949: chore(upup): bump aws-cni to 1.18.6
```release-note
```

Automated cherry pick of #16949: chore(upup): bump aws-cni to 1.18.6

---

mkdocs.yml

This adds a long-overdue toggle for dark mode support in our docs website. The website will automatically align with the OS theme (light/dark), but it's possible to toggle dark mode on/off by using the switch.
Followed mkdocs insturctions [here](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle)
Netlify Preview deploy [here](https://deploy-preview-16951--kubernetes-kops.netlify.app/)
And also screenshots below.
**Light Mode Screenshot (Same as before)**:
**Dark Mode Screenshot**:

feat(docs): add toggle for light/dark mode support

---

upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/k8s-1.19.yaml.template
upup/pkg/fi/cloudup/template_functions.go

Cherry pick of #16948 on release-1.30.
#16948: openstack: add external dns support
```release-note
```

Automated cherry pick of #16948: openstack: add external dns support

---

cloudbuild.yaml

Cherry pick of #16765 on release-1.30.
#16765: Allocate more resources to cloudbuild
```release-note
```

Automated cherry pick of #16765: Allocate more resources to cloudbuild

---

clusterapi/bootstrap/controllers/kopsconfig_controller.go
pkg/commands/toolbox_enroll.go
pkg/nodemodel/fileassets.go
pkg/nodemodel/nodeupconfigbuilder.go
upup/pkg/fi/cloudup/apply_cluster.go

Also remove the (potentially) confusing FileAssets type.

refactor: build assets for kubernetes and nodeup explicitly

---

nodeup/pkg/model/containerd.go
nodeup/pkg/model/context.go
nodeup/pkg/model/kube_proxy_test.go
pkg/apis/kops/model/features.go
pkg/apis/kops/model/instance_group.go
pkg/apis/kops/model/kubernetes_version.go
pkg/apis/kops/util/versions.go
pkg/model/components/context.go
pkg/nodemodel/fileassets.go
pkg/nodemodel/nodeupconfigbuilder.go
pkg/nodemodel/wellknownassets/cni.go
pkg/nodemodel/wellknownassets/cni_test.go
pkg/nodemodel/wellknownassets/containerd.go
pkg/nodemodel/wellknownassets/crictl.go
pkg/nodemodel/wellknownassets/crictl_test.go
pkg/nodemodel/wellknownassets/nerdctl.go
pkg/nodemodel/wellknownassets/runc.go

This abstraction should let us change the version on an instance group level.

refactor: create abstraction over cluster/instancegroup for building assets

---

channels/alpha

Bumps alpha channel versions
- https://github.com/kubernetes/kubernetes/releases/tag/v1.29.11
- https://github.com/kubernetes/kubernetes/releases/tag/v1.30.7

chore(channels): bump k8s and ubuntu jammy ami versions in alpha channel

---

upup/pkg/fi/nodeup/nodetasks/package.go
util/pkg/distributions/distributions.go
util/pkg/distributions/identify.go
util/pkg/distributions/identify_test.go

Also simplify the dnf-detection logic; it looks like all our rpm distros now use dnf.

Recognize fedora 41 and debian 13

---

dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go

Ref: https://github.com/kubernetes/kops/issues/16837#issuecomment-2506780983
Here is the call stack leading to the logging statement: 
https://github.com/kubernetes/kops/blob/323dbae1b3a41571c27878b4574b9540860dcf12/vendor/github.com/aws/aws-sdk-go-v2/config/load_options.go#L912-L917
https://github.com/kubernetes/kops/blob/323dbae1b3a41571c27878b4574b9540860dcf12/vendor/github.com/aws/aws-sdk-go-v2/aws/logging.go#L16-L21
https://github.com/kubernetes/kops/blob/323dbae1b3a41571c27878b4574b9540860dcf12/vendor/github.com/aws/aws-sdk-go-v2/aws/logging.go#L36-L39
https://github.com/kubernetes/kops/blob/323dbae1b3a41571c27878b4574b9540860dcf12/vendor/github.com/aws/aws-sdk-go-v2/feature/ec2/imds/request_middleware.go#L112-L115
https://github.com/kubernetes/kops/blob/323dbae1b3a41571c27878b4574b9 …

Remove more unnecessary IMDS request logging

---

dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go

Cherry pick of #16966 on release-1.30.
#16966: Remove more unnecessary IMDS request logging
```release-note
```

Automated cherry pick of #16966: Remove more unnecessary IMDS request logging

---

tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template

Fixes https://github.com/kubernetes/kops/issues/16965
This reverts the cherrypick of https://github.com/kubernetes/kops/pull/16855 in https://github.com/kubernetes/kops/pull/16856

Revert 1.30 Cherrypick "correct hubble tls file names as ..."

---

channels/stable
tests/integration/create_cluster/minimal-1.27/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.28/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.29/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.30/expected-v1alpha2.yaml

chore(channels): promoe alpha to stable (k8s and ubuntu ami)

---

cmd/kops/update_cluster.go
docs/cli/kops_update_cluster.md
pkg/apis/kops/model/instance_group.go
pkg/assets/builder.go
pkg/nodemodel/nodeupconfigbuilder.go
upup/pkg/fi/cloudup/apply_cluster.go

Automatically preserve kubelet supported version skew on worker nodes while control plane is being updated
Fixes: https://github.com/kubernetes/kops/issues/16907

Fix version upgrade kubelet support

---

clusterapi/bootstrap/controllers/kopsconfig_controller.go
cmd/kops/create_cluster.go
cmd/kops/edit_cluster.go
cmd/kops/edit_instancegroup.go
nodeup/pkg/model/kubelet_test.go
pkg/assets/builder.go
pkg/assets/builder_test.go
pkg/commands/helpers_readwrite.go
pkg/instancegroups/rollingupdate_os_test.go
pkg/model/components/containerd_test.go
pkg/model/components/etcdmanager/model_test.go
pkg/model/components/image_test.go
pkg/model/components/kubeapiserver/model_test.go
pkg/model/components/kubecontrollermanager_test.go
pkg/model/components/kubelet_test.go
pkg/model/components/kubescheduler/model_test.go
pkg/model/components/kubescheduler_test.go
pkg/nodemodel/wellknownassets/cni_test.go
pkg/nodemodel/wellknownassets/crictl_test.go
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/awstasks/elastic_ip_test.go
upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
upup/pkg/fi/cloudup/gcetasks/serviceaccount_test.go
upup/pkg/fi/cloudup/populate_cluster_spec_test.go
upup/pkg/fi/dryruntarget_test.go
upup/pkg/fi/nodeup/command.go

This field is no longer used, and can be removed.

Remove unusued kubernetesVersion from AssetBuilder

---

nodeup/pkg/model/context.go
pkg/apis/kops/model/kubernetes_version.go
pkg/model/components/apiserver.go
pkg/model/components/awscloudcontrollermanager.go
pkg/model/components/containerd_test.go
pkg/model/components/context.go
pkg/model/components/gcpcloudcontrollermanager.go
pkg/model/components/kubecontrollermanager.go
pkg/model/components/kubelet.go
pkg/model/components/kubelet_test.go
pkg/model/components/kubescheduler.go
pkg/model/components/kubescheduler_test.go
pkg/nodemodel/nodeupconfigbuilder.go
upup/pkg/fi/cloudup/populate_cluster_spec.go
upup/pkg/fi/cloudup/spec_builder.go

We need to differentiate between the version of the control plane
and the version of the nodes.

Fixup kubelet and controlPlaneKubelet config building

---

cmd/kops/reconcile_cluster.go
cmd/kops/update_cluster.go
docs/cli/kops_update_cluster.md

This is adding the "combined command" now that the control-plane must be upgraded before the nodes.
I'm not clear as to what the best name is (or even whether it should be a separate command, or a flag).  Thoughts / suggestions very welcome!

reconcile command to combine update and rolling-update

---

pkg/apis/kops/util/taints.go
pkg/model/awsmodel/autoscalinggroup.go
pkg/resources/aws/filters.go
protokube/pkg/gossip/dns/provider/zone.go
upup/pkg/fi/cloudup/template_functions.go

fix some function names in comment

chore: fix some function names in comment

---

pkg/assets/builder.go

We have to download the hash file for assets that are not well-known,
but this is not an error, and this causes a lot of noise in our logs.

Dial down warning level when asset is not found

---

channels/alpha

chore(channels): update alpha k8s and ubuntu ami versions

---

pkg/model/context.go
tests/integration/update_cluster/complex/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-bootstrap_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
tests/integration/update_cluster/complex/in-v1alpha2.yaml
tests/integration/update_cluster/complex/kubernetes.tf

Cherry pick of #17141 on release-1.31.
#17141: Only set NTH ManagedASGTag label if it doesn't already exist
```release-note
```

Automated cherry pick of #17141: Only set NTH ManagedASGTag label if it doesn't already exist

---

tests/e2e/pkg/tester/skip_regex.go

This job uses the latest stable k/k release, and started failing once 1.32.0 was released:
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/pr-logs/directory/pull-kops-e2e-k8s-gce-cilium
This test was added in https://github.com/kubernetes/kubernetes/pull/125222. Until we can look into this further and/or progress is made on the linked k/k issue, we can skip the test to unblock other kops PRs.

Temporarily skip failing cilium test to unblock PRs

---

pkg/model/context.go
tests/integration/update_cluster/complex/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-bootstrap_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-node-termination-handler.aws-k8s-1.11_content
tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
tests/integration/update_cluster/complex/in-v1alpha2.yaml
tests/integration/update_cluster/complex/kubernetes.tf

Reported on slack.
If a cluster has ManagedASGTag set to an existing label, it is overwritten with an empty value. For the `kubernetes.io/cluster/$cluster` tag, this can cause problems during cluster deletion.
NTH doesn't actually care about the value of the tag:
https://github.com/aws/aws-node-termination-handler/blob/a0c0aa1bd14780b0d5ca7ce70cd92eed746ff64d/pkg/monitor/sqsevent/sqs-monitor.go#L427-L431
So if the tag is already set then we should preserve its existing value.

Only set NTH ManagedASGTag label if it doesn't already exist

---

channels/stable
tests/integration/create_cluster/minimal-1.27/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.28/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.29/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.30/expected-v1alpha2.yaml

chore(channels): promote alpha to stable (k8s and ubuntu ami versions)

---

cmd/kops/delete_instance.go
cmd/kops/rolling-update_cluster.go
pkg/instancegroups/instancegroups.go
pkg/instancegroups/instancegroups_test.go
pkg/instancegroups/rollingupdate.go
pkg/instancegroups/rollingupdate_os_test.go
pkg/instancegroups/rollingupdate_test.go
pkg/instancegroups/rollingupdate_warmpool_test.go

Move it out of the struct, and into the function parameters.
This is more go idiomatic.

chore: add context to rolling update functions

---

channels/cmd/channels/main.go
channels/pkg/cmd/apply.go
channels/pkg/cmd/apply_channel.go
channels/pkg/cmd/factory.go
channels/pkg/cmd/get.go
channels/pkg/cmd/get_addons.go
channels/pkg/cmd/root.go
cmd/kops/delete_instance.go
cmd/kops/get_instances.go
cmd/kops/rolling-update_cluster.go
cmd/kops/toolbox_addons.go
cmd/kops/toolbox_dump.go
cmd/kops/util/factory.go
cmd/kops/validate_cluster.go
pkg/commands/commandutils/factory.go
pkg/commands/toolbox_enroll.go
pkg/instancegroups/rollingupdate.go
pkg/validation/validate_cluster.go
pkg/validation/validate_cluster_test.go

This should allow us to build our own rest config in future,
rather than relying on the kubeconfig being configured correctly.
To do this, we need to stop sharing the factory between the channels
and kops commands.

chore: refactor factory to accept a cluster

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa25/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa26/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Cherry pick of #17163 on release-1.31.
#17163: chore(networking): bump aws-vpc-cni version to 1.19.2
```release-note
```

Automated cherry pick of #17163: chore(networking): bump aws-vpc-cni version to 1.19.2

---

channels/cmd/channels/main.go
channels/pkg/cmd/apply.go
channels/pkg/cmd/apply_channel.go
channels/pkg/cmd/factory.go
channels/pkg/cmd/get.go
channels/pkg/cmd/get_addons.go
channels/pkg/cmd/root.go
cmd/kops/delete_instance.go
cmd/kops/get_instances.go
cmd/kops/rolling-update_cluster.go
cmd/kops/toolbox_addons.go
cmd/kops/toolbox_dump.go
cmd/kops/util/factory.go
cmd/kops/validate_cluster.go
pkg/commands/commandutils/factory.go
pkg/commands/toolbox_enroll.go
pkg/instancegroups/rollingupdate.go
pkg/kubeconfig/create_kubecfg.go
pkg/kubeconfig/kubecfg_builder.go
pkg/validation/validate_cluster.go
pkg/validation/validate_cluster_test.go

- **chore: refactor factory to accept a cluster**
- **chore: generate kubeconfig on the fly**

chore: generate kubeconfig on the fly

---

pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #17170 on release-1.31.
#17170: Update Cilium to v1.16.5
```release-note
```

Automated cherry pick of #17170: Update Cilium to v1.16.5

---

pkg/model/master_volumes.go
upup/pkg/fi/cloudup/azuretasks/disk.go
upup/pkg/fi/cloudup/azuretasks/disk_test.go

Fixes https://github.com/kubernetes/kops/issues/16838

Adding VolumeType for Azure for etcdMembers

---

pkg/model/master_volumes.go
upup/pkg/fi/cloudup/azuretasks/disk.go
upup/pkg/fi/cloudup/azuretasks/disk_test.go

Cherry pick of #17171 on release-1.31.
#17171: Adding VolumeType for Azure for etcdMembers
```release-note
```

Automated cherry pick of #17171: Adding VolumeType for Azure for etcdMembers

---

pkg/model/context.go
pkg/model/hetznermodel/servers.go
pkg/nodeidentity/hetzner/identify.go
tests/integration/update_cluster/minimal_hetzner/kubernetes.tf
upup/pkg/fi/cloudup/hetzner/cloud.go

Fixes https://github.com/kubernetes/kops/issues/16159
This adds Hetzner server labels for the instance group nodeLabels. kops-controller then recognizes these server labels and sets them on the associated k8s node.
I'm marking this WIP as we may need to change this approach due to label length limits in the Hetzner API:
https://docs.hetzner.com/cloud/servers/getting-started/creating-a-server/
> Both key and value must be 63 characters or less, beginning and ending with an alphanumeric character and alphanumerics can be used inbetween
The Hetzner CCM mentions support for the `node.kubernetes.io/exclude-from-external-load-balancers` label included in the integration test output changes: https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/182#issuecomment-830577642 which …

Propagate IG NodeLabels to k8s nodes in Hetzner

---

pkg/model/context.go
pkg/model/hetznermodel/servers.go
pkg/nodeidentity/hetzner/identify.go
tests/integration/update_cluster/minimal_hetzner/kubernetes.tf
upup/pkg/fi/cloudup/hetzner/cloud.go

Cherry pick of #16739 on release-1.31.
#16739: Propagate IG NodeLabels to k8s nodes in Hetzner
```release-note
```

Automated cherry pick of #16739: Propagate IG NodeLabels to k8s nodes in Hetzner

---

cloudbuild.yaml
go.mod
hack/go.mod
tests/e2e/go.mod
tools/otel/traceserver/go.mod

Cherry pick of #17184 on release-1.31.
#17184: Update Go to v1.23.4
```release-note
```

Automated cherry pick of #17184: Update Go to v1.23.4

---

util/pkg/vfs/s3fs.go
util/pkg/vfs/s3fs_test.go

Alternative to https://github.com/kubernetes/kops/pull/17182
The aws-sdk-go-v2 includes an endpoint resolver that uses the region and partition information embedded in the SDK without making any API call to AWS.
This makes the VFS code more flexible, supporting all regions and partitions that the SDK recognizes.

Use SDK's built-in resolver for S3Path.GetHTTPsUrl

---

util/pkg/vfs/s3fs.go
util/pkg/vfs/s3fs_test.go

Cherry pick of #17183 on release-1.31.
#17183: Use SDK's built-in resolver for S3Path.GetHTTPsUrl
```release-note
```

Automated cherry pick of #17183: Use SDK's built-in resolver for S3Path.GetHTTPsUrl

---

docs/contributing/ports.md
pkg/wellknownports/wellknownports.go
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template

Cilium uses port `9965` for hubble-metrics. See https://docs.cilium.io/en/stable/observability/metrics/#hubble-metrics
Fixes #17174

Use the same port for hubble-metrics that is used by cilium

---

pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/validation/validation.go
util/pkg/reflectutils/access.go
util/pkg/reflectutils/set_fields.go
util/pkg/reflectutils/tests/access_test.go

We also have to move some of the EnvVar handling around to avoid a circular reference.

Refactor validation logic around checking for multiple options

---

docs/contributing/ports.md
pkg/wellknownports/wellknownports.go
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template

Cherry pick of #17177 on release-1.31.
#17177: Use the same port for hubble-metrics that is used by
```release-note
```

Automated cherry pick of #17177: Use the same port for hubble-metrics that is used by

---

channels/alpha
channels/stable
tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_hetzner/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.32/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-arm64/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-gce-dns-none/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-gce/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-irsa/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal_hetzner/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
upup/pkg/fi/cloudup/new_cluster.go
upup/pkg/fi/cloudup/new_cluster_test.go
upup/pkg/fi/cloudup/populate_instancegroup_spec.go

As discussed during the Jan 10th Office Hours, we are defaulting to Ubuntu 24.04 (Noble) starting with K8s 1.32.
/cc @rifelpet @justinsb @zetaab

Use Ubuntu 24.04 (Noble) as the default distro for K8s 1.32+

---

tests/integration/update_cluster/minimal-ipv6-kindnet/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-kindnet/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.kindnet-k8s-1.32_content
tests/integration/update_cluster/privatekindnet/data/aws_s3_object_privatekindnet.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatekindnet/data/aws_s3_object_privatekindnet.example.com-addons-networking.kindnet-k8s-1.32_content
upup/models/cloudup/resources/addons/networking.kindnet/k8s-1.32.yaml.template

With the final 1.8.0 release of kindnet (yeah, this time the tag is final 😄 ).
One of the features is that it completely moved the image to distroless https://github.com/aojea/kindnet/releases/tag/v1.8.0
Because of that, current manifest that is using `args:` instead of `command:` fails to run https://testgrid.k8s.io/kops-distro-u2404#kops-aws-cni-kindnet

kindnet: use commands instead of args for the container image

---

pkg/resources/gce/errors.go
pkg/resources/ops/delete.go
upup/pkg/fi/cloudup/gce/wrappers.go

Similar to what we do on AWS, we avoid printing confusing error
messages when there is a dependency we aren't aware of.

delete cluster: avoid logspam on GCE "resource in use" error

---

cmd/kops/delete_instance.go
cmd/kops/reconcile_cluster.go
cmd/kops/rolling-update_cluster.go
cmd/kops/validate_cluster.go
pkg/instancegroups/instancegroups.go
pkg/instancegroups/rollingupdate_test.go
pkg/instancegroups/rollingupdate_warmpool_test.go
pkg/validation/validate_cluster.go
pkg/validation/validate_cluster_test.go

The rolling-update requires the apiserver (when called without --cloudonly),
so reconcile should wait for apiserver to start responding.
Implement this by reusing "validate cluster", but filtering to only the instance groups
and pods that we expect to be online.

reconcile: wait for apiserver to response before trying rolling-update

---

pkg/model/components/kindnet.go
tests/integration/update_cluster/minimal-ipv6-kindnet/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-kindnet/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-kindnet/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.kindnet-k8s-1.32_content
tests/integration/update_cluster/privatekindnet/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatekindnet/data/aws_s3_object_privatekindnet.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatekindnet/data/aws_s3_object_privatekindnet.example.com-addons-networking.kindnet-k8s-1.32_content

Some bugfixes https://github.com/aojea/kindnet/releases/tag/v1.8.1
and some other more https://github.com/aojea/kindnet/releases/tag/v1.8.2

bump kindnet default version to 1.8.2

---

tests/integration/update_cluster/minimal-ipv6-kindnet/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-kindnet/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.kindnet-k8s-1.32_content
tests/integration/update_cluster/privatekindnet/data/aws_s3_object_privatekindnet.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatekindnet/data/aws_s3_object_privatekindnet.example.com-addons-networking.kindnet-k8s-1.32_content
upup/models/cloudup/resources/addons/networking.kindnet/k8s-1.32.yaml.template

kindnet needs to read the node configuration to obtain the dns nameserver and configuration, so it can implement the dnscache restricting the traffic to the in-cluster dns traffic only and avoid any possible disruption on the network
Fixes: https://github.com/aojea/kindnet/issues/159
/assign @hakman

fix kindnet permissions

---

pkg/model/components/kubecontrollermanager.go
pkg/resources/gce/dump.go
tests/integration/update_cluster/privatekindnet/data/aws_launch_template_master-us-test-1a.masters.privatekindnet.example.com_user_data
tests/integration/update_cluster/privatekindnet/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatekindnet/data/aws_s3_object_nodeupconfig-master-us-test-1a_content

Different cloud providers provide the basic ipam functionality on the node.spec.podcidr via different components.
Typically this was done on the kube-controller-manager, but since the removal of the in-tree cloud provider code in Kubernetes, the GCP only ipam mode called CloudAllocator is not available, so it is provided by the cloud-controller-manager.
The commit in 27e8624cffec1ba643bb29d37ae1aa3e024d3527 made a GCP only check to apply to all cloud providers, hence disabling the ipamm functionality in the KCM, and as a consequence the kindnet jobs that depend on that started failing
https://testgrid.k8s.io/kops-distro-u2404#kops-aws-cni-kindnet
Revert that PR and keep the dumping functionality that is unrelated to the IPAM functionality

Kindnet requires cluster to provide ipam via the node.spec.podcidr

---

cmd/kops/create_cluster.go
cmd/kops/update_cluster.go
docs/cli/kops_create_cluster.md
docs/cli/kops_update_cluster.md
upup/pkg/fi/cloudup/apply_cluster.go
upup/pkg/fi/cloudup/target.go

A small cleanup that makes our code a little more robust.

Support strong-typing for --target values

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

We expect people to start using the reconcile command
particularly for upgrades.

tests: use reconcile command for kOps 1.31+

---

cloudbuild.yaml
go.mod
hack/go.mod
tests/e2e/go.mod
tools/otel/traceserver/go.mod

Cherry pick of #17217 on release-1.31.
#17217: Update Go to v1.23.5
```release-note
```

Automated cherry pick of #17217: Update Go to v1.23.5

---

tests/e2e/scenarios/bare-metal/run-test
upup/pkg/fi/cloudup/metal/cloud.go

The cluster should be considered healthy by kOps at this point.

e2e: add `kops validate` step to metal test

---

cmd/kops/update_cluster.go
docs/cli/kops_update_cluster.md

We have `kops reconcile`, and it's confusing having both.
We didn't ship the --reconcile flag in any released version.

Remove reconcile flag from `kops update`

---

channels/stable
tests/integration/create_cluster/cilium-eni/expected-v1alpha2.yaml
tests/integration/create_cluster/complex-private/expected-v1alpha2.yaml
tests/integration/create_cluster/complex/expected-v1alpha2.yaml
tests/integration/create_cluster/ha/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/ipv6/expected-v1alpha2.yaml
tests/integration/create_cluster/karpenter/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.27/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.28/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.29/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.30/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.31/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-1.32/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-arm64/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal-irsa/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal_feature-gates/expected-v1alpha2.yaml
tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
tests/integration/create_cluster/private/expected-v1alpha2.yaml
tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml

Promotes #17216 to stable channel

chore(channels): promote alpha to stable

---

docs/operations/updates_and_upgrades.md
docs/releases/1.31-NOTES.md
docs/tutorial/upgrading-kubernetes.md

A few open questions:
1. Do we update all the `rolling-update cluster` docs references to `reconcile cluster`?
2. Do we return an error when a user tries to upgrade from k8s 1.30 to 1.31 using `update cluster --yes`? (with no `--instance-group*` filtering)
3. Do we add a new [permalink](https://github.com/kubernetes/kops/tree/master/permalinks) that the error message links to?
4. Do we mention the new `update cluster --reconcile` flag? When would a user use it instead of `kops reconcile cluster` ?

Add docs for the new kops reconcile cluster command

---

pkg/apis/kops/validation/validation.go
tests/e2e/pkg/tester/skip_regex.go
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateflannel/data/aws_s3_object_privateflannel.example.com-addons-networking.flannel-k8s-1.25_content
upup/models/cloudup/resources/addons/networking.flannel/k8s-1.25.yaml.template

Cherry pick of #17179 on release-1.32.
#17179: Re-enable Flannel
```release-note
```

Automated cherry pick of #17179: Re-enable Flannel

---

docs/networking.md
docs/networking/flannel.md
docs/releases/1.32-NOTES.md

Remove removal notice for flannel and update docs

---

docs/operations/etcd_administration.md

On a modern (k8s and kops 1.31.x) cluster, etcd CLI tools are located in:
```
etcdctl version: 3.5.13
API version: 3.5
```
so I updated the docs example to point to the right place, so it can be used as-is.

docs: updated etcdctl example

---

tests/e2e/scenarios/upgrade-ab/run-test.sh

Example failure: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/e2e-kops-aws-upgrade-k130-ko130-to-k130-ko130/1891475173542989824
```
+ [[ 1.30 =~ 1.(20|21|22|23|24|25|26|27|28|29|30). ]]
+ /tmp/kops.nYZ7aVdIW reconcile cluster
Error: unknown command "reconcile" for "kops" 
```

Fix conditional for reconcile command in upgrade tests

---

upup/pkg/fi/nodeup/nodetasks/package.go

ref: https://man7.org/linux/man-pages/man1/dpkg-query.1.html
```
db:Status-Abbrev
It contains the abbreviated package status (as three
characters), such as “ii ” or “iHR” (since dpkg 1.16.2).
See the --list command description for more details.
```
We were previously splitting on a space which depended on Status-Abbrev only using 1 or 2 of its 3 character width. When Status-Abbrev has 3 non-whitespace characters the parsing fails. Now we use tab delimiters and trim off any whitespace after splitting.
This is the first step towards fixing the failing GCE presubmit. Based on [these logs](https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kops/17270/pull-kops-e2e-k8s-gce-cilium/1892382171776159744/artifacts/34.118.249.58/journal.log):
```
nodeup[5467]: I0220 01:46:51.146325 …
```

Split dpkg-query fields with a tab

---

cmd/kops/toolbox_dump.go
pkg/dump/dumper.go

Previously this would always fail in a confusing way,
regardless of whether we had connectivity,
because we tried to connect to an empty-string host.
Now we are more explicit about the error,
and will at least try to connect directly.

Better dumping via private IP when bastion is not set

---

tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm-irsa/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-ccm/data/aws_s3_object_minimal.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-networking.amazon-vpc-routed-eni-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml

Cherry pick of #17277 on release-1.32.
#17277: chore(networking): upgrade amazon vpc cni to 1.19.3
```release-note
```

Automated cherry pick of #17277: chore(networking): upgrade amazon vpc cni to 1.19.3

---

cmd/kops/reconcile_cluster.go
cmd/kops/rolling-update_cluster.go
cmd/kops/update_cluster.go
pkg/instancegroups/rollingupdate.go

Improving the logging for `kops reconcile `cluster`.

Cleanup logging for reconcile cluster

---

cmd/kops/reconcile_cluster.go
cmd/kops/rolling-update_cluster.go
cmd/kops/update_cluster.go
pkg/instancegroups/rollingupdate.go

Cherry pick of #17282 on release-1.31.
#17282: Cleanup logging for reconcile cluster
```release-note
```

Automated cherry pick of #17282: Cleanup logging for reconcile cluster

---

cmd/kops/rolling-update_cluster.go
cmd/kops/util/factory.go
docs/cli/kops_rolling-update_cluster.md

Cherry pick of #17274 on release-1.32.
#17274: make --admin configurable to rolling-update
```release-note
```

Automated cherry pick of #17274: make --admin configurable to rolling-update

---

.github/workflows/main.yml

Cherry pick of #17286 on release-1.32.
#17286: gha: Introduce arm64 for tests
```release-note
```

Automated cherry pick of #17286: gha: Introduce arm64 for tests

---

tests/e2e/pkg/tester/skip_regex.go

These tests are still failing in 1.33 because of the hostname inconsistencies in the e2e test's assumptions.
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/e2e-kops-gce-cni-cilium-k8s-ci/1895087038508568576
```
{ failed [FAILED] failed dialing endpoint, received unexpected responses... 
Attempt 0
Command curl -g -q -s 'http://100.96.3.253:9080/dial?request=hostname&protocol=http&host=100.68.31.181&port=80&tries=1'
retrieved map[nodes-us-west3-a-x22d.c.k8s-infra-e2e-boskos-109.internal:{}]
expected map[nodes-us-west3-a-fmh4:{} nodes-us-west3-a-gc31:{} nodes-us-west3-a-km0d:{} nodes-us-west3-a-x22d:{}]
In [It] at: k8s.io/kubernetes/test/e2e/network/networking.go:479 @ 02/27/25 12:42:40.728
}
```

Skip hostnetwork + hostname tests through 1.33

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/cluster.go
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/cluster.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha3/cluster.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/model/components/nodeproblemdetector.go
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-authentication.aws-k8s-1.12_content
tests/integration/update_cluster/complex/data/aws_s3_object_complex.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons/data/aws_s3_object_many-addons.example.com-addons-node-problem-detector.addons.k8s.io-k8s-1.17_content
upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
upup/models/cloudup/resources/addons/node-problem-detector.addons.k8s.io/k8s-1.17.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/crd/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/authentication.aws-k8s-1.12.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/mappings/manifest.yaml

Remove the default CPU limits defined for the aws-iam-authentication and node-problem-detector DaemonSets.
This makes them behave the same as the other `cpuLimit` parameters for the cluster that also do not have defaults.
As it was previously set up, if an administrator does not want CPU limits defined for these DaemonSets, there was no way to define that via the cluster spec.

Remove default CPU limits for aws-iam-authentication and node-problem-detector

---

tests/integration/create_cluster/ha_hetzner/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal_hetzner/expected-v1alpha2.yaml
tests/integration/update_cluster/minimal_hetzner/in-v1alpha2.yaml
tests/integration/update_cluster/minimal_hetzner/kubernetes.tf
upup/pkg/fi/cloudup/populate_instancegroup_spec.go

Machine type cx21 is no longer available. Seems like it was completely obsoleted several months ago and cannot be created, resulting in errors like such if attempting to deploy with defaults:
error running task "ServerGroup/nodes-hel1" (9m59s remaining to succeed): server type 'cx21' is deprecated

Change to cx22 as default instance for Hetzner

---

tests/e2e/go.mod
tests/e2e/kubetest2-kops/aws/s3.go
tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/kubetest2-kops/deployer/deployer.go
tests/e2e/kubetest2-kops/deployer/down.go
tests/e2e/kubetest2-kops/deployer/up.go

Use S3 buckets created during the lifecycle of a test instead of a
static one.

Use ephemeral S3 buckets for E2E tests

---

upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template

FYI @hakman 
A long overdue bump to kube-router's image on kops. This comes with a bunch of bug fixes as well as a newer iptables userspace.
I've tested a deployment of this against a new kops cluster and haven't noticed any regressions.

kube-router: bump version v2.1.1 -> v2.5.0

---

tests/integration/create_cluster/ha_hetzner/expected-v1alpha2.yaml
tests/integration/create_cluster/minimal_hetzner/expected-v1alpha2.yaml
tests/integration/update_cluster/minimal_hetzner/in-v1alpha2.yaml
tests/integration/update_cluster/minimal_hetzner/kubernetes.tf
upup/pkg/fi/cloudup/populate_instancegroup_spec.go

Cherry pick of #17296 on release-1.32.
#17296: Change to cx22 as default instance for Hetzner as cx21 is no
```release-note
```

Automated cherry pick of #17296: Change to cx22 as default instance for Hetzner as cx21 is no

---

upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template

Cherry pick of #17297 on release-1.32.
#17297: kube-router: bump version v2.1.1 -> v2.5.0
```release-note
```

Automated cherry pick of #17297: kube-router: bump version v2.1.1 -> v2.5.0

---

pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_launch_template_nodes.minimal-warmpool.example.com_user_data
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Update Cilium to v1.16.7

---

tests/e2e/scenarios/scalability/run-test.sh

Feature gate is GA now: https://github.com/kubernetes/kubernetes/pull/130673
- https://testgrid.k8s.io/amazon-ec2-release#ec2-master-small-scale-performance&width=20
- https://testgrid.k8s.io/amazon-ec2-release#ec2-master-scale-performance&width=20
```
❯
❯ (find . -name kube-apiserver.log && find . -name kube-proxy.log)
./1902072946013245440/artifacts/18.116.47.23/kube-apiserver.log
./1902072946013245440/artifacts/3.142.225.232/kube-apiserver.log
./1902072946013245440/artifacts/18.191.224.177/kube-apiserver.log
./1902072946013245440/artifacts/18.116.47.23/kube-proxy.log
./1902072946013245440/artifacts/3.142.225.232/kube-proxy.log
./1902072946013245440/artifacts/18.191.224.177/kube-proxy.log
❯ grep ServiceTrafficDistribution ./1902072946013245440/artifacts/18.116.47.23/kube-apiserver.log | …
```

ServiceTrafficDistribution cannot be switched off for kubernetes master (for scalability tests)

---

upup/pkg/fi/cloudup/awstasks/warmpool.go

This is as a top-level task and implementing
CompareWithID lets us refer to it from multiple
tasks.

WarmPool should implement CompareWithID

---

cmd/kops/integration_test.go
pkg/model/awsmodel/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/warmpool.go

* Add a test that catches the problem
~* Implement CompareWithID on WarmPool (not technically needed here)~ removed for safer cherry-picking
* Mark WarmPool as not-serialized in JSON on ASG

Fix JSON circular dependency in ASG / WarmPool

---

cmd/kops/integration_test.go
pkg/model/awsmodel/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
upup/pkg/fi/cloudup/awstasks/warmpool.go

Cherry pick of #17321 on release-1.32.
#17321: tests: verify that we can marshal tasks to json
```release-note
```

Automated cherry pick of #17321: tests: verify that we can marshal tasks to json

---

tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

This PR removes cilium-config-path mount in the cilium-agent container.
This mount overwrites config generated by [config initContainer](https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template#L1242-L1243). This caused CiliumNodeConfigs not working as expected.
This issue reported in https://github.com/kubernetes/kops/issues/17269

Remove cilium-config-path mount in cilium-agent container

---

tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_minimal-warmpool.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-bootstrap_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_scw-minimal.k8s.local-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_privatecilium.example.com-addons-networking.cilium.io-k8s-1.16_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-bootstrap_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_privateciliumadvanced.example.com-addons-networking.cilium.io-k8s-1.16_content
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/insecure-1.19/manifest.yaml
upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/metrics-server/secure-1.19/manifest.yaml

Cherry pick of #17319 on release-1.32.
#17319: Remove cilium-config-path mount in cilium-agent container
```release-note
```

Automated cherry pick of #17319: Remove cilium-config-path mount in cilium-agent container

---

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template

Cherry pick of #17336 on release-1.32.
#17336: fix(cilium): operator prometheus port
```release-note
```

Automated cherry pick of #17336: fix(cilium): operator prometheus port

---

pkg/apis/kops/validation/legacy.go

Upgrade jobs to latest k/k are failing because the validation was still being enforced for k8s 1.33.0-beta.1:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kops/17319/pull-kops-e2e-aws-upgrade-k130-ko130-to-klatest-kolatest-many-addons/1908282150768087040
This updates the logic to skip pre-releases that included the flag removal (https://github.com/kubernetes/kubernetes/commit/2382c0125b3c8a55e9963fd3e663a3c1c25819a2)

Support 1.33 pre-releases with --cloud-provider flag removal validation

---

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template

pr #16800 changed the operator prometheus port to `9963`. However the config actually still has `operator-prometheus-serve-addr: ":6942"` which makes scraping the declared port not possible as the wrong port is discovered.
This pr simply fixes the config.

fix(cilium): operator prometheus port

---

pkg/model/components/gcpcloudcontrollermanager.go
tests/integration/update_cluster/ha_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content

The GCP CCM Image builds included a breaking change in https://github.com/kubernetes/cloud-provider-gcp/pull/825
until we can update our manifest to account for the change, lets pin to the last stable tag from https://console.cloud.google.com/artifacts/docker/k8s-staging-cloud-provider-gcp/us/gcr.io/cloud-controller-manager?invt=AbuPzg
ref: #17347

Pin GCP CCM image to v32.2.4

---

pkg/commands/toolbox_enroll.go

Ensure `kops toolbox enroll` verify if SSH keys are loaded before authenticate to the host.

toolbox: ensure SSH keys are loaded

---

pkg/model/components/gcpcloudcontrollermanager.go
tests/integration/update_cluster/ha_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/ha_gce/data/aws_s3_object_ha-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-bootstrap_content
tests/integration/update_cluster/many-addons-gce/data/aws_s3_object_minimal.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce/data/aws_s3_object_minimal-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_dns-none/data/aws_s3_object_minimal-gce.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb/data/aws_s3_object_minimal-gce-ilb.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_ilb_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_longclustername/data/aws_s3_object_minimal-gce-with-a-very-very-very-very-very-long-name.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_plb/data/aws_s3_object_minimal-gce-plb.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal_gce_private/data/aws_s3_object_minimal-gce-private.example.com-addons-gcp-cloud-controller.addons.k8s.io-k8s-1.23_content

Cherry pick of #17348 on release-1.30.
#17348: Pin GCP CCM image to v32.2.4
```release-note
```

Automated cherry pick of #17348: Pin GCP CCM image to v32.2.4

---

docs/networking/cilium.md
k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/networking.go
pkg/apis/kops/v1alpha2/networking.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
pkg/apis/kops/v1alpha3/networking.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/zz_generated.deepcopy.go
pkg/apis/kops/zz_generated.deepcopy.go
pkg/model/components/cilium.go
tests/integration/update_cluster/minimal-ipv6-cilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal-warmpool/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/minimal_scaleway/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium-eni/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privatecilium2/data/aws_s3_object_cluster-completed.spec_content
tests/integration/update_cluster/privateciliumadvanced/data/aws_s3_object_cluster-completed.spec_content
upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.15.yaml.template

I have added the ability to set the `cni-exclusive` flag. It was hard-coded to be true before and it made it difficult to run service meshes like Istio(my usecase was to use ambient mode in istio which requires this flag to be false).
Here is the issue with more details: #17352
This is my first PR, please let me know if I have missed anything, I'll try my best to make this smooth for the maintainers. Thanks!

feat: Added cni-exclusive setting for cilium

---

k8s/crds/kops.k8s.io_clusters.yaml
pkg/apis/kops/componentconfig.go
pkg/apis/kops/v1alpha2/componentconfig.go
pkg/apis/kops/v1alpha2/zz_generated.conversion.go
pkg/apis/kops/v1alpha3/componentconfig.go
pkg/apis/kops/v1alpha3/zz_generated.conversion.go

Cherry pick of #17357 on release-1.32.
#17357: add goaway-chance parameter for kube-apiserver
```release-note
```

Automated cherry pick of #17357: add goaway-chance parameter for kube-apiserver

---

tests/e2e/pkg/tester/skip_regex.go

Bump skip.regex for failing tests to 1.34

---

tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
upup/pkg/fi/cloudup/gcetasks/backend_service.go
upup/pkg/fi/cloudup/gcetasks/healthcheck.go

kops' cloudup target for creating/updating a GCE cluster creates a regional backend service, which is on par with the forwarding rule being regional. The Terraform target however creates a global backend service and a regional forwarding rule, a combination that's not supported by GCP.
This PR aligns the Terraform target to the cloudup one and fixes the failing `terraform apply`.

Make GCE backend service regional for the Terraform target

---

tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
upup/pkg/fi/cloudup/gcetasks/backend_service.go
upup/pkg/fi/cloudup/gcetasks/healthcheck.go

Cherry pick of #17229 on release-1.32.
#17229: Make GCE backend service regional for the Terraform target
```release-note
```

Automated cherry pick of #17229: Make GCE backend service regional for the Terraform target

---

upup/pkg/fi/dryrun_target.go

We weren't correctly checking for bool differences,
so we would print things like `field: false -> false`

Fix diff formatting of bools

---

nodeup/pkg/model/kubelet.go

Several periodic tests are failing due to the removal of the --cloud-provider flag
https://github.com/kubernetes/kubernetes/pull/130161
Failing tests:
https://github.com/kubernetes/kubernetes/issues/130849
Code change modeled after the removal of the flag from the api-server
https://github.com/kubernetes/kops/commit/1f6ea4fc7519a3d9567e14cb96a5c3e7003b1912#diff-f81768b75ea2816be1479eac878f905b34b772f08c233164966f7fbe237d91b1

Remove cloud-config and cloud-provider from 1.33 kubelet

---

nodeup/pkg/model/networking/amazon-vpc-routed-eni.go

Cherry pick of #17398 on release-1.32.
#17398: Set MACAddressPolicy=none for Ubuntu 24.04
```release-note
```

Automated cherry pick of #17398: Set MACAddressPolicy=none for Ubuntu 24.04

---

nodeup/pkg/model/networking/amazon-vpc-routed-eni.go

[known issues](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md#known-issues) in the  vpc cni project mention:
> The workaround for this issue is to set MACAddressPolicy=none, as shown https://github.com/aws/amazon-vpc-cni-k8s/issues/2103#issuecomment-1321698870. This issue is known to affect Ubuntu 22.04+, and long-term solutions are being evaluated.
Kops was only setting this on 22.04, and we've seen similar pod connectivity issues with 24.04. So we'll try setting the same workaround for 24.04.

Set MACAddressPolicy=none for Ubuntu 24.04

---

pkg/model/gcemodel/storageacl.go

Keep track of already visited service accounts, using the email as the index, in order to avoid creating duplicate bucket IAM tasks.
This fixes a regression introduced in 65aba4e, where switching from email to the entire ServiceAccount object as index subkey would cause set `serviceAccountRoles` to have as many items as the amount of `InstanceGroups`, some of them referencing the same service account if they belong to the same role.
This in turn causes kops to attempt to build duplicate `StorageBucketIAM` tasks, such as object admin permission for control planes/etcd.
This was not an issue before due to implicitly avoiding duplicates by using the email as index subkey. The proposed fix is to reinstate this check, in a separate set.

GCE: avoid duplicate bucket IAM tasks for a single service account

---

docs/networking/cilium.md

The "CNI Exclusive" topic should come under "Configuring Cilium" instead of "Enabling Cilium ENI IPAM (IPv4 only)". Adjusted the placement of the topic.

[docs] fixed cilium cni exclusive topic placement

---

tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-bootstrap_content
tests/integration/update_cluster/minimal-ipv6-calico/data/aws_s3_object_minimal-ipv6.example.com-addons-networking.projectcalico.org-k8s-1.25_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-bootstrap_content
tests/integration/update_cluster/privatecalico/data/aws_s3_object_privatecalico.example.com-addons-networking.projectcalico.org-k8s-1.25_content
upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.25.yaml.template

Cherry pick of #17427 on release-1.32.
#17427: Upgrade calico to 3.29.4
```release-note
```

Automated cherry pick of #17427: Upgrade calico to 3.29.4

---

tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/many-addons-gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
upup/pkg/fi/cloudup/gcetasks/instancegroupmanager.go

This change makes it so that kops doesn't reset existing GCE managed instance groups `target_size` field on cluster updates, making it a "set once at creation" parameter.
The reason for this proposal is the following:
It is more consistent with the AWS model, where autoscaling groups do not have a `desired_capacity` value set, and instead set the initial ASG size at creation time based on `min_size` value. GCE's API does not support min and max sizes for MIGs, so `target_size` has to be set at least once.
The respective implementations on direct cloud and Terraform targets make `target_size` behave like AWS' `min_size`. This way, kops does not interfere with any external MIG size changes (e.g. from `cluster-autoscaler`).

GCE: do not reset MIG target size on cluster updates

---

Makefile

The `channels-install` and `nodeup-install` rules were mistakenly declared with a lowercase `.phony` directive.  
Only the uppercase special target `.PHONY` tells GNU make to run the rule unconditionally; with the typo, the targets could be skipped if files named `channels-install` or `nodeup-install` existed, breaking local builds or CI.
This patch capitalises the directive:
* `.PHONY: channels-install`
* `.PHONY: nodeup-install`
Restores proper phony-target behaviour and guarantees reliable installation of the `channels` and `nodeup` binaries.

Makefile: correct .PHONY casing

---

nodeup/pkg/model/networking/amazon-vpc-routed-eni.go
nodeup/pkg/model/networking/cilium.go

Cherry pick of #17438 on release-1.32.
#17438: add systemd network config for Cilium and Amazon VPC CNI on Ubuntu 22.04+ and AL2023 to prevent route removal
```release-note
```

Automated cherry pick of #17438: add systemd network config for Cilium and Amazon VPC CNI on Ubuntu 22.04+ and AL2023 to prevent route removal

---

tests/integration/update_cluster/ha_gce/kubernetes.tf
tests/integration/update_cluster/many-addons-gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce/kubernetes.tf
tests/integration/update_cluster/minimal_gce_dns-none/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_ilb_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_longclustername/kubernetes.tf
tests/integration/update_cluster/minimal_gce_plb/kubernetes.tf
tests/integration/update_cluster/minimal_gce_private/kubernetes.tf
upup/pkg/fi/cloudup/gcetasks/instancegroupmanager.go

Cherry pick of #17441 on release-1.31.
#17441: GCE: do not reset MIG target size on cluster updates
```release-note
```

Automated cherry pick of #17441: GCE: do not reset MIG target size on cluster updates

---

cmd/kops/toolbox_addons.go
docs/cli/kops_toolbox_addons_apply.md

Currently, when running `kops toolbox addons apply <some-channel>` user is instructed to supply non-supported flag `Must specify --yes to update`.
This change will allow to use the command the same way as in `channels/pkg/cmd/apply_channel.go`.

Fix toolbox addons apply command

---

.github/workflows/e2e.yml

Skip tests-e2e-scenarios-bare-metal when `version.go` changes

---

.github/workflows/e2e.yml

Cherry pick of #17391 on release-1.32.
#17391: Skip tests-e2e-scenarios-bare-metal when `version.go` changes
```release-note
```

Automated cherry pick of #17391: Skip tests-e2e-scenarios-bare-metal when `version.go` changes

---

pkg/clouds/supported.go
util/pkg/vfs/context.go

hetzner: Add support for Object Storage

---

cloudbuild.yaml
go.mod
hack/go.mod
tests/e2e/go.mod
tools/otel/traceserver/go.mod

Cherry pick of #17456 on release-1.31.
#17456: Update golang to 1.23.10
```release-note
```

Automated cherry pick of #17456: Update golang to 1.23.10

---

cmd/kops/delete_instance.go
cmd/kops/export_kubeconfig.go
cmd/kops/get_instances.go
cmd/kops/rolling-update_cluster.go
cmd/kops/toolbox_enroll.go
cmd/kops/update_cluster.go
cmd/kops/util/factory.go
cmd/kops/validate_cluster.go
docs/cli/kops_delete_instance.md
docs/cli/kops_export_kubeconfig.md
docs/cli/kops_get_instances.md
docs/cli/kops_rolling-update_cluster.md
docs/cli/kops_toolbox_enroll.md
docs/cli/kops_update_cluster.md
docs/cli/kops_validate_cluster.md
pkg/commands/commandutils/factory.go
pkg/commands/toolbox_enroll.go
pkg/kubeconfig/create_kubecfg.go
pkg/kubeconfig/create_kubecfg_test.go

Cherry pick of #17459 on release-1.32.
#17459: Create flag api-server which allows for custom DNS setups
```release-note
```

Automated cherry pick of #17459: Create flag api-server which allows for custom DNS setups

---

pkg/model/gcemodel/autoscalinggroup.go
tests/integration/update_cluster/ha_gce/data/aws_s3_object_nodeupconfig-nodes_content
tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_nodes-ha-gce-example-com_metadata_user-data
tests/integration/update_cluster/ha_gce/in-v1alpha2.yaml
tests/integration/update_cluster/ha_gce/kubernetes.tf

This proposed change sets `InstanceGroup` node labels and taints in `kube-env` on GCP, so that autoscaler can make a scale-up decision based on taints and tolerations, and that the resulting node has the labels set.

GCE: set node labels and taints as autoscaler env vars

---

docs/releases/1.22-NOTES.md

Add a note in 1.22 changelog about https://github.com/kubernetes/kops/pull/11921 et al's CA changes
- this broke some of my teams' automation code that relied on the CN, so thought it would be good to call out in case anyone else stumbles upon this in order to not spend a few hours debugging 😅 
- this change may particularly impact Prod environments, where the cluster has not been rebuilt in some time (years), and so they will have the old CN while new clusters in lower environments will have the new CN
- so code that relies on the CN may unexpectedly break Production while working fine in lower environments 😬 😬 😬 
- fortunately we caught this in our QA env, but it passed Dev fine
From an internal fix my team made to another team's automation:
(We've recommend they pull the CA from …

docs: Add note to 1.22 about the CA CN rename

---

cloudmock/openstack/mocknetworking/ports.go
upup/pkg/fi/cloudup/openstack/cloud.go
upup/pkg/fi/cloudup/openstack/cloud_test.go

This will determine the ports to delete when deleting an InstanceGroup in OpenStack based on the tags, rather than comparing the prefix of the name of the port to a pattern.
The current approach for deleting ports associated with an InstanceGroup in OpenStack can be problematic.
For example, when creating an InstanceGroup called `worker` and another one called `worker-2`. Some of the ports kOps creates for those groups will look like this:
* `port-worker-2-1-<clusterName>`
* `port-worker-2-2-<clusterName>`
* `port-worker-1-<clusterName>`
* `port-worker-2-<clusterName>`
* `port-worker-20-<clusterName>`
Deleting the `worker-2` IG will ultimately delete all the ports prefixed with `port-worker-2`, which means that kOps will also delete ports of the `worker` IG.
TODO:

fix(openstack): determine ports to delete based on tags

---

pkg/model/components/apiserver.go
pkg/model/components/kubelet.go

Cherry pick of #17482 on release-1.33.
#17482: Fix cloud-provider flag for K8s 1.31+
```release-note
```

Automated cherry pick of #17482: Fix cloud-provider flag for K8s 1.31+

---

cmd/kops/update_cluster.go

This warning isnt particularly actionable - it is expected behavior for `kops create cluster` and any `kops update cluster` that experiences this (due to a broken cluster) will proceed as normal. The user's subsequent `kops validate cluster` would surface any such errors
ref: https://github.com/kubernetes/kops/issues/17146#issuecomment-3076579856

Reduce verbosity of k8s version warning

---

upup/pkg/fi/cloudup/awstasks/securitygroup.go

Cherry pick of #17500 on release-1.33.
#17500: Fix invalid filters for describing security group rules
```release-note
```

Automated cherry pick of #17500: Fix invalid filters for describing security group rules

---

upup/pkg/fi/cloudup/defaults.go

chore: Use constants for default network CIDRs

---

upup/pkg/fi/cloudup/gcetasks/disk.go

Cherry pick of #17512 on release-1.32.
#17512: Wait for the GCE disk creation operation to finish
```release-note
```

Automated cherry pick of #17512: Wait for the GCE disk creation operation to finish

---

cmd/kops/create_cluster.go
tests/e2e/kubetest2-kops/deployer/common.go
upup/pkg/fi/cloudup/azure/verifier.go
upup/pkg/fi/cloudup/azuretasks/vmscaleset.go
upup/pkg/fi/cloudup/azuretasks/vmscaleset_test.go
upup/pkg/fi/cloudup/new_cluster.go

Ref: https://testgrid.k8s.io/kops-network-plugins#kops-azure-cni-cilium
> Resource name control-plane-uksouth-1.masters.e2e-e2e-kops-azure-cni-cilium.k8s.local-netconfig is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'.
/cc @ameukam @rifelpet

azure: Fix periodic tests

---

tests/e2e/kubetest2-kops/deployer/common.go
tests/e2e/pkg/tester/skip_regex.go

Broken in https://github.com/kubernetes/kops/commit/553509bd46c4525f187cdc8e75891e2b7f761885
```diff
-       return fmt.Sprintf("%v.%v", jobName, suffix), nil
+
+       if suffix != "" {
+               jobName = jobType + "." + suffix
+       }
+
+       return jobName, nil
```

testing: Fix e2e test job name

---

upup/pkg/fi/cloudup/terraformWriter/writer.go

The terraform e2e tests are failing at this log line:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/e2e-kops-scenario-ipv6-terraform/1949972594287448064#1:build-log.txt%3A357
This function can only be called in 3 places: s3fs, memfs, and gsfs
https://github.com/search?q=repo%3Akubernetes%2Fkops%20EnsureTerraformProvider&type=code
The gsfs and s3fs arguments should always be identical, leading me to believe we're somehow referencing a memfs:// file in the e2e test.
I'm hoping this additional logging helps troubleshoot.

Add more context to terraform fatal log

---

tests/e2e/scenarios/aws-lb-controller/run-test.sh

This was failing because the AMI is no longer discoverable:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/e2e-kops-aws-aws-load-balancer-controller/1950309628495532032
Since we dont update these jobs regularly, we can just use the SSM parameter already used by other e2e jobs: https://github.com/search?q=repo%3Akubernetes%2Fkops+%2Faws%2Fservice%2Fcanonical%2Fubuntu%2Fserver&type=code

Use ssm parameter for AMI ID in LBC scenario

---

tests/e2e/pkg/tester/skip_regex.go

Cherry pick of #17523 on release-1.32.
#17523: testing: Fix e2e test job name
```release-note
```

Automated cherry pick of #17523: testing: Fix e2e test job name

---

docs/metal.md
tests/e2e/scenarios/bare-metal/start-vms

Cherry pick of #17531 on release-1.32.
#17531: metal: Update Debian image
```release-note
```

Automated cherry pick of #17531: metal: Update Debian image

---

.github/workflows/e2e.yml

Similar to https://github.com/kubernetes/kops/pull/17391

Skip tests-e2e-scenarios-bare-metal-ipv6 when `version.go` changes

---

util/pkg/distributions/identify.go
util/pkg/distributions/identify_test.go
util/pkg/distributions/tests/debian13/etc/os-release

The Debian 13 `Distribution` was added in https://github.com/kubernetes/kops/pull/16963 but missed adding the check to recognize it.

Recognize Debian 13

---

util/pkg/distributions/identify.go
util/pkg/distributions/identify_test.go
util/pkg/distributions/tests/debian13/etc/os-release

Cherry pick of #17550 on release-1.33.
#17550: Recognize Debian 13
```release-note
```

Automated cherry pick of #17550: Recognize Debian 13

---

nodeup/pkg/model/packages.go
util/pkg/distributions/distributions.go

According to https://tracker.debian.org/pkg/cgroupfs-mount, the package has been removed starting with Debian 13

Install cgroupfs-mount for distros lower than Debian Trixie

---

nodeup/pkg/model/packages.go

NFtables proxy mode is GA in Kubernetes 1.33. See: https://kubernetes.io/blog/2025/02/28/nftables-kube-proxy/

Add nftables package

---

nodeup/pkg/model/packages.go

Those packages are no longer required according to:
- https://github.com/kubernetes/kubernetes/pull/127151
- https://github.com/kubernetes/kubernetes/pull/129131

Drop ebtables, ethtool and socat

---

nodeup/pkg/model/packages.go
util/pkg/distributions/distributions.go

Cherry pick of #17581 on release-1.33.
#17581: Install cgroupfs-mount for distros lower than Debian
```release-note
```

Automated cherry pick of #17581: Install cgroupfs-mount for distros lower than Debian

---

upup/models/cloudup/resources/addons/azure-cloud-node.addons.k8s.io/k8s-1.31.yaml.template

**cloud-node-manager** needs to be able to remove the `node.cloudprovider.kubernetes.io/uninitialized` taint, before the CNI can run (e.g. `cilium-operator`).
/cc @ameukam

azure: Use internal K8s API endpoint for cloud-node-manager

---

pkg/model/awsmodel/api_loadbalancer.go
pkg/model/awsmodel/autoscalinggroup.go
pkg/wellknownservices/wellknownservices.go

In newer versions of cilium, all agents require access to the dedicated etcd cluster.
/cc @ameukam @rifelpet

Add support for `cilium-etcd` with `dns=none`

---

nodeup/pkg/model/containerd.go

Based on https://github.com/kubernetes/kops/pull/9584 which was removed together with Docker support.
Alternative to https://github.com/kubernetes/kops/pull/17579.
/cc @jsafrane @ameukam

Restore default SELinux security contexts for containerd binaries
