- docs/addons.md
line33: RBAC is Proper nouns, should be capitalized, thanks
> fix :"rbac" should be "RBAC"

- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/pre-k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
> upgrade kube-dns to 1.14.10, fixes #4986

- docs/apireference/build/index.html
- docs/instance_groups.md
- pkg/apis/kops/cluster.go
- pkg/apis/kops/instancegroup.go
- pkg/apis/kops/v1alpha1/cluster.go
- pkg/apis/kops/v1alpha1/instancegroup.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/instancegroup.go
- pkg/model/resources/nodeup.go
> Typo fix aditional->additional

- cmd/kops/create.go
- cmd/kops/delete.go
- cmd/kops/replace.go
Fixes #4149 
Also adds delete and cleans up a few things.
> Add Replace and delete for SSH Secret YAML

- README-ES.md
- README.md
Update readme docs for 1.9 and a little cleanup
Fixes https://github.com/kubernetes/kops/issues/5046
> Update readme for 1.9

- docs/releases/1.9-NOTES.md
Line 294: compatability->compatibility
> Typo fix in 1.9-NOTES.md: compatability->compatibility

- docs/vsphere-development-status.md
> Typo fix in vsphere-development-status.md: secrete->secret

- docs/terraform.md
Please keep in mind that english is not my native language! I'm happy to rephrase this in a different way 😄 
-----
Closes https://github.com/kubernetes/kops/issues/4740
cc @mikesplain
> Note that `kops rolling-update` is required after tf apply

- docs/apireference/build/documents/_generated_accessspec_v1alpha2_kops_definition.md
- docs/apireference/build/index.html
- pkg/apis/kops/v1alpha1/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
> Typo fix: wil->will

- cmd/kops/create_cluster.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/lifecycle.go
fix 3 typos:
acutally->actually
overide->override
to to->to
> Typo fix: acutally->actually/overide->override/to to->to

- docs/apireference/build/index.html
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha1/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
> Typo fix detaults->defaults

- cmd/kops/validate.go
- docs/cli/kops_validate.md
- docs/cli/kops_validate_cluster.md
> Typo fix: healthly->healthy

- pkg/model/iam/iam_builder.go
- pkg/model/iam/iam_builder_test.go
- pkg/model/iam/tests/iam_builder_bastion.json
- pkg/model/iam/tests/iam_builder_master_legacy.json
- pkg/model/iam/tests/iam_builder_master_strict.json
- pkg/model/iam/tests/iam_builder_master_strict_ecr.json
- pkg/model/iam/tests/iam_builder_node_legacy.json
- pkg/model/iam/tests/iam_builder_node_strict.json
- pkg/model/iam/tests/iam_builder_node_strict_ecr.json
- tests/integration/update_cluster/additional_user-data/cloudformation.json
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json
>  Remove custom Statement IDs from IAM Policy Statements

- cmd/kops/toolbox_template.go
> Typo fix in returned message: formated->formatted

- cmd/kops/rollingupdatecluster.go
- docs/cli/kops_rolling-update_cluster.md
This is important for the e2e upgrade tests
> Allow rolling-update to filter on roles

- pkg/model/network.go
- upup/pkg/fi/cloudup/awstasks/instance.go
We don't need to (and we can add it later if we do)
Also clean up the Name tag
> Don't tag shared instances at all

- docs/advisories/cve_2017_14491.md
line 56-60 Because N/A means " Not Applicable",Abbreviation is not easy to understand
> fix:please N/A should be " Not Applicable"

- pkg/apis/kops/validation/legacy.go
> Re-enable validation of DNS ServerIP

- docs/instance_groups.md
Fix a typo:
Line 109:  recieve->receive
> [instance_groups.md] typo: recieve->receive

- upup/pkg/fi/nodeup/nodetasks/package.go
> Typo fix in the returned message: runnning->running

- nodeup/pkg/model/kube_controller_manager.go
- locking down the ca.key somewhat by forcing the file permissions to 0600
> CA Key File Permissions

- channels/alpha
> Update alpha channel with latest k8s versions

- .gitignore
- addons/prometheus-operator/README.md
- addons/prometheus-operator/addon.yaml
- addons/prometheus-operator/sync-repo.sh
- addons/prometheus-operator/v0.19.0.yaml
- docs/addons.md
This addon setup prometheus operator and kube-prometheus
> Create addon for prometheus-operator

- addons/cluster-autoscaler/README.md
Fixing name of certificate file in the documentation. Also adding clarification for ASG group name.
> Fixing name of cert file

- nodeup/pkg/model/context.go
> Typo fix: are be->are

- cmd/kops/completion.go
> Add proper autoloading for kops autocomplete

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
> Add AuthenticationTokenWebhook flag

- nodeup/pkg/model/kube_apiserver.go
- adjusting the file permissions on the heptio authenticator to 0600
> File Permissions Private Key

- cmd/kops/BUILD.bazel
- cmd/kops/toolbox_bundle.go
- upup/pkg/fi/utils/BUILD.bazel
- upup/pkg/fi/utils/sanitize.go
- util/pkg/vfs/BUILD.bazel
- util/pkg/vfs/swiftfs.go
Works on windows & linux
Fixes #4523
> Use HomeDir from client-go to get home directory

- nodeup/pkg/model/docker.go
Equivalent of https://github.com/kubernetes/kubernetes/pull/51986
> docker: Set TasksMax to infinity

- Makefile
> Perf fix for makefile

- Gopkg.lock
- Gopkg.toml
- WORKSPACE
- vendor/github.com/bazelbuild/bazel-gazelle/cmd/gazelle/BUILD.bazel
- vendor/github.com/bazelbuild/bazel-gazelle/cmd/gazelle/fix-update.go
- vendor/github.com/bazelbuild/bazel-gazelle/internal/generator/BUILD.bazel
- vendor/github.com/bazelbuild/bazel-gazelle/internal/generator/construct.go
- vendor/github.com/bazelbuild/bazel-gazelle/internal/generator/doc.go
- vendor/github.com/bazelbuild/bazel-gazelle/internal/generator/generator.go
- vendor/github.com/bazelbuild/bazel-gazelle/internal/generator/sort_labels.go
- vendor/github.com/bazelbuild/bazel-gazelle/internal/merger/fix.go
- vendor/github.com/bazelbuild/bazel-gazelle/internal/merger/merger.go
- vendor/github.com/bazelbuild/bazel-gazelle/internal/repos/BUILD.bazel
- vendor/github.com/bazelbuild/bazel-gazelle/internal/repos/repo.go
- vendor/github.com/bazelbuild/bazel-gazelle/internal/resolve/resolve.go
- vendor/google.golang.org/genproto/googleapis/api/annotations/BUILD.bazel
Update bazel gazelle for the latest version.
> Update bazel gazelle

- tests/integration/update_cluster/existing_iam/kubernetes.tf
- tests/integration/update_cluster/privatekopeio/kubernetes.tf
> Update expected TF output for latest master

- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/BUILD.bazel
> Fixup bazel

- cmd/kops/root.go
Tweaks so that we are stricter about how we use viper config file
discovery.  By being more explicit we are less dependent on its
specific behaviour.
> Use less viper discovery

- cmd/kops/create_cluster.go
- docs/cli/kops_create_cluster.md
> Don't autoload SSH key on GCE

- nodeup/pkg/model/calico.go
- just cleaning up the path concat to use filepath.Join() rather then string formats
> Code Clean

- nodeup/pkg/model/convenience.go
- nodeup/pkg/model/kube_apiserver.go
- removing the duplication code (i think by me :-)) and reusing the BuildCertificateTaskd and BuildPrivateKeyTask
> Removing Duplication

- nodeup/pkg/model/docker.go
Only clear the flag if there is a docker config file, so that we can
continue to set the storage flag on older COS images.  We could be
smarter about checking if the storage driver is actually set in the
docker config, but for now we just start by logging it.
Issue #5358
> GCE: Handle storage flag on COS more carefully

- nodeup/pkg/model/directories.go
- nodeup/pkg/model/file_assets.go
- nodeup/pkg/model/firewall.go
- nodeup/pkg/model/kube_apiserver.go
- nodeup/pkg/model/kube_controller_manager.go
- nodeup/pkg/model/kube_proxy.go
- nodeup/pkg/model/kube_router.go
- nodeup/pkg/model/kube_scheduler.go
- nodeup/pkg/model/kubectl.go
- nodeup/pkg/model/logrotate.go
- nodeup/pkg/model/network.go
- nodeup/pkg/model/packages.go
- nodeup/pkg/model/protokube.go
- nodeup/pkg/model/secrets.go
- nodeup/pkg/model/sysctls.go
Cleaning up elements in the nodeup command. Separated into logical commits to make reviewing eaiser
- https://github.com/kubernetes/kops/commit/6188ca559f17492695eb49a007f6d33aba1c7b68 removes the duplicates methods
- https://github.com/kubernetes/kops/commit/90676da61377fed78bca2a250d8a11578dd569c8 cleans up some imports, comments and formatting etc
- https://github.com/kubernetes/kops/pull/5352/commits/2256a2c588c417374c773261664097979690e9cb fixing up the issues highlighted in the review
> Nodeup clean

- pkg/apis/kops/dockerconfig.go
- pkg/apis/kops/v1alpha1/dockerconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/dockerconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- adding the userspace remap options for docker daemon
> Docker Userspace Remapping Options

- hack/.packages
- pkg/resources/ali/BUILD.bazel
- pkg/resources/ali/ali.go
To support clearing cluster resources when deleting a cluster.
> delete cluster resources for ALicloud

- pkg/model/iam/iam_builder.go
- pkg/model/iam/tests/iam_builder_master_strict.json
- pkg/model/iam/tests/iam_builder_master_strict_ecr.json
> Add IAM ec2:ModifyVolume permission to allow EBS volume resize

- docs/cluster_spec.md
> Update Audit file example

- nodeup/pkg/model/kube_apiserver.go
> Don't mount volume for auditLog when STDOUT is configured as path

- addons/cluster-autoscaler/README.md
- addons/cluster-autoscaler/cluster-autoscaler.sh
Create a more complete cluster-autoscaler installation script based on https://github.com/kubernetes/autoscaler/issues/110 which will automate the installation of the IAM Policy.
> add cluster-autoscaler.sh

- cmd/kops/create_secret_weave_encryptionconfig.go
- docs/cli/kops_create_secret_weavepassword.md
- docs/networking.md
Addresses the enhancements proposed by @justinsb in #5441
> Generate random weave password it none is supplied

- cmd/kops/integration_test.go
- pkg/model/bootstrapscript_test.go
Rename to HACK_UPDATE_EXPECTED_IN_PLACE as it isn't just terraform any more.
> More autofix of expected test output

- pkg/model/resources/nodeup.go
- pkg/model/tests/data/bootstrapscript_0.txt
- pkg/model/tests/data/bootstrapscript_1.txt
- pkg/model/tests/data/bootstrapscript_2.txt
- pkg/model/tests/data/bootstrapscript_3.txt
- pkg/model/tests/data/bootstrapscript_4.txt
- pkg/model/tests/data/bootstrapscript_5.txt
- tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
Only delete if the file doesn't match the hash.
Should help with retry issues / bandwidth
> Don't repeatedly download nodeup

- docs/state.md
Update the paths, and add a concrete example of a configuration file.
> Update docs for config file

- hack/verify-apimachinery.sh
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
> have travis fail when verify-apimachinery.sh fails and fix incompatible apimachinery

- pkg/assets/builder.go
- pkg/assets/builder_test.go
The OptionLoader currently builds the cluster config multiple times until it converges.
This causes the etcd image to be processes multiple times by the asset builder, remapping it every time.
Because of this, the config never converges and the `cluster edit` fail after max_iterations when `containerRegistry` is configured.
This change makes the remapping of `containerRegistry` atomic, preventing this issue.
Fixes #5061
> ContainerRegistry remapping should be atomic

- upup/pkg/fi/cloudup/awsup/machine_types.go
https://github.com/kubernetes/kops/issues/5527
https://github.com/kubernetes/kops/issues/5451
> Add new instance types r5, r5d, z1d

- pkg/model/iam.go
- tests/integration/update_cluster/additional_user-data/cloudformation.json
- tests/integration/update_cluster/additional_user-data/in-v1alpha2.yaml
Note though that I pulled the primary fix out as #5533, for easier cherry-picking.
> Some tweaks around IAM additional policies

- cmd/kops/integration_test.go
Another place where this was useful!
> Add HACK_UPDATE_EXPECTED_IN_PLACE for cloudformation output

- cmd/kops/BUILD.bazel
- cmd/kops/create_ig.go
- cmd/kops/edit_cluster.go
- cmd/kops/edit_instancegroup.go
- hack/.packages
- pkg/try/BUILD.bazel
- pkg/try/files.go
We create a helper package `try`
> Add error handling for failed deletion of tempfiles

- cmd/kops/toolbox_bundle.go
- cmd/kops/toolbox_template.go
- nodeup/pkg/model/BUILD.bazel
- nodeup/pkg/model/cloudconfig.go
- pkg/try/files.go
- util/pkg/hashing/BUILD.bazel
- util/pkg/hashing/hash.go
- util/pkg/vfs/BUILD.bazel
- util/pkg/vfs/fs.go
More missing error handling
Follows on from #5543
> Add error handling (logging) when we fail to close a file

- upup/models/cloudup/resources/addons/node-authorizer.addons.k8s.io/k8s-1.10.yaml.template
- adding the prometheus metrics annotations to the deployment
> Node Authorizer Prometheus Metrics

- upup/pkg/fi/cloudup/awstasks/load_balancer.go
Fixes https://github.com/kubernetes/kops/issues/5574
> Fix additional security groups changes on api lb

- upup/pkg/fi/cloudup/awsup/machine_types.go
Cherry pick of #5529 onto release-1.10
> Cherry pick of #5529 onto release-1.10

- pkg/model/iam/iam_builder.go
- pkg/model/iam/tests/iam_builder_master_legacy.json
- pkg/model/iam/tests/iam_builder_master_strict.json
- pkg/model/iam/tests/iam_builder_master_strict_ecr.json
- tests/integration/update_cluster/additional_cidr/cloudformation.json
- tests/integration/update_cluster/additional_user-data/cloudformation.json
- tests/integration/update_cluster/externallb/cloudformation.json
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json
> Cherry pick of #5566 onto release-1.10

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
> Cherry pick of #5508 onto release-1.10

- pkg/model/iam/iam_builder.go
- pkg/model/iam/tests/iam_builder_master_strict.json
- pkg/model/iam/tests/iam_builder_master_strict_ecr.json
> Cherry pick of #5597 onto release-1.10

- upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
> Cherry pick of #5595 onto release-1.10

- pkg/resources/aws/aws.go
- pkg/resources/dumpmodel.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
> Cherry pick of #5511 onto release-1.10

- docs/state.md
> Docs for policy to do cross account state store in s3

- docs/images.md
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
> Cherry pick of #5577 onto release-1.10

- upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
> Cherry pick of #5552 onto release-1.10

- pkg/apis/kops/validation/legacy.go
- pkg/featureflag/featureflag.go
- pkg/model/components/kubelet.go
> Cherry pick of #5610 onto release-1.10

- util/pkg/vfs/s3fs.go
> Cherry pick of #5625 onto release-1.10

- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
> Cherry pick of #5618 onto release-1.10

- upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
https://github.com/kubernetes/kops/issues/2150
https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/CHANGELOG.md#v017-beta---aug-1st-2018
> Upgrade DigitalOcean CCM to v0.1.7

- Makefile
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/pre-k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
- version.go
This is so that we pick up the latest nodeup for people building kops from source.
cc @geojaz
> Cherry-pick release 1.10.0 commit

- channels/alpha
> Push latest k8s versions to alpha channel

- docs/cluster_spec.md
Fixes https://github.com/kubernetes/kops/issues/4997
> Add etcd volumeSize docs

- docs/manifests_and_customizing_via_api.md
Fix a typo in line 308: ectd->etcd
> Fix a typo: ectd->etcd

- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
> Update CoreDNS version and manifest

- docs/instance_groups.md
- docs/networking.md
- docs/node_authorization.md
- docs/releases.md
- docs/single-to-multi-master.md
I'm so sorry to find those spell errors when I read `kops` documents. Maybe those change don't make sense. Perhaps I have obsessive-compulsive disorder, hahaha.
> correct 8 spell errors

- util/pkg/vfs/s3fs.go
Resolves https://github.com/kubernetes/kops/issues/5725
> Use appropriate log level for KOPS_STATE_S3_ACL debug message

- Makefile
- hack/machine_types/machine_types.go
- upup/pkg/fi/cloudup/awsup/machine_types.go
Keep go vet happy - address its complaints about error formatting
> machine-type generator: go vet fixes

- docs/horizontal_pod_autoscaling.md
Add comment that enable custom metrics has been removed on K8S 1.11+
> Update HPA docs

- docs/examples/kops-tests-private-net-bastion-host.md
Change occurrences of higly to highly
> doc: Trivial spelling change

- CONTRIBUTING.md
I found the broken url in `CONTRIBUTING.md` file!
> Fix broken url in CONTRIBUTING.md

- docs/download_config.md
I found the mis-typed documentation.
> Fix mis-typing in documentation

- docs/instance_groups.md
> Fix mis-typings in documentation.

- addons/prometheus-operator/v0.19.0.yaml
identifer -> identifier
defailt -> Default
default -> Default
Signed-off-by: Rui Cao <ruicao@alauda.io>
> Fix some typos

- docs/apireference/build/scroll.js
- pkg/apis/kops/cluster.go
- pkg/apis/kops/instancegroup.go
- pkg/systemd/unit_test.go
Fix typos issues in below files:
1. docs/apireference/build/scroll.js
2. pkg/apis/kops/cluster.go
3. pkg/apis/kops/instancegroup.go
4. pkg/systemd/unit_test.go
> Fix typos issues

- cmd/kops/create_cluster.go
- cmd/kops/create_secret_sshpublickey.go
- docs/cli/kops_create_cluster.md
Follow on to #5425; another flag and we need to update the source code
as well as the output.
> Update create-cluster arg help

- docs/networking.md
> fix network.md

- docs/install.md
> fix install.md

- channels/pkg/api/channel.go
@rdrgmnzs pointed out that the comment needed to be updated after
Removing!
> Removed misleading comment about metav1

- docs/development/homebrew.md
fix typo: remove duplicate words
> fix typo: remove duplicate words

- addons/kube-ingress-aws-controller/v1.0.0.yaml
> fix service name

- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Follow on to #5845
cc @bboreham
> Update weave bootstrapchannelbuilder version

- docs/manifests_and_customizing_via_api.md
- docs/node_resource_handling.md
- docs/terraform.md
Fix documents issues in below files:
1. docs/manifests_and_customizing_via_api.md
2. docs/node_resource_handling.md
3. docs/terraform.md
> Fix documents issue

- docs/security.md
Line 9: is be-> will be
Line 54: a existing->an existing
> fix small typos in security.md

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/validation/legacy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- adding the additional ipvs options to the kube proxy configuration
- adding a basic check in the network cidrs supplied
>  IPVS Options

- docs/networking.md
> Fix broken url in documentation

- docs/node_resource_handling.md
> Delete duplicate 'be'.

- addons/prometheus-operator/v0.19.0.yaml
- cmd/kops/validate_cluster.go
- docs/advisories/cve_2017_14491.md
- docs/development/testing.md
- docs/high_availability.md
- docs/networking.md
- nodeup/pkg/model/kubelet.go
I fixed some typos in this project.
> Fix the typos

- protokube/pkg/protokube/volume_mounter.go
We don't have any shared directories, and certainly not root!
> Fix nsenter mounter in protokube

- docs/networking.md
> Remove excess Spaces

- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Updates CoreDNS version to 1.2.4 and updates the manifest.
> Bump CoreDNS version to 1.2.4 and update manifest

- docs/apireference/build/tabvisibility.js
- pkg/apis/kops/instancegroup.go
- pkg/apis/kops/v1alpha1/instancegroup.go
- pkg/apis/kops/v1alpha2/instancegroup.go
Change the wrong function name and wrong word
> Change the wrong function name and wrong word

- docs/upgrade_from_kubeup.md
Correct the table format in upgrade_from_kubeup.md
the original format displays the table into normal text lines.
> Correct the table format in upgrade_from_kubeup.md

- upup/models/cloudup/resources/addons/networking.kope.io/k8s-1.6.yaml
- upup/models/cloudup/resources/addons/networking.kope.io/pre-k8s-1.6.yaml
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
Also add the RBAC permissions needed for operation on GCE.
> Bump kopeio-networking to latest version

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
As discussed here: https://github.com/kubernetes/kops/pull/5102#issuecomment-435566584
Updating to Calico v3.3.1
> Update Calico to v3.3.1

- channels/pkg/channels/channel_version.go
- cmd/kops/create.go
- dns-controller/pkg/dns/dnscache.go
- kube-discovery/cmd/kube-discovery/main.go
Delete some redundant code, save a space
> delete some code

- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
Changelog: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/CHANGELOG.md
> Update amazon-vpc-routed-eni to v1.2.1

- hack/machine_types/machine_types.go
- upup/pkg/fi/cloudup/awsup/machine_types.go
Fixes for duplicated instance types and for instances without ECUs
> Update machine types

- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha1/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/resources/aws/securitygroup.go
Fix typos: dnsmaq -> dnsmasq, mutiple -> multiple
> Fix typos: dnsmaq -> dnsmasq, mutiple -> multiple

- docs/addons.md
Relates to #3554 and #2399
I found no good info in the docs about how to:
1. specify addons to be created during cluster bootstrap
2. create a custom addon 
https://github.com/kubernetes/kops/blob/master/docs/authentication.md#aws-iam-authenticator mentions addons while bootstrapping which led me to research how this is done. But as mentioned, docs did not help with this at all.
> Document how to create a custom addon

- node-authorizer/pkg/server/middleware.go
- node-authorizer/pkg/server/server.go
- adding a recovery middles to capture panics
> Node Authorizer Recovery Middleware

- upup/pkg/kutil/import_cluster.go
Signed-off-by: gaozhenhai <gaozh1988@live.com>
> Fix log warning info

- nodeup/pkg/model/logrotate.go
Closes #5378.
On CoreOS Container Linux, `/usr/share/logrotate/logrotate.conf` (which is on a read-only mount) enables `dateext`, which causes maxsize-based log rotation to fail when a previous rotation already happened on the calendar same day. This has the undesirable effect that kube-system logs in /var/log grow unbounded until it dominates and fills up `/`.
> Set a `dateformat` on logrotate configs on CoreOS

- hack/machine_types/machine_types.go
And we write these warnings to the output, so that we can see them in
PR review.
> machine-type generator: Warn if instance type not in ENI map

- channels/alpha
> Bump alpha channel kubernetes versions

- cloudmock/aws/mockautoscaling/launchconfigurations.go
> Add missing locking to awsmock LaunchConfigurations

- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #6128 on release-1.11.
#6128: Update amazon cni to 1.3.0
> Automated cherry pick of #6128: Update amazon cni to 1.3.0

- docs/addons.md
Hello! Just a quick docs fix. Dashboard is now on release v1.10.0 :)
If you need anything else please let me know. Thanks!
> Update addons dashboard version

- WORKSPACE
Fixing some recent issues in Bazel, seems to work well for me!
> Workspace updates for bazel / fix tests

- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.8.0.yaml.template
- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.9.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #6129 on release-1.11.
#6129: feat: bump controller version to 1.0.18
> Automated cherry pick of #6129: feat: bump controller version to 1.0.18

- cmd/kops/upgrade_cluster.go
- docs/cli/kops_upgrade_cluster.md
Add -y as an option for upgrade command to be consistent with other commands
> Add y flag for upgrade command for consistency

- addons/prometheus-operator/README.md
- addons/prometheus-operator/addon.yaml
- addons/prometheus-operator/sync-repo.sh
- addons/prometheus-operator/v0.26.0.yaml
- docs/addons.md
bump prometheus-operator version and deploy file.
1、Supplementary introduction document
2、introduce new version
> bump prometheus-operator version and deploy file

- addons/monitoring-standalone/README.md
- addons/monitoring-standalone/v1.11.0.yaml
- docs/addons.md
bump heapster version and mark it retired
> update heapster version and mark it retired

- cmd/kops/validate_cluster.go
- pkg/validation/validate_cluster.go
Also log the names of the non-ready containers.
> Consider pending pods to be a validation failure

- addons/cluster-autoscaler/cluster-autoscaler.sh
This should make things run a little more smoothly on Macs.
> Automagically use curl instead of wget if that's what's available

- WORKSPACE
Cherry pick of #6144 on release-1.11.
#6144: Workspace updates for bazel
> Automated cherry pick of #6144: Workspace updates for bazel

- nodeup/pkg/model/kubelet.go
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
> Cherry pick of #6179 onto release-1.11

- upup/pkg/fi/cloud.go
> Cherry pick of #6152 onto release-1.11

- upup/pkg/fi/cloudup/awsup/machine_types.go
Cherry pick of #6253 on release-1.11.
#6253: Add p3dn.24xlarge
> Automated cherry pick of #6253: Add p3dn.24xlarge

- docs/releases/1.8-NOTES.md
> fixed the sentence mistake

- docs/releases/1.8-NOTES.md
I had to change it in a different place also. I missed it previous time.
> Change jessie to stretch

- channels/alpha
We're having some more stability with some of these changes so I think it's worth moving them into the alpha channel
> Bump alpha channels

- WORKSPACE
* Rules go
* Gazelle
* Docker Rules
> Update bazel rules

- upup/pkg/fi/cloudup/openstacktasks/floatingip.go
> recheck floatingip after server is active

- pkg/resources/aws/aws.go
> Guess SSH usernames for RHEL & Centos in toolbox dump

- nodeup/pkg/model/docker.go
Docker 17.x with rhel-family fails to detect overlay2 correctly, and
need us to pass overlay2.override_kernel_check=true for docker to
correctly detect overlay2 support.
> Workaround for overlay2 vs rhel-family docker bug

- upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
- upup/pkg/fi/cloudup/openstacktasks/floatingip.go
fixes #6494 
it seems that we need retry and wait that floatingip is in place in fresh cluster
/sig openstack
/cc @drekle
> retry l3floatingip list in fresh cluster

- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
- before I forget why, just adding a link to the issue as to why this here
> Adding Comment

- pkg/apis/kops/validation/cluster.go
> Cherry pick of #6180 onto release-1.11

- nodeup/pkg/model/docker.go
> Cherry pick of #6202 onto release-1.11

- WORKSPACE
> Cherry pick of #6401 onto release-1.11

- Makefile
- docker/Dockerfile
> Cherry pick of #6458 onto release-1.11

- docs/etcd/manager.md
- nodeup/pkg/model/BUILD.bazel
- nodeup/pkg/model/context.go
- nodeup/pkg/model/etcd_manager_tls.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- upup/pkg/fi/nodeup/command.go
> Cherry pick of #6411 onto release-1.11

- pkg/model/components/docker.go
> Cherry pick of #6488 onto release-1.11

- nodeup/pkg/model/docker.go
> Cherry pick of #6491 onto release-1.11

- nodeup/pkg/model/docker.go
- upup/pkg/fi/nodeup/nodetasks/BUILD.bazel
- upup/pkg/fi/nodeup/nodetasks/chattr.go
- upup/pkg/fi/nodeup/nodetasks/service.go
> Cherry pick of #6506 onto release-1.11

- nodeup/pkg/model/docker.go
> Cherry pick of #6338 onto release-1.11

- pkg/model/openstackmodel/servergroup.go
- upup/pkg/fi/cloudup/openstacktasks/instance.go
fixes issue #6533 
Before:
After:
/sig openstack
/cc @drekle please review
> spread instances equally to all AZs

- nodeup/pkg/model/sysctls.go
> Cherry pick of #6343 onto release-1.11

- nodeup/pkg/model/docker.go
> Cherry pick of #6461 onto release-1.11

- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
> Cherry pick of #6526 onto release-1.11

- pkg/model/components/docker.go
> Cherry pick of #6524 onto release-1.11

- nodeup/pkg/model/docker.go
- nodeup/pkg/model/docker_test.go
> Cherry pick of #6523 onto release-1.11

- nodeup/pkg/model/docker.go
After all the cherry-picks against this file, the state drifted a
little.  Resync with master (this shouldn't be version specific
anyway)
> Sync up docker with master

- WORKSPACE
> Cherry pick of #6287 onto release-1.11

- upup/pkg/fi/cloudup/openstack/instance.go
> implement delete instance, this is needed in rolling-update

- pkg/model/openstackmodel/BUILD.bazel
- pkg/model/openstackmodel/firewall.go
- pkg/model/openstackmodel/servergroup.go
- upup/pkg/fi/cloudup/openstack/cloud.go
- upup/pkg/fi/cloudup/openstack/port.go
- upup/pkg/fi/cloudup/openstacktasks/lb.go
- upup/pkg/fi/cloudup/openstacktasks/port.go
- upup/pkg/fi/cloudup/openstacktasks/securitygrouprule.go
Fixes:
https://github.com/kubernetes/kops/issues/6510
https://github.com/kubernetes/kops/issues/6511
/hold
I am currently experiencing an issue which seeing "duplicate security group rule exists" responses from openstack which I cannot easily explain.  I will test in another environment.
/sig openstack
> Openstack Security Group hardening

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
On merge of https://github.com/kubernetes/kops/pull/6277 the launchconfiguration or template is evaluated; where as before LC was just taken at face value, now the LC/LT is checked for existence. This causes an issue on rolling nodes, nodes where the LC has dissappeared due to retention or terminating instances
> Instance LaunchConfig/Template Bug Fix

- README.md
I find it that way much more easy to distinguish the Markings.
This is a suggestion, merge or reject at your wish. I'm okay with either.
> Replace Y / N Markings of Compatibility Matrix in readme with ✔ / ❌

- addons/cluster-autoscaler/cluster-autoscaler.sh
Hi, I added jq installation for OSX environment using Homebrew in cluster-autoscaler.sh
Thanks
> addons/cluster-autoscaler: Add jq installation for OSX environment

- cmd/kops/rollingupdatecluster.go
- docs/cli/kops_rolling-update_cluster.md
Cherry pick of #6185 on release-1.11.
#6185: Let a user specify the validation timeout when rotating a
> Automated cherry pick of #6185: Let a user specify the validation timeout when rotating a

- cmd/kops/BUILD.bazel
- cmd/kops/create.go
- cmd/kops/delete.go
- cmd/kops/replace.go
- hack/.packages
- pkg/kubemanifest/BUILD.bazel
- pkg/kubemanifest/manifest.go
- pkg/testutils/BUILD.bazel
- pkg/testutils/modelharness.go
- util/pkg/text/BUILD.bazel
- util/pkg/text/text.go
- util/pkg/text/text_test.go
kops replace/create/delete now correctly handle crlf in the manifest.
This fixes issue #6532
> Correcly handle CRLF in the manifest

- addons/metrics-server/v1.7.x.yaml
- addons/metrics-server/v1.8.x.yaml
- docs/single-to-multi-master.md
This is just the changes that aren't for backwards compatability, from
the bigger #4931
> Replace gcr.io URL with k8s.gcr.io vanity URL

- nodeup/pkg/model/docker.go
- nodeup/pkg/model/docker_test.go
Follow up to #6347 - add a test for some of the names based on some
heuristics, and fix some of the problems that popped up.
> Fix some of the docker package names & versions

- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
In #6502 we fixed an invalid CRD, but we need to fix in all versions. Also
bump the manifest version so it applies correctly!
> Apply scope fix in #6502 to all manifest versions

- cmd/kops/delete_cluster.go
- cmd/kops/export_kubecfg.go
- cmd/kops/update_cluster.go
- docs/cli/kops_export_kubecfg.md
- pkg/kubeconfig/create_kubecfg.go
- pkg/kubeconfig/kubecfg_builder.go
> Add --kubeconfig flag to `kops export kubecfg`

- upup/pkg/fi/cloudup/openstacktasks/instance.go
- upup/pkg/fi/cloudup/openstacktasks/subnet.go
This PR addresses issue:
#6649
by using an exact match for instance name in the tasks Find method.
/sig openstack
> Openstack server name collisions

- docs/download_config.md
> tiny backslash arrangement

- pkg/apis/kops/validation/legacy.go
- pkg/model/bootstrapscript.go
- pkg/model/components/apiserver.go
- pkg/model/components/kubecontrollermanager.go
- pkg/model/components/kubelet.go
- protokube/cmd/protokube/main.go
- upup/pkg/fi/cloudup/alitasks/vpc.go
- upup/pkg/fi/cloudup/populate_instancegroup_spec.go
- upup/pkg/fi/cloudup/tagbuilder.go
> add ALI flags

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
Picking up kopeio/etcd-manager#192, for #6562
> Bump etcd-manager / etcd-backup to 3.0.20190325

- pkg/model/awsmodel/api_loadbalancer.go
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/load_balancer.go
Fixes https://github.com/kubernetes/kops/issues/2048
Please let me know if I need to add tests and if so where? Not familiar with the code base, sorry.
Also should I merge the two maps being passed to AddELBTags calls into a single map and subsequently single call to AddELBTags?
Thanks
Please let me know if I need to add tests and if so where? Not familiar with the code base, sorry.
Also should I merge the two maps being passed to AddELBTags calls into a single map and subsequently single call to AddELBTags?
Thanks
> 2048 - Add cloudLabels as tags to API ELB resource

- WORKSPACE
> Upgrade rules go

- upup/pkg/fi/cloudup/networking.go
Equivalent of https://github.com/kubernetes/kubernetes/pull/75455
> Use CNI 0.7.5

- channels/alpha
- channels/stable
Bringing all the latest versions into the alpha channels
> Update alpha channel with other latest versions

- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go
Change to address https://github.com/kubernetes/kops/issues/6688
> Fix Key error change Overrides to Override

- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go
Cherry pick of #6689 on release-1.12.
#6689: Fix Key error change Overrides to Override
> Automated cherry pick of #6689: Fix Key error change Overrides to Override

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
> Cherry pick of #6682 onto release-1.12

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
> Cherry pick of #6695 onto release-1.12

- upup/pkg/fi/cloudup/networking.go
> Cherry pick of #6671 onto release-1.11

- pkg/model/awsmodel/api_loadbalancer.go
- pkg/model/bastion.go
- tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
- tests/integration/update_cluster/complex/kubernetes.tf
- tests/integration/update_cluster/existing_sg/kubernetes.tf
- tests/integration/update_cluster/lifecycle_phases/loadbalancer-kubernetes.tf
- tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
- tests/integration/update_cluster/privatecalico/kubernetes.tf
- tests/integration/update_cluster/privatecanal/kubernetes.tf
- tests/integration/update_cluster/privatedns1/kubernetes.tf
- tests/integration/update_cluster/privatedns2/kubernetes.tf
- tests/integration/update_cluster/privateflannel/kubernetes.tf
- tests/integration/update_cluster/privatekopeio/kubernetes.tf
- tests/integration/update_cluster/privateweave/kubernetes.tf
- tests/integration/update_cluster/unmanaged/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/load_balancer.go
- upup/pkg/fi/cloudup/awsup/aws_apitarget.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
Cherry pick of #6703 on release-1.12.
#6703: Fix tagging and remove tagging elbs
> Automated cherry pick of #6703: Fix tagging and remove tagging elbs

- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha1/cluster.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/BUILD.bazel
- pkg/model/components/kubedns.go
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #6719 on release-1.12.
#6719: Add DNS Resource Settings
> Automated cherry pick of #6719: Add DNS Resource Settings

- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Get things up-to-date for new instance types
> Update 1.3.0 to 1.3.3

- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #6723 on release-1.12.
#6723: Update 1.3.0 to 1.3.3
> Automated cherry pick of #6723: Update 1.3.0 to 1.3.3

- pkg/validation/validate_cluster.go
> Cherry pick of #6272 onto release-1.11

- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
> Cherry pick of #6740 onto release-1.12

- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Following updates to k8s 1.12 in k/k
> kube-dns: Update to 1.14.13

- nodeup/pkg/model/kube_apiserver.go
> Cherry pick of #6743 onto release-1.12

- channels/stable
> channels: promote alpha to stable

- nodeup/pkg/model/kube_apiserver.go
Fix #6702
Parallel to upstream issue #71054
> Increase apiserver timeout to 45 seconds

- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
> Cherry pick of #6741 onto release-1.12

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
Use LaunchTemplateName and Version when calculation if LaunchTemplate has changed.
> Use version number as well as name when checking LaunchTemplates

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
Cherry pick of #6753 on release-1.12.
#6753: User version number as well as name when checking
> Automated cherry pick of #6753: User version number as well as name when checking

- pkg/model/iam/iam_builder.go
Cherry pick of #6762 on release-1.12.
#6762: use dynamic s3 prefix in addAmazonVPCCNIPermissions func
> Automated cherry pick of #6762: use dynamic s3 prefix in addAmazonVPCCNIPermissions func

- Makefile
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/pre-k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
- version.go
Doing release 1.13.0-alpha.1 on the branch, but it's time to get the alpha releases on-deck!
> Release 1.14.0-alpha.1

- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
> Carry Provisioned IOPS to Terraform and CloudFormation templates

- hooks/nvidia-device-plugin/image/files/02-nvidia-docker.sh
https://github.com/kubernetes/kops/issues/6767
> pin nvidia-docker2 version to avoid installation failure

- WORKSPACE
Cherry pick of #6766 on release-1.14.
#6766: Update rules go
> Automated cherry pick of #6766: Update rules go

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- just adding another configurable parameter as we hit issues due to pod levels
> KubeAPIServer HTTP2 Stream Parameter

- docker/README.md
Signed-off-by: xichengliudui <liuduidui@beyondcent.com>
> Update docker README.md file, delete `$`

- pkg/model/iam.go
> Cherry pick of #6769 onto release-1.13

- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
> Cherry pick of #6776 onto release-1.13

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
> Cherry pick of #6787 onto release-1.13

- .travis.yml
- Makefile
- WORKSPACE
- docker/Dockerfile
- images/dns-controller-builder/Dockerfile
- images/protokube-builder/Dockerfile
For cherry-picking to 1.14
https://github.com/kubernetes/kubernetes/blob/release-1.14/build/build-image/cross/Dockerfile
> Switch to golang 1.12.1

- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
> Cherry pick of #6776 onto release-1.14

- pkg/model/iam.go
> Cherry pick of #6769 onto release-1.14

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
> Cherry pick of #6787 onto release-1.14

- pkg/assets/builder.go
- upup/pkg/fi/cloudup/loader.go
- upup/pkg/fi/dryrun_target.go
> Cherry pick of #6420 onto release-1.13

- Makefile
- hack/verify-bazel.sh
Cherry pick of #6841 on release-1.14.
#6841: Remove verify bazel from travis its run in prow
> Automated cherry pick of #6841: Remove verify bazel from travis its run in prow

- upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.11.yaml.template
> update openstack external cloud provider tolerations

- protokube/pkg/gossip/dns/hosts/BUILD.bazel
- protokube/pkg/gossip/dns/hosts/hosts.go
- protokube/pkg/gossip/dns/hosts/hosts_test.go
Cherry pick of #6893 without the glog/klog changes.
> Cherry pick of #6893 upstream release 1.12

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
> Cherry pick of #6737 onto release-1.12

- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha1/cluster.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.10.yaml.template
- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
> Cherry pick of #6730 onto release-1.12

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
Includes the fixes for concurrent file writes
> Update to etcd-manager 1.0.20190509

- docs/cluster_spec.md
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
> Cherry pick of #5961 onto release-1.12

- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
> Cherry pick of #6776 onto release-1.12

- upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.11.yaml.template
> Cherry pick of #6821 onto release-1.12

- pkg/apis/kops/cluster.go
> Cherry pick of #6840 onto release-1.12

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
> Cherry pick of #6357 onto release-1.12

- protokube/pkg/gossip/mesh/state.go
> Cherry pick of #6707 onto release-1.12

- .shipbot.yaml
> Cherry pick of #6680 onto release-1.12

- upup/pkg/fi/cloudup/populate_cluster_spec.go
> Cherry pick of #6641 onto release-1.12

- cmd/kops/integration_test.go
- tests/integration/update_cluster/additional_cidr/in-v1alpha3.yaml
- tests/integration/update_cluster/additional_cidr/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/vpccidrblock.go
> Cherry pick of #6693 onto release-1.12

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
> Cherry pick of #6917 onto release-1.12

- pkg/model/sshkey.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
- upup/pkg/fi/cloudup/awstasks/sshkey.go
Cherry pick of #6886 on release-1.13.
#6886: Based on the Readme, if you specify a SSHKeyName in the
> Automated cherry pick of #6886: Based on the Readme, if you specify a SSHKeyName in the

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
Cherry pick of #6917 on release-1.14.
#6917: Update to etcd-manager 3.0.20190509
> Automated cherry pick of #6917: Update to etcd-manager 3.0.20190509

- util/pkg/vfs/BUILD.bazel
- util/pkg/vfs/s3context.go
> Cherry pick of #6943 onto release-1.12

- pkg/model/openstackmodel/network.go
- upup/pkg/fi/cloudup/openstacktasks/subnet.go
Back porting the following change:
#6941
/sig openstack
/assign zetaab
> Subnet Update Consistency

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
> Cherry pick of #6959 onto release-1.12

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
> Cherry pick of #6959 onto release-1.14

- channels/alpha
- channels/stable
Put the latest image into both alpha & stable channels.
> Configure AMIs for 1.12

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
> Cherry pick of #6959 onto release-1.13

- nodeup/pkg/model/docker.go
> Cherry pick of #6965 onto release-1.12

- nodeup/pkg/model/docker.go
> Cherry pick of #6965 onto release-1.13

- nodeup/pkg/model/docker.go
> Cherry pick of #6965 onto release-1.14

- channels/alpha
Changelog: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#changelog-since-v1119
> bumped k8s 1.11 versions to 1.11.10 in alpha channel

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
Cherry pick of #6951 on release-1.12.
#6951: LaunchTemplate - support for deletion of instance group which
> Automated cherry pick of #6951: LaunchTemplate - support for deletion of instance group which

- pkg/model/openstackmodel/firewall.go
cc @drekle could you lgtm if ok
> Cherry-pick #6944 to release-1.13

- pkg/model/openstackmodel/firewall.go
cc @drekle could you lgtm if ok
> Cherry-pick #6944 to release-1.14

- util/pkg/vfs/BUILD.bazel
- util/pkg/vfs/s3context.go
> Cherry pick of #6943 onto release-1.13

- util/pkg/vfs/BUILD.bazel
- util/pkg/vfs/s3context.go
> Cherry pick of #6943 onto release-1.14

- docs/releases/1.12-NOTES.md
Calling our disruptive nature of update, and clarifying a couple change log items.
> 1.12 highlight changelog

- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
> Terraform: fix options field, should be spot_options

- hack/verify-generate.sh
> Add script to verify CRD generation

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
> Cherry pick of #7000 onto release-1.12

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
> Don't panic when deleting instancegroups

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
> Cherry pick of #7007 onto release-1.12

- cmd/kops/util/BUILD.bazel
- cmd/kops/util/factory.go
Not terribly useful yet, as we still need an S3 state store (or
comparable), but getting closer!
> Support using kops CLI with CRDs

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
> Cherry pick of #7007 onto release-1.13

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
> Cherry pick of #7007 onto release-1.14

- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
> Cherry pick of #6988 onto release-1.13

- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
> Cherry pick of #6988 onto release-1.14

- channels/alpha
- channels/stable
We should encourage people to use the released version now that it is
released (and the latest release version at that!)
> Recommend kops 1.12.1

- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Manual Fixed Conflicts in CP of #6950
> Cherry pick of #6950 onto release-1.13

- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Manually fix CP conflicts on #6950
> Cherry pick of #6950 onto release-1.14

- pkg/resources/aws/vpc.go
> Cherry pick of #7008 onto release-1.13

- pkg/resources/aws/vpc.go
> Cherry pick of #7008 onto release-1.14

- dns-controller/cmd/dns-controller/main.go
> Cherry pick of #6925 onto release-1.13

- dns-controller/cmd/dns-controller/main.go
> Cherry pick of #6925 onto release-1.14

- Makefile
- WORKSPACE
- docker/Dockerfile
- images/dns-controller-builder/Dockerfile
- images/protokube-builder/Dockerfile
Upstream change is https://github.com/kubernetes/kubernetes/pull/77528
> Update go_version to 1.12.5

- Makefile
- WORKSPACE
- docker/Dockerfile
- images/dns-controller-builder/Dockerfile
- images/protokube-builder/Dockerfile
> Cherry pick of #7035 onto release-1.14

- docs/releases/1.13-NOTES.md
- docs/releases/1.14-NOTES.md
Mostly just a changelog at this point; hopefully if we don't put much
into kops 1.13 into 1.14 it should stay that way!
> Start relnotes for 1.13 and 1.14

- channels/alpha
> Bump alpha-channel of k8s

- upup/pkg/fi/cloudup/awsup/machine_types.go
Looks like there's fresh data from aws on this now.
> Fix machine empheral disks

- upup/pkg/fi/cloudup/awsup/machine_types.go
Cherry pick of #7062 on release-1.13.
#7062: Fix machine empheral disks
> Automated cherry pick of #7062: Fix machine empheral disks

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/apiserver.go
> implement append admission controllers

- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation_test.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
> Cherry pick of #7094 onto release-1.12

- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation_test.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
> Cherry pick of #7094 onto release-1.13

- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation_test.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
> Cherry pick of #7094 onto release-1.14

- nodeup/pkg/distros/distribution.go
- nodeup/pkg/distros/identify.go
- nodeup/pkg/model/docker.go
- nodeup/pkg/model/kubectl.go
> Cherry pick debian buster support for release-1.14

- nodeup/pkg/distros/distribution.go
- nodeup/pkg/distros/identify.go
- nodeup/pkg/model/docker.go
- nodeup/pkg/model/kubectl.go
> Cherry pick debian buster support for release-1.13

- node-authorizer/pkg/server/metrics.go
> Cherry pick of #7080 onto release-1.13

- node-authorizer/pkg/server/metrics.go
> Cherry pick of #7080 onto release-1.14

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
> support apiserver admission-control-config-file flag

- OWNERS
Add rdrgmnzs to the approvers list in OWNERS
> Add rdrgmnzs to the approvers list in OWNERS

- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Changelog: https://docs.projectcalico.org/v3.7/release-notes/#v373
> Update Canal to v3.7.3

- hack/.packages
- nodeup/pkg/model/BUILD.bazel
- nodeup/pkg/model/convenience.go
- nodeup/pkg/model/kube_apiserver.go
- nodeup/pkg/model/kube_controller_manager.go
- nodeup/pkg/model/kube_scheduler.go
- nodeup/pkg/model/protokube.go
- pkg/model/components/etcdmanager/BUILD.bazel
- pkg/model/components/etcdmanager/model.go
- util/pkg/proxy/BUILD.bazel
- util/pkg/proxy/proxy.go
Fixes an issue where the settings in `egressProxy` were not being set on etcd-manager
> Egress proxy for etcd manager

- README-ES.md
> Fix the link to the Prow commands.

- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.10.yaml.template
- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
See https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.4.0
Consider cherry-picking this to 1.13 and 1.14
> Update aws-iam-authenticator image to 0.4.0

- docs/tutorial/openstack.md
> Added some changes to openstack.md file

- channels/alpha
Includes fixes for "TCP SACK PANIC" CVE
> Add updated 1.12 image to the alpha channel

- docs/instance_groups.md
- pkg/apis/kops/instancegroup.go
- pkg/apis/kops/v1alpha1/instancegroup.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/instancegroup.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/awsmodel/autoscalinggroup.go
- tests/integration/update_cluster/mixed_instances/in-v1alpha2.yaml
- tests/integration/update_cluster/mixed_instances/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Cherry pick of #7177 on release-1.13.
#7177: First pass at instance protection
> Automated cherry pick of #7177: Instance protection

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/flagbuilder/buildflags_test.go
- upup/pkg/fi/cloudup/openstack/server_group.go
Cherrypick #7153 onto release 1.13
> Cherry pick of #7153 onto release 1.13

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/flagbuilder/buildflags_test.go
- upup/pkg/fi/cloudup/openstack/server_group.go
> Cherry pick of #7153 onto release-1.14

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #7223 on release-1.14.
#7223: Bumping calico for bugfixes.
> Automated cherry pick of #7223: Bumping calico for bugfixes.

- protokube/pkg/gossip/mesh/state.go
Cherry pick of #7219 on release-1.13.
#7219: Make an actual deep-copy of the state
> Automated cherry pick of #7219: Make an actual deep-copy of the state

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
> Cherry pick of #7182 onto release-1.13

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
> Cherry pick of #7051 onto release-1.12

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
> Cherry pick of #7182 onto release-1.14

- pkg/commands/set_cluster.go
> Cherry pick of #7160 onto release-1.14

- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.10.yaml.template
- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
> Cherry pick of #6803 onto release-1.13

- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
> Cherry pick of #7077 onto release-1.14

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
> Cherry pick of #7109 onto release-1.14

- docs/images.md
- nodeup/pkg/distros/distribution.go
- nodeup/pkg/distros/identify.go
- nodeup/pkg/model/context.go
- nodeup/pkg/model/docker.go
- nodeup/pkg/model/etcd.go
- nodeup/pkg/model/kubelet.go
- nodeup/pkg/model/logrotate.go
- nodeup/pkg/model/update_service.go
> Cherry pick of #7084 onto release-1.14

- upup/pkg/fi/cloudup/dns.go
> Cherry pick of #7141 onto release-1.14

- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.10.yaml.template
- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
> Cherry pick of #6803 onto release-1.14

- pkg/client/simple/vfsclientset/cluster.go
> Cherry pick of #7202 onto release-1.14

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
Bumping calico to 3.7.4 for various bug fixes.
> Bumping calico to 3.7.4.

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
> Cherry pick of #7249 onto release-1.12

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
> Cherry pick of #7249 onto release-1.13

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
> Cherry pick of #7249 onto release-1.14

- hack/update-expected.sh
This should streamline things a little!
> Create hack/update-expected.sh to update test output

- upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
> Update DigitalOcean CCM to v0.1.16

- OWNERS
Add  granular-ryanbonham as a reviewer.   
@mikespain sponsoring
> Add me as reviewer

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
> Cherry pick of #7282 onto release-1.12

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
> Cherry pick of #7282 onto release-1.13

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
> Cherry pick of #7282 onto release-1.14

- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/utils/hash.go
> Cherry pick of #7312 onto release-1.14

- channels/alpha
> Bump alpha channel with latest kubernetes versions

- pkg/model/components/etcd.go
> Cherry pick of #7341 onto release-1.14

- pkg/featureflag/featureflag.go
- pkg/model/components/etcdmanager/BUILD.bazel
- pkg/model/components/etcdmanager/options.go
> Cherry pick of #7340 onto release-1.13

- pkg/featureflag/featureflag.go
- pkg/model/components/etcdmanager/BUILD.bazel
- pkg/model/components/etcdmanager/options.go
> Cherry pick of #7340 onto release-1.14

- docs/tutorial/digitalocean.md
- pkg/model/components/etcdmanager/BUILD.bazel
- pkg/model/components/etcdmanager/model.go
- upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
- upup/pkg/fi/cloudup/dns.go
- upup/pkg/fi/cloudup/do/cloud.go
> Cherry pick of #7221 onto release-1.14

- pkg/model/components/etcd.go
> Cherry pick of #7341 onto release-1.13

- nodeup/pkg/distros/distribution.go
- nodeup/pkg/distros/identify.go
- nodeup/pkg/model/docker.go
> Cherry pick of #7287 onto release-1.14

- upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
> Cherry pick of #7292 onto release-1.14

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
> Cherry pick of #7349 onto release-1.12

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
> Cherry pick of #7349 onto release-1.13

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
> Cherry pick of #7349 onto release-1.14

- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
> Cherry pick of #7317 onto release-1.14

- pkg/featureflag/featureflag.go
- pkg/model/components/etcdmanager/BUILD.bazel
- pkg/model/components/etcdmanager/options.go
> Cherry pick of #7340 onto release-1.12

- upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
> Cherry pick of #7102 onto release-1.14

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/flagbuilder/buildflags_test.go
> Cherry pick of #7344 onto release-1.14

- upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
> Cherry pick of #7326 onto release-1.14

- protokube/pkg/protokube/gce_volume.go
Signed-off-by: ethan <guangming.wang@daocloud.io>
> protokube/gce_volume.go: error info correction

- node-authorizer/pkg/client/client.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
> cleanup: client.go error message words correction

- upup/pkg/fi/cloudup/awstasks/instance_volume_attachment.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
> awstasks: fix misspelled words in logging.

- nodeup/pkg/model/kube_scheduler.go
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
> Cherry pick of #7346 onto release-1.14

- pkg/bundle/builder.go
- tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data
- tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_nodes.k8s-iam.us-west-2.td.priv_user_data
- tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/urls.go
> Cherry pick of #7377 onto release-1.14

- pkg/model/resources/nodeup.go
- tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
> Cherry pick of #7370 onto release-1.14

- hack/.packages
- nodeup/pkg/model/BUILD.bazel
- nodeup/pkg/model/convenience.go
- nodeup/pkg/model/kube_apiserver.go
- nodeup/pkg/model/kube_controller_manager.go
- nodeup/pkg/model/kube_scheduler.go
- nodeup/pkg/model/protokube.go
- util/pkg/proxy/BUILD.bazel
- util/pkg/proxy/proxy.go
> Cherry pick of #7103 onto release-1.14

- kube-discovery/cmd/kube-discovery/main.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
> cleanup: fix error message typos

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/BUILD.bazel
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/openstackmodel/firewall.go
original PR #7395 
openstack support is still under alpha, so I think its ok to cherrypick this to 1.14?
> Cherrypick etcd-manager support for openstack 

- pkg/resources/ali/ali.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
> ali.go: cleanup error words in messages

- pkg/model/resources/nodeup.go
- pkg/model/tests/data/bootstrapscript_0.txt
- pkg/model/tests/data/bootstrapscript_1.txt
- pkg/model/tests/data/bootstrapscript_2.txt
- pkg/model/tests/data/bootstrapscript_3.txt
- pkg/model/tests/data/bootstrapscript_4.txt
- pkg/model/tests/data/bootstrapscript_5.txt
- tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data
- tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_nodes.k8s-iam.us-west-2.td.priv_user_data
- tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
On an error, we were bailing out early!
> nodeup download should try all mirrors

- README.md
- docs/index.md
Signed-off-by: Sakura <longfei.shang@daocloud.io>
> fix typo "in ingards to" -> "in regard to"

- pkg/model/resources/nodeup.go
- pkg/model/tests/data/bootstrapscript_0.txt
- pkg/model/tests/data/bootstrapscript_1.txt
- pkg/model/tests/data/bootstrapscript_2.txt
- pkg/model/tests/data/bootstrapscript_3.txt
- pkg/model/tests/data/bootstrapscript_4.txt
- pkg/model/tests/data/bootstrapscript_5.txt
- tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data
- tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_nodes.k8s-iam.us-west-2.td.priv_user_data
- tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
> Cherry pick of #7447 onto release-1.14

- .shipbot.yaml
- Makefile
- docs/development/release.md
> Cherry pick of #7449 onto release-1.14

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
Cherry pick of #7517 on release-1.13.
#7517: fix(addons/networking.projectcalico.org) calico
> Automated cherry pick of #7517: fix(addons/networking.projectcalico.org) calico

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
Cherry pick of #7526 on release-1.14.
#7526: fix(addons/networking.projectcalico.org) calico
> Automated cherry pick of #7526: fix(addons/networking.projectcalico.org) calico

- pkg/instancegroups/instancegroups.go
> Cherry pick of #7465 onto release-1.14

- docs/tutorial/digitalocean.md
- pkg/model/components/etcdmanager/model.go
> Cherry pick of #7435 onto release-1.14

- util/pkg/vfs/sshfs.go
> Cherry pick of #7483 onto release-1.14

- WORKSPACE
Cherry pick of #7348 on release-1.14.
#7348: Update repo-infra for bazel fixes
> Automated cherry pick of #7348: Update repo-infra for bazel fixes

- docs/development/bazel.md
- docs/development/vendoring.md
* Document bazel versions to make it easier to build specific releases
* Document gomod
* Add todo for gomod docs
> Add a few docs comments on gomod and bazel

- WORKSPACE
- tools/bazel.rc
> Cherry pick of #7499 onto release-1.14

- Makefile
- docker/Dockerfile
- images/dns-controller-builder/Dockerfile
- images/protokube-builder/Dockerfile
Adding a few places I missed in #7549
Thanks @rifelpet for the heads-up!
> [release-1.13] Add more go 1.11.5 -> 1.11.13

- docs/networking.md
- k8s/crds/kops_v1alpha2_cluster.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha1/networking.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #7528 on release-1.15.
#7528: Add ability to configure number of Typha Replicas
> Automated cherry pick of #7528: Add ability to configure number of Typha Replicas

- pkg/assets/builder.go
> Log more sensibly when we can't get sha256

- docs/cluster_spec.md
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha1/cluster.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #7376 on release-1.15.
#7376: CoreDNS: Allow for Specification of external
> Automated cherry pick of #7376: CoreDNS: Allow for Specification of external

- pkg/model/iam/iam_builder.go
- upup/pkg/fi/cloud.go
This is a patch to go along with issue #7564.
> Fix kops for us-gov-east-1 #7564

- docs/cluster_spec.md
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
Cherry pick of #7573 on release-1.15.
#7573: Add horizontalPodAutoscalerDownscaleStabilization
> Automated cherry pick of #7573: Add horizontalPodAutoscalerDownscaleStabilization

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
Cherry pick of #7388 on release-1.14.
#7388: Upgrading k8s-srcdst to v0.2.2
> Automated cherry pick of #7388: Upgrading k8s-srcdst to v0.2.2

- OWNERS
I've been involved with the project for almost two years now, I figured I should join the ranks and make it official :)
> Add myself @rifelpet as a reviewer

- README.md
Add missing OpenStack reference.
> Add missing OpenStack reference

- upup/pkg/fi/cloudup/awstasks/internetgateway_test.go
- upup/pkg/fi/cloudup/openstacktasks/subnet.go
- upup/pkg/fi/nodeup/command.go
Cherry pick of #7586 on release-1.14.
#7586: upup/pkg/fi/cloudup/awstasks: fix dropped error
> Automated cherry pick of #7586: upup/pkg/fi/cloudup/awstasks: fix dropped error

- cmd/kops/create_cluster.go
Cherry pick of #7601 on release-1.15.
#7601: add cilium in error message
> Automated cherry pick of #7601: add cilium in error message

- nodeup/pkg/model/logrotate.go
> Add logrotate for etcd/etcd-events.log

- pkg/model/BUILD.bazel
- pkg/model/components/etcdmanager/model.go
- pkg/model/domodel/BUILD.bazel
- pkg/model/domodel/droplets.go
- pkg/model/master_volumes.go
- upup/pkg/fi/cloudup/do/cloud.go
- upup/pkg/fi/cloudup/dotasks/BUILD.bazel
- upup/pkg/fi/cloudup/dotasks/droplet.go
- upup/pkg/fi/cloudup/dotasks/volume.go
Cherry pick of #7566 on release-1.15.
#7566: Update DO objects to use tags
> Automated cherry pick of #7566: Update DO objects to use tags

- nodeup/pkg/model/logrotate.go
Cherry pick of #7614 on release-1.15.
#7614: Add logrotate for etcd/etcd-events.log
> Automated cherry pick of #7614: Add logrotate for etcd/etcd-events.log

- pkg/model/openstackmodel/firewall.go
- upup/pkg/fi/cloudup/openstack/cloud.go
- upup/pkg/fi/cloudup/openstack/security_group.go
- upup/pkg/fi/cloudup/openstacktasks/lb.go
- upup/pkg/fi/cloudup/openstacktasks/securitygroup.go
Cherry pick of #7561 on release-1.15.
#7561: clean security groups
> Automated cherry pick of #7561: clean security groups

- cmd/kops/validate_cluster.go
- docs/cli/kops_validate_cluster.md
Cherry pick of #7371 on release-1.14.
#7371: Add --wait argument to kops validate
> Automated cherry pick of #7371: Add --wait argument to kops validate

- pkg/model/openstackmodel/network.go
- pkg/model/openstackmodel/servergroup.go
- pkg/model/openstackmodel/servergroup_test.go
- upup/pkg/fi/cloudup/openstack/cloud.go
- upup/pkg/fi/cloudup/openstack/instance.go
- upup/pkg/fi/cloudup/openstacktasks/instance.go
We have environment which do not have any external router so we cannot provisiong floatingips. Instead we will use fixed ips to connect instances.
> Use without external router (OpenStack)

- pkg/model/openstackmodel/servergroup.go
Cherry pick of #7641 on release-1.15.
#7641: fix instance name
> Automated cherry pick of #7641: fix instance name

- pkg/model/openstackmodel/network.go
- pkg/model/openstackmodel/servergroup.go
- pkg/model/openstackmodel/servergroup_test.go
- upup/pkg/fi/cloudup/openstack/cloud.go
- upup/pkg/fi/cloudup/openstack/instance.go
- upup/pkg/fi/cloudup/openstacktasks/instance.go
Cherry pick of #7644 on release-1.15.
#7644: Use without external router
> Automated cherry pick of #7644: Use without external router

- pkg/model/iam/iam_builder.go
- pkg/model/iam/tests/iam_builder_master_strict.json
- pkg/model/iam/tests/iam_builder_master_strict_ecr.json
Cherry pick of #7580 on release-1.14.
#7580: Updating master IAM policies.
> Automated cherry pick of #7580: Updating master IAM policies.

- pkg/model/openstackmodel/firewall.go
- pkg/model/openstackmodel/servergroup.go
- pkg/model/openstackmodel/servergroup_test.go
- upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
- upup/pkg/fi/cloudup/openstacktasks/instance.go
- upup/pkg/fi/cloudup/openstacktasks/port.go
- upup/pkg/fi/cloudup/openstacktasks/port_test.go
This allows to apply additional security groups on instance groups
> OpenStack: Additional security groups for instances

- nodeup/pkg/model/docker.go
> Cherry pick of #7674 onto release-1.13

- nodeup/pkg/model/docker.go
> Cherry pick of #7674 onto release-1.14

- nodeup/pkg/model/docker.go
> Cherry pick of #7674 onto release-1.15

- pkg/apis/kops/instancegroup.go
- pkg/apis/kops/v1alpha1/instancegroup.go
- pkg/apis/kops/v1alpha2/instancegroup.go
Fixes: #7405
Signed-off-by: jakub.coufal <jakub.coufal@wandera.com>
> Align AWS and kops validation for spot allocation strategy

- channels/alpha
> Bump k8s versions in alpha channel

- pkg/model/openstackmodel/servergroup.go
- pkg/model/openstackmodel/servergroup_test.go
> Cherrypick #7690 onto release 1.15

- cmd/kops/integration_test.go
- go.mod
- pkg/apis/kops/BUILD.bazel
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/parse_test.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/flagbuilder/BUILD.bazel
- pkg/flagbuilder/build_flags.go
- pkg/flagbuilder/buildflags_test.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
This incorporates #7706 and #7707 as its first two commits.  Then we
verify that although the intermediate representation changes, we can
still parse both floating point (3.14) and resource.Quantity (3140m)
style values.
> Change from float -> resource.Quantity

- cmd/kops/integration_test.go
- pkg/apis/kops/parse_test.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
Similar to #7706, but now we are testing the parsing side of things!
> Add test for parsing of float args

- cmd/kops/integration_test.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
We likely need to change from floats to resource.Quantity, so we need
to estabilsh more test coverage before we can safely make the change.
> Add test for float args

- kube-discovery/cmd/kube-discovery/main.go
- nodeup/pkg/model/file_assets.go
- nodeup/pkg/model/protokube.go
- pkg/instancegroups/instancegroups.go
Improve the quality of annotations.
> Correct word misspelling

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
As discussed during office hours.
/cc @justinsb
> Add calico 3.9.1

- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
> Cherry pick of #7710 onto release-1.14

- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
> Cherry pick of #7710 onto release-1.15

- pkg/model/components/etcd.go
Should be no changes in the backup image (so no need to backport), but
just want to sync up the versions so I don't forget it again!
> Update etcd-manager backup image

- upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
The update brings a number of bug fixes, stability improvements, and features.
> Update DigitalOcean CCM to v0.1.20

- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #7646 on release-1.15.
#7646: Fix Cilium addon version
> Automated cherry pick of #7646: Fix Cilium addon version

- tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
- upup/pkg/fi/cloudup/urls.go
Cherry pick of #7378 on release-1.15.
#7378: Add artifacts.k8s.io to mirror list
> Automated cherry pick of #7378: Add artifacts.k8s.io to mirror list

- docs/releases/1.14-NOTES.md
Includes changes from 1.14.0-beta.2 to 1.14.0
> relnotes for 1.14.0

- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
> Cherry pick of #7477 onto release-1.13

- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
> Cherry pick of #7477 onto release-1.14

- Makefile
- cmd/kops-controller/BUILD.bazel
- cmd/kops-controller/main.go
- hack/.packages
- pkg/nodeidentity/openstack/BUILD.bazel
- pkg/nodeidentity/openstack/identify.go
Implements OpenStack part to #7496
> Kops controller support for OpenStack

- docs/state.md
This PR adds documentation on how to use the state stores.
> docs: document state store configuration

- tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
- upup/pkg/fi/cloudup/urls.go
The official mirror is coming!
> Add artifacts.k8s.io to mirror list

- cmd/kops-controller/BUILD.bazel
- cmd/kops-controller/main.go
- cmd/kops-controller/pkg/config/BUILD.bazel
- cmd/kops-controller/pkg/config/options.go
- go.mod
- hack/.packages
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/BUILD.bazel
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
This is more in keeping with componentconfig, and lets us add more
options easily in future.
> Move kops-controller to use a yaml configuration file

- k8s/crds/kops_v1alpha2_cluster.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/flagbuilder/buildflags_test.go
Cherry pick of #7487 on release-1.15.
#7487: Add Event TTL flag
> Automated cherry pick of #7487: Add Event TTL flag

- nodeup/pkg/model/kubelet.go
Cherry pick of #7539 on release-1.15.
#7539: fix(nodeup): miscalculated `max-pods` when using
> Automated cherry pick of #7539: fix(nodeup): miscalculated `max-pods` when using

- Makefile
- WORKSPACE
- docker/Dockerfile
- images/dns-controller-builder/Dockerfile
- images/protokube-builder/Dockerfile
https://groups.google.com/forum/#!msg/golang-announce/lVEm7llp0w0/VbafyRkgCgAJ
fixes #7799
> Upgrade go version to 1.12.11

- nodeup/pkg/model/protokube.go
- upup/pkg/fi/cloudup/awstasks/elastic_ip.go
fix-up some gosimple errors
@justinsb  @zetaab  can you help  me review these changes?Thanks!
> fix-up bug in nodeup/pkg/model

- pkg/commands/status_discovery.go
> Alicloud: fix status discovery

- upup/pkg/fi/nodeup/command.go
> Alicloud: fix error msg when check hostname

- Makefile
- netlify.toml
First step in an official netlify: https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md#requesting-a-netlify-site
Only addition in this PR is a netlify config and removing a TODO
/hold
> Add netlify config

- pkg/model/openstackmodel/firewall.go
- pkg/wellknownports/wellknownports.go
@justinsb etcd-manager in OpenStack does not currently work with master branch. This will make it work again
please check this before 1.16 alpha 1
/kind bug
> fix firewalls for OpenStack

- permalinks/upgrade_k8s.md
> Fix permalink

- README-ES.md
- README.md
- addons/README.md
- addons/ingress-citrix/README.md
- cmd/kops/update_cluster.go
- docs/README.md
- docs/examples/kops-test-route53-subdomain.md
- docs/operations/addons.md
This fixes the broken links for addons docs.
> docs(addons): fix broken links

- pkg/cloudinstances/cloud_instance_group.go
Even though this related with #7849, but it should be not blocked by #7849.
> Alicloud: split ProviderID with "."

- pkg/model/spotinstmodel/instance_group.go
> remove the unnecessary break

- channels/stable
Promoting this recommendation into the stable channel.
> Recommend kops 1.11.1

- docs/single-to-multi-master.md
Hi,
I've added a hint, how to determine the mount paths of the etcd directories. I think most people know how to get the correct path, but if you go through such a risky procedure, you'll be more comfortable with such information.
> Add hint how to determine mount path of etcd data

- channels/stable
- tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_vpc/expected-v1alpha1.yaml
- tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
> stable channel: promote default AMIs from alpha -> stable

- Makefile
Addresses one of the two issues in #7934
> Fix fork bomb in Makefile

- Makefile
It probably makes sense to unhide this both for debugging and for netlify.
> Unhide docs make logging

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha1/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.5.5
> Upgrade AWS VPC CNI to 1.5.5

- docs/development/vendoring.md
> Update vendoring documentation for go modules

- docs/single-to-multi-master.md
The steps to move from single to multi master are much easier with etcd-manager. Updated the documentation for the single-to-multimaster for the case of etcd-manager. A rollback strategy is missing. 
Outline for rollback could be: remove autoscaling groups, delete ETCD EBS volumes, revert changes made with kops edit to the cluster and kops update the cluster. Then restore the etcd-manager with etcd-manager-ctl. Since I did not test this (or only for a normal restore) I did not feel comfortable to write it down.
> Updated documentation on how to move from single to multi master

- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
> Cherry pick of #7856 onto release-1.15

- addons/kube-ingress-aws-controller/README.md
- docs/development/testing.md
- docs/networking.md
@justinsb  can you help me deal with  this pr?Thanks.
> fix 404 urls in docs

- nodeup/pkg/model/docker.go
- nodeup/pkg/model/docker_test.go
- pkg/model/components/docker.go
> Cherry pick of #7860 onto release-1.15

- docs/apireference/build/node_modules/jquery.scrollto/README.md
- docs/apireference/build/node_modules/optimist/readme.markdown
* Normally I wouldn't suggest modifying dependencies
* These dependencies are just images
* Therefore, lets fix the netlify issue:
https://github.com/kubernetes/kops/runs/308987838
> Fix netlify mixed content

- OWNERS
Thank you for all your excellent work!
> Promote peter & ryan & zetaab to approvers

- nodeup/pkg/model/sysctls.go
Comment for net.ipv4.tcp_tw_reuse from tcp(7).
> sysctls.go: Fix some comments

- .travis.yml
> Dont run travis with Go 1.11

- docs/instance_groups.md
- nodeup/pkg/model/tests/dockerbuilder/skipinstall/cluster.yaml
- tests/integration/update_cluster/additional_cidr/in-v1alpha3.yaml
- tests/integration/update_cluster/api_elb_cross_zone/in-v1alpha2.yaml
- tests/integration/update_cluster/unmanaged/in-v1alpha2.yaml
Not sure how to update `docs/apireference/build/index.html`
> Update apiVersion in docs and tests

- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/BUILD.bazel
- upup/pkg/fi/cloudup/template_functions.go
Cherry pick of #7979 on release-1.15.
#7979: cloudup: Map sprig indent template function
> Automated cherry pick of #7979: cloudup: Map sprig indent template function

- cmd/kops/root.go
- docs/cli/kops.md
Clear whitespace in root command. Also do we want to update the list of alpha supported providers? Or can we permalink somewhere?
> cleanup whitespace in root.go

- docs/releases/1.15-NOTES.md
This PR just removes a comment about 1.15 not being released. It was released five days ago.
> Remove note about 1.15 not being released

- pkg/model/alimodel/network.go
> Alicloud: only private subnets need SNAT rule

- upup/pkg/fi/cloudup/alitasks/eip_natgateway_association.go
> Alicloud: use ID of EIP to compare

- upup/pkg/fi/cloudup/alitasks/scalinggroup.go
Also small refactor to make the code looks cleaner.
> Alicloud: fix comparison failure for scalinggroup

- pkg/model/alimodel/api_loadbalancer.go
- pkg/model/alimodel/context.go
- upup/pkg/fi/cloudup/alitasks/loadbalancer.go
> Alicloud: support internal api loadbalancer

- pkg/model/alimodel/network.go
- upup/pkg/fi/cloudup/alitasks/natgateway.go
- upup/pkg/fi/cloudup/alitasks/vpc.go
I'll come up with a few more PRs to fix all the comparison failures for Alicloud resources, to make each PR only contains smaller changes, thus make it easier for code review.
Thanks!
> Alicloud: fix comparison failures for VPC and NATGateway

- upup/pkg/fi/cloudup/alitasks/launchconfiguration.go
- upup/pkg/fi/cloudup/alitasks/loadbalancerwhitelist.go
I'm submitting the last batches of PRs to fix the comparison failures, also try to make the related code a little bit cleaner.
After all these PRs merged, it would be a big milestone for Alicloud support.
> Alicloud: fix comparison failures for LaunchConfiguration and LoadBalancerWhiteList

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
> Cherry pick of #8038 onto release-1.15

- pkg/validation/BUILD.bazel
- pkg/validation/validate_cluster_test.go
- vendor/github.com/stretchr/testify/require/BUILD.bazel
- vendor/github.com/stretchr/testify/require/doc.go
- vendor/github.com/stretchr/testify/require/forward_requirements.go
- vendor/github.com/stretchr/testify/require/require.go
- vendor/github.com/stretchr/testify/require/require.go.tmpl
- vendor/github.com/stretchr/testify/require/require_forward.go
- vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
- vendor/github.com/stretchr/testify/require/requirements.go
- vendor/modules.txt
More prep work for rolling update improvements.
> Increase validation test coverage

- upup/pkg/fi/cloudup/alitasks/vswitch.go
- upup/pkg/fi/cloudup/alitasks/vswitchSNAT.go
> Alicloud: fix comparison failures for VSwitch and VSwitchSNAT

- upup/pkg/fi/cloudup/alitasks/rampolicy.go
- upup/pkg/fi/cloudup/alitasks/ramrole.go
> Alicloud: fix comparison failures for RAMRole and RAMPolicy

- Makefile
Allow earlier detection of problems, especially for non-maintainers.
@geojaz Want to take this one too?
> Add verify-generate to Travis and 'make ci'

- cmd/kops/update_cluster.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Fix mounting Calico "flexvol-driver-host" in CoreOS #8062
> Cherry pick of #8062 to release-1.17

- channels/alpha
- channels/stable
@justinsb / @mikesplain please check this as it is first time when I do the channel update. And remove hold
/hold
> put kubernetes 1.17.0 to channels

- cmd/kops/update_cluster.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Fix mounting Calico "flexvol-driver-host" in CoreOS #8062
> Cherry pick of #8062 to release-1.15

- docs/advisories/spectre-meltdown-kernel-update.md
- docs/boot-sequence.md
- docs/calico-v3.md
- docs/development/testing.md
- docs/development/vendoring.md
- docs/etcd/roadmap.md
- docs/examples/kops-test-route53-subdomain.md
- docs/examples/kops-tests-private-net-bastion-host.md
- docs/getting_started/arguments.md
- docs/getting_started/digitalocean.md
- docs/getting_started/openstack.md
- docs/iam_roles.md
- docs/labels.md
- docs/operations/addons.md
- docs/operations/cluster_upgrades_and_migrations.md
- docs/philosophy.md
- docs/releases.md
- docs/releases/1.6.1.md
- docs/rotate-secrets.md
- docs/run_in_existing_vpc.md
- docs/single-to-multi-master.md
- docs/upgrade_from_kops_1.6_to_1.7_calico_cidr_migration.md
- docs/vsphere-development-status.md
- docs/welcome/contributing.md
Going to give the docs another run through on the formatting side but in the interests of making these at least semi-manageable from a review point of view making this one is purely fixing up list formatting plus a few bits of whitespace and one rogue full stop.
Also one docs link fix.
> Docs: More List fixes

- pkg/instancegroups/instancegroups.go
- pkg/instancegroups/rollingupdate_test.go
> Add test for flapping cluster validation and improve its logging

- nodeup/pkg/model/BUILD.bazel
- nodeup/pkg/model/protokube_test.go
- nodeup/pkg/model/tests/protokube/docker/cluster.yaml
- nodeup/pkg/model/tests/protokube/docker/tasks.yaml
This should give us some assurances that we haven't changed things too
much with the containerd introduction.
> Add test for protokube builder

- cmd/kops/update_cluster.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Fix mounting Calico "flexvol-driver-host" in CoreOS #8062
> Cherry pick of #8062 to release-1.16

- cmd/kops/create_cluster.go
- docs/cli/kops_create_cluster.md
There were some missing `\`'s and they were not consistent/working. I refreshed them.
> Cleans up the create cluster CLI prompts

- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #8104 on release-1.17.
#8104: Add Calico v3.10.2
> Automated cherry pick of #8104: Add Calico v3.10.2

- hack/.staticcheck_failures
- k8s/crds/kops.k8s.io_clusters.yaml
- nodeup/pkg/model/convenience.go
- nodeup/pkg/model/file_assets.go
- nodeup/pkg/model/kubelet.go
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
> nodeup/pkg/model - fix static check

- cmd/kops-controller/BUILD.bazel
- cmd/kops-controller/main.go
- hack/.packages
- pkg/model/domodel/droplets.go
- pkg/nodeidentity/do/BUILD.bazel
- pkg/nodeidentity/do/identify.go
- upup/pkg/fi/cloudup/do/cloud.go
Cherry pick of #7961 on release-1.16.
#7961: Initial work
> Automated cherry pick of #7961: Initial work

- hack/.staticcheck_failures
- pkg/resources/aws/aws.go
> pkg/resources/aws:simplify code and remove code

- pkg/util/subnet/subnet_test.go
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
> Add corresponding unit test to the function in subnet.go.

- cmd/kops/create_cluster.go
- docs/cli/kops_create_cluster.md
- tests/integration/create_cluster/complex/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha/expected-v1alpha1.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_encrypt/expected-v1alpha1.yaml
- tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
- tests/integration/create_cluster/ingwspecified/expected-v1alpha1.yaml
- tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha1.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha1.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
- tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets/expected-v1alpha1.yaml
- tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha1.yaml
- tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_vpc/expected-v1alpha1.yaml
- tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
> containerd: Add --container-runtime cli flag

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
> Cherry pick of #8038 onto release-1.16

- pkg/diff/diff.go
according to the comment, the buildDiffLines function need clean up
> clean up buildDiffLines

- hack/.staticcheck_failures
- node-authorizer/pkg/authorizers/aws/verifier.go
> Fix node-authorizer/pkg/authorizers/aws staticcheck failure

- hack/.staticcheck_failures
- pkg/resources/openstack/openstack.go
> Fix pkg/resources/openstack staticcheck failure

- util/pkg/slice/BUILD.bazel
- util/pkg/slice/slice_test.go
Add corresponding unit tests to the functions in slice.go.
Signed-off-by: Zhou Hao zhouhao@cn.fujitsu.com
> util/pkg/slice: Add slice test

- pkg/apis/kops/registry/helpers.go
- pkg/apis/kops/validation/instancegroup.go
- pkg/apis/kops/validation/validation.go
- pkg/commands/status_discovery.go
- pkg/model/components/kubecontrollermanager.go
- pkg/model/iam.go
pkg/apis/kops/registry/helpers.go:35:22: error strings should not be capitalized (ST1005)
pkg/apis/kops/validation/instancegroup.go:80:21: error strings should not be capitalized (ST1005)
pkg/apis/kops/validation/instancegroup.go:221:22: error strings should not be capitalized (ST1005)
pkg/apis/kops/validation/instancegroup.go:235:20: error strings should not be capitalized (ST1005)
pkg/apis/kops/validation/validation.go:387:90: error strings should not be capitalized (ST1005)
pkg/commands/status_discovery.go:67:27: error strings should not be capitalized (ST1005)
pkg/commands/status_discovery.go:105:24: error strings should not be capitalized (ST1005)
pkg/model/components/context.go:130:24: error strings should not be capitalized …
> pkg/apis/ pkg/commands/ pkg/model/ staticcheck

- pkg/apis/kops/channel.go
- pkg/client/simple/vfsclientset/commonvfs.go
- pkg/client/simple/vfsclientset/instancegroup.go
- pkg/cloudinstances/cloud_instance_group.go
Delete a package imported twice, for example:
```shell
metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
```
> staticcheck:remove duplicate import packages

- pkg/instancegroups/BUILD.bazel
- pkg/instancegroups/rollingupdate_test.go
In preparation for the next feature.
/area rolling-update
> Refactor rolling update tests

- docs/http_proxy.md
- docs/networking.md
small documentation typo fixes
> small documentation typo fixes

- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- tests/integration/update_cluster/restrict_access/in-v1alpha2.yaml
- tests/integration/update_cluster/restrict_access/kubernetes.tf
Would have caught the user error in #8040
> Improve CIDR validation

- pkg/formatter/instancegroup_test.go
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
> Add unit test for func RenderInstanceGroupSubnets in instancegroup.go

- upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #7874, as we have run into the same issue of weave pods getting evicted from a host.
> Cherry pick #7874 onto 1.15

- cmd/kops/integration_test.go
- docs/cluster_spec.md
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha1/cluster.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/awsmodel/autoscalinggroup.go
- pkg/model/context.go
- pkg/model/names.go
- pkg/model/sshkey.go
- protokube/pkg/gossip/mesh/mesh.pb.go
- tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json
- tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/nosshkey-cloudformation/in-v1alpha2.yaml
- tests/integration/update_cluster/nosshkey/in-v1alpha2.yaml
- tests/integration/update_cluster/nosshkey/kubernetes.tf
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/awstasks/BUILD.bazel
- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
- upup/pkg/fi/cloudup/awstasks/sshkey.go
Cherry pick of #7096 on release-1.17.
#7096: Add ability to specify no ssh key by setting sshKeyName to
> Automated cherry pick of #7096: Add ability to specify no ssh key by setting sshKeyName to

- README.md
Fix http link to https link for security
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
> Securing http link to https link

- pkg/edit/BUILD.bazel
- pkg/edit/edit_test.go
> Add unit test for pkg/edit/edit.go

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/options.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
> Cherry pick of #8399 onto release-1.17

- pkg/model/components/etcdmanager/BUILD.bazel
- pkg/model/components/etcdmanager/model.go
- pkg/model/master_volumes.go
This is currently blocked by https://github.com/kopeio/etcd-manager/pull/269.
Please hold on until https://github.com/kopeio/etcd-manager/pull/269 is merged.
> Alicloud: etcd-manager support

- hack/verify-shellcheck.sh
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
> Fix typo in comment

- docs/node_authorization.md
- docs/operations/images.md
Although it is spelling mistakes, it might make an affects while reading.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
> docs: trivial fix some typos

- tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json.extracted.yaml
- upup/pkg/fi/cloudup/urls.go
> Cherry pick of #8468 onto release-1.17

- tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
- upup/pkg/fi/cloudup/urls.go
> Cherry pick of #8468 onto release-1.15

- tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json.extracted.yaml
- upup/pkg/fi/cloudup/urls.go
> Cherry pick of #8468 onto release-1.16

- pkg/apis/kops/networking.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
> Update cilium to 1.6.6

- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This reverts commit 4a9fbdca9c28ba06db163191e81eec60b2fcd549, reversing
changes made to 48eb069e611839886dcea24903d1de565d509ccb.
See #8501 for further details
> Revert "Merge pull request #8452 from maruina/coredns-1.6.7"

- pkg/acls/gce/BUILD.bazel
- pkg/acls/gce/storage.go
> Cherry pick of #8493 onto release-1.15

- pkg/acls/gce/BUILD.bazel
- pkg/acls/gce/storage.go
> Cherry pick of #8493 onto release-1.17

- pkg/acls/gce/BUILD.bazel
- pkg/acls/gce/storage.go
> Cherry pick of #8493 onto release-1.16

- cloudbuild.yaml
Adding build & upload of our binaries to the staging bucket, from the
trusted builder.
> cloudbuild: Try uploading our binaries to the staging bucket also

- pkg/jsonutils/BUILD.bazel
- pkg/jsonutils/streamwriter_test.go
> Add unit test for pkg/jsonutils/streamwriter.go

- pkg/model/bootstrapscript.go
Cherry pick of Stabilize sequence of "export xx=xxx" statements on release-1.17.
#8247 Stabilize sequence of "export xx=xxx" statements
For details on the cherry pick process, see the cherry pick requests page.
> Automated cherry pick of #8247 release-1.17

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha1/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.6.0
> Update amazon-vpc-cni-k8s to v1.6.0

- Makefile
- tools/gzip.bzl
Another source of non-reproducible builds!
> gzip: use --no-name to avoid saving timestamp

- Makefile
This is one step towards removing the requirement that kops lives in the GOPATH.
* Consolidate the redundant `KOPS_ROOT` and `MAKEDIR` variables
* Remove dependency of `GOPATH_1ST` variable except for `GOPATH_1ST/bin`
* Remove broken `check-builds-in-go111` target
* Remove unused `KOPS_SERVER_TAG`
> Update makefile to reduce dependency on GOPATH

- util/pkg/env/standard.go
> cherrypick #8592 (add s3 region)

- pkg/nodelabels/BUILD.bazel
- pkg/nodelabels/builder_test.go
> Add unit test for pkg/nodelabels/builder.go

- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Should fix the superfluous dot breaking the e2e
> Fix typo in the cilium default version

- pkg/model/components/context.go
> Resolve TODO in /pkg/model/component/context.go

- pkg/apis/kops/networking.go
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
> Fix typo in comment for struct LyftVPCNetworkingSpec

- channels/pkg/api/BUILD.bazel
- channels/pkg/api/channel.go
- channels/pkg/api/channel_test.go
- channels/pkg/channels/BUILD.bazel
- channels/pkg/channels/addons.go
- channels/pkg/channels/addons_test.go
- channels/pkg/cmd/apply_channel.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Ensure such things get noticed early.
(Having lost half a day due to such a thing.)
> Refuse to read channels with addons with unparseable versions

- nodeup/pkg/model/docker.go
- upup/pkg/fi/nodeup/nodetasks/package.go
- upup/pkg/fi/nodeup/tags/tags.go
Cherry pick of #8020 on release-1.17.
#8020: Automatically install dependencies with local packages
> Automated cherry pick of #8020: Automatically install dependencies with local packages

- channels/stable
These have been in alpha for two weeks and should be good for stable now.
> Promote alphas to stable

- docs/development/release.md
- hack/set-version
* We need to publish kops-controller image
* Including experimental hack/set-version script that should help with rolling versions
> Update release process

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha1/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #8618 on release-1.17.
#8618: Update Calico and Canal to v3.12.0
> Cherry pick of #8618: Update Calico and Canal to v3.12.0

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Fixes#https://github.com/kubernetes/kops/issues/8546
/cc @rifelpet
> support apiserver --kubelet-certificate-authority  flag

- README-ES.md
- README.md
> Update compatibility matrix

- docs/getting_started/digitalocean.md
A minor issue to fix Digitial Ocean getting started documentation.
> [Digital Ocean] Fix minor document issue

- pkg/apis/kops/cluster.go
- pkg/apis/kops/networking.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
> Revert "Automated cherry pick of #8589: Bump Cilium to 1.7 for k8s 1.12+ #8591: Fix typo in the cilium default version"

- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Cherry pick of #8682 on release-1.17.
#8682: Add env var config
> Automated cherry pick of #8682: Add env var config

- docs/README.md
- docs/operations/service_account_token_volumes.md
Signed-off-by: Jonathan Meyers <jonathan@cybrary.it>
Shoutout to @jfassad for all the testing and figuring out configs.
> [Docs] Add service account token volumes

- util/pkg/vfs/BUILD.bazel
- util/pkg/vfs/fs_test.go
> Add UT for util/pkg/vfs/fs.go

- util/pkg/exec/BUILD.bazel
- util/pkg/exec/exec_test.go
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
> Adding Unit Test for util/pkg/exec/exec.go

- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
/assign @olemarkus
xref https://github.com/cilium/cilium/issues/10468
> Bump Cilium to 1.7.1 for k8s 1.12+

- docs/OWNERS
- k8s/crds/OWNERS
- nodeup/OWNERS
- pkg/apis/OWNERS
- pkg/instancegroups/OWNERS
- pkg/resources/ali/OWNERS
- pkg/resources/aws/OWNERS
- pkg/resources/digitalocean/OWNERS
- pkg/resources/gce/OWNERS
- pkg/resources/openstack/OWNERS
- pkg/resources/spotinst/OWNERS
- protokube/OWNERS
- upup/models/cloudup/resources/addons/OWNERS
- upup/pkg/fi/cloudup/alitasks/OWNERS
- upup/pkg/fi/cloudup/aliup/OWNERS
- upup/pkg/fi/cloudup/awstasks/OWNERS
- upup/pkg/fi/cloudup/awsup/OWNERS
- upup/pkg/fi/cloudup/do/OWNERS
- upup/pkg/fi/cloudup/dotasks/OWNERS
- upup/pkg/fi/cloudup/gce/OWNERS
- upup/pkg/fi/cloudup/gcetasks/OWNERS
- upup/pkg/fi/cloudup/openstack/OWNERS
- upup/pkg/fi/cloudup/openstacktasks/OWNERS
- upup/pkg/fi/cloudup/spotinsttasks/OWNERS
- upup/pkg/fi/cloudup/vsphere/OWNERS
- upup/pkg/fi/cloudup/vspheretasks/OWNERS
- upup/pkg/fi/nodeup/OWNERS
This will automatically label PRs that touch these directories.
This makes it easier to query GitHub for PRs that affect certain areas of the code.
I mostly used existing labels but created some new ones as well.
> Add labels to OWNERS files

- upup/pkg/fi/assettasks/copyfile.go
- util/pkg/hashing/hash.go
Cherry pick of #8694 on release-1.17.
#8694: Fix uploading of file assets
> Automated cherry pick of #8694: Fix uploading of file assets

- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Let's see if kube-router v0.4.0 fixes the issues we are seeing in e2e:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-cni-kuberouter/1238479448160866306
> Update kube-router to v0.4.0

- upup/models/cloudup/resources/addons/storage-aws.addons.k8s.io/v1.15.0.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #8582 on release-1.17.
#8582: Update expected
> Automated cherry pick of #8582: Create New Default StorageClass: kops-ssd-1-17

- pkg/model/gcemodel/storageacl.go
This expands the code that gets turned on and off under the `GoogleCloudBucketACL` flag.
It wasn't clear to me why the flag applied to only one of the ACLs that we were setting. If this is not the intended behavior, we should document how to use the flag a bit more clearly :)
> Tweak the featureflag.GoogleCloudBucketACL.Enabled

- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Followup of #8742. This time works on my test cluster also.
> Fix template for kube-router v0.4.0 #2

- docs/operations/etcd_administration.md
- mkdocs.yml
Document for https://github.com/kubernetes/kops/issues/8400
> etcd admin doc

- nodeup/pkg/model/kubectl.go
> Update default user for CoreOS, Flatcar for kubecfg

- upup/pkg/fi/BUILD.bazel
- upup/pkg/fi/files_test.go
> Add UT for upup/pkg/fi/files.go

- docs/instance_groups.md
- pkg/apis/kops/instancegroup.go
- pkg/apis/kops/v1alpha2/instancegroup.go
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Also improved consistency of rest of InstanceGroup docs and some docstrings
Try no 3 to get Travis to successfully report build status after #8829 and #8818
> Cleanup InstanceGroup MixedInstancePolicy docs

- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://docs.projectcalico.org/v3.13/release-notes/#v3132
> Update Calico and Canal to v3.13.2

- pkg/pretty/BUILD.bazel
- pkg/pretty/help_test.go
- pkg/systemd/BUILD.bazel
- pkg/systemd/escaping_test.go
- pkg/urls/BUILD.bazel
- pkg/urls/join_test.go
> pkg: add some unit tests

- Makefile
Use go run, instead of trying to install and then run.
> Makefile: simplify running go-bindata

- Makefile
- images/dns-controller-builder/Dockerfile
- images/protokube-builder/Dockerfile
Adding a few places I missed previously.
> Update go to 1.13.9 (continued)

- dnsprovider/pkg/dnsprovider/providers/coredns/BUILD.bazel
- dnsprovider/pkg/dnsprovider/providers/coredns/rrchangeset.go
- dnsprovider/pkg/dnsprovider/providers/coredns/rrsets.go
- dnsprovider/pkg/dnsprovider/providers/coredns/stubs/BUILD.bazel
- dnsprovider/pkg/dnsprovider/providers/coredns/stubs/corednsapi.go
- protokube/pkg/protokube/BUILD.bazel
- protokube/pkg/protokube/gce_volume.go
- upup/pkg/fi/assettasks/BUILD.bazel
- upup/pkg/fi/assettasks/docker_api.go
- upup/pkg/fi/cloudup/gce/BUILD.bazel
- upup/pkg/fi/cloudup/gce/gce_cloud.go
- upup/pkg/fi/cloudup/gce/instancegroups.go
- upup/pkg/fi/cloudup/gce/network.go
- upup/pkg/fi/cloudup/gce/wrappers.go
- util/pkg/vfs/BUILD.bazel
- util/pkg/vfs/context.go
- util/pkg/vfs/gsfs.go
It's not x-perimental any more!
> Replace deprecated x/net/context with context

- docs/README.md
- docs/extra.css
- docs/index.md
- Adds note to index.md only visible in github
- Adds note to docs/README.md
> Adds docsite hidden note on index.md

- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #8795 #8865 on release-1.17.
#8795: Canal v3.13.1
#8865: Update Calico and Canal to v3.13.2
> Cherry pick of #8795 #8865: Update Calico and Canal to v3.13.2

- docs/cluster_spec.md
- docs/instance_groups.md
- docs/tutorial/working-with-instancegroups.md
- mkdocs.yml
* try to make cluster and IG docs more consistent
* split the IG docs between the spec and common operational use cases
> Clean up the spec docs

- cmd/kops/create_ig.go
- cmd/kops/delete_cluster.go
- cmd/kops/export_kubecfg.go
- cmd/kops/get_cluster.go
- cmd/kops/rollingupdatecluster.go
- cmd/kops/upgrade_cluster.go
- cmd/kops/validate_cluster.go
- pkg/model/components/containerd_test.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/deepvalidate_test.go
- upup/pkg/fi/cloudup/loader.go
- upup/pkg/fi/cloudup/networking.go
- upup/pkg/fi/cloudup/populate_cluster_spec.go
- upup/pkg/fi/cloudup/populatecluster_test.go
- upup/pkg/fi/cloudup/populateinstancegroup_test.go
- upup/pkg/fi/cloudup/spec_builder.go
ref: #8244 
Updated import package aliases:
`api "k8s.io/kops/pkg/apis/kops"` -> `kopsapi "k8s.io/kops/pkg/apis/kops"`
> Import package aliases modified

- nodeup/pkg/model/containerd.go
- pkg/model/components/containerd.go
https://github.com/containerd/containerd/releases/tag/v1.3.4
> Add support for containerd v1.3.4

- pkg/kopscodecs/codecs_test.go
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
> Add unit test for func rewriteAPIGroup

- pkg/model/firewall_test.go
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
> Add unit test for func JoinSuffixes

- nodeup/pkg/model/sysctls.go
It looks like the same problems are occuring on rhel7, so turn on the
fixes there also.
> Turn on flannel sysctl fixes on rhel7 as well

- pkg/systemd/escaping_test.go
> Add unit test case for pkg/systemd/escaping_test.go

- pkg/k8sversion/version_test.go
> Modify the wrong name for unit test case

- pkg/instancegroups/instancegroups.go
> Ignore already-deleted nodes during rolling update

- .github/workflows/main.yml
Resolves #8984. This adds a parallel Github Actions implementation of what's also being run at Travis CI.
> Add initial github actions workflow

- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- k8s/crds/kops.k8s.io_instancegroups.yaml
- nodeup/pkg/model/kube_apiserver_test.go
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
Porting https://github.com/kubernetes/kops/pull/8967 to 1.17 release
> cherry pick of #8967 upstream release 1.17

- docs/single-to-multi-master.md
- pkg/apis/kops/validation/BUILD.bazel
- pkg/apis/kops/validation/cluster.go
- pkg/apis/kops/validation/cluster_test.go
Removes some necessary restrictions and updating the docs.
Fixes #8091
> Allow single to multi-master cluster

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.6.1
> Upgrade amazon vpc cni to 1.6.1

- docs/README.md
- docs/operations/images.md
This was a bit out of date and may be easier to just point people to it than explaining the issues every time.
> Update docs on supported distros and images

- cmd/kops/create_cluster.go
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/model/gcemodel/autoscalinggroup.go
- tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
- tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-a-ha-gce-example-com_metadata_startup-script
- tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-b-ha-gce-example-com_metadata_startup-script
- tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-c-ha-gce-example-com_metadata_startup-script
- tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_nodes-ha-gce-example-com_metadata_startup-script
- tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script
- tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script
It's cloud-provider specific, so belongs in CloudConfig.
/cc @geojaz
> Move GCEServiceAccount into CloudConfig

- nodeup/pkg/model/kubelet.go
Flatcar has just added `conntrack` to their distro and the static utils are no longer needed.
https://github.com/flatcar-linux/portage-stable/pull/48
> Don't install static utils for Flatcar

- docs/operations/images.md
3rd pass at this doc with very small changes.
> Update docs on supported distros and release notes

- pkg/resources/aws/aws.go
> Treat NatGatewaysNotFound error as already-deleted

- README.md
- docs/advisories/README.md
- docs/index.md
Also fixing bulleted list on the advisory index page.
/hold
> Add advisory notice to readme and docs homepage

- pkg/instancegroups/instancegroups.go
Manual cherry-pick of https://github.com/kubernetes/kops/pull/8994 into 1.17
> manual cherry-pick #8994 into 1.17.

- upup/pkg/fi/files_owner.go
> Cherry pick of #8576 onto release-1.17

- cmd/kops/completion.go
> Fix zsh completion

- util/pkg/hashing/BUILD.bazel
- util/pkg/hashing/hash_test.go
> Add unit test for util/pkg/hashing/hash.go

- addons/kube-state-metrics/addon.yaml
- addons/kube-state-metrics/v1.9.5.yaml
> Adding most recent version of kube-state-metrics - 1.9.5

- pkg/validation/validate_cluster.go
- pkg/validation/validate_cluster_test.go
> Return cluster validation failure if ASG missing

- docs/advanced/experimental.md
- docs/getting_started/spot-ocean.md
- mkdocs.yml
This PR adds documentation for the Spot provider.
> Spotinst: Documentation

- pkg/k8sversion/version_test.go
> Add unit test case for pkg/k8sversion/version_test.go

- pkg/instancegroups/rollingupdate_test.go
> Reduce test flakiness

- cmd/kops/create_cluster.go
Cherry pick of #8002 on release-1.17.
#8002: Minor fix to have proper indexing for digital ocean
> Automated cherry pick of #8002: Minor fix to have proper indexing for digital ocean

- docs/cluster_spec.md
- docs/operations/etcd_backup_restore_encryption.md
Followup for https://github.com/kopeio/etcd-manager/pull/322
> Document etcd-manager backups retention settings

- pkg/model/iam/iam_builder.go
- upup/models/vfs.go
- util/pkg/vfs/fs.go
- util/pkg/vfs/gsfs.go
- util/pkg/vfs/k8sfs.go
- util/pkg/vfs/memfs.go
- util/pkg/vfs/ossfs.go
- util/pkg/vfs/s3fs.go
- util/pkg/vfs/sshfs.go
- util/pkg/vfs/swiftfs.go
- util/pkg/vfs/vfs.go
@justinsb noticed a few minor issues with https://github.com/kubernetes/kops/pull/9171.
> Fix nits for removal of S3 file versions

- pkg/commands/status_discovery.go
- pkg/resources/digitalocean/BUILD.bazel
- pkg/resources/digitalocean/cloud.go
- pkg/resources/digitalocean/resources.go
- upup/pkg/fi/cloud.go
- upup/pkg/fi/cloudup/aliup/ali_cloud.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/baremetal/cloud.go
- upup/pkg/fi/cloudup/dotasks/loadbalancer.go
- upup/pkg/fi/cloudup/dotasks/volume.go
- upup/pkg/fi/cloudup/dotasks/volume_test.go
- upup/pkg/fi/cloudup/gce/gce_cloud.go
- upup/pkg/fi/cloudup/openstack/cloud.go
- upup/pkg/fi/cloudup/vsphere/vsphere_cloud.go
Cherry pick of #8180 #9116 on release-1.17.
#8180: Refactor: Add Region() method to fi.Cloud
#9116: Changes for handling kops update
> Automated cherry pick of #8180: Refactor: Add Region() method to fi.Cloud #9116: Changes for handling kops update

- OWNERS
> Add comment in OWNERS linking to test-infra OWNERS files

- nodeup/pkg/model/kube_scheduler.go
https://github.com/kubernetes/kubernetes/pull/91420
> Use kubescheduler.config.k8s.io/v1beta1 for Kubernetes 1.19

- cmd/kops/delete_secret.go
- docs/cli/kops_delete_secret.md
> Add example for delete secret

- docs/releases/1.19-NOTES.md
> Start release notes for kops 1.19

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
https://github.com/kopeio/etcd-manager/releases/tag/3.0.20200531
> Update etcd-manager to 3.0.20200531

- channels/stable
It's been 9 days since these version were updated in alpha and no issues were raised, seems safe enough to push to stable.
> Updating stable channel with May updates

- upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
Cherry pick of #9249 on release-1.17.
#9249: update RBAC for DO CCM
> Automated cherry pick of #9249: update RBAC for DO CCM

- .shipbot.yaml
Shipbot config needs updating after #8922 and #9197.
> Update shipbot config

- docs/advanced/download_config.md
- docs/authentication.md
- docs/aws-china.md
- docs/cluster_spec.md
- docs/development/adding_a_feature.md
- docs/development/new_kubernetes_version.md
- docs/development/vendoring.md
- docs/getting_started/aws.md
- docs/getting_started/install.md
- docs/iam_roles.md
- docs/instance_groups.md
- docs/labels.md
- docs/mfa.md
- docs/networking/lyft-vpc.md
- docs/node_authorization.md
- docs/operations/addons.md
- docs/operations/etcd_administration.md
- docs/operations/etcd_backup_restore_encryption.md
- docs/operations/service_account_token_volumes.md
- docs/rotate-secrets.md
- docs/run_in_existing_vpc.md
- docs/secrets.md
- docs/security_groups.md
- docs/state.md
- docs/terraform.md
- docs/topology.md
- docs/upgrade_from_kubeup.md
- mkdocs.yml
also updating the globe logo's link to the docs homepage
> Docs - add syntax highlighting + markdown cleanup

- upup/pkg/fi/cloudup/loader.go
- upup/pkg/fi/named.go
- upup/pkg/fi/nodeup/nodetasks/archive.go
- upup/pkg/fi/nodeup/nodetasks/bindmount.go
- upup/pkg/fi/nodeup/nodetasks/chattr.go
- upup/pkg/fi/nodeup/nodetasks/file.go
- upup/pkg/fi/nodeup/nodetasks/group.go
- upup/pkg/fi/nodeup/nodetasks/issue_cert.go
- upup/pkg/fi/nodeup/nodetasks/load_image.go
- upup/pkg/fi/nodeup/nodetasks/package.go
- upup/pkg/fi/nodeup/nodetasks/service.go
- upup/pkg/fi/nodeup/nodetasks/user.go
> Don't require nodeup tasks to have SetName()

- pkg/model/iam/iam_builder.go
This will enable us to apply similar restricted permissions on GCE and
other clouds.
> IAM: Refactor vfs-access logic so we can see the required readable paths

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
https://github.com/weaveworks/weave/releases/tag/v2.6.5
> Update Weave Net to 2.6.5

- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
Cleaner, and preparation for ServiceAccount IAM support.
> Refactor BootstrapChannelBuilder to use a KopsModelContext

- docs/releases/1.16-NOTES.md
- docs/releases/1.17-NOTES.md
- docs/releases/1.18-NOTES.md
/cc @mikesplain @rifelpet 
/hold for all cherrypicks to merge
> Update release notes for Ubuntu 20.04 and CVEs

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://docs.projectcalico.org/archive/v3.9/release-notes/
> Update Calico for CVE-2020-13597

- pkg/model/components/kubedns.go
Minor tweaks to the code-style when filling out the NodeLocalDNS
config, just to make it more consistent.
> NodeLocalDNS config population: small tweaks

- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/populate_cluster_spec.go
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/cloudup/template_functions_test.go
We had some fields that were duplicated; this was confusing and seemed
likely to cause (subtle) bugs.
> Refactor to clean up TemplateFunctions

- docs/overrides/main.html
- mkdocs.yml
Inspired by https://github.com/kubernetes-sigs/kind/pull/1670
which was lightly adapted from kubernetes-sigs/kubebuilder#1553
originally from kubernetes/website#21505
> Add notice from k8s.io to docs site

- docs/overrides/main.html
Follow up to #9393
Fixes #9405
> Fix override css

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This PR upgrades the Spotinst controller to version 1.0.61.
> Spotinst: Upgrade the Spotinst controller to version 1.0.61

- pkg/kopscodecs/codecs_test.go
Signed-off-by: zouyu <zouy.fnst@cn.fujitsu.com>
> Add unit test for func VersionedJSON

- docs/networking/cilium.md
> Cilium requires manual restart when migrating to nodeport

- Makefile
- cloudbuild.yaml
> Cherry pick of #9272 onto release-1.18

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://github.com/cloudnativelabs/kube-router/releases/tag/v1.0.0
> Update kube-router to v1.0.0

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Another attempt at https://github.com/kubernetes/kops/pull/7476.
> Fix KubeDNS missing resourceVersion

- upup/pkg/fi/files_test.go
- util/pkg/vfs/fs_test.go
> Add some err judgments

- pkg/model/components/etcdmanager/model.go
> Add missing lifecycle to etcd keypair tasks

- Makefile
- WORKSPACE
- docker/Dockerfile
- images/dns-controller-builder/Dockerfile
- images/protokube-builder/Dockerfile
https://groups.google.com/g/golang-dev/c/Fuxyd9YQLCw
Followup to #9499 which was merged a few hours ago (I should have seen this coming)
> Upgrade go to 1.14.5

- channels/alpha
https://github.com/kubernetes/kubernetes/releases/tag/v1.19.0-rc.1
https://github.com/kubernetes/kubernetes/releases/tag/v1.18.6
https://github.com/kubernetes/kubernetes/releases/tag/v1.17.9
https://github.com/kubernetes/kubernetes/releases/tag/v1.16.13
> Update alpha channel with July releases

- nodeup/pkg/model/etcd.go
- pkg/wellknownusers/wellknownusers.go
> Use fixed UID for etcd user and restrict to legacy provider

- pkg/resources/ops/delete.go
Hopefully this gives more info on the what happens with https://github.com/kubernetes/kops/issues/9578.
/cc @rifelpet
> Print error during cluster delete for dependency violation

- OWNERS
If no objections, promoting John and myself to the approvers list. 😄
> Promote Ciprian & John to approvers

- channels/alpha
> Update stretch images (from 1.11) in alpha channel

- cmd/kops/update_cluster.go
- cmd/kops/validate.go
- cmd/kops/validate_cluster.go
- docs/cli/kops_validate.md
- docs/cli/kops_validate_cluster.md
- docs/getting_started/aws.md
- docs/rotate-secrets.md
- docs/single-to-multi-master.md
Cherry pick of #9333 on release-1.18.
#9333: Update cmd help text
> Automated cherry pick of #9333: Update cmd help text

- upup/pkg/fi/cloudup/openstacktasks/lb.go
- upup/pkg/fi/cloudup/openstacktasks/poolassociation.go
> remove LB circular in OpenStack

- cmd/kops/create.go
- cmd/kops/create_cluster.go
- cmd/kops/replace.go
- pkg/apis/kops/validation/validation.go
- pkg/model/components/BUILD.bazel
- pkg/model/components/apiserver.go
- pkg/model/components/kubecontrollermanager.go
- pkg/model/components/kubelet.go
- upup/pkg/fi/cloudup/BUILD.bazel
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/cloudup/template_functions_test.go
> Exempt OpenStack from the EnableExternalCloudController feature flag

- go.mod
- go.sum
- upup/pkg/fi/cloudup/awstasks/routetable.go
- vendor/github.com/aws/aws-sdk-go/aws/config.go
- vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/eventstreamapi/reader.go
- vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/header.go
- vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/message.go
- vendor/github.com/aws/aws-sdk-go/service/s3/api.go
- vendor/modules.txt
requires updating the aws sdk
ref: #9640
> Use "tag on create" for AWS Route Tables

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This PR upgrades the Spotinst controller to version 1.0.62.
> Spotinst: Upgrade the Spotinst controller to version 1.0.62

- .github/workflows/main.yml
- .travis.yml
- Makefile
- WORKSPACE
Moving in sync with Kubernetes 1.19: https://github.com/kubernetes/kubernetes/pull/93264.
> Upgrade Go to version 1.15rc1

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Adding the fix from #9609 to Canal also.
> Prefer nodes with "master" role for Canal Typha pods

- .github/ISSUE_TEMPLATE/bug_report.md
Hopefully this will result in easier to read cluster specs
> Add markdown code block to bug report GH issue template

- upup/pkg/fi/cloudup/dns.go
> Improve the error logged when multiple DNS Zones match the provided name

- docs/operations/images.md
> Update docs for Amazon Linux 2

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
This adds support for arm64
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.6.4
> Upgrade AWS VPC CNI provider to 1.6.4

- Makefile
> Fix test-windows target

- hack/update-goimports
- hack/verify-goimports
Broken by the migration to Go v1.15 and also fixing the error handling.
/cc @rifelpet
> Fix update and verify goimports

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
This should fix the ARM64 periodic tests.
xRef: https://github.com/kubernetes/k8s.io/pull/1131
> Update cluster-proportional-autoscaler to v1.8.3

- docs/operations/images.md
Preview URL: https://deploy-preview-9736--kubernetes-kops.netlify.app/operations/images/
Fixes https://github.com/kubernetes/kops/issues/9727.
> Update images docs

- channels/alpha
https://github.com/kubernetes/kubernetes/releases/tag/v1.18.8
https://github.com/kubernetes/kubernetes/releases/tag/v1.17.11
https://github.com/kubernetes/kubernetes/releases/tag/v1.16.14
> Update alpha channel with August releases

- docs/run_in_existing_vpc.md
Clean up and remove outdated information.
Closes #232
> Update shared-VPC documentation

- channels/alpha
- channels/stable
Signed-off-by: Marius Voila <myself@mariusv.com>
> Move kubernetes 1.18 from alpha to stable

- docs/releases/1.18-NOTES.md
As discussed during office hours.
> Add the client cert / ACM cert known issue to the 1.18 release notes

- docs/cluster_spec.md
- docs/releases/1.18-NOTES.md
Fixes: #9688
Preview:
* https://deploy-preview-9760--kubernetes-kops.netlify.app/releases/1.18-notes/#breaking-changes
* https://deploy-preview-9760--kubernetes-kops.netlify.app/cluster_spec/#networking
> Document Docker iptables settings

- cmd/kops-controller/pkg/server/server.go
- nodeup/pkg/model/context.go
- nodeup/pkg/model/kops_controller.go
- nodeup/pkg/model/networking/BUILD.bazel
- nodeup/pkg/model/networking/cilium.go
- pkg/apis/kops/model/features.go
- pkg/model/iam/iam_builder.go
- upup/pkg/fi/cloudup/template_functions.go
> Issue the cilium etcd client cert out of kops-controller

- .shipbot.yaml
> Add all images to GH release

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://docs.projectcalico.org/archive/v3.15/release-notes/
> Update Calico to v3.15.2 for k8s 1.16+

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://github.com/cloudnativelabs/kube-router/releases/tag/v1.0.1
> Update kube-router to v1.0.1

- Makefile
- hack/set-version
- pkg/assets/builder.go
- pkg/model/components/kubeapiserver/model.go
- pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
xRef: https://github.com/kubernetes/k8s.io/pull/1175
> Pull images from k8s.gcr.io/kops instead of docker.io/kope

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.7.1
> Upgrade AWS VPC CNI to 1.7.1

- pkg/model/openstackmodel/BUILD.bazel
- pkg/model/openstackmodel/context.go
- pkg/model/openstackmodel/firewall.go
- pkg/model/openstackmodel/servergroup_test.go
- upup/pkg/fi/cloudup/openstacktasks/securitygrouprule.go
> Remove unknown rules from managed security groups on openstack

- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/loader.go
- upup/pkg/fi/cloudup/populate_cluster_spec.go
- upup/pkg/fi/resources.go
> Remove more machinery for file-based cloudup models

- pkg/model/iam/iam_builder.go
This helps for the JWKS / ServiceAccount role support.
> Refactor IAM route53 construction

- util/pkg/vfs/fs.go
> Map ENOENT to ErrNotExist in FSPath

- .github/workflows/main.yml
- .travis.yml
- WORKSPACE
https://github.com/golang/go/compare/go1.15...go1.15.1
> Update Go to v1.15.1

- nodeup/pkg/model/tests/golden/awsiam/tasks-kube-apiserver.yaml
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-apiserver.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-amd64.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-arm64.yaml
- pkg/model/components/apiserver.go
- tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/privatecalico/data/aws_launch_template_master-us-test-1a.masters.privatecalico.example.com_user_data
> Don't explicitly set insecure-bind-address on newer k8s

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://docs.projectcalico.org/archive/v3.15/release-notes/
> Update Calico to v3.15.3

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://docs.projectcalico.org/archive/v3.16/release-notes/
> Update Calico to v3.16.1

- pkg/model/components/clusterautoscaler.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
> Add missing flags to cluster autoscaler template

- pkg/apis/kops/model/BUILD.bazel
- pkg/apis/kops/model/features_test.go
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
> Add unit test for pkg/apis/kops/model/features.go

- .github/workflows/main.yml
- .travis.yml
- WORKSPACE
https://github.com/golang/go/compare/go1.15.1...go1.15.2
> Update Go to v1.15.2

- Makefile
- hack/set-version
- pkg/model/components/kubeapiserver/model.go
- pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
- upup/pkg/fi/cloudup/urls_test.go
- version.go
As discussed during office hours, new Alpha release for 1.19.
> Release 1.19.0-alpha.4

- upup/pkg/fi/cloudup/openstacktasks/floatingip.go
Set description field on existing floating ips
fixes #9957 
/cc @zetaab
> Fix fip description

- images/mkdocs/Dockerfile
- images/mkdocs/requirements.txt
This should fix the netlify builds
> Update mkdocs dependencies and pin macro plugin

- cmd/kops/delete_instance.go
> Fix nil pointer when instance has not joined the cluster

- docs/getting_started/aws.md
> Clarified S3 state store encryption default

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
> Fix CAS ASG configuration

- docs/getting_started/openstack.md
Fix a pair of small typos in the openstack docs
> Fix pair of typos in openstack docs

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template
Also fixes a bug in the manifest.
> Bump NTH to 1.8

- pkg/model/components/cilium.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
> Bump cilium to 1.8.4

- pkg/model/network.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/vpc.go
- upup/pkg/fi/cloudup/awstasks/vpccidrblock.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
> Fix support for multiple additionalNetworkCIDR blocks

- cmd/kops/create_cluster.go
- cmd/kops/create_ig.go
- cmd/kops/edit_cluster.go
- cmd/kops/edit_instancegroup.go
- cmd/kops/toolbox_instance_selector.go
- cmd/kops/update_cluster.go
- nodeup/pkg/model/kubelet_test.go
- pkg/commands/helpers_readwrite.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/defaults.go
- upup/pkg/fi/cloudup/defaults_test.go
- upup/pkg/fi/cloudup/populate_cluster_spec.go
- upup/pkg/fi/cloudup/populate_instancegroup_spec.go
- upup/pkg/fi/cloudup/populatecluster_test.go
- upup/pkg/fi/cloudup/populateinstancegroup_test.go
- upup/pkg/fi/cloudup/subnets.go
- upup/pkg/fi/cloudup/subnets_test.go
- upup/pkg/fi/cloudup/validation_test.go
- upup/pkg/kutil/convert_kubeup_cluster.go
- upup/pkg/kutil/import_cluster.go
Almost all use of BuildCloud now happens in the main package and then pushed down from there.
> More removals of BuildCloud

- pkg/model/components/docker.go
- tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/privatecalico/data/aws_launch_template_master-us-test-1a.masters.privatecalico.example.com_user_data
- tests/integration/update_cluster/privatecalico/data/aws_launch_template_nodes.privatecalico.example.com_user_data
- upup/pkg/fi/cloudup/populatecluster_test.go
This aligns Docker and containerd update policy with other components.
> Update Docker version defaults for older k8s versions

- pkg/validation/validate_cluster.go
Have cluster validation consider the required static pods as being present even when they don't have a PriorityClassName.
Fixes #10041
> Don't require PriorityClassName to pass missing-static-pod checks

- pkg/validation/validate_cluster.go
Cherry pick of #10049 on release-1.18.
#10049: Don't require PriorityClassName to pass missing-static-pod
> Automated cherry pick of #10049: Don't require PriorityClassName to pass missing-static-pod

- Makefile
- pkg/instancegroups/rollingupdate_os_test.go
- pkg/model/components/kubeapiserver/model.go
- pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
- upup/pkg/fi/cloudup/urls_test.go
- version.go
Decided to one more Alpha during the October 9th Office Hours.
> Release 1.19.0-alpha.5

- pkg/model/openstackmodel/firewall.go
> do not create egress rules when using vipacl octavia

- docs/development/release.md
> Update docs for cutting new release branches

- README-ES.md
- docs/welcome/office_hours.md
Update zoom links on the Spanish README
> Update zoom links on the spanish README

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.flannel/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://github.com/coreos/flannel/releases/tag/v0.13.0
> Update Flannel CNI to v0.13.0

- upup/pkg/fi/cloudup/alitasks/loadbalancer.go
- upup/pkg/fi/cloudup/awstasks/load_balancer.go
- upup/pkg/fi/cloudup/dotasks/loadbalancer.go
Cherry pick of #10086 on release-1.19.
#10086: Ignore changes to ForAPIServer field
> Automated cherry pick of #10086: Ignore changes to ForAPIServer field

- nodeup/pkg/model/kubelet.go
- nodeup/pkg/model/networking/cilium.go
> Cert circular deps

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This PR upgrades the Spot Cluster Controller to 1.0.68.
> Spotinst: Bump the Spot Cluster Controller to 1.0.68

- cmd/kops/integration_test.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
Cherry pick of #10106 on release-1.19.
#10106: Remove dependency of TerraformJSON feature flag
> Automated cherry pick of #10106: Remove dependency of TerraformJSON feature flag

- docs/releases/1.18-NOTES.md
> Fix release notes links to point to https://kops.sigs.k8s

- pkg/instancegroups/rollingupdate_os_test.go
- upup/pkg/fi/cloudup/openstack/cloud.go
- upup/pkg/fi/cloudup/openstack/instance.go
- upup/pkg/fi/cloudup/openstack/mock_cloud.go
- upup/pkg/fi/cloudup/openstack/port.go
- upup/pkg/fi/cloudup/openstacktasks/instance.go
Cherry pick of #10178 on release-1.19.
#10178: Reset deviceID status if needed
> Automated cherry pick of #10178: Reset deviceID status if needed

- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
> Fix auto scaling group changes when using spot instances

- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/targetgroup.go
Some missing pieces to be able to restore a broken setup.
/cc @rifelpet
> Fix AWS NLB reconciliation

- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/targetgroup.go
Cherry pick of #10199 on release-1.19.
#10199: Fix AWS NLB reconciliation
> Automated cherry pick of #10199: Fix AWS NLB reconciliation

- .github/workflows/main.yml
- .travis.yml
- WORKSPACE
... and remove the *very slow* TravisCI AMD64 job.
/cc @rifelpet
> Update Go to v1.15.4

- Makefile
- pkg/model/components/kubeapiserver/model.go
- pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
- upup/pkg/fi/cloudup/urls_test.go
- version.go
> Release 1.19.0-beta.1

- docs/cluster_spec.md
> Fix cluster autoscaler docs

- channels/alpha
* https://github.com/kubernetes/kubernetes/releases/tag/v1.17.14
* https://github.com/kubernetes/kubernetes/releases/tag/v1.18.12
* https://github.com/kubernetes/kubernetes/releases/tag/v1.19.4
> Update k8s versions nov 2020

- pkg/apis/kops/validation/instancegroup.go
- pkg/apis/kops/validation/validation.go
- pkg/resources/aws/aws.go
- pkg/resources/aws/errors.go
- tests/integration/update_cluster/externalpolicies/in-v1alpha2.yaml
- tests/integration/update_cluster/externalpolicies/kubernetes.tf
- upup/pkg/fi/dryrun_target.go
* Validate external IAM policies
* Print changes also for consistency errors
* Handle cluster cleanup more gracefully
> Fix various nits

- .travis.yml
> Switch ARM64 CI to Graviton2 CPU

- docs/cluster_spec.md
Dynamic auditing was removed in https://github.com/kubernetes/kubernetes/pull/91502.
Preview: https://deploy-preview-10231--kubernetes-kops.netlify.app/cluster_spec/#audit-logging
> Update docs related to audit logging

- pkg/apis/kops/validation/instancegroup.go
- pkg/apis/kops/validation/validation.go
- pkg/resources/aws/aws.go
- pkg/resources/aws/errors.go
- tests/integration/update_cluster/externalpolicies/in-v1alpha2.yaml
- tests/integration/update_cluster/externalpolicies/kubernetes.tf
- upup/pkg/fi/dryrun_target.go
Cherry pick of #10217 on release-1.19.
#10217: Fix various nits
> Automated cherry pick of #10217: Fix various nits

- Makefile
- cloudbuild.yaml
- cmd/kops-controller/BUILD.bazel
- cmd/kube-apiserver-healthcheck/BUILD.bazel
- dns-controller/cmd/dns-controller/BUILD.bazel
One last thing remaining for ARM64 support.
This is the first try, based on https://github.com/kubernetes/cloud-provider-aws/blob/master/cloudbuild.yaml.
/cc @rifelpet
> Push multi-arch images

- channels/alpha
Refreshing images with latest packages.
> alpha channel: update legacy images

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/options.go
xRef: https://github.com/kubernetes/kubernetes/pull/94536
> Use etcd v3.4.13 for k8s v1.19+

- Makefile
- pkg/model/components/kubeapiserver/model.go
- pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
- upup/pkg/fi/cloudup/urls_test.go
- version.go
/hold for #10288 and #10290 to merge
> Release 1.19.0-beta.2

- Makefile
- pkg/model/components/kubeapiserver/model.go
- pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
- upup/pkg/fi/cloudup/urls_test.go
- version.go
> Update kOps version after 1.19.0-beta.2 release

- k8s/crds/kops.k8s.io_clusters.yaml
- nodeup/pkg/model/kube_apiserver.go
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/complex/data/aws_launch_template_master-us-test-1a.masters.complex.example.com_user_data
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
Automated cherrypick of #10275 onto release-1.19
> Automated cherrypick of #10275 onto release-1.19

- Makefile
Followup of #10267. 
/cc @olemarkus
> Optimize Bazel dev builds by arch

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://docs.projectcalico.org/archive/v3.17/release-notes/
> Update Calico to v3.17.0

- go.mod
- go.sum
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/github.com/aws/aws-sdk-go/service/autoscaling/api.go
- vendor/github.com/aws/aws-sdk-go/service/cloudformation/api.go
- vendor/github.com/aws/aws-sdk-go/service/elbv2/api.go
- vendor/github.com/aws/aws-sdk-go/service/elbv2/doc.go
- vendor/github.com/aws/aws-sdk-go/service/s3/api.go
- vendor/modules.txt
https://github.com/aws/aws-sdk-go/releases/tag/v1.36.0
> Update aws-sdk-go to v1.36.0

- cmd/kops/create_cluster_integration_test.go
- tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zone/options.yaml
> Add integration test for creating an HA cluster in shared zone

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
> Cilium bump 1.18

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.7.7
> Bump aws-cni to 1.7.7

- OWNERS
Removing myself from the reviewers list as I haven't been able to dedicate the required time to this role as well as us moving to EKS at work.
Raised the mirror PR to test-infra, see below.
> Remove gjtempleton as reviewer

- pkg/model/awsmodel/BUILD.bazel
- pkg/model/awsmodel/autoscalinggroup.go
- tests/integration/update_cluster/externallb/cloudformation.json
- tests/integration/update_cluster/externallb/in-v1alpha2.yaml
- tests/integration/update_cluster/externallb/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/targetgroup.go
- upup/pkg/fi/cloudup/awsup/BUILD.bazel
- upup/pkg/fi/cloudup/awsup/aws_utils.go
I hope this was it and should unblock 1.18.
/cc @rifelpet @rdrgmnzs
> Backport TargetGroup related fixes
