nodeup/pkg/model/kube_apiserver.go, nodeup/pkg/model/kube_controller_manager.go, nodeup/pkg/model/kube_proxy.go, nodeup/pkg/model/kube_scheduler.go, pkg/kubemanifest/BUILD.bazel, pkg/kubemanifest/priority.go, pkg/model/components/etcdmanager/model.go, pkg/model/components/etcdmanager/tests/minimal/tasks.yaml, protokube/pkg/protokube/etcd_manifest.go, protokube/tests/integration/build_etcd_manifest/main/etcd_env_vars.yaml, protokube/tests/integration/build_etcd_manifest/main/non_tls.yaml, protokube/tests/integration/build_etcd_manifest/main/tls.yaml
Setting a high priority for kube-proxy is important in clusters that run with PodPriority enabled, otherwise it will get evicted from worker nodes whenever there are unschedulable pods. Also set priorities for the other static pods defined by kops, mainly for completeness.
This should be safe these days since the API always accepts PriorityClassName even if PodPriority isn't enabled.
Fixes #6615.
=> Set priority for static pods

nodeup/pkg/model/node_authorizer.go, pkg/apis/kops/cluster.go, pkg/apis/kops/v1alpha1/cluster.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/cluster.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
Cherry pick of #7211 on release-1.12.
#7211: Use NodeAuthorizer config options instead of soely
=> Automated cherry pick of #7211: Use NodeAuthorizer config options instead of soely

pkg/commands/set_cluster.go
=> Cherry pick of #7160 onto release-1.13

upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Fix for TTA-2019-002.  Note that this is targeting the release-1.12 branch.  Release branch has already advanced to 3.7.
=> Update canal to 3.6.4, for TTA-2019-002

upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
Brings the kops templates in line with recent(ish) weave-net upstream changes. 
References:
weaveworks/weave#3421
weaveworks/weave#3417
=> Use readinessProbe for weave-net instead of livenessProbe

addons/cluster-autoscaler/v1.10.0.yaml
I had the following errors in the log:
E0715 06:51:45.385758       1 reflector.go:125] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:312: Failed to list *v1.DaemonSet: daemonsets.apps is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list daemonsets.apps at the cluster scope
E0715 06:51:45.399557       1 reflector.go:125] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:339: Failed to list *v1.ReplicaSet: replicasets.apps is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list replicasets.apps at the cluster scope
E0715 06:51:45.894870       1 reflector.go:125] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:330: Failed to list *v1.Job: jobs.batch is forbidden: User …
=> Add some permissions to cluster-autoscaler clusterrole

pkg/resources/spotinst/resources.go
The instance registration registers all active instances with their instance group. In addition, it looks for outdated instances by comparing each instance creation timestamp against the modification timestamp of its instance group. 
In a rolling-update operation, one or more detach operations are performed to replace existing instances. This is done by updating the instance group and results in updating the modification timestamp to the current time. The update of the modification timestamp occurs only after the detach operation is completed, meaning that new instances have already been created, so our comparison may be incorrect. 
In order to work around this issue, we assume that the detach operation will take up to two minutes, and therefore we subtract this duration from the …
=> Spotinst: Rolling update always reports NeedsUpdate

README.md, docs/README.md, docs/continuous_integration.md
Based on questions in #kops-users it seems like many are interested in running Kops in CI environments, or dont realize that they could/should. I'm hoping this page helps others in doing so.
We only use GitLab CI so i'm hoping anyone with setups in other platforms can add examples to this page as well. I'll try to add screenshots later down the road when I have more time to sanitize an example project and cluster in our environment.
Also, if anyone has any suggestions on improving the sample pipeline, it would be awesome if we could build off of the examples here.
=> Add documentation example for running Kops in a CI environment

upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Both in bootstrapchannelbuilder (follow-up to #7249), but also in
older versions, because it is a security fix for TTA-2019-002.
=> Calico -> 3.7.4 for older versions

docs/tutorial/digitalocean.md, pkg/model/components/etcdmanager/BUILD.bazel, pkg/model/components/etcdmanager/model.go, upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template, upup/pkg/fi/cloudup/dns.go, upup/pkg/fi/cloudup/do/cloud.go
Couple of updates to get digitial ocean cloud provider working with the latest master.
- Updated the digital ocean cloud manager to an updated version - 0.1.15
- Update KOPS_FEATURE_FLAGS to also include an override flag, this is temporary, I'll be adding the next set of changes to include support for etcd-manager, but until then we can use legacy support.
- Update etcd manager for DO cloud provider, so we don't get a not supported error. will be adding another PR for more changes to the etcdmanager repo to support DO.
Note: I have tested this change and it seems to work on release-1.12, release-1.13 and release-1.14 branches. I believe there is some issue with the latest master, I didn't see any logs generated in the master linux server once I SSH to it. If this gets approved, I would …
=> [Issue-7148] Legacyetcd support for Digital Ocean

nodeup/pkg/distros/distribution.go, nodeup/pkg/distros/identify.go, nodeup/pkg/model/docker.go
Ran some directions as per
https://github.com/kubernetes/kops/pull/7130
here's what I've done
git clone git@github.com:VibrentHealth/kops.git
cd kops
git remote add upstream https://github.com/kubernetes/kops
git fetch upstream
git merge upstream/master
git push origin 
//(our fork's master is now synced with upstream master)
git checkout -b rhel8_support
git cherry-pick f449e6194f763063781e08c4922f0ca1260bc900
git cherry-pick 592d7cd211df45d7e1869d217889ee1d8490724e
git cherry-pick 05c5af4137fae4121fae7fb0633692b420b5457c
git diff master
//(makes it look like only the desired diff is captured)
Created this new PR
Also worth mentioning: I looked into signing the CLA, and to my knowledge, the VibrentHealth organization signed it, and since myself and Cassandra are part of that organization …
=> Rhel8 support

cmd/kops/create.go, cmd/kops/delete.go, cmd/kops/replace.go
The function was trivial, and it is changed in a later k8s version.
=> Replace use of cmdutil IsFilenameSliceEmpty

channels/pkg/api/channel.go, channels/pkg/channels/addon.go, channels/pkg/channels/addons_test.go, channels/pkg/channels/channel_version.go, docs/addon_manager.md, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml, upup/pkg/fi/utils/BUILD.bazel, upup/pkg/fi/utils/hash.go
Improve channel updates  to use hash of manifests to ensure we always update.
=> Improve channel updates

hack/update-expected.sh
Otherwise we don't always pick up the latest changes to manifests.
=> hack/update-expected: regenerate gobindata

upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/utils/hash.go
It's a little confusing to have a hash function which auto-trims.  But
trimming the manifests does make sense.  We also want to be sure that
the hash matches the raw hash of the manifest, which it didn't when we
transformed the manifest "inside the hash".
=> Manifest hashing: move trimming out of hash function

docs/etcd3-migration.md
When running the upgrade process to quickly roll all the master, you can enter a state which causes nodes to become `NotReady`. This can lead to nodes (potentially _all_ nodes) being removed from ELBs managed by Kubernetes Services type LoadBalancer. In order to avoid this you can add an IAM policy which temporarily blocks Kubernetes from removing nodes from ELBs, thus mitigating the temporary reconciliation state.
=> Adding documentation to mitigate workload outages on AWS

nodeup/pkg/model/kube_controller_manager.go
Mounts the FlexVolume directory so that FlexVolumes with attach capability can run on KOPs clusters
=> Mount FlexVolume directory in kube-controller-manager pod

pkg/model/components/etcd.go
This is the current recommended etcd version for 1.14 / 1.15
=> Default etcd-version to 3.3.10 for >= 1.14

pkg/featureflag/featureflag.go, pkg/model/components/etcdmanager/BUILD.bazel, pkg/model/components/etcdmanager/options.go
Should prevent the scenario where etcd-manager can't come up because of a different version.
Can be bypassed with the SkipEtcdVersionCheck feature flag.
=> Warn/prevent if the version of etcd is unsupported with etcd-manager

addons/ingress-citrix/v1.1.1-aws.yaml, addons/ingress-citrix/v1.1.1.yaml
Updating the Citrix Ingress Controller manifest files to use the latest version of the Citrix Ingress Controller. Also refining the RBAC needed for Citrix Ingress Controller
=> Update Image version and RBAC for Citrix Ingress Controller

WORKSPACE
Fixes this error seen in the [bazel prow jobs](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kops/6958/pull-kops-bazel-test/1156660534251098112/):
`'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.`
Specifically picking up these fixes:
* https://github.com/kubernetes/repo-infra/pull/114
* https://github.com/GoogleContainerTools/distroless/pull/373
=> Update repo-infra and distroless for bazel fixes

hooks/nvidia-device-plugin/image/files/02-nvidia-docker.sh
xref #6728
When install the nvidia docker runtime, kubelet will try to restart stopped containers via old docker. This will leak those containers as orphan containers.
=> stop kubelet to prevent orphan containers

nodeup/pkg/model/kube_controller_manager.go
Default on COS is a different location, see
https://github.com/kubernetes/kubernetes/pull/58171
=> Update default flexvolumepath for COS

channels/stable
includes fixes for "TCP SACK PANIC" CVE
xref: https://github.com/kubernetes/kops/pull/7176
/cc @justinsb @KashifSaadat
=> Promote 1.12 image from alpha to stable

upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.6.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Bump kube-router version to v 0.3.1. This version includes various security fixes and performance improvements.
=> Update kube-router to 0.3.1

upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template, upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Weave has some [useful metrics](https://github.com/weaveworks/weave/blob/master/site/tasks/manage/metrics.md) that it exposes on two ports:
* `6782` - Weave router
* `6781` - Weave network policy controller
This change annotates the weave pod, making it a target for scraping by prometheus. 
It also adds two container ports, one for each container, which prometheus will probe for `/metrics` endpoints. This gets around the limitation that you can only have one `prometheus.io/port` annotation per pod. I've also given the ports the name "metrics" so that if necessary, users can adjust their prometheus configuration to [target them more directly](https://stackoverflow.com/a/46825817).
=> Enable scraping of weave metrics

pkg/model/components/etcd.go, pkg/model/components/etcdmanager/model.go, pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
Relnotes are at https://github.com/kopeio/etcd-manager/blob/master/docs/relnotes/3.0.20190801.md
Highlights:
* etcd-manager-ctl is now available in the image, and for download from github
* etcd 3.3.13 is included
* etcd-manager will now run a compatible version of etcd if it is available (for example, etcd 3.3.13 instead of 3.3.11), to better import backups or support migration
* listen-metrics-urls can now be specified and will be passed through to etcd
* improved docs around internals
=> Bump etcd-manager to 3.0.20190801

pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/componentconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/validation/validation.go, pkg/apis/kops/validation/validation_test.go, pkg/apis/kops/zz_generated.deepcopy.go, pkg/flagbuilder/buildflags_test.go
Adding the missing parameters I reported as an [issue](https://github.com/kubernetes/kops/issues/7321) the other day. First PR in a go repository so bear with me. Had a look at [previous similar addition](https://github.com/kubernetes/kops/commit/720174c678d934a4a2a28e10d39af7252fb81d56) an tried to figure it out from there. Added a few tests to verify and tested setting up a new cluster with the added parameters as well.
=> Add mappings for Webhook authorization mode.

cmd/kops/update_cluster.go, docs/cluster_spec.md, nodeup/pkg/model/kube_controller_manager.go, nodeup/pkg/model/kubelet.go, nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha2/componentconfig.go
Following the introduction of PR #6874 we had the following occur:
- A flex volume plugin directory was mounted on the kube controller manager even when no flag was specified
- The default flex volume plugin directory is not writeable for certain Operating Systems (e.g. CoreOS)
This PR will set the volume plugin dir according to OS (both for kubelet and controller manager) and always provides the flag to the controller manager.
=> Set and mount the correct volume plugin dir based on OS

pkg/model/resources/nodeup.go, tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
Currently the MIMEBOUNDARY header is added if one of the following cases is met:
- `AdditionalUserData` is set on an Instance Group
- `MixedInstancesPolicy` is set on an Instance Group
The latter being set on an IG for a CoreOS nodepool now breaks on provisioning the nodes, as CoreOS doesn't support MIME messages. It is still set as required when `AdditionalUserData` has been provided, but will need follow-up with further investigation to get additional user data scripts working when using CoreOS.
- Regressed in #6732 for CoreOS
- Fixes #7091
=>  Don't default adding MIMEBOUNDARY headers when a mixed instances policy is set

docs/releases/1.13-NOTES.md
Also backfill the beta.1 -> beta.2 notes
=> Add release notes for 1.13.0 beta.2 -> 1.13.0

nodeup/pkg/model/kube_scheduler.go, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/componentconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
This PR adds `maxPersistentVolumes` to the `KubeSchedulerConfig` struct, which allows the cluster operator to set the `KUBE_MAX_PD_VOLS` environment variable on the kube-scheduler static pod manifest to set a [custom node-specific volume limit](https://kubernetes.io/docs/concepts/storage/storage-limits/#custom-limits).
This env-var has been supported as far back as the [Kubernetes 1.7 scheduler](https://github.com/kubernetes/kubernetes/blob/release-1.7/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go#L49), which is older than the kops compatibility matrix. As such, I didn't add a Kubernetes version guard check; I also didn't bother going further back.
*Background:* We unfortunately need this, because even dynamic volume limits (supported in k8s 1.15) is still not conservative …
=> Add maxPersistentVolumes to support the KUBE_MAX_PD_VOLS scheduler setting

pkg/bundle/builder.go, tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml, tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml, tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data, tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_nodes.k8s-iam.us-west-2.td.priv_user_data, tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml, tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml, upup/pkg/fi/cloudup/apply_cluster.go, upup/pkg/fi/cloudup/urls.go
We weren't using mirrors for nodeup (just protokube), though the
existing bash script supports mirrors.
=> Support mirroring for nodeup also

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
Follow the example of Kube-DNS for scaling the CoreDNS deployment by use of a cluster proportional autoscaler. Also adds a 10% `maxSurge` tolerance.
YAML added is near identical to the existing CPA and associate roles etc. used in https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
Mutually exclusive with #6797
=> Use Cluster Proportional Autoscaler for CoreDNS 1.12+

upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
Version upgrade:
* v0.2.2 - fix unexpected panic when a Node gets deleted
=> Upgrading k8s-srcdst to v0.2.2

pkg/model/components/etcd.go, pkg/model/components/etcdmanager/BUILD.bazel, pkg/model/components/etcdmanager/model.go, pkg/model/components/etcdmanager/tests/minimal/tasks.yaml, pkg/model/openstackmodel/firewall.go
adds openstack support for etcd-manager, no need to use legacy anymore.
cc @drekle 
/hold
lets wait that openstack support for etcd-manager is added
=> add OpenStack etcd-manager support

channels/alpha
Add 1.13 and 1.14 images, bump 1.11 and 1.12 images.
=> Update AMIs in alpha channels

channels/alpha, channels/stable
https://discuss.kubernetes.io/t/security-release-of-kubernetes-v1-15-3-v1-14-6-v1-13-10-cve-2019-9512-and-cve-2019-9514/7596
=> promote k8s versions

pkg/model/components/kubelet.go
The E2E tests are [currently failing](https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-aws-1.14) due to this [kubelet error](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-beta/1163216201782923264/artifacts/52.77.251.45/kubelet.log):
`F0818 22:43:57.642896    6424 server.go:179] unrecognized feature gate: ExperimentalCriticalPodAnnotation`
This feature gate [was removed in Kubernetes 1.16](https://github.com/kubernetes/kubernetes/pull/80342)
=> Dont set ExperimentalCriticalPodAnnotation feature gate in k8s 1.16

protokube/tests/integration/build_etcd_manifest/integration_test.go
Signed-off-by: 928234269 <longfei.shang@daocloud.io>
fix typo in integration_test.go
=> fix typo "specifiction" -> "specification"

pkg/model/resources/nodeup.go, pkg/model/tests/data/bootstrapscript_0.txt, pkg/model/tests/data/bootstrapscript_1.txt, pkg/model/tests/data/bootstrapscript_2.txt, pkg/model/tests/data/bootstrapscript_3.txt, pkg/model/tests/data/bootstrapscript_4.txt, pkg/model/tests/data/bootstrapscript_5.txt, tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml, tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml, tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml, tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
We were previously assuming that the name of the URL matched the name
we wanted to download to, but also assuming that the name of the file
was nodeup.  Change to download to a known file location, whatever the
mirror url.
=> bash script: don't assume nodeup filename

docs/custom_ca.md
This adds a doc on how to create a `kops` cluster using a custom certificate authority, or with a previously `kops` generated CA keypair. I saw some PR issues on allowing this but no clear documentation on how to go about implementing it. This is how I got it to work, more than happy to adjust if anything is not totally accurate.
=> Add doc for using custom CA

.shipbot.yaml, Makefile, docs/development/release.md
I had omitted it previously, so it wasn't getting copied to mirrors.
=> Add nodeup to shipbot targets for release upload

channels/alpha, channels/stable
The kubernetesVersion in the kopsVersions block is used for new
clusters.  I had forgotten to update it, so new clusters were being
created with versions that then immediately recommended an update.
=> Update channel recommended versions for kops versions

upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #7444 on release-1.14.
#7444: upgrade weave to 2.5.2 to address the issues in
=> Automated cherry pick of #7444: upgrade weave to 2.5.2 to address the issues in

upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
This PR updates weave to 2.5.2 to alleviate the following issues:
- In Kubernetes cluster, when a pod is deleted and at the same time if weave-net pod is restarting or in rare occasion like when weave-kube container is hung then IP address assigned to the pod is not freed and never released, potentially running out of IP's to allocate to the pod's on the node #3587, #3638
- In Kubernetes cluster a reclaim daemon runs as part of kube-utils that automates weave forget for deleted nodes. Fixes panic that occurs in reclaim daemon resulting in weave to attempt to connect to dead nodes #3613, #3623
This can be seen here - https://github.com/weaveworks/weave/releases/tag/v2.5.2
=> Update weave to 2.5.2

pkg/model/resources/nodeup.go, pkg/model/tests/data/bootstrapscript_0.txt, pkg/model/tests/data/bootstrapscript_1.txt, pkg/model/tests/data/bootstrapscript_2.txt, pkg/model/tests/data/bootstrapscript_3.txt, pkg/model/tests/data/bootstrapscript_4.txt, pkg/model/tests/data/bootstrapscript_5.txt, tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml, tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml, tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml, tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
=> Cherry pick of #7448 onto release-1.14

cmd/kops/BUILD.bazel, cmd/kops/integration_test.go
This allows us to auto-fix the expected output also.
=> cloudformation tests: use standard file comparison

upup/pkg/fi/nodeup/nodetasks/service.go
Signed-off-by: Salvatore Mazzarino <dev@mazzarino.cz>
This solves an issue for Flatcar distribution. kops can't bootstrap because the systemd dir is not found due to unmatched tag.
How can we test this safely? Do we have integration tests that could cover this? If not I don't mind to create them
=> Fix Flatcar distro

README.md
Signed-off-by: Sakura <longfei.shang@daocloud.io>
=> fix typo "new" -> "newer"

docs/tutorial/digitalocean.md, pkg/model/components/etcdmanager/model.go
This PR incorporates changes to use etcd-manager, instead of the legacy mode.
Able to see the cluster coming up Ok with this change.
Please refer to the etcdmanager PR that is merged (https://github.com/kopeio/etcd-manager/pull/243) to incorporate DigitialOcean related changes.
=> [DO-7148] Digital Ocean support for etcd-manager

util/pkg/vfs/sshfs.go
Creating a new SSH session inside of an if-block also declared a new `err` variable with scope that never made it out to the return.
=> util/pkg/vfs: Fix swallowed errors

.travis.yml
We were observing some flakes in the travis builds pulling from
github; by setting GOPROXY we should avoid those; we also gain some
security.
=> Set GOPROXY in travis builds

go.sum, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
Currently ip to ip mode is hardcoded to be Always or CrossSubnet. However, ip to ip mode is taking quite big performance hit all the time. That is why we want to disable ip to ip mode in some services. We can see about ~10x increase in network performance if we use `never` option.
so the network config then is
```
networking:
calico:
majorVersion: v3
ipipMode: never
```
=> Allow configure ip to ip mode in calico

pkg/apis/kops/dockerconfig.go, pkg/apis/kops/v1alpha1/dockerconfig.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/dockerconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
Add exec options so it is possible to support `native.cgroupdriver=systemd` as recommended in k8s production documentation [0].
[0] https://kubernetes.io/docs/setup/production-environment/container-runtimes/
=> Add exec-opts options to dockerconfig

README.md, cmd/kops/create_cluster.go, docs/cli/kops_create_cluster.md, docs/tutorial/openstack.md, upup/pkg/fi/cloudup/apply_cluster.go
We have contributed quite much to OpenStack part of kops. Our opinion is that OpenStack should not be anymore in alpha, because the things are in place what is needed to really run kops OpenStack heavily. Etcd manager support is there and so on.
What you think @justinsb? As I see it, this is not big change from code perspective. However, we could get more users by moving it out of alpha and receive feedback from our mistakes :)
We have been using kops OpenStack already like 6 months without huge issues. Thing that comes to my mind is that rolling-update is not working perfectly without external autoscaler pod (https://github.com/ElisaOyj/kops-autoscaler-openstack we deploy this to under kube-system and it will handle autoscaling instances back when we run rolling update to cluster).
/cc …
=> move OpenStack from alpha to beta

docs/networking.md, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
(First part of #7390)
This adds `netExtraArgs` to the Weave spec and allows for adding extra command line parameters to weave net (well, technically weave-kube).
This has been tested by applying it to one of our clusters.
=> Add support for netExtraArgs

README.md
As discussed during office hours.
=> Cleanup versions, deprecate kops 1.10, remove k8s 1.8

Makefile, go.mod, hack/verify-gomod
Wrapper around go mod tidy
Currently doesn't delete from go.sum, which is untidy but expected
behaviour.
=> Create verify-gomod script

WORKSPACE, tools/bazel.rc
We particularly want the http fixes in 1.12.8:
https://golang.org/doc/devel/release.html#go1.12.minor
=> Update to golang 1.12.9

docs/examples/kops-tests-private-net-bastion-host.md
Corrected spelling of 'we' in the documentation.
=> Corrected spelling of 'we' in the documentation

cmd/kops/BUILD.bazel, cmd/kops/create.go, cmd/kops/delete.go, cmd/kops/replace.go
It was hiding what was actually going on here, which just a slice.
=> Replace resource.FilenameOptions with []string

upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
If I am using 1440 MTU in openstack, it is not working at all. After modifying it to 1430 calico works fine.
Like this doc says the correct value for openstack is 1430:
https://docs.projectcalico.org/v3.7/networking/mtu
=> Configure calico MTU

upup/models/cloudup/resources/addons/networking.flannel/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.flannel/k8s-1.6.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Similar to #3206 but for `flannel`, related to #3132
In this PR I updated the flannel's `cni` config file to enable `portmap` plugin and changed its extension from `.conf` to `.conflist` in order to support multiple plugins.
P.S.
I haven't changed pre 1.6 manifests, to avoid breaking old clusters that doesn't ship `portmap` plugin
=> Support for using hostPort when using flannel

cmd/kops/rollingupdatecluster.go, pkg/instancegroups/BUILD.bazel, pkg/instancegroups/rollingupdate.go
This is no longer needed now we are using the k8s drain code.
=> Remove unused ClientGetter from Drain code

pkg/instancegroups/instancegroups.go
This restores the kops behaviour before the refactor, where pods using
emptyDir would not block the rolling update.
=> DeleteLocalData on drain

tools/bazel.rc
Add some verbosity to bazel builds.
Includes some python changes from #7508
=> Add verbosity

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
[There is a known bug on `CoreOS` `1.3.1`](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#known-issues) wherein if the Kubernetes API shuts down while CoreDNS is connected, CoreDNS will crash. 
The workaround is to create a `/tmp` volume [See here](https://github.com/coredns/deployment/pull/138/files)
```
E0827 00:44:53.344864       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:322: Failed to list *v1.Namespace: Get https://172.20.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 172.20.0.1:443: connect: connection refused
E0827 00:44:53.344864       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:322: Failed to list *v1.Namespace: Get …
```
=> fix(addons/coredns.addons.k8s.io) Workaound to stop coredns crashing on 1.3.1 version

Makefile, WORKSPACE, tools/bazel.rc
The [kops-postsubmit jobs](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kops-postsubmit/1168617128891256836/) are currently failing with a python interpreter issue. See https://github.com/bazelbuild/rules_docker/issues/842 for more info and https://github.com/bazelbuild/rules_docker/issues/580 for tracking the long term fix.
Also updating the docker builds to use the same go version as https://github.com/kubernetes/kops/pull/7499
=> Update rules_docker with python2 workaround

pkg/resources/aws/aws.go
Right now, if a NatGateway is shared, kops will still try to remove ElasticIPs associated to the NatGateway when trying to delete a cluster. These ElasticIPs don't have any ownership tags.
This will never work, as kops is not deleting the NatGateway, and it shouldn't anyway, since kops doesn't own the ElasticIP.
Fixed this by not checking for ElasticIPs when trying to delete a shared NatGateway.
Tested that with an owned NatGateway, the associated Elastic IP is still deleted.
=> Don't try to delete ElasticIPs of NatGateway is shared

upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
The code comment says that Calico Kube Controllers isn't need in CRD mode, but we can see [docs of calico saying how to configure for datastore mode](https://docs.projectcalico.org/v3.8/reference/kube-controllers/configuration) and we started having problems using calico without this.
- We start seeing logs like this in `calico-node`:
```
2019-09-03 14:50:41.821 [INFO][24] ipam.go 311: Looking up existing affinities for host handle="ipip-tunnel-addr-ip-10-164-41-80.ec2.internal" host="ip-10-164-41-80.ec2.internal"
2019-09-03 14:50:41.966 [INFO][24] ipam.go 369: Ran out of existing affine blocks for host handle="ipip-tunnel-addr-ip-10-164-41-80.ec2.internal" host="ip-10-164-41-80.ec2.internal"
2019-09-03 14:50:41.971 [INFO][24] ipam.go 434: No more affine blocks, but need to allocate 1 …
```
=> fix(addons/networking.projectcalico.org) calico kube-controllers is needed in CRD mode

addons/metrics-server/README.md
Broken link: https://kubernetes.io/docs/tasks/debug-application-cluster/core-metrics-pipeline/
I assume the correct/updated URL is: https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/
Thank you!
=> docs: fix link to Metrics Server user guide

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
This PR fixes a protokube error while applying the `coredns` addon.  [We can see the same behavior (already fixed) on kubeadm using kube-dns](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/dns/manifests.go#L194-L196)
```
I0826 22:05:34.677310   14969 addon.go:130] Applying update from "s3://BUCKET-STATE-STORE/CLUSTER-NAME/addons/coredns.addons.k8s.io/k8s-1.12.yaml"
I0826 22:05:34.677339   14969 s3fs.go:220] Reading file "s3://BUCKET-STATE-STORE/CLUSTER-NAME/addons/coredns.addons.k8s.io/k8s-1.12.yaml"
I0826 22:05:34.693912   14969 apply.go:67] Running command: kubectl apply -f /tmp/channel974681140/manifest.yaml
I0826 22:05:34.853468   14969 apply.go:70] error running kubectl apply -f /tmp/channel974681140/manifest.yaml
The Service "coredns" is invalid: …
```
=> fix(upup/models/cloudup/resources/addons/coredns.addons.k8s.io) missing resourceVersion

pkg/resources/aws/aws.go
This is a cherry-pick to get #7525 (Don't try to delete ElasticIPs of NatGateway if shared) into 1.14.
=> Cherry-pick #7525 into 1.14

Makefile
This now includes the sha256 sum that we need going forwards.
=>  When fast-building, copy a newer version of utils.tar.gz

nodeup/pkg/model/kubelet.go, nodeup/pkg/model/protokube.go, protokube/cmd/protokube/main.go, protokube/pkg/protokube/BUILD.bazel, protokube/pkg/protokube/kube_boot.go, protokube/pkg/protokube/labeler.go, protokube/pkg/protokube/tainter.go
As of k8s 1.16, the node-role label is protected for security reasons.
We will introduce a controller to set those labels generically.
However, we need these labels to run the controller (only) on master
nodes.
To solve this bootstrapping problem, we use protokube to apply the
master role node labels to the master node only.  This isn't a
security problem because we assume that protokube on the master is
highly trusted - we are still administering labels centrally.
Then kops-controller can use this label to target the master nodes,
and run a central label controller.
=> Bootstrap: protokube labels its own node with node-role label

docs/networking.md, k8s/crds/kops_v1alpha2_cluster.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/validation/validation.go, pkg/apis/kops/validation/validation_test.go, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
After #7517 I noticed much of our calico is out of sync with upstream so I thought it may be worth reformatting to match upstream adding back our customizations. I know @gjtempleton has been working on adding Typha however he was facing rebasing issues, so I pulled them in here while upgrading us.  I'm doing more testing on this but I think we should target 1.15 for this and possibly 1.14 depending on testing time.
Key points on this pr:
* Add Typha (thanks @gjtempleton for taking care of the hard part)
* Updates to calico 3.8.2
* Replaces our format of calico for the official calico one which should allow updating easier in the future.
Todo:
/hold
Fixes #7181
Fixes #7158
=> Calico update and typha

WORKSPACE
Similar to #7499, we particularly want the http fixes:
https://golang.org/doc/devel/release.html#go1.11.minor
=> [release-1.13] Update to golang 1.11.13

channels/alpha
Even 1.11 and 1.12 are technically unsupported, but this should get
users off the very oldest unsupported versions of k8s.
Users that want to stay on those versions can pass the
KOPS_RUN_OBSOLETE_VERSION env var.
=> "Force" k8s 1.11.10

pkg/model/openstackmodel/BUILD.bazel, pkg/model/openstackmodel/servergroup.go, pkg/model/openstackmodel/servergroup_test.go, upup/pkg/fi/cloudup/openstacktasks/port.go
This PR fixes the association of nodes to the specified subnets, valuing their IP ranges.
Previously the instances were moved within the zone of the subnets but the ports of the instances were not associated to the right subnet and IP range.
=> Associate subnets to port within OpenStack

pkg/assets/builder.go
Cherry pick of #7555 on release-1.15.
#7555: Log more sensibly when we can't get sha256
=> Automated cherry pick of #7555: Log more sensibly when we can't get sha256

pkg/model/iam/iam_builder.go, upup/pkg/fi/cloud.go
Cherry pick of #7565 on release-1.14.
#7565: Fix 'unable to infer CloudProvider from Zones' for
=> Automated cherry pick of #7565: Fix 'unable to infer CloudProvider from Zones' for

Makefile, docs/apireference/build/node_modules/jquery/README.md, images/mkdocs/Dockerfile, images/mkdocs/entrypoint.sh, images/mkdocs/requirements.txt, mkdocs.yml, requirements-docs.txt
This pr should help fix the mkdocs setup. Thanks to @aledbf for all his hard work getting this going!
I moved requirements to be inside the container it's self and built our own container much like ingress-nginx. I've also fixed the nodejs readme that was breaking the builds.
In future PRs I plan to cleanup some docs and reorganize things prior to us publishing these docs.
=> Fix mkdocs

upup/pkg/fi/cloudup/awstasks/internetgateway_test.go, upup/pkg/fi/cloudup/openstacktasks/subnet.go, upup/pkg/fi/nodeup/command.go
upup/pkg/fi/cloudup/openstacktasks: fix dropped error
upup/pkg/fi/cloudup/awstasks: fix dropped error
upup/pkg/fi/nodeup: fix dropped error
This PR picks off a few dropped errors under `upup`.
=> Fix Dropped Errors in upup

channels/stable, tests/integration/create_cluster/minimal/expected-v1alpha1.yaml, tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
=> Promote 2019-08-16 AMIs from alpha -> stable

hack/update-expected.sh
There are a few env vars which are frequently set in development, but
should not be reflected in the tests.  Clear them before generated the
expected output.
=> hack/update-expected.sh: mask development env vars

cmd/kops/create_cluster.go
add cilium in error message like other networks
=> add cilium in error message

pkg/model/openstackmodel/firewall.go, upup/pkg/fi/cloudup/openstack/cloud.go, upup/pkg/fi/cloudup/openstack/security_group.go, upup/pkg/fi/cloudup/openstacktasks/lb.go, upup/pkg/fi/cloudup/openstacktasks/securitygroup.go
=> Clean security groups if api/ssh ips are removed from config

pkg/model/BUILD.bazel, pkg/model/components/etcdmanager/model.go, pkg/model/domodel/BUILD.bazel, pkg/model/domodel/droplets.go, pkg/model/master_volumes.go, upup/pkg/fi/cloudup/do/cloud.go, upup/pkg/fi/cloudup/dotasks/BUILD.bazel, upup/pkg/fi/cloudup/dotasks/droplet.go, upup/pkg/fi/cloudup/dotasks/volume.go
Digital Ocean doesn't support Multi master yet. This PR introduces tags that helps in associating a specific droplet to a volume. 
I have tested with by making the needed changes in etcd-manager and they are getting linked up properly. I'll be sending a PR for etcd-manager repo separately once this is merged.
I'll also be adding a new PR to add DO support for protokube's gossip cluster to add peers as part of the next step.
=> [DO-7442] Digital Ocean add consistent volume and droplet tags for multi master feature

pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/componentconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
This adds the fields described in the documentation here:
https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md#kubernetes-api-server-configuration
using field descriptions defined [here](https://github.com/kubernetes/kubernetes/blob/1d016cc1d3ee2f95c5ea13e5666bb78d66c7c5e8/cmd/kube-apiserver/app/options/options.go#L239), [here](https://github.com/kubernetes/kubernetes/blob/f4e39afea082afac7bf6f6936c34e012b7cb3c25/pkg/kubeapiserver/options/authentication.go#L280), and [here](https://github.com/kubernetes/kubernetes/blob/f4e39afea082afac7bf6f6936c34e012b7cb3c25/pkg/kubeapiserver/options/authentication.go#L193) 
Note that I did not run `make crds` because it looks like the required library was removed from the vendor directory during our migration to go …
=> Expose API Server flags needed for AWS pod identities

pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/componentconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
Cherry pick of #7610 on release-1.15.
#7610: Expose API Server flags needed for aws pod identities
=> Automated cherry pick of #7610: Expose API Server flags needed for aws pod identities

upup/pkg/fi/http.go
I noticed that the recent container-selinux issue on centos was reporting a hash mismatch rather than a 404.
See the error message here: https://github.com/kubernetes/kops/issues/7608 and the "actual" sha1 reported in the current error message is that of the 404 page:
```
curl http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.68-1.el7.noarch.rpm
curl http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.68-1.el7.noarch.rpm | shasum -a 1
```
This should now report a more descriptive error message if this happens again.
=> Check the HTTP response code when downloading URLs

nodeup/pkg/model/docker.go
Cherry pick of #7609 on release-1.14.
#7609: Updated container-selinux url to pint to the right path
=> Automated cherry pick of #7609: Updated container-selinux url to pint to the right path

upup/pkg/fi/http.go
Cherry pick of #7611 on release-1.13.
#7611: Check the HTTP response code when downloading URLs
=> Automated cherry pick of #7611: Check the HTTP response code when downloading URLs

cmd/kops/validate_cluster.go, docs/cli/kops_validate_cluster.md
With this argument, kops validate will poll until the timeout expires,
waiting for readiness.  On readiness or on timer expiration, it exits
as if wait was not present.
=> Add --wait argument to kops validate

upup/pkg/fi/cloudup/awsup/aws_cloud.go
This PR fixed issue #6796,  that "NeedsUpdate" status of nodes in mixedinstancegroups after rolling update.
=> Fixed "NeedsUpdate" status of nodes in mixedinstancegroups after rolling update

upup/pkg/fi/cloudup/awsup/aws_cloud.go
Cherry pick of #7445 on release-1.15.
#7445: Fix that the node of the instance group of the mixed
=> Automated cherry pick of #7445: Fix that the node of the instance group of the mixed

pkg/model/openstackmodel/servergroup.go
In some cases there is possibility that instance name contains `_` chars which are not valid for k8s:
```
"kube-scheduler-master-foo_ovs_az1-3-1-own-k8s-local": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.',
```
=> fix instance name

pkg/model/openstackmodel/servergroup.go, pkg/model/openstackmodel/servergroup_test.go
This values the setting of associating public IPs from InstanceGroupSpec. The default is still backwards compatible, as it still creates floating IPs if the field is not set.
=> Openstack: value if spec does not associate public ips

pkg/model/iam/iam_builder.go, pkg/model/iam/tests/iam_builder_master_strict.json, pkg/model/iam/tests/iam_builder_master_strict_ecr.json
Should fix https://github.com/kubernetes/kops/issues/7562
=> Updating master IAM policies.

upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template, upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/pre-k8s-1.6.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Do not use ports less than that given as source for outbound DNS queries. Dnsmasq picks random ports as source for outbound queries: when this option is given, the ports used will always to larger than that specified. Useful for systems behind firewalls.
More information: Kubernetes kube-dns uses dnsmasq version 2.78 (http://www.thekelleys.org.uk/dnsmasq/dnsmasq-2.78.tar.xz), which doesn't set the default min_port to 1024 (probably a bug). Later versions of dnsmasq have fixed this issue and don't need explicit min-port command-line argument.
=> Add arg min-port=1024 to dnsmasq container in kube-dns

pkg/model/openstackmodel/BUILD.bazel, pkg/model/openstackmodel/servergroup.go, pkg/model/openstackmodel/servergroup_test.go, upup/pkg/fi/cloudup/openstacktasks/port.go
This cherry-picks #7578 , a bugfix for the OpenStack cloud provider.
It uses the specified subnets to roll out the instances. Previously it wasn't using them which could lead to cluster instances not coming up correctly.
=> Cherry pick #7578 into release 1.14

pkg/model/openstackmodel/firewall.go, pkg/model/openstackmodel/servergroup.go, pkg/model/openstackmodel/servergroup_test.go, upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel, upup/pkg/fi/cloudup/openstacktasks/instance.go, upup/pkg/fi/cloudup/openstacktasks/port.go, upup/pkg/fi/cloudup/openstacktasks/port_test.go
This cherry picks #7581 into release 1.15. It propagates additional security groups from Instance groups to the associated OpenStack ports and instances.
=> Cherrypick #7581 into release 1.15

nodeup/pkg/model/docker.go
This isn't as nice as debian's vault, in that it doesn't contain the
latest packages.  But it appears that once a package is in the vault,
it should stay there.
Source from the vault to unbreak 1.13.
=> Pull centos.org packages from the vault

pkg/apis/kops/instancegroup.go, pkg/apis/kops/v1alpha1/instancegroup.go, pkg/apis/kops/v1alpha2/instancegroup.go
Cherry pick of #7660 on release-1.14.
#7660: Align AWS and kops validation for spot allocation strategy
=> Automated cherry pick of #7660: Align AWS and kops validation for spot allocation strategy

nodeup/pkg/model/context.go, pkg/apis/kops/validation/gce.go, protokube/cmd/protokube/main.go
I noticed these issues when running staticcheck:
```
nodeup/pkg/model/context.go:563:10: this value of err is never used (SA4006)
pkg/apis/kops/validation/gce.go:46:3: this value of allErrs is never used (SA4006)
protokube/cmd/protokube/main.go:216:12: this condition occurs multiple times in this if/else if chain (SA4014)
```
If we think its beneficial I'll see about integrating staticcheck into our CI process [similar to how k/k did](https://groups.google.com/forum/#!searchin/kubernetes-dev/staticcheck%7Csort:date/kubernetes-dev/XKBtVRE_d_Q/76cNLhMCBAAJ).
=> Fix some bugs reported by staticcheck

k8s/crds/kops_v1alpha2_cluster.yaml, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha2/componentconfig.go
I noticed that the documentation on KubeProxyConfig.MetricsBindAddress is no longer correct.
Since release 1.11 of kube-proxy the `--metrics-bind-address` needs to be an IP address. See [kube-proxy commit](https://github.com/kubernetes/kubernetes/pull/72682).
To overwrite the port an additional parameter would be needed.
=> Misleading description for KubeProxy MetricsBindAddress

pkg/model/components/apiserver.go, pkg/model/components/context.go, pkg/model/components/image_test.go, pkg/model/components/kubecontrollermanager.go, pkg/model/components/kubeproxy.go, pkg/model/components/kubescheduler.go
Image names from 1.16 on include an architecture suffix,
e.g. "-amd64"; the generic alias continues to work when pulling, but
when loading from a tarball (i.e. running in CI) we must use the
per-architecture name.
=> Fix for tarball image names after 1.16

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Fixes a couple of smaller issues left unresolved in #7474
Upgrades from Kops 1.13 stable to this PR works as expected.
Note that because bpffs is not mounted on the host before #7474, upgrading cilium will freeze the network on nodes where a cilium pod is being rolled.
Fixes #7575 
Fixes #7046 
Fixes #6496
=> Cilium standalone continuation

upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Per docs/development/instancesizes.md we don't have much cpu on a 1
core machine.  Note that this is only requests, not limits, so calico
can still burst.
At least related to issue #7592
=> Limit calico cpu request to 100m

pkg/model/openstackmodel/servergroup.go, pkg/model/openstackmodel/servergroup_test.go
Uses `kops.InstanceGroupSpec.Zones` as availability zone for instances. 
This change is backwards compatible as it uses the old mechanism if there are no zones defined in spec.
=> OpenStack: use InstanceGroup zones to populate availability zone

upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #7688 on release-1.15.
#7688: Limit calico cpu request to 100m
=> Automated cherry pick of #7688: Limit calico cpu request to 100m

channels/alpha
alpha channel: image for 1.15 and general update
Note that source of images is now:
https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder
=> alpha channel: image for 1.15 and general update

upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
We want to pick up https://github.com/projectcalico/pod2daemon/pull/28 , to
address https://github.com/kubernetes/kops/issues/7592 .
This is not ideal, but looking at the commit changes the only potentially
problematic change in the diff is
https://github.com/projectcalico/pod2daemon/pull/21 , which seems like it
shouldn't cause ay skew issues.
=> Calico: upgrade pod2daemon (only)

Makefile, tools/sha1, tools/sha256
We can continue to support platforms that have either shasum or
sha1sum / sha256sum.  but we can move that logic to a helper so that
our makefile is simpler, and also so that we can use the same helper
in bazel in future.
=> Create tools/sha1 and sha256 helpers, simply Makefile

Makefile, upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
So (counterintuitively) we set it to 1.15.0-alpha.1, because that is the version on the master branch.
=> kops-controller version should match version of kops

Makefile, cmd/kops-controller/BUILD.bazel, upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/apply_cluster.go, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
We then `docker load` it when using a KOPS_BASE_URL.
This should simplify the development process (particularly once we also do
this for dns-controller; at that point we won't need a registry at all).
This should also fix the problems in CI, where the kops-controller image
isn't available.  We've been getting away with testing with the previous
version for dns-controller, which changes pretty slowly.  But that's not a
good idea for kops-controller, which is likely to be more critical and
evolve more rapidly.
(Builds on #7700)
=> Publish kops-controller container dump to S3/GCS

dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go, hack/.staticcheck_failures, hack/machine_types/machine_types.go, node-authorizer/pkg/authorizers/aws/authorizer.go, node-authorizer/pkg/authorizers/aws/authorizer_test.go, node-authorizer/pkg/authorizers/aws/verifier.go, pkg/assets/builder_test.go, pkg/model/components/etcd.go, protokube/pkg/protokube/openstack_volume.go, upup/pkg/fi/dryrun_target.go, upup/pkg/fi/fitasks/keypair.go, util/pkg/ui/user.go
* `dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go:66:21: session.New is deprecated: Use NewSession functions to create sessions instead. NewSession has the same functionality as New except an error can be returned when the func is called instead of waiting to receive an error until a request is made.  (SA1019)`
(same with other instances of `session.New()`)
* `node-authorizer/pkg/authorizers/aws/authorizer_test.go:31:3: this value of config is never used (SA4006)`
* `pkg/assets/builder_test.go:147:2: this value of err is never used (SA4006)
pkg/assets/builder_test.go:147:19: New is a pure function but its return value is ignored (SA4017)`
* `pkg/model/components/etcd.go:139:26: printf-style function with dynamic format string and no further arguments should use print-style …
=> More staticcheck bugfixes and cleanup

docs/cluster_spec.md, nodeup/pkg/model/protokube.go, pkg/apis/kops/cluster.go, pkg/apis/kops/v1alpha1/cluster.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/cluster.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go, pkg/model/components/etcdmanager/model.go, upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template, upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.11.yaml.template
In some cases (in OpenStack) we have situations that OpenStack API certificates are coming from vendors (and in some cases vendors do use self-signed certificates). This lead to situation that we do have self-signed certificates in OpenStack API. However, we can get self-signed certificates working with mounting ca-certificates.crt (assuming that self-signed rootCA is added to instance root ca bundle) from the instance itself inside the official kops containers.
Adding certificates to root ca bundle can be done for instance in following way (in debian/ubuntu):
```
additionalUserData:
- name: cacert.sh
type: text/x-shellscript
content: |
#!/bin/sh
cat > /usr/local/share/ca-certificates/openstack.crt <<EOF
-----BEGIN CERTIFICATE-----
snip
-----END CERTIFICATE-----
EOF
update-ca-certificates …
```
=> Allow to use custom rootCAs

pkg/model/components/etcdmanager/model.go, pkg/model/components/etcdmanager/tests/minimal/tasks.yaml, pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
etcd-manager changes:
* Use disk by id for mounting devices in OpenStack [@zetaab](https://github.com/zetaab) [#253](https://github.com/kopeio/etcd-manager/pull/253)
=> Update etcd-manager with OpenStack fixes

upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
Cherry pick of #7714 on release-1.15.
#7714: Update DigitalOcean CCM to v0.1.20
=> Automated cherry pick of #7714: Update DigitalOcean CCM to v0.1.20

upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #7694 on release-1.15.
#7694: Add calico 3.9.1
=> Automated cherry pick of #7694: Add calico 3.9.1

nodeup/pkg/model/context.go, pkg/apis/kops/validation/gce.go, protokube/cmd/protokube/main.go
Cherry pick of #7663 on release-1.15.
#7663: Fix some staticcheck warnings
=> Automated cherry pick of #7663: Fix some staticcheck warnings

upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template, upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/pre-k8s-1.6.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #7020 on release-1.15.
#7020: Add arg min-port=1024 to dnsmasq container in kube-dns
=> Automated cherry pick of #7020: Add arg min-port=1024 to dnsmasq container in kube-dns

Makefile, tools/hashes.bzl
So I figured out how to generate the outputs in the correct way so
that we don't need an artificial name; we must construct the outputs
field in the rule using a helper function.
=> bazel: fix hashes rule to generate outputs

channels/alpha
Suggesting this due to:
https://github.com/kubernetes/kubernetes/issues/82923
Will place hold to wait for confirmation rolling back doesn't break anything.
/hold
=> Rollback alpha channels 1.14.7

WORKSPACE
( rules_go recently started [prefixing their tags with v](https://github.com/bazelbuild/rules_go/tags) )
I was running into [dependency issues](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kops/7727/pull-kops-bazel-test/1179152700873379849) hence the additional load statement, but if theres a simpler way to accomplish that let me know.
=> Upgrade bazel's rules_go and rules_docker

pkg/model/resources/nodeup.go, pkg/model/tests/data/bootstrapscript_0.txt, pkg/model/tests/data/bootstrapscript_1.txt, pkg/model/tests/data/bootstrapscript_2.txt, pkg/model/tests/data/bootstrapscript_3.txt, pkg/model/tests/data/bootstrapscript_4.txt, pkg/model/tests/data/bootstrapscript_5.txt, tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml, tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml, tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml, tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml, tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
We pass the appropriate flag to curl / wget, but where it fails we fall
back to not using compression.
Also simplify the code paths here, as it has proven so tricky - we simply
try a sequence of commands until we successful download and a hash match.
=> nodeup download: try to use compression

WORKSPACE, images/BUILD.bazel, tools/bazel.rc
* Run WORKSPACE and tools/BUILD.bazel through buildifier
* Translate tag into commit for rules_docker (better caching/performance)
* Update repo-infra to latest
* Add rbe_autoconfig repo
* Add rbe config to bazelrc
- enable with `--config=remote --remote_instance_name=projects/PROJ/instances/default_instance`, see https://github.com/kubernetes/test-infra/blob/master/rbe/configure.sh
/assign @justinsb 
Next things to do:
* Configure this repo's prow jobs to start using --config=ci (currently does nothing)
* Configure CI jobs to start using RBE
* Start using more interesting stuff from repo-infra
=> Add optional RBE support for kops

Makefile
Intend to change CI jobs from `make bazel-build` to `make bazel-build BAZEL_CONFIG=--config=ci`
https://github.com/kubernetes/test-infra/blob/4db0b31df68e72c01edfe6eeb450d6cccd4f1615/config/jobs/kubernetes/kops/kops-config.yaml#L22-L23
Note that `bazel test --config=ci` is required (`bazel --config=ci test # unrecognized flag`)
=> Add a BAZEL_CONFIG Makefile arg to bazel commands

WORKSPACE
Gives an error:
error running 'git reset --hard f905a6636c5106c36cc979bdcc19f0fe4fc01ede' while working with @distroless:
fatal: Could not parse object 'f905a6636c5106c36cc979bdcc19f0fe4fc01ede'.
=> bazel: comment out shallow_since as fails to build with bazel 1.0

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha2/networking.go, upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This was released recently: https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.5.4
Also properly set the addon versions for older versions of kubernetes.
Older versions of Kubernetes are still using 1.3.3: https://github.com/kubernetes/kops/blob/8568c6461e94809f563c52e5a16d144fec415f54/upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template#L70
Technically anyone running an older version of kops will have their addon version downgraded even though the manifest itself didnt change. I'm not sure what impact that may have if any.
=> Upgrade Amazon VPC CNI plugin to 1.5.4

nodeup/pkg/model/kubelet.go
Nodeup takes into account the first instance type from the Instance Group spec when the `max-pods` is calculated. This leads to a miscalculated value when using multiple instance types.
This PR fixes the issue by querying the EC2 instance metadata service to find out the actual instance type and maintains backward compatibility by falling back to the Instance Group spec.
=> Kubelet configuration: Maximum pods flag is miscalculated when using Amazon VPC CNI

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/componentconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go, pkg/flagbuilder/buildflags_test.go
/kind api-change
Add support for kops to declare `event-ttl` flag from `kube-apiserver`  
Fixes #7484 
Should I remove `pkg/apis/kops/types.generated.go` from this PR?
This file made this PR longer than it should be :disappointed: 
I ran this commented command [here](https://github.com/kubernetes/kops/blob/a9574284465216a26929d8ef5e5fa5ee8e69e92f/Makefile#L666)
**Does this PR introduce a user-facing change?**:
```release-note
Add "event-ttl" flag from kube-apiserver
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
kind: Cluster
spec:
kubeAPIServer:
eventTTL: 03h0m0s
```
=> Add event ttl flag

Makefile, dns-controller/cmd/dns-controller/BUILD.bazel, upup/pkg/fi/cloudup/apply_cluster.go
Like we recently did with kops-controller, this means we aren't
reliant on pushing a docker container for development.  This should
also fix the e2e tests, which otherwise break whenever we make an
incompatible change to dns-controller.
=> Upload dns-controller archive, use in KOPS_BASE_URL

k8s/crds/kops_v1alpha2_cluster.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha2/networking.go, upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #7398 on release-1.15.
#7398: Upgrade Amazon VPC CNI plugin to 1.5.4
=> Automated cherry pick of #7398: Upgrade Amazon VPC CNI plugin to 1.5.4

nodeup/pkg/model/kube_apiserver_test.go, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha2/componentconfig.go
Currently, an error occurs when multiple [service-account-key-file](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/) are specified for kube-apiserver.
This PR will fix it.
fixed #7645 
=> fix(apiserver): allow multiple service-account-key-file

nodeup/pkg/model/kube_apiserver_test.go, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha2/componentconfig.go
Cherry pick of #7781 on release-1.15.
#7781: fix(apiserver): allow multiple service-account-key-file
=> Automated cherry pick of #7781: fix(apiserver): allow multiple service-account-key-file

cmd/kops-controller/main.go, upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
We want it to be a daemonset so that we can start to offer a GRPC
service, for kubelet bootstrapping.
We also scale-down the old Deployment to have 0 replicas, to be sure to
stop it.
We can remove it later when we have proper pruning here.
=> Move kops-controller to daemonset

dns-controller/cmd/dns-controller/BUILD.bazel, dns-controller/cmd/dns-controller/main.go, docs/development/ports.md, hack/.packages, pkg/model/components/etcdmanager/BUILD.bazel, pkg/model/components/etcdmanager/model.go, pkg/model/openstackmodel/BUILD.bazel, pkg/model/openstackmodel/firewall.go, pkg/wellknownports/BUILD.bazel, pkg/wellknownports/wellknownports.go, protokube/cmd/protokube/BUILD.bazel, protokube/cmd/protokube/main.go, upup/pkg/fi/cloudup/BUILD.bazel, upup/pkg/fi/cloudup/template_functions.go
We had a port collision on 3997; change the default memberlist ports
to avoid the collision (we haven't shipped a release with this in it).
Also create a go file so that we can use constants to keep track of
our port numbers, rather than magic values.
=> Change default port for memberlist from 3997

images/BUILD.bazel
Attribute is now automatically inferred.
=> bazel: remove deprecated stamp attribute from container building

upup/pkg/fi/cloudup/openstacktasks/port.go, upup/pkg/fi/cloudup/openstacktasks/port_test.go
When updating from 1.15.0-alpha.1 to 1.15.0-beta.1 we cannot update any of the clusters. I do not want to start searching git blame which is causing this. However, I will just fix it. This needs to be backported to release-1.15
When I run kops update cluster <foo> in existing cluster (created before 1.15.0-beta.1)
The error log is
```
W1017 09:57:08.188375   32485 executor.go:130] error running task "Port/port-nodes-4-kaasprod-k8s-local" (9m59s remaining to succeed): Field cannot be changed: Network
W1017 09:57:08.188396   32485 executor.go:130] error running task "Port/port-nodes-2-kaasprod-k8s-local" (9m59s remaining to succeed): Field cannot be changed: Network
W1017 09:57:08.188409   32485 executor.go:130] error running task "Port/port-master-zone-2-1-1-kaasprod-k8s-local" (9m59s …
```
=> Cherry-pick #7807 to release-1.15

Makefile
The variable name ${UPLOAD} is currently used twice in Makefile, and it causes problem when run `make`.
line 35: `UPLOAD=$(BUILD)/upload`
line 50: `UPLOAD=$(MAKEDIR)/hack/upload`
=> Rename upload command variable in Makefile

hack/machine_types/machine_types.go
`TrimRight` is char based, and `TrimSuffix` is word based, I think that's what we want here.
=> fix string trim func in main

Makefile, hack/upload
OSS is the object storage in Alicloud. 
This PR adds the ability to upload artifacts to OSS, this is helpful when someone is developing kops and test kops in Alicloud.
This change is also part of #4127
=> Alicloud: add OSS as upload dest

pkg/model/components/kubelet.go, pkg/model/components/kubeproxy.go, upup/pkg/fi/nodeup/command.go, util/pkg/vfs/context.go
=> Alicloud: add hostname override

docs/cluster_spec.md, k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/cluster.go, pkg/apis/kops/v1alpha1/cluster.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/cluster.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Allow users to override the CoreDNS image version to take advantage of local image registries or differing versions of the image to allow quicker access to new/improved CoreDNS plugins. Useful for us given we make heavy use of internally cached images to avoid external registry dependencies wherever possible.
Resolves #7776 - although not the underlying bug suggested in that issue. As mentioned there I don't think that applies given the work merged in #7376 
I'll follow up with a separate PR for upgrading the default as we're currently soak testing the upgrade to CoreDNS v1.6.2 in one of our clusters.
=> Allow for override of CoreDNS version

pkg/model/components/etcd.go, pkg/model/components/etcdmanager/model.go, pkg/model/components/etcdmanager/tests/minimal/tasks.yaml, pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Primarily for DigitalOcean support
Changes:
* fix issues in pr#253
* Update rules-docker to 0.12
* [DO-7442] Fix logic for Digital Ocean volume tag
* Update release process to use shipbot
* Move to go modules
* Update golang to 1.13.3
* travis: Test newer bazel versions
* Fix unit tests
* Test everything, not just //test
=> Update etcd-manager to 3.0.20191025

docs/cluster_spec.md
/kind documentation
Documents `eventTTL` usage explaining that you must fill empty units of time with zeros.
NONE
This configuration from ClusterSpec is already inside the release 1.15, but lacks documentation on how to use it.
This flag was added here: https://github.com/kubernetes/kops/pull/7487
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
```
=> Document eventTTL

docs/getting_started/openstack.md, upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/template_functions.go
currently people needs to setup openstack cloud-controller-manager images by themselves. This is not that good as it should be. This PR will setup the default image for ccm, but it will still allow to customise the image if needed. This PR will also setup the default loglevel to 2 (which can be changed if needed)
cc @mitch000001
=> Set default image for OpenStack CCM

pkg/model/openstackmodel/firewall.go
this is needed in case of calico for instance.
=> Add protocol rules to master as well

k8s/crds/kops_v1alpha2_cluster.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha2/networking.go, upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #7847 on release-1.15.
#7847: Revert "Upgrade Amazon VPC CNI plugin to 1.5.4"
=> Automated cherry pick of #7847: Revert "Upgrade Amazon VPC CNI plugin to 1.5.4"

upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
Attempting to use kops 1.15.0-beta.1 with AWS VPC CNI plugin (the networking value `amazon-vpc-routed-eni`) causes these errors on the masters:
```
error: error validating "k8s-1.12.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
```
in fact, new clusters do not even come up healthy in my tests: the masters never reach `Ready` status.
This tiny change removes `---` from the AWS VPC CNI addon, which directly addresses the above error. Upon fix, the masters showed `Ready` in the order of minutes.
Fixes #7805
=> Remove extraneous document separator causing failures applying addons

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha2/networking.go, upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This reverts commit 699fe56619bee0e2fe0bb87b2a2261ecd19ef6a6.
In Office Hours we we discussed this as potential blockers for the next 1.15.0 beta release and 1.16.0 alpha. [They cut an RC1](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.5.5-rc1) but it may still be a while before a 1.5.5 stable so I'm just going to revert this for now. We can upgrade to 1.5.5 (or 1.6.X) once it is stable.
=> Revert "Upgrade Amazon VPC CNI plugin to 1.5.4"

upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
fixes #7873 .
Have a look at the folowing discussions:
- https://github.com/weaveworks/weave/issues/3691
- https://github.com/weaveworks/weave/pull/3697
=> mark weavenet-pod as system-critical

upup/pkg/fi/cloudup/openstack/instance.go
sometimes when new cluster is created, the servers does not start fast enough.
=> increase retry count

upup/pkg/fi/cloudup/awsup/status.go
Variable `etcdClusterName` is being reset inside the loop, resulting in the outer `etcdClusterName` never changing from `""`.
=> awsup: fix shadowed var when looking for etcd cluster name

upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #7885 on release-1.15.
#7885: Add back calico metrics options:
=> Automated cherry pick of #7885: Add back calico metrics options:

upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
I totally left this out of a previous PR.  We need this or we'll break users Calico metrics.  Will CP to 1.15.
=> Add back calico metrics options

docs/operations/cluster_upgrades_and_migrations.md
The *Upgrade a `kops` cluster from one Kubernetes version to another* link was referring to itself (`cluster_upgrades_and_migrations.md`) but I believe it's supposed to link to `updates_and_upgrades.md`.
=> Fix kops upgrade cluster link

upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.12.yaml.template
Cherry pick of #7857 on release-1.15.
#7857: Remove extraneous document separator causing failures
=> Automated cherry pick of #7857: Remove extraneous document separator causing failures

cloudmock/aws/mockautoscaling/group.go
Two of the tests in `kops/pkg/instancegroups/rollingupdate_test.go` are invalid, as can be demonstrated by removing the call to `c.RollingUpdate` in `TestRollingUpdateAllNeedUpdate`—the test will still pass because `asgGroups.AutoScalingGroups` is always empty and all the  assertions are dead code.
This patch fixes the behavior of the mock DescribeAutoScalingGroups when its input omits the `AutoScalingGroupNames` field.
=> Fix behavior of mock DescribeAutoScalingGroups when no names supplied

README.md
#7593 moved the docs for DigitalOcean & OpenStack without updating links.  This PR corrects the links.
=> Update "Guide" links for DigitalOcean & OpenStack

ci/postsubmit/push-to-staging/cloudbuild.yaml
This is the GCB script that will be called to automatically push images to our staging repo from a prow postsubmit job.  That job is https://github.com/kubernetes/test-infra/pull/14503
=> Add ci postsubmit script for pushing images to staging

hack/.packages, nodeup/pkg/model/protokube.go, pkg/model/components/etcdmanager/model.go, pkg/model/domodel/droplets.go, pkg/resources/digitalocean/resources.go, protokube/cmd/protokube/main.go, protokube/pkg/gossip/do/BUILD.bazel, protokube/pkg/gossip/do/seeds.go, protokube/pkg/protokube/BUILD.bazel, protokube/pkg/protokube/do_volume.go, upup/pkg/fi/cloudup/do/cloud.go
As part of this PR, it supports multiple HA masters for DO by adding gossip seed support. The necessary changes are already done on the etcd-manager side - https://github.com/kopeio/etcd-manager/pull/254.
I have tested this locally with 3 master nodes, and was able to see the seeding happening Ok. 
This PR doesn't address adding a load balancer for the HA masters. That will be coming up next.
=> [DO-7442] Add gossip cluster implementation for Digital Ocean cloud provider

OWNERS
I don't work on the DigitalOcean provider for kops anymore so I shouldn't be an approver. 
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>
=> remove myself from OWNERS

Makefile
* Removed `LDFLAGS` workarounds for older (unsupported) versions of go
* Updated `check-builds-in-go*` targets for more recent versions of go. Since the `ci` target requires bazel, rather than trying to install that in a docker container I opted to just use the `all` target which should provide sufficient coverage. Note that the 1.11 target isnt currently working (`build k8s.io/cloud-provider: cannot find module for path k8s.io/cloud-provider`) I'll need to troubleshoot that more unless we decide to just drop go 1.11 support entirely.
* `make protokube` now respects `EXTRA_BUILDFLAGS`
* Removed unused `dep-ensure` code and updated the prereqs task so that `gomod` now checks for the presence of bazel.
=> Cleanup make targets

channels/stable
Promote kubernetes versions from alpha to stable:
* 1.16.2
* 1.15.5
* 1.14.8
* 1.13.12
=> stable channel: promote kubernetes 1.13.12, 1.14.8 etc

cmd/kops/rollingupdatecluster.go, cmd/kops/validate_cluster.go, pkg/instancegroups/BUILD.bazel, pkg/instancegroups/instancegroups.go, pkg/instancegroups/rollingupdate.go, pkg/instancegroups/rollingupdate_test.go, pkg/validation/validate_cluster.go
A rolling update will drain and terminate the first node in a nodes instancegroup even when the cluster is in a state where it fails validation.
Fixes #7258
=> Don't update first node in instancegroup if cluster fails validation

upup/models/cloudup/resources/addons/networking.flannel/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Without `priorityClassName` there is a possibility that flannel pod won't be scheduled to a node, or even worse, be preempted
=> add missing priorityClassName to flannel DaemonSet

upup/pkg/fi/cloudup/awstasks/launchconfiguration.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go, upup/pkg/fi/cloudup/awstasks/subnet.go, upup/pkg/fi/context.go, upup/pkg/fi/nodeup/nodetasks/file.go, upup/pkg/fi/nodeup/nodetasks/file_test.go, upup/pkg/fi/utils/yaml.go
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>
=> Correct spelling mistakes

upup/models/cloudup/resources/addons/networking.flannel/k8s-1.12.yaml.template
This issue occurs when using flannel network provider with the latest master.
This issue is mentioned here - https://github.com/coreos/flannel/issues/1178 and it's fix was done few days back as mentioned here - https://github.com/coreos/flannel/pull/1174/files
_After creating a v1.16 cluster by kubeadm init and installing flannel cni by kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/32a765fd19ba45b387fdc5e3812c41fff47cfd55/Documentation/kube-flannel.yml, the network still does not get ready and coredns remain pending._
The same issue was observed with latest KOPS master and this PR should fix the issue.
I tested this change on the latest master and it seems to be working fine.
=> Fix flannel CNI version to use 0.2.0

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
=> Create PodDisruptionBudget for kube-dns in kube-system namespace

nodeup/pkg/model/docker.go, nodeup/pkg/model/docker_test.go, pkg/model/components/docker.go
/kind feature
Updates supported Docker versions to latest stable. Previous versions for Docker CE are EOL.
Fixes #7463
Fixes #7853
**Special notes for your reviewer:**
At the moment the default Docker version in Kops is 18.06.3, quite old and EOL. Docker version 18.09 has been officially validated since k8s 1.14, but it's EOL also at the moment also.
Docker 19.03 has been stable for some time and has been validated for k8s 1.14+ since June, just not documented. https://github.com/kubernetes/kubernetes/issues/82326#issuecomment-546464495
Test infrastructure has been moved to Docker 19.03 also. https://github.com/kubernetes/test-infra/pull/14784
Website should be getting updated …
=> Add support for newer Docker versions

mkdocs.yml
Without the `site_url` attribute, the `sitemap.xml` file is empty.
Also `permalink: true` concatenates the `¶` character.
=> Fix generation of documentation /sitemap.xml file

cmd/kops/rollingupdatecluster.go, pkg/instancegroups/rollingupdate.go, pkg/instancegroups/rollingupdate_test.go
It turns out we werent running verify-goimports in our CI jobs.
While we work to get that enabled in #7952, we can at least unblock the releases by doing a one-time fix of the failing goimports
=> Fix goimports errors

docs/networking.md, pkg/model/iam/iam_builder.go, upup/pkg/fi/cloudup/apply_cluster.go
This PR:
- Update the Lyft CNI to v0.5.1
- Add a new IAM policy because `ec2:DescribeVpcs is required for m5 and c5 instances because the AWS metadata server does not return the secondary CIDR block on these instance types.`
- Add the Lyft CNI to the documentation
~Marked as WIP because I still need to test this build by spinning up a new cluster, but I'm happy to get any feedback if you something that doesn't look right.~
Tested by creating a new cluster and upgrading an existing one.
=> Upate Lyft CNI to v0.5.1

docs/advanced/experimental.md
I went through the list of feature flags that still default to false and added any missing ones to this list.
See https://github.com/kubernetes/kops/issues/6081#issuecomment-556024019 for the motivation to do this
=> Update feature flag documentation

upup/pkg/fi/cloudup/apply_cluster.go
This PR fixes panic when ssh key does not exist on digitalocean provider
fixes #7940
=> Fix panic when ssh key not exists on digitalocean

.travis.yml, Makefile, WORKSPACE, docker/Dockerfile, go.mod, images/dns-controller-builder/Dockerfile, images/protokube-builder/Dockerfile
Now that the master branch is targeting Kops 1.17 and Kubernetes 1.17, we can upgrade all Go version references to use 1.13, matching [Kubernetes itself](https://github.com/kubernetes/kubernetes/pull/82809).
I used #7811 as a reference
I debated having Travis continue to test Go 1.11 or whether we should drop it. Thoughts?
=> Upgrade go to 1.13

upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7-v3.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Updates the Calico v3 manifests to use more correct values for the [`CALICO_IPV4POOL_IPIP` environment variable](https://docs.projectcalico.org/v3.9/reference/node/configuration#environment-variables), which appear to have changed [since v3.0.0](https://docs.projectcalico.org/v3.0/reference/node/configuration#environment-variables). 
Previous values are still backwards-compatible currently.
=> Use correct values for CALICO_IPV4POOL_IPIP in Calico v3

channels/alpha, channels/stable
As it is bound to pre-release versions of kops, it can do directly
into the alpha and stable channels.
=> Put kubernetes 1.17.0-beta.2 into channels

upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/README.md
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>
=> Correct link error:404

docs/authentication.md
```
> kops version
Version 1.15.0-beta.1 (git-1a662bf87)
```
Not sure if this is only happens on kops 1.15 beta.
When enabling `aws-iam-authenticator` after cluster creation I get `error validating cluster` when rolling-update:
```
I1114 15:45:15.171972   40767 instancegroups.go:275] Cluster did not pass validation, will try again in "30s" until duration "15m0s" expires: kube-system pod "aws-iam-authenticator-fw64l" is not ready (aws-iam-authenticator), kube-system pod "aws-iam-authenticator-qq84m" is not ready (aws-iam-authenticator).
E1114 15:45:44.436473   40767 instancegroups.go:212] Cluster did not validate within 15m0s
master not healthy after update, stopping rolling-update: "error validating cluster after removing a node: cluster did not validate within a duration of \"15m0s\"" …
```
=> [aws-iam-authenticator] Docs - Steps to disable DaemonSet Temporarily

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template, upup/pkg/fi/cloudup/BUILD.bazel, upup/pkg/fi/cloudup/template_functions.go
This PR adds a new `indent` template function and use it to fix KubeDNS.ExternalCoreFile rendering as reported on #7975.
`indent` function was copied from [sprig](https://github.com/Masterminds/sprig/blob/v2.17.1/strings.go#L104-L107).
Fixes #7975
=> Add indent template function and use it to fix KubeDNS.ExternalCoreFile rendering

cmd/kops-controller/BUILD.bazel, cmd/kops-controller/main.go, hack/.packages, pkg/model/domodel/droplets.go, pkg/nodeidentity/do/BUILD.bazel, pkg/nodeidentity/do/identify.go, upup/pkg/fi/cloudup/do/cloud.go
This PR addresses the issue mentioned in https://github.com/kubernetes/kops/issues/7870
for digital ocean cloud provider.
Added a kops-controller that updates the node labels. Tested it and it seems to be working as expected.
Please see the attached image.
=> [Issue-7870] kops controller support for digital ocean

go.mod, go.sum, hack/update-goimports, hack/verify-goimports
This avoids relying on the version that happens to be installed.
=> Run goimports from locked version in go.mod

upup/pkg/fi/cloudup/openstacktasks/port.go, upup/pkg/fi/cloudup/openstacktasks/port_test.go
Previously we mistakenly used the names of the additional security
groups where the Openstack API is expecting their IDs.
=> fix(openstack): fix additional security groups on instance groups

docs/cluster_spec.md, k8s/crds/kops.k8s.io_clusters.yaml, nodeup/pkg/model/BUILD.bazel, nodeup/pkg/model/kube_apiserver.go, nodeup/pkg/model/kube_apiserver_test.go, nodeup/pkg/model/tests/apiServer/auditDynamicConfiguration/cluster.yaml, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/componentconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
Signed-off-by: mmerrill3 <michael.merrill@vonage.com>
This addresses issue #7392 to allow for dynamic audit configuration, so tools like falco can easily be integrated with kops to ingest audit logs through audit sinks.
=> Implementing audit dynamic configuration (#7392)

upup/pkg/fi/cloudup/openstacktasks/port.go, upup/pkg/fi/cloudup/openstacktasks/port_test.go
Previously we mistakenly used the names of the additional security
groups where the API is expecting their ID.
Cherry pick of #8004
=> Automated cherry pick of #8004 origin release 1.15: fix(openstack): fix additional security groups on instance groups

Makefile
/kind bug
When running `make ci`, assures that autogenerated files are properly indented when developing locally. It also fixes the scenario where `upup/models/bindata.go` is generated locally, not indented, and breaks the `verify-goimports` test.
NONE
The discussion started here: https://github.com/kubernetes/kops/pull/7865#issuecomment-558312020
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
```
=> Run goimports in make ci

upup/pkg/fi/cloudup/alitasks/BUILD.bazel, upup/pkg/fi/cloudup/alitasks/securitygrouprule.go, upup/pkg/fi/cloudup/alitasks/sshkey.go
=> Alicloud: fix comparison failures for SecurityGroupRule and SSHKey

upup/pkg/fi/cloudup/alitasks/disk.go
It fixes comparison failures for Disk.
=> Alicloud: add Encrypted field in Disk Find func

OWNERS
In discussion with @mikesplain, adding myself as a reviewer to the project to assist moving forward!
=> Add joshbranham to OWNERs as reviewer

pkg/apis/kops/instancegroup.go, pkg/apis/kops/v1alpha1/instancegroup.go, pkg/apis/kops/v1alpha2/instancegroup.go, upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go, upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go
Adds the new CapacityOptimized spot allocation strategy to the list of supported spot allocation strategies. More info about the new allocation strategy found here: https://aws.amazon.com/blogs/compute/introducing-the-capacity-optimized-allocation-strategy-for-amazon-ec2-spot-instances/
Marking as WIP until the merging of #7404 and https://github.com/terraform-providers/terraform-provider-aws/issues/9750 as I've not had the chance to test it yet and Terraform will need to support it first.
**EDIT:** Discussed at Office Hours on the 8th of November and decided Terraform support is no longer a blocker for this.
Intended to resolve #7401
=> Add CapacityOptimized to list of supported spot allocation strategies

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/componentconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
This commit adds only api changes to allow users to configure the following flags in kube-controller-manager:
- `-concurrent-deployment-syncs`
- `--concurrent-endpoint-sync`
- `--concurrent-namespace-syncs`
- `--concurrent-replicaset-syncs`
- `--concurrent-resource-quota-syncs`
- `--concurrent-service-syncs`
- `--concurrent-serviceaccount-token-syncs`
- `--concurrent_rc_syncs`
We have been using to spin up integration testing environments and we needed the controller to be able to do more syncs concurrently to be able to spin these environments faster.
=> Allow users to set kube controller manager's concurrent sync flags.

util/pkg/vfs/BUILD.bazel, util/pkg/vfs/osscontext.go
This is the first step to gradually move from environment variables ACCESS KEY and SECRET to instance RAM role (known as IAM role in EC2).
This is also related with kopeio/etcd-manager#269. After this PR gets merged, I will try make another separate PR to update the kops dependency to latest in etcd-manager. 
Then kopeio/etcd-manager#269 can be merged.
=> Alicloud: allow use RAM role for OSS client

upup/pkg/fi/cloudup/awsup/aws_cloud.go
Correctly detect the version of the LaunchTemplate that should be used, handling Default, Latest, and a specified version.. 
Currently if you are using TF output and using mixed instances policies for your IGs, without this patch in 1.14+ the rolling update always thinks nodes need to be rolled. 
TF issue caused by this PR which was to fix handling of ASG set to use default version of the Launch Template.https://github.com/kubernetes/kops/pull/7445
TF is settings specific version, and not changing the default, so the logic in 7445 broke rolling updates for TF generated ASGs.
Recommend CP to 1.14, 1.15, 1.16 with new releases.
=> Fix Handling of LaunchTemplate Versions for MixedInstancePolicy

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/componentconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
This PR adds support for the remaining `leader-elect` flags that can be utilized by both the `kube-controller-manager` and the `kube-scheduler`.
=> Additional leader election options

nodeup/pkg/model/kube_apiserver.go
=> Fix truncation of admission control plugins list

Makefile
Some of these were not as dependent on Bazel as first thought.
=> Add more verifications to Travis

cmd/kops/create_cluster.go
Found an issue where regions ending with characters other than "1" like sfo2 had problems with etcdmanager.
The index was set to 2 instead of 1 because of the way we are currently trimming in https://github.com/kubernetes/kops/blob/master/cmd/kops/create_cluster.go#L802
Since this is a common code, I added special check for DO to use the logic differently that suits DO.
You now see the instanceGroup as below and the name is properly set to "1" instead of "2".
`  configBase: do://sri-kops-space/dev5.techthreads.co.in
etcdClusters:
- cpuRequest: 200m
etcdMembers:
- instanceGroup: **master-sfo2-1**
name: "1"
memoryRequest: 100Mi
name: main
- cpuRequest: 100m
etcdMembers:
- instanceGroup: **master-sfo2-1**
name: "1"
memoryRequest: 100Mi
name: events
`
=> [Issue-7956] - [Digital Ocean] Minor fix to have proper indexing for digital ocean regions

cmd/kops/rollingupdatecluster.go, k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/instancegroups/rollingupdate.go, upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
From Canal v3.8 onwards, a new init container is introduced and included in the manifests by default, which installs a Flex Volume Driver. This requires having a writeable path to install the driver in, which by default is `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/`.
The default flexvol directory above is not writeable for OSs such as CoreOS & ContainerOS, so the volume plugin directory must be specified in the Cluster Spec like below:
```yml
spec:
kubelet:
volumePluginDirectory: /var/lib/kubelet/volumeplugins/
```
Typha support is now available for Canal deployments. This can be configured as follows:
```yml
spec:
canal:
typhaReplicas: 3
```
Other available options are: `typhaPrometheusMetricsEnabled`, `typhaPrometheusMetricsPort`
=> Canal v3.10 manifest for k8s v1.15+

Makefile
/kind bug
If the current commit contains a file with an import formatting error, such that make verify-goimports would fail, then a make ci will give the wrong error message, giving the user the wrong instructions for fixing the problem.
The added goimports will "fix up" the problem, causing the later verify-goimports to incorrectly pass. Then, verify-gomod will notice the dirty workspace and incorrectly tell the user to run `go mod tidy`.
This bug was introduced by #8023 
The commit introducing the bug was reviewed and approved by @geojaz, so
/assign @geojaz
=> Fix misleading message in "make ci" when imports formatted incorrectly

cmd/kops/integration_test.go, tests/integration/update_cluster/privatecalico/cloudformation.json, tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
I noticed that #8051 didnt require updating an tests in order to pass which means that cloudformation output of NAT gateways weren't covered by our integration tests.
This adds that to the complex test case. this should cause #8051 to fail until it updates the expected CF as well :)
=> Update integration test to cover CloudFormation output of NAT gateways

tests/integration/update_cluster/privatecalico/cloudformation.json, upup/pkg/fi/cloudup/awstasks/natgateway.go
CloudFormation template that is generated by Kops has the tags in the AWS::EC2::NatGateway incorrectly formatted and fails to install, as described in #7452 .
I cannot confirm that the Tags section is unsupported anymore for AWS::EC2::EIP. For me works without any problem.
Fixes #7452
=> Fix CloudFormation template tags for NatGateway

pkg/apis/kops/networking.go, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Most importantly, this fixes a bug in the 1.6.4 branch causing `externalTrafficPolicy: local` to fail.
=> Bump cilium version to 1.6.4

cmd/kops/update_cluster.go, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Calico has been broken in CoreOS since 1.15, as discussed in #7592, #7931 and in #kops-users.
There is a simple workaround, but still annoying for inexperienced users:
https://docs.projectcalico.org/v3.9/reference/faq#are-the-calico-manifests-compatible-with-coreos
To fix this I am passing the kubelet volume for external plugins as parameter to the template, same way it's done for Canal:
https://github.com/kubernetes/kops/blob/ebbebc5af34168d00834d32416323bb1a743f67b/upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template#L701
To make things easier I also added a naive approach of detecting the distro based on image location like `595879546273/CoreOS-stable-2303.3.0-hvm`.  This should make it easier to get started for those that use the image …
=> Fix mounting Calico "flexvol-driver-host" in CoreOS

nodeup/pkg/distros/distribution.go, nodeup/pkg/model/kube_controller_manager.go, nodeup/pkg/model/kubelet.go, nodeup/pkg/model/miscutils.go, nodeup/pkg/model/ntp.go
Signed-off-by: Salvatore Mazzarino <dev@mazzarino.cz>
Another tiny change that fixes the support for Flatcar (still broken, unfortunately) 
As tested in the release **1.15.1-alpha.1**
```txt
core@ip-172-20-65-153 ~ $ sudo journalctl -u coreos-cloudinit-350015389.service
-- Logs begin at Mon 2019-09-09 20:19:38 UTC, end at Mon 2019-09-09 20:26:45 UTC. --
Sep 09 20:19:59 ip-172-20-65-153.ec2.internal systemd[1]: Started Unit generated and executed by coreos-cloudinit on behalf of user.
Sep 09 20:19:59 ip-172-20-65-153.ec2.internal bash[1454]: == nodeup node config starting ==
Sep 09 20:19:59 ip-172-20-65-153.ec2.internal bash[1454]: Downloading nodeup (https://github.com/kubernetes/kops/releases/download/1.15.0-alpha.1/linux-am>
Sep 09 20:19:59 ip-172-20-65-153.ec2.internal bash[1454]:   % …
```
=> Complete support for Flatcar

cmd/kops/rollingupdatecluster.go, pkg/instancegroups/instancegroups.go, pkg/instancegroups/rollingupdate.go, pkg/instancegroups/rollingupdate_test.go
/kind bug
The fix #7872 exposed an issue where rolling update starts updating the first master before the terminated bastion is replaced by the ASG. Before that fix, kops was relying on the fact that the resulting validation failure was ignored.
This fixes the issue by waiting for validation to succeed after terminating a bastion. It does not change the behavior of updating the first bastion without validating the cluster.
The other possible fix would be to make validation ignore any shortfall in members of bastion instance groups.
Fixes #8070
=> Validate cluster after updating bastions

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Newer distros like Debian 10 and RHEL/CentOS 8 are using iptables 1.8 which defaults to NFT backend. Kubernetes 1.17 adds support and auto-detection for it. From the release notes:
> The official kube-proxy image (used by kubeadm, among other things) is now compatible with systems running iptables 1.8 in “nft” mode, and will autodetect which mode it should use. (#82966)
Calico doesn't yet have auto-detection for the iptables backend, but has a flag named `IptablesBackend` (env var `FELIX_IPTABLESBACKEND`) that can switch from Legacy to NFT:
https://docs.projectcalico.org/v3.9/reference/felix/configuration#iptables-dataplane-configuration
Without this flag Debian 10 networking is broken in Kubernetes 1.17.0. Kubernetes auto-detects NFT and uses it, but Calico still uses legacy, which is an …
=> Add support for NFT with Calico and Canal

docs/development/rolling_update.md, docs/welcome/contributing.md, docs/welcome/office_hours.md
Couple of minor link fixes to development related docs/images
Also cleans up the lists under issues and pull requests headings in `welcome/contributing.md` and lists in `welcome/office_hours.md`
=> Docs: Fix some broken development links

pkg/apis/kops/networking.go, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #8022 on release-1.17.
#8022: Bump cilium version to 1.6.4
=> Automated cherry pick of #8022: Bump cilium version to 1.6.4

nodeup/pkg/distros/distribution.go, nodeup/pkg/model/kube_controller_manager.go, nodeup/pkg/model/kubelet.go, nodeup/pkg/model/miscutils.go, nodeup/pkg/model/ntp.go
Cherry pick of #7545 on release-1.17.
#7545: Complete support for Flatcar
=> Automated cherry pick of #7545: Complete support for Flatcar

cmd/kops/rollingupdatecluster.go, k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/instancegroups/rollingupdate.go, upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #7917 #8076 on release-1.17.
#7917: Canal v3.10 manifest for k8s v1.15+
#8076: Set FELIX_IPTABLESBACKEND for Calico and Canal
=> Automated cherry pick of #7917 and #8076

upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template, upup/pkg/fi/cloudup/tests/manifests/k8s-1.13.yaml
E1212 09:15:05.046471       1 leaderelection.go:331] error retrieving resource lock kube-system/cloud-controller-manager: leases.coordination.k8s.io “cloud-controller-manager” is forbidden: User “system:serviceaccount:kube-system:cloud-controller-manager” cannot get resource “leases” in API group “coordination.k8s.io” in the namespace “kube-system”
/kind bug
=> add missing rbac rules

upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template
cherry pick #8095
adds missing RBAC rules for openstack external cloud controller manager. Without this 1.17 CCM does not work
/kind bug
=> Cherry pick #8095

cmd/kops/rollingupdatecluster.go, pkg/instancegroups/instancegroups.go, pkg/instancegroups/rollingupdate.go, pkg/instancegroups/rollingupdate_test.go
=> test validateCluster twice to make sure it does not flap

docs/README.md
- Broken link on https://github.com/pshanoop/kops/tree/master/docs#inspection for **Get AWS subdomain NS records.**
=> docs(advanced): fix broken links on doc

tests/integration/update_cluster/ha_gce/kubernetes.tf, upup/pkg/fi/cloudup/gcetasks/instancegroupmanager.go, upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
Upgraded some google cloud terraform resources to fit google cloud provider 3.0
* instance template name_prefix is maximum length of 32
* instance group manager needs the instance_template in a version block 
See also https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html
Btw, syntax is still terraform 0.11 and needs to be transformed with terraform 0.12upgrade
=> some resources upgraded to google provider 3.0

pkg/model/alimodel/convenience.go, pkg/model/convenience.go, pkg/model/dns.go, pkg/model/openstackmodel/context.go, pkg/model/openstackmodel/convenience.go, pkg/model/openstackmodel/servergroup.go, pkg/nodeidentity/openstack/identify.go, pkg/pki/sshkey.go
1：remove some repeat code 
2：fix some staticcheck
=> fix-pkg-staticcheck and remove the repeat code

cmd/kops/rollingupdatecluster.go, pkg/instancegroups/instancegroups.go, pkg/instancegroups/rollingupdate.go, pkg/instancegroups/rollingupdate_test.go
Cherry pick of #8088 #8105 on release-1.17.
#8088: validate cluster twice
#8105: Add unit test for flapping validation
=> Automated cherry pick of #8088: validate cluster twice #8105: Add unit test for flapping validation

pkg/testutils/modelharness.go
Don't treat a failure to read a file as an error, if we are supposed
to be generating that file.
=> dev: hack/update-expected.sh should generate missing file

hack/update-expected.sh
hack/update-expected.sh should ignore KOPSCONTROLLER_IMAGE when
regenerating the golden test outputs, just as it ignores the local
DNSCONTROLLER_IMAGE override.
=> dev: ignore kops-controller in hack/update-expected.sh

tests/integration/update_cluster/ha_gce/kubernetes.tf, upup/pkg/fi/cloudup/terraform/target.go
From #8103: added google provider verison to 3.0.0. For terraform 0.11 it needs to go into the provider block (see https://www.terraform.io/docs/configuration-0-11/providers.html)
Alternative to #8106.
@justinsb : sorry for the duplicate effort. I think the change of the required_provider version needs to go onto the bucket list for moving to terraform 0.12
=> Terraform GCE output: setting google provider to at least 3.0.0

upup/pkg/fi/cloudup/openstacktasks/port.go, upup/pkg/fi/cloudup/openstacktasks/port_test.go
Previously we mistakenly used the names of the additional security
groups where the API is expecting their ID.
Cherry pick of #8004
=> Automated cherry pick of #8004: fix(openstack): fix additional security groups on instance groups

channels/alpha, channels/stable
ref: https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#116
=> channels: bump k8s versions after dec. patch releases

docs/README.md
- Fixed broken links on advanced docs `Experimental features` and `Download kops configuration`
=> Fix doc(advanced) broken links

docs/development/api_updates.md, docs/examples/coreos-kops-tests-multimaster.md, docs/operations/cluster_upgrades_and_migrations.md
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>
ref: https://github.com/kubernetes/kops/issues/7944
Because some of the linked files changed a lot, I just modified them as I thought.
Therefore, some links in this pr may be modified incorrectly.
=> fix 404 urls

hack/.staticcheck_failures, pkg/client/simple/api/clientset.go, pkg/diff/diff_test.go, pkg/model/firewall_test.go, pkg/model/gcemodel/convenience.go, pkg/model/network.go
=> pkg/model pkg/diff pkg/client/:simplify code and remove unused code

cmd/kops/validate_cluster.go, docs/cli/kops_validate_cluster.md
=> Add kubeconfig flag to validate cluster command

pkg/apis/kops/instancegroup.go, pkg/apis/kops/v1alpha1/instancegroup.go, pkg/apis/kops/v1alpha2/instancegroup.go, upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go, upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go
Cherry pick of #7406 on release-1.16.
#7406: Add CapacityOptimized to list of supported spot allocation
=> Automated cherry pick of #7406: Add CapacityOptimized to list of supported spot allocation

hack/.staticcheck_failures, util/pkg/tables/format.go
=> util/pkg/ upup/tools/ :  simplify code and remove unused  code

channels/alpha
=> Bump COS version in alpha channel for k8s >= 1.16

upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Calico v3.10 is here with some nice new stuff like bird/bird6 liveness checks.
Canal is already at 3.10 but Calico should be upgraded too.
This PR addresses also some other issues:
* make Calico and Canal templates easier to compare, by moving around some fields
* make Canal easier to compare to official manifest
* add role.kubernetes.io/networking labels to Canal
Commits should be reviewed one by one, as it will be much easier to compare each step.
=> Update Calico to v3.10.2

pkg/instancegroups/rollingupdate_test.go
We never know when e.g. a GC is going to delay us, so we need a lot
more padding on these timeouts.
=> tests: increase timeout in rolling update tests

nodeup/pkg/model/docker.go, upup/pkg/fi/nodeup/nodetasks/package.go, upup/pkg/fi/nodeup/tags/tags.go
/kind feature
**What this PR does / why we need it?**
Changes the way local packages are installed from using the low level dpkg and rpm tools to their higher level alternatives apt and and yum.
This reduces the work needed to maintain the dependencies by letting the package manager take care of this task. Optional dependencies can still be provided if needed.
**Which issue(s) this PR fixes?**
May be a solution for #7878
**Special notes for your reviewer**
At the moment Kops relies on a list of dependencies for each local package that is installed.
Providing a list of dependencies is prone to errors over time and may not know exactly why each dep was added.
Dependencies are only checked if they are installed, not also if the version is the minimum required. …
=> Automatically install dependencies with local packages

nodeup/pkg/model/docker.go
Periodic tests for Ubuntu 16.04 (Xenial) are broken because of missing Docker packages:
https://github.com/kubernetes/kops/pull/7878#issuecomment-567490828
This fix adds Xenial packages for both 19.03.4 and 18.09.9.
=> Fix periodic e2e test for Ubuntu 16.04

upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This PR replaces PRs #8019 and #7920, upgrades the Spotinst controller to version 1.0.50 and aligns all resources with the corresponding Helm [chart](https://github.com/spotinst/spotinst-kubernetes-helm-charts).
=> Spotinst: Upgrade the Spotinst controller to version 1.0.50

cmd/nodeup/main.go, pkg/apis/kops/model/utils.go
I do some cleanup in main file and model/utils.go, to make code more cleaner.
=> kops-change-main

cmd/kops-controller/BUILD.bazel, dns-controller/cmd/dns-controller/BUILD.bazel, images/dns-controller/Dockerfile
They do not need root privileges, so should not be given them.
=> Run dns-controller and kops-controller as non-root user

Makefile, hack/.staticcheck_failures, hack/verify-staticcheck.sh
The new job was missing the generated files from go-bindata. I tested this locally on a clean checkout.
I noticed some of the prow jobs use make and others call hack/ scripts directly.
I think it'd be better to use make so we can more easily add dependencies like this, therefor I'd like to propose that we merge this, update the job to call `make verify-staticcheck` then remove the make command from hack/verify-staticcheck.sh
By fixing the existing job as well as the make target, we can unblock other PRs and not get another swarm of failure notifications when the job gets updated to use make.
=> Fix verify-staticcheck prow job

pkg/resources/digitalocean/cloud.go, pkg/resources/digitalocean/resources.go, upup/pkg/fi/cloud.go, upup/pkg/fi/cloudup/aliup/ali_cloud.go, upup/pkg/fi/cloudup/awsup/aws_cloud.go, upup/pkg/fi/cloudup/baremetal/cloud.go, upup/pkg/fi/cloudup/dotasks/volume.go, upup/pkg/fi/cloudup/dotasks/volume_test.go, upup/pkg/fi/cloudup/gce/gce_cloud.go, upup/pkg/fi/cloudup/openstack/cloud.go, upup/pkg/fi/cloudup/vsphere/vsphere_cloud.go
This enables us to simply the apply logic.
=> Refactor: Add Region() method to fi.Cloud

hack/verify-staticcheck.sh
Followup to https://github.com/kubernetes/kops/pull/8182 and https://github.com/kubernetes/test-infra/pull/15674
This script should now be called using `make verify-staticcheck` which will handle the go-bindata dependency.
Also using this PR to verify the changed prow jobs from the test-infra PR above.
=> Remove make command from verify-staticcheck.sh

upup/pkg/fi/cloudup/gcetasks/storagebucketacl.go
Needs to be Role:Entity Name not Role:Resource Name. It came out as 
`WRITER:serviceAccount...`
now it is
`
WRITER:user-708930735790-compute@developer.gserviceaccount.com
`
https://cloud.google.com/storage/docs/json_api/v1/bucketAccessControls
=> GCE: Fix Permission for the Storage Bucket

hack/.staticcheck_failures, pkg/instancegroups/instancegroups.go
Ref: #7800
Error from staticcheck:
```
pkg/instancegroups/instancegroups.go:233:19: using time.Tick leaks the underlying ticker, consider using it only in endless functions, tests and the main package, and use time.NewTicker here (SA1015)
```
=> pkg/instancegroups - fix static check

cmd/kops/update_cluster.go, cmd/kops/util/factory.go, upup/pkg/fi/cloudup/apply_cluster.go
This updates all references to `https://github.com/kubernetes/kops/blob/master/docs` in the source code to instead use the new docs site.
=> Update links printed by Kops to use new docs site

dnsprovider/pkg/dnsprovider/providers/aws/route53/route53_test.go, dnsprovider/pkg/dnsprovider/providers/coredns/coredns_test.go, dnsprovider/pkg/dnsprovider/providers/google/clouddns/clouddns_test.go, dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/clouddns.go, dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/BUILD.bazel, dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/clouddns.go, hack/.staticcheck_failures
Ref: #7800
Errors from staticcheck:
```
dnsprovider/pkg/dnsprovider/providers/aws/route53/route53_test.go:131:6: func getInvalidRrs is unused (U1000)
dnsprovider/pkg/dnsprovider/providers/coredns/coredns_test.go:111:6: func listRrsOrFail is unused (U1000)
dnsprovider/pkg/dnsprovider/providers/google/clouddns/clouddns_test.go:109:6: func getInvalidRrs is unused (U1000)
dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/clouddns.go:28:18: field impl is unused (U1000)
dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/clouddns.go:30:26: field impl is unused (U1000)
dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/clouddns.go:34:16: field impl is unused (U1000)
dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/clouddns.go:29:26: field …
```
=> dnsprovider/pkg/dnsprovider - fix static check

hack/.staticcheck_failures, pkg/resources/ali/ali.go, pkg/sshcredentials/BUILD.bazel, pkg/sshcredentials/fingerprint.go
ref:#7800
Special notes:
pkg/resources/ali/ali.go:63:3: this value of region is never used (SA4006)
pkg/resources/ali/ali.go:427:27: this result of append is never used, except maybe in other appends (SA4010)
pkg/sshcredentials/fingerprint.go:57:6: func insertFingerprintColons is unused (U1000)
pkg/sshcredentials/fingerprint.go:25:2: imported and not used: "k8s.io/klog"
pkg/resources/ali/ali.go:427:13: append(roleToDelete, role.RoleId) evaluated but not used
pkg/resources/ali/ali.go:415:2: roleToDelete declared and not used
=> fix staticcheck failures in pkg/resources

upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
This release reduces CPU and memory usage in larger clusters, by sending notifications to a smaller set of peers and coalescing updates to reduce topology recalculation. #3715, #3732
Also several bug-fixes and smaller enhancements.
The default soft limit on connections has been raised from 100 to 200.
More details at https://github.com/weaveworks/weave/releases/tag/v2.6.0
=> Update Weave Net to version 2.6.0

cmd/kops/create.go, cmd/kops/create_cluster.go, cmd/kops/replace.go, pkg/model/components/BUILD.bazel, pkg/model/components/apiserver.go, pkg/model/components/kubecontrollermanager.go, pkg/model/components/kubelet.go
Previously when setting the external cloud controller manager configuration the core components `kubelet`, `apiserver` and `kubecontroller-manager` were configured to use the external cloud controller manager. Without setting the feature flag `EnableExternalCloudController` this lead to a cluster in which the masters had the node taint `node.cloudprovider.kubernetes.io/uninitialized` which prevents essential pods, like dns-controller to not be scheduled and leaves a cluster where worker nodes can't connect to the api server because they cannot resolve its hostname.
=> Guard External cloud controller manager with its feature flag

pkg/validation/BUILD.bazel, pkg/validation/validate_cluster.go, pkg/validation/validate_cluster_test.go
/kind bug
When performing cluster validation on a cluster with spot instance nodes (nodes annotated with `node-role.kubernetes.io/spot-worker: "true"`), kops will ignore the node readiness roughly 50% of the time, instead printing the message:
```
W1219 06:35:47.885028    1605 validate_cluster.go:291] ignoring node with role "spot-worker"
```
This means that cluster validation can randomly incorrectly succeed.
This change has cluster validation determine the node's role using the instancegroup spec, not an annotation chosen depending on the randomization of Go map ordering.
Fixes #5038
=> Always consider spot instance node readiness in cluster validation

nodeup/pkg/distros/distribution.go, nodeup/pkg/model/firewall.go, nodeup/pkg/model/miscutils.go, nodeup/pkg/model/ntp.go
RHEL/CentOS 8 support is broken for various reasons:
1. check for Debian family doesn't recognise the distro
2. `iptables-setup` cannot be run from home dir (probably some extra security)
3. `python` package needs to be more explicit (`python2` or `python3`)
4. `ntpd` fails to install because it has been replaced with `chronny`
=> Update support for RHEL 8

hack/.staticcheck_failures, upup/tools/generators/pkg/codegen/parse.go
Ref:#7800
```
upup/tools/generators/pkg/codegen/parse.go:40:2: field typeName is unused (U1000)
upup/tools/generators/pkg/codegen/parse.go:113:35: importer.For is deprecated: Use ForCompiler, which populates a FileSet with the positions of objects created by the importer.  (SA1019)
```
=> Fix upup/tools/generators/pkg/codegen staticcheck failures

nodeup/pkg/model/containerd.go, nodeup/pkg/model/docker.go, pkg/model/components/containerd.go, pkg/model/components/containerd_test.go, pkg/model/components/docker.go, tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml, tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml, tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml, tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/containerd-cloudformation/in-v1alpha2.yaml, tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml, tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml, tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
This PR is related to #7986:
1. adds the `containerd-1.2.4` package for a previously released Docker version
2. sets the default version only for Kubernetes versions >= 1.18
3. warns that Kubernetes versions >= 1.11 and < 1.18 are untested
4. exits with error when Kubernetes versions < 1.11
=> containerd: Use containerd 1.2.4 with Docker 18.09.3

permalinks/upgrade_k8s.md, upup/pkg/fi/cloudup/apply_cluster.go
As discussed during yesterday's office hours.
This should be cherry-picked back to 1.16.
We'll need to bump the minor version in the 1.17 and master branches. Once we officially drop support we could make this a sliding window that uses the `kops.Version` variable.
I think we could have deprecation warnings for the 2 oldest versions still supported by the kops version, announcing that the n+2 Kops version will no longer support the specified k8s version.
=> Add deprecation warning for older k8s versions

cmd/kops/export_kubecfg.go, docs/cli/kops_export_kubecfg.md
=> Add all flag to export cluster command

cmd/kops/delete_cluster.go, cmd/kops/export.go, cmd/kops/export_kubecfg.go, cmd/kops/integration_test.go, cmd/kops/pkix.go, cmd/kops/root.go, cmd/kops/toolbox_bundle.go, hack/.staticcheck_failures
Ref:#7800
```
cmd/kops/delete_cluster.go:95:6: type getter is unused (U1000)
cmd/kops/export.go:40:6: type ExportOptions is unused (U1000)
cmd/kops/export_kubecfg.go:48:2: field tmpdir is unused (U1000)
cmd/kops/export_kubecfg.go:49:2: field keyStore is unused (U1000)
cmd/kops/integration_test.go:102:2: this value of lifecycleOverrides is never used (SA4006)
cmd/kops/pkix.go:61:6: func parsePkixName is unused (U1000)
cmd/kops/root.go:275:6: func readKubectlClusterConfig is unused (U1000)
cmd/kops/toolbox_bundle.go:188:6: func writeToTar is unused (U1000)
```
=> Fix cmd/kops staticcheck failures

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #7492 on release-1.14.
#7492: fix(addons/coredns.addons.k8s.io) Workaround to stop
=> Automated cherry pick of #7492: fix(addons/coredns.addons.k8s.io) Workaround to stop

upup/pkg/fi/cloudup/awsup/aws_cloud.go
=> Cherry pick of #8038 onto release-1.14

hack/go_install_from_commit.sh, hack/pre-commit.sh, hack/update-bazel.sh, hack/update-expected.sh, hack/verify-apimachinery.sh, hack/verify-generate.sh, hack/verify-gomod, hack/verify-spelling.sh, hack/verify-staticcheck.sh
/cc @justinsb  @mikesplain @rifelpet @robinpercy  
/hold
Let's talk about there changes 
i have run  ./hack/update-header.sh before i commited it.
=> /hack: improve shell script  in hack

upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
When booting a cluster with `--networking=cni`, `dns-controller` will not start due to the master node being _tainted_ as "network unreachable". This adds an extra step when managing your own CNI setup, having to SSH into a master and publish the CNI manifests from there.
An operator should expect `kops` to provide a managable cluster by the end of `kops update cluster --yes` step, even if managing the CNI externally, so the next step is a natural "`kubectl apply -f my-cni.yaml`".
This PR adds tolerance and configuration that allows `dns-controller` pod to start when running with `--networking=cni`, properly creating the DNS records so the operator can remotely publish the CNI and extra manifests to have a full working cluster.
This also removes the dependency on `kube-proxy`, by adding …
=> dns-controller: allow it to run on CNI networking mode and remove dependency on kube-proxy

pkg/assets/builder.go
In string based trim scenarios,we shall always use string based TrimPrefix/TrimSuffix instead of char based TrimLeft/TrimRight.
See the diff here: https://play.golang.org/p/S7cBaoIxPQy
=> replace TrimRight with TrimSuffix

cmd/kops/export_kubecfg.go
Fix typo mentioned in #8179 
@justinsb
=> Fix typo in export kubeconfig

nodeup/pkg/model/kube_proxy.go
very minor, but meant to ensure that KubeProxyBuilder satisfies the ModelBuilder interface. likely a copy/paste typo based on other files in the same package.
=> Fix typo in KubeProxy model

upup/pkg/fi/cloudup/apply_cluster.go
Thanks for pointing this out @johngmyers 
It is meant to point [here](https://github.com/kubernetes/kops/blob/master/permalinks/upgrade_k8s.md)
=> Fix link printed in k8s version deprecation message

nodeup/pkg/model/network.go
systemd v238 already includes the mount, and the unit file fails.  We
test for the existence of the mount, rather than testing systemd
versions directly.
=> cilium: don't try to mount sys/fs/bpf if already mounted

pkg/resources/aws/aws.go, pkg/resources/aws/aws_test.go
=> Set shared field for volume resource on delete

cmd/kops/toolbox_template.go, dns-controller/pkg/watchers/ingress.go, dns-controller/pkg/watchers/service.go, hack/verify-staticcheck.sh, upup/pkg/fi/cloudup/alitasks/vpc.go, upup/pkg/fi/cloudup/openstacktasks/volume.go
Ref: #7800
This change adds back code simplification checks.
It also makes the style rules we are breaking explicit, to prevent other types of style checks to break and to make it easier to fix style these later if wanted.
```
Errors from staticcheck:
cmd/kops/toolbox_template.go:138:38: should use make(map[string]string) instead (S1019)
cmd/kops/toolbox_template.go:215:42: should use make(map[string]interface{}) instead (S1019)
cmd/kops/toolbox_template.go:228:40: should use make(map[string]interface{}) instead (S1019)
dns-controller/pkg/watchers/ingress.go:170:4: should merge variable declaration with assignment on next line (S1021)
dns-controller/pkg/watchers/service.go:206:5: should merge variable declaration with assignment on next line (S1021) …
```
=> Add code simplifications for staticheck

nodeup/pkg/model/network.go
Cherry pick of #7832 on release-1.17.
#7832: cilium: don't try to mount sys/fs/bpf if already mounted
=> Automated cherry pick of #7832: cilium: don't try to mount sys/fs/bpf if already mounted

dnsprovider/pkg/dnsprovider/plugins.go, dnsprovider/pkg/dnsprovider/providers/aws/route53/stubs/route53api.go, dnsprovider/pkg/dnsprovider/providers/coredns/coredns.go, dnsprovider/pkg/dnsprovider/providers/coredns/rrchangeset.go, dnsprovider/pkg/dnsprovider/providers/coredns/rrsets.go, dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/changes_create_call.go, dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/managed_zone_create_call.go, dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/managed_zones_delete_call.go, dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/managed_zones_list_call.go, dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/rrsets_service.go, dnsprovider/pkg/dnsprovider/providers/google/clouddns/rrchangeset.go
dnsprovider/pkg/dnsprovider/plugins.go:90:26: error strings should not be capitalized (ST1005)
dnsprovider/pkg/dnsprovider/providers/aws/route53/stubs/route53api.go:83:27: error strings should not be capitalized (ST1005)
dnsprovider/pkg/dnsprovider/providers/aws/route53/stubs/route53api.go:88:27: error strings should not be capitalized (ST1005)
dnsprovider/pkg/dnsprovider/providers/aws/route53/stubs/route53api.go:113:25: error strings should not be capitalized (ST1005)
dnsprovider/pkg/dnsprovider/providers/aws/route53/stubs/route53api.go:124:25: error strings should not be capitalized (ST1005)
dnsprovider/pkg/dnsprovider/providers/aws/route53/stubs/route53api.go:127:25: error strings should not be capitalized (ST1005) …
=> dnsprovider staticcheck

cmd/kops/replace.go, cmd/kops/root.go, cmd/kops/toolbox_bundle.go, cmd/kops/toolbox_convert_imported.go, cmd/kops/toolbox_dump.go, cmd/kops/update_cluster.go, cmd/kops/util/factory.go, cmd/kops/validate_cluster.go
cmd/kops/replace.go:220:22: error strings should not be capitalized (ST1005)
cmd/kops/root.go:224:20: error strings should not be capitalized (ST1005)
cmd/kops/toolbox_bundle.go:83:20: error strings should not be capitalized (ST1005)
cmd/kops/toolbox_bundle.go:86:20: error strings should not be capitalized (ST1005)
cmd/kops/toolbox_convert_imported.go:135:20: error strings should not be capitalized (ST1005)
cmd/kops/toolbox_convert_imported.go:141:21: error strings should not be capitalized (ST1005)
cmd/kops/toolbox_convert_imported.go:146:21: error strings should not be capitalized (ST1005)
cmd/kops/toolbox_dump.go:145:20: error strings should not be capitalized (ST1005)
cmd/kops/update_cluster.go:222:30: error strings should not be …
=> cmd/kops/ staticcheck and remove one mom 

nodeup/pkg/model/context.go, nodeup/pkg/model/file_assets.go, nodeup/pkg/model/kube_apiserver.go, nodeup/pkg/model/kube_proxy.go, nodeup/pkg/model/volumes.go, pkg/model/components/context.go, pkg/nodeidentity/do/identify.go, pkg/resources/aws/aws.go, pkg/testutils/modelharness.go, pkg/util/subnet/subnet.go
nodeup/pkg/model/context.go:570:24: error strings should not be capitalized (ST1005)
nodeup/pkg/model/context.go:574:24: error strings should not be capitalized (ST1005)
nodeup/pkg/model/file_assets.go:86:22: error strings should not be capitalized (ST1005)
nodeup/pkg/model/kube_apiserver.go:278:19: error strings should not be capitalized (ST1005)
nodeup/pkg/model/kube_proxy.go:132:25: error strings should not be capitalized (ST1005)
nodeup/pkg/model/kube_proxy.go:140:26: error strings should not be capitalized (ST1005)
nodeup/pkg/model/kube_proxy.go:148:26: error strings should not be capitalized (ST1005)
nodeup/pkg/model/kube_proxy.go:156:26: error strings should not be capitalized (ST1005)
nodeup/pkg/model/volumes.go:48:21: error …
=> nodeup/pkg/ pkg/ staticcheck: Fix ST1005

upup/pkg/fi/cloudup/awsup/aws_cloud.go, upup/pkg/fi/cloudup/awsup/aws_utils.go, upup/pkg/fi/cloudup/defaults.go, upup/pkg/fi/cloudup/dns.go, upup/pkg/fi/cloudup/gce/gce_cloud.go, upup/pkg/fi/cloudup/gce/labels.go, upup/pkg/fi/cloudup/gcetasks/address.go, upup/pkg/fi/cloudup/gcetasks/disk.go, upup/pkg/fi/cloudup/gcetasks/forwardingrule.go, upup/pkg/fi/cloudup/gcetasks/instance.go, upup/pkg/fi/cloudup/loader.go, upup/pkg/fi/cloudup/openstack/availability_zone.go, upup/pkg/fi/cloudup/openstack/cloud.go, upup/pkg/fi/cloudup/openstack/floatingip.go, upup/pkg/fi/cloudup/openstack/instance.go, upup/pkg/fi/cloudup/openstack/loadbalancer.go
TLTR  
/cc @rifelpet 
/cc @justinsb 
@hakman 
```
upup/pkg/fi/cloudup/openstack/server_group.go:121:26: error strings should not be capitalized (ST1005)
upup/pkg/fi/cloudup/openstack/utils.go:59:24: error strings should not be capitalized (ST1005)
upup/pkg/fi/cloudup/openstack/utils.go:64:24: error strings should not be capitalized (ST1005)
upup/pkg/fi/cloudup/openstack/utils.go:96:24: error strings should not be capitalized (ST1005)
upup/pkg/fi/cloudup/openstack/utils.go:112:24: error strings should not be capitalized (ST1005)
upup/pkg/fi/cloudup/openstack/utils.go:115:23: error strings should not be capitalized (ST1005)
upup/pkg/fi/cloudup/openstacktasks/floatingip.go:56:28: error strings should not be capitalized (ST1005) …
```
=> upup/pkg/fi/cloudup/ staticcheck: Fix ST1005

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/parse_test.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go, upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template, upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/cluster.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
This is a PR to address #8113 whereby kops users can gain the ability to configure resources for the weave and weave-npc containers inside the weave daemonset.
Signed-off-by: mmerrill3 <michael.merrill@vonage.com>
=> Adding ability to configure resources for weave (#8113)

nodeup/pkg/model/containerd_test.go, nodeup/pkg/model/docker_test.go, nodeup/pkg/model/kubelet.go, nodeup/pkg/model/node_authorizer.go, nodeup/pkg/model/protokube.go, nodeup/pkg/model/tests/kubelet/featuregates/cluster.yaml, nodeup/pkg/model/tests/protokube/containerd/tasks.yaml, upup/pkg/fi/nodeup/nodetasks/load_image.go
This fixes various tiny nits observed after #7986 :
* run Protokube in the "default" container namespace instead of "k8s.io", same way is done with Docker
* delete Protokube container on restart without pausing first, not needed and can cause a deadlock
* update hardcoded service dependencies on "docker.service" to "containerd.service" when needed
* run each package hash check as a separate test, some feedback is nice when it takes 3 min
=> containerd: Fix tiny nits

docs/cluster_spec.md, docs/instance_groups.md, k8s/crds/kops.k8s.io_clusters.yaml, k8s/crds/kops.k8s.io_instancegroups.yaml, nodeup/pkg/model/sysctls.go, pkg/apis/kops/cluster.go, pkg/apis/kops/instancegroup.go, pkg/apis/kops/v1alpha1/cluster.go, pkg/apis/kops/v1alpha1/instancegroup.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/cluster.go, pkg/apis/kops/v1alpha2/instancegroup.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
This adds a new `sysctlParameters` to cluster spec and instance group spec to allow setting custom runtime kernel parameters.
I needed to be able to set sysctl parameters on our nodes. I considered adding a file asset, but we can't currently set the `OnChangeExecute` of a `File` nodetask that way. Since we already have a sysctl builder, this change seemed to be an obvious one.
=> Custom sysctl Parameters

cmd/kops/integration_test.go, cmd/kops/lifecycle_integration_test.go, pkg/resources/aws/vpc_test.go, tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml, tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml, tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml, tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data, tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_nodes.k8s-iam.us-west-2.td.priv_user_data, tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml, tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml, tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
To go along with our version deprecation we should update our mocked kops versions
=> Update mock kops version in integration tests

Makefile, tools/gzip.bzl, tools/sha1, tools/sha256
Fixes 2 issues with protokube upload builds on osx:
* Bazel doesn't seem to have access to `which`.  After a number of attempts to fix it locally, it appears this is why we had originally been using `command -v` in Makefile
* `k8-fastbuild` is a platform specific path, so move to label based path.  It will now build in the same directory as everything else.
Tested on a linux box as well to confirm no regression.
I'll plan to cherry pick this to the branches that include these issues as well. Thanks!
=> Fix protokube osx build

docs/aws-china.md
Since kops 1.15.0, nodeup verifies kops assets against the `.sha256` file.
Fixes #8242
=> Fix aws-china.md to download SHA-256 checksums for kops assets

.travis.yml
We don't need it and Travis OS/X resources appear to be scarce.
=> Exclude one Travis osx job

upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
There have been a few regressions in the way InstanceGroups are marked for a RollingUpdate when `LaunchTemplates` are involved (e.g. when using Mixed Instance Policies). This bug resulted in one of two scenarios that I've seen (with previous attempted fixes regressing one of the scenarios):
- Updates via kops (`kops update cluster --yes`) did not set a LT Version, and so an Instance Group using a Mixed Instance Policy would always be marked as `NeedsUpdate` when performing a Rolling Update
- Updates via terraform (`kops update cluster --out=tf-files/ --target=terraform`) were not being marked for a RollingUpdate as the Version was not picked up and matched between changes
This PR aims to fix the above two scenarios. I've tested a cluster build with 2 different Instance Groups (one …
=> Fix RollingUpdate behaviour when using LaunchTemplates for both kops & terraform spec updates

nodeup/pkg/model/firewall.go, pkg/model/resources/nodeup.go, pkg/model/tests/data/bootstrapscript_0.txt, pkg/model/tests/data/bootstrapscript_1.txt, pkg/model/tests/data/bootstrapscript_2.txt, pkg/model/tests/data/bootstrapscript_3.txt, pkg/model/tests/data/bootstrapscript_4.txt, pkg/model/tests/data/bootstrapscript_5.txt, tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml, tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml, tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml, tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml, tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml, tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
RHEL / CenOS 8 have some restrictions on binaries location for Systemd.
This is why initial configuration for `nodeup` cannot run and e2e tests are failing.
https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-aws-containerd
Moving `nodeup` to /opt/kops/bin solves this issue.
At same time, `iptables-setup` script should also move to /opt/kops/bin. https://github.com/kubernetes/kops/pull/8164#discussion_r361681377
```
/opt/kops/
├── bin
│   ├── iptables-setup
│   └── nodeup
└── conf
├── cluster_spec.yaml
├── ig_spec.yaml
└── kube_env.yaml
```
=> Move nodeup to /opt/kops/bin

nodeup/pkg/model/protokube.go, tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml, tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml, tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml, tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml, tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml, tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml, upup/pkg/fi/cloudup/apply_cluster.go, upup/pkg/fi/nodeup/command.go, upup/pkg/fi/nodeup/nodetasks/load_image.go
If we're not going to use the docker images, we don't need to preload
them - saves a bit off the boot time.
=> For dev, don't preload docker images on nodes

pkg/model/bootstrapscript.go, pkg/model/tests/data/bootstrapscript_0.txt, pkg/model/tests/data/bootstrapscript_1.txt, pkg/model/tests/data/bootstrapscript_2.txt, pkg/model/tests/data/bootstrapscript_3.txt, pkg/model/tests/data/bootstrapscript_4.txt, pkg/model/tests/data/bootstrapscript_5.txt
The current yum proxy configuration for rhel is invalid and has no effect on pointing yum operations via a proxy.
Check https://linux.die.net/man/5/yum.conf
The proxy config option for yum is "proxy" not "http_proxy"
=> fixed yum proxy configuration

k8s/crds/kops.k8s.io_clusters.yaml, nodeup/pkg/model/kube_apiserver.go, nodeup/pkg/model/kube_apiserver_test.go, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/componentconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
As of kubernetes 1.13, the [`--encryption-provider-config`](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#configuration-and-determining-whether-encryption-at-rest-is-already-enabled) flag should be used instead of the variant that provided alpha support for the feature.
From https://v1-13.docs.kubernetes.io/docs/setup/release/notes/#deprecations:
>The `--experimental-encryption-provider-config` flag is deprecated in favor of `--encryption-provider-config`. The old flag is accepted with a warning but will be removed in 1.14.
=> Use non-experimental version of encryption provider config flag in 1.13+

cmd/kops/rollingupdatecluster.go, pkg/featureflag/featureflag.go, pkg/instancegroups/BUILD.bazel, pkg/instancegroups/instancegroups.go, pkg/instancegroups/rollingupdate.go
It's excessive having this and `CloudOnly` and `FailOnValidate` and `FailOnDrainError`.
=> Remove DrainAndValidateRollingUpdate feature flag

upup/pkg/fi/clientset_castore.go
ref: #8244 
Update import package alias:
`v1 "k8s.io/apimachinery/pkg/apis/meta/v1"` -> `metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"`
=> staticcheck:modify the import package alias

cmd/kops/validate_cluster.go
Unsure if this is the right approach but wanted to get some others input. I often run into issues on macOS where I cannot run `kops validate cluster` due to failed DNS resolution. I am using OpenVPN Connect which does not edit `/etc/resolv.conf` (which is not standard anymore in macOS anyways at least). By forcing `cgos` to be disabled, `kops validate cluster` uses the `net` packages default resolver that only uses the `nameserver` listed in `/etc/resolv.conf`. In this case, that is the DHCP DNS, which fails.
To see the DNS difference, you can see the single `nameserver` listed in `/etc/resolv.conf` and then other resolvers which are populated via my VPN client.
```
(⎈ |kube-development-01.<redacted>)[kops] cat /etc/resolv.conf …
```
=> Remove forcing disabled cgos Darwin

nodeup/pkg/model/directories.go, pkg/model/resources/nodeup.go, pkg/model/tests/data/bootstrapscript_0.txt, pkg/model/tests/data/bootstrapscript_1.txt, pkg/model/tests/data/bootstrapscript_2.txt, pkg/model/tests/data/bootstrapscript_3.txt, pkg/model/tests/data/bootstrapscript_4.txt, pkg/model/tests/data/bootstrapscript_5.txt, tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml, tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml, tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml, tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml, tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml, tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml, upup/pkg/fi/nodeup/nodetasks/bindmount.go
This approach means that rather than trying to have different
directories on different OSes, we can instead make them look more
similar.
=> Make /opt/kops writeable on COS

docs/operations/addons.md, pkg/drain/drain.go
Although it is spelling mistakes, it might make an affects while reading.
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
=> Remove duplicated words

upup/pkg/fi/nodeup/nodetasks/service.go
We handle service dependencies on BindMount and Archive tasks; this
avoids some false-positive warning messages.
=> nodeup: Add some dependencies for Service

Makefile, tools/gzip.bzl, tools/sha1, tools/sha256
Cherry pick of #8263 on release-1.16.
#8263: Replace binary "which" with build in "command"
=> Automated cherry pick of #8263: Replace binary "which" with build in "command"

upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template, upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template, upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/cluster.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.12.yaml
This will tag ENIs with `cluster.k8s.amazonaws.com/name`
Support for this was added back in v1.1.0: https://github.com/aws/amazon-vpc-cni-k8s/commit/c82dc6e1c0330e76a4ef53df4271bebccb764910 so I added it to all manifest versions.
I'll work on exposing [the other supported env vars](https://github.com/aws/amazon-vpc-cni-k8s/blob/ae4329102d546322a03a635d58b97d98794a4ae0/ipamd/ipamd.go#L69) via the cluster spec next.
=> Set CLUSTER_NAME env var on amazon-vpc-cni pods

pkg/model/components/containerd.go
For testing I need to be able to enable the containerd container runtime with Kubernetes 1.17 without setting the version in cluster spec.
It is a tiny change that should have minimal effect outside e2e tests.
=> containerd: Set a default version even with Kubernetes 1.17

upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.10.yaml.template, upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.7.yaml.template, upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.8.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/cluster.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.12.yaml
Cherry pick of #8274 on release-1.17.
#8274: Set CLUSTER_NAME env var on amazon-vpc-cni pods
=> Automated cherry pick of #8274: Set CLUSTER_NAME env var on amazon-vpc-cni pods

nodeup/pkg/model/logrotate.go, upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/template_functions.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
This makes it easier to get the kops-controller logs from e2e tests since they [only dump logs](https://github.com/kubernetes/test-infra/blob/ec0fe6bd3603dd927cced9b398a8b3a951ab1157/kubetest/dump.go#L50-L74) from systemd services and /var/log files.
This is a bit different than the other components that we log to the host for... others are static pods that are ran on every master (or every node in the case of kube-proxy) but this is a deployment, so the log file will only be present on the master that happens to have the pod scheduled.
=> Enable host logging for kops-controller

upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template, upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
Latest changes broke the weave manifests https://github.com/kubernetes/kops/pull/8216#pullrequestreview-340786303:
`unable to parse quantity's suffix, error found in #10 byte of ...|y":"200mi"}`
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-weave/1214998660220194818/artifacts/ip-172-20-50-49.sa-east-1.compute.internal/protokube.log
=> Fix unit name for memory request for weave

nodeup/pkg/model/miscutils.go
Periodic e2e tests are failing for both CentOS 7 and RHEL 8 because of missing `wget` and `nfs-utils` deps.
Debian family usually has `wget` already installed and Kops adds `nfs-common` alternative to utils already.
`nfs-utils` is required for NFS mounts to work in general, not just for e2e.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-imagecentos7/1214370995477942272
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-containerd/1214741461090701315
=> Add wget and nfs-utils deps needed for e2e tests

nodeup/pkg/model/containerd.go
Pigz is an optional dependency that makes container image decompression faster in some cases.
On RHEL 7 it fails to install being part of the "extras" repo. This makes RHEL 7 e2e to fail:
https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-aws-rhel-7
A more elegant will be to handle this dependency in a `packages.go` later:
https://github.com/kubernetes/kops/pull/8199/files#diff-a0fc0755ee3c8b91f928e7c0c517d906
=> Remove "pigz" containerd dependency for RHEL/CentOS 7

pkg/model/bootstrapscript.go
The "export xx=xxx" statements are added to user data scripts.
But when reading environment variables from `map[string]string`, the sequence is not stable, this will result unnecessary changes to user data in launch configuration.
By sorting the keys in this environment variables map, we can make the "export xx=xxx" statements stable.
=> Stabilize sequence of "export xx=xxx" statements

Makefile, images/BUILD.bazel
We were previously building it in development using bazel, but then
using go build for the release.  That is risky, better to just use
bazel everywhere.
=> Build dns-controller using bazel

permalinks/upgrade_k8s.md, upup/pkg/fi/cloudup/apply_cluster.go
Cherry pick of #8176 on release-1.17.
#8176: Add deprecation warning for older k8s versions
also cherry picks a typo fix in #8209
=> Automated cherry pick of #8176 and #8209: Add deprecation warning for older k8s versions

upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
kops-controller now runs as a DaemonSet. The migration was first made in 1.16.0-alpha.1, so that means 2 releases have been out that set the replicas to zero.
This removal negatively impacts anyone that created a cluster from kops HEAD between 1.15.0 and 1.16.0-alpha.1, and then upgraded kops directly to the 1.16.0 release that includes this commit, without having first upgraded to either of the alphas.
That seems like a reasonably small enough audience that this is safe to remove now.
Perhaps we mention in the release notes that anyone using HEAD or one of the alpha releases needs to `kubectl delete -n kube-system deployment kops-controller`
I'll add a release note in a separate PR since the release note wont get cherry-picked back to 1.16.
We'll also need to add a way to provide an iam …
=> Remove kops-controller deployment

upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #8273 on release-1.17.
#8273: Remove kops-controller deployment
=> Automated cherry pick of #8273: Remove kops-controller deployment

docs/architecture/kops-controller.md, docs/releases/1.16-NOTES.md, docs/releases/1.17-NOTES.md, docs/releases/1.18-NOTES.md
This is a followup to #8273. I guessed at the exact release names for the next 1.16 and 1.17 releases but we can adjust those if necessary.
=> Add release notes for deleting the kops-controller deployment

pkg/model/components/etcdmanager/model.go, pkg/model/components/etcdmanager/model_test.go, pkg/model/components/etcdmanager/tests/minimal/tasks.yaml, pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/cluster.yaml, pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml, pkg/model/context.go
With etcd-manager the DNS names should only be used by the
etcd-manager pod itself, so we don't need to share /etc/hosts with the
host.
By not sharing we avoid:
(1) the temptation to address etcd directly
(2) problems of concurrent updates to /etc/hosts being hard from within a container (because locking is difficult across bind mounts)
Introducing with kubernetes 1.17 to avoid changing behavior of existing versions.
=> Don't share /etc/hosts when using etcd-manager

nodeup/pkg/model/context.go
Rather than remapping the cni-bin to /home/kubernetes/bin, which then
requires us to change the CNI manifests also to write to the new
location, we can instead bind mount /opt/cni/bin so that it is
writeable.
=> Use /opt/cni/bin on all distros (including COS)

pkg/commands/set_cluster.go
This will more easily allow our end-to-end testing to use CoreDNS rather than KubeDNS
`--override spec.kubeDNS.provider=CoreDNS`
Using kubetest's [--kops-overrides flag](https://github.com/kubernetes/test-infra/blob/master/kubetest/kops.go#L74)
=> Allow CoreDNS to be specified by create cluster overrides

cmd/kops/integration_test.go, pkg/model/bootstrapscript.go, tests/integration/update_cluster/private-shared-subnet/kubernetes.tf, tests/integration/update_cluster/privatecalico/cloudformation.json, tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml, tests/integration/update_cluster/privatecalico/kubernetes.tf, tests/integration/update_cluster/privatecanal/kubernetes.tf, tests/integration/update_cluster/privatedns1/kubernetes.tf, tests/integration/update_cluster/privatedns2/kubernetes.tf, tests/integration/update_cluster/privateflannel/kubernetes.tf, tests/integration/update_cluster/privatekopeio/kubernetes.tf, tests/integration/update_cluster/privateweave/kubernetes.tf, tests/integration/update_cluster/unmanaged/kubernetes.tf
This PR consistenly add user-data to the bastion instance even if there is no user-data (in this case, an empty user-data is set).
fix #8330
=> Allow removed of additionalUserData on bastion

docs/operations/etcd_backup_restore_encryption.md
This PR adds more steps to properly restore an etcd cluster using etcd-manager.
We faced this problem yesterday. When we do the restore, the backup brings back the old master endpoints. I thought the flag `--endpoint-reconciler-type` should get rid of it but doesn't.
In order to bring back the stability of our cluster we had to take these actions after the restore.
=> docs(docs/operations) Adding more steps to etcd-manager restore operation to work properly

cmd/kops/integration_test.go, docs/cluster_spec.md, pkg/apis/kops/cluster.go, pkg/apis/kops/v1alpha1/cluster.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/cluster.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go, pkg/model/awsmodel/autoscalinggroup.go, pkg/model/context.go, pkg/model/names.go, pkg/model/sshkey.go, protokube/pkg/gossip/mesh/mesh.pb.go, tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json, tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/nosshkey-cloudformation/in-v1alpha2.yaml, tests/integration/update_cluster/nosshkey/in-v1alpha2.yaml, tests/integration/update_cluster/nosshkey/kubernetes.tf, upup/pkg/fi/cloudup/apply_cluster.go, upup/pkg/fi/cloudup/awstasks/BUILD.bazel, upup/pkg/fi/cloudup/awstasks/launchconfiguration.go, upup/pkg/fi/cloudup/awstasks/sshkey.go
Exposes configuration to allow a user to not specify an SSH key on an instance by setting `sshKeyName: ""`.
[Docs](https://github.kdc.capitalone.com/identity-sre/kops/pull/4)
=> Configuration to specify no SSH key

pkg/instancegroups/rollingupdate_test.go
Cherry pick of #8139 on release-1.17.
#8139: tests: increase timeout in rolling update tests
=> Automated cherry pick of #8139: tests: increase timeout in rolling update tests

Makefile
/kind bug
`make crossbuild-nodeup-in-docker` was missing necessary changes made to `crossbuild-in-docker`.
=> Fix crossbuild-nodeup-in-docker

Makefile
Cherry pick of #8343 on release-1.17.
#8343: Fix crossbuild-nodeup-in-docker
=> Automated cherry pick of #8343: Fix crossbuild-nodeup-in-docker

docs/operations/images.md
Our CentOS 7 e2e job has been failing for a long time: https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-aws-centos-7
due to the AMI's lack of ENA/NVMe support and our tests defaulting to m5.large for the masters. This caused the masters to never launch, which means prow couldn't even get job artifacts from the master instances.
[I updated the AMI in the e2e job](https://github.com/kubernetes/test-infra/pull/15928) and it appears to be successfully launching the cluster (still experiencing aws volume flakes though).
This updates our docs to match the new AMI ID. While the centos website is not up to date, this AMI ID can be found with the documented aws cli query.
=> Update CentOS 7 AMI

nodeup/pkg/model/kubelet.go
Ubuntu 18.04 (Bionic) periodic e2e is failing. Seems to be related to DNS issues:
https://github.com/coredns/coredns/blob/master/plugin/loop/README.md#troubleshooting-loops-in-kubernetes-clusters
=> Fix DNS loop on Ubuntu 18.04 (Bionic)

docs/networking.md, k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/cluster.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Closes #7390
References Weaveworks/Weave#3683
This change is excluded from k8s-1.6.yaml.template as this environmental variable is only effective on Weave 2.6.0 and above.
=> Add support for weave.npcExtraArgs

nodeup/pkg/model/directories.go
Using the same approach we're doing for /opt/kops
=> Make /opt/cni/bin writeable on COS

OWNERS
Cherry pick of #7983 on release-1.16.
#7983: Promote peter & ryan & zetaab to approvers
=> Automated cherry pick of #7983: Promote peter & ryan & zetaab to approvers

tests/integration/update_cluster/additional_cidr/kubernetes.tf, tests/integration/update_cluster/api_elb_cross_zone/kubernetes.tf, tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf, tests/integration/update_cluster/complex/kubernetes.tf, tests/integration/update_cluster/existing_iam/kubernetes.tf, tests/integration/update_cluster/existing_iam_cloudformation/kubernetes.tf, tests/integration/update_cluster/existing_sg/kubernetes.tf, tests/integration/update_cluster/externallb/kubernetes.tf, tests/integration/update_cluster/ha/kubernetes.tf, tests/integration/update_cluster/lifecycle_phases/network-kubernetes.tf, tests/integration/update_cluster/minimal-141/kubernetes.tf, tests/integration/update_cluster/minimal/kubernetes.tf, tests/integration/update_cluster/mixed_instances/kubernetes.tf, tests/integration/update_cluster/mixed_instances_spot/kubernetes.tf, tests/integration/update_cluster/nosshkey/kubernetes.tf, tests/integration/update_cluster/privatecalico/kubernetes.tf, tests/integration/update_cluster/privatecanal/kubernetes.tf, tests/integration/update_cluster/privatedns1/kubernetes.tf, tests/integration/update_cluster/privatedns2/kubernetes.tf, tests/integration/update_cluster/privateflannel/kubernetes.tf, tests/integration/update_cluster/privatekopeio/kubernetes.tf, tests/integration/update_cluster/privateweave/kubernetes.tf, tests/integration/update_cluster/restrict_access/kubernetes.tf, tests/integration/update_cluster/shared_vpc/kubernetes.tf, upup/pkg/fi/cloudup/awstasks/route.go, upup/pkg/fi/cloudup/awstasks/vpccidrblock.go
See #7052 for additional details.
According to the [Terraform 0.12 upgrade guide](https://www.terraform.io/upgrade-guides/0-12.html) resource names cannot start with digits. Currently both routes and VPC CIDR associations start with digits, so this adds prefixes to them so that they are valid resource identifiers in 0.12.
This is a significant change because on its own, terraform will destroy and recreate the route which impact the cluster networking. To avoid this, existing clusters this will require moving the resources within the terraform state prior to the next `apply`.
```
kops update cluster --target terraform --out ./
terraform state mv aws_route.0-0-0-0--0 aws_route.route-0-0-0-0--0
terraform plan
terraform apply
```
The exact terraform state command may vary depending on how …
=> Update Terraform resource names to be 0.12 compatible.

tests/integration/update_cluster/additional_cidr/kubernetes.tf, tests/integration/update_cluster/api_elb_cross_zone/kubernetes.tf, tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf, tests/integration/update_cluster/complex/kubernetes.tf, tests/integration/update_cluster/existing_iam/kubernetes.tf, tests/integration/update_cluster/existing_iam_cloudformation/kubernetes.tf, tests/integration/update_cluster/existing_sg/kubernetes.tf, tests/integration/update_cluster/externallb/kubernetes.tf, tests/integration/update_cluster/ha/kubernetes.tf, tests/integration/update_cluster/lifecycle_phases/network-kubernetes.tf, tests/integration/update_cluster/minimal-141/kubernetes.tf, tests/integration/update_cluster/minimal/kubernetes.tf, tests/integration/update_cluster/mixed_instances/kubernetes.tf, tests/integration/update_cluster/mixed_instances_spot/kubernetes.tf, tests/integration/update_cluster/nosshkey/kubernetes.tf, tests/integration/update_cluster/privatecalico/kubernetes.tf, tests/integration/update_cluster/privatecanal/kubernetes.tf, tests/integration/update_cluster/privatedns1/kubernetes.tf, tests/integration/update_cluster/privatedns2/kubernetes.tf, tests/integration/update_cluster/privateflannel/kubernetes.tf, tests/integration/update_cluster/privatekopeio/kubernetes.tf, tests/integration/update_cluster/privateweave/kubernetes.tf, tests/integration/update_cluster/restrict_access/kubernetes.tf, tests/integration/update_cluster/shared_vpc/kubernetes.tf, upup/pkg/fi/cloudup/awstasks/route.go, upup/pkg/fi/cloudup/awstasks/vpccidrblock.go
Cherry pick of #7957 on release-1.17.
#7957: Update terraform resource names to be 0.12 compatible.
[as discussed](https://github.com/kubernetes/kops/pull/7957#issuecomment-575598054) this will target 1.17.
=> Automated cherry pick of #7957: Update terraform resource names to be 0.12 compatible.

nodeup/pkg/model/BUILD.bazel, nodeup/pkg/model/containerd_test.go, nodeup/pkg/model/docker.go, nodeup/pkg/model/docker_test.go, upup/pkg/fi/nodeup/nodetasks/package.go
Extend the existing "unit" test to check package versions, because
some of the docker packages now have a '5:' prefix.
=> Test package versions as well as hashes

channels/alpha
* Add 1.16, 1.17 images with correct docker versions (cf
https://github.com/kubernetes-sigs/image-builder/pull/127)
* Regular package updates on other stretch images
=> Publish update AMIs into the alpha channel

docs/state.md, util/pkg/vfs/vfs.go
Allows the usage of state storage based on the local filesystem, based on the `file://` prefix/protocol, as [documented](https://github.com/kubernetes/kops/blob/master/docs/state.md).
Fixes [#6463](https://github.com/kubernetes/kops/issues/6463).
=> Allow local filesystem state stores (to aid CI pull-request workflows)

docs/architecture/kops-controller.md, docs/releases/1.16-NOTES.md
Cherry pick of #8321 on release-1.16.
#8321: Add release notes for deleting the kops-controller deployment
=> Automated cherry pick of #8321: Add release notes for deleting the kops-controller deployment

docs/releases/1.17-NOTES.md, docs/releases/1.18-NOTES.md
Followup to https://github.com/kubernetes/kops/pull/7957
/cc @mccare since you're involved with the terraform 0.12 upgrade work as well.
=> Add release notes for terraform resource renaming

cmd/kops/util/factory.go
As discussed during office hours today. This already requires users to opt-in so they should already know what they're doing, but just in case we print this warning.
```
KOPS_STATE_STORE=file://$(pwd)/state kops update cluster foo.k8s.local
W0117 16:44:05.081437   92040 factory.go:122] The local filesystem state store is not functional for running clusters
I0117 16:44:15.092092   92040 executor.go:103] Tasks: 0 done / 137 total; 55 can run
I0117 16:44:16.268684   92040 executor.go:103] Tasks: 55 done / 137 total; 33 can run
...
```
This warning is printed on all kops commands that utilize the state store (`replace`, `update`, etc.)
=> Add a warning when using file:// state store

cmd/kops/util/factory.go, docs/state.md, util/pkg/vfs/vfs.go
Cherry pick of #6465 #8368 on release-1.17.
#6465: Allow local filesystem state stores
#8368: Add a warning when using file:// state store
=> Automated cherry pick of #6465: Allow local filesystem state stores #8368: Add a warning when using file:// state store

docs/releases/1.18-NOTES.md, upup/pkg/fi/cloudup/awsup/aws_cloud.go
While doing the setup for some e2e I noticed that Kops has still defaults to some quite old types of instances. Any reason for not changing to *c5*, *t3*? These should be cheaper and faster.
```
t3.medium - $0.041600 hourly
t2.medium - $0.046400 hourly
c5.large  - $0.085000 hourly
c4.large  - $0.100000 hourly
```
PS: m3.medium is so old that it becomes irrelevant.
=> Update default instance types for AWS

upup/pkg/fi/cloudup/apply_cluster.go
Bump the Lyft CNI to the latest v.0.5.3. This adds support for more instance families and types.
=> Update lyft CNI to v0.5.3

docs/releases/1.18-NOTES.md, upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
Currently, Kops is not able to start a basic cluster with Kubernetes < 1.12 for a few reasons:
* PodPriority feature gate is needed for various manifests with Kubernetes < 1.11
* the kube-dns manifest cannot be applied because of an empty resource `{}`
=> Fix issues with older versions of k8s for basic clusters

upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
Cherry pick of #8248 on release-1.17.
#8248: Fix issues with older versions of k8s for basic clusters
=> Automated cherry pick of #8248: Fix issues with older versions of k8s for basic clusters

docs/releases/1.15-NOTES.md, docs/releases/1.16-NOTES.md
Cherry pick of #8378 on release-1.16.
#8378: Backport the k8s 1.9 required action release note
=> Automated cherry pick of #8378: Backport the k8s 1.9 required action release note

docs/releases/1.13-NOTES.md, docs/releases/1.14-NOTES.md, docs/releases/1.15-NOTES.md, docs/releases/1.9-NOTES.md
View these four documents : docs/releases/1.13-NOTES.md，docs/releases/1.14-NOTES.md，docs/releases/1.15-NOTES.md，docs/releases/1.9-NOTES.md，which contain 4 pr :  https://github.com/kubernetes/kops/pull/7191,https://github.com/kubernetes/kops/pull/6897,https://github.com/kubernetes/kops/pull/6897,https://github.com/kubernetes/kops/pull/3941, these 4 pr  contains one deleted user：vainu-arto，whose link is ready to use ghost instead. This can improve the user experience
=> Change the deleted user to ghost

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
This may have dropped out when we bumped Cilium to 1.6
It is possible to set this value in the cluster spec, but it isn't used anywhere
=> Add Cilium.EnablePolicy back into templates

pkg/model/iam/iam_builder.go
fixes #8359 upstream
Tested in us-gov-west-1 zone with the following
```
$ ./kops create cluster --image=${AMI_NAME} --dns=private --zones=us-gov-west-1a --name=${CLUSTER_NAME}
$ ./kops update cluster ${CLUSTER_NAME} --yes
I0117 13:59:21.485847   14570 dns.go:94] Private DNS: skipping DNS validation
I0117 13:59:22.071985   14570 executor.go:103] Tasks: 0 done / 87 total; 44 can run
I0117 13:59:22.751585   14570 vfs_castore.go:675] Issuing new certificate: "apiserver-aggregator-ca"
I0117 13:59:22.828018   14570 vfs_castore.go:675] Issuing new certificate: "etcd-peers-ca-main"
I0117 13:59:22.830881   14570 vfs_castore.go:675] Issuing new certificate: "ca"
I0117 13:59:22.835241   14570 vfs_castore.go:675] Issuing new certificate: "etcd-manager-ca-main"
I0117 13:59:22.911223   14570 …
```
=> Use IAMPrefix() for hostedzone

nodeup/pkg/model/kube_scheduler.go
`--policy-configmap` and `--policy-configmap-namespace` were added as one string. The result spec is:
```yaml
spec:
containers:
- args:
- --kubeconfig=/var/lib/kube-scheduler/kubeconfig
- --leader-elect=true
- --policy-configmap=scheduler-policy --policy-configmap-namespace=kube-system
- --v=2
- --logtostderr=false
- --alsologtostderr
- --log-file=/var/log/kube-scheduler.log
```
It leads to an error: `couldn't get policy config map kube-system/scheduler-policy --policy-configmap-namespace=kube-system: configmaps "scheduler-policy --policy-configmap-namespace=kube-system" not found`
The spec should be
```
spec:
containers:
- args:
- --kubeconfig=/var/lib/kube-scheduler/kubeconfig
- --leader-elect=true
- --policy-configmap=scheduler-policy
- --policy-configmap-namespace=kube-system
- --v=2 …
```
=> Fix scheduler policy configmap args

nodeup/pkg/model/kube_scheduler.go
Cherry pick of #8386 on release-1.16.
#8386: Fix scheduler policy configmap args
=> Automated cherry pick of #8386: Fix scheduler policy configmap args

pkg/model/iam/iam_builder.go
Cherry pick of #8366 on release-1.17.
#8366: use IAMPrefix() for hostedzone
=> Automated cherry pick of #8366: use IAMPrefix() for hostedzone

channels/alpha, channels/stable
Bumping alpha channel k8s versions to stable. They have been sitting in alpha for quite some time now.
Also bumping k8s in the alpha channels to the recently released ones.
=> Bump k8s versions in alpha and stable channels

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #8379 on release-1.17.
#8379: Add Cilium.EnablePolicy back into templates
=> Automated cherry pick of #8379: Add Cilium.EnablePolicy back into templates

Makefile, nodeup/pkg/distros/identify.go, nodeup/pkg/model/containerd.go, nodeup/pkg/model/convenience.go, nodeup/pkg/model/docker.go, nodeup/pkg/model/miscutils.go, nodeup/pkg/model/packages.go, nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml, upup/pkg/fi/nodeup/nodetasks/archive.go, upup/pkg/fi/nodeup/nodetasks/package.go
Each containerd release comes with a tar.gz that can be used to install it with minimal effort.
Ref: https://github.com/kubernetes/kops/pull/7986#discussion_r357925711
Summary of changes:
* Archive task will extract each required file to the desired location - easier to control what goes where, but may need versioning in the future
* the package contains static binaries, so no need to provide a distro like with each rpm/deb
* having a single package means dependencies need to go to Packages
* support for CentOS should be much simpler now that `container-selinux` is installed from repo and not vault (vault package is still needed for RHEL and Amazon Linux)
**PS1**: Docker could get some similar upgrade by moving the deps to Packages and would open the way to multi-arch.
**PS2**: Amazon …
=> containerd: Add support for tar.gz package

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Also updates the default Corefile config to make use of the new lameduck functionality for healthcheck: https://coredns.io/plugins/health/ as per kubeADM: https://github.com/kubernetes/kubernetes/pull/86260/file
Builds on top of the work done by @michalschott in #7883 however updates the image for all clusters.
Resolves #8332 
Resolves #8309
=> CoreDNS default image bump to 1.6.6 to resolve CVE

pkg/model/components/etcd.go, pkg/model/components/etcdmanager/model.go, pkg/model/components/etcdmanager/options.go, pkg/model/components/etcdmanager/tests/minimal/tasks.yaml, pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml, pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Signed-off-by: mmerrill3 <michael.merrill@vonage.com>
Enable etcdManager version 3.0.20200116 for etcd 3.4.3 access.  This is used by default for k8s 1.17.  Fixes #8310.
=> Bump etcd-manager to 3.0.20200116 (#8310)

upup/pkg/fi/nodeup/command.go
/kind bug
6d0133698d82f578b1a0e78f1dca444ed77cb4d5 stopped generating the "calico-client" keypair and certificate when the CNI was set to Cilium, as the new version of Cilium no longer needed to use the apiserver's etcd cluster. Unfortunately, it failed to stop adding the EtcdTLSBuilder in that case. The result of this is that if the cluster is not using etcd-manager and has etcd TLS enabled, masters will fail to come up looking for "calico-client" certificates that don't exist.
=> Don't load nonexistent calico-client cert when CNI is Cilium

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #8333 on release-1.17.
#8333: CoreDNS default image bump to 1.6.6
=> Automated cherry pick of #8333: CoreDNS default image bump to 1.6.6

Makefile
I noticed this while investigating #8371 and there have been other reports of issues when trying to import kops with go modules (I can't find the GH issues at the moment)
[Go modules require the v prefix](https://github.com/golang/go/wiki/Modules#modules), and [k/k also tags with the v prefix](https://github.com/kubernetes/kubernetes/releases/tag/v1.17.0).
We have some inconsistent tags already, for 1.11.0 we have tags of both `1.11.0` and `v1.11.0` which is the most recent tag with the prefix.
This is also why 1.11.0 is the default version imported by `go get`:
```
go get -v k8s.io/kops
go: downloading k8s.io/kops v1.11.0
```
and the latest version in `go list`:
```
go list -m -versions k8s.io/kops
k8s.io/kops v1.4.0-alpha.1 v1.4.0 v1.4.1 v1.4.2 v1.4.3 v1.4.4 v1.10.0 v1.11.0
```
I'm …
=> Kops releases - prefix git tags with v

upup/pkg/fi/nodeup/command.go
Cherry pick of #8338 on release-1.15.
#8338: Don't load nonexistent calico-client cert when CNI is Cilium
=> Automated cherry pick of #8338: Don't load nonexistent calico-client cert when CNI is Cilium

Makefile
Cherry pick of #8373 on release-1.16.
#8373: Prefix git tags with `v`
=> Automated cherry pick of #8373: Prefix git tags with `v`

cmd/kops/toolbox_template.go
This commit will allow you to define clusterName from the template's values file.
Before that our clusterName value would be overriden by the cli flag ( whether defined or not ).
Now we have an approach where if the value is defined, it will have priority over the cli flag.
This commit will also align with the official documentation under https://github.com/kubernetes/kops/blob/master/docs/cluster_template.md
=> Fix template clusterName behavior

nodeup/pkg/distros/distribution.go, nodeup/pkg/distros/identify.go, nodeup/pkg/model/containerd.go, nodeup/pkg/model/docker.go, nodeup/pkg/model/packages.go, pkg/model/components/containerd.go, pkg/resources/aws/aws.go, upup/pkg/fi/cloudup/awsup/aws_cloud.go
Amazon Linux 2 support is broken with Docker packages for CentOS, because of the missing `container-selinux` dependency. Even if this is added from the CentOS repo, it is missing its own dependencies. Sadly, this is not something that can be easily fixed.
The good news is that Amazon Linux 2 has SELinux disabled by default, so the `container-selinux` package is not needed. Static binaries for containerd or Docker should run just fine.
#8199 adds support for static binaries for latest containerd and can be used to setup a Kubernetes cluster on Amazon Linux 2 with minor changes.
This PR adds the following changes:
* separates Amazon Linux from CentOS and RHEL to not require installing `container-selinux`
* updates default containerd version to 1.3.2 (noting to worry, this is targeted for …
=> Update support for Amazon Linux 2

docs/releases/1.16-NOTES.md
Cherry pick of #8064 on release-1.16.
#8064: Announce removal of kops/v1alpha1 in kops 1.18
=> Automated cherry pick of #8064: Announce removal of kops/v1alpha1 in kops 1.18

nodeup/pkg/model/kube_scheduler.go
As mentioned in https://github.com/kubernetes/kops/pull/8407, this change makes the feature available from kubernetes 1.12 and newer due to incompatibility with 1.11
=> Fixes regression in e2e tests

pkg/model/components/etcdmanager/BUILD.bazel, pkg/model/components/etcdmanager/model.go, pkg/model/master_volumes.go
Cherry pick of #8016 on release-1.17.
#8016: Alicloud: etcd-manager support
=> Automated cherry pick of #8016: Alicloud: etcd-manager support

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This PR updates CoreDNS to 1.6.7 where they restore metrics on cache miss for the cache pluging as per https://github.com/coredns/coredns/pull/3578
=> Update coredns to 1.6.7

util/pkg/vfs/BUILD.bazel, util/pkg/vfs/osscontext.go
Cherry pick of #8025 on release-1.17.
#8025: Alicloud: allow use RAM role for OSS client
=> Automated cherry pick of #8025: Alicloud: allow use RAM role for OSS client

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #8452 on release-1.16.
#8452: Update coredns to 1.6.7
=> Automated cherry pick of #8452: Update coredns to 1.6.7

README-ES.md, README.md, dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/clouddns.go, dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go, dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/clouddns.go, docs/README.md, docs/cluster_spec.md, docs/index.md, docs/manifests_and_customizing_via_api.md, docs/state.md, mkdocs.yml, nodeup/pkg/model/kube_proxy_test.go
[pkg.go.dev will soon replace godoc.org](https://blog.golang.org/pkg.go.dev-2020). The main advantage of pkg.go.dev is that it is module-aware and version-aware, so one can view documentation for previous kops versions.
The only remaining references to godoc.org are these status widgets, which I dont believe are yet supported on pkg.go.dev:
```
grep -r godoc.org . | grep -v vendor
./docs/index.md:[GoDoc Widget]: https://godoc.org/k8s.io/kops?status.svg
./README.md:[GoDoc Widget]: https://godoc.org/k8s.io/kops?status.svg
./README-ES.md:[GoDoc Widget]: https://godoc.org/k8s.io/kops?status.svg
``` 
fixes #8371
=> Update godoc.org references to use pkg.go.dev

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
In the course of debugging [this Cilium Garbage Collection Issue](https://github.com/cilium/cilium/issues/9805) it was noted that the default templates used for the `cilium-operator` `Deployment` were missing the `--identity-allocation-mode` argument.
The default configuration assumes that the Cilium version is > `1.6` with CRD backed identity management and as such the operator deployment should launch with the correct arguments for CRD-backed identity management.
=> Cilium - Add missing Identity Allocation Mode to Operator Template

cmd/kops-controller/BUILD.bazel, dns-controller/cmd/dns-controller/BUILD.bazel, hack/.packages, nodeup/pkg/model/BUILD.bazel, nodeup/pkg/model/kube_apiserver.go, nodeup/pkg/model/logrotate.go, pkg/wellknownusers/BUILD.bazel, pkg/wellknownusers/wellknownusers.go, upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/template_functions.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Writing to a hostPath from a non-root container requires file
ownership changes, which is difficult to roll out today.  See
discussion in #8454
We were primarily using the logfile for e2e diagnostics, so we're
going to look into collecting the information via other means instead.
We also haven't yet shipped this logfile in a released version (though
we have shipped it in beta releases)
=> Stop logging to /var/log/kops-controller.log

docs/cluster_spec.md
Fix simple typos in cluster_spec.md.
1: vigiliant  -> vigilant
2: alernative -> alternative
=> Fix typos in cluster_spec.md

tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml, tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml, tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml, tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml, tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml, tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml, upup/pkg/fi/cloudup/urls.go
Currently this generates:
```
NODEUP_URL=https://artifacts.k8s.io/binaries/kops/1.15.1/linux/amd64/nodeup,https://github.com/kubernetes/kops/releases/download/1.15.1/linux-amd64-nodeup,https://kubeupv2.s3.amazonaws.com/kops/1.15.1/linux/amd64/nodeup
NODEUP_HASH=de4939eadb6e4d89fcf608b1f632e770bcce521d6dc5c45d76d2c4608ad23db4
```
However for the Github URL a `v` is missing in front of the version tag.
Returns a 404:
```
curl https://github.com/kubernetes/kops/releases/download/1.15.1/linux-amd64-nodeup
```
Downloads the file:
```
curl https://github.com/kubernetes/kops/releases/download/v1.15.1/linux-amd64-nodeup
```
=> Fix Github download url for nodeup

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
Another bug in the new templates is the loss of prometheus metrics.
Since there are more cilium components involved here, the old config param didn't make that much sense anymore, so I rewrote that part.
Since the property is removed, this sort of breaks BC, but nothing would have happened for those that did so no loss of functionality. 
/kind bug
=> Make it possible to enable Prometheus metrics for Cilium

pkg/acls/gce/BUILD.bazel, pkg/acls/gce/storage.go
This means we won't be able to work unless there's a bucket permission
(which actually will typically happen if the state store is in the
same GCS project).
This is the minimal workaround for cherry-picking.
=> GCS: Don't try to set ACLs if bucket-policy only is set

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #8445 on release-1.17.
#8445: Cilium - Add missing Identity Allocation Mode to Operator
=> Automated cherry pick of #8445: Cilium - Add missing Identity Allocation Mode to Operator

util/pkg/vfs/gsfs.go
We were recomputing the MD5, but we would need to rewind the stream first.
=> GCS: Fix bug where around retry on GCS

util/pkg/vfs/gsfs.go
We log at V(4) because they are fairly verbose.
=> GCS: Log ACLs if we're writing them

nodeup/pkg/model/containerd.go, pkg/model/components/containerd.go
containerd v1.3.3 uses runc v1.0.0-rc10 which should fix some of the flakes we see in e2e:
https://github.com/containerd/containerd/pull/3973
=> Add support for containerd v1.3.3

nodeup/pkg/model/directories.go
Without this, a reboot on COS does not remount /home/kubernetes/bin with exec permission.
=> Use BindMount task for /home/kubernetes/bin

k8s/crds/kops_v1alpha2_cluster.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
Cherry pick of #8433 on release-1.15.
#8433: Make it possible to enable Prometheus metrics for Cilium
=> Automated cherry pick of #8433: Make it possible to enable Prometheus metrics for Cilium

pkg/apis/kops/networking.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #8484 on release-1.16.
#8484: Update cilium to 1.6.6
=> Automated cherry pick of #8484: Update cilium to 1.6.6

tools/get_workspace_status.sh
The [image pushing postsubmit job](https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-postsubmit-push-to-staging) is one step closer to succeeding! It recognizes the cloudbuild.yaml file in the repo root and is able to call `make kops-controller-push`
It currently fails because when the builder image uploads the kops directory to GCS for to be consumed by GCB, it [excludes the .git directory](https://github.com/kubernetes/test-infra/blob/18391d89866518581e4b6de2546e16ba2b08a3be/images/builder/main.go#L87).
This causes the job to fail because `make kops-controller-push` [uses bazel which runs get_workspace_status.sh](https://github.com/kubernetes/kops/blob/b1276ac8353279c2d1de7beea4e6ec3713d83f6c/tools/bazel.rc#L10) which aborts if the git commands fail.
The prow job doesnt contain …
=> Image Pushing - Remove .git dependency from get_workspace_status.sh

cloudbuild.yaml
Using [this reference](https://cloud.google.com/cloud-build/docs/build-config#options)
As mentioned here: https://github.com/kubernetes/kops/pull/8518#issuecomment-584356896  our postsubmit builds are now timing out because we're building more artifacts: https://storage.googleapis.com/kubernetes-jenkins/logs/kops-postsubmit-push-to-staging/1226925957785325568/artifacts/build.log
We'll see if increasing the CPU resources available will be enough to avoid the timeout.  Otherwise it looks like there are [timeout fields](https://cloud.google.com/cloud-build/docs/build-config#timeout_2) available both at the build and step levels that we could try increasing too.
=> Use larger machine type for cloudbuild jobs

upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
for the benefit of admission controllers that restrict this sort of thing.
=> Mark dns-controller and kops-controller as non-root

pkg/model/alimodel/scalinggroup.go, upup/pkg/fi/cloudup/alitasks/BUILD.bazel, upup/pkg/fi/cloudup/alitasks/launchconfiguration.go, upup/pkg/fi/cloudup/aliup/ali_cloud.go
This PR enables kops to do modification to LaunchConfiguration to Alicloud ESS.
Changes:
- create new LaunchConfiguration with timestamp just like how we deal to AWS AutoScalingGroup configuration if there are changes
- only keep 3 latest LaunchConfiguration by default
- implement DeleteInstance for Alicloud
=> Alicloud: support modification of LaunchConfiguration

upup/pkg/fi/cloudup/awsup/machine_types.go
I'm not sure why this changed in https://github.com/kubernetes/kops/pull/8128 but I'm going to look into modernizing this with the new api soon.
=> Fix Machine types vcpus

upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
[Release Notes](https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.5.0)
I merged changes from these manifests:
* https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/v0.5.0/deploy/example.yaml
* https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/v0.5.0/deploy/iamidentitymapping.yaml
The new version supports replacing the ConfigMap with an IAMIdentityMapping custom resource, but the `--backend-mode` command argument isnt yet exposed through the kops API, so it will still only use configmaps. We can expose a BackendMode API field in a followup PR.
Since I know you also use it...
/cc @rdrgmnzs
=> Update AWS IAM Authenticator to 0.5.0

channels/alpha
- https://groups.google.com/d/msg/kubernetes-announce/o_oUaH7JnRo/kJjnl3EzBAAJ
- https://groups.google.com/d/msg/kubernetes-announce/rto2-YTCbmY/vlXj3UkzBAAJ
- https://groups.google.com/d/msg/kubernetes-announce/Ueq048X3YuA/84Kd_SMzBAAJ
the stable channel already done in https://github.com/kubernetes/kops/pull/8489
=> channels: bump k8s versions after feb. patch releases

upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
I noticed in our new kops-controller logs that there is a permission denied error at startup.
Apparently part of the leader election process involves creating and watching for events off of the kops-controller-leader configmap. This will add the necessary permissions to silence this error.
See:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/1227728236914413570/artifacts/ip-172-20-46-137.ap-northeast-2.compute.internal/kops-controller-6k9sz.log
https://github.com/kubernetes-sigs/controller-runtime/blob/b97ebda47ef9f73d7743cba9e354157b16757057/pkg/internal/recorder/recorder.go#L49-L53
=> Add events RBAC permissions to kops-controller

upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #8535 on release-1.17.
#8535: Add events RBAC permissions to kops-controller
=> Automated cherry pick of #8535: Add events RBAC permissions to kops-controller

nodeup/pkg/model/kubelet.go
Cherry pick of #8353 on release-1.17.
#8353: Fix DNS loop on Ubuntu 18.04 (Bionic)
=> Automated cherry pick of #8353: Fix DNS loop on Ubuntu 18.04 (Bionic)

upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #8423 on release-1.16.
#8423: Update AWS IAM Authenticator to 0.5.0
=> Automated cherry pick of #8423: Update AWS IAM Authenticator to 0.5.0

pkg/apis/kops/validation/legacy.go, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cilium is capable of fully replacing kube-proxy by running in NodePort mode.
This PR will prevent kops from installing kube-proxy if NodePort is enabled on the Cilium addon.
This is implemented similar to how kube-proxy is disabled by kube-router. I do wonder if forcing `kubeProxy.enabled=false` would be a bit cleaner than just disabling it implicitly by the `cilium.enableNodePort` setting.
Note: This feature requires kernel version 4.19.57 or later
=> Cilium nodeport

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha2/networking.go, upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Cherry pick of #8538 on release-1.17.
#8538: Update amazon-vpc-cni-k8s to v1.6.0
=> Automated cherry pick of #8538: Update amazon-vpc-cni-k8s to v1.6.0

Makefile
[The tagging of both formats](https://github.com/kubernetes/kops/pull/8373) was cherry-picked back to 1.15 and will be used in 1.16.0 stable.
I think having all 1.16.X and 1.17.X releases tagged with both formats is long enough, so I'm removing the non-prefixed tag for 1.18.0
=> Only create git tags with the v prefix

upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
The authenticator binary uses glog which requires write access to the filesystem under /tmp.
On the scratch image /tmp doesnt exist which caused a crash loop:
```
time="2020-02-14T02:06:00Z" level=info msg="creating event broadcaster"
time="2020-02-14T02:06:00Z" level=info msg="setting up event handlers"
W0214 02:06:00.358119       1 client_config.go:539] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
log: exiting because of error: log: cannot create log: open /tmp/aws-iam-authenticator.ip-X-X-X-X.aws-iam-authenticator.log.WARNING.20200214-020600.1: no such file or directory
```
Switching to debian-stretch fixed the issue although we could realistically use any of the other images in the release [0]
This will need cherry-picking back to …
=> Switch AWS IAM Authenticator to use non-scratch image

upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
Cherry pick of #8555 on release-1.16.
#8555: Switch AWS IAM Authenticator to use non-scratch image
=> Automated cherry pick of #8555: Switch AWS IAM Authenticator to use non-scratch image

Makefile, upup/models/BUILD.bazel
This was a big contributor to the build being non-repeatable.
=> go-bindata: don't store file metadata

Makefile, WORKSPACE, docker/Dockerfile, images/dns-controller-builder/Dockerfile, images/protokube-builder/Dockerfile
k/k is using 1.13.6, and it looks like there are some potentially
relevant fixes in .7 and .8 (particularly on unpatched Windows).
=> Update golang to 1.13.8

k8s/crds/kops.k8s.io_clusters.yaml, nodeup/pkg/model/context.go, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/validation/legacy.go, pkg/model/iam/iam_builder.go, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
With this feature enabled, Cilium will create and allocate ENIs for pods similar to LyftVPC and AmazonVPC.
Marked this as work in progress since there are a couple of other Cilium PRs that should go in first.
=> Cilium eni

upup/pkg/fi/files_owner.go
If the user/group isn't specified, don't try to change it.
=> EnsureFileOwner: cleanup logic

hack/update-header.sh
Avoids discrepancies between developer's laptop and CI verification in the evening of Dec 31.
=> Use UTC when calculating copyright year

Makefile, cmd/kops-controller/BUILD.bazel, dns-controller/cmd/dns-controller/BUILD.bazel
It's cleaner & more consistent.
=> makefile: use more hash helpers when building images

docs/networking.md, docs/releases/1.18-NOTES.md, upup/models/nodeup/resources/_lyft_vpc_cni/files/etc/cni/net.d/10-cni-ipvlan-vpc-k8s.conflist.template, upup/pkg/fi/nodeup/command.go
The Lyft CNI uses tags to determine which subnets to use when allocating new network adapters.
Current default is not matching anything, so the cluster is broken on startup. Using the cluster name for to determine the cluster subnets seems a better solution.
The the `conflist.template` was misaligned so I reformatted it.
=> Use cluster name as default subnet tag for Lyft CNI

upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This reverts these cherry-picks: #8545 #8557 
I'm running into some issues with the new --backend-mode flag and its default values. I'm confident we can fix it in kops 1.17 and 1.18 but I don't want this to hold up the release of 1.16.0 so I'm backing out the changes from release-1.16 only.
=> Revert update of AWS IAM Authenticator to 0.5.0 for 1.16

cloudbuild.yaml
The _GIT_TAG has a prefix vYYYYMMDD, so is not a valid semver.
Instead we use our CI=1 approach to construct a reasonable semver tag.
=> Staging build: don't use _GIT_TAG

Makefile
Now that we're building with CI=1, we should upload to the same
version, rather than reconstructing the logic (and in this case, we
weren't matching).
=> prow-postsubmit: Upload to a consistently named directory

pkg/model/spotinstmodel/OWNERS, pkg/resources/spotinst/OWNERS, upup/pkg/fi/cloudup/spotinsttasks/OWNERS
We propose that we add OWNERS file to Spotinst specific packages in order to decrease the time of development lifecycle (for example, please see the following PRs: #7040, #7252 and #8294), so we can review and approve things ourselves. For now, these files contain only one approver (me), but we will add more contributors later.
=> Spotinst: Add OWNERS file to Spotinst specific packages

pkg/apis/kops/cluster.go, pkg/apis/kops/networking.go, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cilium 1.7 requires K8s 1.12 minimum. Changed the templates so that we
can have different cilium versions for different k8s versions.
This also mean that this addon will behave similar to other addons wrt
upgrades. Cilium used to add a fixed version to the cluster spec on cluster creation so
upgrades were slightly more manual. Now, for new clusters, upgrades will
happen implicitly with kops updates unless the .Version is added
manually to the cluster spec.
=> Bump Cilium to 1.7 for k8s 1.12+

util/pkg/env/standard.go
we are currently seeing following error in etcd-manager:
```
W0220 12:42:07.934295    8002 controller.go:149] unexpected error running etcd cluster reconciliation loop: error refreshing control store after leadership change: error reading s3://xxxx/bbb.k8s.local/backups/etcd/events/control: error listing s3://xxxx/bbb.k8s.local/backups/etcd/events/control: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-north-1'
status code: 400, request id: 9C82F7B26B72D41D, host id: bNWE4d3rO/CnkzlfpTrUcW4LcMdxuBH7M5tY6AmOivMLSvaBqrEc8PpiaOXHDKuBi5jgx6B07Cw=
```
this is because we are using custom s3 credentials and s3 region is not passed to etcd-manager container (so it defaults to us-east-1)
=> add s3 region

pkg/apis/kops/util/BUILD.bazel, pkg/apis/kops/util/labels_test.go
=> Add unit test for pkg/apis/kops/util/labels.go

pkg/validation/validate_cluster.go, pkg/validation/validate_cluster_test.go
This should fix the known cause of cluster validation flapping.
=> Fail cluster validation if a master missing kube-controller-manager

pkg/model/context.go, pkg/model/spotinstmodel/BUILD.bazel, pkg/model/spotinstmodel/instance_group.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
Launch Templates are the recommended way of creating an ASG in AWS and allows specifying various options that are not possible with Launch Configurations.
https://docs.aws.amazon.com/autoscaling/ec2/userguide/LaunchTemplates.html
This is a followup of #8462 with the following improvements:
* adds remaining cloud tags
* checks for changes before applying new tags
This is a bit more complicated as it has to account Launch Configurations, Mixed Instance Policies and Launch Templates at same time.
A lot of testing is also required to avoid breaking existing features.
@johngmyers as I said during office hours, I am looking into this for some time. If you plan to do any other changes in this area, we should sync so that we don't duplicate the effort.
=> Update tags support for LaunchTemplates

pkg/apis/kops/util/labels_test.go
Go does not keep the order of items when iterate over a map.
=> Fix a bug in UT apis/kops/util/labels_test.go

docs/getting_started/digitalocean.md
Updated Digitial Ocean documentation for KOPS to support multi-master HA.
=> [Digital Ocean] Update documentation for multi-master HA setup

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #8602 on release-1.17.
#8602: Update coredns to 1.6.7
=> Automated cherry pick of #8602: Update coredns to 1.6.7

k8s/crds/kops.k8s.io_clusters.yaml, k8s/crds/kops.k8s.io_instancegroups.yaml, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/componentconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
Additive flag mapping, may be useful for kubelet bootstrap.
=> kubelet: map rotate-certificates options

go.mod, nodeup/pkg/model/BUILD.bazel, nodeup/pkg/model/network.go
The check introduced in #7832 is unfortunately too naïve to detect if bpffs has been mounted leading to the unit file never being installed. This is quite disastrous for cilium.
This check in this PR should be more robust.
/kind bug
=> Cilium fix bpffs check

go.mod, nodeup/pkg/model/BUILD.bazel, nodeup/pkg/model/network.go
Cherry pick of #8599 on release-1.16.
#8599: Properly detect that bpffs has been mounted
=> Automated cherry pick of #8599: Properly detect that bpffs has been mounted

pkg/model/spotinstmodel/instance_group.go, upup/pkg/fi/cloudup/spotinsttasks/ocean.go
This PR adds support for blacklisting or whitelisting instance types in Ocean.
=> Spotinst: Add support for blacklisting or whitelisting instance types in Ocean

cmd/kops/create_cluster.go, docs/bastion.md
It can't be done anyway; instead we make it work (as far as we can),
and we document the workaround (which is to access it via the ELB DNS
name).
In future we could make it easier to discover this DNS name!
Fix #2881
=> Don't try to configure a bastion DNS name in gossip mode

addons/prometheus-operator/addon.yaml
there are problems without this already described in v0.29.yaml. Is there any reason v0.29 is not included in addons.yaml here?
=> use v0.29 in prometheus operator

docs/networking.md
* Updates a broken link to Calico BGP route reflector documentation
* Adds a link to documentation about the limitations of BGP without route reflectors for larger clusters
=> Update Calico CNI Networking Documentation Links

nodeup/pkg/model/docker.go
Cherry pick of #8160 on release-1.17.
#8160: Add Docker 19.03.4 and 18.09.9 for Ubuntu Xenial
=> Automated cherry pick of #8160: Add Docker 19.03.4 and 18.09.9 for Ubuntu Xenial

pkg/apis/kops/cluster.go, pkg/apis/kops/networking.go, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #8589 #8591 on release-1.17.
#8589: Bump Cilium to 1.7 for k8s 1.12+
#8591: Fix typo in the cilium default version
=> Automated cherry pick of #8589: Bump Cilium to 1.7 for k8s 1.12+ #8591: Fix typo in the cilium default version

docs/cluster_spec.md, docs/instance_groups.md, k8s/crds/kops.k8s.io_clusters.yaml, k8s/crds/kops.k8s.io_instancegroups.yaml, nodeup/pkg/model/sysctls.go, pkg/apis/kops/cluster.go, pkg/apis/kops/instancegroup.go, pkg/apis/kops/v1alpha1/cluster.go, pkg/apis/kops/v1alpha1/instancegroup.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/cluster.go, pkg/apis/kops/v1alpha2/instancegroup.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
Cherry pick of #7730 on release-1.17.
#7730: Add SysctlParameters to ClusterSpec and InstanceGroupSpec
=> Automated cherry pick of #7730: Add SysctlParameters to ClusterSpec and InstanceGroupSpec

pkg/dns/BUILD.bazel, pkg/dns/gossip_test.go
Signed-off-by: Nguyen Hai Truong <truongnh@fujitsu.com>
=> Adding Unit Test for pkg/dns/gossip.go

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/validation/validation.go, upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Calico 3.12 add support for autodetecting the iptables backend, quite useful for the people using Debian Buster, very soon the default base image in Kops.
https://docs.projectcalico.org/v3.12/release-notes/
This PR moves Calico and Canal to 3.12.0 and bumps the patch version for some of the previous releases.
=> Update Calico and Canal to v3.12.0

upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template, upup/pkg/fi/cloudup/BUILD.bazel, upup/pkg/fi/cloudup/template_functions.go
Cherry pick of #7979 on release-1.16.
#7979: cloudup: Map sprig indent template function
=> Automated cherry pick of #7979: cloudup: Map sprig indent template function

hack/.staticcheck_failures, node-authorizer/pkg/server/server.go
Finally fixes the last exception: #7800. Thanks for doing this @tanjunchen.
```
Errors from staticcheck:
node-authorizer/pkg/server/server.go:122:16: the channel used with signal.Notify should be buffered (SA1017)
```
=> Fix node-authorizer/pkg/server staticcheck failure

upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This is a small leftover of #8618.
=> Bump Calico and Canal version tags for older k8s

docs/releases/1.17-NOTES.md
This issue was discussed during office hours. I'll revert the upgrade in release-1.17 while we address the issue itself.
=> Add the aws iam authenticator known issue to the 1.17 release notes

docs/getting_started/arguments.md, upup/pkg/fi/nodeup/nodetasks/package.go, upup/pkg/fi/nodeup/tags/tags.go
During bootstrap packages that are already installed are skipped. They are later installed by the automatic updater.
The PR checks if automatic updates are enabled and tries to install the updated version.
The package managed decides if there is an update to be installed or not, so the only thing that has to be done is try to install it again. The newer the base image, the less updates will be installed.
This is a followup of #8020 and after discussing about the issue during office hours.
=> Install packages updates during bootstrap

upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This reverts #8544 and #8556 as discussed during office hours. I'll open a PR for a potential fix against master and if it gets merged early enough in our 1.17 release cycle, we can cherry-pick everything back into release-1.17
=> Revert AWS IAM Authenticator Update in release-1.17

upup/pkg/fi/cloudup/awsup/aws_cloud.go
[0] https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_LaunchTemplateSpecification.html
Fixes #8564
=> Treat nil of LaunchTemplateSpecification.Version as $Default [0]

upup/pkg/fi/cloudup/awsup/aws_cloud.go
Cherry pick of #8282 on release-1.17.
#8282: Set the default instance type to t3.medium for AWS
=> Automated cherry pick of #8282: Set the default instance type to t3.medium for AWS

upup/pkg/fi/nodeup/nodetasks/package.go
Due to a mistake in #8635, the condition for installing updated packages was not working correct.
This update should fix it to work as intended.
=> Fix condition for innstall packages updates during bootstrap

pkg/resources/aws/aws.go
Setting the feature flag `EnableLaunchTemplates=true` make kops use Launch Templates instead of Launch Configurations to create the ASGs.
Launch Templates implementation in Kops is derived from the Mixed Instance Policy feature, but requires a few tweaks. One of it is that security groups are declared for the primary network interface instead of the SecurityGroups field. For this reason, the delete mechanism is not finding these launch templates.
=> Delete launch templates when using EnableLaunchTemplates

docs/releases/1.17-NOTES.md, docs/releases/1.18-NOTES.md
#8282 was cherry-picked to 1.17 in #8656. It makes sense that the release notes are updated also.
=> Update release notes for the default instance type change

upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
After thinking through the solutions discussed during last week's office hours, I think the best and cleanest option will be to push for a 0.5.1 to fixes the regression altogether. This way we don't need to have special logic for automatically adding command arguments, or warn users to specify additional api fields when upgrading kops.
More discussion is happening [here](https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/288) and I'll see if i can open a bugfix PR upstream that could land in a 0.5.1 soon.
=> Revert AWS IAM Authenticator upgrade to 0.5.0 on master

hooks/nvidia-device-plugin/image/files/nvidia-device-plugin.service
nvidia-device-plugin.sh could failed due to network issues, apt issues, etc. But the `oneshot` service can't be restarted on failure.
> Service has Restart= setting other than no, which isn't allowed for Type=oneshot services. Refusing.
Changed to `Type=simple` and set `Restart=on-failure`.
=> retry nvidia-device-plugin.sh when failed

k8s/crds/kops.k8s.io_clusters.yaml, k8s/crds/kops.k8s.io_instancegroups.yaml, pkg/apis/kops/cluster.go, pkg/apis/kops/v1alpha1/cluster.go, pkg/apis/kops/v1alpha2/cluster.go, pkg/instancegroups/BUILD.bazel, pkg/instancegroups/settings.go, pkg/instancegroups/settings_test.go
On the cloud provider that supports it, a `maxSurge` of 1 (and thus `maxUnavailable` of 0) is a better default than `maxSurge` of 0 and `maxUnavailable` of 1. Nodes will still be drained one at a time, but the pods evicted from the first node won't have to be replaced on an old node and get evicted again.
The only downside I can think of would require a rather contrived situation: a workload that is deployed with a DaemonSet instead of a Deployment or StatefulSet and which cannot tolerate having the resulting surged pod.
/area rolling-update
=> Default maxSurge to 1 on AWS

upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Adding the changes from #8276 to the new version as well.
=> amazon-vpc-routed-eni env variable config

upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Weave 2.6.1 was (released)[https://github.com/weaveworks/weave/releases/v2.6.1] with support for Debian 10 (Buster).
Changes are based on:
https://github.com/weaveworks/weave/releases/download/v2.6.1/weave-daemonset-k8s-1.11.yaml
https://github.com/weaveworks/weave/releases/download/v2.6.1/weave-daemonset-k8s-1.8.yaml
This should be a good addition to the 1.17 release.
=> Update Weave Net to version 2.6.1

pkg/model/components/etcd.go, pkg/model/components/etcdmanager/model.go, pkg/model/components/etcdmanager/tests/minimal/tasks.yaml, pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml, pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Changelog:
* Allow overwriting etcd configs with env variables  [#296](https://github.com/kopeio/etcd-manager/pull/296)
* Update kops dependency to v1.16.0 [#302](https://github.com/kopeio/etcd-manager/pull/302)
=> Update etcd-manager to 3.0.20200307

mkdocs.yml
Add nav for new docs page. https://github.com/kubernetes/kops/pull/8680
CC: @mikesplain 
Signed-off-by: Jonathan Meyers <jonathan@cybrary.it>
=> [Docs] add link for Service Account Token Volumes

pkg/model/components/context.go
ref:https://github.com/kubernetes/kops/issues/8238
=> remove // TODO path.Join here?

util/pkg/proxy/BUILD.bazel, util/pkg/proxy/proxy_test.go
=> Add UT for util/pkg/proxy/proxy.go

pkg/apis/kops/networking.go, upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Seems that there will be a Kops 1.16.1 .
This PR is updating some of the network plugins to the latest patch releases:
* Calico - 3.9.5
* Canal - 3.75
* Cilium - 1.6.7
=> Use latest patch release for Calico, Canal and Cilium

pkg/apis/kops/channel.go, pkg/apis/kops/cluster.go
ref:https://github.com/kubernetes/kops/issues/8238
I don't think this needs to be moved, I use it as a check function. 
Is there a better solution here? Maybe leave it here ,it is better.
=> remove // TODO move this into networking.go :(

nodeup/pkg/model/network.go
This also avoids overflow during conversion. 0xCAFE4A11 is bigger than
the max of int32, so doing int32(uint32(0xCAFE4A11)) (will not compile
directly unless done over two lines) will result in -0x3501b5ef.
Due to some strange errors[0] in the types in "unix.Statfs_t" for 32 bits
systems, we have to explicitly convert to uint to support those (eg.
armv7). If we only need support for 64 bit systems, we can remove the
uint conversion as well.
[0]: For 32bits systems "fsdata.Type" should be uint32 instead of the
current int32, as it is in the linux kernel. This is due to the types in
glibc that the go types are generated from. For 64 bit systems the type
is correctly set to int64.
=> Use BPF_FS_MAGIC from go sys lib instead of hardcode

upup/pkg/fi/assettasks/copyfile.go, util/pkg/hashing/hash.go
Attempts to run the assets phase to copy file assets results in errors such as:
```
W0307 21:31:28.450047    2220 executor.go:130] error running task "CopyFile/https://kubeupv2.s3.amazonaws.com/kops/1.15.0/linux/amd64/utils.tar.gz" (8m57s remaining to succeed): unable to transfer "https://kubeupv2.s3.amazonaws.com/kops/1.15.0/linux/amd64/utils.tar.gz" to "https://REDACTED.s3.amazonaws.com/file-assets/kops/1.15.0/linux/amd64/utils.tar.gz": the sha value in "s3://file-assets/kops/1.15.0/linux/amd64/utils.tar.gz.sha256" does not match "https://kubeupv2.s3.amazonaws.com/kops/1.15.0/linux/amd64/utils.tar.gz" calculated value "sha1:ec8a939a80c3ba408a8be2d96528ac14f18aea8f"W0307 
```
/kind bug
=> Fix uploading of file assets

docs/networking.md
This was cherry-picked from https://github.com/kubernetes/kops/pull/7309 The code changes were already implemented in other PRs but the docs addition is still useful so I'm splitting it out here.
=> Adding docs for calico MTU

upup/pkg/fi/assettasks/copyfile.go, util/pkg/hashing/hash.go
Cherry pick of #8694 on release-1.15.
#8694: Fix uploading of file assets
=> Automated cherry pick of #8694: Fix uploading of file assets

nodeup/pkg/distros/distribution.go, nodeup/pkg/distros/identify.go, nodeup/pkg/model/kubelet.go
Ubuntu 20.04 is close to release and will be the next Ubuntu LTS release.
From Kubernetes point of view, this will be the supported distro with the newest Kernel for some time (Debian 10 and RHEL/CentOS 8 were just released).
Once official stable images are released will add an e2e test for it.
=> Add support for Ubuntu 20.04 (Focal)

pkg/validation/BUILD.bazel, pkg/validation/validate_cluster.go, pkg/validation/validate_cluster_test.go
Use the system-{cluster,node}-critical PriorityClassName instead of the kube-system Namespace to identify pods which can fail cluster validation.
The kube-system namespace has overloaded semantics, some of which grant pods therein unnecessary privileges. This causes people to run critical pods in other namespaces. These critical pods in other namespaces should be considered in cluster validation.
The system-{cluster,node}-critical PriorityClasses are much better indicators of what cluster validation is looking for. And I will soon need cluster validation to handle cluster-critical and node-critical pods differently.
=> Use PriorityClassName instead of namespace in cluster validation

upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
=> Fix kuberouter for k8s 1.16+

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Since there is a massive amount of fields to document, I only added the docs to one of the packages so far. I will add to the other two if there is no problem with the docs I added here.
=> Document all the fields in the Cilium spec

util/pkg/vfs/BUILD.bazel, util/pkg/vfs/memfs_test.go
=> Add UT for util/pkg/vfs/memfs.go

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
I already had this one in the pipeline. It looks like this is also what is causing source ips not to be preserved.
Fixes #8740
=> Set kube-proxy-replacement to partial

upup/models/cloudup/resources/addons/storage-aws.addons.k8s.io/v1.15.0.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Since kops manages the default storageclass for AWS, I feel we should add some improvements.
First, we can allow volume expansion now which is handy. https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims
Second, in order to prevent race conditions with Pods, setting the `volumeBindingMode` will only create a PV for a PVC and mount it to a node once the pod is scheduled.
https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode
Third, enable default EBS encryption. This one is debatable but I think for a production-ready kubernetes cluster in AWS this a best practice default.
This PR has the `volumeBindingMode` set as well, but I made a new PR since I am suggesting a few other changes. …
=> Create New Default StorageClass: kops-ssd-1-17

upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
#8735 uses the [kubeadm-kuberouter.yaml](https://github.com/cloudnativelabs/kube-router/blob/v0.4.0/daemonset/kubeadm-kuberouter.yaml) template as base, but it's broken. To fix it, I am trying to use the [generic-kuberouter.yaml](https://github.com/cloudnativelabs/kube-router/blob/v0.4.0/daemonset/generic-kuberouter.yaml).
The only real difference is removing `--kubeconfig=/var/lib/kube-router/kubeconfig` from args. The rest of changes are whitespace to make the diff easier next time.
My setup seems broken as I cannot get this to work on my end. Hoping that after this change, the e2e will start working again:
https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-aws-cni-kuberouter
=> Fix template for kube-router v0.4.0

nodeup/pkg/model/ntp.go
Hi 
This is a in working progress PR which will add the cloud specific NTP server into the NTP config.  This will prevent clock drift which could end up in resulting in downtime.  AWS as an example will prevent you speaking with there APIs once your clock is out by five minutes.
It would be great to get some feedback on whether you feel this is the best approach I am taking and also if you would prefer more parameters in the function I created rather pre determining the values inside the function with switch statements.
I used switch statements to prevent having to have the same logic again and again when determining the ntp install type.
I would like in another PR to maybe offer custom NTPs that a user could pass into the cluster spec.  This might be handy when you have custom NTP …
=> Add cloud ntp addresses

nodeup/pkg/model/containerd.go, nodeup/pkg/model/docker.go, nodeup/pkg/model/miscutils.go, nodeup/pkg/model/packages.go, nodeup/pkg/model/tests/dockerbuilder/docker_1.12.1/tasks.yaml, nodeup/pkg/model/tests/dockerbuilder/logflags/tasks.yaml, nodeup/pkg/model/tests/dockerbuilder/simple/tasks.yaml, pkg/model/components/containerd.go, pkg/model/components/docker.go, upup/pkg/fi/nodeup/nodetasks/archive.go
Using the Docker tgz (static) package instead of rpm/deb has some advantages:
* works on more distros, like Amazon Linux
* single package for all supported distros, so much easier to keep updated
* works with any released containerd tgz
* (in the future) will allow to specify any package URL for containerd or docker to be installed
This is similar to https://github.com/kubernetes/kops/pull/8199.
=> Update support for docker tgz package

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
This PR adds the possibility to use etcd as kvstore for cilium agent state. See https://docs.cilium.io/en/v1.7/gettingstarted/k8s-install-etcd-operator/ for the details.
Fixes #8465
Note that coredns 1.6+ currently has a bug that prevents etcd-operator from creating clusters, so if one wants to test this, downgrade coredns first. See https://github.com/coredns/coredns/issues/3686
=> Add option to use etcd managed by cilium-etcd-operator as kvstore

nodeup/pkg/model/docker.go, pkg/model/components/docker.go
Some newer versions of Docker were released since 19.03.4:
https://docs.docker.com/engine/release-notes/#19038
=> Update Docker to 19.03.8 for 1.18

addons/route53-mapper/README.md, docs/operations/addons.md
ref: #8732 
I wanted to update the kubectl apply URLs to not use master but we'd want to wait until a stable release includes #8732 or a cherry-pick of it before referencing something besides master.
=> Deprecate the route53-mapper addon

pkg/model/components/containerd.go
Corresponding containerd needs to be specified at the moment for each version of Docker.
This should fix the failing periodic e2e tests.
=> Use containerd 1.2.13 with Docker 19.03.8

docs/cluster_spec.md
After moving to etcdmanager I've noticed I lost an ability to fetch etcd metrics (by datadog agent).
Raising a question [here](https://github.com/kopeio/etcd-manager/issues/286) lead me to successfully expose the endpoint on master nodes (by manually editing etcd static pod manifests) and being able again to fetch them.
This is an approach to make kops expose the endpoint by default.
=> Expose etcd metrics.

pkg/resources/aws/aws.go, tests/integration/update_cluster/launch_templates/cloudformation.json, tests/integration/update_cluster/launch_templates/kubernetes.tf, tests/integration/update_cluster/mixed_instances/cloudformation.json, tests/integration/update_cluster/mixed_instances/kubernetes.tf, tests/integration/update_cluster/mixed_instances_spot/cloudformation.json, tests/integration/update_cluster/mixed_instances_spot/kubernetes.tf, upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go, upup/pkg/fi/cloudup/awstasks/autoscalinggroup_test.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation_test.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
Adding root volume tags has been requested for a long time #3358 and was implemented in #8462 and #8466, but only for the `direct` target.
This PR adds root volume tags for `terraform` and `cloudformation` targets when using launch templates or mixed instances policies.
Notes:
* launch templates were not working at all
* an autoscaling group should [use only one](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html) of launch configuration, launch template or mixed instances policy
* security groups should be specified for each network interface, instead of globally (global was meant for EC2 Classic and Default VPC)
* to enable the launch templates feature, the `EnableLaunchTemplates` [feature flag](https://github.com/kubernetes/kops/blob/master/docs/advanced/experimental.m …
=> Add root volume tags for CF and TF targets

upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Weave v2.6.1 contains a regression that is fixed in v2.6.2: https://github.com/kubernetes/kops/pull/8691#issuecomment-598111201
=> Update Weave Net to version 2.6.2

nodeup/pkg/model/ntp.go
#8312 broke support for some our supported distros as seen in periodic e2e tests.
This should fix the support by using Chrony (already default in most of the distros).
=> Fix NTP failures after #8312

upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This PR upgrades the Spotinst controller to version 1.0.57 and aligns all resources with the corresponding Helm [chart](https://github.com/spotinst/spotinst-kubernetes-helm-charts).
=> Spotinst: Upgrade the Spotinst controller to version 1.0.57

cmd/kops/validate_cluster.go, docs/cli/kops_validate_cluster.md
Validation of the cluster during e2e tests is not that reliable. Nodes are expected to be in `Ready` state and pass validation once:
https://github.com/kubernetes/test-infra/blob/8eefa866327706ca2ed7048e5a53437917d92f0d/kubetest/kops.go#L444-L452
A more reliable approach would be for Kops validation to succeed N consecutive times during a time interval. This PR improves cluster validation by adding a `--count` flag that can be used together with `--wait` to achieve this.
=> Wait for validation to succeed N consecutive times

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #8731 on release-1.17.
#8731: Allow configuration of enable-remote-node-identity
=> Automated cherry pick of #8731: Allow configuration of enable-remote-node-identity

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/containerdconfig.go, pkg/apis/kops/v1alpha1/containerdconfig.go, pkg/apis/kops/v1alpha2/containerdconfig.go, pkg/model/components/containerd.go, tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml
"info" is the default log level for containerd and also very useful compared to "warn", but still doesn't create a huge log file.
=> Set default log level to "info" for containerd

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
This PR adds the possibility to set the cilium option `--tofqdns-dns-reject-response-code`
https://docs.cilium.io/en/v1.6/cmdref/cilium-agent/#options
Thanks a lot :+1: :cat:
=> Add cilium option tofqdns-dns-reject-response-code

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Health check will fail otherwise.
/kind bug
=> Make cilium operator health check go against localhost IP

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #8789 on release-1.17.
#8789: Make cilium operator health check go against localhost IP
=> Automated cherry pick of #8789: Make cilium operator health check go against localhost IP

nodeup/pkg/model/kubectl.go
Kubernetes 1.19 stoped defaulting kubeconfig to http://localhost:8080 and needs a kubeconf in the home dir for kubectl to work by default.
https://github.com/kubernetes/kubernetes/pull/86173
=> Update default users for kubeconfig with supported distros

pkg/model/awsmodel/autoscalinggroup.go, pkg/model/context.go, pkg/model/spotinstmodel/BUILD.bazel, pkg/model/spotinstmodel/instance_group.go, upup/pkg/fi/cloudup/awstasks/launchtemplate.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
Cherry pick of #8462 #8466 on release-1.16.
#8462: Tag EBS volumes when using launch templates with AWS API
#8466: Update tags support for LaunchTemplates
=> Automated cherry pick of #8462: Tag EBS volumes when using launch templates with AWS API #8466: Update tags support for LaunchTemplates

docs/releases/1.18-NOTES.md, permalinks/upgrade_k8s.md, upup/pkg/fi/cloudup/apply_cluster.go
Per our deprecation policy, I had deprecated Kubernetes 1.9 in Kops 1.18, scheduling for removal int Kops 1.19. This is the minimum necessary to avoid increasing the supported range.
This PR proposes to also deprecate Kubernetes 1.10, removing support in Kops 1.19. This narrows the supported range by one version.
=> Deprecate support for Kubernetes 1.10

upup/pkg/fi/cloudup/alitasks/launchconfiguration.go, upup/pkg/fi/cloudup/alitasks/securitygrouprule.go
In preparation for the Terraform 0.12 support I noticed these inconsistencies.
I dont think it has any impact on functionality, I'm just trying to minimize the diff of the 0.12 PR
=> Fix terraform json field tags

cmd/kops/integration_test.go
closes #8736
This refactors the integration tests so that it is easier to add new variables to tests in the future including the ability to provide default values.
=> Refactor integration tests

pkg/apis/kops/util/labels.go
Stops dns-controller from flapping when nodes have multiple node-role annotations.
Fixes #8184
=> Fix dns-controller flapping on spot instances

upup/pkg/fi/cloud.go
In continue to #7404, this PR adds support for the Middle East (Bahrain) region (me-south-1).
=> Adding support for the Middle East (Bahrain) region (me-south-1)

cmd/kops/integration_test.go, tests/integration/update_cluster/private-shared-subnet/kubernetes.tf, tests/integration/update_cluster/privatecalico/kubernetes.tf, tests/integration/update_cluster/privatecanal/kubernetes.tf, tests/integration/update_cluster/privatedns1/kubernetes.tf, tests/integration/update_cluster/privatedns2/kubernetes.tf, tests/integration/update_cluster/privateflannel/kubernetes.tf, tests/integration/update_cluster/privatekopeio/kubernetes.tf, tests/integration/update_cluster/privateweave/kubernetes.tf, tests/integration/update_cluster/unmanaged/kubernetes.tf, upup/pkg/fi/cloudup/awstasks/launchconfiguration.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
Bastion hosts have no user_data by default. This is not valid in terraform, evidenced by the error messages reported [here](https://travis-ci.org/github/kubernetes/kops/jobs/662472020#L606).
The Terraform provider code says user_data is optional for both [LaunchConfigurations](https://github.com/terraform-providers/terraform-provider-aws/blob/04d24f80f3b740d0c9d74d97e818b7da15cb96c5/aws/resource_aws_launch_configuration.go#L74-L76) and [LaunchTemplates](https://github.com/terraform-providers/terraform-provider-aws/blob/04d24f80f3b740d0c9d74d97e818b7da15cb96c5/aws/resource_aws_launch_template.go#L510-L512).
This change prevents the user_data property from being added to `aws_launch_configuration` and `aws_launch_template` resources if the string is empty.
=> Don't set terraform user_data if it is empty 

k8s/crds/kops.k8s.io_instancegroups.yaml, pkg/apis/kops/instancegroup.go, pkg/apis/kops/v1alpha2/instancegroup.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/validation/aws.go, pkg/apis/kops/validation/aws_test.go, pkg/apis/kops/zz_generated.deepcopy.go, pkg/model/awsmodel/autoscalinggroup.go, tests/integration/update_cluster/launch_templates/cloudformation.json, tests/integration/update_cluster/launch_templates/in-v1alpha2.yaml, tests/integration/update_cluster/launch_templates/kubernetes.tf, upup/pkg/fi/cloudup/awstasks/launchtemplate.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation_test.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
- Launch configuration does not support the field SpotDurationInMinutes which is used to reserve the spot instances, but however Launch Template does
=> Add support for Spot block in launch template

cmd/kops-controller/BUILD.bazel, dns-controller/cmd/dns-controller/BUILD.bazel, images/BUILD.bazel
Currently the images have a timestamp of epoch 0:
```
$ docker inspect kope/kops-controller:1.18.0-alpha.2 -f '{{ .Created }}'
1970-01-01T00:00:00Z
```
The `container_image` [bazel rule](https://github.com/bazelbuild/rules_docker#container_image-1) mentions that `creation_time` has a default value of 0 unless `stamp = True`, so this should be enabled on all container_image rules that are pushed to a docker registry.
=> Enable stamping on bazel image builds

cmd/kops-controller/BUILD.bazel, dns-controller/cmd/dns-controller/BUILD.bazel, images/BUILD.bazel
Cherry pick of #8835 on release-1.17.
#8835: Enable stamping on bazel image builds
=> Automated cherry pick of #8835: Enable stamping on bazel image builds

hack/machine_types/machine_types.go, upup/pkg/fi/cloudup/awsup/machine_types.go
I tracked these fields back to a [2016 commit](https://github.com/kubernetes/kops/commit/caccb8953fa1b3f95937b62afa19de81dffd0868#diff-754b2bd20773bc5b478e031f2761d52b) that added the entire struct but they still weren't used even back then.
Coincidentally ECU is the only field in this type not available in the recently added `ec2.DescribeInstanceTypes`, so we can potentially switch entirely to that and drop hardcoded instance-type list altogether. This would allow new instance types to be supported without having to cut a new kops release.
=> Remove unused ECU and Burstable fields from AWSMachineTypeInfo

upup/pkg/fi/cloudup/networking.go
Equivalent of https://github.com/kubernetes/kubernetes/pull/78819.
=> Use CNI 0.8.5 for Kubernetes 1.18+

cloudbuild.yaml
We upgraded bazel to 2.2.0 in https://github.com/kubernetes/kops/pull/8790 which matches k/k. These cloudbuild jobs were still using an image containing bazel 0.29.1 which [have been failing](https://prow.k8s.io/job-history/kubernetes-jenkins/logs/kops-postsubmit-push-to-staging?buildId=1246516361849475072) since the upgrade.
I added a 2.2.0 image in https://github.com/kubernetes/test-infra/pull/17101 so this updates to use [those new images](https://console.cloud.google.com/gcr/images/k8s-testimages/GLOBAL/bazelbuild?gcrImageListsize=30).
=> Update GCB jobs to use bazel 2.2.0

nodeup/pkg/model/docker.go, nodeup/pkg/model/docker_test.go
For testing purposes people should be able to optionally use Docker 19.03.8 in Kops 1.17, as this will be the default version for Kubernetes 1.18.
https://github.com/kubernetes/website/pull/19643
Fixes #8738
=> Add support for Docker 19.03.8 in Kops 1.17

docs/development/testing.md
Now we're building it with bazel, we no longerger need the
old (pre-bazel) form.
=> Update build instructions for dns controller

pkg/apis/kops/validation/validation.go, pkg/apis/kops/validation/validation_test.go
The repo containing the binaries for Docker 1.11, 1.12 and 1.13 was shut down on March 31. This means support for older docker versions cannot be maintained.
https://www.docker.com/blog/changes-dockerproject-org-apt-yum-repositories/
> On the 31st of March 2020, we will be shutting down the legacy APT and YUM repositories hosted at dockerproject.org and dockerproject.com. These repositories haven’t been updated with the latest releases of Docker and so the packages hosted there contain security vulnerabilities. Removing these repositories will make sure that people download the latest version of Docker ensuring their security and providing the best experience possible
This PR will need to be cherry-picked to 1.16+.
=> Remove support for Docker 1.11, 1.12 and 1.13

pkg/nodeidentity/openstack/identify.go
fixes #8861 (openstack part hopefully)
=> fixes auth problem in case of openstack kops-controller

addons/metrics-server/README.md, addons/metrics-server/addon.yaml, addons/metrics-server/v1.16.x.yaml
Since kubernetes 1.16 does not support older deployments api versions
this needs to be updated as well.
=> Update metrics-server deployment apiVersion to apps/v1

pkg/apis/kops/validation/validation.go, pkg/apis/kops/validation/validation_test.go
Cherry pick of #8855 on release-1.17.
#8855: Remove support for Docker 1.11, 1.12 and 1.13
=> Automated cherry pick of #8855: Remove support for Docker 1.11, 1.12 and 1.13

upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #8697 #8735 #8742 #8751 on release-1.17.
#8697: fix kuberouter for k8s 1.16
#8735: Update kube-router to v0.4.0
#8742: Fix template for kube-router v0.4.0
#8751: Fix template for kube-router v0.4.0
=> Automated cherry pick of #8697 #8735 #8742 #8751: Update kube-router to v0.4.0

pkg/resources/gce/BUILD.bazel, pkg/resources/gce/gce.go, upup/pkg/fi/cloudup/gce/BUILD.bazel, upup/pkg/fi/cloudup/gce/gce_cloud.go, upup/pkg/fi/cloudup/gce/mock_gce_cloud.go
`Kops delete cluster` will now also delete the GCE DNS entries.
GCE DNS deletion is done by creating a Change object with resource record deletions/additions for one zone. So the implementation is using the GroupDeleter and the GroupKey.
For deletion the zone.name was needed and was not present in the dns.ResourceRecordSet. So I passed it along as the name of the ResourceRecord to be deleted. 
Any hints or pointers on how to write tests for this change very much appreciated. Works in my use case (example cluster on GCE).
=> GCE: Delete cluster will also delete the DNS entries created by kubernetes

cmd/kops/rollingupdatecluster.go, docs/cli/kops_rolling-update_cluster.md, pkg/instancegroups/instancegroups.go, pkg/instancegroups/rollingupdate.go, pkg/instancegroups/rollingupdate_test.go
We are still seeing lots of rolling update errors in case of cluster validation after instance roll. 
Example:
```
I0407 16:41:39.366581 85 instancegroups.go:255] Cluster validated; revalidating in 10s to make sure it does not flap.
I0407 16:42:00.200357 85 instancegroups.go:271] Cluster validated.
master not healthy after update, stopping rolling-update: "cluster \"updateospr-f95a75.k8s.local\" did not pass validation: kube-system pod \"kube-apiserver-master-zone-1-1-1-updateospr-f95a75-k8s-local\" is pending"
I0407 16:42:17.290824 1 batch.go:902] error running kops rolling-update cluster --bastion-interval 2m --instance-group bastions,master-zone-1-1,master-zone-2-1,master-zone-3-1,nodes-z1,nodes-z2,nodes-z3 --validation-timeout 20m --yes
```
Disclaimer: we are running e2e tests quite …
=> Validate cluster N times in rolling-update

Makefile, hack/verify-bindata.sh
=> add verify-bindata.sh & separate bindata check and update make commands.

Makefile
Now that this is checked into version control we shouldn't be deleting it. replace it with a `bazel clean` that also removes the bazel directories.
=> Don't delete bindata on "make clean"

hack/verify-terraform.sh, tests/integration/update_cluster/ha_gce/kubernetes.tf, tests/integration/update_cluster/minimal_gce/kubernetes.tf, upup/pkg/fi/cloudup/gcetasks/instance.go, upup/pkg/fi/cloudup/gcetasks/instancetemplate.go, upup/pkg/fi/cloudup/terraform/BUILD.bazel, upup/pkg/fi/cloudup/terraform/hcl2.go, upup/pkg/fi/cloudup/terraform/hcl2_test.go
The HCL2 library used for Terraform 0.12 support does not handle embedded types easily. The `google_compute_instance` and `google_compute_instance_template` terraform types used embedded types for common fields. Rather than detecting embedded types with reflection I figured it was easier to just copy the shared fields directly into the two types which included creating distinct AttachedDisk types as well. This also updates the `Add*` receiver functions for the defunct InstanceCommon type to instead return the value for the field that was being modified for both `google_compute_instance` and `google_compute_instance_template`.
This also adds support for writing maps of strings to `file()` references which is used in GCE's metadata fields.
Lastly, this updates the verify-terraform script to …
=> Fix Terraform 0.12 support for GCE

nodeup/pkg/model/kube_scheduler.go, nodeup/pkg/model/kube_scheduler_test.go
kubescheduler.config.k8s.io/v1alpha2 was removed in 1.19 by https://github.com/kubernetes/kubernetes/pull/89298.
kubescheduler.config.k8s.io/v1alpha2 was added in 1.18 by https://github.com/kubernetes/kubernetes/pull/87628.
Fixes #8871
=> Use kubescheduler.config.k8s.io/v1alpha2 for Kubernetes 1.18+

addons/ingress-nginx/v1.6.0.yaml
Deployments with `extensions/v1beta1` apiVersions are deprecated, according to [this](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/).
`spec.selector` is also required for deployment.
=> Fix addon/ing/nginx v1.6.0 deployment apiVersion and selector

pkg/model/components/docker.go, upup/pkg/fi/cloudup/populatecluster_test.go
#8860 broke one of the tests. This should fix it.
=> Fix tests for obsolete Docker versions in 1.17

pkg/model/components/docker.go, upup/pkg/fi/cloudup/populatecluster_test.go
#8859 broke one of the tests. This should fix it.
=> Fix tests for obsolete Docker versions in 1.16

docs/releases/1.18-NOTES.md
With #8825 and #8878 merged and targeting Kops 1.18, this updates the release notes with updated migration instructions.
=> Update 1.18 release notes now that Terraform 0.12 is supported

docs/releases/1.17-NOTES.md, docs/releases/1.18-NOTES.md
Release notes for 1.18 and 1.17 should have info about:
* default Docker version
* new distros supported by Kops
=> Add Docker version and new distros to release notes

README.md, docs/index.md, docs/welcome/releases.md, mkdocs.yml
The docs in README.md is duplicated in /docs, but we are not good at
keeping them in sync. Therefor I removed most of the information from
README.md andr refer to the docs instead.
Also fixed a few broken/missing links.
This is really more of an RFC, but I would love to get into a state where people start using https://kops.sigs.k8s.io/ over just the markdowns on github.
=> Remove duplicated docs

pkg/model/context.go, tests/integration/update_cluster/api_elb_cross_zone/kubernetes.tf, tests/integration/update_cluster/complex/cloudformation.json, tests/integration/update_cluster/complex/kubernetes.tf, tests/integration/update_cluster/externalpolicies/kubernetes.tf, tests/integration/update_cluster/nosshkey/kubernetes.tf, tests/integration/update_cluster/privatedns1/in-v1alpha2.yaml, tests/integration/update_cluster/privatedns1/kubernetes.tf
This adds any labels defined in the Cluster spec's CloudLabels to the tags of the following AWS resource types:
- Elastic IP
- Internet Gateway
- NAT Gateway
- Route Table
- Security Group
- Subnet
- VPC DHCP Options
- VPC
I debated between priority if they ever conflict with a tag key already being set by Kops. Currently this PR has CloudLabels taking priority over any built-in tags. If there is concern about users overwriting an important tag key with a value that kops won't handle properly then I could switch it to have the built-in tags take priority over the CloudLabels.
Fixes #8792
=> Add CloudLabels tags to additional AWS resources

pkg/model/context.go, tests/integration/update_cluster/api_elb_cross_zone/kubernetes.tf, tests/integration/update_cluster/complex/cloudformation.json, tests/integration/update_cluster/complex/kubernetes.tf, tests/integration/update_cluster/nosshkey/kubernetes.tf, tests/integration/update_cluster/privatedns1/in-v1alpha2.yaml, tests/integration/update_cluster/privatedns1/kubernetes.tf
Cherry pick of #8903 on release-1.17.
#8903: Add CloudLabels tags to additional AWS resources
=> Automated cherry pick of #8903: Add CloudLabels tags to additional AWS resources

pkg/k8sversion/version_test.go
=> Add unit test for func IsGTE

.travis.yml
Travis OSX test VMs are more rare than linux ones. No need to build on OSX for non-default GO versions.
For reference:
https://github.com/kubernetes/kops/pull/8893#issuecomment-612004667
=> Exclude GO 1.14 for OSX

nodeup/pkg/distros/distribution.go, nodeup/pkg/distros/identify.go, nodeup/pkg/model/kubelet.go
Cherry pick of #8727 on release-1.17.
#8727: Add support for Ubuntu 20.04 (Focal)
=> Automated cherry pick of #8727: Add support for Ubuntu 20.04 (Focal)

cmd/kops/rollingupdatecluster.go, pkg/instancegroups/instancegroups.go, pkg/instancegroups/rollingupdate.go, pkg/instancegroups/rollingupdate_test.go
This is a follow-on to #8868; I believe the intent of that was to
expose the option to do more (or fewer) retries.
We previously had a single retry to prevent flapping; this basically
unifies the previous behaviour with the idea of making it
configurable.
* validate-count=0 effectively turns off validation.
* validate-count=1 will do a single validation, without flapping
detection.
* validate-count>=2 will require N succesful validations in a row,
waiting ValidateSuccessDuration in between.
A nice side-effect of this is that the tests now explicitly specify
ValidateCount=1 instead of setting ValidateSuccessDuration=0, which
had the side effect of doing the equivalent to ValidateCount=1.
=> Rolling-update validation harmonization

hooks/nvidia-device-plugin/Makefile, hooks/nvidia-device-plugin/README.md, hooks/nvidia-device-plugin/image/files/01-aws-nvidia-driver.sh, hooks/nvidia-device-plugin/image/files/02-nvidia-docker.sh
Recent deep learning frameworks like TensorFlow and PyTorch require at least CUDA 10.0.
TensorFlow: https://www.tensorflow.org/install/gpu#software_requirements
PyTorch: https://pytorch.org/get-started/locally/
=> Upgrade CUDA from 9.1 to 10.0

upup/pkg/fi/cloudup/awstasks/natgateway.go
Cherry pick of #8051 on release-1.17.
#8051: Fix CloudFormation template tags for NatGateway
=> Automated cherry pick of #8051: Fix CloudFormation template tags for NatGateway

pkg/model/resources/nodeup.go, pkg/model/tests/data/bootstrapscript_0.txt, pkg/model/tests/data/bootstrapscript_1.txt, pkg/model/tests/data/bootstrapscript_2.txt, pkg/model/tests/data/bootstrapscript_3.txt, pkg/model/tests/data/bootstrapscript_4.txt, pkg/model/tests/data/bootstrapscript_5.txt, tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml, tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml, tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml, tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data, tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml, tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml, tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml, tests/integration/update_cluster/nosshkey-cloudformation/cloudformation.json.extracted.yaml
Cherry pick of #8936 on release-1.17.
#8936: Remove irrelevant TODO comment from userdata
=> Automated cherry pick of #8936: Remove irrelevant TODO comment from userdata

pkg/model/spotinstmodel/BUILD.bazel, pkg/model/spotinstmodel/instance_group.go, upup/pkg/fi/cloudup/spotinsttasks/BUILD.bazel, upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go, upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go, upup/pkg/fi/cloudup/spotinsttasks/ocean.go
This PR adds support for Headroom, Taints and Subnets in Ocean Launch Spec and minor User Data fixes.
=> Spotinst: Support for Headroom, Taints and Subnets in Ocean Launch Spec and User Data fixes

protokube/pkg/hostmount/nsenter_linux.go
We still don't actually support sensitive options, but it doesn't look
like we need them, MountSensitive is just called with empty
sensitiveOptions in a few places.
Issue #8908
=> Partially implement MountSensitive

.travis.yml
At the moment, Travis runs tests using the `.0` version of GO.
Would be better if Travis would use the latest patch version of GO, which is closer to what is used in official builds.
https://docs.travis-ci.com/user/languages/go/#specifying-a-go-version-to-use
=> Use latest patch version for GO in tests

upup/pkg/fi/BUILD.bazel, upup/pkg/fi/vfs_castore.go, upup/pkg/fi/vfs_castore_test.go
=> Load the correct certificate before deleting

upup/pkg/fi/BUILD.bazel, upup/pkg/fi/vfs_castore.go, upup/pkg/fi/vfs_castore_test.go
Cherry pick of #8945 on release-1.17.
#8945: Load the correct certificate before deleting
=> Automated cherry pick of #8945: Load the correct certificate before deleting

nodeup/pkg/model/sysctls.go
Please refer to https://github.com/coreos/flannel/issues/902 for details.
Running Flannel with iptables mode on CentOS 7 needs to have `sysctl` setting as below:
```
net.bridge.bridge-nf-call-ip6tables=1
net.bridge.bridge-nf-call-iptables=1
```
I have tested this change, and it did solve my problem.
=> Fix net.bridge setting for Flannel on CentOS 7

k8s/crds/kops.k8s.io_clusters.yaml, nodeup/pkg/model/kube_apiserver.go, nodeup/pkg/model/kube_apiserver_test.go, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/componentconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
Cherry pick of #7900 on release-1.17.
#7900: Add encryptionProviderConfig field
=> Automated cherry pick of #7900: Add encryptionProviderConfig field

docs/releases/1.18-NOTES.md, pkg/nodeidentity/gce/BUILD.bazel, pkg/nodeidentity/gce/identify.go, pkg/resources/gce/BUILD.bazel, pkg/resources/gce/dump.go, pkg/resources/gce/gce.go, protokube/pkg/gossip/gce/BUILD.bazel, protokube/pkg/gossip/gce/seeds.go, protokube/pkg/protokube/BUILD.bazel, protokube/pkg/protokube/gce_volume.go, upup/pkg/fi/cloudup/gce/BUILD.bazel, upup/pkg/fi/cloudup/gce/gce_cloud.go, upup/pkg/fi/cloudup/gce/instancegroups.go, upup/pkg/fi/cloudup/gce/mock_gce_cloud.go, upup/pkg/fi/cloudup/gce/network.go, upup/pkg/fi/cloudup/gce/op.go, upup/pkg/fi/cloudup/gce/status.go, upup/pkg/fi/cloudup/gce/wrappers.go, upup/pkg/fi/cloudup/gcetasks/BUILD.bazel, upup/pkg/fi/cloudup/gcetasks/address.go, upup/pkg/fi/cloudup/gcetasks/disk.go, upup/pkg/fi/cloudup/gcetasks/firewallrule.go, upup/pkg/fi/cloudup/gcetasks/forwardingrule.go, upup/pkg/fi/cloudup/gcetasks/instance.go, upup/pkg/fi/cloudup/gcetasks/instancegroupmanager.go, upup/pkg/fi/cloudup/gcetasks/instancetemplate.go, upup/pkg/fi/cloudup/gcetasks/network.go, upup/pkg/fi/cloudup/gcetasks/subnet.go, upup/pkg/fi/cloudup/gcetasks/targetpool.go
Waiting on #8969 
Bumps the gcp libraries from v0beta to v1! 
`&compute.InstanceGroupManagersResizeAdvancedRequest` is only available in the beta libraries. I've updated the IGM resize method to reflect the [docs](https://cloud.google.com/compute/docs/reference/rest/v1/instanceGroupManagers/resize#go)
=> Migrates GCE sdk from v0.beta to v1

upup/models/bindata.go, upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
* Calico and Canal `3.13.3` for k8s 1.16+
* Canal `v3.12.1` for k8s 1.15
* Calico liveness probe for k8s 1.12-1.15
=> Update Calico and Canal to latest patch versions

channels/alpha, channels/stable
The versions going to `stable` have been running in `alpha` for just over a month now, looks like it's safe to move to `stable`.
=> Update alpha and stable channels with April updates

docs/operations/addons.md
Generated documentation at https://kops.sigs.k8s.io/operations/addons/#addon-management currently gives 404 on "addons directory" link to https://kops.sigs.k8s.io/addons
=> Make addons directory link absolute to avoid 404

docs/cluster_spec.md, k8s/crds/kops.k8s.io_clusters.yaml, k8s/crds/kops.k8s.io_instancegroups.yaml, nodeup/pkg/model/kube_apiserver_test.go, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha2/componentconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
Adding support for two flags required by CIS / aquasecurity/kube-bench.
Work on this started previously [here](https://github.com/kubernetes/kops/pull/4799).
=> Profiling and protect kernel defaults flags

upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #8961 on release-1.17.
#8961: Update Calico and Canal to v3.13.3 for k8s 1.16+
=> Automated cherry pick of #8961: Update Calico and Canal to v3.13.3 for k8s 1.16+

upup/pkg/fi/cloudup/gcetasks/network.go, upup/pkg/fi/cloudup/gcetasks/subnet.go
closes #9003 
~~I don't think this impacts existing clusters, but am checking...~~
Looks like this is a no-op for existing clusters, we're good to go.
=> GCE: needs to use v1 network resources, not beta

channels/alpha, channels/stable
Debian 8 (Jessie) are shutting down ahead of its soon to be EOL. As Kops still officially supports older versions of Kubernetes and images are already built it should use them by default.
Failing periodic e2e for 1.10:
https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-aws-k8s-1.10
=> Default to Debian 9 (Stretch) for Kubernetes 1.8, 1.9 and 1.10

upup/models/bindata.go, upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Seems that these were missing compared to latest version on the weave site.
=> Fix missing changes in Weave manifest

pkg/model/components/etcd.go, pkg/model/components/etcdmanager/model.go, pkg/model/components/etcdmanager/options.go, pkg/model/components/etcdmanager/tests/minimal/tasks.yaml, pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml, pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml, pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Contains the workaround for 1-year certificate expiry.
3.0.2020428 changes
* Release notes for 3.0.20200307 [#303](https://github.com/kopeio/etcd-manager/pull/303)
* Add support for etcd 3.3.17 [#304](https://github.com/kopeio/etcd-manager/pull/304)
* Adding client usage extension for server cert (#305) [#306](https://github.com/kopeio/etcd-manager/pull/306)
* Add a check to renew certificates on startup if they expire in 60 days or less [#309](https://github.com/kopeio/etcd-manager/pull/309)
* Try github actions [#310](https://github.com/kopeio/etcd-manager/pull/310)
* Upgrade bazel to 2.2.0 [#311](https://github.com/kopeio/etcd-manager/pull/311)
* Update to go 1.13.10 [#314](https://github.com/kopeio/etcd-manager/pull/314)
* Bazel: update dependency …
=> Update to etcd-manager 3.0.20200429

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #8982 on release-1.17.
#8982: Bump cilium to 1.7.2
=> Automated cherry pick of #8982: Bump cilium to 1.7.2

pkg/resources/gce/gce.go
Use the GroupKey to pass the zone name, meaning the name can be the
user-facing value.
Follow-on to #8250
=> GCE DNS Cleanup: Print record name

dnsprovider/pkg/dnsprovider/providers/aws/route53/route53_test.go, dnsprovider/pkg/dnsprovider/providers/coredns/coredns_test.go, dnsprovider/pkg/dnsprovider/providers/google/clouddns/clouddns_test.go
This is very minor...
GH Action's search functionality is not case sensitive.
In Travis CI, one could search for `FAIL:` and be taken to relevant test failures.
In GHA, these tests were also in the search results making it harder to find the actual tests that are failing.
This renames the tests so that searching for `FAIL:` (case insensitive) will only return failing tests.
Example:
=> Rename tests to make it easier to search for failing tests

nodeup/pkg/model/containerd.go, nodeup/pkg/model/docker.go
The rpm containerd 1.2.10 package depends on containerd-selinux, which
isn't available on amazonlinux2.  We can't just skip it, because we
can't install the package without its dependencies.
Instead, install from a binary package.
=> Use raw tarfile for AmazonLinux2 + Containerd 1.2.10

docs/getting_started/aws.md
Correct expression typos and enhance text on `docs/aws.md`.
Note: This is my first contribution to an open source project. I will appreciate suggestions and directions on what to do/not to do.
=> Correct expression typos on docs/aws.md

cmd/kops/create_ig.go, cmd/kops/edit_instancegroup.go, pkg/apis/kops/validation/cluster.go, pkg/apis/kops/validation/cluster_test.go, pkg/apis/kops/validation/instancegroup.go, pkg/apis/kops/validation/instancegroup_test.go, pkg/apis/kops/validation/legacy.go, tests/integration/update_cluster/existing_iam/data/aws_launch_configuration_master-us-test-1a.masters.existing-iam.example.com_user_data, tests/integration/update_cluster/existing_iam/data/aws_launch_configuration_master-us-test-1b.masters.existing-iam.example.com_user_data, tests/integration/update_cluster/existing_iam/data/aws_launch_configuration_master-us-test-1c.masters.existing-iam.example.com_user_data, tests/integration/update_cluster/existing_iam/in-v1alpha2.yaml, tests/integration/update_cluster/existing_iam/kubernetes.tf, upup/pkg/fi/cloudup/deepvalidate_test.go, upup/pkg/fi/cloudup/populateinstancegroup_test.go, upup/pkg/fi/cloudup/validation_test.go
Fixes #8817 
I have not done any testing on terraform though.
Care still needs to be taken when deleting master IGs. If you break quorum you need to restore etcd from backup. Preventing master IGs in an unsafe way is already possible though, so I didn't do anything to prevent this here.
=> Allow changing AZ of masters

pkg/resources/aws/aws.go, upup/pkg/fi/cloudup/awsup/aws_cloud.go
Well known owner aliases and SSH users were updated on master via multiple PR, but never back-ported.
These are important, considering they are listed in https://kops.sigs.k8s.io/operations/images/.
=> Back-port well known owner aliases and SSH users to 1.16

pkg/resources/aws/aws.go, upup/pkg/fi/cloudup/awsup/aws_cloud.go
Well known owner aliases and SSH users were updated on master via multiple PR, but never back-ported.
These are important, considering they are listed in https://kops.sigs.k8s.io/operations/images/.
=> Back-port well known owner aliases and SSH users to 1.17

nodeup/pkg/model/docker.go
Focal requires a Docker package in older Kops versions. As an official package for Ubuntu 20.04 (Focal) doesn't exist at the moment, the one for Ubuntu 18.04 can be used.
Support for Ubuntu 20.04 is experimental in Kops 1.16 and 1.17.
Related to https://github.com/kubernetes/kops/pull/9044.
=> Use Ubuntu 18.04 Docker packages for Ubuntu 20.04 setups

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #8794 on release-1.16.
#8794: Make cilium operator health check go against localhost IP
=> Automated cherry pick of #8794: Make cilium operator health check go against localhost IP

docs/operations/images.md, docs/releases/1.17-NOTES.md, docs/releases/1.18-NOTES.md
Added a few more tweaks to the supported distros and release notes.
Decided to advertise Ubuntu 20.04 only for Kops 1.17+. For those that want to test, they will be able to use also Kops 1.16.2.
No action was done to remove the deprecated distros, but we need to start announcing the reduced support for them.
/cc @rifelpet @johngmyers
=> Update docs on supported distros and release notes

channels/stable
It's been a week since we updated these versions and things seem stable, Looks like we should be good bumping the versions up to reflect the latest patch versions of k8s.
=> Updating stable channel to use latest k8s versions

util/pkg/vfs/s3context.go, util/pkg/vfs/s3context_test.go
Support S3 URLs written in Virtual Hosted Style, which seems to be only recommended notation nowadays, but isn't supported in kops.
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#virtual-host-style-url-ex
All the other options are more or less deprecated path style https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#path-style-access, old virtual styles https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#VirtualHostingBackwardsCompatibility
=> Support S3 Virtual Hosted Style

upup/models/bindata.go, upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template, upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.9.0.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This PR upgrades the Spotinst controller to version 1.0.58 and removes erroneous YAML separators
CC @liranp
=> Feature spotinst controller v1.0.58

nodeup/pkg/model/containerd.go, nodeup/pkg/model/docker.go
download.docker.com doesn't have packages for ubuntu 20.04 (focal),
use the generic tar.gz versions instead.
=> Ubuntu focal: Use generic docker & container packages

pkg/model/components/etcd.go, pkg/model/components/etcdmanager/model.go, pkg/model/components/etcdmanager/tests/minimal/tasks.yaml, pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Cherry pick of #9016 on release-1.15.
#9016: Update to etcd-manager 3.0.20200428
=> Automated cherry pick of #9016: Update to etcd-manager 3.0.20200428

upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #9026 on release-1.17.
#9026: Bump cilium to 1.7.3
=> Automated cherry pick of #9026: Bump cilium to 1.7.3

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/networking.go, pkg/apis/kops/parse_test.go, pkg/apis/kops/v1alpha1/networking.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/networking.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go, upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template, upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/cluster.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #8216 #8303 on release-1.17.
#8216: Adding ability to configure resources for weave (#8113)
#8303: Fix unit name for memory request for weave
=> Automated cherry pick of #8216 #8303: Adding ability to configure resources for weave

.github/workflows/main.yml
A significant benefit of Travis/GitHub Actions is getting test and verification results before making a pull request. Restricting push triggers to master branch significantly impedes this.
Remove the restriction to master branch, bringing it into alignment with the current Travis settings.
=> Don't restrict GitHub Actions to master

pkg/validation/validate_cluster.go, pkg/validation/validate_cluster_test.go
This should cut down on cluster validation flapping.
Not testing the etcd pods as their `k8s-app` annotation depends on whether or not the cluster is configured to use etcd-manager. (It's also unlikely kube-apiserver would be ready without them.) Not testing kube-proxy pods because whether or not they're supposed to be there depends on the cluster spec.
Suppressing the static pod checks on non-ready nodes to cut down on redundant failure messages.
/area rolling-update
=> Validate more static pods on masters

upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template, upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #7898 #8691 #8764 #8965 on release-1.17.
#7898: Update Weave Net to version 2.6.0
#8691: Update Weave Net to version 2.6.1
#8764: Update Weave Net to version 2.6.2
#8965: Fix missing changes in Weave manifest
=> Automated cherry pick of #7898 8691 8764 8965: Update Weave Net to version 2.6.2

upup/pkg/fi/cloud.go
AWS announced a third AZ in ca-central-1, which is showing up as "ca-central-1d" for me. While I was there, I noticed ap-northeast-3 was missing.
=> Add more ca-central-1 AZs, add ap-northeast-3 AZs

docs/advisories/README.md, docs/advisories/etcd-manager-certificate-expiration.md
A few notes:
* etcd-manager was actually introduced in Kops 1.10, but wasn't made default until k8s 1.12
* I guessed on the next kops release versions that will include the fix
I'd like this to be throughly reviewed before we merge since people will start seeing it and linking to it.
/cc @justinsb
=> Add etcd-manager certificate expiration advisory

cmd/kops/create_ig.go, cmd/kops/edit_instancegroup.go, upup/pkg/fi/cloudup/apply_cluster.go, upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Addresses some aspects of #8834, assuming no instancegroup is depending on the channel providing a default image to use.
=> Allow cluster maintenance when channel is unavailable

cmd/kops/create_ig.go, cmd/kops/edit_instancegroup.go, upup/pkg/fi/cloudup/apply_cluster.go, upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Cherry pick of #9053 on release-1.17.
#9053: Allow cluster maintenance when channel is unavailable
=> Automated cherry pick of #9053: Allow cluster maintenance when channel is unavailable

nodeup/pkg/model/network.go
Tx checksum offloading is buggy for NAT-ed VXLAN endpoints, leading to an invalid checksum sent and causing Flannel to stop to working as the traffic is being discarded by the receiver.
https://github.com/coreos/flannel/issues/1279
/cc @johngmyers @justinsb
=> Disable TX checksum offload for Flannel VXLAN

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha1/componentconfig.go, pkg/apis/kops/v1alpha1/zz_generated.conversion.go, pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go, pkg/apis/kops/v1alpha2/componentconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
Cherry pick of #9068 on release-1.17.
#9068: Added support for configuring disable-attach-detach-reconcile-sync
=> Automated cherry pick of #9068: Added support for configuring disable-attach-detach-reconcile-sync

nodeup/pkg/model/network.go
Cherry pick of #9074 on release-1.17.
#9074: Disable TX checksum offload for Flannel VXLAN
=> Automated cherry pick of #9074: Disable TX checksum offload for Flannel VXLAN

nodeup/pkg/model/docker.go
Followup of #9047 which did the same for Docker 18.09.9 and 19.03.4.
/cc @rifelpet
=> Use Ubuntu 18.04 Docker 19.03.8 packages for Ubuntu 20.04

nodeup/pkg/model/protokube.go
This way if you have the value set in config (even as "") it'll get
passed down to allow you to override the default config
Related to #9006
More detailed explanation: https://github.com/kubernetes/kops/issues/9006#issuecomment-620298643
=> Include secondary protocol flag always

.travis.yml
For release branches we only need Linux and macOS with the default GO version.
This should help reduce the load on macOS jobs and, in general, before releases.
=> Reduce the number of TravisCI jobs for release branch

pkg/wellknownports/wellknownports.go
Both were allocated port 3993; etcd-cilium is new and so it is less
impactful to renumber that.
=> Fix port conflict on etcd-cilium vs dns-controller memberlist

pkg/model/components/apiserver.go, pkg/model/components/kubeapiserver/model.go, pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
We cherry picked, but now we need to activate the feature.
=> kube-apiserver-healthcheck: actually enable on 1.17

nodeup/pkg/model/protokube.go, nodeup/pkg/model/tests/protokube/containerd/tasks.yaml, upup/pkg/fi/nodeup/nodetasks/load_image.go
Imported container images have to be put into the `k8s.io` namespace to be accessible to Kubernetes. Initially I thought side-loading was just for Protokube and could be kept in a different namespace, but the mechanism is used for more than this.
In short, beginner level mistake. This fix mostly reverts an old commit of mine from https://github.com/kubernetes/kops/pull/8217.
Fixes https://github.com/kubernetes/kops/issues/9099
=> Fix containerd image side-loading

docs/bastion.md, docs/getting_started/aws.md, docs/gossip.md, mkdocs.yml
=> Add documentation on gossip

cmd/kops/completion.go
Cherry pick of #9108 on release-1.17.
#9108: Fix zsh completion
=> Automated cherry pick of #9108: Fix zsh completion

pkg/featureflag/featureflag.go, upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This PR adds a new feature flag, named `SpotinstController`, that allows users to toggle the installation of the Spotinst controller off. The feature flag defaults to `true` to maintain backward compatibility.
=> Spotinst: Allow users to disable the controller add-on

cmd/kops/rollingupdatecluster.go, pkg/cloudinstances/cloud_instance_group.go, pkg/resources/spotinst/resources.go, pkg/validation/validate_cluster.go, pkg/validation/validate_cluster_test.go, upup/pkg/fi/cloudup/aliup/status.go, upup/pkg/fi/cloudup/awsup/aws_cloud.go, upup/pkg/fi/cloudup/gce/instancegroups.go, upup/pkg/fi/cloudup/openstack/server_group.go
If the ASG has scaled above the min, rolling updates can start draining the next node before the ASG replaces a terminated one.
=> Fail cluster validation if too few nodes for ig's target size

cmd/kops-controller/controllers/node_controller.go, pkg/nodeidentity/aws/identify.go, pkg/nodeidentity/interfaces.go
When using a "mixed instance policy"[1] instance group spot and onDemand nodes are part of the same ASG. The ASG handles the percentage of spot vs onDemand
instances. There are no annotations, EC2 tags or labels to identify which
instances are onDemand vs spot.
This PR introduces a new label to be attached on all AWS instances.
The label is:
```
node-role.kubernetes.io/spot-worker: <value>
```
Possible values are:
* onDemand (default)
* spot
[1]: https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#mixedinstancepolicy-aws-only
=> Add EC2 Instance LifeCycle label

pkg/model/defaults/BUILD.bazel, pkg/model/defaults/volumes_test.go, upup/pkg/fi/utils/BUILD.bazel, upup/pkg/fi/utils/equals_test.go, upup/pkg/fi/utils/hash_test.go, upup/pkg/fi/utils/sanitize_test.go
=> add some unit tests

upup/pkg/fi/http.go
I observed a node failure where we failed to download docker; we need
some timeout just to prevent the hang.
Two minutes should be plenty for our downloads.
=> http download: set a timeout to avoid hangs

k8s/crds/kops.k8s.io_instancegroups.yaml, pkg/apis/kops/instancegroup.go, pkg/apis/kops/v1alpha2/instancegroup.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/validation/aws.go, pkg/apis/kops/validation/aws_test.go, pkg/apis/kops/zz_generated.deepcopy.go, pkg/model/awsmodel/autoscalinggroup.go, tests/integration/update_cluster/launch_templates/cloudformation.json, tests/integration/update_cluster/launch_templates/in-v1alpha2.yaml, tests/integration/update_cluster/launch_templates/kubernetes.tf, upup/pkg/fi/cloudup/awstasks/launchtemplate.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation_test.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go, upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
ref: #8809
Updated Launch Template with spot instance interruption behavior
=> Added Launch Template support for instance interruption behavior

dns-controller/pkg/dns/dnscontroller.go, dnsprovider/pkg/dnsprovider/dns.go, dnsprovider/pkg/dnsprovider/providers/aws/route53/route53_test.go, dnsprovider/pkg/dnsprovider/providers/aws/route53/rrchangeset.go, dnsprovider/pkg/dnsprovider/providers/coredns/coredns_test.go, dnsprovider/pkg/dnsprovider/providers/coredns/rrchangeset.go, dnsprovider/pkg/dnsprovider/providers/google/clouddns/clouddns_test.go, dnsprovider/pkg/dnsprovider/providers/google/clouddns/rrchangeset.go, dnsprovider/pkg/dnsprovider/providers/openstack/designate/BUILD.bazel, dnsprovider/pkg/dnsprovider/providers/openstack/designate/designate_test.go, dnsprovider/pkg/dnsprovider/providers/openstack/designate/rrchangeset.go, dnsprovider/pkg/dnsprovider/tests/BUILD.bazel, dnsprovider/pkg/dnsprovider/tests/commontests.go, dnsprovider/pkg/dnsprovider/tests/contract.go, pkg/resources/digitalocean/dns/dns.go, pkg/resources/digitalocean/dns/dns_test.go, protokube/pkg/gossip/dns/provider/changeset.go, upup/pkg/fi/cloudup/apply_cluster.go, upup/pkg/fi/cloudup/dns.go
For GCE this was resulting in confusing error messages.
=> DNS: Don't try to apply empty changesets

mkdocs.yml
There is already an "Our release process" item that links to this same page. line 144
=> Remove redundant menu item in the docs site

docs/networking.md
Classic networking support was dropped as of Kubernetes 1.4.
=> Remove Classic networking from docs

docs/state.md
Fix json example for Cross Account State-store.
=> doc: Typo in docs/state.md

k8s/crds/kops.k8s.io_clusters.yaml, pkg/apis/kops/componentconfig.go, pkg/apis/kops/v1alpha2/componentconfig.go, pkg/apis/kops/v1alpha2/zz_generated.conversion.go, pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go, pkg/apis/kops/zz_generated.deepcopy.go
This is needed/useful for identity federation to AWS.
=> Map kube-apiserver service-account-jwks-uri flag

pkg/model/openstackmodel/servergroup.go, tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml, tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml, tests/integration/create_cluster/private/expected-v1alpha2.yaml, upup/pkg/fi/cloudup/populate_instancegroup_spec.go
There's no reason to put bastions in utility subnets as their securitygroup only allows incoming traffic from the load balancer.
=> Don't put bastions in the utility subnets

pkg/resources/aws/BUILD.bazel, pkg/resources/aws/aws_test.go
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
=> Add unit test for func matchesElbTags

cmd/kops-controller/controllers/node_controller.go, pkg/nodeidentity/aws/identify.go, pkg/nodeidentity/interfaces.go
Cherry pick of #9121 on release-1.17.
#9121: Add EC2 instance lifecycle label to nodes
=> Automated cherry pick of #9121: Add EC2 instance lifecycle label to nodes

upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml, upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Cherry pick of #9020 on release-1.17.
#9020: Upgrade amazon vpc cni to 1.6.1
=> Automated cherry pick of #9020: Upgrade amazon vpc cni to 1.6.1

nodeup/pkg/model/BUILD.bazel, nodeup/pkg/model/containerd.go, nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml, pkg/model/components/containerd.go, tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml
Docker generates the a conflist file for Kubenet when needed.
containerd has a different approach:
https://github.com/containerd/cri/blob/master/docs/config.md#cni-config-template
At some point, Kubenet will migrate to CNI and this workaround can be removed. Until then, this is the default in Kops and should be added, if possible.
https://github.com/kubernetes/kubernetes/issues/38890
CNI config template is based on:
https://github.com/containerd/cri/blob/master/hack/install/install-cni-config.sh
=> Add support for Kubenet with containerd

pkg/commands/status_discovery.go, pkg/resources/digitalocean/BUILD.bazel, pkg/resources/digitalocean/cloud.go, upup/pkg/fi/cloudup/dotasks/loadbalancer.go
- Added logic for FindCluster Status
- Also fixed load balancer logic to only create LB if it doesn't exist.
- Tested with kops edit cluster by adding new Instance group and was able to see the cluster updated as expected.
=> [Digital Ocean] Handle logic for kops edit/update cluster

cmd/kops-controller/controllers/node_controller.go, pkg/nodeidentity/aws/identify.go, pkg/nodeidentity/interfaces.go
This reverts commit 7f2f195a cherrypicked in through #9152.
Concern was raised during Kops Office Hours as to the naming of the label. I propose we revert this change from 1.17 to give us until 1.18 to resolve the naming decision.
=> Revert "Add EC2 instance lifecycle label to nodes"

Makefile, pkg/model/components/kubelet.go, tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-a-ha-gce-example-com_metadata_startup-script, tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-b-ha-gce-example-com_metadata_startup-script, tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-c-ha-gce-example-com_metadata_startup-script, tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_nodes-ha-gce-example-com_metadata_startup-script, tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_master-us-test1-a-minimal-gce-example-com_metadata_startup-script, tests/integration/update_cluster/minimal_gce/data/google_compute_instance_template_nodes-minimal-gce-example-com_metadata_startup-script, upup/pkg/fi/nodeup/command.go, util/pkg/vfs/context.go
Distros that use systemd for DHCP often don't have the hostname
correct, due to e.g. the requirement for policy kit.
We don't rely on it being set correctly on other clouds; no real
reason to require it on GCP either!
Example issue: https://github.com/systemd/systemd/issues/13501
=> GCE: don't rely on hostname being correct

pkg/apis/kops/util/BUILD.bazel, pkg/apis/kops/util/versions_test.go
=> Add unit test case for pkg/apis/kops/util/versions_test.go

pkg/featureflag/featureflag.go, pkg/model/awsmodel/BUILD.bazel, pkg/model/awsmodel/autoscalinggroup.go, pkg/model/spotinstmodel/BUILD.bazel, pkg/model/spotinstmodel/instance_group.go, pkg/resources/aws/aws.go, upup/pkg/fi/cloudup/apply_cluster.go, upup/pkg/fi/cloudup/awsup/aws_cloud.go
This PR allows users to gradually integrate with Spotinst.
When the Spotinst feature flag is toggled on (`export KOPS_FEATURE_FLAGS="+Spotinst"`), kops manages all instance groups through the Spotinst API using both Spotinst Elastigroup and Spotinst Ocean.
The new hybrid integration mode allows users to continue managing their instance groups through AWS Auto Scaling Groups, except for specific instance groups labeled with a predefined metadata label.
1. Toggle on the hybrid integration feature flag:
```sh
export KOPS_FEATURE_FLAGS="+Spotinst,SpotinstHybrid"
```
2. Create a new instance group or update an existing one:
```yaml
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
labels:
...
spotinst.io/hybrid: "true"
...
spec:
...
```
=> Spotinst: New hybrid integration mode

upup/models/bindata.go, upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
This changes bumps DigitalOcean's cloud-controller-manager (CCM) to version 0.1.24 which brings a number of new features and bug fixes.
It seems like there are now two occurrences of the CCM manifest: one as YAML and one in-code. I wasn't entirely sure if the image versions needed to be updated in both places, which I did for now. Please let me know in case that's not needed.
Ideally, the change should be cherry-picked into 1.17 subsequently.
=> Update DigitalOcean cloud-controller-manager to v0.1.24

pkg/model/components/etcd.go, pkg/model/components/etcdmanager/model.go, pkg/model/components/etcdmanager/tests/minimal/tasks.yaml, pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml, pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml, pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Changes since 3.0.20200429:
* Use env vars to customize backup retention
* Use next attachment point when device already in use
* Simplify uploading backups
=> Update etcd-manager to 3.0.20200527

docs/getting_started/digitalocean.md, upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Since coreOS will no longer be supported, changing the DO image default to Debian instead.
=> Use debian as default image for DO images

nodeup/pkg/model/ntp.go
`systemd-timesyncd` is the default service for clock synchronisation in Ubuntu 20.04. Installing `ntp` seems to make `kops-configuration` crash as reported in #9180.
We already use `systemd-timesyncd` for Ubuntu in 1.18 and this issue is not noticeable. Using it  in 1.17 and 1.16 instead of `ntp` seems the best way to go.
https://github.com/kubernetes/kops/blob/82257362184894e882bdbba79e79840c2b89b340/nodeup/pkg/model/ntp.go#L60-L64
=> Use systemd-timesyncd for Ubuntu 20.04

upup/models/vfs.go, util/pkg/vfs/fs.go, util/pkg/vfs/gsfs.go, util/pkg/vfs/k8sfs.go, util/pkg/vfs/memfs.go, util/pkg/vfs/ossfs.go, util/pkg/vfs/s3fs.go, util/pkg/vfs/sshfs.go, util/pkg/vfs/swiftfs.go, util/pkg/vfs/vfs.go
Kops uses versioned S3 buckets for the state store, which is also used for storing etcd backups.
Currently versions are not deleted and the bucket usage keeps growing over time.
`etcd-manager` should be adjusted to use this change.
The change works for both versioned and unversioned buckets. In the case of unversioned bucket, the version ID is "null" and deletion still works as expected.
This won't fix older versions that were not deleted, but going forward removal should be permanent.
=> Remove all versions of a file form the S3 bucket

OWNERS
@gjtempleton has been active in reviewing and authorship and meets the requirements for being a kops reviewer.
/cc @gjtempleton
=> Add gjtempleton as reviewer

pkg/model/components/etcd.go, pkg/model/components/etcdmanager/model.go, pkg/model/components/etcdmanager/tests/minimal/tasks.yaml, pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Cherry pick of #9184 on release-1.17.
#9184: Update etcd-manager to 3.0.20200527
=> Automated cherry pick of #9184: Update etcd-manager to 3.0.20200527

upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
Cherry pick of #9179 on release-1.17.
#9179: Update DigitalOcean cloud-controller-manager to v0.1.24
=> Automated cherry pick of #9179: Update DigitalOcean cloud-controller-manager to v0.1.24

nodeup/pkg/model/ntp.go
Cherry pick of #9182 on release-1.16.
#9182: Use systemd-timesyncd for Ubuntu 20.04
=> Automated cherry pick of #9182: Use systemd-timesyncd for Ubuntu 20.04

WORKSPACE
This version contains a fix required for multi architecture support when creating container images:
https://github.com/bazelbuild/rules_docker/releases/tag/v0.14.2
=> Update Bazel rules for Docker to v0.14.2

docs/getting_started/digitalocean.md, upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Cherry pick of #9181 on release-1.17.
#9181: Use debian as default image for DO images
=> Automated cherry pick of #9181: Use debian as default image for DO images

docs/releases/1.18-NOTES.md, pkg/apis/kops/validation/legacy.go, pkg/apis/kops/validation/validation.go, pkg/apis/kops/validation/validation_test.go
This proposes to remove support for the legacy etcd provider for clusters running Kubernetes 1.18 or later.
=> Remove support for the legacy etcd provider as of k8s 1.18

pkg/model/iam/iam_builder.go, upup/models/vfs.go, util/pkg/vfs/fs.go, util/pkg/vfs/gsfs.go, util/pkg/vfs/k8sfs.go, util/pkg/vfs/memfs.go, util/pkg/vfs/ossfs.go, util/pkg/vfs/s3fs.go, util/pkg/vfs/sshfs.go, util/pkg/vfs/swiftfs.go, util/pkg/vfs/vfs.go
Cherry pick of #9171 #9188 on release-1.17.
#9171: Remove all versions of a file form the S3 bucket
#9188: Fix nits for removal of S3 file versions
=> Automated cherry pick of #9171: Remove all versions of a file form the S3 bucket #9188: Fix nits for removal of S3 file versions

upup/pkg/fi/nodeup/nodetasks/package.go
I think the refactoring of `package.go` in https://github.com/kubernetes/kops/commit/6b011c044b3b7d0455bd9815ff29a908eefe3e0c  introduced a bug that keeps repo packages from being installed. 
From https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-k8s-latest/1266103273169883138/artifacts/54.249.221.142/kops-configuration.log
```
I0528 20:27:01.652991     836 package.go:299] Installing package "chrony" (dependencies: [])
I0528 20:27:01.653018     836 package.go:355] running command [apt-get install --yes --no-install-recommends]
```
```
I0528 20:48:51.349091    6615 executor.go:103] Tasks: 64 done / 65 total; 1 can run
I0528 20:48:51.349125    6615 executor.go:174] Executing task "Service/chrony": Service: chrony
I0528 20:48:51.349177    6615 changes.go:81] Field changed …
```
=> Fix repo packages not being installed
