kubernetes/kops

- README.md
Drop some optional arguments that are just noise
> docs: streamline readme

- upup/pkg/fi/cloud.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
Also add the new ap-south-1 region
> More diagnostics when an AZ is not recognized

- docs/changing_configuration.md
The procedure could definitely use some work!
> Initial docs for how to apply a configuration change

- doc.go
> Add dummy go source to root, to avoid go get warning

- README.md
Make it clearer that the cluster name should be a DNS name.
Fix #28
> docs: provide more hints about how to choose a cluster name

- upup/pkg/fi/cloudup/awstasks/iaminstanceprofile.go
This should avoid spurious errors when creating dependent resources,
which fail if we try to create before the InstanceProfile is fully
created.
Issue #35
> Wait for InstanceProfile to be readable after creation

- cmd/kops/addons.go
Issue #43 (not a fix though, just something observed in that issue)
> Fix formatting in error message

- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
When we retry a task, we run the Run method again.  But in this case,
the run method actually populated some default values.  Only warn if the
values we are populating are different, to avoid spurious warnings.
We probably need a stronger lifecycle - for example having a Validate
method would probably be helpful.
Fix #48
> Only warn if a _different_ ephemeral device is attached

- upup/pkg/fi/cloudup/awstasks/sshkey.go
Just in case it contains invalid characters
Issue #63
> Quote public key in error message

- upup/pkg/fi/cloudup/awstasks/sshkey.go
- upup/pkg/fi/cloudup/awstasks/sshkey_test.go
Issue #63
Edit: And fix the reported problem also :-)
> Add tests for SSH key fingerprint

- upup/pkg/fi/cloudup/awstasks/sshkey.go
> Fix typo in error message

- upup/pkg/fi/cloudup/awsup/machine_types.go
> Add support for r3 family

- upup/pkg/fi/nodeup/nodetasks/service.go
We were previously just starting them, which works fine for the new
machine and machine termination case, but doesn't work when doing a
machine restart (e.g. init 6)
Issue #70
> Make sure that we enable systemd services

- upup/pkg/kutil/delete_cluster.go
Initial implementation: we match by name, for example; when we have a
hosted zone id we should plumb it through.
Does implement bulk deletion, because on Route53 we have to delete
multiple resources at once.
Issue #74
> Delete Route53 host records on cluster-down

- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
> More tweaks to the IAM async creation tolerance

- cmd/kops/edit_instancegroup.go
- cmd/kops/editor.go
- cmd/kops/format.go
- cmd/kops/get_cluster.go
- cmd/kops/get_instancegroups.go
This lets us start to manage instancegroups through the CLI
> Support `kops get/edit instancegroup`

- cmd/kops/delete_cluster.go
- cmd/kops/format.go
- cmd/kops/get_cluster.go
- cmd/kops/get_instancegroups.go
- cmd/kops/secrets_expose.go
* Move delete output to table helper
* Sort table rows in tables
> Move delete output to table helper

- upup/pkg/kutil/delete_cluster.go
Again we delete by name, which is why we name them by the very unlikely
to conflict name "kubernetes.<clustername>"
Issue #107
> Delete cluster deletes keypairs

- upup/models/cloudup/_aws/master/_master_asg/master_asg.yaml
- upup/models/cloudup/_aws/nodes.yaml
- upup/pkg/api/instancegroup.go
- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
> Add support for spot instances

- Makefile
- cmd/kops/version.go
> Add version command that prints compiled version

- cmd/kops/create_cluster.go
- docs/arguments.md
- upup/models/cloudup/_aws/master/_master_lb/master_lb.yaml
- upup/models/cloudup/_aws/master/_not_master_lb/not_master_lb.yaml
- upup/models/cloudup/_aws/master/master.yaml
- upup/models/cloudup/_aws/nodes.yaml
- upup/models/cloudup/_gce/master.yaml
- upup/models/cloudup/_gce/network.yaml
- upup/pkg/api/cluster.go
- upup/pkg/api/validation.go
- upup/pkg/fi/cloudup/create_cluster.go
- upup/pkg/fi/cloudup/template_functions.go
> Configuration of admin access to ports 22 and master-443

- upup/pkg/kutil/import_cluster.go
- upup/pkg/kutil/utils.go
We now query for the launchconfiguration and import the first machine
type we find.
Fix #148
> Import the node instance type when importing a cluster

- upup/pkg/fi/values.go
(I hope)
Also cover more of the cases
Fix #167
> Fix nil dereference correctly

- upup/pkg/api/componentconfig.go
- upup/pkg/fi/cloudup/create_cluster.go
> Populate kube-apiserver apiserver-count flag for HA

- upup/models/cloudup/_aws/resources/iam/kubernetes-master-policy.json.template
- upup/models/cloudup/_aws/resources/iam/kubernetes-master-role.json.template
- upup/models/cloudup/_aws/resources/iam/kubernetes-node-policy.json.template
- upup/models/cloudup/_aws/resources/iam/kubernetes-node-role.json.template
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/template_functions.go
> Adapt IAM policies when running in cn-north-1

- upup/pkg/fi/cloudup/awstasks/internetgateway.go
We currently don't do discovery of existing resources when running with
Terraform output, but when using a shared VPC this is wrong - we need to
reuse the existing gateway.
Directly discover the existing gateway.  We might need to do full
discovery later, but for now this is sufficient.
Fix #181
> Discover an existing InternetGateway when running with Terraform Output

- cmd/kops/edit_cluster.go
- cmd/kops/edit_instancegroup.go
- upup/pkg/fi/cloudup/populatecluster_test.go
Also add some tests, and fix some variable naming to hopefully stop it
happening again.
Fix #194
> Fix bug where edit cluster was computing with the old spec

- upup/models/config/components/kubelet/kubelet.options
This should be a little faster
> Make sure master uses 127.0.0.1:8080 to reach apiserver

- cmd/kops/delete_cluster.go
- cmd/kops/import_cluster.go
- docs/upgrade_from_k8s_12.md
- upup/pkg/kutil/delete_cluster.go
- upup/pkg/kutil/import_cluster.go
Seems to be less special-cased also.
Fix #216
> support multiple zones in `kops import`

- docs/creating_subdomain.md
My little contribution for kops.
> How to add NameServer with AWS

- upup/pkg/kutil/kubecfg_builder.go
- upup/pkg/kutil/kubectl.go
> Fix log message of shell commands

- cmd/kops/get_secrets.go
- cmd/kops/secrets_describe.go
- cmd/kops/secrets_get.go
- upup/pkg/fi/ca.go
- upup/pkg/fi/vfs_castore.go
Matches our naming pattern, and now using our text grid output
> Add `kops get secrets` command

- upup/pkg/fi/cloudup/terraform/target.go
Thanks for reporting @azell
Fix #235
> Fix concurrent map write bug in TF creation

- README.md
- upup/pkg/kutil/kubecfg_builder.go
> Better output when kubectl not in PATH

- cmd/kops/root.go
> Make it clearer when we use the cluster from kubecfg

- docs/run_in_existing_vpc.md
> Remove lingering reference to --dryrun mode

- cmd/kops/get.go
- cmd/kops/get_cluster.go
- cmd/kops/get_instancegroups.go
Also for instance groups.
Hat-tip to @zmerlynn for the suggestion.
> Expose full spec, by `kops get cluster -oyaml`

- cmd/kops/create_secret_sshpublickey.go
- cmd/kops/delete_secret.go
- docs/secrets.md
- upup/pkg/fi/vfs_castore.go
> More consistency in publickey CLI

- upup/pkg/api/componentconfig.go
- upup/pkg/fi/cloudup/populatecluster_test.go
> Add docker flags: insecure-registry and mtu

- cmd/kops/create_cluster.go
- cmd/kops/root.go
- cmd/kops/update_cluster.go
- docs/upgrade_from_k8s_12.md
- upup/models/cloudup/_aws/master/_master_asg/master_asg.yaml
- upup/models/cloudup/_aws/master/_master_single/master_single.yaml
- upup/models/cloudup/_aws/nodes.yaml
- upup/models/cloudup/_aws/sshkey.yaml
- upup/pkg/fi/ca.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/awstasks/sshkey.go
- upup/pkg/fi/cloudup/awstasks/sshkey_test.go
- upup/pkg/kutil/delete_cluster.go
* Use the SSH key stored in secrets
* Support changing the SSH key
> SSH key improvements

- cmd/kops/create_cluster.go
- cmd/kops/export_kubecfg.go
- cmd/kops/update_cluster.go
- docs/addons.md
- upup/pkg/kutil/create_kubecfg.go
- upup/pkg/kutil/kubecfg_builder.go
This is where users expects to find it, because it is how kube-up does
it.
Issue #166
> Export admin password in kubecfg

- upup/models/config/components/kube-dns/kube-dns.options
Change the default to a more sensible starting point.
> DNS is a SPOF; make sure there are replicas

- cmd/kops/create_cluster.go
- cmd/kops/root.go
- cmd/kops/update_cluster.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/dryrun_target.go
> If no changes are needed in an update, don't print a confusing message

- upup/pkg/fi/nodeup/build_flags.go
- upup/pkg/fi/nodeup/nodetasks/service.go
- upup/pkg/fi/utils/reflect.go
* Correctly identify user tasks as a dependency for services
* Cleaned up flag-walking
> A few nodeup cleanups

- cmd/kops/get_cluster.go
- cmd/kops/root.go
> Warn if KOPS_STATE_STORE is not an S3 bucket

- cmd/kops/upgrade_cluster.go
- docs/upgrade.md
> Document cleaned up upgrade command

- cmd/kops/rollingupdate_cluster.go
- upup/pkg/kutil/rollingupdate_cluster.go
It makes testing it much easier, for one!
> Add force command to rolling-update

- docker/build-squash-push.sh
Pretty sure I broke that in the second to last commit. :)
> CI: Fix relative pathing

- docker/build-squash-push.sh
> CI: Fix another BUILD_TAG case (typo)

- .gitignore
- docker/Dockerfile
- docker/build-squash-push.sh
Changes the build to copy the source in, instead of pulling from git, isolating it to the machine involved (and setting it up for PR building).
> Build: Build from source

- docker/build-squash-push.sh
Default to cleaning up the tag unless asked.
> Build: Refine slightly how the tag is cleaned

- Makefile
We should have a target for all our supported versions
> Add makefile target for go16 as well

- upup/models/nodeup/_protokube/services/protokube.service.template
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/nodeup/config.go
- upup/pkg/fi/nodeup/loader.go
- upup/pkg/fi/nodeup/template_functions.go
We introduce two env vars:
* NODEUP_URL url to nodeup that we want to run
* PROTOKUBE_IMAGE specifies the protokube Docker image to run
> Make it easy to run a custom build

- upup/pkg/fi/vfs/s3fs.go
It was one line of code.  Gotta love that.  Tested locally with a couple of runs.  May work on getting a setup locally for testing in Jenkins.
> Enabled server side encryption

- upup/models/cloudup/_aws/resources/iam/kubernetes-master-policy.json.template
- upup/models/cloudup/_aws/resources/iam/kubernetes-node-policy.json.template
While I deal with the case where the KOPS_STATE_STORE has a path
> Temporarily revert #365

- upup/pkg/api/validation.go
Pretty straightforward! :grin:
Fix #346
> Better error message when zone is typoed

- cmd/kops/create_cluster.go
- upup/pkg/api/cluster.go
> Change default networking model to kubenet

- docs/images.md
Explain that ubuntu is not yet tested
> More docs on custom images

- cmd/kops/update_cluster.go
- upup/models/cloudup/_aws/master/_master_asg/master_asg.yaml
- upup/models/cloudup/_aws/master/_master_single/master_single.yaml
- upup/models/cloudup/_aws/nodes.yaml
- upup/models/cloudup/_aws/resources/nodeup.sh.template
- upup/models/cloudup/_gce/master.yaml
- upup/models/cloudup/_gce/nodes.yaml
- upup/models/cloudup/resources/config.yaml.template
- upup/models/nodeup/kubelet/files/etc/sysconfig/kubelet.template
- upup/pkg/api/cluster.go
- upup/pkg/api/componentconfig.go
- upup/pkg/api/instancegroup.go
- upup/pkg/api/kubeletconfig.go
- upup/pkg/api/registry.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/spec_builder.go
- upup/pkg/fi/cloudup/tagbuilder.go
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/nodeup/build_flags.go
- upup/pkg/fi/nodeup/command.go
- upup/pkg/fi/nodeup/config.go
- upup/pkg/fi/nodeup/template_functions.go
A lot of supporting work was needed, including improvements to the model and model generation logic.
> Support labels on k8s nodes & AWS instances

- vendor/k8s.io/kubernetes/federation/pkg/dnsprovider/providers/aws/route53/zone.go
Fixing error from version skew / failure to check in correct version
> Fix integration error

- cmd/kops/upgrade_cluster.go
In particular, the cluster name
> Support positional args in upgrade cluster

- cmd/kops/root.go
Previously we were relying on k8s to do it for us
Fix #442
> Always set logtostderr

- upup/pkg/fi/cloudup/iam_builder.go
This PR will add the KMS IAM permissions to the master role, so that the master can attach encrypted etcd EBS volumes that use a custom KMS key. Prior to this PR, a user would have to manually whitelist the master role, this PR automates this step.
We restrict the KMS permissions to only the KMS key IDs that are set for the encrypted etcd volumes. If there are no encrypted etcd volumes with custom KMS keys, then no KMS IAM permissions will be created.
> Add KMS IAM permissions

- upup/pkg/api/componentconfig.go
> Map Master & LogLevel flags for kube-scheduler

- upup/models/cloudup/_aws/master/master.yaml
- upup/models/cloudup/_aws/nodes.yaml
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/awstasks/securitygroup.go
- upup/pkg/fi/cloudup/awstasks/securitygrouprule.go
- upup/pkg/fi/context.go
- upup/pkg/fi/default_methods.go
- upup/pkg/fi/deletions.go
- upup/pkg/fi/dryrun_target.go
- upup/pkg/fi/nodeup/command.go
We don't normally need to delete items, but we do need to purge old
security group rules.
> Support deletion of items

- upup/pkg/fi/cloudup/awstasks/securitygroup.go
We are removing ELB security group rules
Issue #478
> Revert security group deletion

- cmd/kops/create_cluster.go
- cmd/kops/update_cluster.go
- docs/arguments.md
- upup/pkg/fi/cloudup/apply_cluster.go
> Don't add terraform to --out

- upup/models/config/components/kubelet/kubelet.options
The equivalent of https://github.com/kubernetes/kubernetes/pull/32886
Fix #469
> Bump master CIDR to /29

- upup/models/config/components/kube-proxy/kube-proxy.options
- upup/models/nodeup/_kubernetes_master/kube-dns/files/etc/kubernetes/addons/dns/kubedns-rc.yaml.template
> Update resource requests to match official values

- upup/models/cloudup/_aws/resources/nodeup.sh.template
Just in case nobody else sets it!
> Call /bin/systemd-machine-id-setup as part of init

- cmd/kops/rollingupdate_cluster.go
Otherwise it's possible to get "stuck" if the API is down
> If the API is down in a rolling-update, support --cloudonly

- upup/pkg/api/componentconfig.go
As I think I introduced a schema change
> Revert AdmissionControl change in 507

- cmd/kops/delete_cluster.go
> Clean up delete cluster messaging

- cmd/kops/upgrade_cluster.go
> Remove unused import which breaks make

- docs/labels.md
> Add docs for labels

- upup/models/config/components/docker/docker.options
- upup/pkg/api/dockerconfig.go
- upup/pkg/fi/nodeup/command.go
nodeup will then choose the first supported driver.
This is how we can be image-independent
> Support a list of docker storage drivers

- util/pkg/vfs/s3fs.go
- util/pkg/vfs/vfs.go
> Skip directory objects in S3 when listing files

- upup/pkg/fi/nodeup/template_functions.go
More efficient and prevents circular dependencies
> Point kube-proxy to localhost when running on master

- upup/models/nodeup/_kubernetes_master/kube-apiserver/files/etc/kubernetes/manifests/kube-apiserver.manifest.template
Makes for much more obvious diffs
> Switch kube-apiserver manifest to YAML

- channels/cmd/channels/apply_channel.go
- channels/cmd/channels/get_addons.go
- channels/pkg/channels/addon.go
- channels/pkg/channels/addons.go
- protokube/pkg/protokube/channels.go
This allows us to move them to a dedicated addons repo later.
> Allow channels tool to understand well-known short references

- cmd/kops/edit_instancegroup.go
It can generate it instead, which helps if there has been a schema
change.
> `kops edit ig` shouldn't ready full cluster spec

- Makefile
- dns-controller/cmd/dns-controller/main.go
- dns-controller/docs/flags.md
- dns-controller/pkg/dns/dnscontroller.go
- dns-controller/pkg/dns/zonespec.go
- upup/models/cloudup/manifests/addons.yaml
- upup/models/cloudup/resources/addons/bootstrap-channel.yaml
- upup/models/cloudup/resources/addons/dns-controller/addon.yaml
- upup/models/cloudup/resources/addons/dns-controller/v1.4.1.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
> Configure dns-controller with ID of hosted zones

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
> Turn on verbose credentials error messages

- Makefile
- cmd/kops/update_cluster.go
- examples/README.md
- examples/kops-api-example/apply.go
- examples/kops-api-example/main.go
- upup/pkg/fi/cloudup/apply_cluster.go
> More API examples

- upup/pkg/fi/nodeup/nodetasks/update_packages.go
Fixes #635
One thing to note with this PR is that it imports `syscall`. In the docs it says:
>The primary use of syscall is inside other packages that provide a more portable interface to the system, such as "os", "time" and "net". Use those packages rather than this one if you can.
An alternative way to fix this that is not dependent on `syscall` is to do something like:
```
if state := cmd.ProcessState; err != nil && state.String() != "exit status 100" {
return fmt.Errorf("error update packages: %v: %s", err, string(output))
}
```
Despite the message in the docs, the usage of `syscall` seems appropriate to me. The risk is low, because the usage is limited, and it seems better to compare the exit code against an int, rather than a string. If someone feels we shouldn't be using `syscall` …
> Handle exit code 100 from 'yum check-update'

- README.md
So our title now claims we are prod ready... so should our README
> Removing WIP line from README

- cmd/kops/create_cluster.go
> Fix flag description on dns-zone

- upup/pkg/fi/cloudup/awstasks/routetableassociation.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
We don't have a lot of choice here; also try to provide more status
feedback.
This is not a true fix, it merely extends the timeouts.
Issue #597
> Wait longer for eventual consistency convergence

- upup/pkg/fi/dryrun_target.go
Issue #600 
Admittedly a slightly speculative fix, but nothing else makes sense (that I can see!)
> Avoid concurrent append to slices in DryRunTarget

- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
From 1 minute -> 5 minutes
Should help with issue #591
> Increase timeout for IAM instance propagation

- docs/upgrade_from_k8s_12.md
- pkg/apis/kops/validation.go
- upup/models/cloudup/_aws/network.yaml
- upup/pkg/fi/vfs_castore.go
- upup/pkg/kutil/convert_kubeup_cluster.go
- upup/pkg/kutil/delete_cluster.go
- upup/pkg/kutil/import_cluster.go
Some of the validation & changes we introduced broke the kube-up upgrade.
> Fix upgrade from kube-up

- upup/models/nodeup/kubelet/services/kubelet.service
- upup/pkg/fi/nodeup/nodetasks/load_image.go
- upup/pkg/fi/nodeup/nodetasks/service.go
Tested with manual build and NODEUP_URL
Fixes #685, #686
> nodeup: Add docker.service dep to LoadImageTask

- upup/pkg/fi/cloudup/validation_test.go
> Add unit test for imported cluster name

- upup/pkg/kutil/kubectl.go
> Don't merge stdout & stderr when running kubectl

- upup/pkg/fi/cloud.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
- upup/pkg/fi/cloudup/gce/gce_cloud.go
- upup/pkg/fi/cloudup/populate_cluster_spec.go
- upup/pkg/fi/cloudup/utils.go
Issue #585
Also, move FindDNSHostedZone to utils
> Check NS records as part of kops apply

- channels/stable
kubernetes 1.4.3
Kernel 4.2.26
> Update stable channel

- upup/pkg/fi/cloud.go
- upup/pkg/fi/cloudup/awsup/aws_utils.go
- upup/pkg/fi/cloudup/awsup/aws_utils_test.go
- upup/pkg/fi/cloudup/populate_instancegroup_spec.go
- upup/pkg/fi/cloudup/populateinstancegroup_test.go
- upup/pkg/fi/cloudup/utils.go
Our defaulting logic didn't recognize the new us-east-2 AZs
> Add support for new us-east-2 region

- README.md
I want to add more features - but opening this as a WIP for now - feedback please!
> [WIP] Readme Updates to Kops

- code-of-conduct.md
adding the kode of konduct
Fixes this https://github.com/kubernetes/kops/issues/740
> adding k8s code of conduct

- docs/build.md
RE: https://github.com/kubernetes/kops/issues/719
> Adding note on the kops build directory structure

- cmd/kops/util/factory.go
> Better error message when KOPS_STATE_STORE not set

- docs/images.md
* make heading for the ubuntu image
* add links for the debian images
Fix #756
> Improve docs for images & the ubuntu image

- pkg/apis/kops/versions.go
CI builds are broken right now.
> Quick fix: add v1.[67] to valid version checks

- upup/models/cloudup/_aws/topologies/_topology_private/bastion.yaml
Fix for issue - https://github.com/kubernetes/kops/issues/862
**What?**
Yaml parsing was failing when `kops update cluster uswest1.clusters.mydomainexample.com --yes`
> Comment should be inside the if block - bastion.yaml

- docs/development/hack.md
- hack/dev-build.sh
Any recommendations for the DNS stuff???  Otherwise, this script is AWESOME.
@razic any comments?
> Hack dev scripts

- Makefile
> Add examples to CI

- docs/development/instancesizes.md
- protokube/model/etcd/main.config
- upup/models/nodeup/_kubernetes_master/kube-apiserver/files/etc/kubernetes/manifests/kube-apiserver.manifest.template
- upup/models/nodeup/_kubernetes_master/kube-controller-manager/files/etc/kubernetes/manifests/kube-controller-manager.template
> Reduce CPURequests, so we can run on 1 core machine

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
> Bump retries up to ~6m for a request

- cmd/kops/create_cluster.go
- docs/networking.md
- hack/dev-build.sh
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha1/networking.go
- upup/models/cloudup/resources/addons/networking.weave/v1.8.0.20161116.yaml
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/networking.go
- upup/pkg/fi/cloudup/tagbuilder.go
This drops in weave vendoring into `kops`
> Weave implementation

- cmd/kops/create_cluster.go
- hack/dev-build.sh
- pkg/apis/kops/cluster.go
- upup/pkg/fi/cloudup/tagbuilder.go
- upup/pkg/fi/cloudup/tagbuilder_test.go
> Weave implementation part 2

- images/dns-controller-builder/Dockerfile
- images/protokube-builder/Dockerfile
> Build protokube & dns-controller with go 1.7.3

- dns-controller/pkg/dns/record.go
- dns-controller/pkg/watchers/nodecontroller.go
- dns-controller/pkg/watchers/servicecontroller.go
> Support aliases for NodePort services

- README.md
@justinsb and @chrislovecnm 
Can I get +1's from each of you please on this? It's what we discussed on our last call - but need each of you to awk this so you know what trouble I am getting you into :) 
Cheers
PS:
Do we need to add anyone else?
> Adding office hours to README

- Makefile
- protokube/pkg/protokube/kube_boot.go
- upup/models/nodeup/_protokube/services/protokube.service.template
- upup/models/nodeup/kubelet/services/kubelet.service
- upup/models/nodeup/kubelet/services/kubelet.service.meta
- upup/pkg/fi/nodeup/command.go
- upup/pkg/fi/nodeup/nodetasks/service.go
- upup/pkg/fi/nodeup/template_functions.go
* Change protokube to do `systemctl start kubelet` every sync round
* .. which takes a change to the systemd unit for protokube to mount in D-Bus
* Don't start kubelet in nodeup
> Disable kubelet from starting until after volume mounts

- cmd/kops/get_instancegroups.go
> Fix printing of max size on instance group

- pkg/apis/kops/cluster.go
- upup/pkg/fi/cloudup/populatecluster_test.go
> Avoid tests hitting kubernetes stable.txt HTTP file

- upup/pkg/fi/cloudup/awstasks/natgateway.go
- upup/pkg/fi/cloudup/awstasks/route.go
So users know what is happening
> Refactor wait-for-NAT-gateway code & add log messages

- docs/topology.md
@chrislovecnm please review and see if these notes help
Closes https://github.com/kubernetes/kops/issues/981
> Adding notes on bastion agent forwarding

- addons/cluster-autoscaler/README.md
- addons/cluster-autoscaler/addon.yml
- addons/cluster-autoscaler/v1.4.0.yaml
addresses issue https://github.com/kubernetes/kops/issues/341
required for https://github.com/kubernetes/contrib/issues/2004
> cluster autoscaler addon

- cloudmock/aws/mockec2/api.go
- cloudmock/aws/mockec2/routetable.go
- cloudmock/aws/mockec2/unimplemented.go
- upup/pkg/fi/cloudup/awstasks/natgateway.go
- upup/pkg/fi/cloudup/awstasks/securitygroup_test.go
Yo we need the darn munger fixed.  Maybe we just run it during the commit post hook :(
Anyways.  Fixed for legal :)
> updating header

- upup/pkg/fi/cloudup/awsup/machine_types.go
adds the following machine types:
* r4.large
* r4.xlarge
* r4.2xlarge
* r4.4xlarge
* r4.8xlarge
* r4.16xlarge
* t2.xlarge
* t2.2xlarge
> adds more machine types

- upup/models/cloudup/resources/addons/networking.weave/v1.8.1.20161130.yaml
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
bumped weave to 1.8.1
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1021)
> bumping weave version

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1038)
> Include error in message when we fail to query AZs

- dns-controller/pkg/dns/zonespec_test.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1034)
> Apply gofmt

- dns-controller/pkg/dns/record_test.go
- dns-controller/pkg/dns/zonespec_test.go
- dns-controller/pkg/util/equality_test.go
OMG we need this in the ci build
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1042)
> updating headers

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/awsup/logging_retryer.go
- upup/pkg/fi/cloudup/awsup/request_logger.go
Also of logging at v=2
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1046)
> Add logging of AWS retries

- upup/pkg/fi/executor.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1045)
> Print time remaining to succeed as a positive value

- Makefile
- dns-controller/pkg/dns/record_test.go
- dns-controller/pkg/dns/zonespec_test.go
- dns-controller/pkg/util/equality_test.go
- hack/verify-boilerplate.sh
checking that headers are correct!  BTW I have a PR in for fixing some of the headers.  Until that PR is in, this build should fail.
closes: https://github.com/kubernetes/kops/issues/734
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1044)
> adding hack/verify-boilerplate.sh to make ci target

- Makefile
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1047)
> Add verify-boilerplate target

- .gitmodules
- pkg/diff/diff.go
- pkg/diff/diff_test.go
- upup/pkg/fi/dryrun_target.go
- vendor/github.com/sergi/go-diff/.gitignore
- vendor/github.com/sergi/go-diff/.travis.yml
- vendor/github.com/sergi/go-diff/APACHE-LICENSE-2.0.txt
- vendor/github.com/sergi/go-diff/LICENSE.txt
- vendor/github.com/sergi/go-diff/Makefile
- vendor/github.com/sergi/go-diff/README.md
- vendor/github.com/sergi/go-diff/diffmatchpatch/dmp.go
- vendor/github.com/sergi/go-diff/diffmatchpatch/dmp_test.go
- vendor/github.com/sergi/go-diff/diffmatchpatch/speedtest1.txt
- vendor/github.com/sergi/go-diff/diffmatchpatch/speedtest2.txt
- vendor/github.com/sergi/go-diff/scripts/lint.sh
Fix #973
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/997)
> Format resource diffs

- README.md
- docs/development/homebrew.md
- docs/update_kops.md
- hack/brew/kops.rb
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/989)
> Add brew install documentation

- pkg/apis/kops/validation.go
- upup/pkg/fi/cloudup/template_functions.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1056)
> Hotfix for segfaults

- upup/pkg/fi/cloudup/template_functions.go
Fix mistake in rebase
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1065)
> Remove unused import

- upup/pkg/fi/cloudup/awstasks/elastic_ip.go
- upup/pkg/fi/cloudup/awstasks/natgateway.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1072)
> Fixes to existing NAT gateway detection

- cmd/kops/util/factory.go
closes: https://github.com/kubernetes/kops/issues/397
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1049)
> Serious STATE_STORE error message

- pkg/apis/kops/cluster.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1085)
> Simplify return

- hack/dev-build.sh
Tweaking the script to force the setting of an ami.  We should know which ami we are developing against anyways :) Called it $IMAGE because --image.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1031)
> removing our image and forcing setting of an ami

- upup/pkg/fi/cloudup/awstasks/elastic_ip.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1091)
> elastic ip cleanup

- upup/pkg/fi/cloudup/awstasks/dnsname.go
- upup/pkg/fi/cloudup/awstasks/elastic_ip.go
- upup/pkg/fi/cloudup/awstasks/load_balancer.go
- upup/pkg/fi/cloudup/awstasks/loadbalancer_attributes.go
- upup/pkg/fi/cloudup/awstasks/loadbalancer_connsettings.go
- upup/pkg/fi/cloudup/awstasks/loadbalancer_healthchecks.go
- upup/pkg/fi/cloudup/awstasks/natgateway.go
- upup/pkg/fi/cloudup/awstasks/securitygrouprule.go
Remove a few spurious changes
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1092)
> Cleanups to make kops update apply cleanly for private topologies

- upup/pkg/fi/cloud.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1108)
> Recognize ca-central-1 region

- cloudmock/aws/mockec2/address.go
- cloudmock/aws/mockec2/misc.go
- cloudmock/aws/mockec2/subnets.go
- cloudmock/aws/mockec2/tags.go
- cloudmock/aws/mockec2/unimplemented.go
- cloudmock/aws/mockec2/vpcs.go
- cloudmock/aws/mockroute53/api.go
- cloudmock/aws/mockroute53/unimplemented.go
- upup/pkg/fi/cloudup/awstasks/elastic_ip_test.go
- upup/pkg/fi/cloudup/awstasks/misc.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1096)
> First test of a fi.Task

- upup/pkg/fi/cloudup/loader.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1101)
> diagnostics: sort known tasks before printing

- cmd/kops/create_ig.go
- pkg/apis/kops/instancegroup.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1106)
> Allow role specification on kops create ig

- cmd/kops/create_ig.go
- cmd/kops/edit_cluster.go
- cmd/kops/edit_federation.go
- cmd/kops/edit_instancegroup.go
- cmd/kops/get_cluster.go
- cmd/kops/get_federation.go
- cmd/kops/get_instancegroups.go
- cmd/kops/util/factory.go
- federation/federation_cluster.go
- federation/federation_configuration.go
- pkg/apis/kops/channel.go
- pkg/apis/kops/codecs.go
- pkg/apis/kops/parse.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/kutil/kubecfg_builder.go
In particular during a kops edit
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1089)
> Use versioned marshaling where we can

- docs/run_in_existing_vpc.md
See https://github.com/kubernetes/kops/issues/476
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1022)
> Add documentation about incorrect VPC diffing

- README.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1076)
> more detailed installation instructions

- upup/pkg/fi/loader/tree_walker.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1121)
> Improve log message when skipping log

- docs/releases.md
Documentation on the release process
Note: This is just a starting point, ideally I could get some feedback from @justinsb and @chrislovecnm as we get closer to doomsday
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1053)
> Release Process Documentation 

- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Closes https://github.com/kubernetes/kops/issues/1099
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1125)
> Removing workaround for #241

- cmd/kops/validate_cluster.go
- prettier output
- fixing panic
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1133)
> Validation fix

- hack/dev-build.sh
I think we are missing a `.s3` in there >.<
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1127)
> Fixing $NODEUP_URL in /hak/dev-build.sh

- docs/development/adding_a_feature.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1135)
> Fix broken link of cluster_spec.md

- cmd/kops/create_cluster.go
- cmd/kops/update_cluster.go
@kris-nova let me know if you see anything you'd like me to change.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1151)
> Display SSH Public key being used. Fixes issue #1140

- cloudmock/aws/mockec2/vpcs.go
- upup/pkg/fi/cloudup/awstasks/vpc_test.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1139)
> Add super-simple test for VPC task

- upup/pkg/fi/executor.go
Correctly this time ...
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1138)
> Fix display of time remaining

- README.md
This is a really minor improvement, but it was bugging me enough to make this PR :)
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1148)
> docs: Minor README formatting improvement.

- pkg/diff/diff.go
- pkg/diff/diff_test.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1156)
> Fix a bug in diff formatting

- addons/cluster-autoscaler/v1.4.0.yaml
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1167)
> fix bug in cluster autoscaler addon spec

- cloudmock/aws/mockec2/api.go
- cloudmock/aws/mockec2/unimplemented.go
- cloudmock/aws/mockec2/volumes.go
- cloudmock/aws/mockroute53/zones.go
Just stubs DescribeVolumes call
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1190)
> mockec2: first step towards volume support

- upup/pkg/fi/cloudup/template_functions.go
Non-trivial backport, but the same counting function
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1173)
> Backport #1048

- cloudmock/aws/mockec2/api.go
- cloudmock/aws/mockec2/securitygroups.go
- cloudmock/aws/mockec2/tags.go
- cloudmock/aws/mockec2/unimplemented.go
- upup/pkg/fi/cloudup/awstasks/securitygroup_test.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1193)
> Simple test for securitygroups task

- docs/networking.md
The `weave-kube` repo has been merged with `weave`. 
Save people a click.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1205)
> Update link to Weave repository.

- Makefile
- nodeup/pkg/model/architecture.go
- nodeup/pkg/model/context.go
- nodeup/pkg/model/convenience.go
- nodeup/pkg/model/distribution.go
- nodeup/pkg/model/docker.go
- nodeup/pkg/model/resources/docker.go
- pkg/apis/kops/cluster.go
- pkg/apis/kops/dockerconfig.go
- pkg/apis/kops/v1alpha1/dockerconfig.go
- pkg/apis/kops/v1alpha2/dockerconfig.go
- pkg/model/components/docker.go
- upup/models/nodeup/docker/files/usr/share/doc/docker/apache.txt
- upup/models/nodeup/docker/packages/_centos7/docker-engine
- upup/models/nodeup/docker/packages/_centos7/docker-engine-selinux
- upup/models/nodeup/docker/packages/_jessie/docker-engine
- upup/models/nodeup/docker/packages/_rhel7/docker-engine
- upup/models/nodeup/docker/packages/_rhel7/docker-engine-selinux
- upup/models/nodeup/docker/packages/_xenial/docker-engine
- upup/pkg/fi/cloudup/populate_cluster_spec.go
- upup/pkg/fi/cloudup/populatecluster_test.go
- upup/pkg/fi/nodeup/command.go
- upup/pkg/fi/nodeup/loader.go
- upup/pkg/fi/nodeup/nodetasks/file.go
- upup/pkg/fi/nodeup/nodetasks/package.go
- upup/pkg/fi/nodeup/tags.go
And automatically choose 1.12.3 for k8s >= 1.5, 1.11.2 for < 1.5
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1209)
> Configure DockerVersion in Docker Spec

- nodeup/pkg/model/docker_test.go
- nodeup/pkg/model/tests/dockerbuilder/docker_1.12.1/cluster.yaml
- nodeup/pkg/model/tests/dockerbuilder/docker_1.12.1/tasks.yaml
- nodeup/pkg/model/tests/dockerbuilder/simple/cluster.yaml
- nodeup/pkg/model/tests/dockerbuilder/simple/tasks.yaml
- upup/pkg/fi/nodeup/nodetasks/file.go
- upup/pkg/fi/nodeup/nodetasks/package.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1217)
> Add tests for docker nodeup side

- Makefile
- docs/build.md
#1074
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1224)
> Ability to cross-compile nodeup

- Makefile
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1237)
> Fix e2e: nodeup-dist can continue to build in docker

- docs/run_in_existing_vpc.md
Giving example for external netowrking
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/766)
> elaborate "external networking"

- README.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1261)
> Adding GoDoc widget - we really need to start coding with this in mind

- README.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1263)
> Readme updates!

- cmd/kops/create_cluster_integration_test.go
- tests/integration/create_cluster/private/expected-v1alpha1.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/options.yaml
Bastions are created when `-bastion` is passed.
Issue #1232
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1271)
> Add test for bastion creation

- channels/alpha
- pkg/apis/kops/channel.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1292)
> Create alpha channel for 1.5.1

- upup/models/cloudup/resources/addons/networking.kope.io/v1.0.20161116.yaml
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1293)
> Reduce CPU request for kopeio vxlan

- channels/stable
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1291)
> Run 1.4.7 in the stable channel

- upup/models/cloudup/resources/addons/dns-controller/v1.4.1.yaml.template
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1290)
> Run dnscontroller in host network, for faster bringup

- pkg/model/components/apiserver.go
- pkg/model/components/context.go
- pkg/model/components/docker.go
- pkg/model/components/networking.go
- upup/models/config/components/kubelet/_networking_classic/kubelet.classic.options
- upup/models/config/components/kubelet/_networking_cni/kubelet.cni.options
- upup/pkg/fi/cloudup/populate_cluster_spec.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1287)
> Only specify --configure-cbr0 when running with k8s <= 1.4

- cmd/kops/create_cluster.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1295)
> Fix gofmt & calico autogen

- cloudmock/aws/mockroute53/api.go
- cloudmock/aws/mockroute53/records.go
- cloudmock/aws/mockroute53/unimplemented.go
- cloudmock/aws/mockroute53/zones.go
- cmd/kops/integration_test.go
- pkg/featureflag/featureflag.go
- pkg/model/context.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/dns.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1006)
> Pre-create DNS records

- pkg/model/components/context.go
- pkg/model/components/kubelet.go
- upup/models/config/components/kubelet/kubelet.options
- upup/pkg/fi/cloudup/populate_cluster_spec.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1294)
> Only set PodCIDR on master in <= 1.4

- README.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1307)
> Getting rid of the comments, they are polluting the readme!

- docs/aws.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1256)
> Updating AWS to use pypi instead of brew

- cmd/kops/create.go
- pkg/apis/kops/cluster.go
- pkg/apis/kops/validation.go
- tests/integration/create_cluster/ha/expected-v1alpha1.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
- upup/pkg/fi/cloudup/defaults.go
Closes https://github.com/kubernetes/kops/issues/1002
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1254)
> Backport the backport

- cmd/kops/get_cluster.go
Fix #1238
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1269)
> Respect the name flag on cluster get

- cmd/kops/delete_cluster.go
- upup/pkg/kutil/kubecfg_builder.go
Fixes https://github.com/kubernetes/kops/issues/287
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1218)
> Delete kubectl config when deleting cluster

- pkg/model/bastion.go
- tests/integration/privatecalico/kubernetes.tf
- tests/integration/privateweave/kubernetes.tf
Only open port 22 (SSH)
Fix #1312
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1324)
> Lock down bastion->master/nodes

- pkg/model/components/context.go
- pkg/model/components/kubelet.go
- upup/models/config/components/kubelet/_isolate_masters/kubelet.options
- upup/models/config/components/kubelet/_networking_kubenet/kubelet.kubenet.options
- upup/models/config/components/kubelet/kubelet.options
- upup/pkg/fi/cloudup/tagbuilder.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1327)
> Don't specify configure-cidr for k8s >= 1.5

- pkg/featureflag/featureflag.go
- pkg/featureflag/featureflag_test.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1328)
> Add unit test for featureflag parsing

- cmd/kops/get_cluster.go
- cmd/kops/get_federation.go
- cmd/kops/get_instancegroups.go
Fix #1088
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1326)
> Separate yaml output with dashes

- hack/update-header.sh
Updating the script for the new year! Woo 🎉
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1258)
> Headers 2016->2017

- hack/boilerplate/boilerplate.py
And generally update to the latest upstream boilerplate script
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1356)
> Consider 2017 a year

- upup/models/cloudup/resources/addons/storage-aws/v1.5.0.yaml
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1304)
> Create storage class on AWS

- cmd/kops/root.go
- cmd/kops/toolbox.go
- cmd/kops/toolbox_convert_imported.go
- cmd/kops/toolbox_dump.go
- upup/pkg/kutil/delete_cluster.go
Can dump a VPC
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1274)
> First step towards cluster-dump command

- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
I forgot to update the tests previously
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1359)
> Fix storage tests

- channels/pkg/channels/addon.go
- channels/pkg/channels/addons.go
- channels/pkg/channels/channel_version.go
Looks like I forgot to update it for the k8s API update
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1362)
> Fix channels build

- channels/pkg/channels/addon.go
- channels/pkg/channels/addons.go
- channels/pkg/channels/channel_version.go
- upup/models/cloudup/resources/addons/storage-aws.addons.k8s.io/v1.5.0.yaml
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1361)
> Fix AWS storage manifest location

- README.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1363)
> make installation a heading

- cmd/kops/create_cluster.go
- docs/bastion.md
- docs/cli/kops.md
- docs/cli/kops_create_cluster.md
- docs/cli/kops_create_instancegroup.md
- docs/cli/kops_get.md
- docs/cli/kops_get_clusters.md
- docs/cli/kops_get_federations.md
- docs/cli/kops_get_instancegroups.md
- docs/cli/kops_replace.md
- docs/cli/kops_rolling-update_cluster.md
- docs/cli/kops_toolbox.md
- docs/cli/kops_toolbox_convert-imported.md
- docs/cli/kops_toolbox_dump.md
- pkg/model/bastion.go
- pkg/model/context.go
- pkg/model/dns.go
- Giving the bastion docs a much needed once over
- Fixing bastion bugs with hosted zones
- Support for the clustername/dnszone conundrum
- Removing references to `--bastion=true` as a user can just do `--bastion`
Closes https://github.com/kubernetes/kops/issues/1331
Closes https://github.com/kubernetes/kops/issues/1322
Closes https://github.com/kubernetes/kops/issues/1276
Closes (or at least addresses) https://github.com/kubernetes/kops/issues/1232 (I think this is now done)
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1364)
> Bug fixes and bastion reworking

- tests/integration/privatecalico/kubernetes.tf
- tests/integration/privateweave/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/load_balancer.go
Otherwise we can't delete
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1385)
> Tag ELBs when building with terraform

- cmd/kops/create_cluster.go
Fix #1373
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1398)
> De-emphasize cni for private topologies

- pkg/model/dns.go
- upup/pkg/fi/cloudup/populate_cluster_spec.go
Closes https://github.com/kubernetes/kops/issues/1394
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1399)
> Fixing hosted zone errors with bastion, and cleaning up dns model logic

- Makefile
- util/pkg/vfs/context.go
- util/pkg/vfs/s3fs.go
- util/pkg/vfs/s3fs_test.go
Fix #902
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1389)
> Raise an error on an invalid s3 path

- nodeup/pkg/model/sysctls.go
- upup/models/nodeup/networking/_aws/files/etc/sysctl.d/99-k8s-networking.conf
- upup/models/nodeup/networking/_aws/files/etc/sysctl.d/99-k8s-networking.conf.meta
- upup/models/nodeup/networking/_gce/files/etc/sysctl.d/99-k8s-networking.conf
- upup/models/nodeup/networking/_gce/files/etc/sysctl.d/99-k8s-networking.conf.meta
- upup/pkg/fi/nodeup/command.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1344)
> Set default sysctls

- docs/bastion.md
Closes https://github.com/kubernetes/kops/issues/1371
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1412)
> Docs on using the bastion

- cmd/kops/create_cluster.go
- pkg/apis/kops/cluster.go
- pkg/apis/kops/topology.go
- pkg/apis/kops/v1alpha1/conversion.go
- pkg/apis/kops/v1alpha1/defaults.go
- pkg/apis/kops/v1alpha1/topology.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/defaults.go
- pkg/apis/kops/v1alpha2/topology.go
- pkg/featureflag/featureflag.go
- pkg/model/context.go
- pkg/model/dns.go
- pkg/model/names.go
- tests/integration/conversion/integration_test.go
- tests/integration/conversion/minimal/v1alpha0.yaml
- tests/integration/conversion/minimal/v1alpha1.yaml
- tests/integration/conversion/minimal/v1alpha2.yaml
- tests/integration/create_cluster/ha/expected-v1alpha1.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha1.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
- upup/pkg/fi/cloudup/awstasks/dnszone.go
- upup/pkg/fi/task.go
Builds on #1268
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1345)
> Support private hosted zones in DNS

- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/addon.yaml
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/v1.5.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1406)
> Update to dns-controller 1.5.0

- upup/pkg/fi/nodeup/template_functions.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1408)
> Dial down default protokube logging to 4

- pkg/model/firewall.go
- tests/integration/minimal-141/kubernetes.tf
- tests/integration/minimal/kubernetes.tf
- tests/integration/privatecalico/kubernetes.tf
- tests/integration/privateweave/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/securitygrouprule.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1313)
> Lock down master security group rules

- pkg/client/simple/vfsclientset/commonvfs.go
Marked as WIP, because we need to merge the other schema-changing PRs first (or decide that they will not impact the schema in a backwards-incompatible way)
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1275)
> Store in v1alpha2 format

- nodeup/pkg/model/sysctls.go
Remove duplicate key; add missing blank line
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1407)
> Clean up sysctls

- channels/alpha
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1422)
> Bump to 4.4.41 image, with more regions

- dns-controller/pkg/dns/dnscontroller.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1423)
> Turn down no-change logging in dns-controller

- upup/pkg/fi/cloudup/awstasks/elastic_ip.go
We don't yet have a strong strategy for how to handle this if we are
interrupted, but the same problem exists with taggging in general.
Likely we'll need to write something like a WAL-log, and then check for
interrupted in-flight objects next time we run.
In any case, we shouldn't treat not using TagOnSubnet as an error.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1424)
> Don't fail elastic IP task if TagOnSubnet is not set

- cmd/kops/create_cluster.go
- cmd/kops/update_cluster.go
We were trying to do the same thing but the result was subtly different (because of
different defaulting.)  The two code paths makes testing hard, so just
have one code path.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1421)
> Use update cluster from create cluster

- Makefile
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1426)
> Update makefile for 1.5.0-alpha2

- dns-controller/pkg/dns/dnscontroller.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1430)
> DNS logging tweaks

- Makefile
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1443)
> Tag alpha3

- addons/kubernetes-dashboard/addon.yaml
- addons/kubernetes-dashboard/v1.5.0.yaml
- docs/addons.md
Closes #1375
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1379)
> Update kube dashboard in docs and addons/

- channels/alpha
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1460)
> Bump alpha channel to k8s 1.5.2

- upup/pkg/fi/cloudup/populate_instancegroup_spec.go
These newer regions don't support the m3 family; a c4.large is the
cheapest non-burstable instance.
Fix #1455
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1461)
> Set default master size for ca-central-1 and eu-west-2

- Makefile
- cmd/kops/version.go
- cmd/nodeup/main.go
- version.go
Fix #1462
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1482)
> Always include a gitsha in the version

- util/pkg/vfs/context.go
Fix #1441
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1488)
> Retry readHttpLocation on 500 errors

- hack/.packages
- nodeup/pkg/distros/distribution.go
- nodeup/pkg/distros/identify.go
- nodeup/pkg/model/context.go
- nodeup/pkg/model/docker.go
- upup/pkg/fi/nodeup/command.go
Part of splitting up the coreos PR
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1486)
> Split out distros into its own package

- cmd/kops/root.go
- federation/federation_cluster.go
- federation/federation_configuration.go
- hack/.packages
- pkg/kubeconfig/config.go
- upup/pkg/kutil/kubectl.go
Splitting up the coreos PR
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1485)
> Refactor kubeconfig into its own package

- upup/pkg/fi/cloudup/awsup/logging_retryer.go
Unclear if this will actually be sufficient, but it can't hurt
Fix #1437
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1495)
> Log more details when we retry on an AWS error

- hack/.packages
- nodeup/pkg/model/docker.go
- pkg/systemd/manifest.go
Part of splitting up the CoreOS PR
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1487)
> Split out systemd package

- hack/.packages
- pkg/flagbuilder/build_flags.go
- upup/pkg/fi/nodeup/template_functions.go
Splitting out the CoreOS PR
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1484)
> Move flagbuilder to a shared package

- federation/federation_configuration.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1505)
> fix adminToken not used

- docs/bastion.md
- docs/topology.md
Closes https://github.com/kubernetes/kops/issues/1371
CC @kris-nova
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1490)
> Removed troubleshooting from topology. Added to bastion docs.

- pkg/apis/kops/validation.go
Fix #1198
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1504)
> Validate that bastion IdleTimeout < 1 hour

- docs/etcd_backup.md
ref #1506
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1511)
> Add docs for backup of etcd in a cluster

- docs/cluster_spec.md
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/componentconfig.go
Based on #1357
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1438)
> Add OIDC flags

- cmd/kops/rollingupdate.go
- cmd/kops/rollingupdate_cluster.go
- cmd/kops/rollingupdatecluster.go
- cmd/kops/root.go
Fix #1265
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1270)
> Support rolling-update of a single instance group

- HA.md
Add a doc on HA
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1239)
> Add a doc on HA

- CONTRIBUTING.md
- LICENSE
- OWNERS
- code-of-conduct.md
- docs/development/release.md
Updating some of the base does to better mirror our template project.
Closes https://github.com/kubernetes/kops/issues/1023
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1040)
> updating base docs to match close to kubernetes-template-project

- upup/pkg/fi/cloudup/awstasks/load_balancer.go
- upup/pkg/fi/cloudup/awstasks/loadbalancer_attributes.go
Looks like I dropped this when refactoring - sorry!
Fix #1456
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1502)
> Apply ELB setting changes

- docs/aws.md
I was trying to use an already created hosted zone that was private. 
That doesn't work.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1548)
> Letting it clear that the hosted zone should be public

- docs/testing.md
@zmerlynn
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1469)
> Adding example code - Zach please comment

- docs/aws.md
- docs/ns.md
Response to https://github.com/kubernetes/kops/issues/859
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1552)
> Improve docs to prevent "Missing API" issues

- pkg/featureflag/featureflag.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1535)
> Fix feature flags potential deadlock

- protokube/pkg/protokube/volume_mounter.go
We primarily need to make sure we don't mount all the volumes on the
same instance.
This is not complete support for multiple masters (we still block it in `kops create`, but it is a start)
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1536)
> Support multi masters in a single AZ

- cmd/kops/create_cluster.go
- cmd/kops/create_cluster_integration_test.go
- cmd/kops/update_cluster.go
- docs/aws.md
- pkg/apis/kops/v1alpha1/cluster.go
- pkg/apis/kops/v1alpha1/conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/validation.go
- pkg/model/network.go
- tests/integration/create_cluster/ngwspecified/expected-v1alpha1.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/options.yaml
* Round trip to v1alpha1
* Enable test
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1564)
> Egress follow up

- upup/pkg/fi/cloudup/awstasks/natgateway.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
Fix #1568
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1569)
> Fix segfault in NatGateway

- addons/cluster-autoscaler/README.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1567)
> Update cluster-autoscaler to latest `0.4.0`

- upup/pkg/fi/cloudup/awstasks/iamrolepolicy.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1575)
> Keep go vet happier

- upup/pkg/fi/cloudup/dns.go
Issue #1468
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1500)
> Suggest the --dns-zone flag when we have multiple zones

- pkg/model/components/apiserver.go
Fix #1556
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1561)
> Resolve nodes by IP before trying by name

- cmd/kops/create.go
- cmd/kops/replace.go
- pkg/apis/kops/instancegroup.go
- pkg/client/simple/vfsclientset/instancegroup.go
- tests/integration/create_cluster/ha/expected-v1alpha1.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha1.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha1.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
Fix #1559
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1560)
> Include `cluster` label in `kops get ig -oyaml`

- federation/targets/kubernetes/kubernetestarget.go
- upup/pkg/fi/cloudup/awsup/aws_apitarget.go
- upup/pkg/fi/cloudup/gce/gce_apitarget.go
- upup/pkg/fi/cloudup/terraform/target.go
- upup/pkg/fi/default_methods.go
- upup/pkg/fi/dryrun_target.go
- upup/pkg/fi/nodeup/cloudinit/cloud_init_target.go
- upup/pkg/fi/nodeup/local/local_target.go
- upup/pkg/fi/target.go
Terraform processes deletions itself
Fix #1515
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1572)
> Skip deletion processing for terraform

- pkg/apis/kops/validation.go
- upup/pkg/fi/cloudup/populatecluster_test.go
- upup/pkg/fi/cloudup/tagbuilder.go
First step towards supporting mixed-modes.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1503)
> Turn off validation that master & nodes have same topology

- upup/pkg/fi/cloudup/awstasks/load_balancer.go
- upup/pkg/fi/cloudup/awstasks/securitygroup.go
- upup/pkg/fi/cloudup/awstasks/subnet.go
Issue #1525
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1570)
> Ignore changes in subnet, security group ordering in ELB

- cmd/kops/create_cluster.go
- docs/run_in_existing_vpc.md
- upup/pkg/fi/cloud.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
- upup/pkg/fi/cloudup/defaults.go
- upup/pkg/fi/cloudup/gce/gce_cloud.go
- upup/pkg/fi/cloudup/subnets.go
- upup/pkg/fi/cloudup/validation_test.go
Issue #1492
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1540)
> Automatically infer VPC & Subnet CIDRs

- cmd/kops/delete.go
- cmd/kops/delete_cluster.go
- cmd/kops/delete_confirm_test.go
- cmd/kops/delete_instancegroup.go
- cmd/kops/delete_secret.go
- cmd/kops/root.go
- cmd/kops/update_cluster.go
- cmd/kops/update_federation.go
- util/pkg/ui/user.go
* A few edge cases in the ui code (e.g. empty string)
* Move to new command model
* Copy the --yes flag, rather than trying to do special parsing
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1547)
> Refactor delete commands

- upup/pkg/kutil/delete_cluster.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1587)
> dump: add ELB dumping

- cmd/kops/create.go
- cmd/kops/delete.go
- cmd/kops/describe.go
- cmd/kops/edit.go
- cmd/kops/export.go
- cmd/kops/get.go
- cmd/kops/import.go
- cmd/kops/rollingupdate.go
- cmd/kops/secrets.go
- cmd/kops/toolbox.go
- cmd/kops/update.go
- cmd/kops/upgrade.go
- cmd/kops/version.go
Still nailing down my understanding of all the commands so some of these may not be accurate or any good just yet.
#1550
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1580)
> WIP: Improve command descriptions

- cmd/kops/create.go
- cmd/kops/delete.go
- cmd/kops/describe.go
- cmd/kops/edit.go
- cmd/kops/export.go
- cmd/kops/get.go
- cmd/kops/import.go
- cmd/kops/rollingupdate.go
- cmd/kops/secrets.go
- cmd/kops/toolbox.go
- cmd/kops/update.go
- cmd/kops/upgrade.go
- cmd/kops/version.go
Reverts kubernetes/kops#1580
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1589)
> Revert "WIP: Improve command descriptions"

- docs/aws.md
removing as to not confuse anyone
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1578)
> this line is actually not correct

- protokube/pkg/protokube/kube_boot.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1541)
> protokube: log when starting kubelet

- LICENSE
Upstream error, but we have to fix it too
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1545)
> Unmangle the Apache library

- upup/pkg/fi/cloudup/awstasks/natgateway.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1571)
> Add message about expected time for NAT gateway creation

- pkg/model/network.go
We don't link it up anyway, so we shouldn't try to create it
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1603)
> Don't create route table at all if all subnets are shared

- hack/dev-build.sh
Closes: https://github.com/kubernetes/kops/issues/903
Also updates hack script to work with current channel
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1618)
> updates for hack script

- cmd/kops/update_cluster.go
Fix #1489
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1616)
> Use correct bastion name in SSH suggestion

- docs/run_in_existing_vpc.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1602)
> Document existing-subnet requirements

- util/pkg/vfs/context.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1633)
> Recognize file:// urls

- pkg/model/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
Issue #1562
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1665)
> Allow clearing of maxPrice

- cmd/kops/update_cluster.go
Fix #1626
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1662)
> Clearer 'all done' message on kops update cluster

- pkg/model/autoscalinggroup.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1624)
> Clarify ignoring AssociatePublicIP message

- docs/iam_roles.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1678)
> Add some more detail to additionalPolicies docs

- cmd/kops/edit.go
- cmd/kops/edit_cluster.go
- cmd/kops/edit_instancegroup.go
- cmd/kops/rollingupdatecluster.go
More hints to avoid confusion when editing the cluster configuration.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1656)
> CLI: Add long descriptions

- cmd/kops/create_cluster.go
- pkg/apis/kops/cluster.go
- pkg/apis/kops/validation/legacy.go
- tests/integration/create_cluster/ha/expected-v1alpha1.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha1.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha1.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
- upup/pkg/fi/cloudup/populatecluster_test.go
Fix #1641
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1661)
> Allow specification of multiple CIDRs to create cluster

- docs/cluster_upgrades_and_migrations.md
- docs/upgrade.md
Updated the doc for upgrading and migrating clusters, with and without downtime.
Let me know if I could word things better or what.
cc @chrislovecnm
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/889)
> docs: update cluster migration doc, closes #753

- upup/pkg/kutil/delete_cluster.go
Ignore the specific error codes reported as happening during concurrent
cluster deletion.
Fix #1614
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1694)
> Tolerate concurrent deletion errors

- channels/alpha
- tests/integration/channel/simple/channel.yaml
Issue #1667
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1691)
> Add version-dependent recommendations to alpha channel

- cmd/kops/root.go
Fix #1518
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1693)
> Better message for name specified twice

- nodeup/pkg/model/docker.go
Fix #1542
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1702)
> Fix path to docker service manifest

- util/pkg/vfs/s3context.go
In cases where the user is the bucket owner an initial call to
s3.GetBucketLocation will succeed. If it does return an error we
fall back to the bruteforce method.
This effectively makes the behaviour unchanged from previous versions
for bucket owners.
This fixes #1703 
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1705)
> fix s3context: Attempt a normal S3 call before bruteforcing location

- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
The error message continues to worry users.  Trade off a bit of speed
for comfort with a friendlier error.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1716)
> Wait in launchconfiguration task for IAM profile to be ready

- upup/pkg/kutil/delete_cluster.go
Issue #1695
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1704)
> Ignore two more already-deleted errors in deleted

- pkg/featureflag/featureflag.go
- upup/pkg/fi/cloudup/terraform/hcl_printer.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1712)
> Feature flag for tf fmt

- upup/pkg/fi/cloudup/awsup/machine_types.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1706)
> Add GPU flag to MachineTypes

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/componentconfig.go
Issue #518
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1728)
> Map NvidiaGPUs / --experimental-nvidia-gpus

- docs/aws.md
@kris-nova Opened this new PR to brute force the merge issues that arose in my last one.
Adds more details to the IAM user section, detailing the IAM permissions required and some bash/awscli commands to create said user.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1696)
> more detail for IAM user

- .github/ISSUE_TEMPLATE.md
Added Issues template to project
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1315)
> Added .github folder and ISSUE_TEMPLATE

- upup/pkg/fi/dryrun_target.go
Fix #1736
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1739)
> Sort tasks consistently in dryrun

- docs/aws.md
- docs/install.md
- docs/topology.md
Hi,
Initial stab at reworking the AWS guide.  There's a ton of change in here so I'd definitely appreciate a lot of review, and feedback.  My internet has been flaky so I haven't been able to even preview this so hopefully I didn't bungle the header levels!
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1709)
> Improve AWS Guide

- docs/cli/kops.md
- docs/cli/kops_create_cluster.md
- docs/cli/kops_delete_cluster.md
- docs/cli/kops_delete_instancegroup.md
- docs/cli/kops_edit.md
- docs/cli/kops_edit_cluster.md
- docs/cli/kops_edit_federation.md
- docs/cli/kops_edit_instancegroup.md
- docs/cli/kops_rolling-update.md
- docs/cli/kops_rolling-update_cluster.md
- Cobra docs need update
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1762)
> Updating documentation

- Makefile
Fixes https://github.com/kubernetes/kops/issues/1777
/cc @chrislovecnm
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1785)
> Run govet and gofmt as first steps in CI

- pkg/apis/kops/v1alpha2/componentconfig.go
Fixes #1768
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1770)
> Edit EtcdClusterSpec: replace Config -> PodManifestPath

- cmd/kops/rollingupdatecluster.go
- docs/cli/kops_create_cluster.md
- docs/cli/kops_rolling-update_cluster.md
- docs/cli/kops_toolbox.md
- docs/cli/kops_toolbox_convert-imported.md
- docs/cli/kops_toolbox_dump.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1786)
> Generate docs against master branch

- nodeup/pkg/model/docker.go
For Docker >= 1.12
Fix #1781
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1789)
> Don't set docker.socket on RHEL

- util/pkg/vfs/context.go
We were returning the "don't retry" value (true).
Also tidy up the logic a little.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1787)
> Actually retry on HTTP 404s

- docs/development/release.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1798)
> Release notes

- tests/integration/create_cluster/ha/expected-v1alpha1.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha1.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha1.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
@justinsb this fixes #1799 
Looks like I merged a bit too early!
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1801)
> Bump to 1.4.8 in integration tests to fix #1799

- docs/api-server/README.md
- docs/aws.md
- hack/new-iam-user.sh
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1803)
> Adding hack script and fixing aws.md

- docs/etcd_backup.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1826)
> Fix Lambda typo

- cmd/kops/validate_cluster.go
- pkg/validation/validate_cluster.go
Fixes #1674 
I have also decreased the connection timeout.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1701)
> Improve cluster validate output

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/componentconfig.go
Required for https://github.com/kubernetes/kops/pull/1813 (`/usr/libexec/` is read only)
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1843)
> Map kubelet flag volume-plugin-dir

- cloudmock/aws/mockautoscaling/api.go
- cloudmock/aws/mockautoscaling/group.go
- cloudmock/aws/mockautoscaling/unimplemented.go
- hack/.packages
Part of https://github.com/kubernetes/kops/issues/1761 (testing rolling-update code). 
So far I've only added mock implementation for functions that I think will be needed for unit testing later. I may end up adding more as I go.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1824)
> Add mock autoscaling

- tests/integration/privatecanal/kubernetes.tf
Caused by terraform default format change & crossing of PRs
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1856)
> Fix test failure

- docs/development/release.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1805)
> Update release docs - channel info

- upup/pkg/fi/cloudup/awsup/aws_utils.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1811)
> Include error details when error querying regions

- upup/pkg/kutil/delete_cluster.go
Fixes a bug that I've described in #1431
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1844)
> fixing bug with leaking Elastic ips on cluster delete.

- docs/aws.md
Fixes a link in `aws.md` and also will close https://github.com/kubernetes/kops/pull/1223
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1868)
> Fix bogus SQS link

- nodeup/pkg/model/packages.go
Issue #1830
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1862)
> Install ethtool in nodeup

- Makefile
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1859)
> Makefile: hint on how to install sha1sum

- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Fixing master - v1alpha2 file was missed
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1889)
> fixing missed api file

- cmd/kops/create_cluster.go
Fix #1901
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1906)
> Set bastion image when creating cluster

- cmd/kops/validate_cluster.go
Fix #1897
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1904)
> Fix up table renderers in kops validate

- docs/images.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1910)
> Recommend the latest coreos image

- pkg/apis/kops/componentconfig.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1900)
> fix misspell "unhealthy" in componentconfig.go

- docs/iam_roles.md
- docs/security.md
First step for addressing #1577
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1870)
> Update docs regarding IAM roles

- README.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1918)
> readme: mention #kops rather than #sig-cluster-lifecycle

- hack/.packages
- pkg/model/iam/iam_builder.go
- pkg/model/iam/iam_builder_test.go
- pkg/util/stringorslice/stringorslice.go
- pkg/util/stringorslice/stringorslice_test.go
- upup/pkg/fi/cloudup/awstasks/iamrolepolicy.go
Fix #1920
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1928)
> Support string-or-slice in IAM policies

- cmd/kops/edit_cluster.go
- hack/.packages
- pkg/edit/edit.go
This will allow for easier reuse
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1936)
> Refactor extra-field logic into pkg/edit

- cmd/kops/edit_cluster.go
Fix #124
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1741)
> don’t discard user's changes

- upup/pkg/kutil/delete_cluster.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1926)
> Include security groups in toolbox dump

- docs/aws.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1881)
> Updated docs to reflect exporting new keys to ENV

- cmd/kops/edit_cluster.go
- pkg/edit/edit.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1937)
> Incorporate extra field detection into edit results

- README.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1632)
> updating office hours

- README.md
Minor updates to the maintainers section to list all "maintainers" but hopefully encourage contribution from all! 
Also dropped the time in UTC right on the page.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1942)
> Update README.md for all current maintainers and a little word-smithing

- tests/integration/minimal/cloudformation.json
Fix #1951
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1952)
> Update expected cloudformation output for tighter route53 policy

- docs/iam_roles.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1950)
> docs: reflect changes made in #1871

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
fixes #1872
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1879)
> Add audit flags to kube-apiserver

- pkg/model/components/kubelet.go
We're going with a much cleaner cgroup hierarchy for k8s 1.6
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1955)
> Update cgroup hierarchies for k8s 1.6

- README.md
@geojaz  this is a small follow up on your last PR.. what are your thoughts?
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1946)
> Add office hour heading

- docs/mfa.md
I figure we can throw this into the docs so end users have a documented work around until there is real support. Please let me know if there is a better way to document this (or an existing doc to add to).
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1888)
> Document MFA workaround

- docs/run_in_existing_vpc.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1722)
> fixed link to topology.md file

- pkg/model/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/iamrolepolicy.go
- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
- upup/pkg/fi/cloudup/awstasks/securitygroup.go
- upup/pkg/fi/default_methods.go
- upup/pkg/fi/utils/reflect.go
Fix #1793
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1925)
> Additional ShouldCreate method to prevent spurious changes

- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1966)
> Output ephemeral devices in terraform in consistent order

- util/pkg/vfs/s3context.go
fixes #1974
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1978)
> validate region

- hack/.packages
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/validation/legacy.go
- pkg/flagbuilder/buildflags_test.go
- tests/codecs/componentconfig_test.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1957)
> Cleanup nil handling in kubelet options

- upup/pkg/kutil/cluster_resources.go
- upup/pkg/kutil/delete_cluster.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1992)
> Add filter to delete

- pkg/model/api_loadbalancer.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1979)
> Choose only one subnet per AZ for API ELB

- tests/integration/ha/kubernetes.tf
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1994)
> Fix tests - another cross-merge

- pkg/diff/diff.go
- pkg/diff/diff_test.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1958)
> Fix diff edge case for trailing diffs

- .shipbot.yaml
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1993)
> Add manifest for shipbot

- upup/pkg/kutil/cluster_resources.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2004)
> Disable CloudFormation Delete (again)

- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/v1.6.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1997)
> Update kube-dns addon configuration to match the latest

- Makefile
Trying to track down why we seem to still be building the previous
version.
> Cleanup of protokube image building

- Makefile
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2036)
> makefile: replace protokube.tar.gz

- upup/models/nodeup/_kubernetes_pool/kube-proxy/files/etc/kubernetes/manifests/kube-proxy.manifest.template
The equivalent of https://github.com/kubernetes/kubernetes/pull/41700
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2017)
> Set OOM for kube-proxy

- addons/cluster-autoscaler/README.md
- addons/cluster-autoscaler/v1.4.0.yaml
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1715)
> Update cluster-autoscaler readme

- upup/models/cloudup/resources/addons/networking.weave/v1.9.3.yaml
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Weave Net [v1.9.3](https://github.com/weaveworks/weave/releases/tag/v1.9.3) has just been released: adding it to Kops.
cc: @bboreham, @brb
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2062)
> Add Weave Net v1.9.3

- pkg/model/api_loadbalancer.go
- pkg/model/bastion.go
- pkg/model/context.go
- pkg/model/context_test.go
- tests/integration/privatecalico/kubernetes.tf
- tests/integration/privatecanal/kubernetes.tf
- tests/integration/privateflannel/kubernetes.tf
- tests/integration/privatekopeio/kubernetes.tf
- tests/integration/privateweave/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/dnsname.go
- upup/pkg/fi/cloudup/awstasks/load_balancer.go
- upup/pkg/fi/cloudup/awstasks/load_balancer_attachment.go
- upup/pkg/fi/cloudup/awstasks/loadbalancer_attributes.go
- upup/pkg/fi/cloudup/template_functions.go
Rather than using the LoadBalancerName to match, we match on the Name
tag.
Related to #2019
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2051)
> Use Name tag to match ELBs

- channels/alpha
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2076)
> Bump alpha channel to 1.5.4

- docs/addons.md
Saw some user confusion on slack.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2077)
> Add clarifying note about route53-controller vs dns-controller

- docs/development/release.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2054)
> Update release notes with branches

- upup/pkg/fi/cloudup/apply_cluster.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2117)
> Don't fail if we can't pre-create DNS records

- dns-controller/pkg/dns/dnscontroller.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2118)
> More verbose error messages on DNS errors

- docs/run_in_existing_vpc.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2122)
> Fix broken link in existing VPC readme

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
fixes #2089
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2090)
> add webhook authenticator flags

- cmd/kops/create_ig.go
Issue #2099
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2121)
> Fix omitted err check

- util/pkg/vfs/s3context.go
- util/pkg/vfs/s3fs.go
Hopefully to shed some light on issues like #2108
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2125)
> More logging around errors in s3 write path

- docs/development/release.md
Fix #2040
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2126)
> More notes on release branches

- docs/terraform.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2162)
> Fix Terraform state link at docs

- docs/aws.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2153)
> Add jq note; wrap long line.

- cmd/kops/create_ig.go
Fix #2078
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2124)
> Allow specifying subnets on `create ig`

- docs/high_availability.md
- docs/single-to-multi-master.md
This adds a lengthy documentation on how to go from a single-master setup to a multi-master setup.
cc @justinsb @chrislovecnm for review
This is for issue #1566
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1657)
> Documentation to go from single to multi-master

- .gitignore
- Makefile
- hack/lib/__init__.py
- hack/lib/kubernetes/__init__.py
- hack/lib/kubernetes/devtools.py
- hack/update-goimports
- hack/verify-goimports
Trying out python
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2140)
> Script to call goimports

- upup/pkg/kutil/rollingupdate_cluster.go
**Background**
The current code base has where nodes are rolled in parallel when multiple ig's exist in the cluster.  Talking with @justinsb we agreed that it is best to pull this out.  Talked with a couple of end users and they were not using the functionality.  This specifically helps when rolling clusters with stateful applications.
**TODO**
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2182)
> Removing parallel node rolling with multiple ig

- hack/deps.py
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2127)
> Script to sync our submodules from Godeps

- nodeup/pkg/model/network.go
- pkg/model/components/context.go
- pkg/model/components/kubecontrollermanager.go
- upup/pkg/fi/cloudup/tagbuilder.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2193)
> Update error message for golang style

- pkg/apis/kops/v1alpha1/instancegroup.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/instancegroup.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
I tried a manual conflict resolve in github; it went _ok_
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2198)
> Fix merge problems from tenancy

- cmd/kops/edit.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2199)
> Make changes so we can apply #1590

- cmd/kops/completion.go
- cmd/kops/create.go
- cmd/kops/delete.go
- cmd/kops/describe.go
- cmd/kops/edit.go
- cmd/kops/export.go
- cmd/kops/get.go
- cmd/kops/import.go
- cmd/kops/replace.go
- cmd/kops/rollingupdate.go
- cmd/kops/secrets.go
- cmd/kops/toolbox.go
- cmd/kops/update.go
- cmd/kops/upgrade.go
- cmd/kops/validate.go
- cmd/kops/version.go
Improving the short descriptions for top level kops commands.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1590)
> improving short descriptions for cli commands

- cmd/kops/edit.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2200)
> Reapply the changes we undid in #2199

- cmd/kops/create.go
Fix for #1953. 
Current state for `kops create -f` is no response on proper parsing. 
As resources are "parsed", this prints out what was created and prompts you to deploy your changes via `kops update`.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2052)
> Feedback for kops create -f when operation succeeds

- upup/pkg/kutil/delete_cluster_gce.go
Fixes part of https://github.com/kubernetes/kops/issues/2086.
Most of the logic for choosing which records to delete is from the [AWS implementation for route 53](https://github.com/kubernetes/kops/blob/master/upup/pkg/kutil/delete_cluster.go#L1737). 
In the near future, I would also like to add some tests for the delete cluster code paths as deleting the wrong DNS records would suck!
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2187)
> Delete Cloud DNS record sets in GCE

- nodeup/pkg/model/kubelet.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2215)
> Fix taint format

- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha1/cluster.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/model/components/apiserver.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2217)
> Add Authorization / RBAC option to schema

- pkg/model/pki.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2219)
> Add 127.0.0.1 to the IPs on the master apiserver

- protokube/cmd/protokube/main.go
- protokube/pkg/protokube/kube_boot.go
- protokube/pkg/protokube/kube_context.go
- protokube/pkg/protokube/rbac.go
We are integrating with kubeadm!
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2207)
> Add initialize-rbac flag to protokube

- cmd/kops/delete_cluster.go
- cmd/kops/export_kubecfg.go
- cmd/kops/update_cluster.go
- federation/apply_federation.go
- federation/federation_cluster.go
- federation/federation_configuration.go
- federation/targets/kubernetestarget/kubernetestarget.go
- pkg/kubeconfig/create_kubecfg.go
- pkg/kubeconfig/kubecfg_builder.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2208)
> Refactor kubeconfig building

- nodeup/pkg/model/secrets.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2224)
> Add RBAC roles to basic auth

- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/v1.6.0.yaml.template
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2226)
> Add RBAC permissions for dns-controller

- nodeup/pkg/model/kubeapiserver.go
- nodeup/pkg/model/kubeapiserver_test.go
- nodeup/pkg/model/kubectl.go
- nodeup/pkg/model/protokube.go
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/model/components/apiserver.go
- pkg/model/components/kubecontrollermanager.go
- pkg/model/pki.go
- upup/pkg/fi/cloudup/populate_cluster_spec.go
- upup/pkg/fi/nodeup/nodetasks/file.go
- upup/pkg/fi/nodeup/template_functions.go
All components need a kubeconfig
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2220)
> Be able to disable insecure port for apiserver

- nodeup/pkg/model/kubeproxy.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2221)
> Use tee for kube-proxy, so kubectl logs works

- nodeup/pkg/model/kubecontrollermanager.go
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/model/components/kubecontrollermanager.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2225)
> Set --use-service-account-credentials for 1.6

- cmd/kops/create_cluster.go
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha1/cluster.go
- pkg/apis/kops/v1alpha1/defaults.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/defaults.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/model/components/apiserver.go
- tests/integration/create_cluster/ha/expected-v1alpha1.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha1.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha1.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
Also add AlwaysAllow to the schema
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2233)
> Add authorization flag to kops create

- docs/releases/1.6.0-alpha.1.md
Proposed release notes for 1.6.0-alpha.1
cc @geojaz @yissachar @chrislovecnm @kris-nova
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2237)
> Release notes for 1.6.0-alpha.1

- docs/releases/1.6.0-alpha.1.md
Addressing concerns in https://github.com/kubernetes/kops/pull/2237
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2239)
> Release notes tweaks

- Makefile
- docs/development/release.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2241)
> Link to shipbot

- pkg/validation/validate_cluster.go
This otherwise breaks validation.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2248)
> Fix node role defaulting

- docs/instance_groups.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2270)
> Fix markdown formatting

- addons/route53-mapper/v1.3.0.yml
route53-kubernetes 1.3.0 addon
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2269)
> route53-mapper v.1.3.0

- nodeup/pkg/model/docker_test.go
- nodeup/pkg/model/kubelet.go
- nodeup/pkg/model/kubelet_test.go
- nodeup/pkg/model/tests/kubelet/featuregates/cluster.yaml
- nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
- pkg/flagbuilder/build_flags.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2285)
> Tidy up kubelet nodeup tests

- upup/models/cloudup/resources/addons/networking.weave/v1.9.4.yaml
We label all the resources we would delete when we switch networking
providers.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2274)
> Add weave manifest labels

- nodeup/pkg/model/docker.go
- pkg/model/components/docker.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2283)
> Update to docker 1.12.6 for k8s 1.6

- docs/images.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2302)
> Fix formatting

- upup/models/nodeup/docker/_systemd/_debian_family/services/docker-healthcheck.service.meta
Issue #2279
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2299)
> Make sure we start docker-healthcheck.service

- hack/dev-build.sh
fixing missing `CI=1` in the hack script.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2079)
> updating CI in hack script

- images/protokube-builder/onbuild.sh
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2308)
> updating protokube kubectl to v1.6.1

- hack/update-header.sh
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2316)
> Add fix for hack/update-header.sh

- channels/cmd/channels/apply_channel.go
This otherwise has broken head.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2321)
> Fix govet problem

- nodeup/pkg/model/cloudconfig.go
- pkg/apis/kops/componentconfig.go
This changed is related to Issue #2171 
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2172)
> Add AWS CloudConfig DisableSecurityGroupIngress Configuration Parameter

- dns-controller/pkg/dns/dnscontroller.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2326)
> Fix typo: changset -> changeset

- nodeup/pkg/model/kubeapiserver.go
- upup/models/nodeup/_kubernetes_master/kube-apiserver/files/var/log/kube-apiserver.log.meta
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2166)
> Move touching kubeapiserver log file to code

- nodeup/pkg/model/context.go
- nodeup/pkg/model/kubelet.go
- nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
- upup/pkg/fi/nodeup/command.go
- upup/pkg/fi/nodeup/tags/tags.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2330)
> Replaces UsesCNI with logic

- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/pre-k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2339)
> Split canal manifests to 1.5 & 1.6

- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
Issue #2304
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2324)
> Add missed error handling from Autoscaling list

- channels/pkg/channels/channel_version.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2338)
> Fix channel version format string

- cmd/nodeup/main.go
Issue #2304
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2323)
> Add missed error handling from nodeup lstat

- docs/terraform.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2374)
> Correct typo

- pkg/validation/validate_cluster.go
- pkg/validation/validate_cluster_test.go
Fixes #2379 
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2380)
> Fix cluster validation when there's additional nodes. 

- addons/kubernetes-dashboard/addon.yaml
- addons/kubernetes-dashboard/v1.6.0.yaml
I updated k8s dashboard to 1.6 and manually verified that the addon worked.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2361)
> Updated k8s dashboard to 1.6

- channels/pkg/cmd/apply_channel.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2336)
> channels: accept -f and --files

- nodeup/pkg/model/kubecontrollermanager.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2385)
> Enable CertificateSigner API on k8s 1.6

- docs/gpu.md
- hooks/nvidia-bootstrap/Makefile
- hooks/nvidia-bootstrap/README.md
- hooks/nvidia-bootstrap/image/Dockerfile
- hooks/nvidia-bootstrap/image/run.sh
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2298)
> Experimental nvidia driver installation via a hook

- pkg/validation/validate_cluster_test.go
Addendum to #2380
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2382)
> Test for having fewer nodes than minimum count

- hooks/prepull-images/Makefile
- hooks/prepull-images/README.md
- hooks/prepull-images/image/Dockerfile
- hooks/prepull-images/image/run.sh
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2381)
> hook for prepulling images

- pkg/apis/kops/validation/aws.go
- pkg/apis/kops/validation/aws_test.go
- pkg/apis/kops/validation/legacy.go
- pkg/apis/kops/validation/validation_test.go
Fix #2110
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2112)
> Perform validation of the security group names

- upup/pkg/fi/cloudup/awsup/machine_types.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2359)
> Add "m4.16xlarge" type

- addons/logging-elasticsearch/addon.yaml
- addons/logging-elasticsearch/v1.5.0.yaml
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1305)
> (experimental) addon for Elasticsearch logging

- cmd/kops/rollingupdatecluster.go
- docs/upgrade.md
explained in commits
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2409)
> Update docs for upgrading with terraform

- channels/alpha
- channels/stable
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2425)
> Bump stable channel with alpha; alpha channel with latest

- docs/networking.md
Changed daesonset to daemonset.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2431)
> Spell mistake in document.

- README.md
This is for developers only ... let's not have users do it.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2434)
> removing --HEAD instructions as that is a developer install

- addons/monitoring-standalone/addon.yaml
- addons/monitoring-standalone/v1.3.0.yaml
- docs/addons.md
Upgrade heapster to 1.3.0 and addon-resizer to 1.7
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2356)
> [heapster] Create v1.3.0.yaml

- cmd/kops/create.go
- cmd/kops/create_cluster.go
- cmd/kops/delete.go
- cmd/kops/delete_cluster.go
- cmd/kops/edit.go
- cmd/kops/edit_cluster.go
- cmd/kops/root.go
- cmd/kops/update.go
- cmd/kops/upgrade.go
- cmd/kops/upgrade_cluster.go
Improved cli command line help by adding k8s templates, i18n, and examples. Fixes #1005
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2443)
> Fixes issue #1005

- README.md
to correspond to https://github.com/kubernetes/kops/pull/2445
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2457)
> Update version of Go in readme

- upup/models/cloudup/resources/addons/networking.flannel/k8s-1.6.yaml
- upup/models/cloudup/resources/addons/networking.flannel/pre-k8s-1.6.yaml
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Includes some important fixes for taints in 1.6
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2463)
> Update flannel to 0.7.1

- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/pre-k8s-1.6.yaml.template
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2465)
> Bump version of flannel embedded in canal to 0.7.1

- docs/aws.md
Relates to #353
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2462)
> docs aws: Add explicit note about cross-account S3 support

- README.md
As discussed in office hours today.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2461)
> Updates README around community contributions as discussed 4/28/17

- protokube/pkg/gossip/dns/provider/zone.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2476)
> typo in TODO

- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2479)
> Update tests for version bump

- docs/creating_subdomain.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2491)
> Fix md typo

- .travis.yml
- Makefile
- cmd/kops/edit.go
- cmd/kops/gen_help_docs.go
- cmd/kops/replace.go
- cmd/kops/update_cluster.go
- docs/cli/kops.md
- docs/cli/kops_create.md
- docs/cli/kops_create_cluster.md
- docs/cli/kops_delete.md
- docs/cli/kops_delete_cluster.md
- docs/cli/kops_delete_instancegroup.md
- docs/cli/kops_delete_secret.md
- docs/cli/kops_edit.md
- docs/cli/kops_edit_cluster.md
- docs/cli/kops_replace.md
- docs/cli/kops_rolling-update_cluster.md
- docs/cli/kops_update.md
- docs/cli/kops_update_cluster.md
- docs/cli/kops_upgrade.md
- docs/cli/kops_upgrade_cluster.md
- hack/verify-boilerplate.sh
- hack/verify-gendocs.sh
Adding script to check that the cobra generated docs are up to date.  We have some docs that are out of date as well :)
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2418)
> updating docs, adding verify-gendocs and more build tweaks

- addons/monitoring-standalone/addon.yaml
- addons/monitoring-standalone/v1.6.0.yaml
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2483)
> add heapster addon

- addons/monitoring-standalone/README.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2488)
> add readme for Heapster

- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/model/components/kubelet.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2447)
> Remove babysit-daemons flag from 1.7

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/pre-k8s-1.6.yaml.template
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2536)
> Update calico to 2.1.5 for k8s 1.6+ bugfixes

- cmd/kops/root.go
- cmd/kops/util/factory.go
Signed-off-by: Jaipradeesh Janarthanan <jaipradeesh@gmail.com>
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2524)
> [Fixes #2439] Trim trailing slash (if present) in state store value

- docs/security.md
Fixes #2234
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2532)
> Updated security docs to display API secret token correctly

- cmd/kops/update_cluster.go
Fixes https://github.com/kubernetes/kops/issues/2530
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2531)
> Added -A flag to ssh connection

- nodeup/pkg/model/kubeapiserver.go
This commit exposes kube-apiserver's audit log to the host as a host
mapping.
PR #1872 gave the ability to users to define a custom log path for the
apiserver to write its audit logs to. Prior to this commit, the log file
would stay within the container's filesystem, and getting access to it from
outside the container was a nuisance.
This change allows a logging aggregator, like fluentd, to be able
to read and tail this log from outside the kube-apiserver container.
Tested this change on Kubernetes 1.5 and Kubernetes 1.6.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2494)
> Expose apiserver audit log by setting it as a Host Path

- nodeup/pkg/model/kubectl.go
Signed-off-by: Jaipradeesh Janarthanan <jaipradeesh@gmail.com>
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2523)
> [Fixes #2466] Creates .kube dir at /home/admin with group/owner as admin

- cmd/kops/edit.go
- docs/cli/kops.md
- docs/cli/kops_edit.md
- docs/cli/kops_edit_cluster.md
- docs/cli/kops_edit_federation.md
- docs/cli/kops_edit_instancegroup.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2552)
> Fixed some typos, s/resrouces/resources/

- Makefile
This PR adds a target that makes the Makefile for `kops` (near) self-documenting. The idea is simple:
* Add a comment to a target (like so: `target: # This target does this thing`)
* Run `make help` and see the target appear in the list of targets like so:
* <target name> - <description> (deps: <target dependencies>)
* Targets are ordered and separated in documented and undocumented targets.
* There's also an automatically generated list of variables that are taken from the environment.
It's based on the Unix utilities `grep`, `sed` and `sort`. I'm not sure if I should do something to mark them as new dependencies, they're not build dependencies so I'm not sure how important that is.
It currently looks like this (everything is printed on `stderr`):
```
Targets:
examples - Install kops API …
```
> Added help target to Makefile and fixed small path ordering issue

- cmd/kops/create_cluster.go
We don't want to "accidentally" enable HA.  When users specify multiple
zones, but don't specify a master-count or master-zones, we interpret
that as master-count=1
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2515)
> Only do HA if master-count or master-zones is specified

- channels/alpha
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2482)
> Update alpha channel: new images, new k8s

- cmd/kops/rollingupdatecluster.go
- cmd/kops/upgrade.go
- docs/cli/kops_rolling-update.md
- docs/cli/kops_rolling-update_cluster.md
- docs/cli/kops_upgrade.md
- docs/cli/kops_upgrade_cluster.md
export var KOPS_FEATURE_FLAGS in the docs
rename rolling update to rolling-update
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2566)
> Review rolling-update command

- cmd/kops/secrets_expose.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2574)
> Fix typo: export -> expose

- upup/pkg/fi/cloudup/gcetasks/instance.go
- upup/pkg/fi/cloudup/gcetasks/instancegroupmanager.go
- upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
- upup/pkg/fi/cloudup/utils.go
- upup/pkg/fi/dryrun_target.go
We follow the same pattern as on AWS, where we create a new template,
because the templates are immutable.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2426)
> GCE: Allow updating the instance group template

- pkg/model/iam.go
- pkg/model/names.go
- upup/pkg/fi/cloudup/awstasks/iamrole.go
Tweaks for #2508
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2567)
> Rename RoleType to ExportWithID in IAMRole

- channels/stable
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2581)
> Move alpha channel to stable

- cmd/kops/get.go
- cmd/kops/get_cluster.go
- cmd/kops/get_federation.go
- cmd/kops/get_instancegroups.go
- cmd/kops/get_secrets.go
- cmd/kops/root.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2311)
> Cleanup get command

- upup/models/cloudup/resources/addons/networking.flannel/k8s-1.6.yaml
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Fix #2601
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2602)
> Set hairpinMode for flannel

- docs/cluster_spec.md
Updates docs to reflect https://github.com/kubernetes/kops/pull/1879
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2620)
> Update cluster_spec docs with audit logging

- .gitignore
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2623)
> Don't ignore tags files - we have a package named tags

- cmd/kops/get.go
- cmd/kops/get_cluster.go
- cmd/kops/get_instancegroups.go
- docs/cli/kops_get.md
get now gets a cluster
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2609)
> Get updates

- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/pre-k8s-1.6.yaml.template
Fixes #2588 
- Updated manifests to the latest versions
- Added RBAC to k8s 1.6 manifest
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2635)
> Updating Canal manifests

- ROADMAP.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2625)
> Update roadmap for 1.7

- docs/experimental.md
- pkg/featureflag/featureflag.go
- upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/external-dns.addons.k8s.io/pre-k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/template_functions.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2649)
> add EnableExternalDNS feature flag

- addons/cluster-autoscaler/README.md
- addons/cluster-autoscaler/addon.yml
- addons/cluster-autoscaler/v1.6.0.yaml
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2627)
> add cluster autoscaler addon

- nodeup/pkg/model/kubeapiserver.go
Fixed an oops I created in #2494 where log rotation done by the kube-apiserver does not function
as expected.
The kube-apiserver first has to rename the existing audit log prior to a new one
being created. Renaming is not possible when the audit file is mounted
directly as the host path. kube-apiserver will return a 'Device or
resource busy' error when it tries to do so. So instead, we mount the
directory of the path instead of the file itself. Also remove the
creation of an empty audit log file as that is no longer necessary for
Docker to mount a directory.
"If an audit log file already exists, Kubernetes appends new audit logs
to that file. Otherwise, Kubernetes creates an audit log file at the
location you specified in audit-log-path. If the audit log file exceeds
the size you specify …
> Fix log rotation of apiserver audit logs

- Makefile
Removing duplicate test in Makefile
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2655)
> duplicate test

- docs/bastion.md
Fixes #2695
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2698)
> Reference private key instead of public

- docs/addons.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2700)
> bump dashboard and heapster versions

- cmd/kops/create_cluster.go
- docs/cli/kops_create_cluster.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2684)
> Initial commit to add option to set volume size at creation

- upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This includes the hairpin fix
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2704)
> Update weave to 1.9.7

- docs/releases/1.6-NOTES.md
- docs/releases/1.6.1.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2706)
> Add release notes for 1.6.1

- docs/images.md
Related to https://github.com/kubernetes/kops/pull/2689#issuecomment-307380522
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2723)
> Sort coreos images by CreationDate

- protokube/pkg/protokube/kube_boot.go
fixes #1882
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2716)
> Check if kubelet is already running before calling systemctl start

- protokube/pkg/protokube/kube_boot.go
Follow on to #2716
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2756)
> Log systemctl output from status/start kubelet

- upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Includes the nodeport fixes
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2760)
> Update weave to 1.9.8

- docs/images.md
Follow up to #2723
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2757)
> CoreOS AMI docs formatting

- docs/development/release.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2759)
> Add git push to release notes

- docs/cluster_spec.md
- pkg/flagbuilder/buildflags_test.go
Follow up to #2662
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2764)
> Tweaks to docs for fields that can be empty

- Makefile
- cmd/kops/create_cluster.go
- hack/.packages
- pkg/model/awsmodel/api_loadbalancer.go
- pkg/model/dns.go
- pkg/model/iam/iam_builder.go
- protokube/pkg/gossip/aws/seeds.go
- protokube/pkg/gossip/mesh/state.go
- protokube/pkg/protokube/aws_volume.go
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/pre-k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/awstasks/load_balancer.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2761)
> Support internal names for AWS also

- docs/networking.md
Also sort by name.
Came up on slack, where a user assumed that #1 in the list was most
highly favored, which was not the intention.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2758)
> Convert networking list to bulleted list

- cmd/kops/delete.go
- docs/cli/kops_delete.md
Grammar and typo corrections mentioned in @justinsb review of https://github.com/kubernetes/kops/pull/2772
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2781)
> Fixing typo and grammar

- channels/alpha
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2788)
> alpha channel: Bump k8s version to 1.6.6

- docs/releases/1.6-NOTES.md
- docs/releases/1.6.2.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2786)
> Add release notes for 1.6.2

- Makefile
- cmd/kops/get_instancegroups.go
- tests/integration/channel/integration_test.go
Fixing some simple problems.   Found with git 1.8.3 vet.  Not sure why CI is missing this with the ig file.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2805)
> fixing govet issues and adding test directory

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2836)
> Fix missing ids in a few log messages

- docs/instance_groups.md
- pkg/apis/kops/instancegroup.go
- pkg/apis/kops/v1alpha1/instancegroup.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/instancegroup.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/model/awsmodel/autoscalinggroup.go
- pkg/model/awsmodel/autoscalinggroup_test.go
- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
Fixes #1808
I'm not sure if similar remote storage optimization capabilities are offered on other platforms like GCP. If similar optimizations are offered, then we should open another issue to add support for this field on each platform.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2822)
> Add field to enable EBS Volume Optimization

- docs/README.md
- docs/vsphere-dev.md
- docs/vsphere-development-status.md
> Added documentation for vSphere support status.

- cmd/kops/upgrade.go
- docs/cli/kops_upgrade.md
- docs/cli/kops_upgrade_cluster.md
Fix typos in kops_upgrade.md.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2815)
> Fix typos in kops_upgrade.md

- cmd/kops/create_cluster_integration_test.go
- cmd/kops/integration_test.go
- hack/.packages
- pkg/assets/builder.go
- pkg/assets/templates.go
- pkg/kubemanifest/images.go
- pkg/kubemanifest/manifest.go
- pkg/kubemanifest/visitor.go
- pkg/templates/templates.go
- pkg/testutils/integrationtestharness.go
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/pre-k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/awstasks/elastic_ip_test.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
- upup/pkg/fi/dryrun_target.go
- upup/pkg/fi/nodeup/command.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2769)
> Asset redirection via manifest parsing

- docs/download_config.md
> Fixing wrong brackets on links

- docs/releases/1.7-NOTES.md
> Start 1.7 release notes

- pkg/resources/aws.go
> fix delete_cluster for those regions don't have route53

- pkg/apis/kops/channel.go
- upup/pkg/fi/cloud.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/utils.go
This adds some initial digitalocean code and a feature flag gate while I'm adding new features for the DO cloud provider. 
Related:
https://github.com/kubernetes/kops/issues/2150
https://github.com/kubernetes/kops/pull/2864
> digitalocean feature flag

- upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
Still some changes to order, but should be much easier to audit now.
> Dedent weave manifest, for easier diffing

- images/dns-controller-builder/Dockerfile
- images/dns-controller/Dockerfile
- images/protokube-builder/Dockerfile
- images/protokube/Dockerfile
- images/utils-builder/Dockerfile
> Reduce size of images using debian-base

- upup/pkg/fi/cloudup/awstasks/sshkey.go
- upup/pkg/fi/cloudup/vspheretasks/attachiso.go
- upup/pkg/fi/k8sapi/k8s_keystore.go
I found some unhandled err variables in packages under the `upup` directory.
> Fix swallowed errors in upup subdirectory.

- pkg/instancegroups/instancegroups.go
- pkg/resources/aws.go
I found some unhandled error variables in packages under the pkg subdirectory.
> Fix swallowed errors under pkg subdirectory.

- federation/federation_configuration.go
I found a dropped error in the federation package.
> Fix swallowed err in federation.

- tests/integration/channel/integration_test.go
I found an unused import in the tests, and I fixed it.
> Fixed unused import in tests.

- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Looks like I forgot to run it previously
> Update generated apimachinery

- pkg/assets/builder.go
Don't insert an extra blank line before separators, don't insert a
separator at the end.
> Cleaner yaml formatting

- docs/manifests_and_customizing_via_api.md
Closes Issue #2977: Improve Manifest documentation
@chrislovecnm
> Issue #2977: Improve Manifest documentation

- util/pkg/vfs/s3context.go
I found an unhandled error in the vfs package, and fixed it.
> Fix swallowed err variable in vfs package

- docs/upgrade_from_kops_1.6_to_1.7_calico_cidr_migration.md
1. Added missing step to pull down template file.
2. Changed step wording to reflect change.
3. Change 'rolling-upgrade' command option to correct 'rolling-update'.
> Add missing step to pull template file; correct kops option.

- Makefile
- docs/apireference/README.md
Following instructions in docs/apireference/README.md
> Add gen-api-docs target to makefile

- upup/pkg/fi/cloudup/apply_cluster.go
This has been bugging me for a bit.
> removing dead code

- docs/calico_cidr_migration/create_migration_manifest.sh
Fixes #3018. Thank you @blakebarnett for the report! 
The migration manifest was assuming that everyone was using cross-subnet mode, which is a big no-no. :(
This script removes the cross-subnet line from the manifest file if `crossSubnet` is not set to be `true`.
Once merged, people will be able to pull the latest version without a release since the migration README points to master for the script.
> Fix migration script to take ipip mode into account

- dns-controller/pkg/watchers/ingresscontroller.go
- dns-controller/pkg/watchers/nodecontroller.go
- dns-controller/pkg/watchers/podcontroller.go
- dns-controller/pkg/watchers/servicecontroller.go
Fixes: https://github.com/kubernetes/kops/issues/3049
> raising logging levels and removing dead code

- docs/upgrade_from_kops_1.6_to_1.7_calico_cidr_migration.md
> added missing command in documentation

- hack/dev-build.sh
Silly quotes fix and image update to make it more copy and paste friendly.
> Fix quote typo on dev-build

- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/pre-k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- Switch Calico images to be pulled from quay.io
Addresses #3161
> Update to Calico 2.4.1

- channels/stable
Updated AMIs, newer k8s versions
> Promote alpha to stable channel

- docs/releases/1.7-NOTES.md
1.7 is released, so docs should reflect that!
> Fix heading on 1.7 notes

- docs/networking.md
Adding couple of sentences to kube-router documentation.
> Add documentaion to kube-router section of docs/networking

- docs/development/release.md
> Fix Broken Link

- cmd/kops/create.go
- cmd/kops/edit_cluster.go
- cmd/kops/replace.go
- cmd/kops/upgrade_cluster.go
- examples/kops-api-example/up.go
- pkg/apis/kops/registry/helpers.go
- pkg/client/simple/clientset.go
- pkg/client/simple/vfsclientset/clientset.go
- pkg/client/simple/vfsclientset/cluster.go
This enables better validation (in the etcd status PR)
> Explicit CreateCluster & UpdateCluster functions

- .travis.yml
So that we can start testing with it
> Add go1.9 target to travis

- pkg/apis/kops/util/versions.go
- pkg/model/components/apiserver.go
Also sync up Admission controllers with current default sets for 1.7 &
1.8
> Add Initializers admission controller

- federation/apply_federation.go
- federation/federation_configuration.go
- hack/.packages
- pkg/pki/certificate.go
- pkg/pki/csr.go
- pkg/pki/privatekey.go
- upup/pkg/fi/ca.go
- upup/pkg/fi/fitasks/keypair.go
- upup/pkg/fi/k8sapi/cert_secret.go
- upup/pkg/fi/k8sapi/k8s_keystore.go
- upup/pkg/fi/nodeup/template_functions.go
- upup/pkg/fi/vfs_castore.go
- upup/pkg/kutil/import_cluster.go
This will support generation of keys on the node.
> Refactor PKI classes into their own package

- docs/aws.md
pointing links to the k8s slack directly, single click enter to slack.
> Update aws.md pointing links to the k8s slack directly

- docs/cluster_spec.md
> Correct typo in Hooks Spec examples

- Makefile
The default makefile target should do a standard go install of kops
so we don't break existing workflows.
> Makefile: build kops in dev-mode by default

- upup/pkg/fi/cloudup/gcetasks/disk.go
- upup/pkg/fi/cloudup/gcetasks/firewallrule.go
- upup/pkg/fi/cloudup/gcetasks/instancegroupmanager.go
- upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
- upup/pkg/fi/cloudup/gcetasks/network.go
We need to ignore the Lifecycle field
> GCE: Fix logic around change detection

- upup/models/config/_aws/defaults.options
- upup/models/config/_gce/defaults.options
Another step closer to removing the tags
> Remove unused GCE/AWS options

- cmd/kops/edit_cluster.go
- cmd/kops/replace.go
- cmd/kops/status_discovery.go
- cmd/kops/upgrade_cluster.go
- hack/.packages
- pkg/apis/kops/status.go
- pkg/apis/kops/validation/cluster.go
- pkg/apiserver/registry/cluster/strategy.go
- pkg/client/simple/clientset.go
- pkg/client/simple/vfsclientset/clientset.go
- pkg/client/simple/vfsclientset/cluster.go
- protokube/pkg/etcd/cluster_spec.go
- protokube/pkg/etcd/utils.go
- protokube/pkg/protokube/aws_volume.go
- protokube/pkg/protokube/etcd_cluster.go
- protokube/pkg/protokube/gce_volume.go
- protokube/pkg/protokube/volume_mounter_test.go
- protokube/pkg/protokube/volumes.go
- protokube/pkg/protokube/vsphere_volume.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/awsup/status.go
- upup/pkg/fi/cloudup/gce/gce_cloud.go
- upup/pkg/fi/cloudup/gce/mock_gce_cloud.go
- upup/pkg/fi/cloudup/gce/status.go
This will allow us to permit changing the etcd configuration only if
etcd has not yet been configured.
> Add function to get etcd status

- Makefile
Have make scan all the deps seems much slower than having go do it.
> Makefile: use go install

- upup/pkg/fi/cloudup/template_functions.go
> getting rid of uneeded logging in ux

- protokube/tests/integration/build_etcd_manifest/main/non_tls.yaml
- protokube/tests/integration/build_etcd_manifest/main/tls.yaml
PR crossed with others, I believe.
> Fix integration test

- nodeup/pkg/model/kube_apiserver.go
- nodeup/pkg/model/kube_controller_manager.go
- nodeup/pkg/model/kube_scheduler.go
> Set critical pod annotations

- nodeup/pkg/distros/distribution.go
- nodeup/pkg/distros/identify.go
- nodeup/pkg/model/docker.go
- nodeup/pkg/model/kubectl.go
Recognize debian 9 and map docker on it
> Debian 9 (stretch) support

- Makefile
We need to copy to a location that is not mounted noexec
> GCE: fix makefile push-gce-run

- pkg/model/resources/nodeup.go
- pkg/model/tests/data/bootstrapscript_0.txt
- pkg/model/tests/data/bootstrapscript_1.txt
- pkg/model/tests/data/bootstrapscript_2.txt
- pkg/model/tests/data/bootstrapscript_3.txt
- pkg/model/tests/data/bootstrapscript_4.txt
- pkg/model/tests/data/bootstrapscript_5.txt
- tests/integration/minimal/cloudformation.json.extracted.yaml
Some images don't include curl but do have wget.  Prefer curl, but
fallback to wget.
(The official Debian 9 image does not have curl.)
> Support wget for download, not just curl

- channels/alpha
- channels/stable
- tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
Equivalent of https://github.com/kubernetes/kubernetes/pull/52120
> Update Google COS image

- nodeup/pkg/model/docker.go
Helps to understand what went wrong if something went wrong.
> nodeup: warn if no docker version matched

- Makefile
The build is still running on Mac, and I should problem do another with a clean.  But let's see how e2e like it.
> updating paths in Makefile for docker oddness

- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
- version.go
General maint on integration tests
> updating kops version so that we do not get warnings, fixing cf tests

- tests/integration/create_cluster/complex/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha/expected-v1alpha1.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_encrypt/expected-v1alpha1.yaml
- tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha1.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha1.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha1.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
> Cherry Pick of #3264

- docs/releases/1.7.1.md
Cherry-pick of https://github.com/kubernetes/kops/pull/3571 for master.
> 1.7.1 Release notes for master

- docs/cluster_spec.md
- Tested it with kops version 1.7 and k8s v1.7.2
> Document Enabling custom metrics API using kops

- nodeup/pkg/model/logrotate.go
Related to #2710, minor improvement mentioned in https://github.com/kubernetes/kops/pull/3488#issuecomment-333340885.
This change replaces the logrotate crontab with a systemd timer. Any existing systemd timer for logrotate will be overridden.
> Replace logrotate crontab with systemd timer

- docs/development/release.md
The command to push to the release branch was wrong, which meant the
release branch wasn't getting updated.
> Release docs update git push command

- Makefile
For https://github.com/kubernetes/kops/pull/3591
> Fix .PHONY

- upup/pkg/fi/cloudup/awstasks/load_balancer.go
- upup/pkg/fi/cloudup/terraform/literal.go
- upup/pkg/fi/cloudup/terraform/target.go
> Sort terraform literals in ELB task

- nodeup/pkg/model/docker.go
Add missing docker depednencies
> Docker dependencies for docker 1.12.6 on RHEL

- upup/models/cloudup/resources/addons/storage-gce.addons.k8s.io/v1.6.0.yaml
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
We only want to install the AWS storage class on AWS, and on GCE we want
to install the GCE storage class.
> GCE: Install correct storage class

- upup/pkg/fi/fitasks/BUILD.bazel
> Fix misssing bazel dependency

- Makefile
- upup/pkg/fi/cloudup/BUILD.bazel
- upup/pkg/fi/cloudup/tests/BUILD.bazel
Fixes: https://github.com/kubernetes/kops/issues/3626
> fixing bazel testing for upup

- docs/advisories/cve_2017_14491.md
> Added example output from a 1.4.12 cluster

- OWNERS
As requested by @chrislovecnm ;). Also puts all approvers as reviewers too. 
cc @justinsb
> Add myself as a reviewer

- addons/kubernetes-dashboard/v1.7.1.yaml
- docs/addons.md
https://github.com/kubernetes/dashboard/issues/2401, causing high CPU, is fixed in 1.7.1.
Image version number is the only change.
> update kubernetes-dashboard image version to v1.7.1

- pkg/model/network.go
- tests/integration/update_cluster/complex/kubernetes.tf
- tests/integration/update_cluster/ha/kubernetes.tf
- tests/integration/update_cluster/minimal-141/kubernetes.tf
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json
- tests/integration/update_cluster/minimal/kubernetes.tf
- tests/integration/update_cluster/privatecalico/kubernetes.tf
- tests/integration/update_cluster/privatecanal/kubernetes.tf
- tests/integration/update_cluster/privatedns1/kubernetes.tf
- tests/integration/update_cluster/privatedns2/kubernetes.tf
- tests/integration/update_cluster/privateflannel/kubernetes.tf
- tests/integration/update_cluster/privatekopeio/kubernetes.tf
- tests/integration/update_cluster/privateweave/kubernetes.tf
- tests/integration/update_cluster/shared_vpc/kubernetes.tf
This is a replacement for #3527 that I think makes more sense. Thanks!
Closes #2011
> [AWS] Properly tag public and private subnets for ELB creation

- nodeup/pkg/model/kubelet.go
Per https://github.com/kubernetes/kubernetes/pull/53564
> Rename flag from network-plugin-dir -> cni-bin-dir

- upup/pkg/fi/cloudup/awsup/machine_types.go
Adding support for P3 instances on AWS
> Updates for p3 machine type

- upup/pkg/fi/cloudup/gce/BUILD.bazel
- upup/pkg/fi/cloudup/gce/gce_cloud.go
Requires less permissions and is more correct.
> Use compute API to fetch default service account directly

- hack/.packages
- pkg/resources/BUILD.bazel
- pkg/resources/gce/BUILD.bazel
- pkg/resources/gce/gce.go
- pkg/resources/gce/gce_test.go
- pkg/resources/ops/BUILD.bazel
- pkg/resources/ops/collector.go
> Refactor gce resources into pkg/resources/gce

- upup/pkg/fi/cloudup/gcetasks/storagebucketacl.go
- upup/pkg/fi/cloudup/gcetasks/storageobjectacl.go
The messages were ambiguous at best, wrong at worst.
> Fix log messages from storage acl tasks

- util/pkg/vfs/vfs.go
Make it clearer that it needs to fetch all the files recursively
> Clarify comment on ReadTree

- docs/cluster_spec.md
- adding some documentation on the audit policy
> Audit Policy Docs

- OWNERS
So the bot will merge and I can get back in game :)
> Adding back to the approvers

- channels/alpha
- channels/stable
We are happily running k8s 1.7.10 and kops 1.7.1 in production since yesterday, so far so good :)
> Bump alpha and stable to latest

- docs/apireference/build/index.html
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/client/clientset_generated/clientset/scheme/register.go
- pkg/client/clientset_generated/internalclientset/scheme/register.go
- pkg/openapi/openapi_generated.go
/assign @justinsb @geojaz @andrewsykim
/approve
> updating api docs

- dns-controller/pkg/dns/dnscontext.go
- dns-controller/pkg/dns/dnscontroller.go
- dns-controller/pkg/watchers/ingress.go
- dns-controller/pkg/watchers/node.go
- dns-controller/pkg/watchers/pod.go
- dns-controller/pkg/watchers/service.go
Otherwise there's a chance that we have have extra records, particularly
in the case of a master restart and reconnect.
Fix #2572
> Verify that no extra records remain after a reconnection

- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
> upscale-delay flag in two more places

- pkg/model/BUILD.bazel
- upup/pkg/fi/cloudup/openstack/BUILD.bazel
- upup/pkg/fi/cloudup/openstacktasks/BUILD.bazel
> generate gazelle for cinder volume tasks

- OWNERS
- adding myself and kashifsaadat to the owners file .. proud moment :-)
> Owners files

- nodeup/pkg/model/file_assets.go
> Use EnsureTask so we don't have to track directories as closely

- pkg/model/firewall.go
- tests/integration/update_cluster/additional_user-data/cloudformation.json
- tests/integration/update_cluster/complex/kubernetes.tf
- tests/integration/update_cluster/ha/kubernetes.tf
- tests/integration/update_cluster/lifecycle_phases/security-kubernetes.tf
- tests/integration/update_cluster/minimal-141/kubernetes.tf
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json
- tests/integration/update_cluster/minimal/kubernetes.tf
- tests/integration/update_cluster/privatecalico/kubernetes.tf
- tests/integration/update_cluster/privatecanal/kubernetes.tf
- tests/integration/update_cluster/privatedns1/kubernetes.tf
- tests/integration/update_cluster/privatedns2/kubernetes.tf
- tests/integration/update_cluster/privateflannel/kubernetes.tf
- tests/integration/update_cluster/privatekopeio/kubernetes.tf
- tests/integration/update_cluster/privateweave/kubernetes.tf
- tests/integration/update_cluster/shared_subnet/kubernetes.tf
- tests/integration/update_cluster/shared_vpc/kubernetes.tf
Ports 2380 & 2381 should not be exposed to nodes.
Fix #3746
> Block etcd peer port from nodes

- cmd/kops/replace.go
- docs/cli/kops_replace.md
- pkg/client/simple/vfsclientset/cluster.go
> Fix segfault when updating non-existent object

- protokube/pkg/protokube/aws_volume.go
> Fix filepath concatenation

- pkg/instancegroups/instancegroups.go
> Spelling fix in instancegroups.go error msg

- pkg/resources/aws.go
- pkg/resources/dumpmodel.go
Proves very handy when diagnosing problems.
> Include roles in toolbox dump structured output

- cmd/kops/update_cluster.go
- cleaning up the bastion username line, stop you from getting
```shell
* to ssh to the bastion, you probably want to configure a bastionPublicNameThe admin user is specific to Debian...
```
> Bastion output line

- addons/kube-ingress-aws-controller/README.md
- addons/kube-ingress-aws-controller/addon.yaml
- addons/kube-ingress-aws-controller/v1.0.0.yaml
Adds an addon that needs some more requirements, because it has to have the rights to create/update/delete ALBs, find certificates, ..
I hope this is ok to have here a more long page to explain requirements and show some features that are not common in ingress implementations.
> add kube-ingress-aws-controller + skipper addons

- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
> Bump flannel packaging version

- pkg/validation/validate_cluster.go
When running `kops validate`, and the cluster size is greater than the minimum configuration, the display message is 
This PR sets the NodeCount value to the length of the nodes array instead of the configuration.
> Fix node counts

- upup/pkg/fi/nodeup/nodetasks/package.go
Otherwise we risk getting stuck on a prompt
> apt-get: specify unattended installation

- protokube/cmd/protokube/main.go
Remove superfluous if statement
> protokube: fix logging / logic around cluster-id

- protokube/cmd/protokube/main.go
Fix up the local IP address discovery logic, to recognize new
en-interfaces, and to better log what it is doing.  Plug it in for
baremetal installations.
> protokube: better discovery of local address

- pkg/apis/kops/validation/legacy.go
> validation: don't require subnet CIDRs on baremetal

- pkg/validation/BUILD.bazel
- upup/pkg/fi/cloudup/openstack/BUILD.bazel
- upup/pkg/fi/nodeup/BUILD.bazel
man we need a ci test for this :(
> fixing bazel

- cmd/kops/delete_secret.go
- cmd/kops/describe_secrets.go
- cmd/kops/get_secrets.go
- pkg/apis/kops/keyset.go
- pkg/sshcredentials/fingerprint.go
- upup/pkg/fi/ca.go
- upup/pkg/fi/clientset_castore.go
- upup/pkg/fi/secrets/vfs_secretstore.go
- upup/pkg/fi/vfs_castore.go
We now return KeySet objects
Builds on #3832
> Refactor CAStore to use API types

- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/0.1.1-kops.1.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/pre-k8s-1.6.yaml.template
This new image contains https://github.com/ottoyiu/k8s-ec2-srcdst/pull/5 and https://github.com/ottoyiu/k8s-ec2-srcdst/pull/6
> Update ottoyiu/k8s-ec2-srcdst docker image

- cmd/kops/delete_secret.go
- cmd/kops/get_secrets.go
- hack/.packages
- nodeup/pkg/model/BUILD.bazel
- nodeup/pkg/model/secrets.go
- pkg/model/BUILD.bazel
- pkg/model/pki.go
- pkg/tokens/BUILD.bazel
- pkg/tokens/wellknown.go
- upup/pkg/fi/secrets.go
- upup/pkg/fi/secrets/clientset_secretstore.go
- upup/pkg/fi/secrets/vfs_secretstore.go
This helps up with GCE permissions, but also helps us get rid of auth
tokens.
Builds on #3834
> Avoid ListSecrets call in nodeup

- docs/manifests_and_customizing_via_api.md
Quickie note for docs based on clarification in slack.
> Added a clarification/warning note about exporting full specs

- pkg/model/iam.go
- pkg/model/iam/iam_builder.go
- upup/pkg/fi/cloud.go
Add support for cn-northwest-1.
But I am not sure whether the packages under /vender/ are all supported.
> Add support for cn-northwest-1.

- cmd/kops/util/factory.go
- examples/kops-api-example/apply.go
- examples/kops-api-example/up.go
- pkg/client/simple/vfsclientset/clientset.go
- upup/pkg/fi/clientset_castore.go
- upup/pkg/fi/cloudup/populatecluster_test.go
- upup/pkg/fi/nodeup/command.go
- upup/pkg/fi/vfs_castore.go
Makes the mirror code essentially identical.
Builds on #3839
> Implement mirroring for API CAStore

- docs/boot-sequence.md
- docs/cluster_spec.md
- docs/development/hack.md
- docs/experimental.md
- docs/instance_groups.md
- docs/labels.md
Throughout my learning of Kops I've updated the docs on anything that was out of date or missing. Also fixed a few typos.
This should close out #2921
> Documentation Cleanup

- WORKSPACE
- hack/.packages
- kube-discovery/README.md
- kube-discovery/cmd/kube-discovery/BUILD.bazel
- kube-discovery/cmd/kube-discovery/main.go
- kube-discovery/images/BUILD.bazel
To split off master discovery from protokube.
> Add experimental kube-discovery

- docs/manifests_and_customizing_via_api.md
Added table of contents to document.  Updated command to include using
dry-run for the creations of YAML.
> Updating Manifest documentation

- docs/README.md
Adding missing documents from tutorial documents, and removing
duplicate.
> Updating docs README.md file

- Makefile
Trying to use bazel for the experimental targets.
> Add makefile target for kube-discovery image

- docs/commands.md
Adding the --target switch option in the documentation.
> Cloudformation

- docs/advisories/spectre-meltdown-kernel-update.md
Just noticed these as I was testing out the rollout on my own machines.
> Slight changes to commands.

- channels/alpha
Round of kubernetes updates, AMI with kernel 4.4.111
> Bump alpha channel

- cmd/kops/create_cluster.go
> Move net mode log after it is known in create

- pkg/model/components/apiserver.go
I'm not sure why Priority was added, happy to put it back if it's needed...
> Update list of AdmissionControllers for k8s 1.9

- .gitignore
- kube-discovery/cmd/kube-discovery/BUILD.bazel
- pkg/pki/BUILD.bazel
- upup/pkg/fi/BUILD.bazel
I'm not certain this is needed or correct, but makes my tree look good :)
> bazel 0.9.0 running `make bazel-build` updates

- channels/alpha
- channels/stable
> Use jessie for 1.10 as well, to unblock queue

- pkg/model/components/kubelet.go
Should fix https://github.com/kubernetes/kubernetes/pull/58367
> Don't specify require-kubeconfig from 1.10

- pkg/model/iam/iam_builder.go
- pkg/model/iam/tests/iam_builder_node_legacy.json
- pkg/model/iam/tests/iam_builder_node_strict.json
- pkg/model/iam/tests/iam_builder_node_strict_ecr.json
- tests/integration/update_cluster/additional_user-data/cloudformation.json
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json
> Fix ASG scaling by adding in ec2:DescribeRegions permission to the nodes IAM role

- dnsprovider/pkg/dnsprovider/providers/google/clouddns/clouddns.go
- upup/pkg/fi/cloudup/gce/gce_cloud.go
Turn off a few of the more spurious log messages
> GCE: Dial down logging

- cmd/kops/create_cluster.go
- cmd/kops/create_cluster_integration_test.go
We also pull a bit of logic out of the mega-function.
Fix #4210
> GCE: Don't require SSH public key

- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
We would loop forever on an unexpected error.
> AWS LaunchConfiguration error handling fix

- docs/addons.md
Bump the version to 1.8.1 in docs
> Bump kubernetes dashboard version to 1.8.1

- Makefile
update go version to 1.9.3 and add -w ldflag to remove DWARF symbol table from binary see: https://golang.org/cmd/link/
> update go version and ldflags

- images/dns-controller-builder/Dockerfile
- images/protokube-builder/Dockerfile
update dns-controller-builder and protokube-builder go version to 1.9.3
> update image go version

- upup/models/cloudup/resources/addons/networking.kope.io/k8s-1.6.yaml
- upup/models/cloudup/resources/addons/networking.kope.io/pre-k8s-1.6.yaml
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
No major changes, just version updates.
> Update kopeio-networking to 1.0.20180203

- docs/boot-sequence.md
- pkg/apis/kops/cluster.go
Just a couple things I noticed when reading documentation. Nothing critical.
I just signed the CNCF contributor agreement. I'm not sure how long that takes to show up when a PR is submitted.
> Documentation spelling/grammar fixes.

- pkg/instancegroups/instancegroups.go
> Fix drain command for rolling-updates

- .travis.yml
This appeared to work in my test, might need additional adjustments if we see specific issues.
cc: @chrislovecnm, @justinsb
> Add mac build for travis

- upup/models/cloudup/resources/addons/networking.romana/k8s-1.7.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This updates the template for romana networking to ship the latest released versions.
> Update versions for romana container images

- upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
Release notes: http://github.com/weaveworks/weave/releases/tag/v2.2.0
> Update Weave Net to version 2.2.0

- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
> Bump weave version to 2.2.0

- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha1/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/model/components/kubelet.go
- upup/models/cloudup/resources/addons/networking.kope.io/k8s-1.6.yaml
- upup/models/cloudup/resources/addons/networking.kope.io/pre-k8s-1.6.yaml
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.8.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/pre-k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.romana/k8s-1.7.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.7.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/pre-k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/kopeio-vxlan/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
* Ignore keyset.yaml
* Updates of networking components
> Cherrypicks for 1.8.1

- docs/cluster_spec.md
Update to the doc based on issue #4368
> API audit doc changes

- cmd/kops/toolbox_template.go
fix a typo in tool_template.go
> fix a typo in tool_template.go

- pkg/apis/kops/dockerconfig.go
- pkg/apis/kops/v1alpha1/dockerconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/dockerconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
More info: https://github.com/kubernetes/kops/issues/4160
> Add live-restore flag to docker config

- cmd/kops/create_ig.go
- cmd/kops/delete_instancegroup.go
- docs/cli/kops_create_instancegroup.md
- docs/cli/kops_delete_instancegroup.md
- docs/instance_groups.md
This addresses issue #4404, fixes instance groups docs given that the command it indicates there doesn't exactly work, and modifies an example in the command's `--help` UX.
> Fix instange groups docs

- addons/cluster-autoscaler/v1.8.0.yaml
> add storageclasses permissions for cluster-autoscaler:v1.1.0

- Makefile
Fixes #4491 and maybe #2785 as well.
> Fix -ldflags incompatibility in go1.10

- Makefile
- images/BUILD.bazel
- tools/get_workspace_status.sh
This avoids us a docker load / docker save, and should be a little faster.
> Build protokube tar in bazel

- pkg/apis/kops/dockerconfig.go
- pkg/apis/kops/v1alpha1/dockerconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/dockerconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- Just reordering the variables; i'm somewhat OCD on alphabetical sorting
> DockerConfig Order

- cmd/kops/set.go
- cmd/kops/set_cluster.go
This is based on #4381 and needs to be merged after that merges.  This fixes a nit pit that I would in the PR review.
> Fix snake case

- WORKSPACE
Could fix some issues, I don't think any other changes are required.
https://github.com/bazelbuild/rules_go/releases/tag/0.10.1
> Update rules go

- docs/run_in_existing_vpc.md
Mostly visual changes to make the information easier to digest.
Based on my experience creating a cluster in an existing VPC, few things went over my head.
> Clarify few things in Running an existing VPC

- docs/instance_groups.md
> Moving from one IG w multiple AZs to one IG per AZ

- nodeup/pkg/model/kube_proxy.go
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha1/componentconfig.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/model/bootstrapscript_test.go
- pkg/model/tests/data/bootstrapscript_0.txt
- pkg/model/tests/data/bootstrapscript_1.txt
- pkg/model/tests/data/bootstrapscript_2.txt
- pkg/model/tests/data/bootstrapscript_3.txt
- pkg/model/tests/data/bootstrapscript_4.txt
- pkg/model/tests/data/bootstrapscript_5.txt
- API changes following from the discussion on https://github.com/kubernetes/kops/issues/4415
> Kube-proxy API to accept cpu: limit, memory: request and limit

- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha1/networking.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/pre-k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
* Exposes Felix prometheus endpoint
* Same as `networking.projectcalico.org.canal`
> Expose Felix metrics

- .travis.yml
- Makefile
- hack/verify-apimachinery.sh
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
This PR adds a script that validates api machinery.  This script calls make, so that I could re-use a make target.  Updated travis to call the script.
> Verify apimachinery

- hack/update-bazel.sh
- hack/verify-bazel.sh
I should combine these into a single file ... but ok for now
> Bumping gazelle version on bazel scripts

- upup/pkg/fi/cloud.go
Adding support for the new Paris region. https://github.com/kubernetes/kops/issues/4113
> Adding support for new Paris region 

- pkg/model/network.go
- tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
- tests/integration/update_cluster/lifecycle_phases/network-kubernetes.tf
- tests/integration/update_cluster/privatecalico/kubernetes.tf
- tests/integration/update_cluster/privatecanal/kubernetes.tf
- tests/integration/update_cluster/privatedns1/kubernetes.tf
- tests/integration/update_cluster/privatedns2/kubernetes.tf
- tests/integration/update_cluster/privateflannel/kubernetes.tf
- tests/integration/update_cluster/privateweave/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/natgateway.go
Add tags to nat gateways
Fixes https://github.com/kubernetes/kops/issues/4604
> Tag nat gateways

- docs/aws-china.md
"failes" is an error, should be fails or failure.
> Typo fix "failes"->"fails"

- docs/releases/1.8.1.md
a grammatical error in line 4: "ignore ....; provides .... "
> Typo fix "provides"->"provide"

- docs/development/Docker.md
> Typo "offical"->"official"

- docs/examples/basic-requirements.md
> Typo fix "previouslly"->"previously"

- pkg/pki/certificate.go
- pkg/pki/privatekey.go
These messages are not very useful, even for v=8
> Reduce log levels: parsing pem block

- tests/BUILD.bazel
- tests/keypair_test.go
We have a nice diff library for printing diffs, use it for the tests.
> keypair integration test: print diffs

- upup/pkg/fi/fitasks/keypair.go
We don't need to special-case it
> Keypair: tweak Render logic

- cloudmock/aws/mockautoscaling/BUILD.bazel
- cloudmock/aws/mockautoscaling/attach.go
- cloudmock/aws/mockautoscaling/group.go
- cloudmock/aws/mockautoscaling/unimplemented.go
- cloudmock/aws/mockec2/BUILD.bazel
- cloudmock/aws/mockec2/api.go
- cloudmock/aws/mockec2/internetgateways.go
- cloudmock/aws/mockec2/natgateway.go
- cloudmock/aws/mockec2/tags.go
- cloudmock/aws/mockec2/unimplemented.go
- cloudmock/aws/mockelb/BUILD.bazel
- cloudmock/aws/mockelb/api.go
- cloudmock/aws/mockelb/attributes.go
- cloudmock/aws/mockelb/healthcheck.go
- cloudmock/aws/mockelb/tags.go
- cmd/kops/lifecycle_integration_test.go
- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
> More mocks - sufficient for privatecalico to roundtrip

- pkg/apis/kops/componentconfig.go
in line 337:
"ReconcilerSyncLoopPeriod" should be replaced with "AttachDetachReconcileSyncPeriod"
I think it's a mistake.
> Fix a mistake in componentconfig.go

- nodeup/pkg/model/docker.go
> Centos: add selinux package dependencies

- hack/update-header.sh
- hack/verify-boilerplate.sh
update-header.sh uses the output of verify-boilerplate
> Fix boilerplate scripts

- upup/pkg/fi/cloudup/awstasks/load_balancer.go
- upup/pkg/fi/cloudup/awstasks/loadbalancer_attributes.go
Should help us diagnose issue #4693, though not really a fix.
> Add more logging around ELB attribute modification

- pkg/model/network.go
> Don't tag shared VPCs

- cloudmock/aws/mockec2/vpcs.go
- pkg/resources/aws/BUILD.bazel
- pkg/resources/aws/aws.go
- pkg/resources/aws/errors.go
- pkg/resources/aws/filters.go
- pkg/resources/aws/tags.go
- pkg/resources/aws/vpc.go
- pkg/resources/aws/vpc_test.go
- pkg/testutils/integrationtestharness.go
> Improve logic around VPC detection

- nodeup/pkg/model/kube_proxy.go
We only do this for >= 1.9 so we don't change existing clusters.
Equivalent of https://github.com/kubernetes/kubernetes/pull/46259
> Mount the iptables lock file

- pkg/kubeconfig/create_kubecfg.go
We introduced some new heuristics in #3941 that meant we would access
private DNS names via the ELB's name, just as we do with gossip names.
But it's also possible to set up a VPN or DirectConnect and access a
private HostedZone directly, and in this case we don't want to use the
ELB DNS Name.  We recognize this case because the ELB can be set to
Internal (and probably should be, for minimal attack surface!)
We'll probably have to introduce a field for this, but hopefully this
heuristic is sufficient to unblock the release.
> Don't use ELB DNS name for internal ELBs

- upup/pkg/kutil/config.go
fix function comment error change ClientConfig -> SimpleClientConfig
```release-note
None
```
> fix function comment error

- pkg/apis/kops/v1alpha2/componentconfig.go
fix some grammar mistakes
```release-note
None
```
> fix some grammar mistakes

- protokube/pkg/protokube/kube_dns.go
fix a grammar mistake delete the "," at the end of the function comment
```release-note
None
```
> fix a grammar mistake

- upup/pkg/fi/cloudup/awstasks/elastic_ip.go
We need to discover the actual tags on an ElasticIP, or else
we will always have changes detected.
> ElasticIP: Collect tags

- pkg/model/master_volumes.go
- tests/integration/update_cluster/additional_user-data/cloudformation.json
- tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
- tests/integration/update_cluster/complex/kubernetes.tf
- tests/integration/update_cluster/ha/kubernetes.tf
- tests/integration/update_cluster/minimal-141/kubernetes.tf
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json
- tests/integration/update_cluster/minimal/kubernetes.tf
- tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
- tests/integration/update_cluster/privatecalico/kubernetes.tf
- tests/integration/update_cluster/privatecanal/kubernetes.tf
- tests/integration/update_cluster/privatedns1/kubernetes.tf
- tests/integration/update_cluster/privatedns2/kubernetes.tf
- tests/integration/update_cluster/privateflannel/kubernetes.tf
- tests/integration/update_cluster/privatekopeio/kubernetes.tf
- tests/integration/update_cluster/privateweave/kubernetes.tf
- tests/integration/update_cluster/shared_subnet/kubernetes.tf
- tests/integration/update_cluster/shared_vpc/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/ebsvolume.go
Currently we were only tagging it if shared, but tagging for owned
objects has fewer downsides.
> Make sure volumes are tagged

- tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
- tests/integration/update_cluster/lifecycle_phases/network-kubernetes.tf
- tests/integration/update_cluster/privatecalico/kubernetes.tf
- tests/integration/update_cluster/privatecanal/kubernetes.tf
- tests/integration/update_cluster/privatedns1/kubernetes.tf
- tests/integration/update_cluster/privatedns2/kubernetes.tf
- tests/integration/update_cluster/privateflannel/kubernetes.tf
- tests/integration/update_cluster/privateweave/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/elastic_ip.go
We previously weren't populating the terraform configuration with these
tags.
> ElasticIP tags for cloudformation & terraform

- docs/instance_groups.md
- pkg/apis/kops/instancegroup.go
- pkg/apis/kops/v1alpha1/instancegroup.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/instancegroup.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/awsmodel/autoscalinggroup.go
- tests/integration/update_cluster/additional_user-data/cloudformation.json
- tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- tests/integration/update_cluster/ha/kubernetes.tf
- tests/integration/update_cluster/lifecycle_phases/cluster-kubernetes.tf
- tests/integration/update_cluster/minimal-141/kubernetes.tf
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json
- tests/integration/update_cluster/minimal/kubernetes.tf
- tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
- tests/integration/update_cluster/privatecalico/kubernetes.tf
- tests/integration/update_cluster/privatecanal/kubernetes.tf
- tests/integration/update_cluster/privatedns1/kubernetes.tf
- tests/integration/update_cluster/privatedns2/kubernetes.tf
- tests/integration/update_cluster/privateflannel/kubernetes.tf
- tests/integration/update_cluster/privatekopeio/kubernetes.tf
- tests/integration/update_cluster/privateweave/kubernetes.tf
- tests/integration/update_cluster/shared_subnet/kubernetes.tf
- tests/integration/update_cluster/shared_vpc/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
Add support for instance monitoring.
Please review this PR carefully since it's my first contribution.
#4482
> Add support for instance monitoring

- channels/alpha
- channels/stable
Seems like we should always want people testing the latest alpha at this point!
> Bump channels to 1.9.0-alpha.3

- pkg/apis/kops/dockerconfig.go
- pkg/apis/kops/v1alpha1/dockerconfig.go
- pkg/apis/kops/v1alpha2/dockerconfig.go
Typo fix defailt->default in 3 dockerconfig.go files
> Typo fix defailt->default

- addons/ingress-nginx/v1.6.0-gce.yaml
- addons/ingress-nginx/v1.6.0.yaml
Keep update with the latest ingress-nginx version.
> Bump ingress-nginx version to 0.12.0

- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha1/cluster.go
- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/master_volumes.go
- upup/pkg/fi/cloudup/awstasks/ebsvolume.go
Fix for https://github.com/kubernetes/kops/issues/4720
same issue as https://github.com/kubernetes/kops/issues/3278
PR same like https://github.com/kubernetes/kops/pull/3102
> AWS: etcd volume provisioned IOPS support

- util/pkg/vfs/context.go
- util/pkg/vfs/s3fs.go
Adds DigitalOcean VFS which reuses the S3 VFS with the scheme and SSE configured. 
Related discussions: 
https://github.com/kubernetes/kops/pull/4697#discussion_r178475607 
https://github.com/kubernetes/kops/pull/4857#issuecomment-377837485
https://github.com/kubernetes/kops/pull/4235 
cc @justinsb 
Can wait til 1.10 release
> Add DigitalOcean VFS 

- pkg/apis/kops/validation/cluster.go
- pkg/apis/kops/validation/instancegroup.go
- pkg/model/awsmodel/autoscalinggroup.go
- pkg/model/master_volumes.go
https://github.com/kubernetes/kops/issues/4853
> Validation around IOPS fields

- upup/pkg/fi/cloudup/awstasks/ebsvolume.go
https://github.com/kubernetes/kops/issues/4854
> add output support to terraform & cloudformation for iops volume

- upup/pkg/fi/cloudup/gce/mock_gce_cloud.go
Line 64: "not yet implented" -> "not yet implemented"
> Typo fix in err message

- OWNERS
Over the past three months, @mikesplain and I have worked with @chrislovecnm as part of the first reviewer cohort in the K8s mentorship program. We have both now met the Reviewer requirements outlined in https://github.com/kubernetes/community/blob/master/community-membership.md#community-membership , namely:
* member for at least 3 months
* Primary reviewer for at least 5 PRs to the codebase
* Reviewed or merged at least 20 substantial PRs to the codebase
cc @parispittman
> Adding Mike and myself as reviewers

- upup/pkg/fi/cloudup/subnets.go
> Fix some info errors

- upup/pkg/fi/cloudup/template_functions.go
> Fixes port collision between dns-controller metrics and gossip.

- docs/examples/coreos-kops-tests-multimaster.md
- docs/images.md
as promised in https://github.com/kubernetes/kops/pull/4808
> removed sed from command to get AMI images

- cmd/kops/create_cluster.go
- cmd/kops/create_ig.go
- cmd/kops/validate_cluster.go
- docs/cli/kops_create_cluster.md
- docs/cli/kops_create_instancegroup.md
- docs/cli/kops_validate_cluster.md
changed file under cmd. and I run `make gen-cli-docs` , according to my PR [#4862](#4862)
> correct spell in the code and the relative doc

- pkg/model/domodel/droplets.go
- upup/pkg/fi/cloudup/dotasks/droplet.go
https://github.com/kubernetes/kops/issues/2150
> digitalocean: support multiple droplets

- pkg/apis/kops/v1alpha1/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
For some reason the proxy values got missed in a PR.
> Updating API Machinery

- nodeup/pkg/model/protokube.go
Line 119: "kubectl is downloaded an installed by other tasks"
Typo fix an->and
> Typo fix an->and

- upup/pkg/fi/cloudup/urls.go
> Fix grammar mistake

- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.6.yaml.template
cc @murali-reddy @roffe 
ref: https://github.com/kubernetes/kops/issues/4196
> fix version of kube-router at v0.1.0

- pkg/model/iam/iam_builder.go
> Avoid collisions in IAM ids

- channels/alpha
> Update alpha channel with latest k8s releases

- README.md
- docs/tutorial/digitalocean.md
https://github.com/kubernetes/kops/issues/2150
> digitalocean tutorial

- pkg/bundle/builder.go
- pkg/model/awsmodel/autoscalinggroup.go
- pkg/model/bootstrapscript.go
- pkg/model/bootstrapscript_test.go
- pkg/model/domodel/droplets.go
- pkg/model/gcemodel/autoscalinggroup.go
- pkg/model/resources/nodeup.go
- pkg/model/tests/data/bootstrapscript_0.txt
- pkg/model/tests/data/bootstrapscript_1.txt
- pkg/model/tests/data/bootstrapscript_2.txt
- pkg/model/tests/data/bootstrapscript_3.txt
- pkg/model/tests/data/bootstrapscript_4.txt
- pkg/model/tests/data/bootstrapscript_5.txt
- pkg/model/vspheremodel/autoscalinggroup.go
- tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
- upup/pkg/fi/cloudup/vspheretasks/attachiso.go
> Set AWS_REGION into bootstrapscript

- pkg/resources/digitalocean/resources.go
fixes https://github.com/kubernetes/kops/issues/4995
> digitalocean: only delete A DNS records

- docs/networking.md
There was a trivial error while exporting the environment variables for the zones which I fixed in this PR.
> Fixes environment variable export.
