- pkg/model/iam/iam_builder.go
- pkg/model/iam/tests/iam_builder_master_legacy.json
- pkg/model/iam/tests/iam_builder_master_strict.json
- pkg/model/iam/tests/iam_builder_master_strict_ecr.json
- pkg/model/iam/tests/iam_builder_node_legacy.json
- pkg/model/iam/tests/iam_builder_node_strict.json
- pkg/model/iam/tests/iam_builder_node_strict_ecr.json
`s3:ListBucketVersions` is required for permanently deleting files from the S3 state store (for now intended just for backups).
Followup for https://github.com/kubernetes/kops/pull/9171#discussion_r431245812.
> Allow listing versions for objects in the S3 bucket

- pkg/instancegroups/instancegroups.go
> Try validating multiple times before updating instancegroup

- pkg/model/iam/iam_builder.go
- pkg/model/iam/tests/iam_builder_master_legacy.json
- pkg/model/iam/tests/iam_builder_master_strict.json
- pkg/model/iam/tests/iam_builder_master_strict_ecr.json
- pkg/model/iam/tests/iam_builder_node_legacy.json
- pkg/model/iam/tests/iam_builder_node_strict.json
- pkg/model/iam/tests/iam_builder_node_strict_ecr.json
Cherry pick of #9205 on release-1.17.
#9205: Allow listing versions for objects in the S3 bucket
> Automated cherry pick of #9205: Allow listing versions for objects in the S3 bucket

- docs/development/adding_a_feature.md
- nodeup/pkg/model/context.go
- pkg/apis/kops/validation/validation_test.go
Move away from nodeup model files. This one is light on testing and the history is a bit revisionist, but there weren't a lot of examples that touched api, validation, and nodeup.
/cc @olemarkus
> Update adding_a_feature.md with more modern example

- docs/development/release.md
- hack/set-version
I had forgotten to automatically bump the
KUBE_APISERVER_HEALTHCHECK_TAG in the Makefile.
Also add pushing the image to the release procedure.
> Update set-version script to bump tag in Makefile

- util/pkg/vfs/context.go
Previously the EC2 metadata service was straightforward HTTP, but IMDS
v2 now requires managing a session token (and is more secure for it).
We now use the AWS SDK when retrieving metadata; it automatically
supports IMDS v2.
> Use AWS SDK to fetch metadata

- util/pkg/vfs/s3fs.go
This way we're not limited to one page of versions.  This is likely a
purely theoretical concern, at least as we're using it today.
> S3 DeleteAllVersions: use pagination

- pkg/apis/kops/validation/instancegroup.go
The mixed instance policy is also useful for spot instances, and
generally overriding the instances doesn't seem to be required.
Also both 0 and 1 instance type overrides appear to be supported by
AWS.
> Validation: MixedInstancePolicy need not override instance types

- Makefile
- hack/verify-hashes.sh
Prow should verify package hashes for containerd and Docker.
Reference: https://github.com/kubernetes/kops/pull/9215#issuecomment-636327311
/cc @rifelpet
> Add packages hashes verification for containerd and Docker

- netlify.toml
https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds
> Don't build site when docs are unchanged

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Two changes in this PR:
1. Upgrading image to version 1.6.2 following [release](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.6.2)
2. Applying changes to node selectors, following [this update](https://github.com/aws/amazon-vpc-cni-k8s/pull/937) to the upstream manifest
> Upgrde amazon vpc cni to 1.6.2

- docs/releases/1.18-NOTES.md
- docs/security.md
- nodeup/pkg/model/kube_apiserver.go
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-apiserver.yaml
Disables by default in k8s 1.18, can be re-enabled ~~by enabling basic auth. Removed in k8s 1.19~~ using instructions in security.md.
> Disable static tokens by default as of Kubernetes 1.18

- cmd/kops/describe_secrets.go
- docs/cli/kops_describe_secrets.md
> Add example for describe secret

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Cherry pick of #9237 on release-1.16.
#9237: Update etcd-manager to 3.0.20200531
> Automated cherry pick of #9237: Update etcd-manager to 3.0.20200531

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
Fixes RBAC for DO CCM.
Tested with the below change and ensured the cluster now comes up Ok.
> [Digital Ocean] Update RBAC for DO CCM

- cmd/kops/edit_instancegroup.go
The `cloudup.PopulateInstanceGroupSpec` directly after this calls `ValidateInstanceGroup` so this first call is redundant.
https://github.com/kubernetes/kops/blob/7b067983dfab5e78148dc9906242bed29efed455/upup/pkg/fi/cloudup/populate_instancegroup_spec.go#L61-L66
This is minor cleanup to help simplify the aws instance type validation PR
> Remove redundant ValidateInstanceGroup call

- .travis.yml
- Makefile
- docs/development/adding_a_feature.md
- docs/development/building.md
Adding the ARM64 build targets for kops and nodeup to see how build and CI is behaving.
This should be merged first to avoid issue with ARM64 assets not being found by `kops apply cluster`.
> Add ARM64 build targets for kops and nodeup

- go.mod
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/validation/BUILD.bazel
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
By default, Calico auto-detects the IP address to bind to from the IP addresses available on the host using a "first-found" policy.  This works, except when it doesn't.  This will sometimes fail on hosts that have multiple interfaces.  To work around this, Calico allows setting the IP_AUTODETECTION_METHOD environment variable and customizing how it selects the right IP address.
This PR adds the environment variables IP_AUTODETECTION_METHOD and IP6_AUTODETECTION_METHOD to the DaemonSet config and adds some api variables for this so they can be customized in the cluster yaml.
I'm not a kops expert by any means, so if there is a better way to do this please let me know.
> Enable configuration of the calico IP_AUTODETECTION_METHOD  and IP6_AUTODETECTION_METHOD

- upup/pkg/fi/cloudup/networking.go
Due to security advisory https://github.com/kubernetes/kubernetes/issues/91507, k/k upgraded the CNI binaries to 0.8.6 for 1.16+. We still support 1.15, so we should do it for it also.
Refs:
* https://github.com/kubernetes/kubernetes/pull/91370
* https://github.com/kubernetes/release/pull/1309
> Use CNI 0.8.6 for Kubernetes 1.15+

- docs/networking.md
- docs/networking/romana.md
- docs/releases/1.18-NOTES.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
As discussed on slack, we should have a table here to guide users at what kind of support one can expect.
There is a quite a bit to debate here.
The question marks is where I believe they have this status, but no idea since when. Predates the release logs so we can just default to 1.6 here if no one minds.
Romana is dead and I think this one is a no-brainer. Starting a new cluster with Romana hasn't worked since the introduction of etcd-manager.
Classic doesn't work. If you try to create the cluster, you get a validation error about classic not being a valid provider.
Kopeio is undocumented and not frequently modify. We could keep it at experimental. It seems to work when I install it.
Flannel has had its issues lately, but I am not too familiar with the status. My guess is experimental.
> Add table of networking providers and their status

- docs/releases/1.18-NOTES.md
- nodeup/pkg/model/docker.go
- pkg/apis/kops/validation/validation.go
- pkg/model/components/containerd.go
- pkg/model/components/docker.go
Due to security advisory kubernetes/kubernetes#91507, Docker 19.03.11 was released.
We may want to add and set this version as the default in 1.17 and 1.16 also.
Refs:
* https://github.com/docker/docker-ce/releases/v19.03.11
> Use Docker 19.03.11 for Kubernetes 1.18+

- docs/releases/1.18-NOTES.md
- nodeup/pkg/model/docker.go
- pkg/apis/kops/validation/validation.go
- pkg/model/components/containerd.go
- pkg/model/components/docker.go
Cherry pick of #9258 on release-1.18.
#9258: Use Docker 19.03.11 for Kubernetes 1.18+
> Automated cherry pick of #9258: Use Docker 19.03.11 for Kubernetes 1.18+

- docs/getting_started/aws.md
This could probably use additional cleanup but wanted to fix a link that I rediscovered while putting together the 1.18 conformance docs.
> Fix link to point to aws docs

- upup/pkg/fi/cloudup/networking.go
Cherry pick of #9256 on release-1.18.
#9256: Use CNI 0.8.6 for Kubernetes 1.15+
> Automated cherry pick of #9256: Use CNI 0.8.6 for Kubernetes 1.15+

- channels/alpha
- channels/stable
The latest patch release in the 1.15 series is 1.15.12, released 29 days ago, with plenty of bugfixes
> Update channel 1.15 k8s recommendation to 1.15.12

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Due to security advisory kubernetes/kubernetes#91507, new versions of Calico were released.
Ref: https://www.projectcalico.org/security-bulletins/
/assign @KashifSaadat
> Update Calico and Canal for CVE-2020-13597

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.15.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #9268 on release-1.18.
#9268: Update Calico and Canal for CVE-2020-13597
> Automated cherry pick of #9268: Update Calico and Canal for CVE-2020-13597

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
This will remove some cruft that is added to users' cluster spec.
> Tag all cilium keys with omitempty

- docs/getting_started/spot-ocean.md
- pkg/model/spotinstmodel/instance_group.go
- upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
- upup/pkg/fi/cloudup/spotinsttasks/ocean.go
This PR adds support for node draining timeout for both Elastigroup and Ocean.
> Spotinst: Allow a user specifiable node draining timeout

- pkg/apis/kops/validation/instancegroup.go
- pkg/apis/kops/validation/instancegroup_test.go
> Validate IG RootVolumeType

- pkg/acls/gce/storage.go
It's a pretty important message when permissions aren't set correctly;
let's re-enable it and then figure out more accurate conditions for
if it matters.
> gce: log bucket-policy-only message at a level that always appears

- pkg/model/iam/BUILD.bazel
- pkg/model/iam/iam_builder.go
- pkg/model/iam/iam_builder_test.go
- pkg/model/iam/tests/iam_builder_master_legacy.json
- pkg/model/iam/tests/iam_builder_master_strict.json
- pkg/model/iam/tests/iam_builder_master_strict_ecr.json
- pkg/model/iam/tests/iam_builder_node_legacy.json
- pkg/model/iam/tests/iam_builder_node_strict.json
- pkg/model/iam/tests/iam_builder_node_strict_ecr.json
If we are expected to write to other buckets, we need to have suitable
permissions to e.g. determine their location.
> Ensure we have IAM bucket permissions to other S3 buckets

- .travis.yml
The ARM64 test in TravisCI seems flaky and should be allowed to fail for now until we have a chance to see if anything can be improved.
> Allow failure of the ARM64 job in TravisCI

- channels/alpha
- channels/stable
As discussed in Kops Office Hours from Jun 5, 2020. 
Fixes #9163
> Use Ubuntu 20.04 as the default image for Kubernetes 1.18+

- pkg/model/components/kubelet.go
e2e pre-submits and periodic e2e for 1.19. Logs indicate it is related to the eviction manager that cannot correctly retrieve the disk stats:
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/e2e-kops-aws-k8s-latest/1269848278476787712/
```
W0608 04:40:31.222453    4996 eviction_manager.go:339] eviction manager: attempting to reclaim ephemeral-storage
I0608 04:40:31.222488    4996 container_gc.go:85] attempting to delete unused containers
I0608 04:40:31.225274    4996 image_gc_manager.go:322] attempting to delete unused images
I0608 04:40:31.231317    4996 eviction_manager.go:350] eviction manager: must evict pod(s) to reclaim ephemeral-storage
I0608 04:40:31.231341    4996 eviction_manager.go:368] eviction manager: pods ranked for eviction: …
```
> Disable disk based evictions for Kubernetes 1.19

- nodeup/pkg/model/BUILD.bazel
- nodeup/pkg/model/fakes_test.go
- nodeup/pkg/model/kube_apiserver_test.go
- nodeup/pkg/model/kube_controller_manager_test.go
- nodeup/pkg/model/kube_proxy_test.go
- nodeup/pkg/model/kube_scheduler_test.go
- nodeup/pkg/model/kubelet_test.go
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-controller-manager.yaml
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-proxy.yaml
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-scheduler.yaml
Add tests for kube-controller-manager, kube-proxy, kube-scheduler
> More nodeup golden tests

- mkdocs.yml
I've noticed that we don't have recent releases in the nav pane (the most recent is 1.16).
I added 1.17 release and 1.18 (marked as beta)
> Adding recent releases to docs site

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Due to security advisory kubernetes/kubernetes#91507, new versions of Weave was released.
Ref: https://github.com/weaveworks/weave/releases/tag/v2.6.3
> Update Weave for CVE-2020-13597

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #9285 on release-1.18.
#9285: Update Weave for CVE-2020-13597
> Automated cherry pick of #9285: Update Weave for CVE-2020-13597

- nodeup/pkg/model/networking/BUILD.bazel
- nodeup/pkg/model/networking/weave.go
- upup/pkg/fi/nodeup/command.go
Weave requires `portmap` that seems to be missing at the moment:
https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#-installation
e2e tests are failing because of the missing portmap plugin:
https://testgrid.k8s.io/kops-network-plugins#kops-aws-cni-weave
```
E0608 09:35:30.294544    5002 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
I0608 09:35:33.143148    5002 kubelet.go:1952] SyncLoop (PLEG): "weave-net-6v74s_kube-system(14526285-9260-43e3-8c5e-62eb340b2dc1)", event: &pleg.PodLifecycleEvent{ID:"14526285-9260-43e3-8c5e-62eb340b2dc1", Type:"ContainerStarted", Data:"6cea0ffccafd5578fc62e565b78258d4d10bc6fc11be27b5e1990fbc0b40cf2e"}
W0608 09:35:34.281513 …
```
> Copy "portmap" to /opt/cni/bin for Weave

- pkg/kubeconfig/BUILD.bazel
- pkg/kubeconfig/create_kubecfg.go
Cherry pick of #9284 on release-1.18.
#9284: Don't export basic auth credentials if basic auth is disabled
> Automated cherry pick of #9284: Don't export basic auth credentials if basic auth is disabled

- nodeup/pkg/model/etcd_manager_tls.go
> Don't try building TLS for etcd-manager if not using etcd-manager

- pkg/apis/kops/topology.go
- pkg/apis/kops/validation/legacy.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- upup/pkg/fi/cloudup/validation_test.go
> Refactor and improve API validation

- cmd/kops/create_cluster.go
kube-router e2e jobs have been failing for a while: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-cni-kuberouter/1270539617296191488
```
Completed cluster failed validation: spec.spec.kubeProxy.enabled: Forbidden: kube-router requires kubeProxy to be disabled
172
2020/06/10 02:15:10 process.go:155: Step '/tmp/kops502689941/kops create cluster --name e2e-kops-aws-cni-kuberouter.test-cncf-aws.k8s.io --ssh-public-key /workspace/.ssh/kube_aws_rsa.pub --node-count 4 --node-volume-size 48 --master-volume-size 48 --master-count 1 --zones eu-west-1b --master-size c5.large --kubernetes-version https://storage.googleapis.com/kubernetes-release/release/v1.18.3 --admin-access 35.238.143.128/32 --cloud aws --networking=kube-router --override cluster.spec.nodePortAccess=0.0.0.0/0' …
```
> Disable kubeproxy when creating a kube-router cluster

- nodeup/pkg/model/networking/calico.go
- nodeup/pkg/model/networking/canal.go
- nodeup/pkg/model/networking/common.go
- nodeup/pkg/model/networking/flannel.go
Installing *all* CNI plugin binaries seems more reliable considering that we are supporting pretty much most known network plugins.
These binaries are harmless. Even the `flannel` one that was a concern previously is not such a big issue, just collecting and configuring other CNI plugins required for Flannel (such as bridge plugin).
https://github.com/containernetworking/plugins/tree/master/plugins/meta/flannel#overview
This should also fix the failing tests for older Kubernetes releases where not all binaries are available (in this case `bandwidth`):
```
W0609 20:53:12.021210    1202 main.go:138] got error running nodeup (will retry in 30s): error building loader: unable to locate asset "bandwidth"
```
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-k8s-1-14/127045807985 …
> Install all CNI plugin binaries for all network plugins

- nodeup/pkg/model/docker.go
- nodeup/pkg/model/tests/dockerbuilder/docker_1.12.1/tasks.yaml
- nodeup/pkg/model/tests/dockerbuilder/logflags/tasks.yaml
- nodeup/pkg/model/tests/dockerbuilder/simple/tasks.yaml
- pkg/apis/kops/validation/validation.go
- pkg/model/components/docker.go
Due to security advisory kubernetes/kubernetes#91507, Docker 19.03.11 was released.
This is a back-port of #9258.
Ref: https://github.com/docker/docker-ce/releases/v19.03.11
> Use Docker 19.03.11 for Kubernetes 1.17+

- nodeup/pkg/model/docker.go
- nodeup/pkg/model/tests/dockerbuilder/docker_1.12.1/tasks.yaml
- nodeup/pkg/model/tests/dockerbuilder/logflags/tasks.yaml
- nodeup/pkg/model/tests/dockerbuilder/simple/tasks.yaml
- pkg/apis/kops/validation/validation.go
- pkg/model/components/docker.go
Cherry pick of #9314 on release-1.16.
#9314: Use Docker 19.03.11 for Kubernetes 1.17+
> Automated cherry pick of #9314: Use Docker 19.03.11 for Kubernetes 1.17+

- nodeup/pkg/model/context.go
- nodeup/pkg/model/etcd_manager_tls.go
- nodeup/pkg/model/kube_apiserver_healthcheck.go
- nodeup/pkg/model/kube_controller_manager.go
- nodeup/pkg/model/kube_scheduler.go
- nodeup/pkg/model/networking/cilium.go
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-controller-manager.yaml
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-scheduler.yaml
- pkg/model/pki.go
- pkg/testutils/modelharness.go
- upup/pkg/fi/nodeup/nodetasks/BUILD.bazel
- upup/pkg/fi/nodeup/nodetasks/issue_cert.go
- upup/pkg/fi/nodeup/nodetasks/kubeconfig.go
- upup/pkg/fi/resources.go
- upup/pkg/fi/topological_sort.go
Need to research how to make the golden output more readable/useful.
/cc @justinsb
> Issue kube-scheduler and kube-controller-manager certs in nodeup

- cmd/kops/update_cluster.go
- cmd/kops/validate.go
- cmd/kops/validate_cluster.go
- docs/cli/kops_validate.md
- docs/cli/kops_validate_cluster.md
- docs/getting_started/aws.md
- docs/rotate-secrets.md
- docs/single-to-multi-master.md
* Add `--wait` to most `kops validate cluster` examples. Some confusion there because the help text is reused as well. See #1517 
* Ubuntu instead of Debian since I was in the neighbourhood
> Docs helptext

- upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #8965 #9285 on release-1.16.
#8965: Fix missing changes in Weave manifest
#9285: Update Weave for CVE-2020-13597
> Automated cherry pick of #8965: Fix missing changes in Weave manifest #9285: Update Weave for CVE-2020-13597

- pkg/assets/builder.go
- pkg/kubemanifest/images.go
- pkg/kubemanifest/manifest.go
Primarily renaming manifests to objects, which is a more accurate
term.
> Refactor kubemanifest to be clearer

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.8.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #9330 on release-1.18.
#9330: Update Weave Net to 2.6.5
> Automated cherry pick of #9330: Update Weave Net to 2.6.5

- docs/cluster_spec.md
- docs/releases/1.18-NOTES.md
Another instance of #9151. See #9350 
Also think this deserves a mention in the release notes
> Add nodelocal dns cache to release notes and add kops version to docs

- docs/releases/1.17-NOTES.md
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/storage-aws.addons.k8s.io/v1.15.0.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Dropping the annotation versus setting it to `false` breaks cluster upgrades.
Set the old `gp2` StorageClass explicitly not the default
Fixes https://github.com/kubernetes/kops/issues/9336
> Bug: Explicitly set default StorageClass to support upgrades

- docs/releases/1.17-NOTES.md
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/storage-aws.addons.k8s.io/v1.15.0.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #9337 on release-1.18.
#9337: Explicitly set default storageclass to support upgrades
> Automated cherry pick of #9337: Explicitly set default storageclass to support upgrades

- nodeup/pkg/model/kubectl.go
Cherry pick of #8798 #8800 on release-1.17.
#8798: Update default users for kubeconfig with supported distros
#8800: Update default user for CoreOS, Flatcar for kubecfg
Fixes #9358
> Automated cherry pick of #8798 #8800: Update default users for kubeconfig with supported distros

- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- pkg/model/components/BUILD.bazel
- pkg/model/components/cilium.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.7.yaml.template
- upup/pkg/fi/cloudup/populate_cluster_spec.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
It is a bit too easy for Cilium users to configure unsupported combinations of cilium version and features. This PR ensures that users only set a supported version. Plan on follow-ups that will validate various features as well.
> Validate cilium version

- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Cherry pick of #9367 on release-1.17.
#9367: Bump cilium to 1.7.5
> Automated cherry pick of #9367: Bump cilium to 1.7.5

- pkg/model/components/kubeapiserver/model.go
- pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
Use a [valid tag](https://hub.docker.com/r/kope/kube-apiserver-healthcheck/tags) for the kube-apiserver-healthcheck image
> Fix kube-apiserver-healthcheck image

- pkg/model/components/kubeapiserver/model.go
- pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
This reverts commit 7e52f223
Likely cause of e2e failures.
> Revert "Fix kube-apiserver-healthcheck image"

- cmd/kube-apiserver-healthcheck/BUILD.bazel
- cmd/kube-apiserver-healthcheck/README.md
- cmd/kube-apiserver-healthcheck/main.go
- cmd/kube-apiserver-healthcheck/proxy_test.go
- docs/boot-sequence.md
- nodeup/pkg/model/BUILD.bazel
- nodeup/pkg/model/kube_apiserver.go
- pkg/model/components/apiserver.go
- pkg/model/components/kubeapiserver/BUILD.bazel
- pkg/model/components/kubeapiserver/model.go
- pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
- pkg/wellknownports/wellknownports.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
I am unable to test the node-local-dns change.
> Move host-network services off of port 8080

- cmd/kube-apiserver-healthcheck/BUILD.bazel
- cmd/kube-apiserver-healthcheck/README.md
- cmd/kube-apiserver-healthcheck/main.go
- cmd/kube-apiserver-healthcheck/proxy_test.go
- docs/boot-sequence.md
- nodeup/pkg/model/BUILD.bazel
- nodeup/pkg/model/kube_apiserver.go
- pkg/model/components/apiserver.go
- pkg/model/components/kubeapiserver/BUILD.bazel
- pkg/model/components/kubeapiserver/model.go
- pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
- pkg/wellknownports/wellknownports.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
Cherry pick of #9355 on release-1.18.
#9355: Move kube-apiserver-healthcheck to port 3990
> Automated cherry pick of #9355: Move kube-apiserver-healthcheck to port 3990

- .github/workflows/main.yml
To document the changes in https://github.com/kubernetes/test-infra/pull/17857.
/cc @rifelpet
Holding until that PR merges and make sure it works.
/hold
> Add comment on blocking jobs to actions

- images/mkdocs/.dockerignore
- images/mkdocs/Dockerfile
- images/mkdocs/requirements.txt
- mkdocs.yml
- netlify.toml
The biggest improvement I see is much snappier search results.
followed the material theme upgrade instructions [here](https://squidfunk.github.io/mkdocs-material/releases/5/)
> Upgrade mkdocs to latest versions

- .github/workflows/main.yml
- .travis.yml
> try github actions failure to see if PRs can't be merged 

- Makefile
- hack/verify-gomod.sh
This will actually catch vendoring issues.
also removing it from `make travis-ci` because `make gomod` depends on bazel which isnt available in travis. `make gomod` has its own prow job though, so we still get sufficient coverage.
> Run "go mod vendor" in verify-gomod

- .github/workflows/main.yml
- .travis.yml
This reverts commit b85c0a47e537d7039a0c911520eb07f9687b3710.
> Revert "try github actions failures to see if PRs can't be merged"

- docs/cluster_spec.md
Updating docs with two extra flags which allowed me finally to enforce resource allocation for kubelet on flatcar linux, altho might be valid for other distros too.
Potentially fixes/closes https://github.com/kubernetes/kops/issues/3223 ?
> Updating cluster_spec doc.

- Makefile
- hack/verify-gomod.sh
Cherry pick of #9389 on release-1.18.
#9389: Run "go mod vendor" in verify-gomod
> Automated cherry pick of #9389: Run "go mod vendor" in verify-gomod

- hack/verify-terraform.sh
The provider binaries are in the hundreds of MBs and by defaulta are redownloaded into each integration tests' directory, this is a waste of bandwidth, time, and space.
TF supports specifying a [provider cache directory](https://www.terraform.io/docs/configuration/providers.html#provider-plugin-cache) which will avoid redownloading them and storing them in multiple places, which should speed up the job time by a bit.
I was having trouble getting it to work with TF 0.12 so I bumped us up to the latest 0.13 beta (stable is scheduled for ~1 month from now)
> Cache terraform's providers between tests

- .shipbot.yaml
- Makefile
Kops moved to SHA256 and SHA1 are no longer used.
> Stop creating SHA1 hashes for build artifacts

- .github/workflows/main.yml
- .travis.yml
GO 1.14 is planned for Kubernetes 1.19. There is no reason to keep CI jobs for it for Kubernetes 1.18.
> Remove go 1.14 CI jobs for k8s 1.18

- Makefile
- hack/make-apimachinery.sh
Without this set, go 1.13 was redownloading all dependencies into the module cache, effectively ignoring the vendor directory.
This instructs go 1.13 to always use (and verify the contents of) the vendor directory.
See an example prow job [here](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kops/9389/pull-kops-verify-govet/1273460433402990595). All of the `go: downloading` and `go: extracting` lines indicate its downloading those dependencies rather than using the vendor directory.
Unsetting it for when we actually update the vendor directory with `make gomod`.
I'm not sure if/how this affects bazel
Ref: https://github.com/kubernetes/kops/pull/9389#issuecomment-645757357
> Use -mod=vendor for most go commands

- OWNERS
@olemarkus has been an active contributor and reviewer for some time now and I think he would make a great addition to the Kops reviewers.
> Add olemarkus as reviewer

- nodeup/pkg/model/containerd.go
Docker builds the containerd binaries differently than containerd does.
This makes possible some things like enabling SELinux, which otherwise as described in https://github.com/kubernetes/kops/pull/9334#issuecomment-642601044.
Using containerd from the docker packages should ensure better compatibility.
> Temporarily use containerd from Docker packages

- upup/pkg/fi/cloudup/awsup/machine_types.go
> Add support for c5a aws ec2 instance types

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Ref: https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.6.3
> Upgrade Amazon VPC CNI to 1.6.3

- docs/operations/high_availability.md
> Clean up the HA docs

- cmd/kops/create_cluster.go
- docs/cli/kops_create_cluster.md
As discussed during office hours, we decided to add these new options to help test ARM64 deployments.
> Add master and node image options when creating a cluster

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
* Use multiarch where possible. Remove hardcoded use of amd64-only images.
* Remove Arch templating function as an approach using this will not
work anyway
* No multiarch version of dns autoscaler, so force this one to run on
master for now.
> Make dns pods work on arm64 clusters

- docs/getting_started/commands.md
This is a follow up to PR #9132 which wasn't applied, the original author never signed the CLA.
While out there, I went through the entire doc and fixed a few other things that made sense to me.
> Typo and wording fix to getting_started/commands doc

- Makefile
Builds have become slower since extra targets for ARM64 were added.
For now, tests are only done on Linux AMD64 and now ARM64, so makes sense to only build and upload those artifacts that are needed in tests.
This PR stops building and uploading only the `kops` binary for Linux ARM64, MacOS and Windows.
> Build and publish only Linux AMD64 Kops artifacts for CI

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Fixes #4877
The main problem is using the default rolling upgrade strategy. If the `dns-controller` is created on the same node during the upgrade we are seeing this issue as this is `hostNetwork` pod
```
panic: listen tcp4 0.0.0.0:3998: bind: address already in use
```
example:
```
dns-controller-5f88fdd576-d8d6m     0/1     CrashLoopBackOff   11         35m   172.16.45.40        ip-172-16-45-40.us-west-2.compute.internal    <none>           <none>
dns-controller-68f76b5848-kdfhm     1/1     Running            0          51m   172.16.45.40        ip-172-16-45-40.us-west-2.compute.internal    <none>           <none>
```
This PR will use `Recreate` strategy to avoid this issue
> Fix: dns-controller: 3999 port address already in use

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Use `kubernetes.io/role` instead of `kubernetes.io/arch` as nodeselector. This will work for all supported versions of K8s.
ref #9418 
/cc @hakman @johngmyers
> Fix dns selectors for older k8s

- upup/pkg/fi/cloudup/awsup/machine_types.go
Cherry pick of #9386 on release-1.17.
#9386: add c5a ec2 aws support
> Automated cherry pick of #9386: add c5a ec2 aws support

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #9404 on release-1.18.
#9404: Fix: dns-controller: 3999 port address already in use
> Automated cherry pick of #9404: Fix: dns-controller: 3999 port address already in use

- cmd/kops/create_cluster.go
- upup/pkg/fi/cloudup/BUILD.bazel
- upup/pkg/fi/cloudup/new_cluster.go
This is initial work in pushing some of the logic that is in create_cluster into pkg for use as an import.
My intent for `NewCluster()` is for it to initialize the cluster and instance group specs, but not query or update the cluster state in the state store.
We try to approximate GitOps and want to avoid configuration drift between "defaults for new clusters" and "defaults or existing clusters". Our existing update cluster code always goes through a `kops create cluster --dry-run` for that reason and we would like to instead call this `NewCluster()` code.
> Start pushing create_cluster logic into pkg

- pkg/model/spotinstmodel/instance_group.go
This PR aligns the [Spotinst Instance Group model](https://github.com/kubernetes/kops/blob/master/pkg/model/spotinstmodel/instance_group.go#L573-L583) with the [AWS one](https://github.com/kubernetes/kops/blob/master/pkg/model/awsmodel/autoscalinggroup.go#L218-L229) by adding the missing `Lifecycle` field to `awstasks.SecurityGroup` for every additional security groups.
> Spotinst: Add missing lifecycle to awstasks.SecurityGroup

- pkg/model/BUILD.bazel
- pkg/model/bootstrapscript.go
- pkg/model/bootstrapscript_test.go
- pkg/model/openstackmodel/servergroup_test.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/tagbuilder.go
- upup/pkg/fi/cloudup/tagbuilder_test.go
- upup/pkg/fi/resources.go
In order to issue the `kubernetes-master` server cert out of nodeup, I'm going to need to pass the loadbalancer IP in userdata. That means the code that is currently in `BootstrapScript.ResourceNodeUp()` is going to have to run later, after the load balancer IPs have been determined.
This refactoring is in preparation for that. It pulls code out of `BootstrapScript.NodeupConfigBuilder` that probably should not be run later.
> Prepatory refactoring of BootstrapScript

- docs/networking/cilium.md
- nodeup/pkg/model/networking/cilium.go
- pkg/model/iam/iam_builder.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
This PR fixes two issues:
* One where we have changed the etcd-manager cert files, but forgotten to change the names in the cilium manifest
* One where the check used for deploying cilium cert files used `etcdManaged` instead of testing for the the existence of the cilium cluster making a graceful migration from CRD to etcd impossible.
This PR also adds some documentation around migrating to etcd and about migrating to/from nodeport.
Fixes #9448 
Fixes #9446
> Fix cilium etcd migration

- pkg/model/spotinstmodel/instance_group.go
- upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
This PR adds support for Root Volume Size in Ocean Launch Spec.
> Spotinst: Support for Root Volume Size in Ocean Launch Spec

- docs/networking/cilium.md
- nodeup/pkg/model/cilium.go
- pkg/model/iam/iam_builder.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
Cherry pick of #9451 on release-1.18.
#9451: Deploy cilium etcd credentials if the cilium cluster
> Automated cherry pick of #9451: Deploy cilium etcd credentials if the cilium cluster

- channels/alpha
Updating alpha channel with k8s releases from yesterday.
The previously set versions in this channel seem to have had a bug/regression with hyperkube, so I figured there's no point pushing those into `stable` channel. Instead- we'll let the new releases bake-in for about a week and then push them to `stable`.
[More info about the bug in the release page](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#bug-or-regression)
> Bump k8s versions for alpha channel with latest releases

- cmd/kops/create_cluster.go
- docs/networking/cilium.md
- docs/releases/1.19-NOTES.md
Upstream default since cilium 1.7 and perhaps the primary reason why people pick cilium.
> Enable nodeport by default

- addons/ambassador/README.md
- addons/ambassador/addon.yaml
- addons/ambassador/ambassador-operator.yaml
This commit adds Ambassador (https://getambassador.io/) addon to
Kops.
Ambassador is installed via Ambassador Operator which is the
recommended way of installed Ambassador - it makes sure users
always have the latest version of Ambassador installed and takes
care of the update schedule as well.
CC: @brucehorn @inercia
> Add Ambassador addon to kops

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://docs.projectcalico.org/archive/v3.15/release-notes/
> Update Calico to v3.15.0 for k8s 1.16+

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
During the move from https://console.cloud.google.com/gcr/images/google-containers to https://console.cloud.google.com/gcr/images/k8s-artifacts-prod, some images were lost so older versions are not starting because of this.
This is also a good opportunity to bump the version to latest for `kube-dns` and `cluster-proportional-autoscaler`.
> Update KubeDNS to v1.15.13

- pkg/apis/kops/validation/validation.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
- pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
- upup/pkg/fi/fitasks/managedfile.go
Currently if a user defines a non-standard backupStore location, such as:
- backups:
backupStore: s3://my-bucket/etcdBackup/my-cluster.local
the etcd-cluster-spec is still written to the default location and ignores the store set in backupStore. This in turn causes etcd-manager to not start etcd since it still honors the user defined backupStore location.
------
This is an alternative to #9319
> Fix where etcd-cluster-spec is writen when etcd's BackupStore is defined -v2

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #9444 on release-1.18.
#9444: Update Calico to v3.15.0 for k8s 1.16+
> Automated cherry pick of #9444: Update Calico to v3.15.0 for k8s 1.16+

- docs/terraform.md
Also remove some outdated terraform instructions (0.7 was released in 2016)
followup to https://github.com/kubernetes/kops/pull/9416
> Update terraform docs with version compatibility

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #9462 on release-1.18.
#9462: Update KubeDNS to v1.15.13
> Automated cherry pick of #9462: Update KubeDNS to v1.15.13

- nodeup/pkg/model/docker.go
- nodeup/pkg/model/packages.go
- nodeup/pkg/model/tests/dockerbuilder/docker_18.06.3/tasks.yaml
- nodeup/pkg/model/tests/dockerbuilder/healthcheck/tasks.yaml
- nodeup/pkg/model/tests/dockerbuilder/logflags/tasks.yaml
- nodeup/pkg/model/tests/dockerbuilder/simple/tasks.yaml
Cherry pick of #9465 on release-1.18.
#9465: Update the service manifest for Docker 
> Automated cherry pick of #9465: Update the service manifest for Docker

- Makefile
- tools/get_version.sh
- tools/get_workspace_status.sh
This is working towards "hands off" release builds, where we just tag
the release.  When CI=1 and the git sha we are building _exactly_
matches a tag, we build that version.  We enforce that version.go must
have previously been updated to match the tag.
We also refactor out the duplicated code into a shared script (tools/get_version.sh)
> Allow CI builds to build a tagged version

- Makefile
- pkg/model/components/kubeapiserver/model.go
- pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
- version.go
As this is the first release of the 1.19.0 alpha series, I think we
can try releasing from the automated build.  I _believe_ that tags
will now be automatically be built by CI.  So (if this works) the
process will be:
* We merge the "release" PR, but it's not yet tagged
* It merges and prow and cloudbuild build it like any other PR, with a
"CI" version (i.e. not the correct version number, yet).
* Our normal e2e tests will run against it (and our normal PR tests
run against it).
* We then tag that version (manually, currently).  This should trigger
a build with the version set to that tag - though it still goes to
our staging area.
* We can perform additional validation against that build (including,
in future, automated validation against the "last tag"?)
* We then promote that build to …
> Release 1.19.0-alpha.1

- nodeup/pkg/model/kubelet.go
- nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
- pkg/model/components/kubelet.go
- tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml
xRef: https://github.com/kubernetes/kubernetes/pull/62982
```bash
$ kubelet --help | grep  docker-specific | tr -s " " | cut -d " " -f 2
--cni-bin-dir
--cni-cache-dir
--cni-conf-dir
--docker-endpoint
--image-pull-progress-deadline
--network-plugin
--network-plugin-mtu
--pod-infra-container-image
```
> Use kubelet docker-specific flags only for Docker

- cloudbuild.yaml
This allows them to be promoted to k8s.gcr.io (when we nominate them
for promotion)
> cloudbuild: Push additional images from cloudbuild

- WORKSPACE
In preparation for updating to go 1.14, we need to at least update rules_go. I updated the other rules while I was at it.
* [rules_go](https://github.com/bazelbuild/rules_go/releases/tag/v0.23.3)
* [rules_docker](https://github.com/bazelbuild/rules_docker#setup) 
* [bazel-gazelle](https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.21.1)
* [bazel-toolchains](https://github.com/bazelbuild/bazel-toolchains/releases/tag/2.2.0) to match the .bazelversion file
> Update bazel rules versions

- hack/verify-terraform.sh
Cherry-pick 5499402227f9de5ad5ad0cd11de37e908e39add4 from #9340 
Also cherry-pick #9399
> Fix verify-terraform in release-1.18 branch

- nodeup/pkg/model/kubelet.go
- nodeup/pkg/model/tests/kubelet/featuregates/tasks.yaml
- pkg/model/components/kubelet.go
- tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml
Cherry pick of #9495 on release-1.18.
#9495: Use kubelet docker-specific flags only for Docker
> Automated cherry pick of #9495: Use kubelet docker-specific flags only for Docker

- docs/cluster_spec.md
- pkg/apis/kops/validation/validation.go
- pkg/model/components/kubelet.go
> Default ClusterDNS appropriately when NodeLocalDNS is enabled

- docs/cluster_spec.md
- pkg/apis/kops/validation/validation.go
- pkg/model/components/kubelet.go
Cherry pick of #9491 on release-1.18.
#9491: Default ClusterDNS appropriately when NodeLocalDNS is enabled
> Automated cherry pick of #9491: Default ClusterDNS appropriately when NodeLocalDNS is enabled

- cmd/kops/create_cluster.go
- docs/cli/kops_create_cluster.md
- docs/networking/aws-vpc.md
Both values are valid:
https://github.com/kubernetes/kops/blob/030b7dc7401d5e12eddf2abcf48f2ba3f7547cea/cmd/kops/create_cluster.go#L615-L616
but `amazonvpc` is more concise so it probably makes more sense to use that in the `create cluster` help text and the docs.
> Update AWS VPC CNI docs to use `--networking amazonvpc`

- docs/operations/addons.md
In #9115, I forgot to add Ambassador documentation to the addons section in the docs at https://kops.sigs.k8s.io/operations/addons/. This PR fixes that.
Ping @mikesplain
> Add Ambassador documentation to addons docs

- cmd/kops/BUILD.bazel
- cmd/kops/create_cluster.go
- pkg/apis/kops/cluster.go
- pkg/apis/kops/instancegroup.go
- upup/pkg/fi/cloudup/new_cluster.go
This is intended to be the last PR in the series.
The intent is to leave settings with trivial logic in cmd: the assumption is that external callers could just as easily implement that themselves.
> Move remaining new cluster setup to pkg

- node-authorizer/Dockerfile
> Changing base image for node authorizer.

- cmd/kops/create_cluster.go
- docs/cli/kops_create_cluster.md
- docs/networking/cilium.md
- pkg/commands/BUILD.bazel
- pkg/commands/set_cluster.go
- pkg/commands/set_cluster_test.go
- upup/pkg/fi/cloudup/BUILD.bazel
- upup/pkg/fi/cloudup/new_cluster.go
- upup/pkg/fi/cloudup/new_cluster_test.go
Needed for a new e2e cilium test
> Add ability to set various cilium flags through CLI

- tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
- tests/integration/update_cluster/complex/kubernetes.tf
- tests/integration/update_cluster/existing_iam/kubernetes.tf
- tests/integration/update_cluster/existing_sg/kubernetes.tf
- tests/integration/update_cluster/externallb/kubernetes.tf
- tests/integration/update_cluster/externalpolicies/kubernetes.tf
- tests/integration/update_cluster/ha/kubernetes.tf
- tests/integration/update_cluster/minimal-json/kubernetes.tf.json
- tests/integration/update_cluster/minimal-tf11/kubernetes.tf
- tests/integration/update_cluster/minimal/kubernetes.tf
- tests/integration/update_cluster/mixed_instances/kubernetes.tf
- tests/integration/update_cluster/mixed_instances_spot/kubernetes.tf
- tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
- tests/integration/update_cluster/privatecalico/kubernetes.tf
- tests/integration/update_cluster/privatecanal/kubernetes.tf
- tests/integration/update_cluster/privatecilium/kubernetes.tf
- tests/integration/update_cluster/privatecilium2/kubernetes.tf
- tests/integration/update_cluster/privateciliumadvanced/kubernetes.tf
- tests/integration/update_cluster/privatedns1/kubernetes.tf
- tests/integration/update_cluster/privatedns2/kubernetes.tf
- tests/integration/update_cluster/privateflannel/kubernetes.tf
- tests/integration/update_cluster/privatekopeio/kubernetes.tf
- tests/integration/update_cluster/privateweave/kubernetes.tf
- tests/integration/update_cluster/shared_subnet/kubernetes.tf
- tests/integration/update_cluster/shared_vpc/kubernetes.tf
- tests/integration/update_cluster/unmanaged/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/launchtemplate.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
In addition to TagSpecifications which allow tagging of instances and volumes, launch templates support tags of their own.
This adds the usual tags to LTs, as seen in the kubernetes.tf additions. Cloudformation [does not yet support it](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html), so only "api" and "terraform" targets are updated.
> Add tag support to AWS launch templates

- cloudmock/aws/mockec2/api.go
- cloudmock/aws/mockec2/dhcpoptions.go
- cloudmock/aws/mockec2/internetgateways.go
- cloudmock/aws/mockec2/launch_templates.go
- cloudmock/aws/mockec2/natgateway.go
- cloudmock/aws/mockec2/routetable.go
- cloudmock/aws/mockec2/securitygroups.go
- cloudmock/aws/mockec2/subnets.go
- cloudmock/aws/mockec2/tags.go
- cloudmock/aws/mockec2/volumes.go
- cloudmock/aws/mockec2/vpcs.go
- pkg/resources/aws/aws_test.go
- upup/pkg/fi/cloudup/awstasks/securitygroup_test.go
In order to add "tag-on-create" support for ec2 resources, cloudmock first needs to support recognizing and storing tags provided in `ec2.Create*` requests. This way a `DescribeTags` call will return the tags provided either by the resource's `Create` call or in a `CreateTags` call.
Additionally this sets up launch templates to use their `lt-` ID prefix so that we can get/set their tags more easily (now that #9519 is merged).
> Cloudmock cleanup - preparation for EC2 tag-on-create

- upup/pkg/fi/cloudup/awstasks/dhcp_options.go
- upup/pkg/fi/cloudup/awstasks/ebsvolume.go
- upup/pkg/fi/cloudup/awstasks/internetgateway.go
- upup/pkg/fi/cloudup/awstasks/securitygroup.go
- upup/pkg/fi/cloudup/awstasks/securitygroup_test.go
- upup/pkg/fi/cloudup/awstasks/subnet.go
- upup/pkg/fi/cloudup/awstasks/subnet_test.go
- upup/pkg/fi/cloudup/awstasks/vpc.go
- upup/pkg/fi/cloudup/awsup/aws_utils.go
- upup/pkg/fi/cloudup/awsup/aws_utils_test.go
This updates DHCP Options, EBS Volumes, InternetGateways, SecurityGroups, Subnets, and VPCs to specify tags at creation-time rather than calling ec2.CreateTags after the resource was created.
I didn't update NATGateway because it adds additional legacy tags that should be evaluated for whether or not they're needed.
I also didn't update SSHKey because it currently isn't tagged at all but it would be good for us to tag down the road.
Note each of the tasks' RenderAWS functions still calls `t.AddAWSTags()` which reconciles tags for resources that were either just created or already exist. I kept that in because:
1. Any resources that are shared (DHCP Options, Internet Gateways, Subnets, VPCs) will need their tags reconciled even though Kops never creates those resources.
2. If we ever add …
> Use EC2's tag-on-create for various resources

- tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
- tests/integration/update_cluster/complex/kubernetes.tf
- tests/integration/update_cluster/existing_iam/kubernetes.tf
- tests/integration/update_cluster/existing_sg/kubernetes.tf
- tests/integration/update_cluster/externallb/kubernetes.tf
- tests/integration/update_cluster/externalpolicies/kubernetes.tf
- tests/integration/update_cluster/ha/kubernetes.tf
- tests/integration/update_cluster/minimal/kubernetes.tf
- tests/integration/update_cluster/mixed_instances/kubernetes.tf
- tests/integration/update_cluster/mixed_instances_spot/kubernetes.tf
- tests/integration/update_cluster/private-shared-subnet/kubernetes.tf
- tests/integration/update_cluster/privatecalico/kubernetes.tf
- tests/integration/update_cluster/privatecanal/kubernetes.tf
- tests/integration/update_cluster/privatecilium/kubernetes.tf
- tests/integration/update_cluster/privatecilium2/kubernetes.tf
- tests/integration/update_cluster/privateciliumadvanced/kubernetes.tf
- tests/integration/update_cluster/privatedns1/kubernetes.tf
- tests/integration/update_cluster/privatedns2/kubernetes.tf
- tests/integration/update_cluster/privateflannel/kubernetes.tf
- tests/integration/update_cluster/privatekopeio/kubernetes.tf
- tests/integration/update_cluster/privateweave/kubernetes.tf
- tests/integration/update_cluster/shared_subnet/kubernetes.tf
- tests/integration/update_cluster/shared_vpc/kubernetes.tf
- tests/integration/update_cluster/unmanaged/kubernetes.tf
- upup/pkg/fi/cloudup/terraform/hcl2.go
- upup/pkg/fi/cloudup/terraform/hcl2_test.go
- upup/pkg/fi/cloudup/terraform/literal.go
In order to provide the HCL2 generation code with knowledge of which function to use for each file reference (`file()` vs `filebase64()` we need to store that in the Literal, so this adds a new field with that information.
Fixes #9518
> Use filebase64 for launch template userdata and Terraform 0.12

- upup/pkg/fi/cloudup/apply_cluster.go
- util/pkg/architectures/architectures.go
Force AMD64 or ARM64 only support via env var to address the issues with Kubernetes PR binaries being AMD64 only.
Fixes: #9526
> Force single arch support via env var

- docs/networking/lyft-vpc.md
- upup/pkg/fi/cloudup/apply_cluster.go
When setting the `LYFT_VPC_DOWNLOAD_URL` environment variable kops uses an empty hash in the user data.  This causes new nodes to fail to launch as the hash is unable to be verified.
Adding a new environment variable `LYFT_VPC_DOWNLOAD_HASH` allows a user to set the hash manually.
> Add lyft hash environment variable

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
followup to https://github.com/kubernetes/kops/pull/8423 and https://github.com/kubernetes/kops/pull/8555 which were later reverted due to issues in 0.5.0 that have been addressed in 0.5.1.
needed for #9500 and #8991
https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.5.1
> Update AWS IAM Authenticator to 0.5.1

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
I cherry-picked the commits from https://github.com/kubernetes/kops/pull/9508 into a new branch to see if this helps with the github action verify failure. I can't reproduce the test failure locally so we should figure out why its happening before merging.
We'll see if this one fails as well.
> Update CoreDNS to v1.7.0 - Take 2

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
This builds on PR #8423 by @rifelpet 
A 5.0.1 version of aws-iam-authenticator has not been released as of the creation of this PR, however I had the need to create internal version with the health check and decided to create the PR as a reminder to merger it in the future.
> Add healthcheck to aws-iam-authenticator

- pkg/model/components/kubelet.go
Issues with cAdvisor were fixed and merged into Kubernetes 1.19.
The fix should be available in 1.19.0-rc.1 next week. Until then, the e2e test will fail.
xRef: https://github.com/google/cadvisor/pull/2586
Reverts: #9296 
Fixes: #9301
> Re-enable disk based evictions for Kubernetes 1.19

- upup/pkg/fi/cloudup/awstasks/natgateway.go
AWS has been adding support for "tag on create" to many services. Typically this support also includes referencing tags in IAM policies involving these resources.
This means kops could use a more locked-down IAM policy that only allows creating NAT Gateways if they include cluster-specific tags, for example. Ideally we could use this for as many resource types as possible and have a much more locked down example IAM policy for kops users.
Marking WIP until I get a chance to test this locally since none of our e2e jobs create NAT gateways.
> Switch AWS NAT Gateway creation to use tags on create

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
None of the other CNI DaemonSets pay attention to taints.
Fixes #9530
> Widen the tolerations of kuberouter

- k8s/crds/kops.k8s.io_clusters.yaml
- nodeup/pkg/model/kube_apiserver.go
- nodeup/pkg/model/kube_controller_manager.go
- nodeup/pkg/model/kubelet_test.go
- nodeup/pkg/model/secrets.go
- nodeup/pkg/model/tests/golden/awsiam/tasks-kube-apiserver.yaml
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-apiserver.yaml
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-controller-manager.yaml
- nodeup/pkg/model/tests/golden/minimal/tasks-secret.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-amd64.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-apiserver-arm64.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-amd64.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-controller-manager-arm64.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/model/pki.go
Service account tokens were signed by the private key of the api-server TLS certificate. When #9354 changed the latter to being issued out of nodeup, multiple masters would fail to verify each other's service account tokens. Single masters would work for a while, but would invalidate all extant service account tokens whenever the master was replaced.
This PR stops reusing the api-server TLS private key as the service account signing key, instead using a key generated by cloudup. In order to keep clusters created by kops 1.18 and earlier working, this key is named "master" so that such clusters will continue to use the (previous) api-server TLS private key as the service account signing key.
Fixes #9531
> Use a stable key for signing service account tokens

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #9512 #9547 on release-1.18.
#9512: Update kube-router to v1.0.0
#9547: Widen the tolerations of kuberouter
> Automated cherry pick of #9512: Update kube-router to v1.0.0 #9547: Widen the tolerations of kuberouter

- pkg/model/components/etcdmanager/model.go
Cherry pick of #9553 on release-1.18.
#9553: Add missing lifecycle to etcd keypair tasks
> Automated cherry pick of #9553: Add missing lifecycle to etcd keypair tasks

- .github/workflows/main.yml
We will need to pass the job names to Tide to make them blocking, so stable names would be required.
> Use stable names for GH workflow jobs

- upup/pkg/fi/files_test.go
If the umask isn't 022, directories may not be created in mode 0755,
even if we ask them to be created as such.
umask problems seem unlikely to affect real world usage (negatively)
> File permission test: clear umask before testing

- .gitignore
- hack/verify-terraform.sh
Because we are running it in docker, I was hitting permission issues
during the cleanup step of verify-terraform.
> Don't try to delete terraform providers

- .github/workflows/main.yml
Cherry pick of #9552 on release-1.18.
#9552: Use stable names for GH workflow jobs
> Automated cherry pick of #9552: Use stable names for GH workflow jobs

- .travis.yml
- Makefile
- WORKSPACE
- docker/Dockerfile
- go.mod
- hack/make-apimachinery.sh
- images/dns-controller-builder/Dockerfile
- images/protokube-builder/Dockerfile
- vendor/modules.txt
k/k 1.19 is using go 1.14.4 so this updates kops to match. https://github.com/kubernetes/kubernetes/pull/88638
Using these PRs as a reference: https://github.com/kubernetes/kops/pull/8882 https://github.com/kubernetes/kops/pull/8886
Depends on https://github.com/kubernetes/kops/pull/9428
also reverts https://github.com/kubernetes/kops/pull/9396 since it is no longer needed (go 1.14's [default behavior changed](https://golang.org/doc/go1.14#go-command))
> Upgrade to go 1.14.4

- hack/update-goimports
Without this change, go 1.14 reports this error:
```
cannot find module providing package golang.org/x/tools/cmd/goimports: working directory is not part of a module
```
Ideally this wouldn't rely on kops being in the GOPATH but that may require updating goimports. This can happen in a followup PR
> Update goimports script for go 1.14

- pkg/model/domodel/BUILD.bazel
- pkg/model/domodel/droplets.go
- pkg/resources/digitalocean/cloud.go
- upup/pkg/fi/cloudup/do/cloud.go
Implementation of KOPS validate cluster for Digital Ocean KOPS provider.
Tested with `./kops validate cluster` and it returns the state of your KOPS cluster as expected.
> [Digital Ocean] Implement KOPS validate cluster

- docs/extra.css
- docs/networking/cilium.md
- hack/__init__.py
- hack/mkdocs_macros/__init__.py
- hack/mkdocs_macros/feature_stability_table.py
- hack/update-header.sh
- images/mkdocs/requirements.txt
- mkdocs.yml
- mkdocs_macros.py
- netlify.toml
Fixes #9151 
To get started, I also added this table to the `cilium` docs for a feature I previously added. This can provide an example for additional features to which we would like to add this table.
Example output of the table when rendered:
> Adding feature stability table to docs and including one example for encryption support in cilium

- nodeup/pkg/model/etcd.go
- pkg/wellknownusers/wellknownusers.go
Cherry pick of #9581 on release-1.18.
#9581: Use fixed UID for etcd user and restrict to legacy provider
> Automated cherry pick of #9581: Use fixed UID for etcd user and restrict to legacy provider

- cmd/kops/create_cluster.go
- cmd/kops/export_kubecfg.go
- cmd/kops/update_cluster.go
- docs/cli/kops_export_kubecfg.md
- docs/cli/kops_update_cluster.md
- docs/releases/1.19-NOTES.md
- pkg/kubeconfig/create_kubecfg.go
- pkg/kubeconfig/create_kubecfg_test.go
- pkg/kubeconfig/kubecfg_builder.go
* Don't export admin user by default.
* Allow specifying existing user when exporting context.
Fixes #8017
> Specify user on export kubecfg

- cmd/kops/create_cluster.go
- docs/cli/kops_create_cluster.md
- docs/releases/1.19-NOTES.md
- tests/integration/create_cluster/complex/expected-v1alpha2.yaml
- tests/integration/create_cluster/gce_byo_sa/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_gce/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
- tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
- tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
- upup/pkg/fi/cloudup/new_cluster.go
Creates one nodes instance group per zone, restricted to that zone. Changes the default number of nodes to the number of zones. If fewer nodes than zones, only creates one instance group per node.
Fixes #8152
> Create one nodes instance group per zone

- docs/extra.css
Fixes table issue in firefox:
Before:
After:
At first I was going to fix it simply for the new feature boxes however I think this `min-width` is to blame for a number of issues that occur cross all browsers such as on the networking page (chrome): https://kops.sigs.k8s.io/networking/
Clearly that's not displaying properly so I'm going to remove the min-width param.  We can figure out the right way to set min-width on tables in a follow up, but this should clean up a number of things for now at least.
More context see https://github.com/kubernetes/kops/pull/9585#issuecomment-660244678
> Remove min width on tables

- util/pkg/vfs/memfs.go
/kind bug
The locking in memfs is insufficient.
```
2020-07-19T21:04:48.9844960Z I0719 21:04:48.217197    3957 executor.go:103] Tasks: 0 done / 103 total; 48 can run
2020-07-19T21:04:48.9845540Z I0719 21:04:48.217788    3957 keypair.go:187] Issuing new certificate: "etcd-peers-ca-main"
2020-07-19T21:04:48.9845680Z fatal error: concurrent map read and map write
2020-07-19T21:04:48.9845750Z 
2020-07-19T21:04:48.9845850Z goroutine 6492 [running]:
2020-07-19T21:04:48.9845940Z runtime.throw(0x4b60bdc, 0x21)
2020-07-19T21:04:48.9846240Z 	/Users/runner/hostedtoolcache/go/1.14.4/x64/src/runtime/panic.go:1116 +0x72 fp=0xc0000806f8 sp=0xc0000806c8 pc=0x10366a2
2020-07-19T21:04:48.9846370Z runtime.mapaccess1_faststr(0x4325920, 0xc000c86ed0, 0xc000225590, 0x6, 0x0)
2020-07-19T21:04:48.9846590Z …
```
> Improve locking in memfs

- docs/bastion.md
- docs/cluster_spec.md
- docs/examples/kops-test-route53-subdomain.md
- docs/examples/kops-tests-private-net-bastion-host.md
- docs/getting_started/gce.md
- docs/iam_roles.md
- docs/instance_groups.md
- docs/manifests_and_customizing_via_api.md
- docs/run_in_existing_vpc.md
- docs/security_groups.md
- docs/state.md
- docs/tutorial/upgrading-kubernetes.md
- docs/tutorial/working-with-instancegroups.md
- hack/mkdocs_macros/feature_stability_table.py
Also cleaning up some creationTimestamps from yaml examples.
It'd be great if someone could double check these versions or even suggest any minimum k8s versions that I left out here.
followup to #9555
> Docs - Add the new feature table to various feature sections

- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/docker.go
With RPMs, SELinux security contexts are magically set for installed files.
In the case of the ones Kops extracts, those security contexts have to be set some other way. Easiest way is to do it during service start.
Note that, at the moment, SELinux support in Kops is limited to worker nodes.
> Restore default SELinux security contexts for container runtime binaries

- upup/pkg/fi/cloudup/alitasks/launchconfiguration.go
- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
- upup/pkg/fi/cloudup/dotasks/droplet.go
- upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
The change to explicit dependencies lost the dependencies
that were previously found by reflection.
/kind bug
Fixes #9602
> Revert move to explicit dependencies

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
> Prefer nodes with "master" role for Calico Typha pods

- OWNERS
Cherry pick of #9590 on release-1.18.
#9590: Promote Ciprian & John to approvers
> Automated cherry pick of #9590: Promote Ciprian & John to approvers

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #9609 on release-1.18.
#9609: Prefer nodes with "master" role for Calico Typha pods
> Automated cherry pick of #9609: Prefer nodes with "master" role for Calico Typha pods

- nodeup/pkg/model/docker.go
Popular Docker version, best to avoid support questions for it.
> Add Ubuntu 20.04 support for Docker 18.06.3

- nodeup/pkg/model/docker.go
Cherry pick of #9616 on release-1.18.
#9616: Add Ubuntu 20.04 support for Docker 18.06.3
> Automated cherry pick of #9616: Add Ubuntu 20.04 support for Docker 18.06.3

- pkg/apis/kops/v1alpha2/defaults.go
- pkg/model/openstackmodel/firewall.go
- pkg/model/openstackmodel/servergroup.go
- pkg/model/openstackmodel/servergroup_test.go
- upup/pkg/fi/cloudup/openstack/cloud.go
- upup/pkg/fi/cloudup/openstack/floatingip.go
- upup/pkg/fi/cloudup/openstacktasks/floatingip.go
- upup/pkg/fi/cloudup/openstacktasks/instance.go
The refactoring done lately have created cyclic dependencies in cloudup tasks when provisioning clusters that use floating or fixed ips for accessing the master API.
This PR breaks this cycle by provisioning floating IPs before the instances.
Using fixed IPs for the API is probably not possible to fix since they are created together with the instance, so one will always have the bootstrapscript -> instance -> bootstrapscript cycle. I think that should be removed in a later PR.
/cc @zetaab
> Openstack fixes

- docs/development/adding_a_feature.md
- docs/operations/cluster_template.md
Fix jinja render double curly braces error.
```
Traceback (most recent call last):
File "/opt/buildhome/python3.7/lib/python3.7/site-packages/macros/plugin.py", line 261, in render
md_template = self.env.from_string(markdown)
File "/opt/buildhome/python3.7/lib/python3.7/site-packages/jinja2/environment.py", line 941, in from_string
return cls.from_code(self, self.compile(source), globals, None)
File "/opt/buildhome/python3.7/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
self.handle_exception(source=source_hint)
File "/opt/buildhome/python3.7/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File "/opt/buildhome/python3.7/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in …
```
> fix(docs): render double curly braces

- upup/pkg/fi/cloudup/openstack/dns.go
- upup/pkg/fi/cloudup/openstack/instance.go
- upup/pkg/fi/cloudup/openstack/keypair.go
- upup/pkg/fi/cloudup/openstack/network.go
- upup/pkg/fi/cloudup/openstack/port.go
- upup/pkg/fi/cloudup/openstack/router.go
- upup/pkg/fi/cloudup/openstack/security_group.go
- upup/pkg/fi/cloudup/openstack/server_group.go
- upup/pkg/fi/cloudup/openstack/subnet.go
- upup/pkg/fi/cloudup/openstack/volume.go
This is minor cleanup before refactoring the openstackCloud functions to make them more mockable, similar to AWSCloud.
This should effectively be a no-op
https://github.com/kubernetes/kops/blob/0bf54419abdc0aae39ca6fcf4402642e1c28041d/upup/pkg/fi/cloudup/openstack/cloud.go#L485-L503
> Use public client accessors within openstackCloud functions

- pkg/instancegroups/rollingupdate_test.go
- upup/pkg/fi/cloudup/awsup/machine_types.go
Go 1.15 introduces some new restrictions:
https://tip.golang.org/doc/go1.15#vet
```
pkg/instancegroups/rollingupdate_test.go:139:16: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL	k8s.io/kops/pkg/instancegroups [build failed]
upup/pkg/fi/cloudup/awsup/machine_types.go:61:30: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL	k8s.io/kops/upup/pkg/fi/cloudup/awsup [build failed]
```
> Fix int to string conversions

- upup/pkg/fi/cloudup/awstasks/render_test.go
> add os.RemoveAll err verification

- .travis.yml
- nodeup/pkg/model/containerd_test.go
- nodeup/pkg/model/docker_test.go
- nodeup/pkg/model/kubelet_test.go
The ARM64 job seems to be faster with latest ubuntu and more stable with latest Ubuntu. Time to try to make it blocking.
> Make ARM64 job blocking with TravisCI

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Upgrading [the _k8s-ec2-srcdst_ controller](https://github.com/ottoyiu/k8s-ec2-srcdst/) to [this latest version](https://github.com/ottoyiu/k8s-ec2-srcdst/releases/tag/v0.3.0) allows it to work correctly with the objects containing the new "metadata.managedFields" field [introduced in Kubernetes version 1.18.0](https://kubernetes.io/blog/2020/04/01/kubernetes-1.18-feature-server-side-apply-beta-2/#how-does-it-work-what-s-managedfields), per ottoyiu/k8s-ec2-srcdst#17.
The previous container image versions used a version of the _client-go_ library that was too old to consume these fields
correctly, causing the controller to fail repeatedly when trying to read _Node_ objects retrieved from the Kubernetes API server.
> Calico: Upgrade the "k8s-ec2-srcdst" controller to version v0.3.0

- pkg/instancegroups/rollingupdate_test.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/awsup/machine_types.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #9647 on release-1.18.
#9647: Calico: upgrade "k8s-ec2-srcdst" to version v0.3.0
> Automated cherry pick of #9647: Calico: upgrade "k8s-ec2-srcdst" to version v0.3.0

- pkg/resources/ops/delete.go
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/iaminstanceprofile.go
- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
- upup/pkg/fi/cloudup/awstasks/natgateway.go
- upup/pkg/fi/cloudup/awstasks/route.go
- upup/pkg/fi/context.go
- upup/pkg/fi/executor.go
When a cluster is created, there are warnings such as:
```
W0727 09:19:16.521016    5204 executor.go:128] error running task "AutoscalingGroup/nodes-ap-northeast-2c.e2e-8e9eb293c0-ff1eb.test-cncf-aws.k8s.io" (9m58s remaining to succeed): error creating AutoscalingGroup: ValidationError: You must use a valid fully-formed launch template. Value (nodes.e2e-8e9eb293c0-ff1eb.test-cncf-aws.k8s.io) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
status code: 400, request id: 56bfbee6-2dad-4c52-902e-5a8ddf9f5734
```
This happens because of AWS EC2 eventual consistency issues:
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency
> Cleanup AWS EC2 eventual consistency warnings

- docs/releases/1.18-NOTES.md
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://github.com/projectcalico/calico/releases/tag/v3.15.1
https://github.com/projectcalico/confd/pull/337
```
Fix critical issue with service IP advertisement breaking host service connectivity
```
> Update Calico to v3.15.1 for k8s 1.16+

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #9656 on release-1.18.
#9656: Update Calico to v3.15.1 for k8s 1.16+
> Automated cherry pick of #9656: Update Calico to v3.15.1 for k8s 1.16+

- Makefile
Included BAZEL_OPTIONS pre-fixed for bazel build.
Initial changes to https://github.com/kubernetes/kops/pull/7758 added BAZEL_CONFIG but that doesn't work for few arguments like below.
`--host_jvm_args=-Djavax.net.ssl.trustStore=/usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts  --host_jvm_args=-Djavax.net.ssl.trustStorePassword=changeit --server_javabase=/usr/lib/jvm/java-11-openjdk-amd64 `
With this change, you can continue to add these JVM args as build options while continue to use other bazel configuration for build and test.
> Use BAZEL_OPTIONS  for bazel build

- .shipbot.yaml
- Makefile
- docs/development/release.md
- docs/release-process.md
Promoting the staging build, for eventual "lights off" / "hands off" releases.
> Document new release process for kops 1.19 and on

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #9663 on release-1.18.
#9663: Prefer nodes with "master" role for Canal Typha pods
> Automated cherry pick of #9663: Prefer nodes with "master" role for Canal Typha pods

- pkg/assets/builder.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/networking.go
- upup/pkg/fi/cloudup/networking_test.go
Most notable changes are:
* extract the LyftVPC assets finder to separate function (similar to the CNI one)
* add test for the new function and update previous ones
* use SHA from repo for the CNI asset finder (similar to the kubelet one)
https://github.com/kubernetes/kops/blob/781279e268847579b47a87600380675317233b58/pkg/assets/builder.go#L249
Note: All file assets can be remapped using `Spec.Assets.FileRepository`, so maybe we should remove some of these env vars like `CNI_VERSION_URL` and `LYFT_VPC_DOWNLOAD_URL `.
> Refactor networking assets finder

- upup/pkg/fi/cloudup/openstack/BUILD.bazel
- upup/pkg/fi/cloudup/openstack/availability_zone.go
- upup/pkg/fi/cloudup/openstack/cloud.go
- upup/pkg/fi/cloudup/openstack/dns.go
- upup/pkg/fi/cloudup/openstack/floatingip.go
- upup/pkg/fi/cloudup/openstack/image.go
- upup/pkg/fi/cloudup/openstack/instance.go
- upup/pkg/fi/cloudup/openstack/keypair.go
- upup/pkg/fi/cloudup/openstack/loadbalancer.go
- upup/pkg/fi/cloudup/openstack/mock_cloud.go
- upup/pkg/fi/cloudup/openstack/network.go
- upup/pkg/fi/cloudup/openstack/port.go
- upup/pkg/fi/cloudup/openstack/router.go
- upup/pkg/fi/cloudup/openstack/security_group.go
- upup/pkg/fi/cloudup/openstack/server_group.go
- upup/pkg/fi/cloudup/openstack/status.go
- upup/pkg/fi/cloudup/openstack/subnet.go
- upup/pkg/fi/cloudup/openstack/utils.go
- upup/pkg/fi/cloudup/openstack/volume.go
This is the first step towards an Openstack implementation of cloudmock, allowing us to have Openstack integration tests.
This separates the majority of the logic from the live implementation of the OpenstackCloud interface, allowing us to reuse the logic in openstack.MockCloud. 
This is the same pattern followed in the AWS package. example:
https://github.com/kubernetes/kops/blob/7f7b5b1782f7b0ac8aabd6581ea8d2b95bf82d1d/upup/pkg/fi/cloudup/awsup/aws_cloud.go#L1038-L1059
https://github.com/kubernetes/kops/blob/7f7b5b1782f7b0ac8aabd6581ea8d2b95bf82d1d/upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go#L161-L163
> Refactor openstackCloud to be mockable, add a MockCloud

- upup/pkg/fi/cloudup/gcetasks/address.go
- upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
Spruce up the find logic to avoid detecting changes that aren't there.
> GCE: Fix spurious comparison failures on adddress & InstanceTemplate

- util/pkg/vfs/memfs.go
Cherry pick of #9597 on release-1.18.
#9597: Improve locking in memfs
> Automated cherry pick of #9597: Improve locking in memfs

- Makefile
- go.mod
- go.sum
- hack/verify-gomod.sh
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/github.com/aws/aws-sdk-go/service/cloudformation/api.go
- vendor/github.com/aws/aws-sdk-go/service/cloudformation/waiters.go
- vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
- vendor/github.com/aws/aws-sdk-go/service/route53/api.go
- vendor/github.com/aws/aws-sdk-go/service/sts/api.go
- vendor/modules.txt
This update is the latest patch release in the 1.30.x series and adds the Route53 endpoints for China (which was a popular request in the past).
> Update aws-sdk-go to 1.30.29

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Now that https://github.com/kubernetes/kops/pull/9674 was merged, there is no need for CPA to run on control-plane nodes.
Basically, this reverts parts of https://github.com/kubernetes/kops/pull/9418 and https://github.com/kubernetes/kops/pull/9431.
> Move cluster-proportional-autoscaler to worker nodes

- upup/pkg/fi/cloudup/apply_cluster.go
Github was returning 500s on the channel request earlier today and I ran into nil pointers around this part of the code.
> When channel is unavailable, don't try to validate things from it

- upup/pkg/fi/cloudup/apply_cluster.go
Cherry pick of #9559 on release-1.18.
#9559: When channel is unavailable, don't try to validate things
> Automated cherry pick of #9559: When channel is unavailable, don't try to validate things

- nodeup/pkg/model/secrets.go
- pkg/model/openstackmodel/network.go
- pkg/model/openstackmodel/servergroup.go
- upup/pkg/fi/cloudup/openstack/cloud.go
- util/pkg/vfs/context.go
As discussed in #9554 
This will break the task dependency cycle. It is a bit hackish with directly using protokube-code. That part should be moved to something shared, but perhaps best done in a followup PR?
> Determine fixedip during nodeup directly

- upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
- upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
- upup/pkg/fi/cloudup/spotinsttasks/ocean.go
The HCL2 library doesn't handle embedded structs like json marshalling does, so this inlines the fields to match how terraform represents the resources.
There was only one type that was embedded in two places, so I just copied those fields.
fixes #9679
> Remove embedded structs from spotinst terraform types

- upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
- upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
- upup/pkg/fi/cloudup/spotinsttasks/ocean.go
Cherry pick of #9682 on release-1.18.
#9682: Remove embedded structs from spotinst terraform types
> Automated cherry pick of #9682: Remove embedded structs from spotinst terraform types

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
#9462 missed upgrading k8s-dns-dnsmasq-nanny in the 1.12 manifest to match KubeDNS. It was thus missed in the #9485 backport. It has since been fixed in master branch.
> Upgrade k8s-dns-dnsmasq-nanny to match KubeDNS

- pkg/resources/openstack/dns.go
If `zs` is an empty slice, `z := zs[0]` will panic. This will return an error instead.
> Openstack - Don't panic if the dns zone is not found

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This PR upgrade the Spot Cluster Controller to version 1.0.63.
> Spotinst: Upgrade the Spot Cluster Controller to version 1.0.63

- pkg/model/spotinstmodel/instance_group.go
This PR changes the way the default Instance Group for Spot Ocean is selected to allow users to create new clusters with multiple Instance Groups (#9471) without having to generate their manifests first to select the default by adding the metadata label (`spotinst.io/ocean-default-launchspec`).
> Spotinst: Selecting a default Instance Group in Spot Ocean should be optional

- hack/upload
Using s3cmd to upload KOPS binaries to DO spaces, helps in development when working on nodeup and other binaries to use custom images from DO Spaces.
> [Digital Ocean] Upload binaries to DO Spaces

- nodeup/pkg/bootstrap/install.go
- nodeup/pkg/model/cloudconfig.go
- nodeup/pkg/model/protokube.go
- pkg/model/bootstrapscript.go
- util/pkg/env/standard.go
- util/pkg/vfs/swiftfs.go
Application credentials allows you to export a purpose-specific set of
credentials for a user instead of exposing user login credentials.
Especially useful when using LDAP or similar for Openstack users.
Also lets you rotate credentials more easily since multiple application
credentials can be provisioned per user.
Depends on https://github.com/kopeio/etcd-manager/pull/336 as well.
> Adds support for using OS application credentials

- docs/authentication.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/authentication.aws-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
This is a small configuration change to allow configuring a custom list of backend modes for aws-iam-authenticator (https://github.com/kubernetes/kops/issues/9468) The available options are MountedFile, EKSConfigMap, or CRD. Any number of these can be selected in order of preference in a comma separated list. The default is still MountedFile.
> Allow configurable backend modes for aws-iam-authenticator

- pkg/model/openstackmodel/firewall.go
Opening ports for the cilium health check and vxlan.
Since the cni rules were the only ones I had in my SGs not using SG->SG rules, I fixed that part as well. I left the rules I am not using as-is.
> Add support for cilium on openstack

- .github/workflows/main.yml
- .travis.yml
- WORKSPACE
At the moment GH jobs are broken because they cannot find the old Go rc1 anymore... 🤷 
Follow-up of https://github.com/kubernetes/kops/pull/9641.
> Update Go to v1.15rc2

- WORKSPACE
Fixing:
```
WARNING: Download from https://dl.google.com/go/go1.15rc2.darwin-amd64.tar.gz failed:
class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException
Checksum was b07775d30e023c1570b1ba74892fc792834436c790fbb0dbb19ebaae9c155105
but wanted c3b33843b6318c80a3d6e4007986aeeea7950f469a7bd6eed549b0633ba9e456
```
/cc @rifelpet
> Fix bazel darwin hash for Go 15rc2

- nodeup/pkg/model/kubelet.go
Kubelet defaults the authorization mode to `Webhook` when the `--config` flag is provided, but it defaults to the insecure `AlwaysAllow` mode when the `--config` flag is not provided.
Since kops uses (the deprecated) flags instead of a config file, this change causes us to get the more secure default.
> Default kubelet authorization-mode to Webhook for k8s 1.19+

- SECURITY_CONTACTS
Update SECURITY_CONTACTS to the current set of approvers.
Before merging, each of the following people should comment that they agree to abide by the [Embargo Policy](https://git.k8s.io/security/private-distributors-list.md#embargo-policy):
I agree to abide by the Embargo Policy.
>  Update SECURITY_CONTACTS

- .travis.yml
Now that we have GitHub actions I don't think we need travis anymore
/hold for input from others
> Remove amd64 TravisCI jobs

- docs/releases/1.19-NOTES.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/BUILD.bazel
- pkg/model/components/openstack.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/openstack.addons.k8s.io/k8s-1.13.yaml.template
- upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/populate_cluster_spec.go
- upup/pkg/fi/cloudup/template_functions.go
This will install the cinder plugin allowing dynamic provisioning of volumes.
Since kops already depend on cinder and since most people need this anyway, I add this unconditionally.
If there are needs for disabling this, I can always add it. But we add storageclass etc unconditionally for AWS and GCE too.
> Add cinder plugin

- .github/workflows/main.yml
- Makefile
- protokube/pkg/protokube/etcd_manifest.go
- protokube/tests/integration/build_etcd_manifest/integration_test.go
- tests/integration/conversion/BUILD.bazel
- tests/integration/conversion/integration_test.go
- tests/integration/conversion/minimal/legacy-v1alpha2.yaml
- upup/pkg/fi/cloudup/awstasks/render_test.go
- upup/pkg/fi/files_test.go
The _kops_ binary for Windows is not tested anywhere.
> Add windows job to GH workflows

- .github/workflows/main.yml
- .travis.yml
These were failing, apparently the RC is no longer available once the stable release lands.
We can bump bazel rules_go once it is released.
> Upgrade CI jobs to go 1.15.0

- WORKSPACE
> Update Go to v1.15.0 for Bazel

- go.sum
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- protokube/pkg/gossip/mesh/mesh.pb.go
PR Summary:
- Adds missing cli options for kube-controller-manager and kube-scheduler
- Fixes https://github.com/kubernetes/kops/issues/9695
> Add missing cli options for kube-controller-manager and kube-scheduler

- hack/verify-terraform.sh
https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-13/
This also now tests version 3.X of the AWS Provider which has a [breaking change related to launch templates](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_launch_template) but my local testing showed that our use of `aws_launch_template` is not impacted.
> Upgrade to Terraform 0.13.0

- mkdocs.yml
Changes:
* 1.18-beta => 1.18
* 1.1 => 1.10 (converted to string now)
* legacy-changes.md => Legacy
Preview: https://deploy-preview-9743--kubernetes-kops.netlify.app/releases/1.18-notes/
> Update link names for releases

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Enable portmap plugin in the kube-router cni config to support hostPort.  
Similar to #7295 (flannel), #4063 (canal), and #3206 (calico).
> Support for using hostPort when using kube-router

- upup/pkg/fi/cloudup/awsup/machine_types.go
Cherry pick of #9630 on release-1.17.
#9630: Fix int to string conversions
> Automated cherry pick of #9630: Fix int to string conversions

- pkg/nodeidentity/openstack/identify.go
Cherry pick of #8862 to be used in 1.17
> fixes(openstack): auth problem for kops-controller

- nodeup/pkg/model/kubelet.go
As discussed in Office Hours.
Fixes #7200
> Default kubelet authenticationTokenWebhook to true for k8s 1.19+

- cmd/kops/create_cluster.go
- cmd/kops/export_kubecfg.go
- cmd/kops/update_cluster.go
- docs/cli/kops_export_kubecfg.md
- docs/cli/kops_update_cluster.md
- docs/releases/1.19-NOTES.md
- pkg/kubeconfig/BUILD.bazel
- pkg/kubeconfig/create_kubecfg.go
- pkg/kubeconfig/create_kubecfg_test.go
- pkg/model/pki.go
> Reduce the lifetime of exported kubecfg credentials

- hack/update-expected.sh
This ensures update-expected still works even when KOPS_FEATURE_FLAGS
is set.
> Clear KOPS_FEATURE_FLAGS in update-expected.sh

- pkg/model/bootstrapscript.go
> Only add OS variables if they are needed

- nodeup/pkg/model/containerd.go
- pkg/model/components/containerd.go
https://github.com/containerd/containerd/releases/tag/v1.4.0
> Add support for containerd v1.4.0

- hooks/nvidia-bootstrap/image/Dockerfile
This PR is clean version of #8681  as requested 
Major Changes No 1 : debian package manager tweaks
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages . 
By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.
This results in smaller downloads and installation of packages .
Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .
Major Changes No 2 : added packages apt-utils ca-certificates
Because Github CI build is 
1.  Slow and in log it is showing because "apt-utils" not installed 
2. to avoid CI build to exits with error without having certificate
> Enhancement in Ubuntu or debian apt-get and CI issue fix

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.9.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
https://github.com/weaveworks/weave/releases/tag/v2.7.0
> Update Weave Net to v2.7.0

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.7.0
> Upgrade AWS VPC CNI to 1.7.0

- pkg/apis/kops/validation/validation.go
- tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/privatecalico/data/aws_launch_template_master-us-test-1a.masters.privatecalico.example.com_user_data
- tests/integration/update_cluster/privatecalico/data/aws_launch_template_nodes.privatecalico.example.com_user_data
- tests/integration/update_cluster/privatecalico/in-v1alpha2.yaml
- upup/pkg/fi/cloudup/BUILD.bazel
- upup/pkg/fi/cloudup/new_cluster.go
- upup/pkg/fi/cloudup/new_cluster_test.go
> Update validation for Calico to assume etcd3 as default

- channels/stable
11 days have passed since these version were pushed to alpha ([ref](https://github.com/kubernetes/kops/commit/9f768c127511b30c0094d2f2a7df3fd7da688ae7#diff-37c59376fa8938637370b21d9540af69)).
We should be good bumping to stable at this point.
> Bump stable versions from alpha

- Makefile
- hack/verify-bindata.sh
- hack/verify-generate.sh
- hack/verify-gomod.sh
- hack/verify-shellcheck.sh
- pkg/model/components/kubeapiserver/model.go
- pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.6.yaml.template
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
- version.go
/cc @justinsb @rifelpet @johngmyers @geojaz @kashifsaadat @mikesplain @rdrgmnzs @zetaab 
/hold for approvals
> Release 1.19.0-alpha.3

- nodeup/pkg/model/protokube.go
- nodeup/pkg/model/tests/protokube/containerd/tasks-protokube.yaml
- nodeup/pkg/model/tests/protokube/docker/tasks-protokube.yaml
Protokube is always side-loaded. It is never pushed to a Docker registry, so there is no reason to pull it.
```yaml
protokubeImage:
hash: 8f09e5b87f6df65e1579c56775f7c9c6ddac315579f367129c0ed297c46840f5
name: protokube:1.18.0
sources:
- https://artifacts.k8s.io/binaries/kops/1.18.0/images/protokube.tar.gz
- https://github.com/kubernetes/kops/releases/download/v1.18.0/images-protokube.tar.gz
- https://kubeupv2.s3.amazonaws.com/kops/1.18.0/images/protokube.tar.gz
```
> Stop trying to pull the Protokube image

- docs/iam_roles.md
This complements #9773 .
Refs #7286 .
/cc @rifelpet
> Adding docs on AWS Permissions Boundaries support

- upup/pkg/fi/cloudup/new_cluster.go
This was later failing api validation with:
`spec.subnets[1].region: Required value: region must be specified for GCE subnets`
So now we copy the region value from the equivalent non-utility subnet when creating utility subnets.
While the value is only set and referenced in GCE, it should be safe to copy the zero-value for other cloud providers.
ref: https://github.com/kubernetes/kops/issues/8626#issuecomment-680242593
> Fix GCE cluster creation with private topology

- nodeup/pkg/model/context.go
- nodeup/pkg/model/secrets.go
- nodeup/pkg/model/tests/golden/minimal/tasks-secret.yaml
- upup/pkg/fi/nodeup/nodetasks/issue_cert.go
This means that our https endpoint will serve the ca.crt as well.
> Support writing a full certificate chain

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #9816 on release-1.18.
#9816: Update Calico to v3.15.2 for k8s 1.16+
> Automated cherry pick of #9816: Update Calico to v3.15.2 for k8s 1.16+

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #9689 #9818 on release-1.18.
#9689: Support for using hostPort when using kube-router
#9818: Update kube-router to v1.0.1
> Automated cherry pick of #9689: Support for using hostPort when using kube-router #9818: Update kube-router to v1.0.1

- cmd/kops/BUILD.bazel
- cmd/kops/create_cluster.go
- pkg/apis/kops/validation/validation.go
Backporting just the fix from #9803, without updating tests.
/cc @olemarkus
> Backport #9803: Update validation for Calico to assume etcd3 as default

- cmd/kops/export_kubecfg.go
- cmd/kops/update_cluster.go
- docs/cli/kops_export_kubecfg.md
- docs/cli/kops_update_cluster.md
- docs/cluster_spec.md
- pkg/kubeconfig/create_kubecfg.go
- pkg/kubeconfig/create_kubecfg_test.go
Kops creates an "api.internal.$clustername" dns A record that points to the master IP(s)
This adds a flag that will use that name and force the CA cert to be included.
This is a workaround for client certificate authentication not working on API ELBs with ACM certificates.
The ELB has a TLS listener rather than TCP, so the client certificate is not passed through to the apiserver.
Using --internal will bypass the API ELB so that the client certificate will be passed directly to the apiserver.
This also requires that the masters' security groups allow 443 access from the client which this does not handle automatically. I suppose if sslCertificateId is set, kops could automatically open 443 on the masters to the same sources that the ELB's 443 allows but I could see that being frowned upon …
> Add --internal flag for export kubecfg that targets the internal dns name

- WORKSPACE
- node-authorizer/images/BUILD.bazel
Given the latest debian-hyperkube-base is based on Debian Stretch which is no longer receiving security updates as of 07/06/2020 and that k/k has completely stopped using it (https://github.com/kubernetes/kubernetes/pull/88676) we should migrate off it as well.
P.S. We may want to migrate node-authorizer to be a scratch container as well but that will require some more digging into.
> Move from debian-hyperkube-base to debian-base for node-authorizer

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.16.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
This PR removes the unnecessary nodeAffinity from the Typha deployment in calico and canal manifests.
**Some background / history on how we got to this point:**
1. `nodeSelector: {kubernetes.io/role: master}` is added to Canal in https://github.com/kubernetes/kops/pull/7917/
1. This `nodeSelector` change is "copied" into the Calico manifest in #8104 .
1. @seh  points out that the node selector "makes it much harder to run more than three Typha replicas. It would be better to have node affinity that expresses a preference, but not a requirement for Typha pods to run on the masters." https://github.com/kubernetes/kops/pull/8104#discussion_r458153054, and raises https://github.com/kubernetes/kops/issues/9608 to track.
1. Nodeselector is converted to an Affinity as part of …
> remove nodeAffinity from typha

- Makefile
- tools/get_workspace_status.sh
This avoids duplication of logic / different logic - and the logic in
the Makefile was indeed different, which was causing us to overwrite
the staging alpha images.
> Use the get_workspace_status script to get the versions

- cloudbuild.yaml
This should allow us to build our tagged builds as _non_ CI builds.
> cloudbuild: allow CI env var to be specified

- upup/pkg/fi/changes.go
- upup/pkg/fi/resources.go
This is needed because otherwise if we try to diff a computed field,
we can't read the value.
> TaskDependentResource: support preview when the task isn't ready

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
closes https://github.com/kubernetes/kops/issues/2045
> add support for cors-allowed-origins

- cmd/kops/BUILD.bazel
- cmd/kops/delete_cluster.go
- cmd/kops/export_kubecfg.go
- cmd/kops/root.go
- cmd/kops/update_cluster.go
- cmd/kops/util/factory.go
- docs/cli/kops_export_kubecfg.md
- go.mod
- hack/.packages
- pkg/commands/BUILD.bazel
- pkg/commands/commandutils/BUILD.bazel
- pkg/commands/commandutils/exit.go
- pkg/commands/helpers.go
- pkg/commands/helpers/BUILD.bazel
- pkg/commands/helpers/kubectl_auth.go
- pkg/kubeconfig/BUILD.bazel
- pkg/kubeconfig/create_kubecfg.go
- pkg/kubeconfig/create_kubecfg_test.go
- pkg/kubeconfig/kubecfg_builder.go
- vendor/modules.txt
We create a simple exec plugin command which can create and renew
short-lived admin credentials on the fly, essentially leveraging the
security of the underlying cloud credentials.
> Support authentication helper for kubectl

- util/pkg/vfs/swiftfs.go
If we were using credentials from env vars, we would not do
reauthentication with Swift.
> Always use OpenStack Swift reauthentication

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This PR upgrade the Spot Cluster Controller to version 1.0.64.
> Spotinst: Upgrade the Spot Cluster Controller to version 1.0.64

- util/pkg/vfs/swiftfs.go
Cherry pick of #9836 on release-1.18.
#9836: Always use OpenStack Swift reauthentication
> Automated cherry pick of #9836: Always use OpenStack Swift reauthentication

- hack/verify-shellcheck.sh
Signed-off-by: Ma Xinjian <maxj.fnst@cn.fujitsu.com>
> Keep SHELLCHECK_IMAGE vesion sync with SHELLCHECK_VERSION defined before

- cmd/kops/delete_instance.go
- pkg/cloudinstances/BUILD.bazel
- pkg/cloudinstances/cloud_instance.go
- pkg/cloudinstances/cloud_instance_group.go
- pkg/instancegroups/instancegroups.go
- pkg/instancegroups/rollingupdate.go
- pkg/instancegroups/rollingupdate_test.go
- pkg/resources/digitalocean/cloud.go
- pkg/resources/spotinst/resources.go
- pkg/validation/validate_cluster.go
- pkg/validation/validate_cluster_test.go
- upup/pkg/fi/cloud.go
- upup/pkg/fi/cloudup/aliup/ali_cloud.go
- upup/pkg/fi/cloudup/aliup/status.go
- upup/pkg/fi/cloudup/awsup/BUILD.bazel
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
- upup/pkg/fi/cloudup/gce/instancegroups.go
- upup/pkg/fi/cloudup/openstack/instance.go
- upup/pkg/fi/cloudup/openstack/mock_cloud.go
- upup/pkg/fi/cloudup/openstack/server_group.go
@johngmyers what do you think about an approach like this?
> Cloudinstances refactor

- upup/pkg/fi/cloudup/openstack/cloud.go
- upup/pkg/fi/cloudup/openstack/server_group.go
This will populate the data later displayed by `kops get instances` once #9762 has merged.
> Populate cloudinstances data on openstack

- hack/verify-staticcheck.sh
IGNORE is an empty array, it throws error when make verify-staticcheck
$ make verify-staticcheck
hack/verify-staticcheck.sh
hack/verify-staticcheck.sh: line 50: IGNORE[*]: unbound variable
make: *** [verify-staticcheck] Error 1
Signed-off-by: Ma Xinjian <maxj.fnst@cn.fujitsu.com>
> fix "unbound variable" issue

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://docs.projectcalico.org/archive/v3.16/release-notes/
> Update Calico to v3.16.0 for k8s 1.16+

- channels/alpha
https://github.com/kubernetes/kubernetes/releases/tag/v1.16.15
> Update alpha channel k8s 1.16 to 1.16.15 and Ubuntu image to latest available

- k8s/crds/kops.k8s.io_clusters.yaml
- k8s/crds/kops.k8s.io_instancegroups.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
/kind bug
Allow Docker and Kubelet to set the **Cgroup Driver** to `systemd` as recommended in the official Kubernetes docs.
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers
When attempting to set the Docker container runtime cgroup driver (native.cgroupdriver) to `systemd` in the Kops YAML manifest.
```
...
docker:
execOpt:
- native.cgroupdriver=systemd
...
```
The following **Kubelet** error is reported during the Kops Kubernetes bootstrapping process.
```
Sep 07 10:48:58 ip-172-20-62-0 kubelet[8384]: F0907 10:48:58.919376    8384 server.go:274] 
failed to run Kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from …
```
> Add kubelet cgroup driver property

- k8s/crds/kops.k8s.io_clusters.yaml
- k8s/crds/kops.k8s.io_instancegroups.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
Cherry pick of #9879 on release-1.18.
#9879: Add kubelet cgroup driver property
> Automated cherry pick of #9879: Add kubelet cgroup driver property

- hack/verify-terraform.sh
Otherwise we get a warning:
"find: warning: you have specified the global option -maxdepth after the argument -type, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments."
> verify-terraform: rearrange arguments to find

- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
#9793 missed the config flags for LaunchConfiguration with Terraform and CloudFormation.
This will be useful in kops 1.18.1.
> Use root volume encryption flag for LaunchConfiguration with TF and CF

- k8s/crds/kops.k8s.io_instancegroups.yaml
- pkg/apis/kops/instancegroup.go
- pkg/apis/kops/v1alpha2/instancegroup.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/awsmodel/autoscalinggroup.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
Cherry pick of #9793 #9872 on release-1.18.
#9793: Add flag for root volume encryption
#9872: Use root volume encryption flag for LaunchConfiguration
> Automated cherry pick of #9793: Add flag for root volume encryption #9872: Use root volume encryption flag for LaunchConfiguration

- nodeup/pkg/model/kube_apiserver.go
- upup/pkg/fi/cloudup/apply_cluster.go
When encryptionConfig is enabled, but the secret is missing, there is no visible errors anywhere. kube-apiserver just goes into a crashloop without any complains. This PR adds warnings both on the client side and through nodeup.
> Errors when encryptionConfig is enabled, but no encryptionconfig secret

- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
Brings AWS direct render in line with Terraform and Cloudformation.
Fixes: #9890
> Add missing spot support to launch template direct render

- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/kubedns.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
In this PR the `NodeLocalDNSConfig` is updated to hold `MemoryRequest` and `CPURequest` (as it is done in the `KubeDNSConfig`).
We end up with the following new cluster_spec (as updated in the documentation):
```
nodeLocalDNS:
enabled: true
memoryRequest: 5Mi
cpuRequest: 25m
```
`5Mi` and `25m` were chosen as they are the current defaults.
The reasoning behind this is that we would like to avoid patching the daemonset once kops has it deployed and be able to configure everything in the cluster spec config.
I am by no means an expert neither in go nor in contributing to the kops repo, so if I have forgotten anything please feel free to fire away any comments, additions, requirements or anything else that I may have overseen.
> Nodelocalcache configure resources

- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
Cherry pick of #9897 on release-1.18.
#9897: Add missing spot support to launch template direct render
> Automated cherry pick of #9897: Add missing spot support to launch template direct render

- cmd/kops-controller/main.go
- cmd/kops-controller/pkg/config/options.go
- pkg/featureflag/featureflag.go
- pkg/nodeidentity/aws/BUILD.bazel
- pkg/nodeidentity/aws/identify.go
- pkg/nodeidentity/interfaces.go
- upup/pkg/fi/cloudup/template_functions.go
Allow caching of Nodeidentity Info in kops-controller for AWS to reduce the number of DescribeInstances API calls.
We've recently been hitting the AWS API rate limit for DescribeInstances very often. Upon further investigation we've discovered that this was due to kops-controller making calls to AWS in order to pull instances info. Given that the information being looked up should never change I implemented caching to help alleviate this issue.
This is behind a feature flag for the time being.
> Allow caching of Nodeidentity Info in kops-controller for AWS.

- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/kubedns.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
Cherry pick of #9376 #9901 on release-1.18.
#9376: NodeLocalDNS config population: small tweaks
#9901: Update NodeLocalDNSConfig with Mem/CPU requests
> Automated cherry pick of #9376: NodeLocalDNS config population: small tweaks #9901: Update NodeLocalDNSConfig with Mem/CPU requests

- util/pkg/vfs/s3context.go
AWS detection assumes that `/sys/devices/virtual/dmi/id/product_uuid` is readable. This is not the case inside containers like `kops-controller`. If there is an error reading the file, AWS api should be queried anyway as a fallback.
Fixes: #9856
> Detect AWS region for S3 inside containers

- pkg/model/iam.go
We experience fatal errors with this new feature (that we are not using) because some of the instance groups in our clusters include `spec.iam.profile` while others use the managed `nodes` role/profile. The `ExternalPolicies` feature is broken, and this makes it go away when not specifically asked for in the cluster configuration.
At the moment, without this patch, the `kops update cluster` operation results in -
```
F0903 17:45:44.372520   48506 task.go:59] found duplicate tasks with name "IAMRolePolicy/node-policyoverride": *awstasks.IAMRolePolicy {"ID":null,"Lifecycle":"Sync","Name":"node-policyoverride","Role":{"ID":null,"Lifecycle":"Sync","Name":"nodes.mycluster.domain.com","RolePolicyDocument":{"Name":"","Resource":{}},"ExportWithID":"nodes"},"PolicyDocument":null,"ExternalPolicies": …
```
> Only apply external policies when these are defined

- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
Should at least partially remediate #9806 by filtering the launch templates before enumerating their versions.
> Get launch template versions after filtering templates

- pkg/model/master_volumes.go
There is no real reason to do this. In some cases this may even prevent clusters from starting where there is no explicit volume type defined in cinder.
fixes #9893
> Remove constraint of setting volume type for OS

- util/pkg/vfs/s3context.go
Cherry pick of #9857 on release-1.18.
#9857: Detect AWS region for S3 inside containers
> Automated cherry pick of #9857: Detect AWS region for S3 inside containers

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
This PR is proposing a change in the nodelocalcache confimap. 
The change is removing the `force_tcp` flag from the `.` zone that handles all external DNS requests.
Using the current nodelocalcache configuration we have experienced increased latencies for our DNS requests that needs to go to our upstream DNS server (which in our case is AWS VPC's DNS servers).
Forcing all DNS communication go through TCP can lead to increased latency and slower DNS responses since a lot of upstream DNS servers are not optimized for TCP traffic.
An example is AWS's VPC DNS server that sending all the DNS traffic through TCP cause it to increase the latencies for this requests.
The kubernetes version has already changed this configmap to skip `force_tcp` flag for the . zone, so it might make sense to follow …
> Remove force_tcp flag for nodelocalcache dot zone

- pkg/apis/kops/validation/BUILD.bazel
- pkg/apis/kops/validation/instancegroup.go
- pkg/apis/kops/validation/instancegroup_test.go
This fixes a couple of issues with labels reported by users:
* A mixup between cloudLabels (which allows many /) and nodeLabels (which don't) ended up in issues with kops-controller who couldn't set labels with a bad value
* Someone setting the kops IG node cloud label manually to something else than the IG name ended up in issues with node identity.
We should validate more, but that can come as future PRs.
> Validate labels

- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
Cherry pick of #9909 on release-1.18.
#9909: Get launch template versions after filtering templates
> Automated cherry pick of #9909: Get launch template versions after filtering templates

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
Most likely this comes from ASG thinking the instance is inService, but it is terminating when we run describe from EC2.
`kops get instances` should maybe also show instance status: terminating at some point, but that would also require changes in the rolling update code as it now assumes we filter terminating/terminated nodes.
> Continue if asg instance is unknown

- nodeup/pkg/model/kube_proxy.go
- nodeup/pkg/model/kubelet.go
- nodeup/pkg/model/networking/kube_router.go
- nodeup/pkg/model/node_authorizer.go
- nodeup/pkg/model/tests/golden/minimal/tasks-kube-proxy.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-amd64.yaml
- nodeup/pkg/model/tests/golden/side-loading/tasks-kube-proxy-arm64.yaml
- pkg/model/iam.go
- upup/pkg/fi/nodeup/nodetasks/bootstrap_client.go
- upup/pkg/fi/nodeup/nodetasks/file.go
- upup/pkg/fi/nodeup/nodetasks/load_image.go
- upup/pkg/fi/nodeup/nodetasks/service.go
> Allow the BootstrapClient task to run after Protokube

- nodeup/pkg/model/cloudconfig.go
- pkg/model/bootstrapscript.go
Looks like the in-tree CCM gets confused over these params.
fixes #9928
> Don't write application credentials to cloud config unless external CCM is enabled

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/podsecuritypolicy.addons.k8s.io/k8s-1.12.yaml.template
fixes #9937 
This is quite good page to read through https://octetz.com/docs/2019/2019-10-12-static-pods/
When we are deploying apiserver, controller-manager, scheduler, etcds with static pods. It means that those are running in docker and we cannot shutdown those using kubernetes api. However, when kubelet will try to add those "mirror pods" to kubernetes API the PSPs are applied. Kubelet cannot add these pods to K8s api without this permission
> add kube-system psp to system:nodes

- pkg/model/iam.go
While reviewing https://github.com/kubernetes/kops/pull/9867 I noticed that kops modifies existing/shared IAM instance profiles when setting additional policies.
In my opinion, kops should only modify the resources it creates. If changes are applied on external resources shared between multiple clusters, the consequences would be unpredictable.
> Only add additional policies to kops managed IAMRoles

- pkg/model/iam.go
Cherry pick of #9867 #9924 on release-1.18.
#9867: only apply external policy tasks on non-shared iam
#9924: Only add additional policies to kops managed IAMRoles
> Automated cherry pick of #9867: only apply external policy tasks on non-shared iam #9924: Only add additional policies to kops managed IAMRoles

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/validation/validation.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Add support for the ChainInsertMode configuration option when using Calico networking.
From https://docs.projectcalico.org/reference/felix/configuration:
Controls whether Felix hooks the kernel’s top-level iptables chains by inserting a rule at the top of the chain or by appending a rule at the bottom. Insert is the safe default since it prevents Calico’s rules from being bypassed. If you switch to Append mode, be sure that the other rules in the chains signal acceptance by falling through to the Calico rules, otherwise the Calico policy will be bypassed. [Default: Insert]
> Support ChainInsertMode config option for Calico Networking

- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
This now exercises the kops-controller node bootstrapping logic
minor improvements as a part of #9855
> Add instance groups and k8s 1.19 to bootstrapchannelbuilder tests

- channels/alpha
- channels/stable
- Bump k8s 1.16.15 and Ubuntu image from August from `alpha` to `stable`
- Bump k8s versions with releases from yesterday:
- https://github.com/kubernetes/kubernetes/releases/tag/v1.19.2
- https://github.com/kubernetes/kubernetes/releases/tag/v1.18.9
- https://github.com/kubernetes/kubernetes/releases/tag/v1.17.12
- Bump ubuntu ami version to latest available - `ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907`
> Bump k8s versions and Ubuntu ami version to latest

- nodeup/pkg/model/containerd.go
- pkg/model/components/containerd.go
https://github.com/containerd/containerd/releases/tag/v1.4.1
v1.4.0 was never released so we can just replace it.
> Update containerd to v1.4.1

- hack/.packages
- pkg/assets/BUILD.bazel
- pkg/assets/builder.go
- upup/pkg/fi/cloudup/BUILD.bazel
- upup/pkg/fi/cloudup/urls.go
- util/pkg/mirrors/BUILD.bazel
- util/pkg/mirrors/mirrors.go
- util/pkg/vfs/context.go
Current implementation only looks for hash files in the S3 mirror and, if that is down, kops commands will fail with:
```
cannot determine hash for "https://kubeupv2.s3.amazonaws.com/kops/1.19.0-alpha.4/linux/amd64/nodeup"
(have you specified a valid file location?)
```
The code in the assets remapping and mirroring is quite complex and even if this looks a bit less elegant than I would like, it works pretty well.
Fixes: #9951
> Use all kops mirrors to determine artifacts hashes

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
The current problem is following: https://play.golang.org/p/6rglepaQ9r8
Because `CreateStorageClass` is `*bool` it will be marked always as `True` if defined. And because https://github.com/kubernetes/kops/blob/master/pkg/model/components/openstack.go#L51-L53 makes sure that this will be always true.
/kind bug
> OpenStack: allow to specify storageClass creation to false

- pkg/model/iam/subject.go
- pkg/model/iam/types.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/awsup/BUILD.bazel
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/awsup/mock_aws_cloud.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
This allows IAM roles that kops creates for service accounts to work in govcloud and china
> Add AWS partition support to iam service account roles

- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/docker.go
- pkg/apis/kops/validation/validation.go
- pkg/model/components/containerd.go
- pkg/model/components/docker.go
https://github.com/docker/docker-ce/releases/tag/v19.03.13
> Update Docker to v19.03.13

- cmd/kops/get_instances.go
When the api is unavailable, kops will say all the nodes have not yet joined the cluster. That is not the case simply because e.g the admin credentials have been expired. This PR makes it a bit more clear that we cannot know the node name when the API is unavailable.
> Improve kops get instances when api is unavailable

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
These became required a few cilium versions ago.
This basically fixes the same as reported in kubespray: https://github.com/kubernetes-sigs/kubespray/issues/6681, which was fixed in https://github.com/kubernetes-sigs/kubespray/pull/6683
I encountered exactly the same error with kops and cilium. A follow up error is that the cilium agents fail and keep restarting due to the cilium-operator not starting up and not issuing heart beats.
EDIT: I'm not sure I understand the folder structure in `upup/models/cloudup/resources/addons/networking.cilium.io`. I already figured out that I have to run a local build first to update bindata.go...but I don't understand which of the 3 templates needs the changes.
> Add missing permissions for cilium-operator

- cmd/kops/create.go
- cmd/kops/create_cluster.go
- cmd/kops/edit_cluster.go
- cmd/kops/edit_instancegroup.go
- examples/kops-api-example/up.go
- nodeup/pkg/model/kubelet_test.go
- pkg/commands/helpers_readwrite.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/defaults.go
- upup/pkg/fi/cloudup/populate_cluster_spec.go
- upup/pkg/fi/cloudup/populatecluster_test.go
- upup/pkg/fi/cloudup/validation_test.go
- upup/pkg/kutil/convert_kubeup_cluster.go
We tend to build cloud, call some method, and then build cloud over
again. It would be easier to just pass the first one along.
Passing along cloud would also make it easier to mock cloud.
> Build cloud outside of PerformAssignments

- channels/stable
It's been a week since these versions were pushed to alpha, seems like it's ready for stable.
> Bumping k8s versions and ubuntu AMI version from alpha to stable

- docs/releases/1.19-NOTES.md
As of Nov 9th 2019, HashiCorp is starting a phased approach to deprecate support of Terraform v0.11 in Terraform providers.
https://www.hashicorp.com/blog/deprecating-terraform-0-11-support-in-terraform-providers
This deprecation notice should be merged in kops v1.19 prior to the merge of PR #9940 in kops v1.20.
> Add deprecation notice for support of Terraform v0.11

- cmd/kops/create_cluster.go
- docs/cli/kops_create_cluster.md
Fixes typo in cmd/kops/create_cluster.go and
docs/cli/kops_create_cluster.md where example output had filename.yamlh,
changed to filename.yaml
Resolves https://github.com/kubernetes/kops/issues/9994
> Fix small typo in create cluster help output

- protokube/pkg/protokube/labeler.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Adds a label and nodeSelector to prevent kops-controller from running on nodes that were created with an older version of kops (and thus don't have the necessary PKI files provisioned by nodeup).
Fixes #9953 
Upgrading a 3-node control plane from kops 1.18.1 appears to be working.
> Add label to prevent kops-controller from running on old nodes

- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/cilium.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/pkg/fi/cloudup/new_cluster_test.go
Fixes #9966 
/cc @hakman @rifelpet
> Cilium hubble pointer

- WORKSPACE
Protokube was not building, needs rules_docker v0.14.4
> Update rules_docker in order to build protokube

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.9.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/template_functions.go
This PR upgrades the Spot Cluster Controller to version 1.0.67 and stores the user credentials in a `Secret` instead of a `ConfigMap`.
> Spotinst: Upgrade the Spot Cluster Controller to version 1.0.67

- cloudmock/aws/mockec2/vpcs.go
- upup/pkg/fi/cloudup/awstasks/vpc.go
- upup/pkg/fi/cloudup/awstasks/vpc_test.go
/cc @codablock
without the fix, the test fails with:
```
--- FAIL: TestSharedVPCAdditionalCIDR (0.00s)
kops/upup/pkg/fi/cloudup/awstasks/vpc_test.go:218: Unexpected VPC: expected={
CidrBlock: "172.21.0.0/16",
CidrBlockAssociationSet: [{
AssociationId: "vpc-1-0",
CidrBlock: "172.22.0.0/16",
CidrBlockState: {
State: "associated"
}
}],
IsDefault: false,
Tags: [{
Key: "Name",
Value: "vpc-1"
}],
VpcId: "vpc-1"
} actual={
CidrBlock: "172.21.0.0/16",
CidrBlockAssociationSet: [{
AssociationId: "vpc-1-0",
CidrBlock: "172.22.0.0/16",
CidrBlockState: {
State: "disassociated"
}
}],
IsDefault: false,
Tags: [{
Key: "Name",
Value: "vpc-1"
}],
VpcId: "vpc-1"
}
FAIL
FAIL	k8s.io/kops/upup/pkg/fi/cloudup/awstasks	0.627s
```
> Don't disassociate additional CIDR blocks with shared VPCs

- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- k8s/crds/kops.k8s.io_instancegroups.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
#6356 Enable kubelet `--housekeeping-interval` flag.
**Testing Completed**
- Create a cluster with `kubelet` option `housekeepingInterval`
- Verify `kubelet` process has argument ` --housekeeping-interval`
> enable kubelet --housekeeping-interval flag

- docs/development/ports.md
- pkg/wellknownports/wellknownports.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
The new kops-controller port conflicts with Cilium etcd's port.
> Move kops-controller serving port out of conflict

- docs/networking/calico.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- pkg/model/iam/iam_builder.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
using calico config `awsSrcDstCheck` and flag `FELIX_AWSSRCDSTCHECK` instead of [k8s-ec2-srcdst](https://github.com/ottoyiu/k8s-ec2-srcdst).  
for backward compatibility where in [k8s-ec2-srcdst](https://github.com/ottoyiu/k8s-ec2-srcdst) resources are already deployed following the below mentioned rules
crossSubnet | awsSrcDestCheck | Result
-- | -- | --
false | Enabled/Disabled/DoNothing | k8s-ec2-srcdst deployment doesn't exist
true | Enabled/Disabled/DoNothing | k8s-ec2-srcdst deployment has 0 replicas, to effectively disable it
Fixes: #10014
> [calico] awsSrcDstCheck to disable src/dest checks in AWS

- nodeup/pkg/model/networking/calico.go
- pkg/apis/kops/cluster.go
- pkg/model/firewall.go
- pkg/model/iam/iam_builder.go
- pkg/model/pki.go
- tests/integration/update_cluster/bastionadditional_user-data/kubernetes.tf
- tests/integration/update_cluster/privatecalico/cloudformation.json
- tests/integration/update_cluster/privatecalico/kubernetes.tf
For _kubernetes_ 1.12+, _kops_ hardcodes `DATASTORE_TYPE` to "kubernetes".
https://github.com/kubernetes/kops/blob/5cc1b5ad8ef074b86a61db80a8b24aca1f6dbb53/upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template#L36
https://github.com/kubernetes/kops/blob/5cc1b5ad8ef074b86a61db80a8b24aca1f6dbb53/upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template#L763-L764
> Open etcd port only when Calico uses "etcd" datastore

- pkg/commands/set_cluster.go
- pkg/commands/set_cluster_test.go
Some fields you cannot change using the `kops set cluster` command because the validation only parses a few.
Adding the `sshAccess` to be in the list for the release-1.18 branch.
On the main branch this is fixed and you can change all the fields, but I cannot use master right now for some cases :)
I propose to add this tiny change and I'm willing to add more in this PR if needed.
I know that might have another release for this branch so will be good to have this.
thanks!
/cc @hakman
> kops/cmd: add sshAccess to be recognized for the kops set cluster command

- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
/kind api-change
Add support for kops to declare `--request-timeout` flag from kube-apiserver
Addresses #10026
**Does this PR introduce a user-facing change?:**
Enable users to set timeout value for all kinds of handlers via `request-timeout` flag on kube-apiserver
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:**
```yaml
kind: Cluster
spec:
kubeAPIServer:
requestTimeout: "180s"
```
> Add support for KubeAPIServer --request-timeout flag

- cmd/kops/upgrade_cluster.go
Ref: https://github.com/kubernetes/kops/issues/10021
/cc @rifelpet @justinsb
> Allow upgrades when IG image is Ubuntu 20.04

- docs/networking/calico.md
- k8s/crds/kops.k8s.io_clusters.yaml
- nodeup/pkg/model/networking/calico.go
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Refs: https://github.com/kubernetes/kops/issues/9753
I add new option to enable WireGuard on Calico.
**Sample Configuration**
```yaml
networking:
calico:
wireguardEnabled: true
```
**Result of this configuration**
```
$ calicoctl get node -o yaml
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
kind: Node
metadata:
annotations:
projectcalico.org/kube-labels: '{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/instance-type":"t2.medium","beta.kubernetes.io/os":"linux","failure-domain.beta.kubernetes.io/region":"ap-northeast-1","failure-domain.beta.kubernetes.io/zone":"ap-northeast-1a","kops.k8s.io/instancegroup":"master-ap-northeast-1a","kops.k8s.io/kops-controller-pki":"","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"ip-172-16-1-104.ap-northeast-1.com …
```
> Add WireGuard support for Calico CNI 

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
Cherry pick of #10038 on release-1.18.
#10038: Add support for KubeAPIServer --request-timeout flag
> Automated cherry pick of #10038: Add support for KubeAPIServer --request-timeout flag

- k8s/crds/kops.k8s.io_clusters.yaml
- nodeup/pkg/model/packages.go
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #10037 on release-1.18.
#10037: Add wireguardEnabled option in networking Calico
> Automated cherry pick of #10037: Add WireGuard support for Calico CNI

- docs/extra.css
- hack/mkdocs_macros/feature_stability_table.py
Feature tables are no longer generated correctly. Simplifying things seems to fix it.
Before fix:
https://kops.sigs.k8s.io/networking/calico/#configuring-wireguard
After fix:
https://5f83dda2c9e9d40008ce7f05--kubernetes-kops.netlify.app/networking/calico/#configuring-wireguard
/cc @MoShitrit @rifelpet @olemarkus
> Fix docs feature table not being rendered

- cmd/kops/delete_instance.go
/kind bug
`kops delete instance` do not pass on cluster resulting in a nil pointer dereference
> Fix nil pointer when deleting instance

- pkg/instancegroups/instancegroups.go
- pkg/resources/digitalocean/cloud.go
Implement delete instance for handling rolling updates.
> [Digital Ocean] Implement Delete Instance logic for rolling update

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/authentication.aws-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
I used these manifests as a reference: https://github.com/kubernetes-sigs/aws-iam-authenticator/tree/v0.5.2/deploy
This addresses some security issues disclosed [here](https://bugs.chromium.org/p/project-zero/issues/detail?id=2066).
> Upgrade aws-iam-authenticator to 0.5.2

- docs/examples/kops-tests-private-net-bastion-host.md
Refs: #9751 
I only update a doc `kops-tests-private-net-bastion-host`.
> Rewrite ssh user to ubuntu in bastions docs

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
Cherry pick of #9917 on release-1.18.
#9917: Remove force_tcp flag for nodelocalcache dot zone
> Automated cherry pick of #9917: Remove force_tcp flag for nodelocalcache dot zone

- channels/alpha
Updating alpha channel with yesterday's releases to k8s versions:
- https://github.com/kubernetes/kubernetes/releases/tag/v1.17.13
- https://github.com/kubernetes/kubernetes/releases/tag/v1.18.10
- https://github.com/kubernetes/kubernetes/releases/tag/v1.19.3
Also, updated Ubuntu AMI to latest release:
```
$ aws ec2 describe-images --region us-east-1 --output table \
>     --owners 099720109477 \
>     --query "sort_by(Images, &CreationDate)[*].[CreationDate,Name,ImageId]" \
>     --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-*"
-------------------------------------------------------------------------------------------------------------------------
|                                                    DescribeImages …
```
> Updating alpha with October releases and latest Ubuntu AMI version

- pkg/model/components/kubelet.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
Since we actually control the kubelet cluster dns IP we don't need to make things complex with iptables rules and complex port bindings.
That upstream defaults to these is only to make things simpler for those deploying this to vendor managed k8s clusters.
I think other maintainers suggested this when reviewing the PR that introduced this addon.
> Simplify node local dns

- channels/pkg/channels/addon.go
- channels/pkg/channels/addons_test.go
I was a little bit confused by the desired behavior of the AddonMenu merge in channels so I decided to write a test to better understand it.  Can someone help me understand the expected behavior after a merge of two AddonMenus, like what happens in `apply_channel.go`?  Unless my understanding is incorrect, (or I've got a bug in the test) it seems like the merge behavior is incorrect, or maybe just confusing.  
```
--- FAIL: Test_MergeAddons (0.00s)
addons_test.go:223: Unexpected AddonMenu merge result,
Merged:
AddonMenu{
Addon{Name: a, Version: 1.0.0, KubernetesVersion: >=1.18.0, Id: k8s-1.18},
}
Expected:
AddonMenu{
Addon{Name: a, Version: 1.0.1, KubernetesVersion: >=1.18.0, Id: k8s-1.18},
}
addons_test.go:223: Unexpected AddonMenu merge result,
Merged:
AddonMenu{
Addon{Name: a, Version: …
```
> Fix bug in MergeAddons and test

- pkg/model/components/kubelet.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/template_functions.go
Cherry pick of #10059 on release-1.18.
#10059: Don't let node-local-dns add iptables rules
> Automated cherry pick of #10059: Don't let node-local-dns add iptables rules

- docs/gpu.md
> Add some quick notes on how to get GPU opertor working

- channels/pkg/cmd/root.go
This removes a redundant printing of error messages and no longer prints the usage help text when channels fails.
Before:
```
$ ./.build/local/channels apply channel -f ./upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml --yes
NAME				CURRENT	UPDATE
core.addons.k8s.io		-	1.4.0
dns-controller.addons.k8s.io	-	1.19.0-alpha.4
kops-controller.addons.k8s.io	-	1.19.0-alpha.4
kube-dns.addons.k8s.io		-	1.15.13-kops.3
kubelet-api.rbac.addons.k8s.io	-	v0.0.1
limit-range.addons.k8s.io	-	1.5.0
storage-aws.addons.k8s.io	-	1.15.0
I1018 16:49:43.908920   87960 addon.go:140] Applying update from "./upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io/k8s-1.12.yaml"
Error: error updating "dns-controller.addons.k8s.io": error applying update from …
```
> Cleanup channels error output

- docs/networking/calico.md
- docs/releases/1.19-NOTES.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/validation/validation.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
https://docs.projectcalico.org/about/about-ebpf
https://docs.projectcalico.org/maintenance/enabling-bpf
https://docs.projectcalico.org/reference/felix/configuration#ebpf-dataplane-configuration
> Add eBPF dataplane support for Calico CNI

- pkg/apis/kops/validation/BUILD.bazel
- pkg/apis/kops/validation/aws.go
- pkg/apis/kops/validation/instancegroup.go
A recent sdk update added `_Values()` functions that return a list of all enums for given values. This updates the API validation's hardcoded lists of strings to instead use these functions.
```go
const (
// InstanceInterruptionBehaviorHibernate is a InstanceInterruptionBehavior enum value
InstanceInterruptionBehaviorHibernate = "hibernate"
// InstanceInterruptionBehaviorStop is a InstanceInterruptionBehavior enum value
InstanceInterruptionBehaviorStop = "stop"
// InstanceInterruptionBehaviorTerminate is a InstanceInterruptionBehavior enum value
InstanceInterruptionBehaviorTerminate = "terminate"
)
// InstanceInterruptionBehavior_Values returns all elements of the InstanceInterruptionBehavior enum
func InstanceInterruptionBehavior_Values() []string {
return []string{ …
```
> Use AWS SDK lists of enum values for API validation

- pkg/apis/kops/validation/instancegroup.go
- pkg/apis/kops/validation/instancegroup_test.go
> Allow more volume types

- upup/pkg/fi/cloudup/alitasks/loadbalancer.go
- upup/pkg/fi/cloudup/awstasks/load_balancer.go
- upup/pkg/fi/cloudup/dotasks/loadbalancer.go
It's a system field, we should treat the value as matching.
Issue #9992
> Ignore changes to ForAPIServer field

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.flannel/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #10064 on release-1.19.
#10064: Update Flannel CNI to v0.13.0
> Automated cherry pick of #10064: Update Flannel CNI to v0.13.0

- Makefile
- hack/verify-gomod.sh
- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/kubetest2-kops/deployer/deployer.go
- tests/e2e/kubetest2-kops/deployer/down.go
- tests/e2e/kubetest2-kops/deployer/up.go
- tests/e2e/kubetest2-kops/util/http.go
- tests/e2e/kubetest2-kops/util/publicip.go
This connects the `kubetest2-kops --up --down` flags to run `kops create cluster` `kops validate cluster` and `kops delete cluster`.
I added a preliminary set of flags that we'll pass to `kops create cluster` but there are many more flags we'll add to the Deployer struct (zones, instance counts and sizes, etc.).
New flags:
```
$ cd tests/e2e; go run kubetest2-kops/main.go --help
Usage:
kubetest2 kops [Flags] [DeployerFlags] -- [TesterArgs]
Flags:
--artifacts string   top-level directory to put artifacts under for each kubetest2 run, defaulting to "${ARTIFACTS:-./_artifacts}". If using the ginkgo tester, this must be an absolute path. (default "/Users/prifel/work/src/k8s.io/kops/tests/e2e/_artifacts")
--build              build kubernetes
--down               tear down the test cluster
-h, …
```
> kubetest2 - Implement create/validate/delete cluster functionality

- nodeup/pkg/model/kubelet.go
- nodeup/pkg/model/networking/cilium.go
Cherry pick of #10092 on release-1.19.
#10092: Fix circular dependency in tasks related to kubelet
> Automated cherry pick of #10092: Fix circular dependency in tasks related to kubelet

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
Fixes: #10081 
Cilium ConfigMap template was wrong, so I fixed it.
I confirmed that kops can successfully create clusters using this change when `enablePrometheusMetrics` is specified  for Cilium.
> Fix cilium template by specifying boolean as a string for enable-metrics

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
Cherry pick of #10094 on release-1.19.
#10094: Fix cilium template by specifying boolean as a string for
> Automated cherry pick of #10094: Fix cilium template by specifying boolean as a string for

- docs/development/building.md
Update Kops documentation to reflect support for Go versions `go1.14+` and `go1.15+`.
Kops `make verify` and `make all examples test` successfully tested against Go versions `go1.14`, `go1.15` and `go1.15.3`.
Latest Go version `go1.13.15` is no longer supported due to the following error...
```
$ go version
go version go1.13.15 linux/amd64
$ make clean && make apimachinery
if test -e /c/GitHub/kops/.build; then rm -rfv /c/GitHub/kops/.build; fi
bazel clean
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
rm -rf tests/integration/update_cluster/*/.terraform
sh -c hack/make-apimachinery.sh
-mod=mod not supported (can be '', 'readonly', or 'vendor')
make: *** [Makefile:526: apimachinery-codegen] Error 1
```
> Update Kops Go build supported versions 1.15

- docs/advisories/etcd-manager-certificate-expiration.md
The hack/workaround works only on some versions so best not to have it at all. Also, I think `--cloudonly` is needed for the rolling-update to work.
We could add some hack/workaround in the issue, if we want to share the link with someone in Slack at some point.
https://deploy-preview-10102--kubernetes-kops.netlify.app/advisories/etcd-manager-certificate-expiration/#solution
> Remove hack/workaround from etcd-manager certificate expiration advisory

- cmd/kops/update_cluster.go
- docs/cli/kops_update_cluster.md
We do log a hint for the user when we have exported an empty kubecfg,
but this now supports the "current cluster" UX.
Issue #9990
> Default to exporting a kubecfg, even without credentials

- cmd/kops/update_cluster.go
- docs/cli/kops_update_cluster.md
Cherry pick of #10105 on release-1.19.
#10105: Default to exporting a kubecfg, even without credentials
> Automated cherry pick of #10105: Default to exporting a kubecfg, even without credentials

- cmd/kops/integration_test.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
Makes the `TerraformJSON` flag not depend on disabling the `Terraform-0.12` flag.
Suitable for backport to 1.19 branch.
> Remove dependency of TerraformJSON feature flag

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
Based on discussion with @fasaxc in Slack I changed the Calico manifest to use an optional ConfigMap to set the k8s endpoints.
Additionally I added an option for the cleanup of iptables rules (in case it's need for migration) and updated the version to 3.16.4.
/cc @seh @olemarkus
> Update Calico config for eBPF mode

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
Cherry pick of #10115 on release-1.19.
#10115: Use optional ConfigMap to configure k8s API endpoint for
> Automated cherry pick of #10115: Use optional ConfigMap to configure k8s API endpoint for

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Cherry pick of #10124 on release-1.19.
#10124: Update AWS VPC CNI to 1.7.5
> Automated cherry pick of #10124: Update AWS VPC CNI to 1.7.5

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
In this PR:
- Update AWS VPC image on main and init container to v.1.7.5
- Adding `apps` `apiGroup` to handle `list` and `watch` `daemonsets`, since `extensions` is no more (we should remove `extensions` at some point, but I figured I would still leave it here since the [original manifest](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.7/aws-k8s-cni-cn.yaml#L47) still contains it).
- Adding `xtables-lock` volume and volumeMount which were introduced in [v1.7.1](https://github.com/aws/amazon-vpc-cni-k8s/pull/1187) as a fix for `iptables`
- Adding `DISABLE_TCP_EARLY_DEMUX` toggle as introduced in [v1.7.3](https://github.com/aws/amazon-vpc-cni-k8s/pull/1222)
> Update AWS VPC CNI to 1.7.5

- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/kubedns.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
Add ability to use kube-dns as upstream on node-local-dns, instead of using systems default in resolv.conf
With this flag enabled, even if we use the node-local-dns to cache responses, we use as upstream the main kube-dns server for all types of requests, and not only the ones of *.cluster.local
This way we can customize the main kube-dns for external domains and make this changes also effective to the node-local-dns nodes
In our case, we're using rewrites on coredns to easily route some requests to internal services without exiting the cluster, and without modifying the application. With this flag we can keep this behaviour and still use node-local-dns:
```
rewrite name exact queue.myapp.com queue-system.myapp.svc.cluster.local
```
A dns request of `queue.myapp.com` to coredns will …
> Add nodeLocalDNSCache.kubeDnsOnly option

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
v1.7.x got a makeup with a lot of quoting (which is quite annoying) which makes it hard to compare to the upstream manifest.
This PR mostly adds quotes, reshuffles things and makes some minor changes to align the kOps manifest with the one from upstream:
https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.7/config/v1.7/aws-k8s-cni.yaml
Changes are best viewed in the generated test file diff `upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml`.
/cc @MoShitrit @rifelpet
> Align AWS VPC CNI manifest with upstream

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Cherry pick of #10126 on release-1.19.
#10126: Amazon VPC CNI - rearrange manifest resources
> Automated cherry pick of #10126: Align AWS VPC CNI manifest with upstream

- Makefile
- hack/.cfnlintrc.yaml
- hack/verify-cloudformation.sh
This is an official AWS linter for cloudformation: https://github.com/aws-cloudformation/cfn-python-lint
It has already caught a few bugs in our cloudformation json generation logic. Examples:
```
E3002 Invalid Property Resources/AWSAutoScalingAutoScalingGroupnodesmixedinstancesexamplecom/Properties/MixedInstancesPolicy/InstancesDistribution/SpotInstancePool
//kops/tests/integration/update_cluster/mixed_instances_spot/cloudformation.json:321:13
E3031 CidrIp contains invalid characters (Pattern: x.x.x.x/y) at Resources/AWSEC2SecurityGroupIngresssshexternaltonode2001085a348/Properties/CidrIp
//kops/tests/integration/update_cluster/complex/cloudformation.json:833:9
I3011 The default action when replacing/removing a resource is to delete it. Set explicit values for UpdateReplacePolicy / …
```
> Add verify-cloudformation script

- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/mixed_instances/cloudformation.json
- tests/integration/update_cluster/mixed_instances_spot/cloudformation.json
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/securitygrouprule.go
```
E3002 Invalid Property Resources/AWSAutoScalingAutoScalingGroupnodesmixedinstancesexamplecom/Properties/MixedInstancesPolicy/InstancesDistribution/SpotInstancePool
//kops/tests/integration/update_cluster/mixed_instances_spot/cloudformation.json:321:13
E3031 CidrIp contains invalid characters (Pattern: x.x.x.x/y) at Resources/AWSEC2SecurityGroupIngresssshexternaltonode2001085a348/Properties/CidrIp
//kops/tests/integration/update_cluster/complex/cloudformation.json:833:9
```
New output:
```
$ make verify-cloudformation
hack/verify-cloudformation.sh
Cloudformation linting succeeded
```
I'm using the strings.Contains to determine if a CIDR is v6 since it seems simplest given that we know the value wont have a port number [0]
ref: #10015
[0] …
> Fix cloudformation lint errors

- Makefile
- hack/.cfnlintrc.yaml
- hack/verify-cloudformation.sh
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/mixed_instances/cloudformation.json
- tests/integration/update_cluster/mixed_instances_spot/cloudformation.json
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/securitygrouprule.go
Cherry pick of #10130 #10131 on release-1.19.
#10130: Add verify-cloudformation script
#10131: Fix cloudformation lint errors
> Automated cherry pick of #10130: Add verify-cloudformation script #10131: Fix cloudformation lint errors

- hack/verify-cloudformation.sh
With #10131 merged, we can now make the job fail if an issue is found. The failure wont prevent the PR from being merged since the job is optional, but it will at least be visible to reviewers.
> Make verify-cloudformation job fail when issues are found

- pkg/model/components/etcd.go
Support for etcd v2 is removed in kOps 1.20, so this can be simplified also.
> Simplify etcd options builder

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- tests/integration/create_cluster/private_gce/expected-v1alpha2.yaml
- upup/pkg/fi/cloudup/new_cluster.go
- upup/pkg/fi/cloudup/new_cluster_test.go
Calico v2 is no longer supported starting kOps 1.20, so `calico.majorVersion` is no longer needed.
> Deprecate field calico.majorVersion

- upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Cilium leverages and builds on the kernel BPF functionality as well as various subsystems which integrate with BPF. Therefore, host systems are required to run Linux kernel version 4.9.17 or later to run a Cilium agent.
Using Debian10 should ensure we have the latest kernel that Cilium expects.
> [Digital Ocean] Use Debian10 as default image

- upup/pkg/fi/cloudup/populate_instancegroup_spec.go
Cherry pick of #10098 on release-1.19.
#10098: Use Debian10 image for DO
> Automated cherry pick of #10098: Use Debian10 image for DO

- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
This ensures we use the LoadBalancerName field rather than the name of the NLB task itself. The `direct` target is already using LoadBalancerName:
https://github.com/kubernetes/kops/blob/e91ed114499294f3e4242c6b23e7150a5c7262ec/upup/pkg/fi/cloudup/awstasks/network_load_balancer.go#L503-L504
This will need to be cherry-picked to release-1.19.
ref: https://github.com/kubernetes/kops/pull/10154#issuecomment-720820551
> Fix NLB naming for terraform and cloudformation targets

- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
Cherry pick of #10158 on release-1.19.
#10158: Fix NLB naming for terraform and cloudformation targets
> Automated cherry pick of #10158: Fix NLB naming for terraform and cloudformation targets

- pkg/model/awsmodel/api_loadbalancer.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/securitygrouprule.go
This way the security group rule task doesn't need to be aware of VPCs, since we should always know the VPC CIDR ahead of time via cluster spec.
This also fixes the terraform and cloudformation rendering of this rule (see the added cidr block in the integration test outputs)
These rules are for NLB's health checks. The AWS docs recommend allowing access from the entire VPC CIDRs
Also add rules for additionalNetworkCIDRs, supporting VPCs with multiple CIDR blocks.
ref: https://github.com/kubernetes/kops/pull/9011#issuecomment-720143425
> Move NLB's VPC CIDR security group rule logic into model

- pkg/model/awsmodel/autoscalinggroup.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/kubernetes.tf
We were correctly adding the security groups to the master ASGs but identified them incorrectly.
ref: https://github.com/kubernetes/kops/pull/10158#issuecomment-721111686
> Fix additionalSecurityGroups support for NLB

- pkg/model/awsmodel/api_loadbalancer.go
- pkg/model/awsmodel/autoscalinggroup.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/securitygrouprule.go
Cherry pick of #10161 #10162 on release-1.19.
#10161: Move NLB's VPC CIDR security group rule logic into model
#10162: Fix additionalSecurityGroups support for NLB
> Automated cherry pick of #10161: Move NLB's VPC CIDR security group rule logic into model #10162: Fix additionalSecurityGroups support for NLB

- pkg/apis/kops/instancegroup.go
- pkg/apis/nodeup/bootstrap.go
- pkg/instancegroups/instancegroups.go
Signed-off-by: zouyu <zouy.fnst@cn.fujitsu.com>
> Some typos

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
This PR fixes a particular issue when deploying Calico CNI in other AMI not based on Debian where the local SSL CA Cert store doesn't always point to `ca-certificates.crt`
@hakman suggested to mount the whole directory instead of referring to a file as a workaorund. More details on #10150 
Signed-off-by: Marcos Soutullo Rodriguez
> Mount the whole /etc/ssl/certs directory for k8s-ec2-srcdst

- pkg/instancegroups/instancegroups.go
- pkg/instancegroups/rollingupdate_test.go
- pkg/validation/validate_cluster.go
- pkg/validation/validate_cluster_test.go
When an error occurs during cluster validation during a rolling update, the validation phase waits for a certain period of time before continuing. 
We can avoid this wait for certain errors inapplicable to an instance group whose rolling update occurring. eg: When a node in a different instance group is terminated leading to a error regarding instance group target size being lesser than expected. For such errors we do not want rolling update on the instance group to wait for errors on inapplicable instance groups.
Fixes [https://github.com/kubernetes/kops/issues/10009](https://github.com/kubernetes/kops/issues/10009)
Really appreciate the review comments and discussions. Working on this PR so far has been a great experience for me.
> Avoid waiting on validation during rolling update for inapplicable instance groups

- pkg/instancegroups/rollingupdate_os_test.go
- upup/pkg/fi/cloudup/openstack/cloud.go
- upup/pkg/fi/cloudup/openstack/instance.go
- upup/pkg/fi/cloudup/openstack/mock_cloud.go
- upup/pkg/fi/cloudup/openstack/port.go
- upup/pkg/fi/cloudup/openstacktasks/instance.go
Because we changed the behaviour how kops rolling update works, we are all the time randomly seeing following error:
```
{"conflictingRequest": {"message": "Port e3a94980-6b13-4ed1-8188-0c3634964915 is still in use.", "code": 409}}
```
The problem here is that we delete the instance that used port x, and then we are creating new instance using port x. Seems that this behaviour is now too fast at least for our OpenStack. Still after one hour the port is attached to deleted instance. This seems OpenStack bug, but because its quite easy to fix in kops side - I will do it.
With this code we are able to run rolling updates also in these cases.
/cc @olemarkus
> OpenStack Reset deviceID status if needed

- pkg/kubeconfig/kubecfg_builder.go
Searching git history shows KubeBearerToken is no longer used.
```
$ grep -r KubeBearerToken . | wc -l
0
```
> Remove unused bearer token field from kubeconfig builder

- pkg/model/openstackmodel/servergroup.go
- upup/pkg/fi/cloudup/openstacktasks/lblistener.go
This fixes #10173 by sorting the Allowed CIDRs and KubernetesAPIAccess, which will result in tasks comparing deterministic slices.
The issue in question mentions comparing the unordered contents against each other, but the change required for that might be considerable.
https://github.com/kubernetes/kops/blob/3941bd507d62a9ef7bb36f91b45478120f840d9b/upup/pkg/fi/changes.go#L181 compares indexed values directly against each other, so I think the implicit assumption is that all comparison slices should be ordered.
> Compare KubernetesAPIAccess to OpenStack allowedCIDRs deterministically

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
Cherry pick of #10169 on release-1.19.
#10169: Fix: Mount the whole `/etc/ssl/certs` directory for
> Automated cherry pick of #10169: Mount the whole /etc/ssl/certs directory for k8s-ec2-srcdst

- pkg/model/awsmodel/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation_test.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform_test.go
Some extra fixes after #10187, to be able to remove the SpotPrice when already set.
/cc @rifelpet
> Fix disabling spot instances when using launch templates

- util/pkg/vfs/swiftfs.go
Cherry pick of #10144 on release-1.19.
#10144: allow reauth for openstack client
> Automated cherry pick of #10144: allow reauth for openstack client

- permalinks/acm_nlb.md
The ACM bugfix will fail API validation with k8s >=1.19 + `sslCertificate` + `class: Classic`.
The error message will contain this permalink, so I'd like to get eyes on this early.
If/when we handle migration without downtime, we can update these instructions to match.
ref: https://github.com/kubernetes/kops/issues/9756
> Add ACM cert permalink

- pkg/apis/kops/validation/validation.go
- pkg/kubeconfig/create_kubecfg.go
- pkg/kubeconfig/create_kubecfg_test.go
- pkg/model/awsmodel/api_loadbalancer.go
- pkg/model/awsmodel/autoscalinggroup.go
- pkg/model/firewall.go
- pkg/model/names.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
- upup/pkg/fi/cloudup/awstasks/targetgroup.go
This uses commits from https://github.com/kubernetes/kops/pull/9761 combined with the new NLB support to provision a second NLB listener. It requires converting the `Listeners` and `TargetGroups` NLB fields to slices in which each listener should forward traffic to the target group of the same list index. I couldn't use a map of port number to TargetGroup because fi/loader.go uses reflection to set values of fields that are Tasks, and map values aren't addressable which resulted in a panic.
I also temporarily pulled in the commit from https://github.com/kubernetes/kops/pull/10076/files to run the e2e presubmit job with an ACM cert. Before we merge this I'll remove the commit.
ref: https://github.com/kubernetes/kops/issues/9756
>  Setup a second NLB listener when an AWS ACM certificate is used

- pkg/apis/kops/validation/validation.go
- pkg/kubeconfig/create_kubecfg.go
- pkg/kubeconfig/create_kubecfg_test.go
- pkg/model/awsmodel/api_loadbalancer.go
- pkg/model/awsmodel/autoscalinggroup.go
- pkg/model/firewall.go
- pkg/model/names.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
- upup/pkg/fi/cloudup/awstasks/targetgroup.go
Cherry pick of #10157 on release-1.19.
#10157: Add support for multiple NLB listeners and target
> Automated cherry pick of #10157: Add support for multiple NLB listeners and target

- .github/workflows/main.yml
- .travis.yml
- WORKSPACE
Cherry pick of #10209 on release-1.19.
#10209: Update Go to v1.15.4
> Automated cherry pick of #10209: Update Go to v1.15.4

- docs/advanced/experimental.md
- docs/getting_started/spot-ocean.md
- pkg/model/spotinstmodel/instance_group.go
- upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
- upup/pkg/fi/cloudup/spotinsttasks/ocean.go
This PR adds support for configuring [Resource Limits](https://docs.spot.io/ocean/features/scaling-kubernetes?id=resource-limits) in Ocean Auto Scaler.
> Spotinst: Configure Resource Limits in Ocean Auto Scaler

- Makefile
- pkg/model/components/kubeapiserver/model.go
- pkg/model/components/kubeapiserver/tests/minimal/tasks.yaml
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/dns-controller.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/dns-controller.addons.k8s.io-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
- upup/pkg/fi/cloudup/urls_test.go
- version.go
```
*********************************************************************************
The cluster was last updated by kops version 1.19.0-beta.1
To permit updating by the older version 1.19.0-alpha.5, run with the --allow-kops-downgrade flag
*********************************************************************************
```
> Update kOps version after 1.19.0-beta.1 release

- pkg/validation/validate_cluster.go
- pkg/validation/validate_cluster_test.go
Validating components is redundant with the `masterStaticPods` check.
Fixes #10057
> Remove components from cluster validation

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/storage-openstack.addons.k8s.io/k8s-1.16.yaml.template
Topology support is going to be added 2.0.4 provisioner, but that is not yet published. This is why at least we need featureflag for it.
Also I added feature to add custom csi plugin image to verify things with newer image if needed.
> Allow to use custom csi plugin image and enable topology support

- pkg/validation/validate_cluster.go
- pkg/validation/validate_cluster_test.go
Cherry pick of #10214 on release-1.19.
#10214: Remove components from cluster validation
> Automated cherry pick of #10214: Remove components from cluster validation

- cmd/kops/validate_cluster.go
- docs/cli/kops_validate_cluster.md
Cherry pick of #10219 on release-1.19.
#10219: Update validate cluster cli docs
> Automated cherry pick of #10219: Update validate cluster cli docs

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/overwrite_settings/cluster.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
This PR addresses #7946, which I believed was closed in error - the PR referenced as a fix allows the etcd log level to be changed, but etcd-manager has its own klog-based log level which was hardcoded to a quite verbose level in Kops itself, even reducing the log level of etcd you still have to deal with a lot of noise which then has to be filtered out in fluentd or whatever you use to collect/aggregate container logs.
I took https://github.com/kubernetes/kops/pull/8402 as a guide, please let me know what you think.
> Make etcd-manager log verbosity configurable

- channels/alpha
- channels/stable
Following @olemarkus's [comment](https://github.com/kubernetes/kops/issues/10184#issuecomment-723413144) on issue #10184, I noticed that ubuntu has a more recent version to their AMI.
This update is for `alpha` channel, within a week or so we can push it to `stable` if everything's good.
```
$ aws ec2 describe-images --region us-east-1 --output table \
>     --owners 099720109477 \
>     --query "sort_by(Images, &CreationDate)[*].[CreationDate,Name,ImageId]" \
>     --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-*"
-------------------------------------------------------------------------------------------------------------------------
|                                                    DescribeImages                                                     | …
```
> Update Ubuntu ami to latest version

- .travis.yml
Cherry pick of #10230 on release-1.19.
#10230: Switch ARM64 CI to Graviton2 CPU
> Automated cherry pick of #10230: Switch ARM64 CI to Graviton2 CPU

- nodeup/pkg/model/miscutils.go
- nodeup/pkg/model/packages.go
I intend to make the boundary be 1.20, but the e2e tests are currently configured with 1.19.
> Don't install the misc packages for k8s 1.20+

- docs/getting_started/install.md
Fixes the install commands in install readme.
> Fix readme

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/overwrite_settings/cluster.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
Cherry pick of #10194 on release-1.19.
#10194: feat: Make etcd-manager log verbosity configurable
> Automated cherry pick of #10194: feat: Make etcd-manager log verbosity configurable

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/dockerconfig.go
- pkg/apis/kops/v1alpha2/dockerconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
Add the capability of defining the default runtime and runtimes fields for the docker daemon used in kops nodes.
This fixes https://github.com/kubernetes/kops/issues/10127
> Add default runtime and runtimes fields in the docker config

- cmd/kops/delete_instance.go
- cmd/kops/rollingupdatecluster.go
- cmd/kops/validate_cluster.go
- pkg/validation/BUILD.bazel
- pkg/validation/validate_cluster.go
- pkg/validation/validate_cluster_test.go
This PR fixes cluster validation dependency on a local kubeconfig file.
Cluster validation requires a local kubeconfig file with a context having the same name as the cluster.
This PR replaces this requirement by providing a `rest.Config`, the same that was used to build the `k8sclient` used to communicate with the target cluster.
> Fix cluster validation dependency on local kubeconfig

- pkg/instancegroups/instancegroups.go
- pkg/validation/validate_cluster.go
- pkg/validation/validate_cluster_test.go
This PR fixes https://github.com/kubernetes/kops/issues/10183
> Associate instance group to pod validation failures in cluster validation.

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/dockerconfig.go
- pkg/apis/kops/v1alpha2/dockerconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
Cherry pick of #10238 on release-1.19.
#10238: dockerconfig: Add default runtime and runtimes fields
> Automated cherry pick of #10238: dockerconfig: Add default runtime and runtimes fields

- upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
This field was causing spurious differences to be detected.
We probably should be comparing the values in the kops model, not the
GCE model.
> GCE: ignore (output-only) networkInterface.name

- channels/pkg/api/channel.go
- channels/pkg/channels/addon.go
- cmd/kops/get_instances.go
- cmd/kops/rollingupdatecluster.go
- pkg/cloudinstances/cloud_instance_group.go
- pkg/instancegroups/rollingupdate.go
- pkg/instancegroups/rollingupdate_test.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
Fixes #7971
Or at least makes it possible to fix it for the addons we need.
Works by adding another element to the addon spec. If it is set, will make channels patch an annotation on the relevant nodes that rolling update uses to determine if an instance needs updating.
> Make it possible to use OnDelete update strategy on addon daemonset

- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Clusters which have been on a patch release of kOps 1.15 would have the version of the storage-aws addon incremented to 1.15.1 or later. Such clusters will not pick up the storage-aws addon changes #8582 added to kOps 1.17.
Bump the storage-addon version to cause such clusters to install these changes.
Fixes #10246 
/kind bug
> Fix version of storage-aws addon manifest

- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/cilium/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/public-jwks/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Cherry pick of #10247 on release-1.19.
#10247: Fix version of storage-aws addon manifest
> Automated cherry pick of #10247: Fix version of storage-aws addon manifest

- hack/cfn-lint.Dockerfile
- hack/verify-cloudformation.sh
The [Dockerfile we were using in the cfn-python-lint repo](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/Dockerfile) wasn't actually pinned to the version associated with the git tag, it always installs the latest version.
A [recent release](https://github.com/aws-cloudformation/cfn-python-lint/releases/tag/v0.41.0) consolidated error rules regarding invalid values (https://github.com/aws-cloudformation/cfn-python-lint/pull/1750)
We use an intentionally invalid "us-test-1" region and zones in much of our testing. We used to be able to ignore this "invalid AZ" error ([E2510](https://github.com/kubernetes/kops/blob/master/hack/.cfnlintrc.yaml#L3)), but now we would need to ignore all invalid values for all resource properties.
This pins cfn-python-lint to an older …
> Fix cloudformation lint job

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Release notes for 3.0.20201117:
* Release notes for 3.0.20200531
* Adds support for using OS application credentials
* Fixes usage of OpenStack Swift reauthentication
* Move from debian-hyperkube-base to debian-base
* Add license headers to each file
* Fix some typos picked up by verify-spelling
* Fix some problems with trailing spaces
* Add support for etcd 3.4.13
* Switch to gcr.io/cloud-marketplace-containers/google/debian10 - Fix
for #340 option 1
* Support for ARM64
* BUG: OpenStack ignore AvailabilityZone in discovery
* Added full cinder ID to candidateDeviceNodes
* feat(etcd-manager-ctl): use backupname to delete backup instead of timestamp
* Update kops to pick up AllowAuth Openstack
* Build base image by raw expansion of deb packages
* Switch the cloudbuild docker image, locking …
> Update etcd-manager to 3.0.20201117

- nodeup/pkg/model/kops_controller.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/nodeup/nodetasks/bootstrap_client.go
> Use separate domain for kops-controller bootstrap

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Cherry pick of #10257 on release-1.19.
#10257: Update etcd-manager to 3.0.20201117
> Automated cherry pick of #10257: Update etcd-manager to 3.0.20201117

- nodeup/pkg/model/kops_controller.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/kops-controller.addons.k8s.io-k8s-1.16.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/nodeup/nodetasks/bootstrap_client.go
Cherry pick of #10239 on release-1.19.
#10239: Use separate domain for kops-controller bootstrap
> Automated cherry pick of #10239: Use separate domain for kops-controller bootstrap

- .travis.yml
This reverts commit e7614fda
https://docs.travis-ci.com/user/multi-cpu-architectures/#multi-cpu-availaibility
> The two arm64 tags are used right now to distinguish between OSS-support only (arch: arm64) and available both for OSS & commercial (arch: arm64-graviton2, available only on travis-ci.com).
/cc @olemarkus
> Revert "Switch ARM64 CI to Graviton2 CPU"

- .travis.yml
Cherry pick of #10262 on release-1.19.
#10262: Revert "Switch ARM64 CI to Graviton2 CPU"
> Automated cherry pick of #10262: Revert "Switch ARM64 CI to Graviton2 CPU"

- Makefile
- cmd/kops-controller/BUILD.bazel
- cmd/kube-apiserver-healthcheck/BUILD.bazel
- dns-controller/cmd/dns-controller/BUILD.bazel
Manifest pushing seems broken because of cross-repo image pushing. Switching to pushing to same repo tags with arch suffix should get it fixed, same as we do with etcd-manager.
https://storage.googleapis.com/kubernetes-jenkins/logs/kops-postsubmit-push-to-staging/1329154456519970816/build-log.txt
> Fix multi-arch image pushing

- Makefile
- cloudbuild.yaml
- cmd/kops-controller/BUILD.bazel
- cmd/kube-apiserver-healthcheck/BUILD.bazel
- dns-controller/cmd/dns-controller/BUILD.bazel
Cherry pick of #10265 #10270 on release-1.19.
#10265: Push multi-arch images
#10270: Fix multi-arch image pushing
> Automated cherry pick of #10265: Push multi-arch images #10270: Fix multi-arch image pushing

- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/validation/aws.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/awsmodel/api_loadbalancer.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
> Add sslPolicy for NLB to change listener's security policy

- Makefile
Latest Bazel changes invalidate the build cache when switching the arch, so build is slower. Grouping artifacts by arch speeds things up. This did not happen before https://github.com/kubernetes/kops/pull/10240.
https://testgrid.k8s.io/kops-misc#kops-postsubmit-push-to-staging
/cc @rifelpet
> Optimize Bazel builds by os and arch

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/options.go
Cherry pick of #10277 on release-1.19.
#10277: Use etcd v3.4.13 for k8s v1.19+
> Automated cherry pick of #10277: Use etcd v3.4.13 for k8s v1.19+

- pkg/apis/kops/validation/instancegroup.go
- pkg/model/awsmodel/BUILD.bazel
- pkg/model/awsmodel/autoscalinggroup.go
- pkg/testutils/integrationtestharness.go
- tests/integration/update_cluster/externallb/cloudformation.json
- tests/integration/update_cluster/externallb/in-v1alpha2.yaml
- tests/integration/update_cluster/externallb/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/BUILD.bazel
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Fixes: #10268 
Summary of fixes:
1. duplicate tasks names because the names for external TGs are the same for each IG
2. model names differ from actual names so always show changes
3. ordering is required to not show false changes
> Parse TargetGroup names from ARNs

- docs/cluster_spec.md
- hack/cfn-lint.Dockerfile
- hack/verify-cloudformation.sh
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/validation/aws.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/awsmodel/api_loadbalancer.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
Cherry pick of #10256 #9666 on release-1.19.
#10256: Fix cloudformation lint job
#9666: feat(aws): add PolicyNames for ELB to change listener's
> Automated cherry pick of #10256: Fix cloudformation lint job #9666: feat(aws): add PolicyNames for ELB to change listener's

- pkg/apis/kops/validation/instancegroup.go
- pkg/model/awsmodel/BUILD.bazel
- pkg/model/awsmodel/autoscalinggroup.go
- pkg/testutils/integrationtestharness.go
- tests/integration/update_cluster/externallb/cloudformation.json
- tests/integration/update_cluster/externallb/in-v1alpha2.yaml
- tests/integration/update_cluster/externallb/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/BUILD.bazel
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Cherry pick of #10276 on release-1.19.
#10276: Parse TargetGrup names from ARNs
> Automated cherry pick of #10276: Parse TargetGrup names from ARNs

- go.sum
During Go v1.15.5 testing, `code-generator v0.20.0-beta.2` crypto hash is automatically added to Go module dependencies.
**Which issue(s) this PR fixes**
N/A
Go crypto hashes file `go.sum` is updated when executing `make verify`.
> Add Go code-generator v0.20.0-beta.2 crypto hash

- docs/releases/1.19-NOTES.md
- permalinks/acm_nlb.md
Also made the permalink instructions easier to follow and mentioned cleanup
(we can amend the cleanup note if https://github.com/kubernetes/kops/pull/10196 lands in 1.19)
> Add ACM/NLB instructions to 1.19 release notes

- docs/advisories/etcd-manager-certificate-expiration.md
Can check cert expiry using openssl
> Can check cert expiry using openssl

- docs/networking/weave.md
- go.sum
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
In this PR, we enable users to override the default version of networking/Weave specs.
> [weave] Add support for default version override

- pkg/model/context.go
`UseLegacyELBName` was added 4 years ago and should be no longer need these days.
Ref: https://github.com/kubernetes/kops/pull/2051#issuecomment-285368816
> Remove support for using legacy ELB name

- pkg/assets/BUILD.bazel
- pkg/assets/builder.go
This appears to have been to support migration to kOps 1.7.
> Remove support for disabling manifest normalization

- util/pkg/vfs/context.go
invalid Azure Blob schem -> invalid Azure Blob scheme
> Fix a typo in an error message returned from buildAzureBlobPath

- docs/networking/weave.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.weave/k8s-1.12.yaml.template
Cherry pick of #10273 on release-1.18.
#10273: Add support for default version override
> Automated cherry pick of #10273: Add support for default version override

- go.sum
- k8s/crds/kops.k8s.io_clusters.yaml
- nodeup/pkg/model/kube_apiserver.go
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/complex/data/aws_launch_template_master-us-test-1a.masters.complex.example.com_user_data
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
Allow setting CPU limit and Mem request / limit for kube API server.
We had a user overload our API server with a few requests recently, which in turn caused the host to OOM different components causing debugging delays and stability issues. We eventually manually applied CPU & Mem Req/Limit to API server causing the API server pod to OOM instead of host level systems. This caused the cluster to become more stable while we debugged the underlying issue.
This change allows for those setting to be permanently set which would allow for a faster recover if something like this happens again in the future.
> Allow setting CPU limit and Mem request / limit for kube API server

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
Sometimes we see the following error during a rolling update:
> I1125 18:12:46.467059     165 instancegroups.go:340] Draining the node: "ip-X-X-X-X.X.compute.internal".
I1125 18:12:46.473365     165 instancegroups.go:359] deleting node "ip-X-X-X-X.X.compute.internal" from kubernetes
I1125 18:12:46.476756     165 instancegroups.go:486] Stopping instance "i-XXXXXXXX", node "ip-X-X-X-X.X.compute.internal",  in group "X" (this may take a while).
E1125 18:12:46.523269     165 instancegroups.go:367] error deleting instance "i-XXXXXXXX", node "ip-X-X- X-X.X.compute.internal": error deleting instance "i-XXXXXXXX", node "ip-X-X-X-X.X.compute.internal": error deleting instance "i-XXXXXXXX": InvalidInstanceID.NotFound: The instance ID 'i-XXXXXXXXX' does not exist
status code: 400, request id: …
> Tolerate missing detached EC2 instances

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #10310 on release-1.19.
#10310: Update Calico to v3.17.0
> Automated cherry pick of #10310: Update Calico to v3.17.0

- pkg/instancegroups/instancegroups.go
detatchInstance used to return if executed against master IG. This is no longer the case, so kops tries to detach master nodes when deleting instance.
/kind bug
> Don't try to detach masters

- upup/pkg/fi/cloudup/awsup/aws_cloud.go
Cherry pick of #10319 on release-1.19.
#10319: Tolerate missing detached EC2 instances
> Automated cherry pick of #10319: Tolerate missing detached EC2 instances

- channels/stable
- tests/integration/create_cluster/complex/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
- tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
- tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
It's been 3 weeks since we pushed [November k8s releases](https://github.com/kubernetes/kops/pull/10227) and 2 weeks since the [AMI updates for legacy versions](https://github.com/kubernetes/kops/pull/10269), looks like they are ready for `stable`.
> Push alpha to stable

- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
closes: #6612 
I added two parameters in kube-apiserver: 
- defaultNotReadyTolerationSeconds
- defaultUnreachableTolerationSeconds
these parameters control the pod toleration time.
You can specify it in cluster spec:
```yaml
spec:
kubeAPIServer:
defaultNotReadyTolerationSeconds: 600
defaultUnreachableTolerationSeconds: 600
```
> Add paramaeters related to Taint based Evictions in kube-apiserver

- pkg/apis/kops/validation/instancegroup.go
- pkg/apis/kops/validation/instancegroup_test.go
Cherry pick of #10345 on release-1.19.
#10345: Alloq using gp3 for root volumes
> Automated cherry pick of #10345: Alloq using gp3 for root volumes

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
A new patch version was just released for aws-vpc-cni: https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.7.6
Also created #10338 for back-porting to 1.19 branch
> Bump aws-vpc-cni version to 1.7.6

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Cherry pick of #10337 on release-1.19.
#10337: Bump aws-vpc-cni version to 1.7.6
> Automated cherry pick of #10337: Bump aws-vpc-cni version to 1.7.6

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
The important PR we want to pick up is 369, fixing a bug when
ListenMetricsURLS is set as an env var.
There are other changes coming to etcd-manager: a go version bump to
1.15, updating kops vfs to include azure support, updating to klog2.
Those have some associated risk, so the intent is that this version
can be back-ported to kops 1.19 and then we can validate the bigger
changes on the master branch.
Full changelist:
* Release notes for 3.0.20201117 [#364](https://github.com/kopeio/etcd-manager/pull/364)
* Fix gofmt [#365](https://github.com/kopeio/etcd-manager/pull/365)
* Add gofmt check to github actions [#366](https://github.com/kopeio/etcd-manager/pull/366)
* Add boilerplate to tools/deb-tools/main.go [#367](https://github.com/kopeio/etcd-manager/pull/367)
* Do not set …
> Update etcd-manager to 3.0.20201202

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/digitalocean-cloud-controller.addons.k8s.io/k8s-1.8.yaml.template
This changes bumps DigitalOcean's cloud-controller-manager to version 0.1.30 which brings a number of new features.
> Update DigitalOcean cloud-controller-manager to v0.1.30

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/model/components/kubecontrollermanager.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/aws-cloud-controller.addons.k8s.io/k8s-1.18.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/aws-cloud-controller.addons.k8s.io-k8s-1.18.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- Added addon for aws-cloud-controller (aws-cloud-controller.addons.k8s.io) 
- Initial manifest: `upup/models/cloudup/resources/addons/aws-cloud-controller.addons.k8s.io/k8s-1.18.yaml.template`
- `--external-cloud-volume-plugin` flag for KCM
- AWSCCMTag to hold the logic to determine the CCM tag.  This will change as soon as we have stable releases (soon).
> Add aws-cloud-controller-manager config to addons

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Cherry pick of #10351 on release-1.19.
#10351: Update etcd-manager to 3.0.20201202
> Automated cherry pick of #10351: Update etcd-manager to 3.0.20201202

- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
Cherry pick of #10339 on release-1.19.
#10339: Add paramaeters related to Taint based Evictions in
> Automated cherry pick of #10339: Add paramaeters related to Taint based Evictions in

- hack/.packages
- tests/fuzz/BUILD.bazel
- tests/fuzz/build.sh
- tests/fuzz/fuzz.go
This PR adds a go-fuzz fuzzer that targets `WriteToken` as well as a build script to integrate Kops into OSS-fuzz. 
I have the integration script available for OSS-fuzz and will be happy to finalize the integration. For this, at least one maintainers email is needed for potential bug reports.
Fuzzing is a way of testing programs whereby pseudo-random data is passed to a target application with the goal of finding bugs and vulnerabilities. Kubernetes is already being fuzzed continuously by way of OSS-fuzz, and this has led to finding bugs and vulnerabilities.
> Add fuzzer and OSS-fuzz build script

- pkg/model/awsmodel/oidc_provider.go
- pkg/model/components/discovery.go
- pkg/model/iam.go
- pkg/model/iam/BUILD.bazel
- pkg/model/iam/subject.go
Kubernetes 1.20+ requires the `--service-account-issuer` flag be passed to kube-apiserver
Fixes #10279 
/cc @justinsb
> Set --service-account-issuer for k8s 1.20+

- docs/getting_started/digitalocean.md
- upup/pkg/fi/cloudup/apply_cluster.go
- vendor/modules.txt
Hi,
I wanted thoughts on promoting Digital Ocean to Beta. Currently, a good amount of KOPS functionality is in place for DO, and I wanted to check with the KOPS maintainers if you are okay with this promotion.
Tested with both single cluster and multi-master HA setup
Tested kubernetes upgrade with kops update feature (ex: from v1.19.3 to v1.19.4)
Tested kops validate command on cluster creation
Tested creating multiple instance groups and managing & updating & deleting it.
Tested using the cluster with a DO load balancer when a new service with type: LoadBalancer is used.
Tested creating new PV with CSI drivers for managing DO volumes.
FYI - @timoreimann
> [Digital Ocean] Promote to Beta

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
Cherry pick of #10375 on release-1.19.
#10375: Remove resource limits from cluster autoscaler
> Automated cherry pick of #10375: Remove resource limits from cluster autoscaler

- addons/cluster-autoscaler/README.md
I was looking into adding the cluster-autoscaler for kops, but couldn't find the proper documentation.
Currently the README points to this: https://kops.sigs.k8s.io/cluster_spec/#cluster-autoscaler which doesnt exist anymore due to this commit: https://github.com/kubernetes/kops/commit/c1b4dd6752937d096665537b3074c81ff36eab0b changing the website documentation.
This should remedy that. I didn't open an issue because this seemed like a super simple fix. Hope that's okay!
> fix cluster-autoscaler README url from cluster_spec -> addons

- .github/workflows/main.yml
- Makefile
This will avoid some make warnings.
/cc @olemarkus
> Rename duplicate ci target to quick-ci

- docs/operations/images.md
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
> Update docs for CentOS 8

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Highlights:
* Fix arm64 images, which were built with an incorrect base image.
* Initial (experimental) Azure support
Full change list:
* Update Kops dependency for Azure Blob Storage support [#372](https://github.com/kopeio/etcd-manager/pull/372)
* Exclude gazelle from tools/deb-tools [#373](https://github.com/kopeio/etcd-manager/pull/373)
* Regenerate bazel in tools/deb-tools [#374](https://github.com/kopeio/etcd-manager/pull/374)
* Release notes for 3.0.20201202 [#375](https://github.com/kopeio/etcd-manager/pull/375)
* Remove travis CI [#377](https://github.com/kopeio/etcd-manager/pull/377)
* Fix vendor generation for tools/deb-tools subproject [#376](https://github.com/kopeio/etcd-manager/pull/376)
* Add script to verify image hashes …
> Update etcd-manager to 20201209

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Cherry pick of #10394 on release-1.19.
#10394: Update etcd-manager to 20201209
> Automated cherry pick of #10394: Update etcd-manager to 20201209

- channels/alpha
* https://github.com/kubernetes/kubernetes/releases/tag/v1.17.15
* https://github.com/kubernetes/kubernetes/releases/tag/v1.18.13
* https://github.com/kubernetes/kubernetes/releases/tag/v1.19.5
Also bumping the focal AMI to the latest one that's available everywhere including gov and china regions.
> Update alpha channel with December 2020 k8s releases and bump Ubuntu AMI version

- hack/update-goimports.sh
- hack/verify-goimports.sh
`mapfile` was introduced in bash 4.
We can use `read` instead to achieve the same thing - listing all .go files in the repo into an array
followup to https://github.com/kubernetes/kops/pull/10407
/cc @seh
> hack/goimports - Replace mapfile with read

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
/cc @johngmyers @olemarkus @rifelpet
> Allow override of registry and tag for Calico images

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- pkg/model/iam/iam_builder.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://docs.projectcalico.org/release-notes/#v3171
This also orders the fields in CalicoNetworkingSpec and updates the comments to make changes in https://github.com/kubernetes/kops/pull/10404 smaller.
Fixes: https://github.com/kubernetes/kops/issues/10363
> Update Calico to v3.17.1

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- pkg/model/iam/iam_builder.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #10316 #10408 on release-1.19.
#10316: Allow override of registry and tag for Calico images
#10408: Update Calico to v3.17.1
> Automated cherry pick of #10316: Allow override of registry and tag for Calico images #10408: Update Calico to v3.17.1

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Cherry pick of #10416 on release-1.19.
#10416: Bump aws-cni to 1.7.7
> Automated cherry pick of #10416: Bump aws-cni to 1.7.7

- pkg/model/components/containerd.go
- pkg/model/components/containerd_test.go
- upup/pkg/fi/cloudup/containerd.go
- upup/pkg/fi/cloudup/containerd_test.go
- upup/pkg/fi/cloudup/docker.go
The ARM64 version of containerd v1.4.3 was made available with the Docker v20.10.0 package.
Also, removing an unnecessary restriction for containerd running with older k8s and bumping the default for older k8s version to v1.3.9.
> Add support for containerd v1.4.3 ARM64

- pkg/model/components/containerd.go
- pkg/model/components/containerd_test.go
- upup/pkg/fi/cloudup/containerd.go
- upup/pkg/fi/cloudup/containerd_test.go
- upup/pkg/fi/cloudup/docker.go
Cherry pick of #10418 on release-1.19.
#10418: Add support for containerd v1.4.3 ARM64
> Automated cherry pick of #10418: Add support for containerd v1.4.3 ARM64

- docs/releases/1.19-NOTES.md
closes https://github.com/kubernetes/kops/issues/10017
> Add release note for terraform launch template migration

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
Problem:
Currently `PrometheusMetricsEnabled` only start servings metrics on `PrometheusMetricsPort` . But Prometheus can not scrape it. This PR will expose that service so Prometheus can scrape it. 
Sample config for Prometheus-operator
```apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
labels:
k8s-app: calico-node
monitoredBy: prometheus-infra
name: calico-node
namespace: kube-system
spec:
podMetricsEndpoints:
- interval: 30s
path: /metrics
port: metrics
namespaceSelector:
matchNames:
- kube-system
selector:
matchLabels:
k8s-app: calico-node
> Expose metrics port when PrometheusMetricsEnabled set to true in Calico

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
Cherry pick of #10414 on release-1.19.
#10414: This will expose metrics port when
> Automated cherry pick of #10414: This will expose metrics port when

- cmd/kops/toolbox_template.go
- docs/cli/kops_toolbox_template.md
- docs/operations/cluster_template.md
- docs/releases/1.20-NOTES.md
- pkg/util/templater/BUILD.bazel
- pkg/util/templater/template_functions.go
- pkg/util/templater/templater.go
- pkg/util/templater/templater_test.go
- tests/integration/channel/BUILD.bazel
- tests/integration/channel/integration_test.go
- tests/integration/channel/simple/BUILD.bazel
- tests/integration/channel/simple/mock_channel.go
This PR implements two template functions for setting recommended k8s version based on info from the given channel.
> Template functions for recommended kubernetes versions

- docs/cluster_spec.md
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
This will install CoreDNS as the default DNS server instead of kube-dns
Fixes https://github.com/kubernetes/kops/issues/6500
> Make CoreDNS the default DNS server

- docs/cluster_spec.md
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/template_functions.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/aws-cloud-controller.addons.k8s.io-k8s-1.18.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/cluster.yaml
1.19 may be a bit too late in the game.
> Delay defaulting to CoreDNS to k8s v1.20

- pkg/model/iam/BUILD.bazel
- pkg/model/iam/types.go
- upup/pkg/fi/cloudup/awsup/aws_utils.go
- upup/pkg/fi/cloudup/awsup/aws_utils_test.go
The maximum IAM role name length is 64 characters, which we hit much
more often now that we are constructing complex names.  Use our normal
strategy of adding a hash when we truncate.
This is not a breaking change, because these names were not valid
previously.
> IAM ServiceAccount Roles: truncate name at 64 characters

- cloudmock/aws/mockec2/vpcs.go
This should fix a flaky TestLifecycleComplex test that I've only been able to repro <1% of the time.
> cloudmock - guard the VPC CIDR association calls with a mutex

- images/mkdocs/requirements.txt
- mkdocs.yml
Except for mkdocs-macros, for some reason it would no longer recognize our hack/mkdocs_macros python module
> Upgrade mkdocs dependencies to latest

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
This PR adds a node affinity to the Ocean Controller deployment to schedule it to Linux nodes only.
> Spotinst: Schedule Ocean Controller to Linux nodes only

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
AWS-CNI 1.7.8 was released yesterday with a performance enhancement to reduce occasional EC2 API latency. More info on the [release page](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.7.8).
> Bump AWS-CNI to version 1.7.8

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Cherry pick of #10447 on release-1.19.
#10447: Bump AWS-CNI to version 1.7.8
> Automated cherry pick of #10447: Bump AWS-CNI to version 1.7.8

- protokube/pkg/protokube/labeler.go
When a user manually sets the hostnameOverride to a non-default value ([for example setting to "@hostname"](https://github.com/kubernetes/kops/blob/c9aa53895a9c77fa0a55cb896573d8e0a6ac1542/nodeup/pkg/model/context.go#L524)) this can cause the nodename passed to protokube to not match the node name in K8s. Instead query for the node by the hostname label as that should always match.
/cc: @johngmyers
> protokube - query host by label when setting tags

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #10442 on release-1.18.
#10442: Allow Calico to run on systems with loose reverse path
> Automated cherry pick of #10442: Allow Calico to run on systems with loose reverse path

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This should allow Calico to run on instances with newer linux versions, like Ubuntu 20.04.
xRef: https://github.com/rancher/rancher/issues/23316
xRef: https://github.com/projectcalico/felix/issues/2082
Fixes: #10441
> Allow Calico to run on systems with loose reverse path forwarding

- channels/alpha
- channels/stable
Following an issue that was raised with version tagging on the previous k8s releases from 9 days ago (more info [here](https://groups.google.com/g/kubernetes-dev/c/dNH2yknlCBA/m/7jq8KMcgAgAJ)), there were new patch releases this morning with fixes:
- https://github.com/kubernetes/kubernetes/releases/tag/v1.17.16
- https://github.com/kubernetes/kubernetes/releases/tag/v1.18.14
- https://github.com/kubernetes/kubernetes/releases/tag/v1.19.6
Also, it's been 9 days since the latest Ubuntu AMI version was updated on alpha, so pushing that to stable.
> Bump k8s versions on alpha and bump Ubuntu AMI version on stable

- docs/networking/calico.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/defaults.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- pkg/model/components/BUILD.bazel
- pkg/model/components/calico.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/populate_cluster_spec.go
- upup/pkg/fi/cloudup/template_functions.go
Cherry pick of #10404 on release-1.19.
#10404: Allow use of Calico's VXLAN networking backend
> Automated cherry pick of #10404: Allow use of Calico's VXLAN networking backend

- docs/networking/calico.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/defaults.go
- pkg/apis/kops/v1alpha2/networking.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/validation/validation.go
- pkg/apis/kops/validation/validation_test.go
- pkg/model/components/BUILD.bazel
- pkg/model/components/calico.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/populate_cluster_spec.go
- upup/pkg/fi/cloudup/template_functions.go
Introduce a new "encapsulationMode" field in Calico's portion of the _Cluster_ specification to allow switching between the the IP-in-IP and VXLAN encapsulation protocols. For now, we accept the values "ipip" and "vxlan," and forgo a possible "none" value that would disable encapsulation altogether (at least for the default Calico IP pool).
Augment the default-populating procedure for Calico to take this field into account when deciding both which networking backend to use and whether to use IP-in-IP or VXLAN encapsulation for the default IP pool. Note that these values supplied for [the "CALICO_IPV4POOL_IPIP" and "CALICO_IPV4POOL_VXLAN" environment variables](https://docs.projectcalico.org/reference/node/configuration#configuring-the-default-ip-pools) in the "calico-node" _DaemonSet_ pod …
> Calico: Allow operators to choose which encapsulation mode to use

- upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
This PR ensures the volume type is always in a lowercase format to prevent unnecessary updates:
```
...
Will modify resources:
Elastigroup/master-us-west-2a.masters.[...]
RootVolumeOpts           {"Type":"GP2","Size":64} -> {"Type":"gp2","Size":64}
...
```
> Spotinst: Ignore volume type case sensitivity to prevent unnecessary updates

- docs/getting_started/spot-ocean.md
- pkg/model/spotinstmodel/instance_group.go
- upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
- upup/pkg/fi/cloudup/spotinsttasks/ocean.go
This PR allows users to specify whether headroom resources should be automatically configured and optimized for Ocean.
> Spotinst: Expose Ocean Headroom percentage and autoconfig labels

- pkg/model/spotinstmodel/instance_group.go
- upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
This PR adds support for multiple subnets per zone by configuring subnets without specifying zone names (according to the Spot API specification).
> Spotinst: Support for multiple subnets per zone

- pkg/model/bootstrapscript.go
- pkg/model/bootstrapscript_test.go
- pkg/model/gcemodel/autoscalinggroup.go
- pkg/model/openstackmodel/tests/servergroup/adds-additional-security-groups.yaml
- pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-ClusterSpec.yaml
- pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-InstanceGroupSpec.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-auto-zone-distribution.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-external-router.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion-2.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-without-bastion-no-public-ip-association.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node.yaml
- pkg/model/openstackmodel/tests/servergroup/uses-instance-group-subnet-as-availability-zones-fallback.yaml
- pkg/model/openstackmodel/tests/servergroup/uses-instance-group-zones-as-availability-zones.yaml
- upup/pkg/fi/cloudup/alitasks/launchconfiguration.go
- upup/pkg/fi/cloudup/awstasks/launchconfiguration.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_api.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_cloudformation.go
- upup/pkg/fi/cloudup/awstasks/launchtemplate_target_terraform.go
- upup/pkg/fi/cloudup/dotasks/droplet.go
- upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
- upup/pkg/fi/cloudup/openstacktasks/instance.go
- upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
- upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
- upup/pkg/fi/cloudup/spotinsttasks/ocean.go
- upup/pkg/fi/topological_sort.go
This removes more of the deprecated type, but it also simplifies 
refactoring the GCE InstanceTemplate.
> Replace (some) deprecated ResourceHolder with Resource

- pkg/apis/kops/validation/validation.go
- tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/containerd-cloudformation/in-v1alpha2.yaml
- upup/pkg/fi/cloudup/containerd.go
Containerd 1.2 was only meant to be used for ARM64, when no other alternative version existed.
Containerd 1.2 was never the default in a released version of kOps, or advertised as supported.
At the moment, there is no need for it anymore, it is no longer supported and makes more complicated improvements to the config files.
> Drop support for containerd 1.2

- pkg/apis/kops/validation/validation.go
- tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/containerd-cloudformation/in-v1alpha2.yaml
- tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/privatecalico/data/aws_launch_template_master-us-test-1a.masters.privatecalico.example.com_user_data
- tests/integration/update_cluster/privatecalico/data/aws_launch_template_nodes.privatecalico.example.com_user_data
- upup/pkg/fi/cloudup/containerd.go
- upup/pkg/fi/cloudup/networking.go
- upup/pkg/fi/cloudup/networking_test.go
Cherry pick of #10483 #10481 on release-1.19.
#10483: Drop support for containerd 1.2
#10481: Update CNI plugins to v0.8.7
> Automated cherry pick of #10483: Drop support for containerd 1.2 #10481: Update CNI plugins to v0.8.7

- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/awstasks/render_test.go
- upup/pkg/fi/cloudup/cloudformation/target.go
- upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
- upup/pkg/fi/cloudup/terraform/target.go
- upup/pkg/fi/cloudup/terraform/target_hcl2.go
- upup/pkg/fi/cloudup/terraform/target_json.go
There's no need to track it separately, now that we have the Region
method on the Cloud interface.
> Use Region method of fi.Cloud

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
This PR upgrades the Ocean Controller to 1.0.69.
> Spotinst: Bump the Ocean Controller to 1.0.69

- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- k8s/crds/kops.k8s.io_instancegroups.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
#6356 Enable kubelet --event-qps flag.
#6150 Will provide the functionality to fix `[WARN] 4.2.9 Ensure that the --event-qps argument is set to 0 or a level which ensures appropriate event capture (Not Scored)` in kube-bench report (CIS benchmarks)
> Added event-qps and event-burst flags to kubelet

- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- k8s/crds/kops.k8s.io_instancegroups.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
Cherry pick of #10486 on release-1.19.
#10486: Added event-qps to kubelet flags Change default value for
> Automated cherry pick of #10486: Added event-qps to kubelet flags Change default value for

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/clusterautoscaler.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
Cherry pick of #10471 on release-1.19.
#10471: addons(cluster-autoscaler): Add newPodScaleUpDelay in
> Automated cherry pick of #10471: addons(cluster-autoscaler): Add newPodScaleUpDelay in

- pkg/model/bootstrapscript.go
Periodic tests are failing when `KOPS_ARCH` is set:
https://testgrid.k8s.io/kops-versions#kops-aws-k8s-latest
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-k8s-latest/1341755177660583936
This happens because the NodeUp template cannot be rendered when any of the supported architectures is missing.
> Fix cluster setup when KOPS_ARCH is set

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Amazon VPC CNI requires access to the CRI socket to get the local container info:
xRef: https://github.com/aws/amazon-vpc-cni-k8s/pull/371
This is the reason the periodic test for Amazon VPC CNI is failing since switching it to containerd:
https://testgrid.k8s.io/kops-network-plugins#kops-aws-cni-amazon-vpc
There are proposed changes to get away from the "dockershim" name, but still not merged:
xRef: https://github.com/aws/amazon-vpc-cni-k8s/pull/1175
> Use containerd.sock for AmazonVPC CNI with containerd

- cmd/kops/BUILD.bazel
- cmd/kops/create_cluster.go
- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml
- nodeup/pkg/model/tests/protokube/containerd/cluster.yaml
- pkg/apis/kops/validation/validation.go
- pkg/model/components/containerd.go
- tests/integration/update_cluster/containerd-custom/cloudformation.json
- tests/integration/update_cluster/containerd-custom/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/containerd-custom/in-v1alpha2.yaml
- tests/integration/update_cluster/containerd/cloudformation.json
- tests/integration/update_cluster/containerd/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/containerd/in-v1alpha2.yaml
Kubenet is not actually supported for containerd and is unmaintained in general. Our current Kubenet setup for containerd is actually a "hack" that should be used only for development.
I had a longer discussion with some people involved in SIG-Networking and the recommendation is to remove this hack and also to stop using Kubenet in general (especially not as a default).
> Remove support for Kubenet with containerd

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/cluster.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.12.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/amazonvpc-containerd/networking.amazon-vpc-routed-eni-k8s-1.16.yaml
Cherry pick of #10502 on release-1.19.
#10502: Use containerd.sock for AmazonVPC CNI with containerd
> Automated cherry pick of #10502: Use containerd.sock for AmazonVPC CNI with containerd

- cmd/kops/BUILD.bazel
- cmd/kops/create_cluster.go
- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml
- nodeup/pkg/model/tests/protokube/containerd/cluster.yaml
- pkg/apis/kops/validation/validation.go
- pkg/model/components/containerd.go
- tests/integration/update_cluster/containerd-custom/cloudformation.json
- tests/integration/update_cluster/containerd-custom/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/containerd-custom/in-v1alpha2.yaml
- tests/integration/update_cluster/containerd/cloudformation.json
- tests/integration/update_cluster/containerd/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/containerd/in-v1alpha2.yaml
Cherry pick of #10501 on release-1.19.
#10501: Remove support for Kubenet with containerd
> Automated cherry pick of #10501: Remove support for Kubenet with containerd

- pkg/resources/aws/aws.go
In case DeleteDhcpOptions returns InvalidDhcpOptionsId.NotFound, if somehow the dhcpoptions is deleted between "list resource" and "delete", treat it as successful delete.
To avoid this:
> I1228 20:39:50.478507      28 errors.go:32] unexpected aws error code: "InvalidDhcpOptionsID.NotFound"
dhcp-options:dopt-09a83785234855c50 	error deleting resources, will retry: error deleting DhcpOptions  "dopt-09a83785234855c50": InvalidDhcpOptionsID.NotFound: The dhcpOptions  ID 'dopt-09a83785234855c50' does not exist
...
not making progress deleting resources; giving up
> Treat InvalidDhcpOptionsId.NotFound as already-deleted

- docs/gpu.md
As the example sets a taint on the gpu-node, a toleration is required for the *gpu-feature-discovery* (gfd) daemonset to be able to run.
> Add required toleration to gpu documentation

- Makefile
- tests/e2e/kubetest2-kops/deployer/build.go
- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/kubetest2-kops/deployer/deployer.go
- tests/e2e/kubetest2-kops/deployer/dumplogs.go
- tests/e2e/kubetest2-kops/deployer/up.go
the cluster manifest will be useful when we add e2e templating support to confirm it is rendered as intended.
> e2e - dump cluster manifests into artifacts and add --kubernetes-version 

- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/kubetest2-kops/deployer/up.go
- tests/e2e/kubetest2-kops/gce/zones.go
Filling in some of the GCE-equivalents to the AWS code.
> kubetest2: add initial support for GCE

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/master_volumes.go
- upup/pkg/fi/cloudup/awstasks/ebsvolume.go
> Add gp3 Volume Type to etcd

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/master_volumes.go
- upup/pkg/fi/cloudup/awstasks/ebsvolume.go
Cherry pick of #10453 on release-1.19.
#10453: add gp3 volume default params
> Automated cherry pick of #10453: add gp3 volume default params

- pkg/model/awsmodel/BUILD.bazel
- pkg/model/awsmodel/autoscalinggroup.go
- pkg/model/awsmodel/autoscalinggroup_test.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
When using an AWS NLB in front of the Kubernetes API servers, we can't attach the EC2 security groups nominated in the _Cluster_ "spec.api.loadBalancer.additionalSecurityGroups" field directly to the load balancer, as NLBs don't have associated security groups. Instead, we intend to attach those nominated security groups to the machines that will receive network traffic forwarded from the NLB's listeners. For the API servers, since that program runs only on the master or control plane machines, we need only attach those security groups to the machines that will host the _kube-apiserver_ program, by way of the ASG launch templates that come from _kOps_ _InstanceGroups_ of role "master."
We were mistakenly including these security groups in launch templates derived from _InstanceGroups_ of …
> Only include API server additional security groups in InstanceGroups for masters

- pkg/model/awsmodel/BUILD.bazel
- pkg/model/awsmodel/autoscalinggroup.go
- pkg/model/awsmodel/autoscalinggroup_test.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
Cherry pick of #10519 on release-1.19.
#10519: Test that AWS launch templates include wrong SG
> Automated cherry pick of #10519: Test that AWS launch templates include wrong SG

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
https://github.com/cloudnativelabs/kube-router/releases/tag/v1.1.1
> Update kube-router to v1.1.1

- pkg/model/iam/iam_builder.go
- tests/integration/update_cluster/public-jwks/data/aws_iam_role_policy_masters.minimal.example.com_policy
These are needed by protokube to create the kops-controller DNS record to allow nodes to bootstrap. Ideally we could figure out a way for protokube to not rely on the ec2 instance's instance profile and role but until then we can revert to our original behavior here.
See these logs: https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-scenario-public-jwks/1345956556562239488/artifacts/ip-172-20-48-1.sa-east-1.compute.internal/protokube.log
```
I0104 05:03:51.264472    6482 dnscache.go:74] querying all DNS zones (no cached results)
I0104 05:03:51.264570    6482 route53.go:53] AWS request: route53 ListHostedZones
W0104 05:03:51.389485    6482 dnscontroller.go:124] Unexpected error in DNS controller, will retry: error querying for zones: error querying for DNS zones: …
```
> IRSA - continue adding route53 permisions to masters

- pkg/resources/aws/aws.go
Cherry pick of #10508 on release-1.19.
#10508: Treat InvalidDhcpOptionsId.NotFound as already-deleted
> Automated cherry pick of #10508: Treat InvalidDhcpOptionsId.NotFound as already-deleted

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
Cherry pick of #10512 on release-1.19.
#10512: Update kube-router to v1.1.1
> Automated cherry pick of #10512: Update kube-router to v1.1.1

- tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
- upup/pkg/fi/cloudup/new_cluster.go
- upup/pkg/fi/cloudup/new_cluster_test.go
> Prefix etcd cluster names with letters

- nodeup/pkg/model/kubectl.go
- nodeup/pkg/model/kubelet.go
- nodeup/pkg/model/miscutils.go
- util/pkg/distributions/distributions.go
- util/pkg/distributions/identify.go
- util/pkg/distributions/identify_test.go
- util/pkg/distributions/tests/ubuntu2010/etc/os-release
Teach nodeup about ubuntu 20.10, including the unusual
/etc/resolv.conf configuration.
> Recognize ubuntu 20.10

- docs/releases/1.19-NOTES.md
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/ebsvolume.go
Fixes  #9982
This will fix the issue for both new and existing clusters and only the clusters that are directly impacted by the bug. We could theoretically merge this as well as https://github.com/kubernetes/kops/pull/10361.
My main concern with this approach is if users don't `terraform state mv` on existing clusters and Terraform deletes and recreates the EBS volumes; their entire etcd state will be lost. We can try to make the release note more prominent but I'm open to other ideas on how to try to prevent people from making that mistake.
> Don't allow ebs volume TF resource names to begin with digit

- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/ebsvolume.go
Cherry pick of #10424 on release-1.19.
#10424: Don't allow ebs volume TF resource names to begin with digit
> Automated cherry pick of #10424: Don't allow ebs volume TF resource names to begin with digit

- docs/releases/1.19-NOTES.md
As Kubernetes will deprecate Docker runtime support from version 1.20 and will be removed in a future release (currently planned for the 1.22 release in late 2021), notify users that the default container runtime will be set to `containerd` from kOps 1.20.
https://github.com/kubernetes/kubernetes/tree/master/CHANGELOG/CHANGELOG-1.20.md#deprecation
**Which issue(s) this PR fixes**
#10356 
PR #10370 raised to set default container runtime to `containerd` in kOps 1.20.
> Add K8s Docker runtime support deprecation release note

- OWNERS
@olemarkus is one of the most active contributors and reviewers.
I would write more good things but I would just be stating the obvious.
😄 
/cc @geojaz @johngmyers @justinsb @kashifsaadat @mikesplain @olemarkus @rdrgmnzs @rifelpet @zetaab
> Promote Ole Markus to approvers list

- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/containerd_test.go
- nodeup/pkg/model/tests/containerdbuilder/flatcar/cluster.yaml
- nodeup/pkg/model/tests/containerdbuilder/flatcar/tasks.yaml
This makes it possible to configure Flatcar from kOps and also fixes the issue of custom socket location (different approach to #10518).
> Add containerd config file to Flatcar based instances

- tests/e2e/kubetest2-kops/deployer/deployer.go
- tests/e2e/kubetest2-kops/deployer/up.go
Otherwise I was getting my IPv6 address, which doesn't work well.
> kubetest2: support specifying admin-access value

- upup/pkg/fi/cloudup/gcetasks/instancetemplate.go
NVME only works with Local SSDs, which have their own restrictions;
it isn't a must-support GA blocker (which is why we had the log
previously)
> GCE: Don't warn about NVME

- tests/e2e/scenarios/upgrade/run-test
Starting very simple and hard-coded!
> Simple upgrade test using kubetest2 framework

- nodeup/pkg/model/kubectl.go
- nodeup/pkg/model/kubelet.go
- nodeup/pkg/model/miscutils.go
- util/pkg/distributions/distributions.go
- util/pkg/distributions/identify.go
- util/pkg/distributions/identify_test.go
Use of a struct makes it more sustainable, centralizing into the 
distribution package makes it simpler to follow.
> Refactor and centralize distribution logic

- hack/verify-bazel.sh
I fix a script for development.
When some diff are detected in `gazelle`, the command exit(1), so `verify-bazel.sh` exit without any messages.
For example, I run `gazelle` command directly:
```
$ _output/bin/gazelle fix -external=vendored -exclude=tests/e2e -mode=diff -proto=disable -repo_root=./
--- cmd/kops-controller/pkg/server/BUILD.bazel  1970-01-01 00:00:00.000000000 +0000
+++ cmd/kops-controller/pkg/server/BUILD.bazel  1970-01-01 00:00:00.000000000 +0000
@@ -13,9 +13,9 @@
"//pkg/apis/nodeup:go_default_library",
"//pkg/pki:go_default_library",
"//pkg/rbac:go_default_library",
+        "//upup/pkg/fi:go_default_library",
"//vendor/k8s.io/apimachinery/pkg/util/sets:go_default_library",
"//vendor/k8s.io/klog/v2:go_default_library",
-        "//upup/pkg/fi:go_default_library",
],
)
$ …
```
> Fix to handle exit code of gazelle command in hack/verify-bazel.sh

- nodeup/pkg/model/directories.go
- nodeup/pkg/model/kubelet.go
- upup/pkg/fi/nodeup/nodetasks/bindmount.go
Upstream bind mounts /var/lib/kubelet with exec, dev and suid
permissions, because emptyDirs end up inheriting these permissions.
Similarly, /home/kubernetes/flexvolume needs exec permission to
support flexdrivers.
> COS/GCE: exec on kubelet/flexvolume dirs

- pkg/model/openstackmodel/tests/servergroup/adds-additional-security-groups.yaml
- pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-ClusterSpec.yaml
- pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-InstanceGroupSpec.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-auto-zone-distribution.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-external-router.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion-2.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-without-bastion-no-public-ip-association.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node.yaml
- pkg/model/openstackmodel/tests/servergroup/uses-instance-group-subnet-as-availability-zones-fallback.yaml
- pkg/model/openstackmodel/tests/servergroup/uses-instance-group-zones-as-availability-zones.yaml
- upup/pkg/fi/cloudup/openstacktasks/instance.go
- upup/pkg/fi/cloudup/openstacktasks/poolassociation.go
- upup/pkg/fi/cloudup/openstacktasks/servergroup.go
We were adding to the ServerGroup without a mutex, so we introduce a mutex.
Also introduce some defense against the member list changing once we've
observed it, though this is already enforced by GetDependencies.
> Openstack: Prevent data race in servergroup member list

- channels/alpha
- channels/stable
- docs/releases/1.20-NOTES.md
- pkg/apis/kops/channel.go
I didn't realize we were defaulting to COS on GCE- this changes the default for >=1.17.0. I discovered this while researching #9832. When I tried to use calico on COS on GCE, I ran into the same  filesystem mount issues we saw with coreos on https://github.com/kubernetes/kops/issues/7931. 
Changing to this image fixes everything and calico comes up properly :)
> Updates GCE channels to use ubuntu over COS

- Makefile
- tests/e2e/kubetest2-tester-kops/main.go
- tests/e2e/pkg/tester/kubectl.go
- tests/e2e/pkg/tester/tester.go
- tests/e2e/scenarios/upgrade/run-test
This allows us to share tester flags (package version and bucket) for downloading kubectl while passing them to the ginkgo tester. The kubectl.go file is essentially copied from kubetest2-tester-ginkgo's [package.go](https://github.com/kubernetes-sigs/kubetest2/blob/master/pkg/testers/ginkgo/package.go) that downloads the e2e.test binary
> Kubetest2 - use our own tester that wraps kubetest2's ginkgo tester

- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
- pkg/model/components/clusterautoscaler.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template
In this PR, we make some additions on Cluster Autoscaler Addon Specs
We enable users to set their desired capacity for cluster-autoscaler addon.
There are edge cases, especially in big clusters, where autoscaler needs
to reconcile a large number of objects thus may need increased memory to
avoid OOMkills or increased cpu to avoid saturation.
Cluster autoscaler provides valuable insights for monitoring capacity
allocation and scheduling aspects of a cluster. In this commit, we
enable users to add proper annotation on deployment to scrape metrics
via Prometheus.
> [addons/CA] Add support for specifying resources and metrics

- pkg/model/spotinstmodel/instance_group.go
This PR fixes the `LaunchSpec` model builder which iterates over metadata labels multiple times.
> Spotinst: Iterate over metadata labels only once

- docs/cluster_spec.md
- nodeup/pkg/model/docker_test.go
- pkg/model/components/containerd.go
- pkg/model/components/docker.go
- pkg/model/components/kubelet.go
- tests/integration/update_cluster/containerd-custom/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/containerd/cloudformation.json.extracted.yaml
Currently, kOps uses cgroupfs cgroup driver for the kubelet and CRIs. This PR defaults
the cgroup driver to systemd for clusters created with k8s versions >= 1.20.
Using systemd as the cgroup-driver is the recommended way as per
https://kubernetes.io/docs/setup/production-environment/container-runtimes/
It would be really great if this can be tested by others :) !! I have tested this by bring up and tearing down a whole bunch of clusters :) .
I verified that systemd was being used by checking the memory cgroup hierarchy. I was able to see the top level kubepod.slice hierarchy. If cgroupfs driver is used then the directory would be named kubepod instead of kubepod.slice. 
Please do let me know if I have missed anything major here. Getting containerd working was very tricky since we don't …
> Default cgroup driver to systemd from k8s 1.20

- util/pkg/vfs/fs.go
The fs:// VFS protocol doesn't detect nonexistent files correctly. This results in files not being found actually bubbling up to the user rather than being treated as if the file doesn't exist.
The [syscall docs](https://pkg.go.dev/syscall#Errno) suggest using `errors.Is`.
Without this fix, `kops update cluster --yes` reports:
```
error reading last kops version used to update: open /path/to/state/foo.k8s.local/kops-version.txt: no such file or directory
```
Given the low impact of this and that kops-version.txt is being introduced in 1.19 I'd propose we cherry-pick this to release-1.19
> Fix file not found error detection in fs:// 

- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
The old code made the incorrect assumption that the NLB's list of TargetGroup tasks is in the same order as the NLB's list of listeners for their associations.
Because the model adds them in opposite orders this resulted in the TLS listener being forwarded to the TCP TG and vice versa.
This updates the terraform and cloudformation generation code to search the NLB's list of target groups by name for the target group that should be associated with the listener.
This matches the logic used in the "direct" target:
https://github.com/kubernetes/kops/blob/a140168c70de521939399f19fb0bdec7dd51ffa4/upup/pkg/fi/cloudup/awstasks/network_load_balancer.go#L87-L95
fixes #10562
> Fix NLB listener -> target group association for TF & CF

- util/pkg/vfs/fs.go
Cherry pick of #10566 on release-1.19.
#10566: Fix file not found error detection in fs://
> Automated cherry pick of #10566: Fix file not found error detection in fs://

- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
Cherry pick of #10567 on release-1.19.
#10567: Fix NLB listener -> target group association for TF & CF
> Automated cherry pick of #10567: Fix NLB listener -> target group association for TF & CF

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
This PR upgrades the Ocean Controller to 1.0.70.
> Spotinst: Bump the Ocean Controller to 1.0.70

- docs/getting_started/spot-ocean.md
- go.mod
- go.sum
- pkg/model/spotinstmodel/instance_group.go
- upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
- vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/launch_spec.go
- vendor/github.com/spotinst/spotinst-sdk-go/spotinst/version.go
- vendor/modules.txt
This PR allows users to specify whether the scale-down activities should be restricted in Ocean Launch Spec.
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
labels:
...
spotinst.io/restrict-scale-down: "true"
name: ...
spec:
...
```
> Spotinst: Specify whether scale-down activities should be restricted

- cloudmock/openstack/mockcompute/servers.go
- pkg/model/openstackmodel/servergroup.go
- pkg/model/openstackmodel/tests/servergroup/adds-additional-security-groups.yaml
- pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-ClusterSpec.yaml
- pkg/model/openstackmodel/tests/servergroup/adds-cloud-labels-from-InstanceGroupSpec.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-auto-zone-distribution.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion-with-API-loadbalancer.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-bastion.yaml
- pkg/model/openstackmodel/tests/servergroup/multizone-setup-3-masters-3-nodes-without-external-router.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion-2.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-one-bastion.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node-without-bastion-no-public-ip-association.yaml
- pkg/model/openstackmodel/tests/servergroup/one-master-one-node.yaml
- pkg/model/openstackmodel/tests/servergroup/uses-instance-group-subnet-as-availability-zones-fallback.yaml
- pkg/model/openstackmodel/tests/servergroup/uses-instance-group-zones-as-availability-zones.yaml
- pkg/resources/openstack/floatingip.go
- pkg/resources/openstack/instances.go
- upup/pkg/fi/cloudup/openstack/cloud.go
- upup/pkg/fi/cloudup/openstacktasks/instance.go
- upup/pkg/fi/cloudup/openstacktasks/servergroup.go
So this will modify the instance name format that we will see in OpenStack instance names AND in Kubernetes cluster. The current problem that we have is that if we delete instance from OpenStack and run `kops update cluster --yes` - the new instance will come back with same name. However, the OpenStack instanceid is changed and it leads to problems (there is mismatch between Kubernetes API node instanceid and real OpenStack instanceid). The current way to fix this is to delete node from Kubernetes API and restart OpenStack instance.
old format: `<ig name>-<index>-<clustername>`
new format: `<ig name>-<6 chars random hash>`
tested with following cases:
- create new cluster `calc.k8s.local`
```
% kubectl get nodes
NAME                   STATUS   ROLES    AGE     VERSION
master-zone-1-kivf21 …
```
> [OpenStack] Use new hash format in instance names

- Makefile
- tests/e2e/go.mod
- tests/e2e/go.sum
- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/kubetest2-kops/deployer/create.go
- tests/e2e/kubetest2-kops/deployer/deployer.go
- tests/e2e/kubetest2-kops/deployer/replace.go
- tests/e2e/kubetest2-kops/deployer/template.go
- tests/e2e/kubetest2-kops/deployer/up.go
- tests/e2e/templates/simple.yaml.tmpl
This adds support for defining manifest templates used in e2e tests, allowing us to test more specific configurations not exposed through `create cluster` cli flags. I'm envision using this for testing ACM certificates on the API NLB, additional cilium configurations, mixed instances policies, etc.
I'm updating the test-e2e make target as I go to make the presubmit job use it but soon I'll work on how we'll actually configure and invoke kubetest2 from our variety of jobs.
Specifically how we'll access these kubetest2 binaries and other static files like the upgrade scenario script or these template files, including using the appropriate kubetest2-kops version for testing on release branches.
1. Have the periodic jobs include [extra_refs](https://github.com/kubernetes/test-infra/blob/master …
> kubetest2 - Add manifest template support

- channels/alpha
Updating Kubernetes versions with today's releases:
- https://github.com/kubernetes/kubernetes/releases/tag/v1.17.17
- https://github.com/kubernetes/kubernetes/releases/tag/v1.18.15
- https://github.com/kubernetes/kubernetes/releases/tag/v1.19.7
Also, I noticed that we're still pointing to kOps 1.19-alpha1 while there's already a beta3 version out, so figured we should also bump that one, jic.
- https://github.com/kubernetes/kops/releases/tag/v1.19.0-beta.3
> Updates to Alpha versions - k8s & kOps

- cloudbuild.yaml
Presubmits jobs are failing because of missing Bazel 3.4.1 from #10550:
https://testgrid.k8s.io/kops-misc#kops-postsubmit-push-to-staging
There is no `bazelbuild` image for that, so experimenting with `kubekins-e2e` image that is used in presubmit jobs.
> Use Bazel 3.4.1 for postsubmit jobs

- Makefile
- tests/e2e/e2e.mk
- tests/e2e/go.mod
- tests/e2e/go.sum
This will help avoid cluttering up the main Makefile even further. I'm imagining we could put all our variants, perhaps even grid combinations (k8s version + distro + networking + cloud). That should greatly simplify the periodic job definitions.
Using GOOS and GOARCH for running the kops binary
Also try deploying and testing against k8s 1.20.2. ~I'm not optimistic based on previous runs but we'll see how it goes this time. I may end up reverting back to 1.19 until we can figure out whats causing the failures.~
> Give kubetest2 its own makefile

- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/kubetest2-kops/deployer/up.go
- tests/e2e/kubetest2-kops/do/zones.go
Initial work for adding e2e tests for DO.
Tested locally and it seems to work fine after adding the below command arguments.
` go run kubetest2-kops/main.go --up --cloud-provider digitalocean --cluster-name test.myclustername.com \
--env KOPS_STATE_STORE=do://***-kops-space \
--env DIGITALOCEAN_ACCESS_TOKEN=bd5f*****472dae3 \
--env S3_ENDPOINT=sfo2.digitaloceanspaces.com \
--env S3_ACCESS_KEY_ID=PPO******NSRW \
--env S3_SECRET_ACCESS_KEY=rm******oIc \
--kops-binary-path /home/kops \
--ssh-public-key ~/.ssh/id_rsa.pub \
--kubernetes-version 1.19.2`
I'll separately work with @timoreimann and @rifelpet to include the necessary environment variables.
> [DigitalOcean] add e2e tests

- upup/pkg/fi/files.go
By creating a tempfile and then moving the file into place, we both
write more atomically and we can overwrite in-use files.
Issue #10122
> Allow nodeup (and others) to replace in-use files

- pkg/flagbuilder/build_flags.go
We still run nodeup at V=8, so the distinction between V=10 and V=8
matters.
This message really is just development logging, so downgrade to V=10.
> Dial-down logging on flagbuilder

- Makefile
Adding the e2e.mk file changed the default target for `make`
This reverts the behavior back to the original `kops-install`
> Fix default make target

- upup/pkg/fi/cloudup/awstasks/ebsvolume.go
Until https://github.com/hashicorp/terraform-provider-aws/pull/16517 is merged, TF will not be able to use the `throughput` arg for `aws_ebs_volume`.
> Allow setting gp3 for terraform volumes without setting throughput

- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml
This configuration file means users don't have to pass the endpoint
to run crictl.
> containerd: Add /etc/crictl config to enable crictl

- cmd/kops/integration_test.go
- tests/integration/update_cluster/minimal-gp3/cloudformation.json
- tests/integration/update_cluster/minimal-gp3/cloudformation.json.extracted.yaml
- tests/integration/update_cluster/minimal-gp3/in-v1alpha2.yaml
- tests/integration/update_cluster/minimal-gp3/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/ebsvolume.go
#10565 makes it possible to add the gp3 test for CF.
Also, changing the etcd volumes to gp3, with small hack to make it work with Terraform until support for `throughput` is added:
https://github.com/hashicorp/terraform-provider-aws/pull/16517
> Add CF integration test for gp3 volumes

- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/containerd_test.go
- nodeup/pkg/model/tests/containerdbuilder/flatcar/cluster.yaml
- nodeup/pkg/model/tests/containerdbuilder/flatcar/tasks.yaml
Cherry pick of #10540 on release-1.19.
#10540: Add containerd config file to Flatcar based instances
> Automated cherry pick of #10540: Add containerd config file to Flatcar based instances

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/cluster.go
- pkg/apis/kops/v1alpha2/cluster.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- upup/models/bindata.go
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.12.yaml.template
Similar to how we can configure coreDNS image we will like to configure
cluster Proportional autoscaler so we can use our internal docker
registry rather than gcr.io.
> Make cluster proportional autoscaler image configurable.

- docs/addons.md
- docs/contributing/homebrew.md
- docs/contributing/testing.md
- docs/examples/coreos-kops-tests-multimaster.md
- docs/networking/aws-vpc.md
- docs/networking/cilium.md
- docs/state.md
- docs/tutorial/working-with-instancegroups.md
> Fix minor docs typos

- pkg/apis/kops/validation/cluster.go
- pkg/apis/kops/validation/instancegroup.go
Users can now set labels such as `Name` on all resources kOps creates. This breaks consequtive runs of `kops update cluster` as kOps cannot find its resources.
Fixes #10596
> Validate cluster cloud labels

- .gitignore
After executing the Terraform v0.14 integration tests, ensure `.terraform.lock.hcl` files are excluded (ignored) from being added to the Git repositiory.
> Exclude terraform.lock.hcl files from Git repo

- tests/e2e/scenarios/upgrade/run-test
Also use version markers rather than hard-coded patch versions
Also dropping the --kubenretes-version requirement for kubetest2-kops --test because it is never used. Initially I was thinking we could use it to determine the e2e.test version to pull down but the ginkgo tester has its own --test-package-* flags for that. Perhaps in the future we can consolidate them into just the --kubernetes-version flag
Hoping to fix this periodic job: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-misc-upgrade/1351188585260257280
```
Error: missing required --kubernetes-version flag
```
> Provide required --kubernetes-version flags to kubetest2-kops --up

- tests/e2e/e2e.mk
- tests/e2e/go.mod
- tests/e2e/go.sum
- tests/e2e/kubetest2-kops/deployer/build.go
- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/kubetest2-kops/deployer/deployer.go
- tests/e2e/kubetest2-kops/deployer/up.go
- tests/e2e/pkg/kops/download.go
- tests/e2e/pkg/util/http.go
- tests/e2e/pkg/util/publicip.go
- tests/e2e/scenarios/upgrade/run-test
- tests/e2e/templates/simple.yaml.tmpl
switch to using version markers for the simple aws kubetest2 job
only require --kubernetes-version for --up rather than --up or --test
> Kubetest - add networking support + misc fixes

- permalinks/terraform_renamed.md
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/ebsvolume.go
- upup/pkg/fi/cloudup/new_cluster.go
- upup/pkg/fi/executor.go
- upup/pkg/fi/task.go
Terraform 0.12 broke compatability and this could result in data loss
if we deleted the etcd volumes.  Document the procedure to fix the
tfstate, and require an env var to be passed to avoid accidental data
loss.
> Require KOPS_TERRAFORM_0_12_RENAMED, to guard against tf breakage

- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/kubetest2-kops/deployer/up.go
- tests/e2e/scenarios/upgrade/run-test
fixing https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-misc-upgrade/1351734337896189952#1:build-log.txt%3A929
Also moving some ssh key flag default lookups to happen for all kubetest2-kops commands rather than only ones specifying --up. this should fix the error a few lines below that ^^ `error reading private key "": open : no such file or directory`
> Use kops binary built by kubetest2-kops in upgrade script

- tests/e2e/scenarios/upgrade/run-test
another attempt at fixing https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-misc-upgrade/1351855654456791040
> kubetest2 upgrade script - PATH needs to be a directory

- k8s/crds/kops.k8s.io_clusters.yaml
- k8s/crds/kops.k8s.io_instancegroups.yaml
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
- pkg/apis/kops/v1alpha2/zz_generated.conversion.go
- pkg/apis/kops/v1alpha2/zz_generated.deepcopy.go
- pkg/apis/kops/zz_generated.deepcopy.go
Adding log rotation and log retention options for containerd:
xRef: https://github.com/kubernetes/kubernetes/pull/59898
Kubelet defaults:
```go
if obj.ContainerLogMaxSize == "" {
obj.ContainerLogMaxSize = "10Mi"
}
if obj.ContainerLogMaxFiles == nil {
obj.ContainerLogMaxFiles = utilpointer.Int32Ptr(5)
}
```
> Add support for container-log-max-size/files with kubelet

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
Increase the CoreDNS default ttl to be inline with kubernetes upstream https://github.com/kubernetes/kubernetes/pull/76238 and the previous kube-dns ttl.
We switching from kube-dns to CoreDNS, we noticed a visible bump in coredns-nodelocal request duration and an increase in cache misses.
This change should make the switch less impactful for others.
> Increase CoreDNS default ttl

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template
Cherry pick of #10610 on release-1.19.
#10610: Increase CoreDNS default ttl
> Automated cherry pick of #10610: Increase CoreDNS default ttl

- cmd/kops/create_cluster.go
- permalinks/terraform_renamed.md
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/ebsvolume.go
- upup/pkg/fi/executor.go
- upup/pkg/fi/task.go
Cherry pick of #10602 on release-1.18.
#10602: Require KOPS_TERRAFORM_0_12_RENAMED, to guard against tf
> Automated cherry pick of #10602: Require KOPS_TERRAFORM_0_12_RENAMED, to guard against tf

- tests/e2e/e2e.mk
- tests/e2e/go.mod
- tests/e2e/go.sum
- tests/e2e/kubetest2-kops/deployer/up.go
- tests/e2e/pkg/version/kubernetes.go
This way we can provide a marker url (like in e2e.mk) rather than hard-coding patch versions.
> kubetest2 - Add support for specifying a kubernetes version marker file

- tests/e2e/pkg/version/kubernetes.go
it turns out semver strings parse as URLs, so try parsing values as a semver first before falling back to URL.
See https://play.golang.org/p/ta_6cUzd8eH
fixes https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-misc-upgrade/1352098187967467520#1:build-log.txt%3A361
> kubetest 2 - fix parsing of k8s version semver values

- nodeup/pkg/model/protokube.go
> Install dbus if needed for protokube with containerd

- nodeup/pkg/model/protokube.go
Cherry pick of #10583 on release-1.19.
#10583: Install dbus if needed for protokube with kope.io
> Automated cherry pick of #10583: Install dbus if needed for protokube with kope.io

- tests/e2e/scenarios/upgrade/run-test
Due to https://github.com/projectcalico/calico/issues/3751, Calico needs longer interval for validating masters.
> kubetest2 - increase validation timeout for the upgrade scenario

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awscloudcontroller/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/awsiamauthenticator/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/simple/manifest.yaml
- upup/pkg/fi/cloudup/tests/bootstrapchannelbuilder/weave/manifest.yaml
This should reduce considerably the issues during rolling update when https://github.com/projectcalico/calico/issues/3751 is hit, until next version of Calico is released.
> Add startup probe for calico-kube-controllers

- pkg/model/spotinstmodel/instance_group.go
This PR fixes the regression introduced by #9699 ([reported](https://github.com/kubernetes/kops/pull/9699/files#r562026418) by @povils): renaming the instance group results in nodeup failing to start with the following errors:
```
$ journalctl --no-pager -o cat -u kops-configuration
Starting Run kops bootstrap (nodeup)...
nodeup version 1.20.0-alpha.1
I0121 17:47:52.707955    1846 s3context.go:213] found bucket in region "us-west-2"
I0121 17:47:52.708041    1846 s3fs.go:290] Reading file "s3://<CONFIG_BASE>/cluster.spec"
I0121 17:47:52.742606    1846 s3fs.go:290] Reading file "s3://<CONFIG_BASE>/instancegroup/nodes.<CLUSTER_NAME>"
W0121 17:47:52.750671    1846 main.go:133] got error running nodeup (will retry in 30s): error loading InstanceGroup …
```
> Spotinst: Avoid unnecessary duplication of tasks

- k8s/crds/kops.k8s.io_clusters.yaml
- pkg/apis/kops/networking.go
- pkg/apis/kops/v1alpha2/networking.go
`components/cilium.go` sets this to true if nil
> enableRemoteNodeIdentity actually defaults to true

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Upstream changes:
* Release notes for 3.0.20201209
* Handling hanging list command from etcd client during reconciliation loop
* Update dependencies to match kOps 1.19
* Include IPs in peer certificates
* Use etcd v3.4.13 in tests
* Eager-broadcast leadership on every leader iteration
* Update Go to 1.15.7
> etcd-manager: Update to 3.0.20210122

- channels/alpha
- channels/stable
[This](https://github.com/kubernetes/kops/pull/10576) PR was merged 9 days ago to alpha, so seems pretty safe to push to stable.
Also, a new Ubuntu ami version was made available two days ago globally (including CN and GOV clouds), so updating alpha channel with that.
https://cloud-images.ubuntu.com/locator/ec2/
> Update k8s versions in stable channel and bump ubuntu ami version in alpha channel

- pkg/model/components/etcd.go
- pkg/model/components/etcdmanager/model.go
- pkg/model/components/etcdmanager/tests/minimal/tasks.yaml
- pkg/model/components/etcdmanager/tests/old_versions_mount_hosts/tasks.yaml
- pkg/model/components/etcdmanager/tests/overwrite_settings/tasks.yaml
- pkg/model/components/etcdmanager/tests/proxy/tasks.yaml
Cherry pick of #10638 on release-1.19.
#10638: etcd-manager: Update to 3.0.20210122
> Automated cherry pick of #10638: etcd-manager: Update to 3.0.20210122

- tests/e2e/go.mod
- tests/e2e/go.sum
This picks up the --test-package-marker support used by the kops grid jobs.
See https://github.com/kubernetes-sigs/kubetest2/compare/4275dd0a0d63...43699a7ba223
> Update kubetest2 library

- docs/getting_started/azure.md
- upup/pkg/fi/cloudup/azure/BUILD.bazel
- upup/pkg/fi/cloudup/azure/azure_cloud.go
- upup/pkg/fi/cloudup/azure/networkinterface.go
- upup/pkg/fi/cloudup/azuretasks/testing.go
Fix:
- Updates azure getting started doc to instruct correct feature flag value
Feature:
- Creates azureup network interfaces client with List method
Update:
- Uses vmScaleSet client and new network interfaces client to get masters ip for api ingress status
> feat: implement azure get api ingress status fn

- tests/e2e/pkg/tester/kubectl.go
When a package marker is provided to the tester, we should use it for downloading the correct kubectl version in addition to the e2e binary version. Copies the logic [here](https://github.com/kubernetes-sigs/kubetest2/pull/83/files#diff-f88766cb5eca5518cdcb44058bd793584616c8ca38227bf0103b7ebfad0ef610).
> Use the same package marker for kubectl as for e2e binary

- cmd/kops/BUILD.bazel
- cmd/kops/create_cluster.go
- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml
- pkg/apis/kops/validation/validation.go
- pkg/model/components/containerd.go
> Add back support for kubenet style networking with containerd

- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/kubetest2-kops/deployer/deployer.go
- tests/e2e/kubetest2-kops/deployer/up.go
This allows us to customize the images, instance types, etc.
kubetest (1) named this --kops-args, I think --create-args is more appropriate because its only passed to `create cluster`
https://github.com/kubernetes/test-infra/blob/f503f3e9a230d5eab64c220c8a9e4380bb6a65db/config/jobs/kubernetes/kops/kops-periodics-misc.yaml#L27
Also support --env=KOPS_FEATURE_FLAGS=foo and having its value correctly passed to the kops invocations.
> Add --create-args kubetest2 flag

- pkg/model/awsmodel/autoscalinggroup.go
- tests/integration/update_cluster/externallb/cloudformation.json
- tests/integration/update_cluster/externallb/in-v1alpha2.yaml
- tests/integration/update_cluster/externallb/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/classic_load_balancer.go
Similar to https://github.com/kubernetes/kops/pull/10335
Fixes: https://github.com/kubernetes/kops/issues/10664
/cc @rifelpet @rdrgmnzs
> Allow attaching same external load balancer to multiple instance groups

- pkg/model/awsmodel/autoscalinggroup.go
- tests/integration/update_cluster/externallb/cloudformation.json
- tests/integration/update_cluster/externallb/in-v1alpha2.yaml
- tests/integration/update_cluster/externallb/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
- upup/pkg/fi/cloudup/awstasks/classic_load_balancer.go
Cherry pick of #10666 on release-1.19.
#10666: Allow attaching same external load balancer to multiple
> Automated cherry pick of #10666: Allow attaching same external load balancer to multiple

- docs/contributing/testing.md
Update the kops e2e testing docs to use the latest Kubernetes `kubetest2` test framework.
> Update kops e2e testing docs

- upup/pkg/fi/cloudup/new_cluster.go
Fixes #10648 
Generate a default load balancer when the SSL certificate is specified, so that the original process would work well.
> Create default loadbalancer when SSL certificate is specified

- upup/pkg/fi/cloudup/spotinsttasks/ocean.go
This field isn't being set anywhere and is causing problems with the terraform HCL2 serialization.
If we do end up setting it we can redefine the struct type ourselves with the necessary field tags.
Fixes #10671
/cc @liranp
> Remove taints from spotinst ocean terraform resource

- cmd/kops/toolbox_dump.go
- docs/cli/kops_toolbox_dump.md
Allows us to use `toolbox dump` on other distros besides ubuntu.
I'd like this to be cherry-picked to release-1.19 (no need to block on 1.19.0 though) so that I can use this in kubetest2 and have kubetest2 be able to dump logs with kops 1.19 builds.
> Allow SSH user to be overridden for `toolbox dump`

- cmd/kops/toolbox_dump.go
- docs/cli/kops_toolbox_dump.md
Cherry pick of #10675 on release-1.19.
#10675: Allow SSH user to be overridden for `toolbox dump`
> Automated cherry pick of #10675: Allow SSH user to be overridden for `toolbox dump`

- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/kubetest2-kops/deployer/deployer.go
- tests/e2e/kubetest2-kops/deployer/dumplogs.go
Requires https://github.com/kubernetes/kops/pull/10675
This does not need to be cherry-picked.
This wires in kubetest2-kops' `--ssh-user` flag to `kops toolbox dump`, defaulting to the value [recognized by the e2e suite](https://github.com/kubernetes/kubernetes/blob/943b1dbf53c405004f35090ccef0dcf3c8065b7a/test/e2e/framework/ssh/ssh.go#L172-L174) and [set in the prow jobs](https://github.com/kubernetes/test-infra/blob/9fc10910eea6910d1763c624ea608cdd26f34ccf/config/jobs/kubernetes/kops/build-grid.py#L105-L106). The kubetest2 flag was previously unused.
> kubetest2 - Use --ssh-user to dump logs

- docs/addons.md
- docs/cluster_spec.md
Also the misplaced cluster-autoscaler docs
> Fix header indentation in addons.md

- docs/iam_roles.md
AWS IAM resource ID's were in an incorrect format.
> Documentation update: Corrected externalPolicy AWS ARN formatting

- tests/integration/create_cluster/complex/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
- tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
- tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
- upup/pkg/fi/cloudup/new_cluster.go
Non-hostNetworking fails to talk to the instance metadata otherwise. Breaking e.g CSI controller
See https://github.com/kubernetes/cloud-provider-aws/issues/169
Note: This should work for kubenet, but other CNIs may need other hop limits. E.g with Cilium, I had to use 3 to get this to work. Will have to investigate a bit more first. Meanwhile this should fix the broken test.
> Increase IMDSv2 hop limit on control plane nodes

- docs/contributing/testing.md
- tests/e2e/kubetest2-kops/deployer/common.go
- tests/e2e/kubetest2-kops/deployer/deployer.go
- tests/e2e/kubetest2-kops/deployer/up.go
- tests/e2e/kubetest2-kops/deployer/up_test.go
This allows kubetest's --create-args to take precedence over arguments we were otherwise hardcoding.
Specifically this will be used to hardcode the list of zones for some prow jobs with `--create-args="--zones us-east-1a"` ([example job still on kubetest 1](https://github.com/kubernetes/test-infra/blob/e048fc0aecd929d056ecca442a28dbc3fae8b084/config/jobs/kubernetes/kops/kops-periodics-misc.yaml#L68))
Also removing the --networking flag now that we have `--create-args` and jobs have been migrated to use it in https://github.com/kubernetes/test-infra/pull/20683
> Kubetest2 - refactor how `kops create cluster` arguments are set

- tests/e2e/scenarios/upgrade/run-test
fixes this failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-misc-upgrade/1356573350847057920
> Fix create args for upgrade test

- docs/operations/service_account_token_volumes.md
Seems that after merging https://github.com/kubernetes/kops/pull/9534 there is no need to specify paths for key-files for service Account Token Volume Projection. 
Instead, the current configuration proposed in docs is making Istio unable to verify JWT token with errors.
In this commit, we remove the paths, letting Kops handles the default ones that are working as expected.
> Docs: Fix ServiceAccountVolume proposed configuration for Istio

- tests/e2e/scenarios/upgrade/run-test
We'll look into these failures separately but for now we just want to get to the upgrade process
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-misc-upgrade/1356634006895988736
> Update the skipped tests in the upgrade job to help the test stage pass

- docs/contributing/how_it_works.md
Update out of date code reference links in the [how it works](https://kops.sigs.k8s.io/contributing/how_it_works/) doc. These out of date links had me confused a bit while reading the docs.
> Update code reference links in docs

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
This might break upgrade if cluster spec have `prometheusMetricsEnabled: true`. I have validated this by upgrading our cluster. This is caused by #10414
> Fix rendering issue created by #10414

- upup/pkg/fi/cloudup/awstasks/dnsname.go
ref: https://github.com/kubernetes/kops/issues/10717
specifically the panic logged [here](https://github.com/kubernetes/kops/issues/10717#issuecomment-772433770)
This should be cherry-picked to 1.19.
> Fix panic when exporting kubecfg for AWS cluster without load balancer

- upup/pkg/fi/cloudup/awstasks/dnsname.go
Cherry pick of #10720 on release-1.19.
#10720: Fix panic when exporting kubecfg for AWS cluster without load
> Automated cherry pick of #10720: Fix panic when exporting kubecfg for AWS cluster without load

- pkg/resources/aws/aws.go
ref: #10709
For k8s 1.19 kops-controller has a DNS record:
https://github.com/kubernetes/kops/blob/1885ccee1730d6b6b6326f5bdfaaf02cac19e74a/upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template#L39
but we dont clean it up during `kops delete cluster`. This ensures the record is deleted.
This should be cherry-picked to 1.19
> Cleanup kops-controller Route53 record during cluster deletion

- docs/releases/1.20-NOTES.md
- tests/integration/create_cluster/complex/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_encrypt/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zone/expected-v1alpha2.yaml
- tests/integration/create_cluster/ha_shared_zones/expected-v1alpha2.yaml
- tests/integration/create_cluster/ingwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.18/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.19/expected-v1alpha2.yaml
- tests/integration/create_cluster/minimal-1.20/expected-v1alpha2.yaml
- tests/integration/create_cluster/ngwspecified/expected-v1alpha2.yaml
- tests/integration/create_cluster/overrides/expected-v1alpha2.yaml
- tests/integration/create_cluster/private/expected-v1alpha2.yaml
- tests/integration/create_cluster/private_shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_subnets_vpc_lookup/expected-v1alpha2.yaml
- tests/integration/create_cluster/shared_vpc/expected-v1alpha2.yaml
- upup/pkg/fi/cloudup/new_cluster.go
It has caused some issues with various CNIs, so we need to wait until 1.21 until we can consider this one again.
> Revert making imdsv2 default

- pkg/resources/aws/aws.go
Cherry pick of #10721 on release-1.19.
#10721: Cleanup kops-controller Route53 record during cluster
> Automated cherry pick of #10721: Cleanup kops-controller Route53 record during cluster

- cmd/kops/create_cluster.go
- pkg/commands/set_cluster.go
- pkg/commands/set_cluster_test.go
- pkg/commands/set_instancegroups.go
- util/pkg/reflectutils/access.go
- util/pkg/reflectutils/access_test.go
Currently, when using kops set cluster <cluster_name> <path>=<value>, if the path is not present it fails silently. eg: 
`kops set cluster test-cluster.k8s.local spec.abc.def.ghi=jkl ` will not throw any error despite the fields not being present in the kops.Cluster struct. This can lead to confusion and mistakes. 
This PR explicitly throws an error if a field being set using `kops set` does not exist in the associated struct. 
Fixes: https://github.com/kubernetes/kops/issues/10647
Depends on: https://github.com/kubernetes/kops/pull/10690
> Throw error if path being set by kops set is not present in struct

- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
refs: #10718 
When user changes only mixedInstancePolicy, LaunchTemplateId is not changed. 
But current logic expect changes to LaunchTemplateId; therefore nil pointer dereference has occur.
In this case, it is not necessary to change LaunchTemplateId in AutoScalingGroup, so I fixed it.
---
I don't know the reason for this logic. If anyone knows why, please tell me.
> Use expected LaunchTemplateId in updating ASG when MixedInstancePolicy is changed

- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Cherry pick of #10742 on release-1.19.
#10742: Use expected LaunchTemplateId in updating ASG when
> Automated cherry pick of #10742: Use expected LaunchTemplateId in updating ASG when

- pkg/apis/kops/validation/validation.go
- upup/pkg/fi/cloudup/alitasks/rampolicy.go
- upup/pkg/fi/cloudup/gcetasks/subnet.go
all issues reported by [goreportcard](https://goreportcard.com/report/k8s.io/kops#ineffassign)
> Fix ineffassign issues

- upup/pkg/fi/cloudup/spotinsttasks/ocean.go
Cherry pick of #10674 on release-1.19.
#10674: Remove taints from spotinst ocean terraform resource
> Automated cherry pick of #10674: Remove taints from spotinst ocean terraform resource

- docs/releases/1.20-NOTES.md
- upup/pkg/fi/cloudup/apply_cluster.go
We no longer have any contributors to this cloud provider.
Example of issues we may be facing in near future is that the implementation is currently largely based on the unofficial github.com/denverdino/aliyungo instead of github.com/aliyun/alibaba-cloud-sdk-go 
Hopefully this prompts someone to step up rather than that we have to punt it.
/milestone v1.20
> Deprecate aliyun

- docs/operations/cluster_template.md
On master, `make build-docs` is failing with the following error message. 
```
**UndefinedError**: 'ChannelRecommendedImage' is undefined
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/macros/plugin.py", line 263, in render
return md_template.render(**self.variables)
File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
self.environment.handle_exception()
File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File "/usr/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
raise value.with_traceback(tb)
File "<template>", line 19, in top-level template code
File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 471, in …
```
> Fix docs build failure

- pkg/model/awsmodel/autoscalinggroup.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Fixes #10715
Partially reverts https://github.com/kubernetes/kops/pull/10666
This way we end up with one CLB task per CLB regardless of how many ASGs it is attached to. Less brittle than creating many CLB tasks with concatenated names and exceptions for known CLBs.
The `Name` -> `LoadBalancerName` shouldn't make a functional difference, just improving consistency with how we attach CLBs to ASGs being created vs updated.
> Use EnsureTask instead of prepending IG names to external ELB tasks

- pkg/model/awsmodel/autoscalinggroup.go
- tests/integration/update_cluster/complex/cloudformation.json
- tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml
- tests/integration/update_cluster/complex/in-v1alpha2.yaml
- tests/integration/update_cluster/complex/kubernetes.tf
- upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
Cherry pick of #10754 on release-1.19.
#10754: Use EnsureTask instead of prepending IG names to external
> Automated cherry pick of #10754: Use EnsureTask instead of prepending IG names to external

- upup/pkg/fi/BUILD.bazel
- upup/pkg/fi/files.go
- upup/pkg/fi/files_owner.go
- upup/pkg/fi/files_owner_windows.go
- upup/pkg/fi/files_test.go
- upup/pkg/fi/nodeup/nodetasks/file.go
- upup/pkg/fi/nodeup/nodetasks/service.go
Otherwise we had an issue where the file existed with the correct
owner/group; when we rewrote it we set the owner/group to root/root;
but we then didn't set the owner/group if they were previously
correct.
Was visible in the flatcar test results.
> nodeup file: Set owner & group when we write the file.

- upup/pkg/fi/BUILD.bazel
- upup/pkg/fi/files.go
- upup/pkg/fi/files_owner.go
- upup/pkg/fi/files_owner_windows.go
- upup/pkg/fi/files_test.go
- upup/pkg/fi/nodeup/nodetasks/file.go
- upup/pkg/fi/nodeup/nodetasks/service.go
Cherry pick of #10757 on release-1.19.
#10757: nodeup file: Set owner & group when we write the file.
> Automated cherry pick of #10757: nodeup file: Set owner & group when we write the file.

- nodeup/pkg/model/kops_controller.go
- nodeup/pkg/model/tests/golden/minimal/tasks-kops-controller.yaml
Cherry pick of #10758 on release-1.19.
#10758: Always generate kops-controller certs
> Automated cherry pick of #10758: Always generate kops-controller certs

- nodeup/pkg/model/kops_controller.go
- nodeup/pkg/model/tests/golden/minimal/tasks-kops-controller.yaml
This is a quick simple fix, but can be easily be reverted and a better one added later.
Fixes: #10704
> Always generate kops-controller certs

- upup/pkg/fi/cloud.go
- upup/pkg/fi/cloudup/new_cluster.go
This PR essentially does 2 things. It updates the GCE zones and it refactors the error message thrown if the cloud provider is not inferred from the zones. 
I didn't bother making 2 seperate PRs as the changes are very small. Please do let me know if we would want to make 2 seperate PRs for this. Will do so.
Fixes: https://github.com/kubernetes/kops/issues/10738
> Update GCE zones

- tests/e2e/go.mod
- tests/e2e/go.sum
- tests/e2e/kubetest2-kops/deployer/up.go
This way any spaces within a quoted value wont cause the value to be broken up into multiple arguments.
The CentOS image in AWS has spaces in its name which is what exposed this issue.
Using this library: https://github.com/google/shlex/blob/master/shlex.go
xref: https://github.com/kubernetes/test-infra/pull/20799
Fixes https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-distro-imagecentos7/1358877320022069248
> Kubetest2 - Use a shell lexer for passing extra args to `create cluster`

- docs/cluster_spec.md
- k8s/crds/kops.k8s.io_clusters.yaml
- nodeup/pkg/model/kube_apiserver.go
- nodeup/pkg/model/kube_apiserver_test.go
- pkg/apis/kops/componentconfig.go
- pkg/apis/kops/v1alpha2/componentconfig.go
Hello!
We have a usecase that would need to be able to specify a different client-CA file for the kube-apiserver. Also, it seems that there were prior discussion about this requirement too(https://github.com/kubernetes/kops/issues/3243), although it was closed for inactivity.
This change just enables the ClientCAFile field of the KubeAPIServerConfig struct, So that the user can specify the ClientCAFile and the apiserver config yaml would reflect it.
Thanks a lot!
> Use the kubeApiServerConfig clientCAFile field

- tests/e2e/kubetest2-kops/deployer/up.go
apparently our presubmits don't validate the e2e go submodule. I'll work on fixing that.
`kubetest2-kops/deployer/up.go:97:34: multiple-value shlex.Split() in single-value context `
> Kubetest2 - Fix splitting of --create-args

- upup/pkg/fi/cloudup/dns.go
We want to communicate what we're doing, but the log message is confusing.
> Logging: don't suggest we are pre-creating DNS records unless we are

- upup/pkg/fi/assettasks/docker_api.go
Otherwise `kops update cluster --name XYZ --yes --phase assets` fails with:
```
panic: assignment to entry in nil map
goroutine 216 [running]:
k8s.io/kops/vendor/github.com/docker/docker/api/types/filters.Args.Add(...)
vendor/github.com/docker/docker/api/types/filters/parse.go:133
k8s.io/kops/upup/pkg/fi/assettasks.(*dockerAPI).findImage(0x4000186128, 0x362192f, 0x14, 0x0, 0x0, 0x22)
upup/pkg/fi/assettasks/docker_api.go:65 +0x2fc
k8s.io/kops/upup/pkg/fi/assettasks.(*CopyDockerImage).Render(0x4001204fc0, 0x4001292d20, 0x0, 0x4001204fc0, 0x4000a1a140, 0x0, 0x0)
upup/pkg/fi/assettasks/copydockerimage.go:136 +0x1f4
```
Ideally this would be test covered, but it seems it wasn't before so I'm not sure how to test this.
This seems to have been introduced in …
> fix: asset task copy docker image

- upup/pkg/fi/assettasks/docker_api.go
Cherry pick of #10767 on release-1.19.
#10767: fix: asset task copy docker image
> Automated cherry pick of #10767: fix: asset task copy docker image

- docs/getting_started/kubectl.md
I've lost a bit of time trying to generate the config for connection to a k8s cluster, since I didn't notice there is a new mandatory flag with kops 1.19.
I think mentioning in the documentation can save from some headcache, and avoiding issues as #10723
> Update kubectl documentation with new flags

- cloudmock/aws/mockautoscaling/group.go
- cloudmock/aws/mockec2/launch_templates.go
- cmd/kops/BUILD.bazel
- cmd/kops/lifecycle_integration_test.go
- tests/integration/update_cluster/complex/cluster.overrides.txt
- tests/integration/update_cluster/complex/instancegroup.nodes.overrides.txt
This allows specific changes to be tested on an existing cluster during an `update cluster --yes` and ensuring a subsequent `update cluster` dryrun correctly reports no changes.
To specify changes, create a `cluster.overrides.txt` or `instancegroup.<name>.overrides.txt` file in the update_cluster integration test's directory as demonstrated here.
Each line is a field=value format, each batch of changes is separated by a `---` line.
Each batch will be ran through `update cluster --yes` on its own.
In particular, reverting https://github.com/kubernetes/kops/pull/10742 correctly caused a panic, so these tests are now capable of exposing those types of bugs.
> Add overrides testing in lifecycle integration tests

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #10787 on release-1.20.
#10787: Update Calico to v3.17.2
> Automated cherry pick of #10787: Update Calico to v3.17.2

- pkg/model/components/kubecontrollermanager.go
- pkg/model/components/kubelet.go
CSIMigrationAWSComplete feature gate does not work unless also CSIMigrationAWS is enabled
per https://github.com/kubernetes/kops/issues/10777#issuecomment-776537706 we need to enable an additional feature gate to disable the in-tree EBS plugin
> Enable CSIMigrationAWS if CSI EBS driver is installed

- pkg/model/components/kubecontrollermanager.go
- pkg/model/components/kubelet.go
Cherry pick of #10791 on release-1.20.
#10791: CSIMigrationAWSComplete feature gate does not work unless
> Automated cherry pick of #10791: CSIMigrationAWSComplete feature gate does not work unless

- pkg/testutils/BUILD.bazel
- pkg/testutils/integrationtestharness.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/template_functions.go
refs: #10719 
The role names are checked in node bootstrap. If profile names are provided, bootstrap will fail. Because profile name and role name do not always mactch in AWS IAM. So I fixed `nodesRoles` in kops-controller-config to store IAM Role names associated with specified IAM Instance Profile.
I think that this should be cherry-picked to 1.19.
> Fill Role names in kops-controller-config instead of instance profile names when it is specified

- pkg/testutils/BUILD.bazel
- pkg/testutils/integrationtestharness.go
- upup/pkg/fi/cloudup/apply_cluster.go
- upup/pkg/fi/cloudup/awsup/aws_cloud.go
- upup/pkg/fi/cloudup/bootstrapchannelbuilder_test.go
- upup/pkg/fi/cloudup/template_functions.go
Cherry pick of #10728 on release-1.20.
#10728: Fill Role names in kops-controller-config instead of instance
> Automated cherry pick of #10728: Fill Role names in kops-controller-config instead of instance

- tests/e2e/kubetest2-kops/deployer/dumplogs.go
`kubectl cluster-info dump` will dump all etcd data into the provided directory organized by namespace. I'm hoping this will assist with troubleshooting our timeout issues once we add timeout support to kubetest2 so that we can invoke this shutdown process after the tests timeout.
> kubetest2 - Dump all pod logs in addition to host logs

- upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
Cherry pick of #10806 on release-1.20.
#10806: Fix LaunchSpec TF output
> Automated cherry pick of #10806: Fix LaunchSpec TF output

- docs/releases/1.19-NOTES.md
- docs/releases/1.20-NOTES.md
As discussed in office hours, we will be working on deprecating launch configurations in favour of launch templates. Add the deprecation notice to the release notes of the 1.19 and 1.20 release.
> Add deprecation notice for launch templates. 

- pkg/model/azuremodel/vmscaleset.go
- pkg/model/azuremodel/vmscaleset_test.go
Allows us to use our own managed images for virtual machine scale sets and not just ones that are published to the marketplace.
Related to
`Be able to configure some more parameters for VM Scale Set such as Windows` in #10412
Not sure if it's necessary we should check for a 
`/subscriptions/<subscription id>/resourceGroups/<resource group>/providers/<provider>/images/<image>` format
> Allow managed images for Azure instance groups

- pkg/model/azuremodel/vmscaleset.go
- pkg/model/azuremodel/vmscaleset_test.go
Cherry pick of #10797 on release-1.20.
#10797: Allow managed images for Azure instance groups
> Automated cherry pick of #10797: Allow managed images for Azure instance groups

- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml
Configure kubenet in containerd/CNI mode to match upstream configuration.
> kubenet containerd: match upstream

- nodeup/pkg/model/containerd.go
- nodeup/pkg/model/tests/containerdbuilder/simple/tasks.yaml
Cherry pick of #10759 on release-1.20.
#10759: kubenet containerd: match upstream configuration
> Automated cherry pick of #10759: kubenet containerd: match upstream configuration

- nodeup/pkg/model/firewall.go
Otherwise we sometimes get an "in-use" message, telling us to use the
lock, if another iptables process is running concurrently.
> iptables: Use the lock when checking for existing rules

- upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
- upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
- upup/pkg/fi/cloudup/spotinsttasks/ocean.go
- upup/pkg/fi/cloudup/terraform/target_hcl2.go
This PR fixes Terraform output of Ocean resources (refs: #10671, #10674, #10679, #10806).
/cc @rifelpet
/cc @hakman
/cc @alejandroandreu
> Spotinst: Replace corev1.Taint to fix HCL2 serialization

- upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go
- upup/pkg/fi/cloudup/spotinsttasks/launch_spec.go
- upup/pkg/fi/cloudup/spotinsttasks/ocean.go
- upup/pkg/fi/cloudup/terraform/target_hcl2.go
Cherry pick of #10819 on release-1.20.
#10819: fix(spot/ocean): replace corev1.Taint to fix hcl2
> Automated cherry pick of #10819: fix(spot/ocean): replace corev1.Taint to fix hcl2

- upup/models/bindata.go
- upup/models/cloudup/resources/addons/spotinst-kubernetes-cluster-controller.addons.k8s.io/v1.14.0.yaml.template
- upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
Cherry pick of #10820 on release-1.20.
#10820: feat(spot/addon): bump ocean-controller to 1.0.72
> Automated cherry pick of #10820: feat(spot/addon): bump ocean-controller to 1.0.72

- tests/e2e/pkg/tester/tester.go
Execute will reparse the flags; we want to reuse the test execution
but not the flag setup.
> kubetest2: Call Test, not Execute

- cmd/kops/delete_instance.go
Cherry pick of #10825 on release-1.19.
#10825: Fix kdi 'must specify' error
> Automated cherry pick of #10825: Fix kdi 'must specify' error

- pkg/instancegroups/instancegroups.go
Cherry pick of #10328 on release-1.19.
#10328: Don't try to detach masters
> Automated cherry pick of #10328: Don't try to detach masters

- pkg/nodeidentity/azure/BUILD.bazel
- pkg/nodeidentity/azure/identify.go
Fixes first bug mentioned here https://github.com/kubernetes/kops/issues/10412#issuecomment-763880477
`nodeLabels` specified in the InstanceGroup spec weren't being labeled on nodes created in Azure
> Use correct tag when creating node labels from azure cloud tags
